### ISSUE TITLE
Support blame on files outside the workspace repository

### ISSUE THREAD

**Issue by Gama11** [eamodio/vscode-gitlens#1]
This extension seems broken for all files that are outside of the workspace's Git repo. I get errors like this in the developer console:

```
fake:1 fatal: '../../../../../HaxeToolkit/haxe/lib/flixel/git/flixel/FlxObject.hx' is outside repository
```

The absolute path for that is `C:/HaxeToolkit/haxe/lib/flixel/git/flixel/FlxObject.hx`, and that file is in a Git repo, just a different one than the workspace I'm currently in.

The command run seems to be `git blame --porcelain --root -- <file-path>` - probably need to switch the working directory first in these cases?

**Comment by eamodio** [comment]
@Gama11 Thanks for the report. The way it is currently setup this might be tricky to implement, but I'll look into it.

**Comment by Gama11** [comment]
Seems to work nicely now, thanks! :)
