### ISSUE TITLE
Add a terminal link handler for links that look like git commits

### ISSUE THREAD

**Issue by Tyriar** [eamodio/vscode-gitlens#1002]
After setting `terminal.integrated.experimentalLinkProvider`, that enables "word links" which would include git commits like this:

![image](https://user-images.githubusercontent.com/2193314/79503484-1503d600-7fe6-11ea-9563-ab9f834835cf.png)

![image](https://user-images.githubusercontent.com/2193314/79503455-09b0aa80-7fe6-11ea-8aa1-136cf1c4f5ba.png)

Example usage of API to intercept and handle link clicks:

```ts
registerTerminalLinkHandler({
  handleLink(term, link) => {
    if (looksLikeACommit(link)) {
      // Handle
      return true;
    }
    return false;
  }
});
```

**Comment by eamodio** [comment]
Added in GitLens 11
