### ISSUE TITLE
The message shown by gitlens keeps bouncing whenever command button is pressed

### ISSUE THREAD

**Issue by ShashankaNataraj** [eamodio/vscode-gitlens#101]
- GitLens Version:4.1.3
- VSCode Version:Version 1.13.1 (1.13.1)
- OS Version:OSX Sierra

Steps to Reproduce:

1. Mouse over any clickable token in source code
2. Press Command button on mac
3. The message shown by gitlens keeps bouncing whenever command button is pressed

http://recordit.co/4FOgvV3LLJ

**Comment by eamodio** [comment]
@ShashankaNataraj does this happen with code lens not shown by GitLens? This feels like a vscode issue.

**Comment by eamodio** [comment]
Closing this as more info is needed. Please reopen if this is still an issue.
