### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by karlAlnebratt** [eamodio/vscode-gitlens#1011]
- Issue Type: `Performance`
- Extension Name: `gitlens`
- Extension Version: `10.2.1`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.44.2`

[eamodio.gitlens-unresponsive.cpuprofile.txt](https://github.com/eamodio/vscode-gitlens/files/4544328/eamodio.gitlens-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by grantyoung** [comment]
I'm also seeing this with larger repos. It appears that the extension is spinning up multiple Git processes in the background as follows:

```
/usr/local/bin/git -c core.quotepath=false -c color.ui=false -c log.showSignature=false log --format=%x3cr%x3e%x20%H -n2 --follow -L 229,229:<FILE_PATH> -- <FILE_PATH>
```

Each of these git processes on my machine are effectively using up a core of my CPU each on Mac. At most I've sometimes seen up to 7 of them.

**Comment by jvilk-stripe** [comment]
An engineer at my company reported the same issue as @grantyoung, although it was >70 processes. The engineer had their git configured to invoke watchman (`core.fsmonitor`) which may have caused the git processes to run for longer than is usual.

Does gitlens spawn these processes with the expectation that they ~always complete quickly?

**Comment by eamodio** [comment]
GitLens does spawn multiple Git processes depending on the data being requested. And typically those Git calls are relatively fast (but of course that depends on a lot of factors). Although if the same git call is attempted to being run more than once, it will wait for the original git call to return.

If you enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. You can see the timings of all the individual git calls. Also if you see `(waited)` at the end of the line, it means that git call blocked waiting for any identical git call to finish (and it won't actually call out to git again).
