### ISSUE TITLE
No way to do "blame previous revision" via keyboard

### ISSUE THREAD

**Issue by russelldavis** [eamodio/vscode-gitlens#1014]
It would be nice to be able to run it from the Command Pallete, and to be able to assign a keyboard shortcut to it.

**Comment by eamodio** [comment]
So, you want the functionality of the button in the hovers?

**Comment by russelldavis** [comment]
That's right.

**Comment by eamodio** [comment]
Adds  a new _Open Blame Prior to Change_ command (`gitlens.openBlamePriorToChange`).

Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by russelldavis** [comment]
Works perfectly, thank you!

**Comment by evans** [comment]
This is incredible!! We ran Prettier our repo about a year ago and it's been a huge thorn trying to get at the history before that commit. After this change it's a breeze, thank you a thousand times @eamodio for writing the code and @russelldavis for suggesting the change!

**Comment by eamodio** [comment]
FYI, you can setup Git/GitLens to ignore that commit (any commit(s)) from blames.

See the [`blame.ignoreRevsFile`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-blameignoreRevsFile) Git config setting or the [`--ignore-revs-file`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt) flag on Git blame.

Basically, you create a file that contains the commits you want to ignore (each on their own line). See [here](https://github.com/eamodio/vscode-gitlens/blob/fdba62a143193e695e088aa41168c72a664f39a7/.gitignore-revs). And then either set `blame.ignoreRevsFile` in your Git config for that repo, or use `--ignore-revs-file <file-name-here>` on the command line.

If you don't want to set it in your Git config, you can always make GitLens use it by setting the following in your `settings.json`
```json
"gitlens.advanced.blame.customArguments": ["--ignore-revs-file", "<file-name-here>"],
```

**Comment by evans** [comment]
So cool! Thank you so much @eamodio 🤩
