### ISSUE TITLE
"Last fetched" message is also updated when fetch failed

### ISSUE THREAD

**Issue by amfasis** [eamodio/vscode-gitlens#1016]
- GitLens Version: 10.2.1
- VSCode Version:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.9.0-8-amd64
- OS Version: Linux NB-BV009 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
 

Steps to Reproduce:

1. Clone a repository which is only available locally, such as in a company network.
2. Fetch when not connected to the company network. 

Observed:
"Last Fetched" will be updated to current date, however in the GitLens debug output the following can be seen:

```
[4a7d] GitService.fetchAll — e=myrepo, t={"all":false,"prune":false}
[4a7e] Repository(/media/work/source/myrepo/).fetch — {"all":false,"prune":false}
[4a7f] GitService.fetch — e=/media/work/Source/myrepo, t={"all":false,"prune":false}
[4a7d] GitService.fetchAll completed • 50 ms
[4a7a] GitCommandsCommand.execute completed
[/media/work/Source/myrepo] Git Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch • ssh: Could not resolve hostname gitlab.<company>.com: Name or service not known • Could not read from remote repository. •  • Please make sure you have the correct access rights • and the repository exists. • 161 ms
[/media/work/Source/myrepo] git fetch • 161 ms 
[4a7f] GitService.fetch completed • 167 ms
[4a7e] Repository(/media/work/source/myrepo/).fetch completed • 171 ms
```

Expected:
"Last Fetched" status message shows "Last Fetched failed" or is not updated to current time

**Comment by eamodio** [comment]
This has been resolved in the latest insiders edition (should be coming to stable soon).

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
