### ISSUE TITLE
Why is GitLens requesting documentSymbols from Language servers?  

### ISSUE THREAD

**Issue by fbricon** [eamodio/vscode-gitlens#1017]
With the Outline view closed and breadcrumbs disabled, I was surprised to see documentSymbols requests on the Java Language server, on each keystroke. Only occurs on files not in the Git index, not for new files. Why does GitLens request other symbol providers?

**Comment by eamodio** [comment]
GitLens uses the document symbols to provide the Git code lens.

See here:
https://github.com/eamodio/vscode-gitlens/blob/eaa91c0edf31cba65af0a661d94d3df9d3570bb1/src/codelens/codeLensProvider.ts#L150-L174

**Comment by fbricon** [comment]
Why do you need to query **all** document symbol providers, and not just the gitlens one?

**Comment by eamodio** [comment]
There is no GitLens one -- it is querying the language of the document to get the structure of the document to figure out where the code lens should be calculated and placed.
