### ISSUE TITLE
View all file changes in a Pull Request

### ISSUE THREAD

**Issue by Bennet-Sunder** [eamodio/vscode-gitlens#1020]
Just as we have options to view by commit ID as below is it possible to view all the changes for a particular pull request.
![image](https://user-images.githubusercontent.com/55491132/80966397-14ff3500-8e32-11ea-9187-80182df37cfa.png)
Say, I give a pull request id 345, I want to see all the changes in repo/pull/345/files. 
Would this be possible?

**Comment by ilovecookiez11** [comment]
I was just thinking about something like this; being able to open up the pull request in a browser window. From there you would be able to check all the files on a PR directly from a GitHub/GitLab page. It wouldn't require a lot of code since it would just be a URL link in the blame tooltip.

**Comment by Bennet-Sunder** [comment]
@ilovecookiez11  It would be better if I could see all the files just as would for a individual commit. I would prefer not the leave the IDE though.

**Comment by eamodio** [comment]
I would suggest looking at the CodeStream or GitHub Pull Requests and Issues extension, as they provide this ability. And soon there should be cross overs from GitLens to both of them.
