### ISSUE TITLE
`Show in File History View` does not work always

### ISSUE THREAD

**Issue by akosyakov** [eamodio/vscode-gitlens#1021]
It works for me only first time. If i try to open it then for another file afterwards it does nothing.

**Comment by akosyakov** [comment]
I guess this view will be irrelevant if VS Code supports the timeline now?

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in the insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
