### ISSUE TITLE
Support custom git diff command in compare with view

### ISSUE THREAD

**Issue by xster** [eamodio/vscode-gitlens#1022]
The compare with branch view is neat but it only allows simple invocations of diff with an existing branch. It would be great to be able to be able to compare the working directory against the `git merge-base --fork-point origin/master` commit so I can compare with the fork point when upstream diverges from my development branch so I can look at all the changes I've made on my development branch.

**Comment by eamodio** [comment]
Can you try out the new comparison implementation in the insiders edition? I think it will provide you with what you are looking for.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
