### ISSUE TITLE
main-styles.css cannot be loaded in remote context

### ISSUE THREAD

**Issue by akosyakov** [eamodio/vscode-gitlens#1023]
Getting errors like:
> Refused to load the stylesheet 'https://webview-3000-a96351c0-d111-42d1-b9b6-863439e1d244.ws-eu01.gitpod.io/webview/theia-resource/file/workspace/theia/plugins/vscode-gitlens/dist/webviews/main-styles.css' because it violates the following Content Security Policy directive: "style-src vscode-resource: 'nonce-nQlyH4xRXZ2pQAMKpiuYVQ=='". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

Please see https://code.visualstudio.com/api/advanced-topics/remote-extensions#option-1-use-asexternaluri 

`const cspSource = panel.webview.cspSource;` should be used

**Comment by eamodio** [comment]
Fixed in GitLens 11
