### ISSUE TITLE
How to use git rebase?

### ISSUE THREAD

**Issue by webcoderkz** [eamodio/vscode-gitlens#1024]
I have 2 branches: dev and master (i want to apply all the DEV changes on top of MASTER branch), in a gitlens window i'm switching to a master branch, then right clicking on dev branch and choosing "Rebase current onto branch", but it shows "master is up to date with dev", so i cannot rebase, but using terminal i can do that:

```
# switching to a master branch
git checkout master

# rebasing master
git rebase dev
``` 

Is that possible in a gitlens interface?

**Comment by michaelgosling** [comment]
im having this issue as well. using gitlens with a remote workspace because I can't use gitkraken or similar and the rebase functionality seems to not detect the later commit on the targeted branch.

**Comment by eamodio** [comment]
Have you tried the new Interactive Rebase editor in GitLens 11?
