### ISSUE TITLE
autolinks does not work for wrapped text

### ISSUE THREAD

**Issue by zaverden** [eamodio/vscode-gitlens#1032]
Issue Type: <b>Bug</b>

In our project we wrap JIRA issues with brackets, like `[JIRA-123] move button 2px left`

Settings: `"gitlens.autolinks": [{ "prefix": "JIRA-", "url": "https://jira.company.com/issue?query=<num>" }]`

- `JIRA-123 move button 2px left` has a link
- `[JIRA-123] move button 2px left` does not have a link
- `(JIRA-123) move button 2px left` does not have a link

Extension version: 10.2.1
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-99-generic

**Comment by zaverden** [comment]
https://github.com/eamodio/vscode-gitlens/blob/59e768545428aa6c599336af999daaa04029d547/src/annotations/autolinks.ts#L72

This regexp does not match if prefix is wrapped

**Comment by zaverden** [comment]
I have set `"prefix": "[SHOR-"` and there is an error in output:
```
[2020-05-15 08:44:01:774] Failed to create autolink generator: prefix=[JIRA-, url=https://jira.company.com/issue?query=<num>, title=undefined
SyntaxError: Invalid regular expression: /(?<=^|\s)(\\[JIRA\\-([0-9]+))\b/: Range out of order in character class
```

**Comment by GreenGremlin** [comment]
@eamodio I found this issue when trying to figure out why I couldn't get autolinks to work with pull request ids like `(#54321)`, it looks like [your fix](https://github.com/eamodio/vscode-gitlens/commit/0de56afe4d8f923da1c5c64e0dd9b214e4e9c28c) should fix my problem as well. Any idea when the fix might get released?

**Comment by eamodio** [comment]
This should be resolved in GitLens 11
