### ISSUE TITLE
Compare working directory with merge base of current commit and master

### ISSUE THREAD

**Issue by hediet** [eamodio/vscode-gitlens#1034]
It would be very handy if I could easily see all the changes I made for my current feature branch.
These changes would be the diff between the working directory and the merge base of the current commit and master, i.e. the most recent commit that both commits inherit from.

How is your workflow if you work on a feature branch and want to revisit all your changes in VS Code and see whether you can improve something? This would be analog to the diff in github the corresponding PR, but directly within VS Code.

**Comment by jopotts** [comment]
"Compare commits" does what you want I think. Simply select your current feature branch and the branch it's going to be merged into, and then select the '...' (three-dot comparison) option:

<img width="312" alt="Screenshot 2020-07-02 at 13 19 11" src="https://user-images.githubusercontent.com/26507/86358054-b8b86600-bc66-11ea-9cda-b131fa8be17d.png">

Feature enhancement request: It would be amazing to have this auto-refesh, default to three dots, and even always have it show the comparison of the current branch with the default merge branch as standard.

**Comment by hediet** [comment]
> Simply select your current feature branch

Will this include changes from the working directory? This is what my request is about ;)

**Comment by raulrpearson** [comment]
@hediet, you posted this a while ago, but just in case.

Comparison can be set between some hash/ref and your current branch or working directory using the [`gitlens.views.commits.showBranchComparison`](https://github.com/eamodio/vscode-gitlens/#commits-view-settings-) setting and the button that @jopotts mentioned.

The problem I find is that this flow makes it easy to select the head of some ref (let's say master) but not the merge base of your working branch/directory with respect to that other branch you're eventually going to want to merge your changes into.

I'm currently querying for the merge base on the command line and feeding that hash into the box that pops up when you click on the three dots. It would be nicer if this could be done in one click, though.

**Comment by eamodio** [comment]
This should actually be resolve in the most recent versions of GitLens. So I'm going to close this -- please chime in if there is something missing.

Also, FYI, you don't need to set the `gitlens.views.commits.showBranchComparison` setting directly, you can just use the toggle button in the UI:

![image](https://user-images.githubusercontent.com/641685/107437994-d3f12b00-6afd-11eb-8890-cd2765824117.png)
