### ISSUE TITLE
Two dot compare shows all changes (like three dot) with working tree

### ISSUE THREAD

**Issue by bd-dgonano** [eamodio/vscode-gitlens#1035]
Issue Type: <b>Bug</b>

1. Do a compare, and pick "working tree" and another branch eg master. 
2. Change to two dot compare

Compare consists on commits and files. 
The commits are correct, they only show commits from one side of the merge-base
The files show changes from both sides of the merge base though. 

The issue is not present if you pick your branch name and master instead of working tree and master, but then you don't get changes in working tree. 

Extension version: 10.2.1
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-99-generic snap
Remote OS version: Linux x64 4.15.0-99-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 4114)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.26GB (5.80GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: desktop-devshare02|
|OS|Linux x64 4.15.0-99-generic|
|CPUs|Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz (36 x 3399)|
|Memory (System)|62.64GB (16.82GB free)|
|VM|0%|
</details>

**Comment by eamodio** [comment]
This feature no longer exists in GitLens 11
