### ISSUE TITLE
Problem in settings.html

### ISSUE THREAD

**Issue by Mr-Lion** [eamodio/vscode-gitlens#1037]
- GitLens Version: 10.2.1
- VSCode Version: 1.45.1
- OS Version: Windows 10 64Bit

I get a problem in VSCode, the settings of which are not saved properly in settings.html.

There are exactly 9 warnings that annoy. Upon closer inspection, this is a simple HTML error. These should be remedied immediately.

As a developer, you should know the structure of an HTML. Everything is mixed up here.

![Anmerkung 2020-05-21 122920](https://user-images.githubusercontent.com/6929357/82545222-0b2e3f00-9b5f-11ea-8290-7a8c85c90547.jpg)
![Anmerkung 2020-05-21 122920_2](https://user-images.githubusercontent.com/6929357/82545223-0c5f6c00-9b5f-11ea-91d6-f9c743e49bb0.jpg)

I ask for an update

**Comment by eamodio** [comment]
This should be resolved in the later versions.
