### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by codenet** [eamodio/vscode-gitlens#1038]
- Issue Type: `Bug`
- Extension Name: `gitlens`
- Extension Version: `10.2.1`
- OS Version: `Darwin x64 19.4.0`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 252,
		"activateCallTime": 3,
		"activateResolvedTime": 2811,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "eamodio.gitlens",
				"_lower": "eamodio.gitlens"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'sha' of undefined"
		}
	]
}
```

**Comment by eamodio** [comment]
Can you provide more details as to what happened and what error(s) you are seeing?
