### ISSUE TITLE
How to get rid of "blame annotions between lines"?

### ISSUE THREAD

**Issue by bluenote10** [eamodio/vscode-gitlens#1039]
This might be a silly question, but I simply can't find the right setting to disable blame annotations that appear "between lines". By that I mean all the "You, X minutes ago | 1 author (You)" in the following:

![image](https://user-images.githubusercontent.com/3620703/82749348-ec22ed80-9da8-11ea-8810-5d120bc7ad85.png)

I find the annotations very noisy due to the changing line heights and the highly redundant information.

I found 29 settings of GitLens related to "blame", but after half an hour of experimenting I still haven't found the correct setting (maybe I do have to reload the editor after making each change to have an effect?). I just don't know how these things are called properly in GitLens terminology.

**Comment by eamodio** [comment]
Please try using the GitLens interactive settings editor. Using the command palette, run `GitLens: Open Settings`. The settings you are looking for are called "Code Lens"

**Comment by bluenote10** [comment]
Thanks, that solved it!

Maybe worth considering to disable it by default. From a UX perspective this is a bit of a questionable feature, much too noisy and there is already the per-line blame (for quick blame checks) and the "toggle blame file annotations" (in case more details are needed).
