### ISSUE TITLE
Show the only view that's currently being focused on

### ISSUE THREAD

**Issue by phmngocnghia** [eamodio/vscode-gitlens#1041]
![image](https://user-images.githubusercontent.com/36730355/83348738-629b8e80-a359-11ea-9e1f-dc7f2641a841.png)

I was using 13 inches laptop, and having all sidebar all open at once is really anoying, because my scrent don't have enough real estate for it, then I have to toggle some sidebars (file, repo....) to get more screen estate. Would be great if there's an option to show only focused sidebar, and I would love to show them by using VSCode command (Focus on * View), or a hotkey

**Comment by eamodio** [comment]
Unfortunately, GitLens can't control that behavior -- it is completely controlled by VS Code itself. If you would like to see that change, please file an issue on the VS Code repository.
