### ISSUE TITLE
Welcome page foreground color is black on dark themes

### ISSUE THREAD

**Issue by xWiiLLz** [eamodio/vscode-gitlens#1043]
Issue Type: <b>Bug</b>

1. Install and use a dark theme (I use Material Theme Ocean Dark Contrast)
2. Install Gitlens
3. The initial **Welcome to GitLens** page is very hard to read. It uses a black font on all themes

![image](https://user-images.githubusercontent.com/1496661/83464683-a2d53c80-a43f-11ea-9cc2-d4a8a2073c10.png)

Extension version: 10.2.1
VS Code version: Code - Insiders 1.46.0-insider (2c1871d538c64df71af4902deba47d7fa4b53f27, 2020-06-01T10:34:11.096Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (19.37GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/***** --remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|Memory (System)|31.60GB (19.37GB free)|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in the insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
