### ISSUE TITLE
Allow revert commit from file history view

### ISSUE THREAD

**Issue by inwardmovement** [eamodio/vscode-gitlens#1044]
In the repository view we can revert a commit:
![image](https://user-images.githubusercontent.com/9438102/83499593-ea021280-a4bd-11ea-8eca-0971b40f7ff7.png)

But not in the file history view:
![image](https://user-images.githubusercontent.com/9438102/83499587-e79fb880-a4bd-11ea-9158-c79659072e20.png)

**Comment by bobbyrenwick** [comment]
The file history view used to let you then "view commit in repositories view" and then you could revert from there but this workflow seems to have disappeared in the latest version. It'd be great to be able to revert commit from right clicking on any representation of a commit!

**Comment by eamodio** [comment]
@bobbyrenwick The option still exists in the menu, its just been renamed slightly
![image](https://user-images.githubusercontent.com/641685/100536908-d7109680-31f1-11eb-907c-9f9c74bb8243.png)

**Comment by eamodio** [comment]
I will add a `Commit >` submenu here to allow access to all the main commit actions

**Comment by eamodio** [comment]
There is now a `Commit` submenu on the file/line history nodes to allow access to many of the commit actions.

Can you please verify this fix in tomorrow's insiders edition? Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by bobbyrenwick** [comment]
Thanks for looking at that, Eric!

I can give the insiders edition a go tomorrow and let you know if I can successfully revert from the file history view.

**Comment by eamodio** [comment]
@bobbyrenwick Any luck? 😄

**Comment by bobbyrenwick** [comment]
@eamodio, thank you, that's excellent!
