### ISSUE TITLE
Disable welcome screen

### ISSUE THREAD

**Issue by jeluard** [eamodio/vscode-gitlens#1049]
I'd like to disable the opening of the welcome screen when gitlens is first executed. I'm operating a fleet of temporary vscode installation and users always get this screen when opening vscode.

Is there a way to achieve that?

**Comment by Tony7lee** [comment]
I have a similar problem, but I'm in the **cloud IDE！**
**The cloud IDE will always init a new instance,** and the welcome page  of gitlens installed before  will show again.

**Comment by Tony7lee** [comment]
how about to prevent the welcome page?

**Comment by Alsan** [comment]
@Tony7lee How can I do this? I've add "workbench.startupEditor":"none" to my settings.json already, but still popup the "Welcome To GitLens" everytime.

**Comment by rickardp** [comment]
I added a PR that fixes this, adding a new setting to disable all "advertising" pages.

**Comment by eamodio** [comment]
I changed the setting to be `gitlens.showWelcomeOnInstall` and only affect the welcome experience on the first install. If you also want to disable the What's New notification you will also need to change the existing `gitlens.showWhatsNewAfterUpgrades` setting.

Can you please verify this fix in tomorrow's insiders edition? Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).
