### ISSUE TITLE
Issue with merge conflict resolution

### ISSUE THREAD

**Issue by cruzzoe** [eamodio/vscode-gitlens#1050]
Gitlens version: 10.2.1
Vscode version: 1.45.1

Issue: 30s + Lag for "Accept Current Change" | "Accept Incoming Change" | ... menu to appear

When it does appear, when I select "Accept Incoming Change" instead of it adjusting the code in the diff section showing the incoming/current change, it instead modifies other code in my script leaving the conflict in place.

Not clear on what has changed. I've been using VsCode/GitLens for 6months+ without issue.

Looking at the errors in dev console I see:

(node:66468) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Also: 

Error Python Extension: 2020-06-08 16:34:00: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file

**Comment by eamodio** [comment]
GitLens doesn't provide the merge conflict code lens -- those are provided by VS Code itself.
