### ISSUE TITLE
Non-optimal expand/collapse behaviour

### ISSUE THREAD

**Issue by Dealerpriest** [eamodio/vscode-gitlens#1054]
Hi. The expand and collapse functionality of the the boxes in the gitlens pane is confusing and non-optimal.
I would argue that when a box is collapsed it should default to shrink downwards (giving it's space to the box above it). The current behaviour (with some edge cases) is that it shrink upwards (giving space to the box beneath).

An example of an edge case in the current version is when all boxes below the box that is collapsing are all collapsed. Then the collapsing box shrinks downwards. This makes sense cause otherwise it would require empty space beneath the bottom (collapsed) box (or that one of the boxes below got expanded).

See the following GIF for a demonstration:
![gitlens pane expand](https://user-images.githubusercontent.com/363913/85271298-e5a49600-b47a-11ea-95ba-a0a6dfc39ad9.gif)

Arguments for defaulting to shrink upwards:
- The box title with the expand/collapse arrow stays (more often) under the mouse so the user can expand/collapse with consequent clicks.
- Arguably more logical that boxes expand downward because we read that from top to bottom.

Arguments for defaulting to shrink downwards:
- The boxes are (arguably) sorted in order of priority, and the main reason for collapsing a box is to give more space to the box with higher priority (above).

**Comment by eamodio** [comment]
Unfortunately, GitLens has no control over this -- that behavior is controlled by VS Code itself. I would recommend filing an issue against the VS Code repo.
