### ISSUE TITLE
Running the contributed command: 'gitlens.views.showAllChildren' failed

### ISSUE THREAD

**Issue by BAE86AEC1946B6AB60CCD7452DC811F0** [eamodio/vscode-gitlens#1055]
- GitLens Version: v10.2.2
- VSCode Version: 1.47.0-insider
- OS Version: Windows_NT x64 10.0.18362

![1](https://user-images.githubusercontent.com/64393724/85831766-5f14ef00-b7c1-11ea-9153-701a04a903b0.png)
![2](https://user-images.githubusercontent.com/64393724/85831772-620fdf80-b7c1-11ea-9798-a55d7b5dd78f.png)

message:

```
Error running command gitlens.views.showAllChildren: Running the contributed command: 'gitlens.views.showAllChildren' failed.. This is likely caused by the extension that contributes gitlens.views.showAllChildren.
```

**Comment by mnazareno-myrp** [comment]
same. getting below error after today's insiders update. expanding commits/branches/remotes not working
```
Error running command gitlens.views.refreshNode: Running the contributed command: 'gitlens.views.refreshNode' failed.. This is likely caused by the extension that contributes gitlens.views.refreshNode.
```

**Comment by Gelio** [comment]
For me, none of the lists in the GitLens extension open up. This is the error in the VSCode DevTools that I saw when I clicked "Refresh" in GitLens:
![image](https://user-images.githubusercontent.com/889383/85839295-07fc2380-b79b-11ea-94ff-638d087465dc.png)

**Comment by mnazareno-myrp** [comment]
> same. getting below error after today's insiders update. expanding commits/branches/remotes not working
> 
> ```
> Error running command gitlens.views.refreshNode: Running the contributed command: 'gitlens.views.refreshNode' failed.. This is likely caused by the extension that contributes gitlens.views.refreshNode.
> ```

Problem no longer happening in latest Insider build:
Version: 1.47.0-insider
Commit: 04203498480e48be84d86f5763e126c7c5bf22e0
Date: 2020-06-30T09:01:06.154Z

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> > same. getting below error after today's insiders update. expanding commits/branches/remotes not working
> > ```
> > Error running command gitlens.views.refreshNode: Running the contributed command: 'gitlens.views.refreshNode' failed.. This is likely caused by the extension that contributes gitlens.views.refreshNode.
> > ```
> 
> Problem no longer happening in latest Insider build:
> Version: 1.47.0-insider
> Commit: 04203498480e48be84d86f5763e126c7c5bf22e0
> Date: 2020-06-30T09:01:06.154Z

yes
