### ISSUE TITLE
GitLens does not work on symlinked folders when opening a subfolder

### ISSUE THREAD

**Issue by MahdiGhiasi** [eamodio/vscode-gitlens#1058]
Issue Type: <b>Bug</b>

We have a large git repository, and certain folders are symlinks to another path *inside* the same repository.

If I open VS Code from root of git repository, everything works fine. But as we have a Unity project inside a folder in the repo, Unity tends to open a subfolder inside the repository. Now, in this scenario, everything still works fine for non-symlinked folders.

But, most of our code files are symlinks to a folder inside repository, but outside of this subfolder. File History and Line History doesn't work on these files.

Here's a sample folder structure:

```
Project --> Root of git repository
Project\Source
Project\Source\Assets
Project\Source\Scripts --> This is a symlink to Project\Source-Configurations\X\Script
Project\Source-Configurations
Project\Source-Configurations\X
Project\Source-Configurations\X\Script
```

In this scenario, if we open VS Code on `Project\Source` folder (instead of `Project`), files *inside* `Project\Source\Scripts` folder does **not** show any file history and line history. But for other files (for example files in `Project\Source` itself or `Project\Source\Assets`, which are not symlinks) GitLens works properly.

This seems to be a scenario *combining* #677 and #679, maybe?

Extension version: 10.2.2
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (2.40GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Mahdi/Projects/epimetheus-percity/Source|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in the insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
