### ISSUE TITLE
Open All Changes with difftool does not work as expected

### ISSUE THREAD

**Issue by jankap** [eamodio/vscode-gitlens#1059]
Dear all, thanks for the awesome work. I'm not sure if this is a bug or not, please remove this issue if it's inappropriate or so.

- GitLens Version:
v10.2.2
- VSCode Version:
1.46.1
- OS Version:
Win 10

Steps to Reproduce:

1. Open any git repo with history
2. In "Repositories" view, right click on previous revision, click "Open all changes" -> a lot of editors open ;)
3. Press ctrl+shift+p -> "Open all changes with difftool"

error:
![image](https://user-images.githubusercontent.com/12893844/86350577-324e5500-bc63-11ea-9c05-b73cdf9b32bf.png)
![image](https://user-images.githubusercontent.com/12893844/86350724-688bd480-bc63-11ea-9ad9-f3c223f24d74.png)

Maybe I do not understand the command properly. Is that command working only when there are merge changes, i.e. when I'm in the process of rebasing or merging?

If yes, how do I open all compare results (vs HEAD or working copy or two SHAs) in a difftool?

Thank you very much.

**Comment by spjspjspj** [comment]
I'm seeing the same error on macOS. 

GitLens Version:
v10.2.2
VSCode version:
1.47.2
OS version:
macOS mojave 10.14.6

**Comment by spjspjspj** [comment]
```
[2020-07-20 19:52:47:350] ExternalDiffCommand
TypeError: Cannot read property 'uri' of undefined
[2020-07-20 19:59:20:206] ExternalDiffCommand
TypeError: Cannot read property 'uri' of undefined
```

**Comment by jankap** [comment]
This seems to be fixed with most recent v11. Not sure when it was fixed, but thanks!
