### ISSUE TITLE
RFE - Expose extension API for other extensions to use

### ISSUE THREAD

**Issue by DonJayamanne** [eamodio/vscode-gitlens#106]
I'm wondering whether you're open to exposing the API of this extension for use by other extensions. In particular my [Git History](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory) extension. I believe it would be much better and easier for me to use the Gitlense UI from within my extension.

E.g. when a user wishes to view the details of a particular file, I could display the dropdown (somehow) that your extension does today. And/Or when I could display my UI and then invoke the API in your extension to display the file history or compare changes, and the like.  

I'm just trying to leverage the great work and awesome UI you have already done.
[Here's the documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_extensions) on how this could be achieved.

**Comment by eamodio** [comment]
@DonJayamanne 👍 I'm definitely interested in this. I've been thinking about breaking GitLens itself up into a "suite" of extensions around a common "core" which may provide an api to access my git object model and/or access to commands (mainly the quick picks, diffs, and such).

Unfortunately (for GitLens work 😄) I'm out on vacation for the next few weeks, but when I get back I'd definitely like to explore this further.

FYI, I also have a "public" GitLens slack setup if you are interested: https://join.slack.com/vscode-gitlens/shared_invite/MTk0NjA3OTIwNTE3LTE0OTY4OTc3NzQtMWQxODFhZWMyMA

**Comment by chatziko** [comment]
Related to this, is it possible for an extension operating on one of the /tmp files created by gitlens for diffing, to get the path of the corresponding working file?

**Comment by joelday** [comment]
I'd find just the wrappers and base implementations for vscode's APIs super helpful!

**Comment by ryaninvents** [comment]
I really like this idea; it would be nice to be able to implement a pull-request package which uses GitLens's (already excellent) Compare view

**Comment by eamodio** [comment]
I am going to close this open-ended API request, but I am starting to add extensibility to GitLens. Please open individual feature requests for extensibility points that are desired.
