### ISSUE TITLE
Enable copying of abbreviated commit IDs

### ISSUE THREAD

**Issue by br3ndonland** [eamodio/vscode-gitlens#1062]
I would like to be able to copy abbreviated commit IDs (SHAs), but I can only copy full-length IDs. I frequently find myself copying a commit ID, pasting it into a commit message (to reference a related commit), and then manually abbreviating it to 7-8 characters.

We now have the ability to change the length of the abbreviated commit ID, after eamodio/vscode-gitlens#608 and eamodio/vscode-gitlens#611. However, there doesn't seem to be a way to actually copy the abbreviated commit ID. I can't find any option to set the length of the commit ID copied to the clipboard. Am I missing something?

I'm on macOS Catalina 10.15.5, VSCode 1.46.1, and GitLens 10.2.1.

I would like to see something like:

- Menu option for copying abbreviated commit ID (probably in between the "Copy Commit ID" and "Copy Commit Message" options)
  ![gitlens-commit-menu](https://user-images.githubusercontent.com/26674818/86487741-e9fb6980-bd2c-11ea-9291-29ba8cd2efa9.png)
- Setting to change the default length of copied commit IDs (so that when you click the "Copy Commit ID" button, it copies the abbreviated commit ID)
  ```json
  {
    "gitlens.defaultCommitIDFormat": "abbreviated"
  }
  ```

I'm happy to take on a PR for this, though it will probably be several weeks until I can make time for it.

**Comment by eamodio** [comment]
Sounds like a good idea. Would you mind opening a PR to add it or get it started? I'd be happy to help point in the right direction, etc.

I would also suggest a setting more like `"gitlens.advanced.useAbbreviatedShaLengthForCopy": true|false`

**Comment by br3ndonland** [comment]
Sure thing. I'll get working on a PR.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by br3ndonland** [comment]
> Can you please verify this fix in tomorrow's insiders edition?

Verified! After disabling `eamodio.gitlens` and installing `eamodio.gitlens-insiders`, I can add these settings:

```json
{
  "gitlens.advanced.abbreviatedShaLength": 8,
  "gitlens.advanced.abbreviateShaOnCopy": true
}
```

GitLens then copies the SHA with the correct abbreviated length of 8 characters.

Thanks for all your work on GitLens! It's a great extension and I really appreciate it. 👏

**Comment by eamodio** [comment]
Awesome thanks!
