### ISSUE TITLE
Newline in gitlens.blame.format messes up rendering

### ISSUE THREAD

**Issue by schuelermine** [eamodio/vscode-gitlens#1064]
- GitLens Version: 10.2.2
  
- VSCode Version: 1.47.0-insider
- OS Version: Windows 10 2004 Build 19041.329

Steps to Reproduce:
1. Use a newline in gitlens.blame.format
2. Observe messed up blame gutter:

![grafik](https://user-images.githubusercontent.com/48802534/86539372-3943c480-befc-11ea-9812-88b927af1b7d.png)
![grafik](https://user-images.githubusercontent.com/48802534/86539380-4b256780-befc-11ea-9964-b4caafe5a99d.png)

Used formatting: `${email}\n${message|20?}\n${agoOrDate|14-}`

**Comment by eamodio** [comment]
Newlines in that format string are not supported.
