### ISSUE TITLE
Gitlens line tail some area cant click

### ISSUE THREAD

**Issue by ilimei** [eamodio/vscode-gitlens#1067]
GitLens Version: 10.2.2
code-server: v3.4.1
VS Code: v1.45.1

step
  open some file in git
  click some line
  move cursor not end
  click line end （cursor cant move to line end）
![image](https://user-images.githubusercontent.com/12947068/87136797-9231a500-c2ce-11ea-9594-5d25f0e9337b.png)

**Comment by eamodio** [comment]
If this is still happening this would be bug in VS Code itself and should be reported there. Thanks!
