### ISSUE TITLE
How do I reset GitLens' panels?

### ISSUE THREAD

**Issue by BBKolton** [eamodio/vscode-gitlens#1068]
I moved gitlens' panel temporarily by dragging it to the terminal area. When I moved it back to the sidebar, it instead grabbed the individual panes that make up the regular gitlens view. However, now I have 5 panels on the sidebar instead of just one for gitlens. 

I figured out I can grab the panel icon on the activity bar and bring that into on of the open gitlens sub-panels, but I'm wondering: how do I reset the extension so that the panels are grouped again by default? Thanks!

**Comment by eamodio** [comment]
In VS Code, if you right-click on a view, and it is not in its "default" location, there should be a `Reset Location` command that should put it back. Hope that helps!
