### ISSUE TITLE
Double-byte characters break blame layout

### ISSUE THREAD

**Issue by kyle245** [eamodio/vscode-gitlens#107]
- GitLens Version: 4.3.0

![zb 8 6 _ri a2bv3 c 2w](https://user-images.githubusercontent.com/10083834/27792843-26297ce4-602e-11e7-9d77-11bae4edcfaf.png)

**Comment by eamodio** [comment]
@kyle245 this will be "fixed" in v4.3.3, but it is dependent on the font used. If the monospace font doesn't properly monospace double-width characters it still won't render properly. Unfortunately there isn't anything I can do about that.

See also https://github.com/Microsoft/vscode/issues/14589

FYI, I tested with Inconsolata and everything worked correctly.
