### ISSUE TITLE
Cannot fetch repositories

### ISSUE THREAD

**Issue by manie204** [eamodio/vscode-gitlens#1070]
I have the exact same issue as described in closed issue #749. Could you reopen/reinvestigate?

- GitLens Version: 10.2.2
- VSCode Version: 1.47.0
- OS Version: Windows_NT x64 10.0.19.041

Steps to Reproduce:

1. Navigate to *gitlens pane* -> *repositories view*.
2. Press *Fetch Repositories*

Expected behavior:
Same as ```git fetch```.

Observed behavior:
The vscode notification "Fetching mpidb..." lasts indefinitely and no fetch occurs.

Gitlens log after pressing *Fetch Repositories*

>[2020-07-13 15:45:11:946] [80] GitService.getOrderedRepositories
>[2020-07-13 15:45:11:946] [81] GitService.getRepositories
>[2020-07-13 15:45:11:946] [81] GitService.getRepositories completed • 0 ms
>[2020-07-13 15:45:11:946] [80] GitService.getOrderedRepositories completed • 0 ms
>[2020-07-13 15:45:11:947] [83] GitService.getOrderedRepositories
>[2020-07-13 15:45:11:947] [84] GitService.getRepositories
>[2020-07-13 15:45:11:947] [84] GitService.getRepositories completed • 0 ms
>[2020-07-13 15:45:11:947] [83] GitService.getOrderedRepositories completed • 0 ms
>[2020-07-13 15:45:11:948] [85] GitService.fetchAll — e=mpidb, t={"all":false,"prune":false}
>[2020-07-13 15:45:11:948] [86] Repository(/some-repo/).fetch — {"all":false,"prune":false}
>[2020-07-13 15:45:11:950] [87] GitService.fetch — e=/some-repo, t={"all":false,"prune":false}
>[2020-07-13 15:45:11:952] [85] GitService.fetchAll completed • 4 ms
>[2020-07-13 15:45:11:952] [82] GitCommandsCommand.execute completed

Gitlens (Git) log is empty.

Additional info:
Repository sits in WSL file system, using [remote WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) to edit files. VS Code uses git (v. 2.27.0) from the WSL side, not from Windows.

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?

**Comment by manie204** [comment]
Issue is resolved in the newest version, thanks!
