### ISSUE TITLE
Missing whitespace in branch "commits behind" node description

### ISSUE THREAD

**Issue by deadmeu** [eamodio/vscode-gitlens#1072]
When in a repository with a branch that is behind (presumably also ahead, though I haven't tested it) the remote, hovering the cursor over the "n commits behind" node shows a description with a missing whitespace character between "behind" and the branch name (in my case, "origin/master".

![image](https://user-images.githubusercontent.com/12111013/87369298-83473d00-c5c3-11ea-9939-7ba5ac877a91.png)

- GitLens Version: 10.2.2
  
- VSCode Version: 1.46.1
- OS Version: Linux x64 5.7.8-5-MANJARO

Steps to Reproduce:

1. Have a branch that is behind the remote
2. Hover the cursor over the "n commits behind" node under the "Branches" tree

**Comment by eamodio** [comment]
Fixed in GitLens 11
