### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by RoySoumyadeep** [eamodio/vscode-gitlens#1074]
Issue Type: <b>Bug</b>

Gitlens has stopped working with the current update

Extension version: 10.2.2
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (4.15GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by itimgit** [comment]
Extension version: 10.2.2
VS Code version: Code 1.47.2
OS version: Windows 10 19041.388
"Unable to show commit details. The commit could not be found"
