### ISSUE TITLE
Copy Remote URL Does Not URL Encode Link

### ISSUE THREAD

**Issue by nchandran3** [eamodio/vscode-gitlens#1075]
Issue Type: <b>Bug</b>

1. Open a file with whitespace in the name
2. Push to remote
3. Copy Remote URL 
4. Paste link that was copied to clipboard

--> Link contains spaces instead of encoding to %20

This causes problems when copy and pasting the link in certain chat applications. It would be better to ensure that the link copied to clipboard is URL encoded. 

Extension version: 10.2.2
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19037
Remote OS version: Linux x64 3.10.0-862.11.6.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|OS|Linux x64 3.10.0-862.11.6.el7.x86_64|
|CPUs|Intel Xeon E312xx (Sandy Bridge) (4 x 2394)|
|Memory (System)|23.39GB (0.20GB free)|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Fixed in GitLens 11

**Comment by electrovir** [comment]
I think this caused a bug that I'm experiencing now where `/` is encoded as `%2F`, which totally messes up the path. `path/to/my/file` turns into `path%2Fto%2Fmy%2Ffile`

**Comment by eamodio** [comment]
Yeah, that one is fixed in insiders, and will be coming to stable soon
