### ISSUE TITLE
Text overlaps in "File history"

### ISSUE THREAD

**Issue by Bird-mw** [eamodio/vscode-gitlens#1078]
- GitLens Version: 101.2.2
  
- VSCode Version: 1.47.2
- OS Version: Windows 10

Steps to Reproduce:

1.Have repository with commits that go far back in time

Mousing over the text makes it show correctly.

![image](https://user-images.githubusercontent.com/58033648/88039967-8bb1f180-cb48-11ea-92f8-3563fd15fb0d.png)

![image](https://user-images.githubusercontent.com/58033648/88040197-d6336e00-cb48-11ea-9605-ed7503f79905.png)
Inspecting the element and setting the display to none reveals that the element that overlaps is placed incorrectly as it should be placed further down
![image](https://user-images.githubusercontent.com/58033648/88040330-08dd6680-cb49-11ea-80fa-38ef37f75e07.png)

**Comment by hpfr** [comment]
I get a similar issue in the Repositories section with long commit histories, whether branches are collapsed or expanded.

**Comment by eamodio** [comment]
If anyone is still seeing issues like this -- they are bugs in VS Code itself and should be reported there. Thanks!
