### ISSUE TITLE
Option to remove stash explorer from the main explorer?

### ISSUE THREAD

**Issue by rfgamaral** [eamodio/vscode-gitlens#108]
I don't really like that now I have a "GIT STASHES" tab on my main explorer, can we get an option to pick where this should be located instead of forcing it on the main explorer?

If not, at least an option to disable this tab would be appreciated. Or is there one already that I might have missed?

Just a few suggestions.

**Comment by eamodio** [comment]
@rfgamaral Really sorry about that. v4.3.1 disables the Git Stashes explorer by default, and adds both a setting and command to turn it back on

**Comment by rfgamaral** [comment]
Awesome, really appreciated, thanks :)
