### ISSUE TITLE
Blame annotation hovers stop working

### ISSUE THREAD

**Issue by jasonvarga** [eamodio/vscode-gitlens#1080]
Issue Type: <b>Bug</b>

When hovering over line blame annotations, the dialog pops up. This is great!

![Screen Capture on 2020-07-23 at 16-59-33](https://user-images.githubusercontent.com/105211/88338170-f8beb600-cd05-11ea-832f-4231839675c4.gif)

I'm not sure what triggers it, but sometimes these just stop working. The annotations appear just fine, but the hovers don't.

I notice this happens more often when I'm using split panes. It'll work for a while after I split the panes, then it just gives up eventually. Removing the splits brings it back to life.

Extension version: 10.2.2
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.4.0

**Comment by jeffreyyjp** [comment]
I also have this problem. Sometimes it works, but later the hover doesn't work. Then when I right-click with my mouse, and click <code>Open Line Changes with Previous Revision</code>, it shows below screenshot.
![image](https://user-images.githubusercontent.com/17985592/89165938-dd786400-d5ab-11ea-97c8-2d1ceb5cc6f1.png)

**Comment by jasonvarga** [comment]
Now hovers just aren't working at all. No idea what changed.

Still extension version 10.2.2

**Comment by ndevenish** [comment]
This happens all the time, has been happening intermittently for a long time, and is very annoying. I haven't been able to work out a specific pattern of causation at all.

GitLens Zen mode _wasn't_ turned on, but toggling it on then off again made the popups come back. Toggling file blame annotations and hovering over the new blame-bar also works when this mode isn't.

**Comment by zenoven** [comment]
+1
I have to restart VSCode to git it work again.

**Comment by eamodio** [comment]
This will be fixed in GitLens 11 (coming soon).

**Comment by eamodio** [comment]
Fixed in GitLens 11
