### ISSUE TITLE
Push doesn't work to default remote

### ISSUE THREAD

**Issue by irvnriir** [eamodio/vscode-gitlens#1081]
Its expected that doing "Set as Default" on Remote, will select it for push.

- GitLens Version:
  
- VSCode Version:1.45.1
- OS Version:win10

Steps to Reproduce:

1. Add local backup repository as Remote via RMB on Remotes in `ActivityBar \ GitLens \ Repositories` .
2. `RMB \ Set as Default` .
3. `ActivityBar \ Source Control \ More Actions \ Push` .

Will output "No configured push designation" .

**Comment by eamodio** [comment]
The `Set as Default` command doesn't affect any Git configuration -- it is just a GitLens flag to mark a particular remote for certain GitLens operations, e.g. connecting to a rich remote provider, opening remote links, etc.

**Comment by irvnriir** [comment]
The target for Push is provided trough Gitlens , setting the Default as this target is nothing else a Gitlens configuration .
