### ISSUE TITLE
Option to git rm (delete) a file

### ISSUE THREAD

**Issue by chmac** [eamodio/vscode-gitlens#1083]
Firstly, thanks a lot for GitLens, it's awesome. Makes git a helluva lot more powerful in vscode.

I'm looking for a way to effectively run `git rm src/path/to/current/file` from within vscode. I can delete the file from the explorer, but then I need to tell git it was deleted. Not sure if I've missed this, searched high and low but couldn't find it.

**Comment by eamodio** [comment]
Other than `git rm` removing the file from both the index (e.g. staged changes) and the working tree, git doesn't do anything else special. So unless you've staged the file and then want to delete it -- in 1 command (because you can just unstage it and then delete it normally) there isn't any reason I know of to need to use `git rm`

**Comment by chmac** [comment]
@eamodio On macOS there's a difference between "move to trash" and `rm`. I usually prefer `git rm` as it uses `rm` underneath, which I prefer to putting files into my system trash.

I understand that you don't see a reason to use `git rm`. Are you open to a PR adding the option, or it's something you're not interested in supporting?

**Comment by eamodio** [comment]
Hrm, where would you want to see this option?

**Comment by chmac** [comment]
I'd imagine it in the command palette while I'm looking at a file. I do most of my git committing in GitUp, purely because I can see precisely what I'm about to commit at the same time as I write the message (like `git commit -v`). In deeply nested files, it's often tricky to find that precise file to run `git rm path`. If I could open the command palette and `git rm` the current file, that would be awesome. The confidence that I'm deleting the correct file would be the win for me.

**Comment by eamodio** [comment]
Hrm -- I don't think I'm comfortable with such a destructive action in the command palette. VS Code doesn't even offer a command to delete the current file. I also don't think GitLens is the right place for it. I could possibly see it being added as a context menu item, e.g. _Delete (Permanently)_ from a file in the VS Code Git changes view.

Would you mind opening a feature request on the vscode repo for that?

**Comment by chmac** [comment]
@eamodio Makes sense. The advantage of `git rm` is that it will fail without `--force` if the file has been modified from the HEAD. It's a "safer" permanent deletion in a sense. It only deletes the file if it's currently identical to what is committed. That means it's a lot less "destructive" than a straight `rm`. Happy to submit a feature request on VS Code, I can see that it also might fit better into the core git commands. Thanks for all the replies, I know it's a lot of work maintaining open source software, and I appreciate the time you've put into answering my questions.
