### ISSUE TITLE
errno=Operation timed out does not refresh after remote repository in LAN connected back to network

### ISSUE THREAD

**Issue by kam89** [eamodio/vscode-gitlens#1085]
Hi all, good day and stay healthy.

I have a remote repository on a Local Area Network (LAN) with 2 workstations.
Workstation A is where my remote repository located and I am using Workstation B.
If Workstation A went to sleep due to inactivity, GitLens **fetch** will encountered **errno=Operation timed out**.

But once I connected back the Workstation A back to the network, GitLens **fetch** is still encountered the same error
**errno=Operation timed out**. 

I have to restart the VS code then only GitLens **fetch** will be working fine.
_It seemed like the error is cached somewhere even though the remote repository is connected back to network._

In fact we can use the terminal to perform **git fetch** to pull the latest changes from the remote repository, so this is not really a big issue.

Anyhow, just want to feedback to you guys.

- GitLens Version: v10.2.2
  
- VSCode Version: 1.47.3
- OS Version: macOS v10.15.6

Steps to Reproduce:

1. Create a remote repository at a workstation (Workstation A) in Local Area Network (LAN).
2. Make the Workstation A to sleep, network should be disconnected automatically.
3. From another Workstation B, fetch the remote repository using the GitLens (fetch).

<img width="279" alt="Screenshot 2020-08-03 at 10 51 17 AM" src="https://user-images.githubusercontent.com/30794641/89141486-53160d00-d577-11ea-8459-3f21f6b1ab4e.png">

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in the insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by kam89** [comment]
Hi, the issue is still reproducible in the insiders edition.
Below is the retrieved from the OUTPUT tab for GitLens.

> [2020-12-31 05:52:45:972] /Users/<username>/.vscode/extensions/eamodio.gitlens-insiders-2020.12.2904/dist/gitlens.js:2:842104
> Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false fetch origin
> fatal: unable to connect to 192.168.X.XXX:
> 192.168.X.XXX[0: 192.168.X.XXX]: errno=Operation timed out

**Comment by eamodio** [comment]
@kam89 When it happens are you able to successfully run `git fetch origin` from the terminal?

**Comment by kam89** [comment]
> @kam89 When it happens are you able to successfully run `git fetch origin` from the terminal?

Sorry. Please refer to my updated comment again. The issue seemed resolved using the GitLens (insiders edition).
Forget to fetch again just now.

**Comment by eamodio** [comment]
@kam89 OK, glad it's resolved. 👍
