### ISSUE TITLE
What is difference between "open changes prev revision", "open line changes prev rivision", and "open line changes with working file"

### ISSUE THREAD

**Issue by NikiforovAll** [eamodio/vscode-gitlens#1086]
I have found what is the difference between "open changes" and "open line changes". Could you please explain the usage of the next commands?

* gitlens.diffLineWithWorking (CTRL+SHIFT+G W)
* gitlens.diffLineWithPrevious CTRL + SHIFT + G SHIFT ,)
* gitlens.diffWithPrevious (CTRL + SHIFT + G ,)

![image](https://user-images.githubusercontent.com/8037439/89155214-15ae8100-d571-11ea-94c9-127410b84edb.png)

**Comment by NikiforovAll** [comment]
After playing with gitlens a little bit more, I've figured out how to interpret these commands:

Hint: In order to understand this functionality I suggest to learn with GitBlame turned on.

"Open Changes" (gitlens.diffWithPreviousInDiffRight) - opens changes for **current file** and shows diff between:
1. Two previous commits, if the working tree for **current file** is empty (file not changed)
2. The working tree and previous commit

"Open Line Changes" (gitlens.diffLineWithPrevious) - open changes for the **current line in the opened file** and shows diff between: 
1. Last commit for this line and preceding commit, if the working tree for the **current line** is empty. (line not changed)
2. The working tree and previous commit for this line 

"Open line changes with working file" (gitlens.diffLineWithWorking) - open changes for *current line in the opened file** and shows diff between:
1. The working tree and last commit for the **current line**, if the working tree for the **current line** is empty (line not changed)
2. Last commit and the working tree (~ git.openChange)

"Open changes" (git.openChange) - opens changes between the working tree and last commit for this file.

**Comment by NikiforovAll** [comment]
I think this issue may be closed if I've got this right.

**Comment by eamodio** [comment]
Yup -- that's correct!
