### ISSUE TITLE
Error retrieving line history from UNC path

### ISSUE THREAD

**Issue by AnrDaemon** [eamodio/vscode-gitlens#1087]
Issue Type: <b>Bug</b>

Have repo located on UNC path.
Try to get line history.

Boom…
```
Unable to open 'create-validator.php (7625aea) ⟷ create-validator.php (d65a66e)': Unable to read file 'gitlens://7625aea/DAEMON-EC.DARKDRAGON.LAN/anrdaemon/Documents/git-projects/create-validator/create-validator.php?{"path":"//DAEMON-EC.DARKDRAGON.LAN/anrdaemon/Documents/git-projects/create-validator/create-validator.php","ref":"7625aea5dcd542555cfa67205ffaa2f9203b06dc","repoPath":"//DAEMON-EC.DARKDRAGON.LAN/anrdaemon/Documents/git-projects/create-validator"}' (Error: Unable to resolve non-existing file 'gitlens://7625aea/DAEMON-EC.DARKDRAGON.LAN/anrdaemon/Documents/git-projects/create-validator/create-validator.php?{"path":"//DAEMON-EC.DARKDRAGON.LAN/anrdaemon/Documents/git-projects/create-validator/create-validator.php","ref":"7625aea5dcd542555cfa67205ffaa2f9203b06dc","repoPath":"//DAEMON-EC.DARKDRAGON.LAN/anrdaemon/Documents/git-projects/create-validator"}').
```

Same effect for any other "GitLens: changes".

Extension version: 10.2.2
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3303)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (4.98GB free)|
|Process Argv|\\DAEMON-EC.DARKDRAGON.LAN\anrdaemon\Documents\caduceus\cadu-x5-gui|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by egfx-notifications** [comment]
I can confirm this, same problem here.
Once I move the affected repository to a local drive, it works again.

Extension version: 10.2.2
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mikes-gh** [comment]
Same here

Gitlens 10.2.2

```
Unable to open 'invfe53gst.et (3d166c2) ⟷ invfe53gst.et (0cee44d)': Unable to read file 'gitlens://3d166c2/aesrocc/home/ROCCTEST/fldedit/invfe53gst.et?{"path":"//aesrocc/home/ROCCTEST/fldedit/invfe53gst.et","ref":"3d166c201da099633882366b3a0ce9fb79a361b2","repoPath":"//aesrocc/home/ROCCTEST"}' (Error: Unable to resolve non-existing file 'gitlens://3d166c2/aesrocc/home/ROCCTEST/fldedit/invfe53gst.et?{"path":"//aesrocc/home/ROCCTEST/fldedit/invfe53gst.et","ref":"3d166c201da099633882366b3a0ce9fb79a361b2","repoPath":"//aesrocc/home/ROCCTEST"}').
```

**Comment by eamodio** [comment]
Can you please verify this fix in the latest insiders version? 

You can install the insiders version from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by mikes-gh** [comment]
Tested using debug of main.  
All working fine.
Testing scenarios

UNC path Windows 10 
Local path  Windows 10
Local path macOS

**Comment by AnrDaemon** [comment]
Cautiously declare this working. Thanks!

**Comment by egfx-notifications** [comment]
Works for me

**Comment by mkanet** [comment]
Working for me.  I've always had this issue ever since I started working from home.  I used to think the issue was an anomaly caused by VPN. The GitLens Insiders fixed it!
