### ISSUE TITLE
How to change the blame line color

### ISSUE THREAD

**Issue by oleksiivelychko** [eamodio/vscode-gitlens#1089]
Hi, I can't change the blame line color. I'd read readme, and tried change Gutter Heatmap settings but nothing was changed.

![image](https://user-images.githubusercontent.com/40713712/89631634-b8386e00-d8a9-11ea-899b-86b62af510d7.png)

Where is there that settings?

**Comment by xzela** [comment]
try adding this to your local `settings.json`:

```json
"workbench.colorCustomizations": {
  "gitlens.trailingLineForegroundColor":"#ff0000"
}
```

After reviewing the documentation, I had to do some trail and error to figure out which one actually targeted the correct type of text.

https://github.com/eamodio/vscode-gitlens#themable-colors-

**Comment by oleksiivelychko** [comment]
> try adding this to your local `settings.json`:
> 
> ```json
> "workbench.colorCustomizations": {
>   "gitlens.trailingLineForegroundColor":"#ff0000"
> }
> ```
> 
> After reviewing the documentation, I had to do some trail and error to figure out which one actually targeted the correct type of text.
> 
> https://github.com/eamodio/vscode-gitlens#themable-colors-

Yes, it works, thank you!
