### ISSUE TITLE
Can't disable Stashes Explorer

### ISSUE THREAD

**Issue by hbenl** [eamodio/vscode-gitlens#109]
- GitLens Version: 4.3.1
- VSCode Version: 1.13.1
- OS Version: Linux x64

Steps to Reproduce:

1. Run the command "Toggle Git Stashes Explorer" -> the Stashes Explorer appears
2. Run the command "Toggle Git Stashes Explorer" again -> nothing happens

Now I'm stuck with the Stashes Explorer, the only way to get rid of it is to uninstall this extension :(

**Comment by eamodio** [comment]
@hbenl Sorry that you are experiencing issues. I'll have to check into why the toggle isn't working. I saw something there once but couldn't reproduce it. But the toggle command just sets the `gitlens.stashExplorer.enabled` setting. If you set `"gitlens.stashExplorer.enabled": false` it should resolve the issue for you.

Please let me know if not. 

FYI, I will be traveling over the next couple of weeks so my response times may be drastically reduced.

**Comment by netopolit** [comment]
I'm having the same problem. "gitlens.stashExplorer.enabled" is set to false but stash explorer is still there. Thanks.

**Comment by eamodio** [comment]
Damn. I'm not near a computer but I'm guessing that the released version of vscode may not yet support conditional views :(

**Comment by hbenl** [comment]
I tried with the latest VS Code Insiders build and it worked. So I guess we'll just wait for the next VS Code release (which should come out in the next days) and see if that fixes it.

**Comment by eamodio** [comment]
Now I just have to decide -- pull the feature until 1.14 or wait it out until 1.14 -- hrm :(

**Comment by hbenl** [comment]
It works in VS Code 1.14
