### ISSUE TITLE
Current Line Blame shows incorrect timestamp

### ISSUE THREAD

**Issue by jplackey** [eamodio/vscode-gitlens#1091]
Issue Type: <b>Bug</b>

Using GitLens on Windows 10 (10.0.17134.1610) along with Remote-SSH (Microsoft, 0.51.0) to a Linux server.  In this setup, the timestamp shown in the current line blame isn't always correct.

For example: The last changes I made to a given file were on Friday.  I open up that same file on Saturday and close it without making any changes.  If I then reopen that same file, the inline blame displays, "You, a few second ago".

I originally thought VSCode and/or Remote-SSH may have been saving the file automatically when closed (despite no changes being made), but the last modified date on the file is still from Friday, so I'm not sure that's the case.

Additionally, if I restart VSCode and re-open the same file immediately, the reported timestamp changes again.  In one case, right after GitLens reported "a few seconds ago", I restarted VSCode, and the timestamp then said, "You, seven minutes ago".

Not quite sure what's going on here, but it's tripped me up several times by making me think I'd made changes more recently than I actually had.

Extension version: 10.2.2
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 (...)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: (redacted)
|OS|Linux x64 (...)
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (8 x 2500)|
|Memory (System)|60.00GB (2.60GB free)|
|VM|0%|
</details>

**Comment by oXwvdrbbj8S4wo9k8lSN** [comment]
I have the same problem running VSCode in a Docker container (using ms-vscode-remote.remote-containers).
All lines say "You, a few second ago" when I open a file and the timer counts up (e.g. "You, a 8 minutes ago") until I save the file.
With VSCode running natively on Windows, correct informations are displayed.

**Comment by oXwvdrbbj8S4wo9k8lSN** [comment]
It seems that this helps at least for problems regarding git repos shared between Windows and Linux systems: https://code.visualstudio.com/docs/remote/troubleshooting#_resolving-git-line-ending-issues-in-containers-resulting-in-many-modified-files

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?

**Comment by jplackey** [comment]
Using GitLens 11.0.6, tried several permutations of open/close/change/undo/save/reload, and the timestamps on the inline blames all looked correct.
