### ISSUE TITLE
How to display changes in hunks

### ISSUE THREAD

**Issue by jczhang07** [eamodio/vscode-gitlens#1092]
When I click the "Open Changes" icon, the screen is split in two and the current file is shown in both sides with changes highlighted.  However, the file is shown in full.  I find it is difficult to browse the changes when the file is long.  

How can I let it only show changes in hunks?

Thanks.

**Comment by eamodio** [comment]
When you are in a VS Code diff editor you can switch between side-by-side view and inline view:
![image](https://user-images.githubusercontent.com/641685/100704860-3bf3fa00-3374-11eb-809b-21df46a36513.png)
