### ISSUE TITLE
Could not fetch repositories

### ISSUE THREAD

**Issue by stijn7621** [eamodio/vscode-gitlens#1093]
This issue happens when clicking on the gitlens fetch repositories button. The pull & push buttons works fine though. Also the git: Fetch command from the quick actions view is also working fine. So I think it should be an issue related to the extension.

Output GitLens:
```
[2020-08-12 09:52:47:330] ChildProcess.exithandler
Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false fetch
Logon failed, use ctrl+c to cancel basic credential prompt.
Logon failed, use ctrl+c to cancel basic credential prompt.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://teamfoundation.green.local': No such file or directory
```

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?

**Comment by stijn7621** [comment]
Yes

**Comment by eamodio** [comment]
Hrm -- it looks like vscode must do something special to deal with this credential issue. Can you fetch from the terminal (both external and integrated?)?

**Comment by stijn7621** [comment]
Yes, I can also pull and push with gitlens and from the integrated terminal

Verstuurd vanaf mijn iPhone

**Comment by eamodio** [comment]
Can you fetch from another terminal (not the integrated one)?
