### ISSUE TITLE
Confusing Telemetry settings

### ISSUE THREAD

**Issue by balibebas** [eamodio/vscode-gitlens#1094]
- GitLens Version: 10.2.22
- VSCode Version:  1.38.1
- OS Version: macOS 11.0 Beta

Steps to Reproduce:

1. Disable telemetry according to the [instructions from Microsoft](https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting)
2. Install GitLens
3. View telemetry settings.
4. Observe GitLens telemetry setting is enabled.

Gitlens telemetry setting should be disabled by default if the overall setting is disabled. Otherwise it appears enabled as shown here (yes, even with the note).

<img width="815" alt="Screen Shot 2020-08-21 at 17 16 36" src="https://user-images.githubusercontent.com/65664227/90874369-329cde00-e3d2-11ea-85dd-c369e3e66667.png">

**Comment by eamodio** [comment]
GitLens doesn't collect any telemetry -- that setting was old (and unused) and has been removed in GitLens 11

**Comment by balibebas** [comment]
> GitLens doesn't collect any telemetry -- that setting was old (and unused) and has been removed in GitLens 11

Today GitLens prompted me to connect to GitHub which is another form of Telemetry (if enabled). Is there a way to prevent this prompt from occurring now that the telemetry disable feature has been removed?

**Comment by eamodio** [comment]
Yes -- there will be an easy opt-out coming very soon, or you can use the [Insiders edition](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders) today.
