### ISSUE TITLE
How to disable the startup welcome screen?

### ISSUE THREAD

**Issue by Alsan** [eamodio/vscode-gitlens#1096]
I have the following in my settings.jon but the gitlens welcome screen still popups everytime.

```json
"gitlens.showWhatsNewAfterUpgrades": false,
"gitlens.advanced.telemetry.enabled": false,
"workbench.startupEditor":"none",
```

I'm using Linux version of vscode.

**Comment by mchelen-gov** [comment]
Same issue here https://github.com/eamodio/vscode-gitlens/issues/1096

**Comment by eamodio** [comment]
@Alsan the GitLens welcome view shouldn't show more than once, and the _What's New_ notification should only show once per major/minor release (and you can opt out of that with `"gitlens.showWhatsNewAfterUpgrades": false`). 

Are you still seeing this with GitLens 11?

**Comment by Alsan** [comment]
I've switched to code-oss since last month, and didn't notice the startup screen anymore.
