### ISSUE TITLE
Cannot commit after merge

### ISSUE THREAD

**Issue by AnhNN96** [eamodio/vscode-gitlens#1098]
*VSCode Version: 1.47.0

*Window 10

*Gitlens 10.2.2

-First scenario
1. Pull source code
2. Conflict happen
3. Choose "Accept current change"
4. **Save**
5. Choose "Stage Changes" and Commit but it keeps giving me this message:'There are no changes to commit'.
6. After editting source like add a space, i can commit

-Second scenario
1. Pull source code
2. Conflict happen
3. Choose "Accept current change"
4. (**Not save**) 
5. Choose "Stage Changes" and the dialog was popped up "The following file has unsaved changes which won't be included in the commit 
if you proceed xxx.js, would you like to save it before committing ?". i choose "Save all and commit".

i do not understand why i can not commit in the first case.

**Comment by zpc7** [comment]
Hi @AnhNN96 ,Have you execute `git add .` to put your changes(after resolved the conflict) become staged?

**Comment by eamodio** [comment]
GitLens isn't involved in this flow -- that is all handled by the built-in Git extension in VS Code.
