### ISSUE TITLE
Log History in sidebar

### ISSUE THREAD

**Issue by Vishnu05** [eamodio/vscode-gitlens#1099]
If there is log history in this sidebar it would be very useful 
By hovering through branches I can see up to 10 commits, beyond that I'm not able to see the commits 
![image](https://user-images.githubusercontent.com/32086222/91253643-ea890d00-e77d-11ea-8cf1-b464cb05edb7.png)

**Comment by eamodio** [comment]
@Vishnu05 Are you still experiencing this issue in GitLens 11?

**Comment by Vishnu05** [comment]
@eamodio This one is fixed now. It was merged to the normal git plugin. It took a while to understand. 
Thanks this is working fine now. I'm closing the issue.
Thanks again for this feature it really helps and amazing who all contributed to this.
