### ISSUE TITLE
Repositories view - do not show not-pushed changes

### ISSUE THREAD

**Issue by Ten0** [eamodio/vscode-gitlens#1101]
The repository view seems to always show the diff between my working tree and `origin/my-branch` instead of just `my-branch`, polluting the view in case I just want to push several commits in batch later, in order to avoid e.g. triggering tons of CI runs which cost money.

Is it possible to change this behaviour, just showing the diff between my working tree and my last commit on the branch?

**Comment by eamodio** [comment]
I'm sorry but I'm not sure what you are asking -- the _Repositories_ (or now the _Commits_) view shows the diff of files between the commit and the previous commit.

**Comment by Ten0** [comment]
It seems I don't have this issue anymore in the new integration in the source control panel. Thanks!
