### ISSUE TITLE
"Proposed API is only available when..." after updating to Insiders 1.50

### ISSUE THREAD

**Issue by anatolyburakov** [eamodio/vscode-gitlens#1107]
Issue Type: <b>Bug</b>

No steps, this happens after update to VSCode Insiders 1.50

Extension version: 10.2.2
VS Code version: Code - Insiders 1.50.0-insider (bc38b0accb3c62180317c63dbe7323200977db0f, 2020-09-11T12:48:20.764Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-112-generic

**Comment by alefragnani** [comment]
Hi @anatolyburakov ,

But based on this report https://github.com/microsoft/vscode/issues/106499 in VS Code repo, It appears to be a VS Code issue.

Hope this helps

**Comment by anatolyburakov** [comment]
Works now, apparently. Thanks!
