### ISSUE TITLE
Missing commit function.

### ISSUE THREAD

**Issue by FEMotong** [eamodio/vscode-gitlens#1108]
- GitLens Version: v10.2.2
  
- VSCode Version: all
- OS Version: all

Steps to Reproduce:

**What is the current behavior? 

- Missing commit function.
- img:  
  - ![gitlensImg](https://ftp.bmp.ovh/imgs/2020/09/091b4616bdd88738.png)

**What is the expected behavior?**

- Adding this feature is even more perfect!

**Comment by eamodio** [comment]
Committing is already provided by the built-in Git extension in VS Code and I don't see a compelling reason to duplicate it.
