### ISSUE TITLE
Go to previous/next commit when comparing "Compare File with Previous"

### ISSUE THREAD

**Issue by cnshenj** [eamodio/vscode-gitlens#111]
- GitLens Version: 4.3.1
- VSCode Version: 1.13.1
- OS Version: Windows 10 x64

Sometimes, Blame is not enough to figure out who made certain changes. What I do is backtracking on commit history using "Compare File with Previous". It would be very useful to have commands to "Compare File's Previous Commit with its Previous" and "Compare File's Next Commit with its Previous". Thus, I don't have to go back to history, then find the previous commit, then select "Compare File with Previous", again and again.

**Comment by eamodio** [comment]
@cnshenj Currently you can keep executing `Compare File with Previous` (or `Compare Line Commit with Previous`) and it will keep walking back in the history -- assuming when the diff editor opens, you set focus to the left side. Unfortunately the vscode api doesn't let me set the focus automatically.

**Comment by cnshenj** [comment]
Yes. It does help. Thanks!

Two things that need improvement:
1. You already pointed out that the focus is not set automatically due to vscode API limit.
2. It opens a new tab every time. When walking back in history, it could have opened many tabs that need to be closed one by one (can't close all tabs since there are other tabs opened). It would be helpful if I can choose to re-use the existing comparison tab.

**Comment by eamodio** [comment]
@cnshenj Ah good point, I'll make those preview tabs in an upcoming release

**Comment by eamodio** [comment]
@cnshenj When vscode 1.15 is released, those diffs should become preview tabs.

**Comment by eamodio** [comment]
Closing this as this is addresses as much as it can be given the vscode api
