### ISSUE TITLE
Show file history not work in wsl

### ISSUE THREAD

**Issue by littleShy** [eamodio/vscode-gitlens#1119]
- GitLens Version:v10.2.2
  
- VSCode Version:1.49.2
- OS Version:Windows_NT x64 10.0.19041

Steps to Reproduce:

1. open workspacce in wsl
2. right click one source file, select 'Show File History'
3. then it show some message 'unable to show file history, See output channel for more details'
4. message "[2020-09-28 03:58:51:089] ShowQuickFileHistoryCommand
Error: cannot open vscode-remote://wsl%2Bcentos8/mnt/e/code/work/YuYouGame/src/branches/dev/Server2.0-Git/connserver/mnt/e/Code/Work/YuYouGame/src/branches/dev/Server2.0-Git/connserver/ActivityMgr.h. Detail: 无法读取文件'vscode-remote://wsl+centos8/mnt/e/code/work/YuYouGame/src/branches/dev/Server2.0-Git/connserver/mnt/e/Code/Work/YuYouGame/src/branches/dev/Server2.0-Git/connserver/ActivityMgr.h' (Error: 无法解析不存在的文件"vscode-remote://wsl+centos8/mnt/e/code/work/YuYouGame/src/branches/dev/Server2.0-Git/connserver/mnt/e/Code/Work/YuYouGame/src/branches/dev/Server2.0-Git/connserver/ActivityMgr.h")"

**Comment by eamodio** [comment]
Does this still happen in GitLens 11?

**Comment by littleShy** [comment]
thanks, it never happened again.


| |
肖永利
|
|
signalyongli@163.com
|
签名由网易邮箱大师定制
On 11/16/2020 15:32，Eric Amodio<notifications@github.com> wrote：

Does this still happen in GitLens 11?
