### ISSUE TITLE
it reset command not found

### ISSUE THREAD

**Issue by st-schneider** [eamodio/vscode-gitlens#1120]
Issue Type: <b>Bug</b>

Seems like a letter is missing in the `git reset --hard` command when you try to reset to a commit.

Extension version: 10.2.2
VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:30:51.469Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 5|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 3b7acc73-7f05-4994-b539-24b72f428fcd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Should be fixed in GitLens 11.
