### ISSUE TITLE
Git Code Lens views me as multiple authors

### ISSUE THREAD

**Issue by BIKA-C** [eamodio/vscode-gitlens#1124]
![image](https://user-images.githubusercontent.com/50717946/95597672-eeff4180-0a1c-11eb-9b4e-d74558cb5a2c.png)

Where on the top of the line, it shows me twice as the author

**Comment by BIKA-C** [comment]
git log:
![image](https://user-images.githubusercontent.com/50717946/95597823-1f46e000-0a1d-11eb-9caf-546785f89ca7.png)

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?
