### ISSUE TITLE
Naming: Commits vs History

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#1125]
I'm trying to decide on a final name for one of the new views in GitLens 11.

Below you can see the view, currently called _Commits_:

![image](https://user-images.githubusercontent.com/641685/95833998-64635e80-0d0a-11eb-8847-72cba51718e8.png)

Should I keep it as _Commits_ or rename it to _History_? Or something else?

**Comment by bcanzanella** [comment]
tough one as it refers to old commits (history), and possibly new code (not yet repo history)... 👍 for Commits

**Comment by tjx666** [comment]
repo history, haha...

**Comment by eamodio** [comment]
Going to stick with _Commits_. Thanks!
