### ISSUE TITLE
Can't show git history for binary file.

### ISSUE THREAD

**Issue by kendling** [eamodio/vscode-gitlens#1126]
Issue Type: <b>Bug</b>

Call all method to show git history for a binary file.
It will report an error:
Error: cannot open file://path/to/binary/file.

Extension version: 10.2.2
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (16.22GB free)|
|Process Argv|--crash-reporter-id a9aa5e6f-1a2f-49c2-8d0d-0e0158e3fe65 --crash-reporter-id a9aa5e6f-1a2f-49c2-8d0d-0e0158e3fe65|
|Screen Reader|no|
|VM|44%|
</details>

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in the insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
