### ISSUE TITLE
Need a way to quickly diff a revision range (ideally using double dot notation)

### ISSUE THREAD

**Issue by elklein** [eamodio/vscode-gitlens#1127]
I'm looking to quickly be able to diff code when I don't know the last point that I want to diff against. Specifically I like using GitLens to do code reviews given a branch on the remote, but my workflow to do so is not optimal. First I have to use git to figure out how many commits back from the head of the remote branch I want to compare, copy/paste the hash of that commit, and then specify (one at a time) the remote branch to GitLens' `Compare References` tool, and then specify the SHA of the commit I want to compare against.

Ideally I would be able to just say, show me the diff for `origin/master..origin/dev/SomeBranch` and have GitLens figure it out from there.

Is there already some functionality like that, and I just haven't discovered it? If not, would it be hard to add something like that?

**Comment by eamodio** [comment]
Does the _Compare References..._ command in GitLens 11.0.1 do what you are looking for?

**Comment by elklein** [comment]
Yes, but not as efficiently as I would like. I also realize that I'm asking for something optimized and it may just be too small a gain to bother with.

What I want is to enter into the compare references dialog something like `origin/master..HEAD` or `origin/master..origin/dev/BranchWithSomeFeature`. Basically I want to see what has changed between our master branch and some merge request branch, and I don't want to have to go through several levels of dialog to do it. In the perfect world I would have some kind of command line that could do this (i.e. tell vscode to tell gitlens to show me diffs between branch A and branch B).

So to do this right now, my flow is:
1) git co origin/dev/BranchWithSomeFeature
2) git log <options> to figure out what the last commit is that this branch shares with origin/master
3) Copy git sha discovered in #2
3) Go to gitlens "Compare References"
4) Select "Working tree" in the first dialog
5) Paste in git SHA from step #3

Ideally I'd reduce those 5 steps to one.

So feel free to close this and ignore if it's just too special a corner case, but I have a lot of code reviews to do, and this would save a lot of time for me (and I suspect I'm not alone).

Thanks!

**Comment by eamodio** [comment]
@elklein Sorry, but I'm a little confused by your steps as compared to what you want.

Is there a reason this flow doesn't work?
1. Open _Compare References..._ from the command palette
1. Type `origin/master` (or enough for auto-complete) and press enter
1. Type `HEAD` or `origin/dev/BranchWithSomeFeature` and press enter

While it is still 2 steps there is almost the same number of characters needed to be typed (`enter`s rather than `.`s)

**Comment by elklein** [comment]
In my case `origin/master` may be quite a bit further along than the branch I'm diffing against. So I don't want to diff directly between `origin/master` and my review branch, but actually between the common ancestor of `origin/master` and my review branch. So if I specified `origin/master` as the first branch to compare against, and my review branch as the second (using the Compare References UI) I'd wind up including in the diff tens or even hundreds of commits that have gone into `origin/master` since the review branch was created.

So the complexity is really in finding and specifying to gitlens the common ancestor. Maybe I've missed something obvious and there is already some really simple way to do that?

**Comment by eamodio** [comment]
Hrm, but doesn't this work today? You would just look at the _Ahead_ group for the commits/changes, rather then the _Behind_?

**Comment by elklein** [comment]
Yep. This absolutely works today. My experience in the past was that it was doing a straight-up diff between the two branches (with no behind/ahead listing). Either I was just really confused or the new version of gitlens changed this. Either way, I think this can be closed :)

**Comment by eamodio** [comment]
Sweet!  Yeah, before GitLens 11 the changes were intermixed making it really hard.

**Comment by elklein** [comment]
BTW: Thank you for GitLens! It really is indispensable!  VSCode without GitLens would still work for course, but... it would be much less than it is.
