### ISSUE TITLE
alt+c and alt+w key bindings conflicts with add next occurrence's options

### ISSUE THREAD

**Issue by yoshijava** [eamodio/vscode-gitlens#113]
- GitLens Version: 4.3.1
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. ctrl+d to select next occurrence
2. alt+c and alt+w, which are the default key bindings for case sensitivity and select whole word

**Comment by eamodio** [comment]
Opened https://github.com/Microsoft/vscode/issues/31683

**Comment by eamodio** [comment]
Closing as duplicate of https://github.com/eamodio/vscode-gitlens/issues/104
