### ISSUE TITLE
separate stash panel

### ISSUE THREAD

**Issue by yoyoys** [eamodio/vscode-gitlens#1130]
![image](https://user-images.githubusercontent.com/22124891/96404214-f12b8200-120c-11eb-895d-84bbc1c7fadf.png)

Unlike file history, currently stash will come with repositories panel.
This means I need open the tree view to see my stashes.

If there're a separate stash panel, I can use stash easily.

**Comment by eamodio** [comment]
Fixed in GitLens 11, as it breaks the repositories view up into separate views.
