### ISSUE TITLE
Vscode remote - Git Lens complains about version of git

### ISSUE THREAD

**Issue by cjlegg** [eamodio/vscode-gitlens#1134]
- GitLens Version:
  v10.2.2
- VSCode Version:
- OS Version: Windows 10 Local, Centos Linux 7 on remote

Steps to Reproduce:

1. include "module load git/2.27.0" in .bashrc on remote system
2. check .bashrc is being executed when vscode logs in to remote with lines in .bashrc that add to a log
3. Git lens generates error pup-up complaining that git version is 1.8.3.1, which is the system version of git to be found at /usr/bin/git when it should be finding that set by the module, which is at /xxxxx/local/git/2.27.0/bin, and which is found if you type "git -version" and "which git" in the terminal window inside vscode.

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?

**Comment by cjlegg** [comment]
Yes, this still happens with GitLens 11. I am working on remote system. I load a module for git 2.29 in .bashrc – the module is shown as loaded in the internal terminal window of vscode (module list) – but GitLens still complains about the version of the system install of git.  Perhaps the main process for vscode suppresses execution of .bashrc

J.

**Comment by cjlegg** [comment]
I am now on vscode (recent upgrade): 
Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
and on git 2.29 - I have a spack module loaded for that.

Git Lens no longer complains about the git version - closing call
