### ISSUE TITLE
Gitlens is not working for Javascript.

### ISSUE THREAD

**Issue by SDG1060** [eamodio/vscode-gitlens#1136]
Gitlens is working fine for HTML or CSS but it's not working at all in Javascript. Please help me.

**Comment by eamodio** [comment]
I'm sorry, but I need more information than what you've provided to help. What isn't working? Is there something different about the javascript files vs html/css? Are they all part of the Git repository?

Please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by SDG1060** [comment]
The icons, the hover effects etc. And it's like I haven't even installed gitlens when I go to a javascript file. Yet the HTML files are working fine but the gitlens is not working only for script files.

**Comment by eamodio** [comment]
Hrm, very strange. Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.
