### ISSUE TITLE
Blame annotations don't caclulate new margin when scrolling to zoom in VS code

### ISSUE THREAD

**Issue by JasonDiBabbo** [eamodio/vscode-gitlens#1137]
- GitLens Version: 10.2.2
- VSCode Version: 1.50.1
- OS Version: Windows NTx64 10.0.19042

Steps to Reproduce:

1. Enable "Mouse Wheel Zoom" in VS Code Settings
2. Enable "Block scope" under "Git Code Lens" > "Add code lens to the following scopes" > "Block scope"
3. Scroll to zoom in or out

**Expected Result**: The proportion of margin between the code lens and the adjacent code element should remain constant
**Actual Result**: The code lens text begins to grow closer or further away from the code portion

**Comment by eamodio** [comment]
@JasonDiBabbo This is actually a bug in VS Code. Can you open this against the vscode repo please?
