### ISSUE TITLE
Stylus files makes code lens freak out

### ISSUE THREAD

**Issue by lindskogen** [eamodio/vscode-gitlens#114]
Code lens freaks out in `.styl` files, same problem is not present i CSS files.

- GitLens Version: 4.3.1
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Install and enable gitlens
2. Open `.styl` file
3. When writing in the file the inline annotations "code lens" text will hide and show itself repeatedly which makes the file contents jump around.

**Comment by eamodio** [comment]
@lindskogen sorry for the delay on getting back to you (I'm currently on vacation). Is this still an issue with vscode 1.14?

**Comment by lindskogen** [comment]
Yes!

**Comment by eamodio** [comment]
@lindskogen do you have a public repo, or an example file I could use to see this in action?

**Comment by eamodio** [comment]
@lindskogen if I can get a reproducible case I'm hopeful that I could fix the issue

**Comment by eamodio** [comment]
@lindskogen sorry to bug you, but I'd love to get this fixed. :)

**Comment by lindskogen** [comment]
Been unable to reproduce it on my non-work computer, only had this issue on my laptop from a previous job. Maybe it is fixed now, since I cannot reproduce it anymore :)

**Comment by eamodio** [comment]
@lindskogen ok thanks! I'm going to close this then -- please feel free to reopen it if it comes back.

**Comment by cwhenderson20** [comment]
This is actually happening to me as well. [Here's how it looks.](http://imgur.com/a/7yYTr)

- GitLens version: 4.4.0
- VSCode version: 1.15.1
- macOS version: 10.12.6

I have the language-stylus extension installed (version 1.7.3).

Typically what happens is that each block of styles (nested or top-level) each gets its own Code Lens annotation (whether it's "Cannot determine recent change or authors (unsaved changes)" or the actual author/change information). When you make changes to the file, all of those annotations appear and disappear frequently, which makes the file jump around.

This happens with every stylus file, but here's a sample of a file where I've been working on recently: 

```stylus
.promo-code__button--delete
	&:hover
		border-color bootstrap-color("danger", "hover")
		background-color bootstrap-color("danger", "hover")
.promo-code__button--edit
	&:hover
		border-color bootstrap-color("primary", "hover")
		background-color bootstrap-color("primary", "hover")
.promo-code__button--confirm
	&:hover
		border-color bootstrap-color("success", "hover")
		background-color bootstrap-color("success", "hover")
		&:disabled
			cursor not-allowed
			background-color brand-color("grey", "darker")
			border-color brand-color("grey", "darker")
.add-employer-form
	display flex
	button
		margin-left 5px
```

**Comment by eamodio** [comment]
@cwhenderson20 Thank you for the GIF, I think I see what is happening. Can you try adding the following setting:
```json
"gitlens.codeLens.perLanguageLocations": [
    {
        "language": "css",
        "locations": [
            "document"
        ]
    },
    {
        "language": "html",
        "locations": [
            "document"
        ]
    },
    {
        "language": "json",
        "locations": [
            "document"
        ]
    },
    {
        "language": "less",
        "locations": [
            "document"
        ]
    },
    {
        "language": "scss",
        "locations": [
            "document"
        ]
    },
    {
        "language": "vue",
        "locations": [
            "document"
        ]
    },
    {
        "language": "styl",
        "locations": [
            "document"
        ]
    }
]
```

**Comment by cwhenderson20** [comment]
Sure thing! Just added it and restarted VSCode (just to be sure). Same behavior, unfortunately.

**Comment by eamodio** [comment]
As in the gif do you still see the codelens at the top of every class definition?

**Comment by cwhenderson20** [comment]
Yes, I do

**Comment by eamodio** [comment]
Hrm, now I'm a bit confused :) -- Do you have a public repo that I can try this on myself?

**Comment by eamodio** [comment]
Maybe the language server uses the full name `stylus` rather than the extension -- Can you try changing the setting to use `"language": "stylus"`?

**Comment by cwhenderson20** [comment]
Yep, that fixed it!

**Comment by cwhenderson20** [comment]
So does this setting have to stay in the settings.json file or is this a bug?

**Comment by eamodio** [comment]
Great! I'll get a release together that adds that to the GitLens defaults. Thank you for your time and patience!

**Comment by eamodio** [comment]
Once I get the update out, you'll be able to remove the setting.

**Comment by cwhenderson20** [comment]
Great! Thank you for your quick response time and excellent extension!
