### ISSUE TITLE
Weird avatar image

### ISSUE THREAD

**Issue by Bios-Marcel** [eamodio/vscode-gitlens#1142]
Hey, so, I've recently downloaded GitLens and without having changed anything, it displays something that looks like a "turd man" as my avatar. I do not have a gravatar or libavatar account and nor is this my GitHub image (as you can see). How do I find out where this image is coming from?

This is what it looks like:
![turdman](https://user-images.githubusercontent.com/19377618/98160070-f14ea180-1edd-11eb-8e10-05b1c569c53a.png)

**Comment by eamodio** [comment]
That is by-design, as that icon is one of the gravatar fallback icons. You can choose which set of gravatar fallback icons to use via:
```json
  // Specifies the style of the gravatar default (fallback) images
  //  - identicon: A geometric pattern
  //  - mp: A simple, cartoon-style silhouetted outline of a person (does not vary by email hash)
  //  - monsterid: A monster with different colors, faces, etc
  //  - retro: 8-bit arcade-style pixelated faces
  //  - robohash: A robot with different colors, faces, etc
  //  - wavatar: A face with differing features and backgrounds
  "gitlens.defaultGravatarsStyle": "robohash",
```

GitLens 11 also adds GitHub avatars, so hopefully that will reduce the times a fallback will happen.
