### ISSUE TITLE
Add interactive rebase option for commit in "Show History" dropdown

### ISSUE THREAD

**Issue by plwalsh** [eamodio/vscode-gitlens#1146]
When choosing the `GitLens: Show Current Branch History` command from the command palette, it would be great if each commit's context menu gave an option to begin an interactive rebase from that commit. This option appears to exist, indirectly, when right-clicking on a commit in the sidebar view and choosing `Rebase Current onto Commit...` &mdash; choosing that option opens a menu that lets you choose either a regular rebase or an interactive rebase. However, when selecting a commit in the "Show History" dropdown, I do not see any similar "rebase" option.

My current workflow consists of opening the command palette (F1), choosing `GitLens: Show Current Branch History`, scrolling down to the relevant commit, selecting it, then selecting `Copy Commit ID to Clipboard`. At that point, I go back to the command line and type `git rebase -i <paste-id>`. Cutting out the command-line typing with a direct menu option would be awesome.

**Comment by eamodio** [comment]
Added in GitLens 11
