### ISSUE TITLE
Icon for "Toggle File Blame Annotations" displays an artifact extruded line in 'off' state at certain zoom levels

### ISSUE THREAD

**Issue by AiwarikiaR** [eamodio/vscode-gitlens#1147]
Issue Type: <b>Bug</b>

Open an editor pane with a file located in a git repo (VS Code with GitLens)
Reset zoom level (Ctrl+NumPad0)
Zoom out two times (Ctrl+-)
Theme: Monokai Dimmed
Windows display setting "Change the size of text, apps and other items" set to scale 150% (automatic/recommended based on 15" laptop screen)

Observed issue: the icon for "Toggle File Blame Annotation" shows a line extending down to the the right, as an extension of one of the branch lines in the icon:
![image](https://user-images.githubusercontent.com/43793099/98870235-4dcc3680-2473-11eb-82f7-720ac284e069.png)

Extension version: 10.2.3
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?

**Comment by AiwarikiaR** [comment]
Yes, still present:
![image](https://user-images.githubusercontent.com/43793099/99236572-aa26b180-27f7-11eb-8e11-7e66c51f18d2.png)

Extension version: 11.0.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

**Comment by eamodio** [comment]
I can't reproduce this, but I tweaked the SVGs a bit to see if that would help. Can you please verify this fix in the latest insiders version? 

You can install the insiders version from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by AiwarikiaR** [comment]
Issue seems resolved by that svg tweak (replace paths with circles and lines):
![image](https://user-images.githubusercontent.com/43793099/101208534-9f32a480-3672-11eb-8455-98fe6950ec0e.png)

Extension version: 2020.12.404
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763
