### ISSUE TITLE
Year value shows as 'yyyy' when hovering-over a change

### ISSUE THREAD

**Issue by jethas-bennettjones** [eamodio/vscode-gitlens#1149]
![image](https://user-images.githubusercontent.com/62298251/99090331-b6a6d200-258b-11eb-8453-a7180dd5ce9c.png)

**Comment by eamodio** [comment]
@jethas-bennettjones Are you still experiencing this issue with GitLens 11?

**Comment by jethas-bennettjones** [comment]
Hi @eamodio,

This was happening on my work PC. I'll be in the office later this week so I'll update you then.
