### ISSUE TITLE
Icons not showing in interactive rebase

### ISSUE THREAD

**Issue by DDeis** [eamodio/vscode-gitlens#1151]
Hello, I'm a really enthusiastic with the new interactive rebase feature that comes with GitLens 11, though some icons are not showing, instead there is a square for **branch**, **commit** and **toggle down** icons as if a font was missing or something.

![Capture d’écran 2020-11-14 à 22 56 24](https://user-images.githubusercontent.com/2820899/99158090-6a64aa80-26cf-11eb-8099-83c55c887157.jpg)

- GitLens Version: `11.0.0`
- Git Version: `2.24.3`
- VSCode Version: `1.51.1`
- OS Version: MacOS `11.0.1` & `10.15.7`
- Editor font family setting: `Fira Code, Menlo, Monaco, 'Courier New', monospace`

**Comment by lanmeidada** [comment]
Me,too

**Comment by eamodio** [comment]
@lanmeidada Are you also on macOS?

**Comment by ceecko** [comment]
I'm on Windows 10 and I can confirm this. It was even worse before restarting VSCode.
The commits were not visible at all, there was just the "Interactive Rebase" heading and labels of buttons (Start rebase and Abort) without the borders or background.

A suggestion - add a note this page is coming from gitlens so people can find an easy way to disable it (see #1153)

**Comment by DDeis** [comment]
> A suggestion - add a note this page is coming from gitlens so people can find an easy way to disable it (see #1153)

Indeed, I also had a hard time finding out that view was coming from GitLens 😅

**Comment by plwalsh** [comment]
I'm also on Windows 10, and seeing squares like that in other places too, such as the gitlens settings editor:

![image](https://user-images.githubusercontent.com/43576448/99272561-eeb14d80-27f5-11eb-8100-16ac3b42857f.png)

Not sure if that's intentional, but it seems odd.

**Comment by eamodio** [comment]
Thanks for the info. Definitely not expected. It looks like the codicons font (the built-in vscode icon set) is not being loaded correctly.

**Comment by eamodio** [comment]
It looks like this issue is somewhat related to https://github.com/microsoft/vscode/issues/85872

@plwalsh @DDeis @ceecko @lanmeidada Do any of you have any other missing icons?

**Comment by ceecko** [comment]
@eamodio No, all other icons are fine.

**Comment by eamodio** [comment]
When you see the issue you can run the `Open Webview Developer Tools` command from the command palette and see if there are any errors in the console?

**Comment by plwalsh** [comment]
I happened upon an old issue you submitted (https://github.com/microsoft/vscode/issues/63967)  just trying to figure out how to open that dang console 😅.. `Open` did nothing, `Toggle` opened it.

But here's what popped up in the console when I launched an interactive rebase:

![image](https://user-images.githubusercontent.com/43576448/99285623-c92c4000-2805-11eb-9dce-7a69d4588eaa.png)

**Comment by raphinesse** [comment]
Same issue for me in GitLens Settings & Interactive Rebase Editor (on Ubuntu)
