### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by k6b2yjxma7li** [eamodio/vscode-gitlens#1152]
- Issue Type: `Bug`
- Extension Name: `gitlens`
- Extension Version: `11.0.0`
- OS Version: `Linux x64 4.15.0-123-generic`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 73,
		"activateCallTime": 1,
		"activateResolvedTime": 63,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "eamodio.gitlens",
				"_lower": "eamodio.gitlens"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "No diff tool found"
		},
		{
			"name": "Error",
			"message": "No diff tool found"
		}
	]
}
```

**Comment by eamodio** [comment]
I'm not sure what this issue is about.

**Comment by k6b2yjxma7li** [comment]
It turned out to be some one-time problem and it didn't happen again.
Sorry for bothering you.
