### ISSUE TITLE
Show File History

### ISSUE THREAD

**Issue by rzee01** [eamodio/vscode-gitlens#1156]
This feature was in the previous version. When right clicking a file and clicking "Show File History", you would be able to view all the changes in the command palette. I don't mind that this was moved, but you used to also be able to view all the previous changes of the file before in situations where the file was renamed. Now it looks like you have to go through all the repo commits. It also looks like you can only view the changes after a file rename in the file history view.

**Comment by eamodio** [comment]
While I removed this option from the right-click menu (to reduce the number of options and possible confusion with _Open File History_, the _Show File History_ command can still be access from the command palette. Also the rename following was disabled by default (because it can cause too many issues if you aren't expecting it), but can be re-enabled by toggling this:

![image](https://user-images.githubusercontent.com/641685/99217942-35c42200-27a7-11eb-9b6a-181bbf37ca0b.png)

or by setting `"gitlens.advanced.fileHistoryFollowsRenames": true` in your `settings.json` (the toggle above just sets the setting)

As for the view there is an issue #1148 that might be giving you issues with rename following, which will be fixed shortly.

**Comment by eamodio** [comment]
Let me know if `11.01` works for you.

**Comment by rzee01** [comment]
Thank you so much, This helped a lot.

What I meant from accessing the Show File History command in the command palette is that in the previous versions versions before version 11, you could see the File History in the command palette instead of it taking you to the side bar. It was nice to see all the various options you can click on when clicking a certain commit of the file.  I am completely fine with it directing you to the side bar instead.

**Comment by eamodio** [comment]
Today, the _Show File History_ command from the command palette does very similar to what it used to -- shows the file history directly in the quick pick menu. While _Open File History_ will open the _File History_ view with the history of the current or selected file.

@rzee01 are you seeing something different?

**Comment by souradeep-nanda** [comment]
Please add this to the documentation. Over here preferably. I was scared for a moment. 
![Screen Shot 2020-12-08 at 9 55 21 AM](https://user-images.githubusercontent.com/72371264/101439862-7e50a480-393b-11eb-9812-b1252fead0e9.png)

**Comment by eamodio** [comment]
@souradeep-nanda I'm not sure what you'd like added to the documentation, but please feel free to send a PR updating the docs! Thanks.

**Comment by rzee01** [comment]
Everything is fine. I think I just liked how everything was shown in the command palate since it seems easier to see. I never really liked how VS Code's Github section looked and would always use your extension to see the options for Git or Github. In version 10,, all the options were placed like this:

![image](https://user-images.githubusercontent.com/24459985/102855406-95d76500-43f2-11eb-8ab3-78e159566bb4.png)

**Comment by eamodio** [comment]
@rzee01 That still exists today -- using the _GitLens: Show File History_ command from the command palette (`ctrl+shift+p` or `cmd+shift+p`. 

Is your issue/request that there is no longer the "show" version of the file history in the content menu of files in the Explorer side bar? As I only have the _Open File History_ option there.

**Comment by rzee01** [comment]
Going back to the version before 11, it looks like I used to click on "Show File History" in the context menu which showed your commits pertaining to the particular file in the command palette. I think I liked it when you click on a commit on a particular file, it brought up those options I have in my previous post. It also looked cleaner when that option in the context menu took you to the command palette and showed the file's history as shown below.
![image](https://user-images.githubusercontent.com/24459985/103703491-9dac1300-4f75-11eb-9b2e-cc9db656ddbe.png)

**Comment by eamodio** [comment]
OK, thanks -- as I've mentioned that still exists today -- using the _GitLens: Show File History_ command from the command palette. 

But I will add an additional _Quick Open File History_ entry to all the menus where _Open File History_ currently lives.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
