### ISSUE TITLE
GitLens report `X files changed` when comparing working tree with a branch having identical files

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [eamodio/vscode-gitlens#1157]
- GitLens Version: 11.0.0
- Git Version: 2.29.2.windows.2

- VSCode Version: 1.51.0
- OS Version: Windows 10 build 19042.630

Steps to Reproduce:

1. clone https://gitlab.com/c2ba/c2ba-toolbox
2. `git checkout -b _gitlens_compare_tmp1`
3. in VSCode: F1 -> `GitLens: Compare working tree with` and select `origin/_gitlens_compare_tmp2`

In the `Search & Compare` view you should see `5 files changes` reported under `Behind` and `Ahead` (See (1) in screenshot below). If you click on any file under these lists, the diff view opens but reports no changes.

I often use this functionality when I rewrite my branches history to check that I keep the same files on the original and the rewritten branch. Fortunatly when I compare the 2 branches `_gitlens_compare_tmp1` and `_gitlens_compare_tmp2` under the `Commits` view I get `No files changed` under `Ahead`, so I can still compare my branches (see (2) in screenshot below). This is less convenient though because there is no `Compare current branch with` command that I could use with `F1`, so I need to use the UI.

![image](https://user-images.githubusercontent.com/1659465/99199517-0958d780-27a0-11eb-8b5a-fd4c4c170a9d.png)

PS: Thanks you for your work on this extension btw, release 11.0.0 is great !

**Comment by Celeborn2BeAlive** [comment]
@eamodio Just tested Gitlens 11.0.1 on the example I gave and the issue is not fixed. Actually it's worse, the case I was mentioning that worked (compare to branch in commits view) is now broken, so I cannot easily compare files of a rebased branch and the original one :/
Here is a new screenshot of the setup:

![image](https://user-images.githubusercontent.com/1659465/99326190-1c3edb00-2878-11eb-8bd7-e3a0407f57c5.png)

(1): still broken
(2): was ok, now is broken

**Comment by eamodio** [comment]
Ah, sorry I misunderstood your original issues (although there was a different bug there).

In v11.0.4 I've added back the ability to compare file changes between the references (regardless of ahead/behind). Sorry for unintentionally removing this feature 🤦‍♂️
