### ISSUE TITLE
gitlens in sidebar disappeared

### ISSUE THREAD

**Issue by dennisleung** [eamodio/vscode-gitlens#1158]
- GitLens Version: v11.0.0
- Git Version: 2.9.5

- VSCode Version: 1.51.1
- Node.js Version: 12.14.1
- OS Version: Catalina 10.15.7

Steps to Reproduce:

1. gitlens extension was enabled but did not show in sidebar
![image](https://user-images.githubusercontent.com/5787225/99207326-a6dff580-27f8-11eb-95b5-916e54c3484f.png)
![image](https://user-images.githubusercontent.com/5787225/99207337-afd0c700-27f8-11eb-81a7-d44464d9bdca.png)

2. after downgrade to v10.2.3，icon on sidebar appears.

**Comment by eamodio** [comment]
GitLens 11 moves all views to the _Source Control_ side bar by default. You can move them back to the _GitLens_ side bar via the _Set Views Layout_ (`gitlens.setViewsLayout`) command or individually via drag and drop

**Comment by y912765390** [comment]
gitlens.setViewsLayout  How do you do that? Can you be a little bit more specific

**Comment by eamodio** [comment]
Type _Set Views Layout_ in the Command Palette (ctrl+shift+p)

**Comment by y912765390** [comment]
think you very much&nbsp;
