### ISSUE TITLE
Get full commit message on hover

### ISSUE THREAD

**Issue by mgarf** [eamodio/vscode-gitlens#116]
Not so much of an issue than a configuration question.

How do i get the full commit message on hover. Right now its only showing the first line.

**Comment by eamodio** [comment]
Because `git blame` only supports returning the "summary" of the commit message, I can't easily show the full commit message (without it being prohibitively expensive when generating the blame), but if you have the active line blame on -- then I do get the full commit message.

Hope that helps!

**Comment by mgarf** [comment]
@eamodio yep!, thank you so much for your help.

**Comment by antcodd** [comment]
What exactly are the conditions required to make full commit message work? I only see the summary line(s) on the trailing line hover even when not in blame mode (if the commit is formatted incorrectly without the blank line I can see multiple lines but never see the commit 'details'). Using git 2.7.4

The copy commit message to clipboard also doesn't appear to give the full commit details.

**Comment by eamodio** [comment]
@mgarf I've figured out a way to both increase blame annotation performance AND provide full commit messages in the hovers! Check out the new beta: https://github.com/eamodio/vscode-gitlens/releases/tag/v5.1.0-beta

**Comment by eamodio** [comment]
@antcodd could you open another issue for this please? This issue is really about adding a new feature (in just hovers), where as it sounds like you are hitting some bug somewhere. Thanks! Be sure to follow the issue notes and provide logs if possible.
