### ISSUE TITLE
Gitlens icon disappears from sidebar in version 11.0.1

### ISSUE THREAD

**Issue by abryant710** [eamodio/vscode-gitlens#1162]
- GitLens Version: 
11.0.1

- Git Version:
git version 2.28.0

- VSCode Version:
1.51.1 x64

- OS Version:
macOS Catalina 10.15.7

Steps to Reproduce:

1. Update to newest version of Gitlens.

The icon disappears from the sidebar. 

Before:
<img width="534" alt="Screenshot 2020-11-16 at 09 30 07" src="https://user-images.githubusercontent.com/21152436/99236348-ffaa9080-27ee-11eb-9f9f-265c05003ef4.png">

After:
<img width="495" alt="Screenshot 2020-11-16 at 09 30 15" src="https://user-images.githubusercontent.com/21152436/99236366-03d6ae00-27ef-11eb-8e65-4234945a4089.png">

I'm having to downgrade to 10.2.3 for it to reappear.

**Comment by vostokwork** [comment]
Same.

**Comment by UntilGone** [comment]
same to me

**Comment by 2garryn** [comment]
Same in Windows 10

**Comment by vostokwork** [comment]
1 

![image](https://user-images.githubusercontent.com/37534401/99248572-bcb1e280-2819-11eb-851d-e6f4a5599e2e.png)


2 

![image](https://user-images.githubusercontent.com/37534401/99248595-c5a2b400-2819-11eb-956d-ba6cbc1367be.png)


3 

![image](https://user-images.githubusercontent.com/37534401/99248621-ce938580-2819-11eb-8121-5ca67d84a3a4.png)

**Comment by FE-wuhao** [comment]
> 1
> 
> ![image](https://user-images.githubusercontent.com/37534401/99248572-bcb1e280-2819-11eb-851d-e6f4a5599e2e.png)
> 
> 2
> 
> ![image](https://user-images.githubusercontent.com/37534401/99248595-c5a2b400-2819-11eb-956d-ba6cbc1367be.png)
> 
> 3
> 
> ![image](https://user-images.githubusercontent.com/37534401/99248621-ce938580-2819-11eb-8121-5ca67d84a3a4.png)

you saved me! when i find the icon disappeared ,i feeled so sad that i just wanted to say fuck.but now,the only word i want to say is :thank you!thank you!!thank you!!!

**Comment by mmkvdev** [comment]
It's Simple,

Open your VS code editor.  
Click 'CTRL + SHIFT + P' to open the command palette   >   Type 'gitlense' > Click 'Gitlens: Set Views Layout' > Select 'Gitlens Layout'.

That's it, you're all good to go!!

**Comment by abryant710** [comment]
@mmkvdev @vostokwork that has not fixed the issue for me. I have had to downgrade to 10.2.3 again.

**Comment by abryant710** [comment]
OK. Sorry, this is fixed from the advice above from @mmkvdev @vostokwork, you just need to make sure you have a workspace open that is using git for the icon to appear. Thanks!

**Comment by LeachZhou** [comment]
Thanks!
