### ISSUE TITLE
Use Interactive Rebase Editor when run from GitLens command (regardless of Git config)

### ISSUE THREAD

**Issue by Hrach-H** [eamodio/vscode-gitlens#1163]
Guys, I cannot find a way to interactively rebase using the new interactive editor. Could someone please help me?

**Comment by AndreyWV** [comment]
I join this question, when I select `Rebase current branch onto Commit...` interactive rebase opens at integrated terminal.

**Comment by eamodio** [comment]
Currently in order for it to work you'd need to have Git configured to use VS Code as your Git editor:
https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreeditor

Although if you just want this for rebasing, you can set:
https://git-scm.com/docs/git-config#Documentation/git-config.txt-sequenceeditor

I will look into automatically using VS Code as the rebase editor when using rebase from within GitLens
