### ISSUE TITLE
Is there any way to set the default behavior of the File Annotations button?

### ISSUE THREAD

**Issue by lymims** [eamodio/vscode-gitlens#1165]
I'd like to do Toggle File Blame with a single click, like the previous version do.

But in this version, I've to select a toggle mode in each click.

![image](https://user-images.githubusercontent.com/9443706/99264340-4a61f200-285b-11eb-88a0-c173b12115aa.png)

Is there any way to set the default behavior of that button?

**Comment by eamodio** [comment]
Not currently, I can look into adding an option, if enough people feel it is needed.

**Comment by tgreen7** [comment]
I also preferred the single click for toggle blame.

**Comment by arrpee** [comment]
Can I work on this? Really prefer having it as a button.

**Comment by eamodio** [comment]
@arrpee sure! It should be pretty straightforward
