### ISSUE TITLE
Enormous avatars in interactive rebase view

### ISSUE THREAD

**Issue by rainersigwald** [eamodio/vscode-gitlens#1166]
Issue Type: <b>Bug</b>

1. Check out https://github.com/dotnet/msbuild to 0eb025d.
2. Command line (with `EDITOR=code --wait`): `git rebase -i HEAD~~~~~~`
3. For some reason the avatar for Forgind is enormous, while mine and others are fine.

![image](https://user-images.githubusercontent.com/3347530/99282580-81072080-27f9-11eb-82e6-ba9849c70ebf.png)

I'm on Windows and I'm running at 125% DPI. And I don't think the user in question has changed their GitHub avatar from the default, while the working ones have.

Extension version: 11.0.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (42.99GB free)|
|Process Argv|. --crash-reporter-id 51716a43-65c8-4b52-a3f7-323ea6f66913|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Argh, bitten again by GitHub not honoring the avatar sizes for fallbacks. I'll get this fixed up.
