### ISSUE TITLE
Can't open rebase editor

### ISSUE THREAD

**Issue by roblourens** [eamodio/vscode-gitlens#1167]
- Trigger interactive rebase
- This prompt appears but I can't confirm

![Nov-16-2020 16-52-57](https://user-images.githubusercontent.com/323878/99325985-3fdc3400-282c-11eb-98a8-f4c73fe850fa.gif)

Side note, could we get this as a command in the command palette? I would prefer that vs finding it in a context menu

**Comment by eamodio** [comment]
@roblourens In that case there were no commits to rebase -- so you can only cancel.

What command would you want in the command palette? Right now most GitLens git command are accessible from the command palette via the Git Command Palette command

**Comment by roblourens** [comment]
Oh, the cancel message clearly says that. I thought that I rebased via the cli after this, but maybe not.

I didn't know about the git command palette, thanks.

So I tried it again and now I do see the expected thing. But it runs the command in a terminal and opens vim which is my git editor. So then I realized that I am supposed to set my git editor to vscode to get this new experience. 

I don't actually want to do that, my mindset is that sometimes I am doing git things through a UI in vscode, and sometimes I am just using the terminal, and I want to use vim in the terminal but use the UI when in vscode. Is that something that I can configure or that you've thought about?

**Comment by eamodio** [comment]
@roblourens Yeah, that scenario will be fixed with https://github.com/eamodio/vscode-gitlens/issues/1163

It was trickier than I thought -- getting the running vscode executable on macOS is iffy, and over remote I end up falling back to `code[-insiders|-exploration]` being on the path. Wish we had an `env` property to get the running exe

**Comment by roblourens** [comment]
Oh ok cool, thanks!
