### ISSUE TITLE
After installing GitLens, no icon appears on the left bar

### ISSUE THREAD

**Issue by jonathanvila** [eamodio/vscode-gitlens#1174]
- GitLens Version: 11
- Git Version: `run git --version` : 2.26.2

- VSCode Version: `run code --version` 1.51.1
- OS Version: Fedora 32

Steps to Reproduce:

1. Install extension
1. Expect to see the icon on the left bar

Already checked the log and I don't see any error.

**Comment by jonathanvila** [comment]
Changing the Layout has fixed the issue. : Ctrl+P+ Git Lens Set Views Layout

**Comment by eamodio** [comment]
@jonathanvila did this view not show up for you?

![image](https://user-images.githubusercontent.com/641685/100495587-f4266600-311a-11eb-846d-837154800edb.png)
