### ISSUE TITLE
GitLens disables links for merging CodeLens

### ISSUE THREAD

**Issue by jesshart** [eamodio/vscode-gitlens#1175]
- GitLens Version: v11.0.1
- Git Version: 2.24.3

- VSCode Version: 1.51.1
- OS Version: 10.15.7

Steps to Reproduce:

1. Use VSCode as mergetool

GitLens enabled:
![2020-11-18 12 47 15](https://user-images.githubusercontent.com/59590184/99573869-3eca1480-299c-11eb-8b61-f3029120da70.gif)

GitLens disabled, close VScode, and reopen:
![2020-11-18 12 49 31](https://user-images.githubusercontent.com/59590184/99574110-92d4f900-299c-11eb-9a0a-f8da9e97a856.gif)

**Comment by eamodio** [comment]
@jesshart Do you still see this? I can't reproduce it.
