### ISSUE TITLE
Could line history and file history both exist like before?

### ISSUE THREAD

**Issue by gamesover** [eamodio/vscode-gitlens#1177]
First, it is very nice for deep integration of gitlens into vscode. Thank you so much.

Now, line history and file history are sharing one block and you have to toggle either of them.

Actually, both are important and the most used feature to me ;)

Is there a way to present the line history and file history like before.

That is, each has their individual block?

If there is no space left, I have no problem to turn off branches/remotes/stashes block.
Since I mainly rely on git graph for those things, which offers a nice gui interface and makes the things much simple.

**Comment by eamodio** [comment]
You can re-enable the old line history, via the `"gitlens.views.lineHistory.enabled": true` setting.

**Comment by eamodio** [comment]
If enough users feel it is warranted, I could re-add the configuration options to the GitLens Settings UI.

**Comment by gamesover** [comment]
@eamodio thank you the reminder. I've set `"gitlens.views.lineHistory.enabled": true`. but nothing happened. I cannot find `line history`, only `file history`.

**Comment by eamodio** [comment]
Sorry, I should have mentioned, once you enable that, the view will still be hidden, you'd need to run the _Show Line History View_ command from the command palette. Or right-click on a view header in the Source Control side bar, and check _Line History_

**Comment by gamesover** [comment]
@eamodio , amazing, everything is back. That's exactly what I want.

Thank you so much!

**Comment by muz3** [comment]
Both fileHistory and lineHistory are pretty helpful. I used to have customized shortcut option for both of them. But they seemed not available any more. 
"command 'gitlens.views.fileHistory:gitlens.focus' not found"

**Comment by eamodio** [comment]
@muz3 the command is now `gitlens.views.fileHistory.focus`, and if you re-enable the line history view, then you can also use the `gitlens.views.lineHistory.focus` command

**Comment by slaughtering** [comment]
helpful
