### ISSUE TITLE
stash all changes has no effect when the number of files is large

### ISSUE THREAD

**Issue by AlCalzone** [eamodio/vscode-gitlens#1183]
- GitLens Version: 11.0.1
- Git Version: 2.28.0.windows.1

- VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
- OS version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Have a bunch of changes
2. Click the icon for stash all changes
3. Enter stash message
4. nothing happens

![ezgif-6-3a999e679625](https://user-images.githubusercontent.com/17641229/98813644-cf48a800-2424-11eb-963c-e886b6aea17a.gif)

It does seem to work if the number of changes is small (a handful of files). The 215 files above seem to be to much.

(originally reported in https://github.com/microsoft/vscode/issues/110390)

**Comment by eamodio** [comment]
We should add a warning when the number of files it too large for git to handle on the command line.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by AlCalzone** [comment]
Will do!

**Comment by AlCalzone** [comment]
Seems to work:
![grafik](https://user-images.githubusercontent.com/17641229/104074551-b5eb8e80-5210-11eb-9676-8b6d96eccea9.png)
