### ISSUE TITLE
Context menu has disappeared

### ISSUE THREAD

**Issue by ChrisBAshton** [eamodio/vscode-gitlens#1184]
- GitLens Version: 11.0.1
- Git Version: 2.24.1
- VSCode Version: 1.51.0
- OS Version: macOS Mojave 10.14.6

In the past few days, I've found that I no longer get the contextual menu options I had before. Right-clicking used to give me options to Copy Remote URL, which I used regularly. I can still do this using `CMD + SHIFT + P` and then searching for "GitLens: Copy Remote URL" but it's nowhere near as convenient.

I'm guessing I've triggered a shortcut somewhere which disables the context menu, but I don't know how to get it back. This is my settings.json:

```json
{
    "explorer.openEditors.visible": 0,
    "window.zoomLevel": 1,
    "editor.wordWrap": "on",
    "javascript.validate.enable": false,
    "editor.minimap.enabled": false,
    "explorer.confirmDragAndDrop": false,
    "gitlens.currentLine.scrollable": false,
    "workbench.statusBar.visible": false,
    "workbench.activityBar.visible": true,
    "breadcrumbs.enabled": true,
    "explorer.confirmDelete": false,
    "gitlens.menus": null
}
```

I've tried removing the last line of the JSON and that didn't help. Any help would be appreciated!

**Comment by tvsbrent** [comment]
I believe that change is intentional, based on what I read in the change log:

> Refines all of the GitLens contributed menus to reduce noise and improve usability

That makes sense, however, I would like to restore them and, o far, I haven't found a way to do so.

**Comment by tvsbrent** [comment]
Actually, I take it back, they are now here:

![image](https://user-images.githubusercontent.com/10372284/99884130-b183fb80-2bf9-11eb-8093-ba818c4b5e55.png)

**Comment by eamodio** [comment]
Yeah, this is intentional. In v11, many menu items have been moved to submenus, but I can't think of any I actually removed.

**Comment by ChrisBAshton** [comment]
> Actually, I take it back, they are now here:
> 
> ![image](https://user-images.githubusercontent.com/10372284/99884130-b183fb80-2bf9-11eb-8093-ba818c4b5e55.png)

Thanks for the screenshot. It wasn't appearing for me, even after updating the extension, and when I went into my settings it just told me I need to edit my settings.json and didn't give any hint as to what to put in there:

![Screenshot 2020-11-23 at 08 31 12](https://user-images.githubusercontent.com/5111927/99941676-558ab580-2d66-11eb-983c-b077c7c85eea.png)

![Screenshot 2020-11-23 at 08 31 16](https://user-images.githubusercontent.com/5111927/99941685-5885a600-2d66-11eb-8b6b-9d24bc45bc2e.png)

But then Visual Studio Code had an update, which I applied, and then restarted VSCode. Now I see the 'Copy as' submenu. 🎉

**Comment by eamodio** [comment]
@ChrisBAshton what version did you update from and to? I didn't think there were any recent bug fixes to menus.


As for the menu settings, it is MUCH easier to use GitLens' Setting editor than vscode's. Use _GitLens: Open Settings_ from the command palette.
