### ISSUE TITLE
How to turn off blame annotations above the lines for specific file types?

### ISSUE THREAD

**Issue by AlCalzone** [eamodio/vscode-gitlens#1185]
- GitLens Version: 11.0.1
- Git Version: 2.28.0.windows.1

- VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
- OS version: Windows_NT x64 10.0.19041

Steps to Reproduce:

Since one of the more recent updates, I'm seeing duplicate blame annotations in markdown files:
![grafik](https://user-images.githubusercontent.com/17641229/99650693-0424b280-2a56-11eb-80ef-d3c535d6a6b6.png)

The one behind the line has been there forever, the one above each line is new and can be really irritating because it takes seconds to load in some files. And as you can see, it introduces a lot of visual noise with duplicate information.

I would like to turn that off for markdown files, but I cannot figure out which option does this.

**Comment by eamodio** [comment]
You can add the following to your `settings.json`, where `[markdown]` can be any supported vscode language:
```json
	"[markdown]": {
		"gitlens.codeLens.scopes": ["document"]
	},
```

You can also set `"gitlens.codeLens.scopes": []` if you even want to disable the code lens on the first line too.

**Comment by AlCalzone** [comment]
Thanks - that worked. I wouldn't ever have guessed that this is the correct option when looking through the available options in VSCode though.
