### ISSUE TITLE
Project with multiple repos

### ISSUE THREAD

**Issue by xiki808** [eamodio/vscode-gitlens#1186]
I have a project, made up of multiple repositories that are not at root level but are nested at 1 or 2 levels. GitLens picks up these repos but only when I have a file for the repo open. Is there a way how to keep all repos active and showing, without the need to open their files?

**Comment by eamodio** [comment]
You can set `"gitlens.advanced.repositorySearchDepth": 2` (or greater) to change how deep GitLens will search for repositories.
