### ISSUE TITLE
Merge commits aren't displayed on the new "rebase interactive GUI"

### ISSUE THREAD

**Issue by DanielGnzlzVll** [eamodio/vscode-gitlens#1189]
- GitLens Version:
````
v11.0.1
`````
- Git Version: `run git --version`
````bash
(base) PS C:\Users\jgonzalez\Documents\GitHub\gitlen-issue> git --version
git version 2.22.0.windows.1
````

- VSCode Version: `run code --version`
````bash
(base) PS C:\Users\jgonzalez\Documents\GitHub\gitlen-issue> code --version
1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
````
![image](https://user-images.githubusercontent.com/22230373/99666484-104e4700-2a39-11eb-8c37-00bf9fa5c05e.png)

Steps to Reproduce:

1.
````bash
git clone https://github.com/DanielGnzlzVll/gitlen-issue.git
````

2.
````bash
git rebase -i --root
````

**Comment by plwalsh** [comment]
Rebasing drops merge commits by default. You would need to use the [`--rebase-merges`](https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---rebase-mergesrebase-cousinsno-rebase-cousins) option, introduced in git v2.18.0, to show them in an interactive rebase

**Comment by DanielGnzlzVll** [comment]
@plwalsh you are right.
