### ISSUE TITLE
Comparing line's commit to working 

### ISSUE THREAD

**Issue by raldred** [eamodio/vscode-gitlens#119]
Comparing commit to working tree opens two empty untitled vscode windows.

- GitLens Version: 4.3.1
- VSCode Version: 1.14.1
- OS Version: macOS 10.12

Steps to Reproduce:

1. Select a line/file
2. Select Directory compare with working tree
3. Observe two blank vscode windows opened.

**Comment by eamodio** [comment]
@raldred did you really mean directory compare? Because that just launches `git difftool` with the specified branches.

**Comment by eamodio** [comment]
@raldred feel free to reopen this with more details if you are still experiencing an issue. Thanks!
