### ISSUE TITLE
GitLens views don't auto-refresh if VS Code is open to a subfolder of a repository

### ISSUE THREAD

**Issue by wiegell** [eamodio/vscode-gitlens#1191]
- GitLens Version: 11.0.1
- Git Version: 2.28.0

- VSCode Version: 1.51.1
- OS Version: macOS 10.15.4

Steps to Reproduce:

Fetch in either sourceontrol -> changes -> fetch or in terminal and gitlens won't autorefresh even though the option is enabled. Tried disabling, reloading, enabling, reloading to no avail.

The "source-control" expansion panel will react to e.g. commits made from terminal, but "branches" expansion panel will not update and show the green symbol suggesting, that the branch is ahead of remote.
Tried setting "gitlens.outputLevel": "debug", but there is no output.

I also have Git: Autorefresh set to true.

**Comment by eamodio** [comment]
Can you please verify this fix in the latest insiders version? 

You can install the insiders version from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by wiegell** [comment]
Still not working as intended on:
<img width="368" alt="Screenshot 2020-11-29 at 09 45 12" src="https://user-images.githubusercontent.com/29224981/100537313-b7946080-3227-11eb-8824-f213d5f04f66.png">
Before commit:
<img width="381" alt="Screenshot 2020-11-29 at 09 43 24" src="https://user-images.githubusercontent.com/29224981/100537328-cb3fc700-3227-11eb-948d-8134e61106ab.png">
After commit (still no auto-refresh):
<img width="383" alt="Screenshot 2020-11-29 at 09 43 47" src="https://user-images.githubusercontent.com/29224981/100537333-d266d500-3227-11eb-9699-34106dad100c.png">
After manual click on refresh:
<img width="381" alt="Screenshot 2020-11-29 at 09 44 00" src="https://user-images.githubusercontent.com/29224981/100537352-1eb21500-3228-11eb-98c9-ff015baaacfa.png">

**Comment by eamodio** [comment]
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

Also is there anything else special about your repository? Symlink? Remote? etc?

**Comment by wiegell** [comment]
Yes it's a monorepo using Yarn workspaces.
[Gist with output](https://gist.github.com/wiegell/6b9f963a3e37c3178fcad6d3cca1dfbb)
In this output i'm pushing some commits, then making a new commit. Have not pressed refresh.

**Comment by eamodio** [comment]
@wiegell Thanks for those logs -- I'm not seeing the filesystem watcher events triggering so it makes me think we might be hitting: https://github.com/Microsoft/vscode/issues/3025. 

I've added more logging in tomorrow's insiders edition. Can you install it from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). But be sure to disable/uninstall the stable version of GitLens first.

And then send me the logs from the start of a vscode session -- I want to look at GitLens' repository discovery logs.

**Comment by wiegell** [comment]
Thanks for the effort. I'm now on:
![image](https://user-images.githubusercontent.com/29224981/101981692-09e57080-3c6f-11eb-8172-e1ab7b37ae3c.png)
Had one non-pushed commit, then made a commit, but didn't have branch pane open. Opened the pane, but that seemed to do an autorefresh (so correctly said two commits ahead), then did third commit, that didn't autorefresh:
[Gist](https://gist.github.com/wiegell/4e9cc0281ca229d5b5e876df627c7ff0)

**Comment by eamodio** [comment]
@wiegell yeah, so this is what I thought:
```
[2020-12-12 10:44:04:503] Repository[monorepo(/users/XXXXXXXX/programmering/angproj/monorepo/)] doesn't support file watching; path=/Users/XXXXXXXX/programmering/angproj/monorepo, workspaceFolders=/Users/XXXXXXXX/programmering/angproj/monorepo/packages/angular
```

So it looks like you are opening the `/Users/XXXXXXXX/programmering/angproj/monorepo/packages/angular` folder in vscode, but the repo is the parent (e.g. outside of that folder): `/Users/XXXXXXXX/programmering/angproj/monorepo`

GitLens (at least in the _Repositories_ view) will detect this and show an indicator in the UI (although its easy to miss):

![image](https://user-images.githubusercontent.com/641685/102310391-e7867800-3f38-11eb-91fd-b1a5666ab2cc.png)

And unfortunately, VS Code only supports file watching of files/folders inside the workspace/folder it was opened to. See https://github.com/microsoft/vscode/issues/3025.

So unfortunately there isn't much I can do here.

**Comment by wiegell** [comment]
Ok, thanks for the effort anyway. I don't know, so if i understand the situation correctly, gitlens would work, if i had my vs-code workspace in the monorepos root folder - right?
Anyway thats not what i want, since i use custom settings for each sub-repo. Custom settings are not supported with vs-code multi-root workspaces either, which i suspect could be the suggested "solution" from microsoft.

**Comment by wiegell** [comment]
> ![image](https://user-images.githubusercontent.com/641685/102310391-e7867800-3f38-11eb-91fd-b1a5666ab2cc.png)

Also - is this an outdated image? Cant' get this view neither in "source control" or regular gitlens view.

**Comment by eamodio** [comment]
Not old, but only shows on the _Repositories_ view -- I probably need to add some indicator to the other views as well.
