### ISSUE TITLE
How to open current revision of current file on GitHub

### ISSUE THREAD

**Issue by elias6** [eamodio/vscode-gitlens#1192]
- GitLens Version: 11.0.1
- Git Version: 2.27.0

- VSCode Version:
1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
- OS Version: macOS 10.15.7

I have been using GitLens for about a year, and overall I like it. But something seems to have changed in the latest version, and it is annoying.

Is there any easy way to open the current revision of the current file on GitHub? I used to be able to do it by pressing command+option+G, H, down, down, down, down, return. But that no longer works. When I press command+option+G then H, I see a list of revisions instead of the list of Git history commands I used to see.

I looked through all the GitLens commands for something like what was there before, but I can't find it. Am I overlooking something?

**Comment by eamodio** [comment]
Does the _Open File on Remote_ command from the command palette, do what you want?

**Comment by elias6** [comment]
It does. Somehow I missed that. Thank you!
