### ISSUE TITLE
Add dart.referencesCodeLens option

### ISSUE THREAD

**Issue by jaredbaszler** [eamodio/vscode-gitlens#1194]
Please add the functionality to show how many references a method has in Flutter/Dart.  

Like this in Typescript:

![image](https://user-images.githubusercontent.com/9924084/99705875-f1af7680-2a5f-11eb-9327-e9a9244e131e.png)

**Comment by eamodio** [comment]
GitLens doesn't provide references -- those code lens are provided by TypeScript. You'd have to ask the Dart extension for this feature.
