### ISSUE TITLE
"Open file on remote" uses wrong URL to Bitbucket Server

### ISSUE THREAD

**Issue by robross0606** [eamodio/vscode-gitlens#1196]
Issue Type: <b>Bug</b>

When using any of the "Open file on remote" options, the wrong URL is used to our Bitbucket server.

The browser opens to a URL like:
`https://internal.company.com/projects/bitbucket/repos/scm/ncp/study-design-service`

However, our actual URL would be something like:
`https://internal.company.com/bitbucket/projects/NCP/repos/study-design-service/browse`

How does the extension determine this URL?

Extension version: 11.0.2
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042
Bitbucket version: 7.5.1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (16.60GB free)|
|Process Argv|--folder-uri file:///c%3A/Code/ncp/study-design-service --crash-reporter-id 94973ead-12e5-4b7d-b033-6d97d3464d2b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by robross0606** [comment]
It appears like part of the problem is that something is misinterpreting my `$repoBase` variable.  Is there any way to control how this is parsed from the git URL?

**Comment by robross0606** [comment]
@mgallagher, it isn't possible to do what you suggest because gitlens misinterprets the git address when coming up with the available variables for custom remotes.  Things like `${repoBase}` are incorrect.  You cannot resolve the problem with custom remotes if the component parts provided by gitlens are wrong.

**Comment by eamodio** [comment]
Could someone provide a PR here? I don't have a Bitbucket server to test with.

**Comment by guaiamum** [comment]
Experiencing a similar issue, the remote file url returned is encoding `/` as `%2F` from baseURL onwards... replacing the encoded chars yields a right url...

**Comment by eamodio** [comment]
Can you please try this in the GitLens insiders edition? As I've fixed encoding issues there. Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by guaiamum** [comment]
Nice, it worked, thanks :)

**Comment by MaerF0x0** [comment]
@robross0606  can you try GitLens insiders edition to confirm bug fixed? ^^

**Comment by robross0606** [comment]
> @robross0606 can you try GitLens insiders edition to confirm bug fixed? ^^

I can say with fair certainty that, no, this is not at all fixed.

With the insider version, it is opening on remote as:

https://server.name/**projects/bitbucket/repos/scm/ncp**/study-design-service/browse/index.js?at=feature/SD-165_amqp-export-completed

when the real URL is:

https://server.name/**bitbucket/projects/NCP/repos**/study-design-service/browse/index.js?at=feature/SD-165_amqp-export-completed

It is still getting thoroughly confused if the server has a context path.

**Comment by robross0606** [comment]
Part of the confusion here may be that @guaiamum's issue is different than mine.  As far as I can tell, encoding is not my issue at all.  I've confirmed by playing with `gitlens.remotes` that the component parts of the URL are indeed incorrectly parsed when the URL has a context path.

**Comment by robross0606** [comment]
Maybe it would help if I broke down the URL into what accurate component parts:
```
https://server.name/bitbucket/projects/NCP/repos/study-design-service/browse/index.js?at=feature/SD-165_amqp-export-completed
```
Base server URL:  `https://server.name/bitbucket/`
Project context: `projects/NCP/`
Repo context: `repos/study-design-service/`
Action: `browse/index.js?at=feature/SD-165_amqp-export-completed`

**Comment by eamodio** [comment]
@robross0606 What are you using for you `gitlens.remotes` configuration?

**Comment by robross0606** [comment]
> @robross0606 What are you using for you `gitlens.remotes` configuration and was is the actual remote url specified in your git config?

Nothing.  I do not have it specified in either my user or workspace configurations.

**Comment by robross0606** [comment]
The first major problem with gitlens is that it tries to _guess_ the base URL of the server and gets it wrong.  Not every server base address stops at the first `/` if you're using context paths.  This is why Atlassian itself allows you to configure the base URL of your server in their own vscode plugin:
![image](https://user-images.githubusercontent.com/2965467/106028919-8b1b8a00-609a-11eb-9fb7-09b40ef37ef2.png)

**Comment by eamodio** [comment]
@robross0606 

Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

To get it to work, you will need to add something like the following to your `settings.json`

```json
"gitlens.remotes": [
	{
		"type": "BitbucketServer",
		"regex": "^(server.name/bitbucket)/scm/(.*)$",
	},
]
```

**Comment by robross0606** [comment]
Why was this closed without waiting for a response?  _NO_ it is not at all fixed.  Not even a little.  That didn't help anything at all.

**Comment by robross0606** [comment]
Okay, this worked I think:
```
    { "type": "BitbucketServer", "regex": "^(.*/bitbucket)/scm/(.*)$" }
```
A bit clunky, but it worked.

**Comment by eamodio** [comment]
@robross0606 I think the words you are failing to find are "Thank You". To show at least a modicum of appreciation or gratitude for my time spent looking into and fixing your issue. I honestly shouldn't be surprised given your tone previously (shame on me I guess), but I was certainly hoping that my efforts would at least be appreciated in kind.

Please remember this project (and most open-source in general) is volunteer work. I build and maintain GitLens in my free time (giving up sleep and family time too often) and offer it for FREE.

**Comment by robross0606** [comment]
This goes both ways, man.  I've spent plenty of time debugging this as well to point out the issue with details about _why_ it is failing.  I doubt this is "my" issue.  We have a vanilla Bitbucker Server installation here.  Thank you.

**Comment by eamodio** [comment]
How does it go both ways? Was a rude and ungrateful to you? No, I saw that, despite your tone, you put in effort to help get to the bottom of the issue, so I in kind spent time to come up with a solution. Check your entitlement.

**Comment by robross0606** [comment]
Wow, okay.

**Comment by eamodio** [comment]
Really? OK, then.
![image](https://user-images.githubusercontent.com/641685/106314540-de770f00-6237-11eb-8a01-8ec1876a0f37.png)
