### ISSUE TITLE
Can't squash commit in interactive rebase editor

### ISSUE THREAD

**Issue by roblourens** [eamodio/vscode-gitlens#1197]
![Nov-21-2020 11-03-05](https://user-images.githubusercontent.com/323878/99885391-5ba75780-2be9-11eb-85cb-6cc9d737b9a0.gif)

git log

![image](https://user-images.githubusercontent.com/323878/99885400-75489f00-2be9-11eb-9bf0-6a22d816f14b.png)

The first commit should have squash as an option in the menu, I can set it using the keyboard but not the dropdown.

v11.0.2

**Comment by eamodio** [comment]
Git rebase doesn't let you squash/fixup the last commit (because you would be then modifying a commit outside of your rebase target). If you want to squash into that last commit you need to rebase to its parent.

Its a bug that it even shows up in the dropdown as an option.

**Comment by roblourens** [comment]
Yeah I understand that, I think it should not show up in the last commit's dropdown, and it should show up in the first one, right?

**Comment by eamodio** [comment]
Yup for some reason those 2 are reversed.

**Comment by eamodio** [comment]
@roblourens I can't seem to reproduce this -- but something else looks wrong in that screenshot.  The base commit is missing. Are those the only 2 commits on that branch?

**Comment by eamodio** [comment]
So it looks like it is caused by the missing base commit. But not exactly sure how you are hitting that. Is this a repo I have access to that I can try it?

**Comment by roblourens** [comment]
Sorry, the repo was in /tmp and it's gone now. It was a fairly straightforward setup, but I just tried to set up the same situation, and now it seems to work fine...
