### ISSUE TITLE
toggle items from the  editor menu bar

### ISSUE THREAD

**Issue by ksdavidc** [eamodio/vscode-gitlens#1199]
I would like to remove the diffWithPrevious and related buttons from the editor menu bar, to open up valuable real estate, but can't seem to find the way to do so. Is it possible, and how, etc.

**Comment by eamodio** [comment]
You also use the GitLens interactive settings editor from the command palette run `GitLens: Open Settings`, and jump to the _Menus & Toolbars_ section

![image](https://user-images.githubusercontent.com/641685/99915661-fdef3a00-2cd2-11eb-8ef4-4fce9c247b58.png)
