### ISSUE TITLE
Feature Request: "Open in Remote" support for custom repositories

### ISSUE THREAD

**Issue by JaredNeil** [eamodio/vscode-gitlens#120]
Maybe a settings object to customize the url that opens in the browser.
I imagine something like:
```json
{
    "gitlens.remotes": [
        {
            "name": "origin",
            "repoUrl": "https://git.mydomain.com/repos/MyProject",
            "fileUrl": "https://git.mydomain.com/repos/MyProject/browse/%s",
            "branchUrl": "https://git.mydomain.com/repos/MyProject/branch/%s",
            "commitUrl": "https://git.mydomain.com/repos/MyProject/commits/%s"
        }
    ]
}
```
And then it just fills in the `%s` with the branch, commit, or file path.
This would be really nice for Stash (Bitbucket Server) repositories.

**Comment by eamodio** [comment]
@JaredNeil Good suggestion, but given my time and priorities I couldn't say when this would be added. On the other hand PRs are definitely welcome ;)

**Comment by AmandaCameron** [comment]
One alternate route this could take is to make it so you can add additional "domains" that a given service is attached to. 

something like ```{
  "gitlens.remotes.gitlab": [ "gitlab.exaple.com" ]
}```

Then this kind of thing could also be solved by just having a bitbucket remote type, which @JaredNeil could add to his config like

```
{
  "gitlens.remote.bitbucket": [ "git.mydomain.com" ]
}
```

or so

**Comment by eamodio** [comment]
@AmandaCameron Excellent suggestion! I will look into adding something like that -- thank you!

**Comment by eamodio** [comment]
@AmandaCameron @JaredNeil the latest [GitLens v5 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v5.0.0-beta) adds a new `gitlens.remotes` setting to allow you to configure custom remotes similar to @AmandaCameron suggestion. Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know if you experience any issues -- thanks!

**Comment by JaredNeil** [comment]
Apparently Stash and Bitbucket are not as similar as I thought.
If I set up my domain as a Bitbucket project and open a file in remote I get:
`https://${DOMAIN}/${PROJECT}/${REPOSITORY}/src/${BRANCH_NAME}/${FILE_PATH}`
But that gets a 404. The actual URL to look at a file is:
`https://${DOMAIN}/projects/${PROJECT}/repos/${REPOSITORY}/browse/${FILE_PATH}?at=refs%2Fheads%2F${BRANCH_NAME}`
I guess Stash will just need it's own custom support.

**Comment by eamodio** [comment]
@JaredNeil if you could provide me with the url structure for all the pieces of stash, I will add it into the next release. 

You can see the urls for Bitbucket here:
https://github.com/eamodio/vscode-gitlens/blob/62580da7023ee240fb2a6835f44f0665c30119e5/src/git/remotes/bitbucket.ts#L15-L41

**Comment by JaredNeil** [comment]
```typescript
protected getUrlForBranches(): string {
    return `${this.baseUrl}/branches`;
}

protected getUrlForBranch(branch: string): string {
    return `${this.baseUrl}/commits?until=${branch}`;
}

protected getUrlForCommit(sha: string): string {
    return `${this.baseUrl}/commits/${sha}`;
}

protected getUrlForFile(fileName: string, branch?: string, sha?: string, range?: Range): string {
    let line = '';
    if (range) {
        if (range.start.line === range.end.line) {
            line = `#${range.start.line}`;
        }
        else {
            line = `#${range.start.line}-${range.end.line}`;
        }
    }
    
    if (sha) return `${this.baseUrl}/browse/${fileName}?at=${sha}${line}`;
    if (branch) return `${this.baseUrl}/browse/${fileName}?at=${branch}${line}`;
    return `${this.baseUrl}/browse/${fileName}${line}`;
}
```
One problem is that `this.baseUrl` also needs to be slightly different.
Bitbucket and GitHub both use `${DOMAIN}/${PROJECT}/${REPO}`, but stash uses `${DOMAIN}/projects/${PROJECT}/repos/${REPO}`. So I guess the `path` variable in the constructor needs to be modified.
Thanks for your work.

**Comment by eamodio** [comment]
@JaredNeil I just posted another [GitLens v5 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v5.0.0-beta.2) which should hopefully resolve the Stash/Bitbucket Server issues. Let me know -- thanks!

**Comment by JaredNeil** [comment]
Works great so far.
The only issue I've seen is that it requires a reload after adding or changing the `gitlens.remotes` option. I'm not sure if there is a way around that, so it might be worth mentioning in the release notes since most settings changes don't require a reload.

**Comment by eamodio** [comment]
@JaredNeil good catch -- I'll try to get that not to require a reload
