### ISSUE TITLE
"Copy Remote File Url" url-encodes the URL

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#1202]
- GitLens Version: 11.0.4
- VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
- OS version: Darwin x64 20.1.0

Steps to Reproduce:

1. Invoke the **GitLens: Copy Remote File Url** command.
2. Paste to the browser, notice how it url-encoded the slashes (`%2F` instead of `/`)

I think this started happening with v11.0.0. The url-encoded version still works but is uglier, for example:

```diff
- https://github.com/user/repo/blob/512a30dc.../packages/src/lib/README.md
+ https://github.com/user/repo/blob/512a30dc.../packages%2Fsrc%2Flib%2FREADME.md
```

**Comment by ngtrunghuan** [comment]
This is causing a lot of issue for my firm's hosted bitbucket.

**Comment by borekb** [comment]
Workaround I use for now is to use the **Open File on Remote** command and copy the URL from the browser. That seems to avoid URL-encoding.

**Comment by eamodio** [comment]
I added the encoding to deal with spaces in the file path (otherwise it would break the url). Maybe I just need to either encode just that, or just decode `/`.

**Comment by eamodio** [comment]
Can you try this fix out in the latest insiders version? https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders

**Comment by ThibaultJanBeyer** [comment]
Hmm, just installed the insider version. My URLs are still encoded:
```
https://stash.int.company.net/projects/company/repos/company-app/browse/services%2Fsome-service%2Fsrc%2Fapi%2Fadmin%2Ffoo%2Fget%2Findex.js?at=AM-632-post-internal-endpoint#3
```

expected:
```
https://stash.int.company.net/projects/company/repos/company-app/browse/services/some-service/src/api/admin/foo/get/index.js?at=AM-632-post-internal-endpoint#3
```

**Comment by ngtrunghuan** [comment]
Hey Eric, it seems to be fixed on my end after disable the GitLens and
install teh GitLens Insiders.

**Comment by eamodio** [comment]
@ThibaultJanBeyer Are you sure you were testing on the latest insiders? I can't see how you'd get that type of encoding given the changes I've made.

**Comment by yrtimiD** [comment]
confirm: insiders versions fixes escaping problem.

**Comment by ThibaultJanBeyer** [comment]
@eamodio I uninstalled and re-installed it. Now the encoding seems correct. Thank you!
