### ISSUE TITLE
Support disabling / hiding editor actions (icons at the right of tab bar)

### ISSUE THREAD

**Issue by JamesBlandford** [eamodio/vscode-gitlens#1211]
#669 is closed, but not sure about the solution.

![image](https://user-images.githubusercontent.com/9812458/100246114-af3edb80-2f30-11eb-94b4-634a9ed5b525.png)

Please can it be (default maybe) switched off easier?

Its totally unusable like this, and the last comment : https://github.com/eamodio/vscode-gitlens/issues/669#issuecomment-713133732 is incorrect, because I have "Bookmarks" extension which _does_ add to the dropdown menu: 

![image](https://user-images.githubusercontent.com/9812458/100246331-e7461e80-2f30-11eb-815f-aee7ac0e27c7.png)

**Comment by JamesBlandford** [comment]
i have no idea why it has been appended twice, but even without the duplication, its like 4 icons more intruding on my tab bar

**Comment by eamodio** [comment]
Run _GitLens: Open Settings_ from the command palette and jump (or scroll) down to the Menu & Toolbars section. There you have full control to all of GitLens' menu contributions.
