### ISSUE TITLE
Stashes list doesn't refresh on deletion

### ISSUE THREAD

**Issue by Ahmeed2m** [eamodio/vscode-gitlens#1212]
When I delete a stash it does that successfully _but_ if I delete another one I get the error 
```
Unable to delete stash. See output channel for more details
```  
And in the GitLens output
```
[2020-11-25 17:51:56:758] Drop Stash
Error: Unable to delete stash; mismatch with stash number
```
Only when I click refresh on the stashes tab deleting a stash will work again

**Comment by eamodio** [comment]
Hrm, I'm not experiencing this issue. So my guess is this has to do with an issue with file watching. Does this happen all the time? What OS are you on and VS Code version? Also is there anything special about your repo? Do other GitLens views auto-refresh properly? Does the VS Code SCM view update properly?

**Comment by eamodio** [comment]
Also it might help to get logs. Please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by Ahmeed2m** [comment]
OS: Linux x64 5.9.10-1-MANJARO
VSCode Version: 1.51.1
I don't think any gitlens view is being refreshed or changed when I do anything without refreshing the view myself (or going to any other tab then back to SC tab).

Having you mentioned if anything is special with the repo itself. I have the idea that it maybe because I have the repo opened in a code workspace with the repo root being one folder and children as other folders (children are normal folders not git repos).
I made a dummy repo with the `.code-workspace` file to be opened and reproduce the issue.
https://github.com/Ahmeed2m/gitlens-issue/
![image](https://user-images.githubusercontent.com/26524089/100526557-9190a100-31d2-11eb-8715-3aa75467af46.png)
The delete logs are also in that repo  https://github.com/Ahmeed2m/gitlens-issue/blob/master/log

**Comment by eamodio** [comment]
@Ahmeed2m Thank you so much for the test repo -- that helped a ton!

Can you please verify this fix in the latest insiders version? 

You can install the insiders version from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by Ahmeed2m** [comment]
Thank you @eamodio for the fix, I've used the insiders version all day yesterday and so far it seems to be working great in my workspace.
