### ISSUE TITLE
Comparing two commits doesn't produce any result.

### ISSUE THREAD

**Issue by queglay** [eamodio/vscode-gitlens#1214]
- GitLens Version:
- Git Version: `run git --version`

```
user@MacBookPro13 firehawk-main-deploy-dev % git --version
git version 2.24.3 (Apple Git-128)'
```

- VSCode Version: `run code --version`
1.51.1

- OS Version:
10.15.7

Steps to Reproduce:

1. Compare two commits with sub modules

This result in the top bar behaving as if it is going to determine the diffs but never produces a result.

**Comment by eamodio** [comment]
Please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by queglay** [comment]
I blew away the repo folder and cloned again and this seemed to fix the issue today.
