### ISSUE TITLE
Cannot find gitlens view since update

### ISSUE THREAD

**Issue by rpuls** [eamodio/vscode-gitlens#1216]
Hello, since my gitlens was auto updated few days I cannot find the view in my vscode editor.
I have tried reinstalling the pluding and restarting windows etc, it's not showing up.
![vscode](https://i.ibb.co/PYYZL8x/Capture.png)

I was using this view every 10 minutes when working so I really don't hope it has been removed. If so, how do I roll back to previous version and turn off auto update?

current version: v11.0.5

Thanks in advance!
Rasmus

**Comment by gmonte** [comment]
I was also confused. I think that the gitlens options is now on the Source Control menu, but it is not intuitive and I didn't find any explicit release notes reporting this change. I found the gitlens options on the source control when I search for `> gitlens` on vs code search files by name (cmd + shift + p on macos).

**Comment by rpuls** [comment]
@gmonte thanks for replying to my question :)
I still can't find the views that I was frequently using, and in fact got so used to them that I hardly know how to do my job without them. I'm specifically talking about the sidebar views for file history (commit history?), i open a file from the file tree view, then click the gitlens button, and i would get this amazing view with changes history, clicking each record on the list would show diff between the commit and following commit. I desperately need this view.

When I search > gitlens, i get about 50 options. the one that sound the most like what I need is called "file history" but this options just shows a dropdown like menu of the commit history, it's not even close to be as useful as the sidebar view with checkout buttons etc. for each commit, and click on each to quickly browse through different commits. 

Maybe I just haven't found the right view. but it seems to have gone from intuitive to super user. and I think I would actually like to just rollback to previous version. I really don't need anything more than what that version offered, and what the new update offer I really don't understand.

**Comment by eamodio** [comment]
You should have seen this view in the GitLens side bar:
![image](https://user-images.githubusercontent.com/641685/100495538-a6116280-311a-11eb-827e-c740957e9080.png)

Did that view not show up?

**Comment by dlwalter** [comment]
> You should have seen this view in the GitLens side bar:

That did show up but it's not intuitive what that means.  And then I click close and the information disappears forever and I'm having to find this thread to figure out where GitLens went.  Highlighting where the "Source Control Side Bar" is or showing the icon in the popup would be helpful.  I'm guessing it means it's the icon directly above the GitLens icon in your image.

**Comment by rpuls** [comment]
> You should have seen this view in the GitLens side bar:
> ![image](https://user-images.githubusercontent.com/641685/100495538-a6116280-311a-11eb-827e-c740957e9080.png)
> 
> Did that view not show up?

It might have showed up, and I have probably just clicked "close" because I was presented something unexpected and just wanted to move on to the view. tbh I do not read UI instructions or any kind of pop up like messages, so something like this I would most likely just have skipped through.

But thanks for pointing it out, at least I can use the tool now. though it seems weird to me to have a custom installed plugin live under one of the editors native features.

**Comment by eamodio** [comment]
@dlwalter What aspect isn't intuitive? And unfortunately I'm extremely limited in what vscode allows in that type of view -- I can't add images or anything like that. I could turn the _Source Control side bar_ into a link that would switch to it though.

@rpuls Why weird? GitLens is all about source control, and moving changes/commit with the rest of GitLens features imo makes a lot of sense. But you can easily move the GitLens views back to their own sidebar, or organize them, via drag and drop, however you'd like.

**Comment by dlwalter** [comment]
@eamodio I had no idea what the "Source Control Side Bar" is until this moment.  I didn't know that column of icons is referred to as the "Side Bar".   May say the "Side Bar Icons on the Left".  Additionally, you click close and you lose the instructions for where to find it because the old icon disappeared.  For a big UI change it would be nice if the old icon stuck around for a while until the new work flow is established.

Honestly its helpful just having this Github issue available because it answers the question quickly.  I'm just complaining preemptively for the next big UI change ;)
