### ISSUE TITLE
`open changes with previous revision` sometime didn't compare with previous commit

### ISSUE THREAD

**Issue by susiwen8** [eamodio/vscode-gitlens#1219]
- GitLens Version: v2020.11.2903 and v11.0.6
- Git Version: 2.29.2

- VSCode Version: 
1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
- OS Version: MacOS High Sierra version 10.13.6

Steps to Reproduce:
click `revision navigation` or  click right click then select `Open Changes` then select `open changes with previous revision`

Here is result which didn't show expect commit compare
<img width="101" alt="Screen Shot 2020-11-29 at 18 42 34" src="https://user-images.githubusercontent.com/20318608/100539801-d02a6800-3273-11eb-9005-dcd6bae56da8.png">
<img width="498" alt="Screen Shot 2020-11-29 at 18 42 48" src="https://user-images.githubusercontent.com/20318608/100539804-d28cc200-3273-11eb-9f46-c7ea992eccf8.png">

It should show the comparison between `25ae247` and `17fa8e5`

**Comment by susiwen8** [comment]
It might cause by [firtst-parent flag](https://github.com/eamodio/vscode-gitlens/blob/main/src/git/git.ts#L836)

Few days ago, I was encountered `There is no previous commit.`  When I use `open changes with previous revision`, I have located that It might be cause by old version of git (2.17.2) which return no commits, upgrade my git to 2.29.2, gitlen shows result, but something compare with wrong commits.

Possible solution: add `rename: false` at [getPreviousUri](https://github.com/eamodio/vscode-gitlens/blob/main/src/git/gitService.ts#L2636) to disable `first-parent`

**Comment by eamodio** [comment]
Can you please try out the latest insiders version? It has a possible fix for this issue 🤞 

You can install the insiders version from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by quocbao1510** [comment]
> Can you please try out the latest insiders version? It has a possible fix for this issue 🤞
> 
> You can install the insiders version from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

working perfect with the insiders version.
