### ISSUE TITLE
GitLens: Open Associated Pull Request doesn't work

### ISSUE THREAD

**Issue by segevfiner** [eamodio/vscode-gitlens#1222]
- GitLens Version: 11.0.6
- Git Version: 2.29.2

- VSCode Version: 1.51.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Run "GitLens: Open Associated Pull Request" when on a branch that has an associated PR that shows in the status bar. (While logged in to GitHub for this extension).
2. xyzzy; Nothing happens.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition? Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).
