### ISSUE TITLE
commit pane, ${tips} does not show tags

### ISSUE THREAD

**Issue by diablodale** [eamodio/vscode-gitlens#1223]
Hi. In COMMITS pane, the default `${❰ tips ❱➤  }` shows branches but does not show tags.
The circled commit below appears in both COMMITS and TAGS pane. However, the COMMITS pane only shows `master` and does not show `master, v1.3.20201027`

![image](https://user-images.githubusercontent.com/679350/100656926-c2e1ac00-334d-11eb-9c3e-28c7b761a280.png)

I am expecting ${tips} to do as its documentation writes. To show branches and tags at a commit.
Also expecting it to show the same information as in a `git log`. Here is that log for this same commit

![image](https://user-images.githubusercontent.com/679350/100657332-63d06700-334e-11eb-89bc-718872b44e7f.png)

### Setup

- GitLens Version: 11.0.6
- Git Version: git version 2.29.2
- Version: 1.51.1 (system setup)
- Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
- Date: 2020-11-10T23:34:32.027Z
- Electron: 9.3.3
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.19042

### Steps to Reproduce:

1. Setup OS, vscode, git, and extensions as above
2. Setup gpg signing. Set `commit.gpgSign`, `tag.gpgSign`, and `tag.forceSignAnnotated` all `true` in git global user settings.
3. Make commits on master branch
4. Tag last commit
5. Make new branch foobar, checkout foobar
6. Make several commits
7. Switch to source control section in vscode
8. open COMMITS pane and view the entry for the commit that was tagged in step 4

### Result

The commit in the COMMITS pane shows only `master`

### Expected

The commit in the COMMITS pane to show `master` and the tag made in step 4

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition? Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).
