### ISSUE TITLE
Gitlens insiders shows following dialog even if Gitlens is uninstalled

### ISSUE THREAD

**Issue by sandy081** [eamodio/vscode-gitlens#1226]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/10746682/100716883-982d3d00-33b9-11eb-865b-bdb2fa33cf49.png">

**Comment by eamodio** [comment]
@sandy081 I don't see how this can happen, unless `extensions.getExtension('eamodio.gitlens')` returns something when it shouldn't

https://github.com/eamodio/vscode-gitlens/blob/57825c7dfa2a490c625411650f26cf82a0cf2f0d/src/extension.ts#L24-L31

**Comment by sandy081** [comment]
Ok, it seems to be a bug on my side in extensions view. Gitlens main extension is still running and Extensions view is not showing reload required action.

**Comment by sandy081** [comment]
Filed https://github.com/microsoft/vscode/issues/111574
