### ISSUE TITLE
Can't find "Copy Remote URL" options in gitLens 11

### ISSUE THREAD

**Issue by ahhmarr** [eamodio/vscode-gitlens#1227]
- unable to find Copy Remote URL options 
- using v11
- tested on both public or private repo 

![Screen Capture on 2020-12-01 at 10-58-36](https://user-images.githubusercontent.com/3134813/100718694-4d64f280-33c4-11eb-964e-990582b81920.gif)

**Comment by eamodio** [comment]
There are multiple _Copy Remote * Url_ commands -- I think you are looking for `Copy Remote File Url`

**Comment by ahhmarr** [comment]
thanks, indeed it is Copy Remote File Url 

did it got renamed or I got it confused?

**Comment by eamodio** [comment]
I think I renamed it when I added the other _Copy Remote * Url_ commands
