### ISSUE TITLE
How to turn off Git Code Lens?

### ISSUE THREAD

**Issue by Stanzilla** [eamodio/vscode-gitlens#1229]
I'm pretty sure I was able to turn these annotations off before, now I no longer can

- GitLens Version: 11.0.6
- Git Version: `2.29.0`

- VSCode Version: `1.51.1`
- OS Version: Win10 20H2

Steps to Reproduce:

1. Open a file

![image](https://user-images.githubusercontent.com/75278/100797340-41a81900-3422-11eb-9ade-be8f57da4002.png)

**Comment by eamodio** [comment]
Those are the _Git Code Lens_, you can easily control them via _GitLens: Open Settings_ from the command palette, and then jump/scroll to the _Git Code Lens_ section

![image](https://user-images.githubusercontent.com/641685/100803773-bca90980-33f9-11eb-8e5d-74959eb67d9d.png)

You can also quickly toggle them on/off via the _GitLens: Toggle Git Code Lens_ command from the command palette.

And if you specifically just don't want them to show on markdown headers you can add the following to your `settings.json`

```json
"[markdown]": {
	"gitlens.codeLens.scopes": ["document"]
},
```

You can control the code lens "scopes" specifically for any language if you want.
