### ISSUE TITLE
[Source control/commit message] Double click on a word issue

### ISSUE THREAD

**Issue by peacefulseeker** [eamodio/vscode-gitlens#1231]
Issue Type: <b>Bug</b>

When I double click on a word within source control
commit message and viewing the Gitlens Diff Tree(before/after),
I'm jumping to the actual file editing, not the commit message.
It's a bit frustrating experience.

Extension version: 11.0.6
VS Code version: Code - Insiders 1.52.0-insider (ac165d7f974d70212be80cb15eaecfc1fd20b21a, 2020-11-30T17:21:33.245Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|-psn_0_1646994 --crash-reporter-id 1bc210f2-0273-4380-a695-9baf18ed57e0|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
This is actually a bug in VS Code: https://github.com/microsoft/vscode/issues/110751
GitLens doesn't not provide that commit view -- that comes directly from VS Code.
