### ISSUE TITLE
Gitlens disables the Bracket colorizer extension

### ISSUE THREAD

**Issue by tking16** [eamodio/vscode-gitlens#1234]
- GitLens Version: v11.0.6
- VSCode Version: 1.51.1
- OS Version: Mac OS 10.15.7

Steps to Reproduce:

1. Download Bracket Pair Colorizer 2 (v0.2.0) from the VSCode extensions store
2. Download Gitlens, make sure they're both enabled 
3. Add some brackets to a .py file

Is Gitlens is disabled the colorizer extension works without issue. As soon it's enabled The former no longer works at all (plain brackets).

Not sure if I should be telling you or them so apologies!

**Comment by eamodio** [comment]
The VS Code APIs are very limited in how extensions can provide decorations to the editor. And it is easy for extension to collide with one another, and unfortunately there is little we can do to work around it.
