### ISSUE TITLE
"Copy Remote URL" missing from context menu

### ISSUE THREAD

**Issue by msorens** [eamodio/vscode-gitlens#1239]
Issue Type: <b>Bug</b>

Don't know when it broke, but a couple weeks ago I had "copy remote URL" available in my VSCode editor window context menu. Today when I tried, it is simply not listed at all in the context menu.
Note that in the VSCode palette (cmd + shift + p) I do have "GitLens: Copy Remote File URL" and that works fine.

Extension version: 11.0.6
Git Version: 2.28.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 6|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 0a1e0b7c-4068-4051-a0c9-864a26889da7|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Yeah, it was renamed because there are now more types of remote urls that can be copied .

**Comment by msorens** [comment]
If it was just "renamed" as you say then I would expect to see "Copy Remote File URL" in the context menu. But I am not seeing any entries in the context menu relating to copying URLs anymore; that is the bug I am reporting.

**Comment by eamodio** [comment]
It's in the _Copy as_ submenu now.

**Comment by msorens** [comment]
Ah, thank you so much! Did not see that. 👍
