### ISSUE TITLE
Add feature to revert series of commits

### ISSUE THREAD

**Issue by Pand9** [eamodio/vscode-gitlens#1242]
I want to be able to do something like `git revert $LAST_WORKING_REVISION..HEAD --no-edit` but from GUI.
There is "Restore" command for a single file, as well as "undo last commit" for a single commit, and even "reset to commit". However, in order to restore a series of commits, right now you have to go to shell.

**Comment by eamodio** [comment]
@Pand9 Using the _Git Command Palette_ from the command palette (`ctrl+shift+p` or `cmd+shift+p`), you can choose _revert_ and then select the commits to revert.

![image](https://user-images.githubusercontent.com/641685/102309643-359a7c00-3f37-11eb-8865-aa68705457d1.png)

Hope that helps!

**Comment by Pand9** [comment]
@eamodio I don't have such command. Gitlens 11.0.6. See the screenshort for revert-related commands that I have.
![image](https://user-images.githubusercontent.com/2797779/102323697-1fb1a900-3f81-11eb-88db-77ecbfffdcc2.png)

**Comment by Pand9** [comment]
Thanks, is it possible to enable --no-edit, so that user doesn't need to learn how to exit vim? :)

**Comment by eamodio** [comment]
Opened: https://github.com/eamodio/vscode-gitlens/issues/1269
