### ISSUE TITLE
compare: open diff with working by default

### ISSUE THREAD

**Issue by mattklein123** [eamodio/vscode-gitlens#1243]
I'm pretty sure this changed recently, but now when I click on a file in the compare view, it does a diff between 2 SHAs vs. a diff between the SHA and the working file. On my machine this causes the editor to not be editable by default.

I can still open the diff with the working file by clicking on the explicit link (on the right side of the below image), but it's a bit more effort for me to do so. Is this a bug? If not can there be an option to have the default open action be different? I really want it to open against the working file so I can edit it.

![Screenshot_2020-12-07_15-47-08](https://user-images.githubusercontent.com/6305260/101419004-eeabe700-38a3-11eb-9893-ca9115c71b8e.png)

- GitLens Version: 11.0.6
- Git Version: git version 2.17.1
- Code details:
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-56-generic

Steps to Reproduce:

1. Do a compare with another branch
2. Click on a file in the compare view.
3. Opens diff between SHAs vs. diff between the branch and the working file.

**Comment by eamodio** [comment]
Unless there is a bug that I'm not seeing, nothing has changed here. If you compare two branches then the diffs will always be between the two branches. But you can compare the working tree to a branch, and that will open a diff between the working tree and the selected branch.

Also if you are trying to compare from the _Compare with_ node in the _Commits_ or _Branches_ view then you can switch between branch and working tree comparision
![compare](https://user-images.githubusercontent.com/641685/102048360-00fab900-3dad-11eb-91c4-e8faeb519c06.gif)

**Comment by mattklein123** [comment]
Thanks. Somehow I got into branch comparison mode vs. working tree comparison.
