### ISSUE TITLE
Repository folders are missing repository actions (e.g. favorites, close repo, etc)

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#1255]
_Originally posted by @plwalsh in https://github.com/eamodio/vscode-gitlens/issues/1252_

**Comment by eamodio** [comment]
@plwalsh There are now actions on each repository folder in the view, with additional commands for favoriting (which controls ordering) and you can close the repo as well.

Can you please verify this fix in today's insiders edition? Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by plwalsh** [comment]
That works! Closing the repo removes it immediately, and keeps it removed for any future file-openings from that repo for the current vscode instance. If vscode is closed and reopened, the repo will again show up the next time a file from that repo is opened, requiring you to repeat the process of closing it. Is that intended? (I think that's in-line with the built-in *Source Control*, but I just wanted to make sure it's working as intended.) If so, would it make sense to add a setting for a list of always ignored repos?

Adding a repo to favorites immediately moves that repo to the top of the list, as expected. This option, however, does stick across a closing and reopening of vscode. In a new instance of vscode, opening a file from that same other repo will place the repo at the top of the list, with the context menu option to "Remove from Favorites". Is that intended?

Thanks for addressing this so quickly!

**Comment by eamodio** [comment]
@plwalsh Thank you! Yup that is exactly the intended behavior of both options!

As for a setting to ignore repositories -- that is a good idea, that I thought I had implemented, but apparently not. Opened https://github.com/eamodio/vscode-gitlens/issues/1259 to track it
