### ISSUE TITLE
Odd Workspace with GitLens

### ISSUE THREAD

**Issue by onyxdragun** [eamodio/vscode-gitlens#126]
- GitLens Version: 4.3.3
- VSCode Version: 1.14.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

Is it possible to get GitLens to peek a folder up for the .git items? 
My workflow is creating a directory that is ignored by git that include 2 symbolic links to folders within the git repo I work from. This is so i can open multiple folders without resorting to opening the parent project. Let's me drill into the area I actually make changes in.

**Comment by eamodio** [comment]
@onyxdragun did you intentionally close this?
