### ISSUE TITLE
Please add a quick way to copy the SHA that last changed a line

### ISSUE THREAD

**Issue by toh-ableton** [eamodio/vscode-gitlens#1266]
Issue Type: <b>Feature Request</b>

It used to be possible to quickly copy the commit hash of the commit that last changed a given line in an editor. The context menu of a line used to contain the command "Copy Commit ID", which in my opinion was the most useful feature of the whole extension, which I used to use constantly.

There are several workarounds how this can still be achieved, e.g. there's now a whole sub-menu "Copy As", which has an entry "SHA", but from a user experience point-of-view, I find this a clear regression. Navigating submenus with a mouse is just painful.

Another workaround is to click on the SHA in the hover. This open as a command palette that contains the single entry "Loading...", once that is complete, it also has a command "Copy SHA" at the very bottom.

I would like a quick way to copy the sha. A direct entry in the immediate context entry would be fine, as would be a button in the hover.

Thank you for considering my feature request!

Extension version: 11.0.6
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.2.0

**Comment by eamodio** [comment]
As you mentioned the command still exists, it was just renamed to Copy SHA and moved into the _Copy as_ submenu. The same command can be accessed from the command palette `ctrl|cmd+shift+p` via _GitLens: Copy SHA_.  Additionally you can set a key binding for that command to make it even easier.

And VS Code 1.52 makes adding key bindings from the command palette nice and easy:

![image](https://user-images.githubusercontent.com/641685/102307862-5eb90d80-3f33-11eb-82b8-2b9d3482b10f.png)

Or you can add the following to your `keybindings.json` file:
```json
	{
		"key": "ctrl+shift+c",
		"command": "gitlens.copyShaToClipboard",
		"when": "editorTextFocus"
	}
```

Hope that helps.
