### ISSUE TITLE
Add --no-edit support to revert

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#1269]
Thanks, is it possible to enable --no-edit, so that user doesn't need to learn how to exit vim? :)

_Originally posted by @Pand9 in https://github.com/eamodio/vscode-gitlens/issues/1242#issuecomment-745924247_

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by Pand9** [comment]
@eamodio I checked and it works, thank you!
