### ISSUE TITLE
Avatar position in hover could be moved downward

### ISSUE THREAD

**Issue by mapringg** [eamodio/vscode-gitlens#1272]
Is it possible to move the position of the avatar downward, so that the height of the box is not too high. I feel like there is a gap underneath the avatar that is wasted.

**Comment by eamodio** [comment]
Unfortunately GitLens can't control that positioning. All I can do it affect the size of the avatar. Which you can change by changing the `gitlens.hovers.avatarSize` setting. Sorry. 😢
