### ISSUE TITLE
Line blame popup disapears immediately once scrolling reaches the top or bottom of the popup

### ISSUE THREAD

**Issue by cateyes99** [eamodio/vscode-gitlens#1276]
- GitLens Version: _11.0.6_
- Git Version: _git version 2.23.0.windows.1_

- VSCode Version: _1.52.0_
- OS Version: _Windows 10 Enterprise_

Steps to Reproduce:

1. Turn on the `Line Blame`, then let a popup of a commit show up as displayed in the below **Screenshot**.
![image](https://user-images.githubusercontent.com/19678455/102560140-64327580-4136-11eb-8dd4-7de1357f52b6.png)
2. So you wanna scroll up & down to see all the context, if you are using a normal mouse, it's ok to click on the scroll bar & scroll up and down. But I'm on my laptop all the time, using its touch pad. As the popup disappears immediately once scrolling reaches the top or bottom of the popup (_I think it's the same for using the middle wheel on a mouse_), it's always not possible to see the full context in the popup. I could use the touch pad as a mouse to click on the scroll bar and scroll it up and down, but it's quite slow & inconvenient with a touch pad on laptop.
3. I think old versions of **GitLens** don't have this issue.

**Comment by eamodio** [comment]
Unfortunately there isn't anything GitLens can do here -- this is the behavior of VS Code hovers and GitLens has no control over that behavior.

Could you open an issue on the [VS Code repository](https://github.com/microsoft/vscode) and fill this issue there? Thanks!
