### ISSUE TITLE
Question: toggling GitLens by vscode tab

### ISSUE THREAD

**Issue by ssynix** [eamodio/vscode-gitlens#128]
Is it possible to to show the inline blame details (and the ones above "containers") only when in the source control tab of vscode? I find them a bit distracting when coding in the explorer tab.

Thanks!

**Comment by eamodio** [comment]
Interesting idea -- but as far as I know the vscode api doesn't have any way for me to detect that

**Comment by ssynix** [comment]
Gotcha, thanks for the quick response! I'll resort to manually toggling code lens then.
