### ISSUE TITLE
Unable to install extension 'eamodio.gitlens' as it is not compatible with VS Code '1.50.1'

### ISSUE THREAD

**Issue by fakeYanss** [eamodio/vscode-gitlens#1280]
- GitLens Version: 11.0.6
- Git Version: 2.7.4

- VSCode Version: 1.50.1
- OS Version: Darwin x64 19.6.0
![image](https://user-images.githubusercontent.com/30440198/102755948-1de54c80-43aa-11eb-970b-9bd3304bd5fb.png)

**Comment by eamodio** [comment]
GitLens 11.0 requires a newer version of VS Code than 1.50, because of the new APIs it needs.
