### ISSUE TITLE
Ability to turn off "Show Branch" tooltip in terminal

### ISSUE THREAD

**Issue by tgreen7** [eamodio/vscode-gitlens#1284]
I like to copy the current git branch name by double clicking it in my integrated terminal. However, gitlens is creating a tooltip on the branch name on hover which breaks my double click selection.

<img width="1115" alt="Screen Shot 2020-12-21 at 12 33 25 PM" src="https://user-images.githubusercontent.com/10415101/102819718-e0bc9280-4388-11eb-8720-52122470bc5e.png">

Where is this code coming from? Is it possible to turn this off?

**Comment by eamodio** [comment]
@tgreen7 Unfortunately there isn't a way to turn this off currently, but I will add a setting.

Although, the terminal links shouldn't break any existing behavior -- could you provide more details on how it is breaking your workflow?

**Comment by tgreen7** [comment]
@eamodio It just blocks the double click selection. When you double click the mouse on text it will select the whole word. But the tooltip blocks the click.

**Comment by eamodio** [comment]
@tgreen7 Hrm, I can't reproduce that, might be OS specific? But even if I could repo, this would be a bug in VS Code itself as the VS Code terminal links API shouldn't cause the impact you are experiencing. Can you open an issue on the VS Code repo so it can get fixed there?

**Comment by eamodio** [comment]
There is now a new `gitlens.terminalLinks.enabled` setting to control whether terminal links are enabled.

Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by tgreen7** [comment]
Perfect. Looks good!
