### ISSUE TITLE
Uncommitted staged changes after pull

### ISSUE THREAD

**Issue by yaroslavsadin** [eamodio/vscode-gitlens#1285]
- GitLens Version: v11.0.6
- Git Version: 2.17.1
- VSCode Version: 1.52.1
- OS Version:  Ubuntu 18.04

I'm noticing that `/usr/bin/git -c core.quotepath=false -c color.ui=false fetch -u origin master:master` command is used to Pull changes (hitting repository ↓ button and confirming Pull changes). Problem is, it will update the working tree in a way that I see uncomitted staged changes in the `Source control` section, as if I reverted all the pulled changes back locally.  Simple`git pull` as well as Pull command from `Source control` works fine. Is that the correct git command to pull changes?

**Comment by ferreroxc** [comment]
I met the same problem. I have to unstage them all, discard them, check out to another branch, and finally check out back to the first branch. I am editing files on a remote linux machine.

- GitLens Version: 11.1.0
- Git version: 2.27.0
- VSCode Version: 1.52.1
- OS Version: Mac OS Catalina 10.15.5
- Git Version on Remote linux machine: 2.27.0

**Comment by eamodio** [comment]
@ferreroxc how are you pulling?

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by ferreroxc** [comment]
> @ferreroxc how are you pulling?

Just as yaroslavsadin described, "hitting repository ↓ button and confirming Pull changes".

**Comment by ferreroxc** [comment]
> Can you please verify this fix in the insiders edition?
> 
> You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

When I was trying this insiders edition, I met another problem, which occurred in both the stable and insiders edition.
The remote master was one commit ahead my local master, when I hit the "Refresh" button, the new commit did not show up and everything stayed the same.
![Uploading refresh_button.png…]()
I probably should open a new issue to discuss this, but I want to tell you first that I need to try this insiders edition on another computer.

**Comment by eamodio** [comment]
@ferreroxc Hrm, yeah please open a new issue. Although, the refresh button doesn't affect git in any way it just (should) re-render the tree.

**Comment by ferreroxc** [comment]
> I met the same problem. I have to unstage them all, discard them, check out to another branch, and finally check out back to the first branch. I am editing files on a remote linux machine.
> 
> * GitLens Version: 11.1.0
> * Git version: 2.27.0
> * VSCode Version: 1.52.1
> * OS Version: Mac OS Catalina 10.15.5
> * Git Version on Remote linux machine: 2.27.0

On this machine (let's call it the first Mac), I still face the problem of the broken "Refresh" button, which I open a new issue [here](https://github.com/eamodio/vscode-gitlens/issues/1305). I tried to uninstall -> reinstall Gitlens, reload VScode Window and install VScode Insider, but none helped.

However, when I try on my second Mac, both the "Refresh" button and the "Pull" button work completely fine. Some background info of my second Mac:

- GitLens Version: Gitlens (Insiders) v2021.1.404
- Git version: 2.27.0
- VSCode Version: 1.52.1
- OS Version: Mac OS Catalina 10.15.6
- Git Version on Remote linux machine: 2.27.0

Since my first and second Mac share the roughly same OS, VScode, and Git version, I decided to uninstall and reinstall the stable VSCode on my first Mac and see if the problem can be solved.

**Comment by ferreroxc** [comment]
> > I met the same problem. I have to unstage them all, discard them, check out to another branch, and finally check out back to the first branch. I am editing files on a remote linux machine.
> > 
> > * GitLens Version: 11.1.0
> > * Git version: 2.27.0
> > * VSCode Version: 1.52.1
> > * OS Version: Mac OS Catalina 10.15.5
> > * Git Version on Remote linux machine: 2.27.0
> 
> On this machine (let's call it the first Mac), I still face the problem of the broken "Refresh" button, which I open a new issue [here](https://github.com/eamodio/vscode-gitlens/issues/1305). I tried to uninstall -> reinstall Gitlens, reload VScode Window and install VScode Insider, but none helped.
> 
> However, when I try on my second Mac, both the "Refresh" button and the "Pull" button work completely fine. Some background info of my second Mac:
> 
> * GitLens Version: Gitlens (Insiders) v2021.1.404
> * Git version: 2.27.0
> * VSCode Version: 1.52.1
> * OS Version: Mac OS Catalina 10.15.6
> * Git Version on Remote linux machine: 2.27.0
> 
> Since my first and second Mac share the roughly same OS, VScode, and Git version, I decided to uninstall and reinstall the stable VSCode on my first Mac and see if the problem can be solved.

1. The "Refresh" button is not broken. I misunderstand the real function that the "Refresh" button do, as described [here](https://github.com/eamodio/vscode-gitlens/issues/1305#issuecomment-754863719).
2. The Gitlens (Insiders) v2021.1.404 works completely fine when pulling from a remote branch, so there is no "uncommitted staged changes"

Thank you so much Eric!
