### ISSUE TITLE
"Line history" missing - was removed?

### ISSUE THREAD

**Issue by Pand9** [eamodio/vscode-gitlens#1286]
I remember there being a "Line history" view. Last time I saw it, it was when everything was in a separate tab. Ever since the tab was merged with VSCode's Version Control, there is no "Line history", only "File history":

![image](https://user-images.githubusercontent.com/2797779/102897176-dd4c0880-4467-11eb-9707-f5960e69fff1.png)

Line history is mighty useful as it serves as a supercharged version of "git blame"/"git annotate", allowing you to see the full history for a single line.

- GitLens Version: v2020.12.2104 (insiders), also 11.0.6
- Git Version: 2.20.1
- VSCode Version:
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
- OS Version: Ubuntu 19.10

**Comment by eamodio** [comment]
It still exists, its just hidden by default. You can enable it by setting `"gitlens.views.lineHistory.enabled": true`. In the next release of GitLens, I've made this more visible (though still hidden by default).
