### ISSUE TITLE
gitlens failed to install in wsl2 remote

### ISSUE THREAD

**Issue by PhyX-Meow** [eamodio/vscode-gitlens#1292]
- GitLens Version: 11.1.0
- Git Version: 2.29.2

- VSCode Version: 
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20279
- OS Version: Manjaro linux in wsl2, win10 build 10.0.20279.1

Steps to Reproduce:
Install vscode in windows host
Install remote-wsl extension
Install gitlens in remote window
Open a git repo

Seems gitlens failed to start, all it's commands result in this error:
![image](https://user-images.githubusercontent.com/17513581/103146295-2bbc1880-4782-11eb-8be5-d106395a45ea.png)

**Comment by PhyX-Meow** [comment]
![image](https://user-images.githubusercontent.com/17513581/103146454-7179e080-4784-11eb-853d-84cae13fc721.png)
Seems to be an installation issue, the extension folder have a lot of 0kb files.

**Comment by PhyX-Meow** [comment]
Copying native extension manually makes everything works fine.

**Comment by eamodio** [comment]
Hrm, any installation issues would be bugs in VS Code itself, as extensions don't have any control over the installation process. If you see this issue again, I would recommend opening an issue against the VS Code repository.
