### ISSUE TITLE
Error when open commits list

### ISSUE THREAD

**Issue by StupnikovVG** [eamodio/vscode-gitlens#1294]
- GitLens Version: v11.1.0
- Git Version: git version 2.12.2.windows.2

- VSCode Version: 1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
- OS Version: Windows 10 Pro 

Steps to Reproduce:

1. Open Commits in gitlens bar. Get an error:  
   
![изображение](https://user-images.githubusercontent.com/27226655/103164158-9ae44c00-4818-11eb-8d98-373ce749fea8.png)

Logs: 
[gitlens_log_2.txt](https://github.com/eamodio/vscode-gitlens/files/5744092/gitlens_log_2.txt)
[gitlens_log_1.txt](https://github.com/eamodio/vscode-gitlens/files/5744093/gitlens_log_1.txt)

**Comment by eamodio** [comment]
This is caused because the old version of Git. I would recommend upgrading to a much newer version.

**Comment by eamodio** [comment]
Since I don't *really* need to use the `(if)` syntax there -- I will replace it, so GitLens will still work with old versions of Git. Although, I would still highly recommend upgrading.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by UnightSun** [comment]
> Can you please verify this fix in tomorrow's insiders edition?
> 
> You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

I'm developing with vscode remote env, and remote system cannot update git to latest version.

v2020.12.2904 seems working fine. thx a lot.

**Comment by StupnikovVG** [comment]
I've already updated my version of git and can't verify this fix, but thanks anyway.

**Comment by pcluteijn** [comment]
Thanks, Eric! Just tested version 11.1.2, as far as I can tell this issue has been dealt with.
