### ISSUE TITLE
I changed folder name from "c"lient to "C"lient and gitlens stopped showing line updates

### ISSUE THREAD

**Issue by MananDesai54** [eamodio/vscode-gitlens#1295]
- GitLens Version: 11.1.0
- Git Version: 2.26.1

- VSCode Version: 1.52.1
- OS Version: windows 10

Steps to Reproduce:

1. can make folder name checking case insensitive

**Comment by eamodio** [comment]
Yeah, this is a known issue with VS Code/Git/GitLens on file systems that aren't case sensitive (Windows, macOS) -- it stems from VS Code not being able to get the correct casing of the folder/file on disk properly, so it basically just uses whatever casing you provide. And Git (unless you set the `core.ignoreCase` config setting to `true`) is expecting the casing to match exactly as on disk.

So to fix this either open the folder/workspace with the exact casing as it exists on disk, or change the Git config to set `core.ignoreCase` to `true`, by running `git config --global core.ignoreCase true` on the command line.
