### ISSUE TITLE
not showing commits: "fatal: unknown field name: if"

### ISSUE THREAD

**Issue by felix021** [eamodio/vscode-gitlens#1296]
- GitLens Version: 11.1.0
- Git Version: git version 2.11.0

- VSCode Version:

> Version: 1.52.1
> Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
> Date: 2020-12-16T16:30:02.420Z
> Electron: 9.3.5
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Switch to Gitlens tab,
2. Not showing any commit, with a pop-up message:

> Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false tag -l --format=%3cn%3e%(refname)%3cr%3e%(if)%(*objectname)%(then)%(*objectname)%(else)%(objectname)%(end)%3cd%3e%(creatordate:iso8601)%3cad%3e%(authordate:iso8601)%3cs%3e%(subject) fatal: unknown field name: if

3. Older versions (<= 11.0.6) are good.

**Comment by acmario** [comment]
I reproduced the issue with:
VSCode version 1.52.1
Git Version 2.8.1
GitLens Version 11.1.0

**Comment by khateeb321** [comment]
Same issue on Windows.

**Comment by eamodio** [comment]
Duplicate of #1294 -- the issue is your Git versions are too old. I would highly recommend upgrading to a recent version (especially given the security issues in older versions)

**Comment by acmario** [comment]
> Duplicate of #1294 -- the issue is your Git versions are too old. I would highly recommend upgrading to a recent version (especially given the security issues in older versions)
> The `(if)` syntax was added in Git v2.13.7 (on 5/22/2018)
@eamodio Thank you for taking the time to comment.. you are obviously right. I upgraded to the latest Git version on Windows 10 and it works fine. I think the issue can be closed.

**Comment by eamodio** [comment]
Since I don't *really* need to use that syntax there -- I will replace it, so GitLens will still work with old versions of Git. Although, I would still highly recommend upgrading.

See #1294 for the fix.

**Comment by BryceLohr** [comment]
I believe this is exacerbated when using Development Containers with VS Code. The version of git that VS Code has inside the dev container in its default configuration is `2.11.0`. 

VS Code version:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 16.7.0

Remote - Containers version: v0.154.1

I installed GitLens inside that dev container, and I get this same error message and commits don't show up.

**Comment by eamodio** [comment]
@BryceLohr see https://github.com/eamodio/vscode-gitlens/issues/1294. The fix is currently in the insiders version and will be coming to stable soon.
