### ISSUE TITLE
Element with id gitlens:repository(d:/../...):stash(...) is already registered

### ISSUE THREAD

**Issue by syagev** [eamodio/vscode-gitlens#1297]
- GitLens Version: 11.1.0
- Git Version: Run `git --version`: git version 2.29.2.windows.1
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to reproduce:
1. Make a new stash in my repo (multi-root workspace with 3 projects).
2. The following error is displayed in a pop-up :
```
Element with id gitlens:repository(d:/../...):stash(ab44cc1798978ce9f01182c7fa26cc6ae7d127a3) is already registered
```
3. Stash entries are no longer displayed in the STASHES window:
![image](https://user-images.githubusercontent.com/5247438/103220298-9eff8f00-4928-11eb-9fd4-71e0d4537d86.png)
(the "PrincetonServices" projects *does* contain stashes, including the latest one)

<details>
<summary>Console log in Developer Tools:</summary>

```
gitlens:repository(d:/../..):stash(ab44cc1798978ce9f01182c7fa26cc6ae7d127a3) is already registered
	at m.createAndRegisterTreeNode (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:663:595)
	at c:\Users\styagev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:662:96
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 1)
	at async m.fetchChildrenNodes (c:\Users\styagev\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:661:974)
onDidChangeNotification @ notificationsAlerts.ts:36
```
</details>

NOTE: reloading the window makes the error go away and stashes properly appear.

**Comment by eamodio** [comment]
@syagev Is this always reproducible? Given those steps?

**Comment by syagev** [comment]
> Is this always reproducible? 

Unfortunately not. It was reproducible multiple times in that instance (even after a window reload I could repro it). I tried again now to confirm (IDE was closed since and computer rebooted) and I could not reproduce.

If there's anything I can do next time it happens (if it happens), in terms of collecting diagnostics, I'm happy to help.
