### ISSUE TITLE
First-run "Thank you for choosing GitLens! [...]" info message shown on every start up

### ISSUE THREAD

**Issue by damsleth** [eamodio/vscode-gitlens#130]
- GitLens Version: v4.3.3
- VSCode Version: 1.15 (July 2017)
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Start VSCode
2. Observe the first-run "Thank you for choosing GitLens! [...]" info message pop down

![GitLens Firstrun](http://i.imgur.com/7FdRzvD.gif)

- Not experiencing the issue with VSCode-insiders 1.16 (August 2017) on the same machine.
- Reinstalling GitLens does nothing.

**Comment by eamodio** [comment]
@damsleth do you have any other issues with that instance of vscode?

**Comment by eamodio** [comment]
@damsleth Can you open up the devtools in vscode (Help -> Toggle Developer Tools), and then select `Application` tab at the top, and then expand `Local Storage` and select `file://`. Using the filter bar at the top type `global/eamodio.gitlens` and then please send me the value of the only key.

It should look like this:
![image](https://user-images.githubusercontent.com/641685/29368987-3fc6bd0c-826f-11e7-9c45-7b30f3387b1f.png)

**Comment by damsleth** [comment]
storage://global/eamodio.gitlens : {"gitlensVersion":"4.3.3"}
i.e. no "suppressWelcomeNotice":true.

**Comment by eamodio** [comment]
@damsleth this is so strange -- since the version number is in there and that is what I key off. See:
https://github.com/eamodio/vscode-gitlens/blob/d3013a03d471a1ff5cc14853a2899924f0f195d7/src/extension.ts#L273-L278

Using the devtools again can you delete the key (press the `del` key) and then restart vscode and see if the welcome message goes away on the 2nd run?

**Comment by damsleth** [comment]
Deleted key, closed and restarted VSCode twice, key value still the same {"gitlensVersion":"4.4.2"}

**Comment by eamodio** [comment]
@damsleth I'm so sorry this is still dragging on. I'm really baffled. I've added more logging in v4.4.3 so hopefully that will help point us in the right direction. Thank you for your patience.

Before you upgrade to 4.4.3 -- can you set `"gitlens.outputLevel": "verbose"` and then after you upgrade please post the output from the `GitLens` output channel?

**Comment by damsleth** [comment]
Don't worry about it, it's not exactly a blocker ;) 
Here's the verbose GitLens output (same for first upgrade-run and all subsequent ones).
`GitLens(v4.4.3) active: /Users/damsleth/Code/
Git found: 2.8.4 (Apple Git-73) @ /usr/bin/git
git -c core.quotepath=false rev-parse --show-toplevel   cwd='/Users/damsleth/Code'
Git version: 2.8.4 (Apple Git-73)
GitLens first-time install
CodeLens config changed; resetting CodeLens provider
getRemotes('/Users/damsleth/Code')
getRemotes('/Users/damsleth/Code')
git -c core.quotepath=false remote -v   cwd='/Users/damsleth/Code'
git -c core.quotepath=false remote -v   cwd='/Users/damsleth/Code'
getStash('/Users/damsleth/Code')
git -c core.quotepath=false stash list --name-status --full-history -M --format=%H -%nauthor-date %ai%nreflog-selector %gd%nsummary %B%nfilename ?   cwd='/Users/damsleth/Code'`

**Comment by eamodio** [comment]
@damsleth I've just published [GitLens 5.0.0-alpha.2](https://github.com/eamodio/vscode-gitlens/releases/tag/v5.0.0-alpha.2). I've added a secondary check to suppress the welcome message -- hopefully this will resolve the issue (🤞 as I have no idea why reading from the `globalState` doesn't seem to be working in this case).

Please make sure to completely remove any prior version before installing a vsix -- instructions here: https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions

**Comment by damsleth** [comment]
Haven't had any issues since then 🤞 now running 7.5.7 - works awesome 👏

**Comment by eamodio** [comment]
Awesome glad to hear it!
