### ISSUE TITLE
Open on Remote is creating invalid URLs for Azure Devops

### ISSUE THREAD

**Issue by TravisTX** [eamodio/vscode-gitlens#1303]
- GitLens Version: 11.1.2 (also main branch)
- Git Version: git version 2.30.0.windows.1

- VSCode Version: 1.52.1 / ea3859d4ba2f3e577a159bc91e3074c5d85c0523 / x64
- OS Version: Windows 10 1909

## Steps to Reproduce:

1. Clone an Azure Devops repo that includes a space escaped as %20. example: `git clone https://DataLinkSoftware@dev.azure.com/DataLinkSoftware/Cloud%20Infrastructure/_git/Azure_Infrastructure`
2. In VSCode, go to source control -> remotes -> click the globe next to the repo to "Open Repository on Remote"
3. The browser will open to the URL:
`https://dev.azure.com/DataLinkSoftware/Cloud%2520Infrastructure/_git/Azure_Infrastructure` which is a 404, because the `%` being re-encoded as `%25`

Expected URL:
`https://dev.azure.com/DataLinkSoftware/Cloud%20Infrastructure/_git/Azure_Infrastructure`
Actual URL:
`https://dev.azure.com/DataLinkSoftware/Cloud%2520Infrastructure/_git/Azure_Infrastructure`

## Another way to reproduce:

1. Clone any repro on Azure Devops
2. In VSCode, go to Explorer and right click any file and choose "Open File on Remote"
3. In my case, I did this with a README.md in the root, and this is the url that was sent to my browser: 
`https://dev.azure.com/DataLinkSoftware/Core/_git/Sso/?path=%252FREADME.md&version=GBmaster&_a=contents` which is a 404. 

Expected URL:
`https://dev.azure.com/DataLinkSoftware/Core/_git/Sso/?path=%2FREADME.md&version=GBmaster&_a=contents`
or
`https://dev.azure.com/DataLinkSoftware/Core/_git/Sso/?path=/README.md&version=GBmaster&_a=contents`
Actual URL:
`https://dev.azure.com/DataLinkSoftware/Core/_git/Sso/?path=%252FREADME.md&version=GBmaster&_a=contents`

These were regressions introduced in 545dc4aac1a745362cabc6ed808d7c608dbe4a34 which was created to address #1202.  I will be submitting a PR to fix this.

**Comment by eamodio** [comment]
@TravisTX awesome work -- I will get this into a release ASAP!

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by TravisTX** [comment]
@eamodio  looks good!

**Comment by eamodio** [comment]
Thanks!
