### ISSUE TITLE
Copy Current Branch Name

### ISSUE THREAD

**Issue by kh0m** [eamodio/vscode-gitlens#1306]
Greetings!

I love using GitLens and it works great when managing multiple repositories and multiple branches. Given the large number of branches in my repos, I would find it extremely convenient to have a command from the Command Palette that copies the name of the currently checked out branch. I do this so many times in a day in order to paste it in trackers and pull requests.

While this can be done using the `copy` command in the branchesView, it will save having to open that view and scroll through the hundreds of branches to find the one with the checkmark next to it.

(Depending on support for this feature, an alternative to it could be to order the checked out branch to the top of the list, following or preceding the default branch)

Thanks!

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
