### ISSUE TITLE
overlap with import cost extension

### ISSUE THREAD

**Issue by ergenekonyigit** [eamodio/vscode-gitlens#131]
![screen shot 2017-08-17 at 17 46 25](https://user-images.githubusercontent.com/7110136/29418261-867f93da-8374-11e7-838a-e991acc1eec1.png)
![screen shot 2017-08-17 at 17 46 36](https://user-images.githubusercontent.com/7110136/29418263-88fdac96-8374-11e7-81a8-4a0686e0a7a8.png)

these two extension overlaped.

- GitLens Version: 4.3.3
- VSCode Version: 1.15.1
- OS Version: 10.12.6

Steps to Reproduce:

1.
2.

**Comment by eamodio** [comment]
@ergenekonyigit I'm not sure what is wrong or what you are expecting to happen? Both extension can add decorations to the end of the code lines -- and only 1 is going to win at a time. GitLens only adds the end of line decoration on the current line, if enabled (can be toggled via a command, or turned off completely via a setting).

What would you expect to happen if you change the current line to one where import cost had already added a decoration?

**Comment by eamodio** [comment]
I've opened https://github.com/Microsoft/vscode/issues/33852 to track this issue

**Comment by eamodio** [comment]
Closing this as it is a vscode issue.
