### ISSUE TITLE
Search by commit SHA shouldn't require 7 characters

### ISSUE THREAD

**Issue by jez9999** [eamodio/vscode-gitlens#1313]
For some reason, search by commit SHA (eg. commit:12ab345) currently requires 7 letters; so `12ab345` would work but `12ab` wouldn't, even though it works on the commandline and is unambiguous: `git log 12ab` works.

GitLens shouldn't require 7 letters, and and set of unambiguous letters should work.  Typing 7 letters is too annoying.

**Comment by eamodio** [comment]
I can't reproduce this.

Here I am searching for `1bf4`, which is unambiguous:
![image](https://user-images.githubusercontent.com/641685/103944209-4c308f00-5101-11eb-9e2b-addfdd6822e6.png)

Here I am searching for `1bf`, which is ambiguous (and thus doesn't return any results):
![image](https://user-images.githubusercontent.com/641685/103944225-52bf0680-5101-11eb-8855-75463c0af781.png)
