### ISSUE TITLE
I have error : GitLens was unable to find Git. Please make sure Git is installed. Also ensure that Git is either in the PATH, or that 'gitlens.advanced.git' is pointed to its installed location. ... help me

### ISSUE THREAD

**Issue by tiendzbk** [eamodio/vscode-gitlens#132]
- GitLens Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by eamodio** [comment]
@tiendzbk I'd be happy to help you but I'm going to need more information from you. Can you please provide the information asked for in the issue template (GitLens version, vscode, os, etc). Also have you followed the steps in the error message? I'm assuming git is installed? If so, is it in your PATH? If not, where is it installed? Have you tried setting the `"gitlens.advanced.git"="<put your git file path here>"`?

Let me know and I'd be glad to help.

**Comment by eamodio** [comment]
This hasn't been updated in almost a month -- please re-open if there is still an issue I can help with

**Comment by shunjinchan** [comment]
I'm having the same issue just after update the lastest xcode.

- MacOS High Sierra (GM)
- Xcode Version 9.0 (9A235)
- VSCode 1.16.1

fix issue
`$ git -v`
`Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.`
`$ sudo xcodebuild -license`

**Comment by shlgug** [comment]
Try running this from Terminal.  Worked for me.
`xcode-select --install`

**Comment by alsGitHub270** [comment]
Just downloaded 1.18.1.  This error is appearing.  It appeared on 1.18.0 also, but never appeared on 1.17.1

**Comment by Hannah-goodridge** [comment]
Can confirm I had this issue once I upgraded from sierra to high seirra.

Tried to find git and got this error:

```git -v
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun```


had to reinstall `xcode-select --install`

Looks like it doesn't reinstall xcode when you upgrade but weirdly git was present so I didn't have in to install that.

Props goes to @shlgug

**Comment by Mane767** [comment]
This code all so wok for me thanks...... 
 xcode-select --install
