### ISSUE TITLE
No way to disable hover

### ISSUE THREAD

**Issue by bmarkovic** [eamodio/vscode-gitlens#1320]
- GitLens Version: v11.1.3
- Git Version: 2.25.1

- VSCode Version: 1.53.0-insider
- OS Version: Xubuntu 20.04

Steps to Reproduce:

Tried multiple things

1. add `"gitlens.blame.line.enabled": false,` as per #243, the setting is faded out ("Unknown configuration setting")
2. the newer version setting `"gitlens.currentLine.enabled": false,` removes the line but not the hover,
3. the options `"gitlens.hovers.annotations.enabled": false,` and `"gitlens.hovers.annotations.changes": false,` also didn't help.

Whatever I do annoying hover blame is still on. My current workaround is to disable Git Lens although I did use the statusbar blame and some other functions.

**Comment by eamodio** [comment]
If you want to disable the current line hover, set `"gitlens.hovers.currentLine.enabled": false`, if you want to disable hovers when showing the Gutter annotations, then set `"gitlens.hovers.annotations.enabled": false`. But please try the GitLens interactive settings editor from the command palette (`ctrl+shift+p` or `cmd+shift+p`) and search for _GitLens: Open Settings_. It will make it really easy for you to configure exactly what you want.

**Comment by bmarkovic** [comment]
I do have a bit of an objection here as there are at very least the following options:

```jsonc
{
    // ..
    "gitlens.hovers.pullRequests.enabled": false,
    "gitlens.hovers.enabled": false,
    "gitlens.hovers.annotations.enabled": false,
    "gitlens.hovers.annotations.changes": false,
    //
    // and none of them apply to this really, even the one named
    //    "gitlens.hovers.enabled"
    // save for the..
    //
    "gitlens.hovers.currentLine.enabled": false,
    //
    // which I still don't know what it's called in the Settings Editor 
    // or your own GitLens Settings UI
    //
}
```

So, my wish/advice is, while the snowy settings editor is nice and all, bit nicer UX effort on it and the settings in the default Code settings editor could really be beneficial to us users. I don't recommend that you (again) change the settings names, because, as confusing as they are at least someone might run into this issue when searching for a solution and it will work for them.

But the hover option is nowhere to be find in either UI -- it certainly isn't grouped with the Current Line Blame where it should be (not to mention that I only got the whole concept of hover being tied to currentLine subgroup after asking here). Documentation is also pretty confusing to get around because it's a huge Readme which kinda added to my confusion.

I understand you must be busy and/or overwhelmed with people requesting things, just stating what could be improved upon when/if someone has the time to do it.

**Comment by eamodio** [comment]
Hrm, I can't reproduce the issue with `"gitlens.hovers.enabled": false` -- when that is set, for me, all hovers are disabled (as is intended). And the other settings are for more granular control -- so you can turn on/off exactly the feature you want. It is a pattern I follow regularly -- a more global setting to turn a whole feature off and additional toggles for individual parts.

As for the UX of the GitLens settings UI -- what is the issue or what should be improved? I went to a LOT of effect to make that settings UI easy to use and show you what most settings will actually do.

And as for the UX of the built-in VS Code settings UI -- unfortunately VS Code offers very little control over that experience -- so there really isn't anything I can do to make it better.
