### ISSUE TITLE
Weird confetti or snow "falling" on welcome/setup screen

### ISSUE THREAD

**Issue by dmrickey** [eamodio/vscode-gitlens#1321]
- GitLens Version: 11

Steps to Reproduce:

1. Install extension
2. look at screen

The "stuff" falling from the top of the screen is incredibly distracting and disorienting. The description of the plugin sounded useful but I couldn't make it through setup before I had to uninstall it.

**Comment by eamodio** [comment]
Click the little snow man and it will stop. I will be removing it in the next release as it was a holiday thing.

![image](https://user-images.githubusercontent.com/641685/104370538-04d54480-54ed-11eb-82aa-a20d0dd84600.png)
