### ISSUE TITLE
Interactive rebase hangs

### ISSUE THREAD

**Issue by yaroslavsadin** [eamodio/vscode-gitlens#1323]
- GitLens Version: 11.1.3
- Git Version: 2.17.1
- VSCode Version: 1.52.1
- OS Version: Ubuntu 18.04

While trying to do interactive rebase, I see this command line used:

`git -c sequence.editor="'/usr/share/code/code' --wait --reuse-window" rebase --interactive master`

Problem is that it hangs, and same happens while trying to execute `/usr/share/code/code` script. Shouldn't `/usr/bin/code` be used instead?

Thanks.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
