### ISSUE TITLE
Error at startup and during stash operation

### ISSUE THREAD

**Issue by Florian-R** [eamodio/vscode-gitlens#133]
- GitLens Version: 4.4.1
- VSCode Version: 1.15.1
- OS Version: Ubuntu 16.04.3

Steps to Reproduce:

1. Start VSCode or stash / unstash any file in Git
2. Have an error message displayed by VSCode : "Error: Path must be a string. Received undefined"

Output with verbose `gitlens.outputLevel`

```log
GitLens(v4.4.1) active: /home/florian/dev/foo
Git found: 2.7.4 @ /usr/bin/git
git -c core.quotepath=false rev-parse --show-toplevel   cwd='/home/florian/dev/foo'
Git version: 2.7.4
CodeLens config changed; resetting CodeLens provider
getRemotes('/home/florian/dev/foo')
getRemotes('/home/florian/dev/foo')
git -c core.quotepath=false remote -v   cwd='/home/florian/dev/foo'
git -c core.quotepath=false remote -v   cwd='/home/florian/dev/foo'
getStash('/home/florian/dev/foo')
git -c core.quotepath=false stash list --name-status --full-history -M --format=%H -%nauthor-date %ai%nreflog-selector %gd%nsummary %B%nfilename ?   cwd='/home/florian/dev/foo'
```

Console output in dev tools : 

```
Path must be a string. Received undefined: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at GitStashCommit.get uri [as uri] (/home/florian/.vscode/extensions/eamodio.gitlens-4.4.1/out/src/git/models/commit.js:39:39)
    at StashCommitNode (/home/florian/.vscode/extensions/eamodio.gitlens-4.4.1/out/src/views/stashCommitNode.js:17:45)
    at system_1.Iterables.map.c (/home/florian/.vscode/extensions/eamodio.gitlens-4.4.1/out/src/views/stashNode.js:25:76)
    at Object.map (/home/florian/.vscode/extensions/eamodio.gitlens-4.4.1/out/src/system/iterable.js:88:19)
    at map.next (<anonymous>)
    at StashNode.<anonymous> (/home/florian/.vscode/extensions/eamodio.gitlens-4.4.1/out/src/views/stashNode.js:25:43)
    at Generator.next (<anonymous>)
    at fulfilled (/home/florian/.vscode/extensions/eamodio.gitlens-4.4.1/out/src/views/stashNode.js:4:58)
```

Also, stash explorer remain empty even with some files stashed in Git.

I'll try to debug this but thought it was worth report it if someone experimented the same.

**Comment by eamodio** [comment]
@Florian-R If you run a `git stash list` on the command line does any look strange? I'm wondering where in the stash output parsing something is going wrong.

**Comment by Florian-R** [comment]
@eamodio Dont think anything seems weird

```
10:34 $ git stash list
stash@{0}: WIP on form-improvements: 230f1b4 Make FileInput text configurable
```

FTR, in case it could help

```
10:42 $ git --version
git version 2.7.4
```

I'll try to dig more but no time at all actually :/

**Comment by eamodio** [comment]
Very strange, I can't reproduce anything like this. Will dig more into it via code inspection.

**Comment by Florian-R** [comment]
Without debugging that much, I *think* I understand what's going on. 

For some reason (which I'll call for now the dark arcanes of Linux and i18n), I recently had to tweak some locale related env vars, but this as the effect to change my git output to french instead of english.

Re-reading your statement : 

> I'm wondering where in the stash output parsing something is going wrong.

Could this be related in some way? After forcing git to output english, I don't have this error anymore and the stash explorer work as intended.

**Comment by eamodio** [comment]
@Florian-R that is definitely it -- GitLens can only deal with parsing English output from git. Sorry about that.

**Comment by Florian-R** [comment]
No problem. Thanks for your input and your extensions.

I'll close this one as it works as intended.
