### ISSUE TITLE
Contributors view doesn't update after fetch

### ISSUE THREAD

**Issue by jasonwilliams** [eamodio/vscode-gitlens#1335]
- GitLens Version: 11.1.3
- Git Version: Run `git --version` 2.14.1

- VSCode Version: Run `code --version`: 1.53
- OS Version: Windows 10

In this image I'm using Git Graph on the right and GitLens on the left. Git Graph seems to use data from the upstream I fetched. However on the left contributors is using my local master (which is a few months behind). The left shows Andrew Clark's last commit as 4 months ago but on the right he committed today (19th Jan) 

![image](https://user-images.githubusercontent.com/936006/105080776-38821280-5a89-11eb-8a67-f539fe812971.png)

Now that autofetch [fetches all remotes](https://github.com/microsoft/vscode/issues/110811) routinely is it possible for contributors to reflect the latest changes remotely, without me needing to pull? Similar to how Git Graph is working.
This would be useful to see what changes contributors have added without needing to switch branches to master then pulling from upstream.

**Comment by eamodio** [comment]
So I think we need a setting as to whether the Contributors view uses the current branch or the current branch's upstream to determine its history. It should be pretty straightforward to add that.

Would you mind opening a PR to add it or get it started? I'd be happy to help point in the right direction, etc.

**Comment by eamodio** [comment]
I've added a few new options for the contributors view and additionally it will use the upstream branch by default if one exists.

New options:
- `gitlens.views.contributors.showAllBranches` &mdash; Specifies whether to show commits from all branches in the _Contributors_ view
- `gitlens.sortContributorsBy` &mdash; Specifies how contributors are sorted in quick pick menus and views


Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by jasonwilliams** [comment]
> Can you please verify this fix in tomorrow's insiders edition?

Yes I will, thank you very much for working on this!

**Comment by jasonwilliams** [comment]
Testing on insiders.

When adding someone's remote the contributors doesn't update. I think its OK if it doesn't update live but it also didn't update when pressing the refresh button. It only worked when I did a "reload window".

Should "refresh" force a rescan?

**Comment by eamodio** [comment]
@jasonwilliams are you testing with showing all commits? Or what is the scenario/steps here, so I can reproduce it?

**Comment by jasonwilliams** [comment]
@eamodio sure.

Settings are 
```json
{
  "gitlens.views.contributors.showAllBranches": true,
  "gitlens.sortContributorsBy": "date:desc",
}
```

* Repo: https://github.com/boa-dev/boa
* Open contribuitors view -> boa
* run `git remote add fermian git@github.com:fermian/boa.git`
* No change in the contributors view
* Run the VSCode command "Reload Windows"
* Load the view again, you will see `fermian` get added
* now run `git remote remove fermian`
* fermian is removed instantly without needing to reload the window

**Comment by eamodio** [comment]
Awesome. Thank you will take a look soon

**Comment by jasonwilliams** [comment]
I understand this would be additional scope/future request. But some sort of ignore functionality would be nice. As I always have “dependabot” and “GitHub Actions” on the top and I don’t care about them. One of them doesn’t even have any commits to show.

if you follow the above steps you’ll see for yourself.

I’m guessing an array in settings and then using that when you loop through 🤷‍♂️

**Comment by eamodio** [comment]
@jasonwilliams following your steps above, I never see anything from `fermian` show up. My guess is that there is some `fetch --all` operation happening in the background, and is what is happening on the window reload. As when you hit the refresh button on the _Contributors_ view, GitLens clears its caches and gets the data directly from Git.

As for the ignore request, please open a new feature request -- thanks!

**Comment by jasonwilliams** [comment]
> My guess is that there is some fetch --all operation happening in the background, and is what is happening on the window reload.

My `git.autoFetch` is set to “all” so that would make sense. I’m guessing on window reload VSCode is calling fetch which then puts fermians branches there.
