### ISSUE TITLE
Some Full-width characters break file-blame alignment

### ISSUE THREAD

**Issue by stania** [eamodio/vscode-gitlens#1339]
I guess that https://github.com/eamodio/vscode-gitlens/issues/135 has been reproduced.

![image](https://user-images.githubusercontent.com/903320/105470359-cefa4200-5cdc-11eb-8fe5-d49765a029f0.png)

(all pixelated characters are latin characters)

- GitLens Version: 11.1.3
- Git Version: 2.25.1
- VSCode Version: 1.52.1 ea3859d4ba2f3e577a159bc91e3074c5d85c0523 x64 (i'm using vscode remote in WSL2)
- OS Version: Windows 10 Pro 20H2

**Comment by eamodio** [comment]
@stania Can you provide me with the lines that cause issues?

Or you can try debugging at the code here, where I try to figure out the "visual" width of the string

https://github.com/eamodio/vscode-gitlens/blob/146cd564b9435dbc8c2e92b2e1242e3a811ac38c/src/system/string.ts#L447-L508
