### ISSUE TITLE
Repositories view changes including changes from older commits in diff

### ISSUE THREAD

**Issue by AnthonyWeston** [eamodio/vscode-gitlens#1347]
Sometimes when I am reviewing changes in the Repositories view under the "X files changed" heading, when I click the changed file to open the diff, it will display current changes as well as changes from older commits. This only happens when I am viewing all the changes for the file or just the staged changes. Opening the unstaged changes correctly shows only unstaged changes. I haven't figured out how to reproduce this consistently.

Recently I was working in a repository with a master branch, a development branch that is periodically merged into master, and a local branch for a bugfix that is a few commits ahead of the development branch. The bugfix branch isn't on the remote repository yet, but everything else is. I currently have 12 uncommitted changes, and when I open the changes for one of the files, it includes the diff for a commit from over a year ago. The development and bugfix branches were created recently, so all three branches had the same history up until about a month ago.

This is a private repository so I can't link to the example, and really have no idea how to reproduce the issue intentionally. If anyone has ideas or knows any additional info that I should include, I would greatly appreciate it!

Log output: Sorry, I wrote the above description a few days ago, and things are no longer in a state to reproduce the issue. I'll update this with the debug logs next time I run into this issue.

- GitLens Version: 11.1.3
- Git Version: 2.29.2.windows.2

VSCode Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

Not sure

**Comment by eamodio** [comment]
I'm not sure what might be going on here, and you haven't reported back if it happened again, so I'm going to close this. If it does happen again and you can capture what you are seeing in a video and/logs please re-open the issue. Thanks!
