### ISSUE TITLE
Duplicate icons on File history and line history

### ISSUE THREAD

**Issue by sailajapalakodeti** [eamodio/vscode-gitlens#1348]
- GitLens Version: 11.1.3

- Git Version: git version 2.19.2.windows.1

- VSCode Version: 1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64

- OS Version: Windows 10

Steps to Reproduce:

1. Select any file and go to File History or Line History, each icon is repeated twice.
2. Here is the screenshot:

![image](https://user-images.githubusercontent.com/12281762/105886516-80002580-5fd8-11eb-8fe7-5effa7dc3bff.png)

![image](https://user-images.githubusercontent.com/12281762/105886647-a3c36b80-5fd8-11eb-8837-9e9e45d24752.png)

**Comment by eamodio** [comment]
Do you possibly have both the stable and insiders editions of GitLens installed?

**Comment by sailajapalakodeti** [comment]
yeah.. you're right.. I've installed insiders edition too and it resulted in duplicate icons. 

Actually I was using remote explorer extension on VSCode and opened another remote instance of VSCode. There I've installed GitLens insider edition. So now in my local VSCode instance it shows both stable and insider editions resulting in duplicate icons.
