### ISSUE TITLE
gitlogs

### ISSUE THREAD

**Issue by navdeep-msp** [eamodio/vscode-gitlens#1350]
show all commit changes, by person name, logs of commit.

**Comment by eamodio** [comment]
Are you looking for something like the _Contributors_ view?

![image](https://user-images.githubusercontent.com/641685/106241300-cec5df00-61d3-11eb-97e3-9498fcdcd04d.png)

If so, it is hidden by default, but can be easily turned on from the:

1. Command palette
  ![image](https://user-images.githubusercontent.com/641685/106241421-03399b00-61d4-11eb-9f22-709544089429.png)
2. View context menu (Right-click on any GitLens view header)
![image](https://user-images.githubusercontent.com/641685/106241488-23695a00-61d4-11eb-809a-751b39d602ac.png)

**Comment by navdeep-msp** [comment]
Great..
Thanks..
I was looking for the same.


Kind Regards,

Navdeep Dhami

Web Development

[cid:image001.png@01D446B5.C630F870]

________________________________
