### ISSUE TITLE
Initial install shows what's new notification

### ISSUE THREAD

**Issue by Tyriar** [eamodio/vscode-gitlens#1351]
Maybe this is because I had installed it previously on this machine, but I installed gitlens for the first time in a long time if so and got hit with this notification (as well as a github auth one).

<img width="465" alt="Screen Shot 2021-01-28 at 8 00 05 AM" src="https://user-images.githubusercontent.com/2193314/106164495-e2733600-613e-11eb-8089-81daa5933f26.png">

This shouldn't have shown because it was a fresh install.

**Comment by Tyriar** [comment]
I also got it on my other machine when it synced 😱

**Comment by eamodio** [comment]
I'm not sure how to handle this one. Since VS Code doesn't remove storage keys, as far as GitLens knows this isn't a first install -- since there was old data there.

As for the 2nd issue, it looks like that is a bug. I am syncing the version across, but if the machine had a local version, it uses that over the sync'd version.

**Comment by Tyriar** [comment]
> I'm not sure how to handle the first one. Since VS Code doesn't remove storage keys, as far as GitLens knows this isn't a first install -- since there was old data there.

Is there an uninstall event you could hook into or you could do something with the time like if it's been x months since gitlens activated don't notify? The two cases I can think of is someone hasn't done any coding for x months so you don't want extensions to all popup notifications, or my situation where it's been uninstalled for x months.

**Comment by eamodio** [comment]
I don't know of any uninstall hook (outside of the VSIX hook, but that is at the filesystem level not within vscode).

Yeah, I could add a timestamp, but I'm not sure it's worth it. Your case is certainly not ideal, but the away for a while case, I don't see that any differently than if you haven't been away.

**Comment by Tyriar** [comment]
> but the away for a while case, I don't see that any differently than if you haven't been away.

The difference is if n extensions do this, the first time back to VS Code experience is n+ notifications. I doubt any of which is important to the user.

**Comment by eamodio** [comment]
Yeah, just because it's more likely because more time has passed. Ultimately, I want to completely avoid any notifications like this, and have VS Code be able to aggregate and show these in nice and tidy UI.

**Comment by Tyriar** [comment]
👍 close in favor of https://github.com/microsoft/vscode/issues/102139 then?

**Comment by eamodio** [comment]
Yeah, ideally that is what I want. But I will still fix the issue that you saw where you can see the notification more than once -- that shouldn't have been happening.

**Comment by eamodio** [comment]
I've fixed the 2nd issue. And will wait for microsoft/vscode#102139 to land
