### ISSUE TITLE
Improve status bar blame flicker avoidance (and make it the default?)

### ISSUE THREAD

**Issue by Tyriar** [eamodio/vscode-gitlens#1353]
When changing lines, the status bar entry hides and then shows again, sometimes with the same content.

![recording (55)](https://user-images.githubusercontent.com/2193314/106165857-65e15700-6140-11eb-8dc6-992a7227dca9.gif)

Some ideas to avoid some visual noise:

- Waiting up to 500ms or so before swapping out the stale text
- Better caching of blame lines for the current file (if you're waiting on the `git blame`?)
- Using the same status bar item instead of creating a new one?

**Comment by eamodio** [comment]
Can set `"gitlens.statusBar.reduceFlicker": true,"`

![image](https://user-images.githubusercontent.com/641685/106199095-ef197d80-6182-11eb-99c0-aeb914166301.png)

**Comment by Tyriar** [comment]
I'm curious why this wouldn't be the default and only option?

**Comment by eamodio** [comment]
For 2 main reasons -- because since it continues to show the previous value, its technically wrong, until it updates, and I prefer it off :smile:

**Comment by Tyriar** [comment]
Hmm ok, well you're the boss 😄 

Personally, this seems like a perfect opportunity to simplify the extension by removing a setting. An alternative approach could be to change the icon to a refresh icon briefly, the icon changing and status bar item remaining stable is better than the entry disappearing and appearing (esp. if there are more entries to the left).

**Comment by eamodio** [comment]
Good idea with the icon, what do you think?

![flicker-free](https://user-images.githubusercontent.com/641685/106236077-1c3d4e80-61ca-11eb-8cb7-6a30e07e248b.gif)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by Tyriar** [comment]
Nice 👍, it might be better to avoid the spin animation to reduce some more noise?
