### ISSUE TITLE
Stuck after merge a branch  with a single quote in the name

### ISSUE THREAD

**Issue by chumfeik** [eamodio/vscode-gitlens#1354]
After the attempt to merge a branch with a single quote in its name GitLens stuck with the next message:
`Pulling last-price-in-the-trade-form's-price-field...`

- GitLens Version:
- Git Version: 2.17.1

- VSCode Version: 1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
- OS Version: Ubuntu 18.04.5 LTS (WSL, Windows 10 )

Steps to Reproduce:

1. Create a branch with a single quote in its name
2. Checkout to `master`
3. Do right click on `branch-with-a-single-qu'ote-in-its-name`
4. `Merge Branch into Current Branch...`
5. Stuck

[2021-01-30 18:32:01:916] /home/<user>/.vscode-server/extensions/eamodio.gitlens-11.1.3/dist/gitlens.js:2:844163
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false merge-base --fork-point branch-with-a-single-qu'ote-in-its-name HEAD

I guess the solution should be:
/usr/bin/git -c core.quotepath=false -c color.ui=false merge-base --fork-point `"`branch-with-a-single-qu'ote-in-its-name`"` HEAD

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
