### ISSUE TITLE
Source control commit placeholder message shows wrong branch when initialized with 'main' branch.

### ISSUE THREAD

**Issue by EntityAdam** [eamodio/vscode-gitlens#1356]
- GitLens Version:v11.1.3
- Git Version: git version 2.28.0.windows.1
- VSCode Version: 1.52.1
- OS Version: 20H2

Steps to Reproduce:

1. git init
2. observe gitlens 'source control' pane -> "Message (Ctrl+Enter to commit on 'master')"
3. observe gitlens 'branches' pane -> The only existing branch is 'main'

Expected observation:
'source control' pane should have a commit message placeholder of "Message (Ctrl+Enter to commit on 'main')"

Reasoning:
I'm sure there's more exciting things to tackle but this could be confusing to some.

**Comment by eamodio** [comment]
That UI comes from VS Code itself. Please open an issue on the vscode repository. Thanks!
