### ISSUE TITLE
Branch sorting may be reversed

### ISSUE THREAD

**Issue by sueka** [eamodio/vscode-gitlens#1357]
- GitLens Version: 11.1.3
- Git Version: 2.30.0
- VSCode Version: 1.52.1
- OS Version: macOS Big Sur 11.2

When I set “Sort Branches By” to “name:asc”/“name:desc”, GitLens seems to sort the branches in descending/ascending order.  The same is true for “Sort Tags By”.

**Comment by eamodio** [comment]
@sueka Thanks -- and that commit looks good. Looking forward to the PR 😄

**Comment by sueka** [comment]
@eamodio Thanks. Opened the PR #1358. Should I also change the default value of “SortBranchesBy” from “name:desc” to “name:asc”?
