### ISSUE TITLE
Error 'Unable to open compare', when git setting log.showsignature is active

### ISSUE THREAD

**Issue by mtelgkamp** [eamodio/vscode-gitlens#1363]
- GitLens Version: 11.1.3
- Git Version: 2.30.0
- VSCode Version: 1.52.1
- OS Version: Ubuntu 20.10

## Steps to Reproduce

1. add git config setting `log.showsignature=true`
2. try to display a diff of a file by selecting it in the COMMITS section
3. Error: Unable to open compare. See output channel for more details

## The reason
From the logs I figured out that the following git command is called
```
git log -n1 --no-renames --format=%H --find-object=HASH ANOTHER_HASH -- FILENAME
```
When I execute it manually the output looks like this:
```
gpg: some text
gpg: some text
gpg: some text
HASH VALUE
```
Afterwards the following command is in the `GitLens (Git)` log:
```
git show --name-status --format= gpg: Signature...
```

## Idea
It might be useful to add the parameter `-c log.showSignature=false` to all git comands relying on the git output. In this case the command would look like this:
```
git  -c log.showSignature=false log -n1 --no-renames --format=%H --find-object=HASH ANOTHER_HASH -- FILENAME
```
Another option would be to ignore all output starting with `gpg: `.

**Comment by eamodio** [comment]
Great catch -- it looks like I had a bunch of newer log calls that were failing to include the `-c log.showSignature=false` parameter.

Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by mtelgkamp** [comment]
Thank you very much for the quick fix. It works for me, in the insider edition.
