### ISSUE TITLE
Suppress message "GitLens was unable to find Git"

### ISSUE THREAD

**Issue by thernstig** [eamodio/vscode-gitlens#1368]
I run VS Code in Windows but develop exclusively with the remote extensions (WSL, ssh, containers). This means I never install git in Windows. Yet, I always get this error when launching VS Code

> GitLens was unable to find Git. Please make sure Git is installed. Also ensure that Git is either in the PATH, or that 'git.path' is pointed to its installed location.

It would be nice if this could be added as a config:

```json
  "gitlens.advanced.messages": {
    "suppressGitNotInstalled": true
  },
```

That way I can suppress that message from showing up at every start.

**Comment by eamodio** [comment]
GitLens can't work without Git installed. So for your scenario, I would recommend disabling GitLens locally, an only leave it on in the remote.

**Comment by thernstig** [comment]
Afaik that is not possible. I just tested it .

Note that I open VS Code in Windows (without being connected to a remote). The only option I then have is to disable globally. This is then synced to all my machines, meaning Gitlens is even disabled locally/remotely for all my machines.

**Comment by eamodio** [comment]
@sandy081 is that expected? I wouldn't have expected the local enabled state to be synchronized to a remote.

**Comment by thernstig** [comment]
By the way, I have a about 20 extensions and many of them require something else to be installed to function. E.g. the docker extension requires docker, but it still does not give me an error when I launch VS Code. Every other extension handles this gracefully only giving me warning/errors/notifications or uses GUI in ways to inform me that it does not work, when actually invoking it.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by sandy081** [comment]
We do not sync local to remote. 

> This is then synced to all my machines, meaning Gitlens is even disabled locally/remotely for all my machines.

I think user is mentioning about other machines when said remote

**Comment by thernstig** [comment]
@sandy081 correct, I meant to other machines (i.e. other laptops I have). But on those other laptops, it then also disables it both locally and on ssh remotes after the sync.

But it's moot now as it seems @eamodio has fixed it :)
