### ISSUE TITLE
Editor is scrolled down after switching from current tab to another and then returning to the original tab

### ISSUE THREAD

**Issue by kiewic** [eamodio/vscode-gitlens#137]
- GitLens Version: 4.4.3
- VSCode Version: 1.15.1
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Open two files, A and B. A must be a very large file.
2. Navigate to some line in the middle of file A, let say line 1390.
3. Switch to file B tab.
4. Return to file A tab, and notice that the page has been scrolled down. Now the first line displayed is line 1450, and line 1390 is not visible now. Although the cursor is still in line 1390, it requires an extra scroll or key press to force the screen to display line 1390 again.

The issue does not reproduce right after opening VSCode, but it reproduces after some tab switches. About 10 tab switched.

Is this a known issue? 

P.S. Thanks for the great extension!

**Comment by eamodio** [comment]
@kiewic Thanks! I looked into this quickly and it looks like an issue with vscode itself when showing code lens. Here is the open issue: https://github.com/Microsoft/vscode/issues/32397
