### ISSUE TITLE
Add capability to view blame prior to line change

### ISSUE THREAD

**Issue by swrobel** [eamodio/vscode-gitlens#1370]
This feature is available in both Github & GitLab and is the most common reason why I use the "Open File on Remote" feature of Gitlens.

**Github:**
<img width="746" alt="Screen Shot 2021-02-08 at 8 15 27 PM" src="https://user-images.githubusercontent.com/157270/107314899-a6f03a00-6a63-11eb-82a6-242a265527cb.png">

**GitLab:**
<img width="1055" alt="Screen Shot 2021-02-08 at 8 16 12 PM" src="https://user-images.githubusercontent.com/157270/107314903-a8216700-6a63-11eb-8180-70b6e4494f8e.png">

**Comment by eamodio** [comment]
This exists in the hovers today:

![image](https://user-images.githubusercontent.com/641685/107321501-a27e4e00-6a70-11eb-8958-68d4ed98f9d6.png)

Does that meet your needs?

**Comment by eamodio** [comment]
See also https://github.com/eamodio/vscode-gitlens/issues/1014 for a newly added command to the command palette to do the same.

**Comment by swrobel** [comment]
Fantastic! Thank you for the quick response - sorry I missed that!
