### ISSUE TITLE
Unexpected repository detection on editor startup after recent updates

### ISSUE THREAD

**Issue by Songworks** [eamodio/vscode-gitlens#1372]
- GitLens Version: 11.2.1
- Git Version: 2.30.0
- VSCode Version: 1.53.1
- OS Version: Ubuntu 20.04.2 LTS

Steps to reproduce:

I have a simple vscode .project file that looks like this:
```
{
	"folders": [
        {
            "path": "ee/source-code"
        },
        {
            "path": "."
        },
    ],
    "settings": {}
}
```

It contains several git repositories:

- ./ee/source-code
- ./ce/source-code
- ./documentation

And I have the setting `git.autoRepositoryDetection` set to `openEditors`, so that only the repositories I actually work on, are detected for version control in VSCode.

However since a couple days (apparently both GitLens and VSCode had updates recently) all repositories are detected by GitLens on editor startup. I've tested that it happens with GitLens active only (though not if it's mayhaps a conflict with any other extension).

I can "fix" this by setting `gitlens.advanced.repositorySearchDepth` to `0` (rather than the default of `1`) and get back to how I'd expect it to work. But I figured I'd mention this new, unexpected behaviour anyway.

Thanks for a great extension by the way.
Cheers!

**Comment by DoctorPolski** [comment]
Not sure if this is somehow linked but similar to above I have some weirdness today after a number of various updates:

- the rendered settings page for GitLens no longer shows graphics and the formatting is broken. 
- interactive rebase editor is broken
- interactive rebase editor intercepts interactive rebases even when it is not enabled

Windows: 10.0.19042.789
VS Code: 1.53.1
Debian on WSL2: 4.19.104-microsoft-standard
Git: 2.20.1

There were recent updates to WSL2 Debian and the WSL plugin for VS Code.

**Comment by eamodio** [comment]
@DoctorPolski definitely not related to this issue. Please try uninstalling and reinstalling GitLens to see if that helps. If not, please open a new issue. Thanks!

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by Songworks** [comment]
@eamodio Could not reproduce the problem on Gitlans Insider v2021.3.904 anymore.
Cheers!
