### ISSUE TITLE
Interactive rebase warns electron deprecation warning

### ISSUE THREAD

**Issue by sralloza** [eamodio/vscode-gitlens#1377]
- GitLens Version: 11.2.1
- Git Version: 2.30.1.windows.1
- VSCode Version: 1.53.2, 622cb03f7e070a9670c94bae1a45d78d7181fbd4, x64
- OS Version: Microsoft Windows Home version 20H2 (compilation version 19042.746)

Steps to Reproduce:

1. Run `git rebase -i head~2` to run the interactive rebase.

Console example:

```
D:\example-repo>git rebase -i head~2
hint: Waiting for your editor to close the file...
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports 
will be uploaded gzipped, which most crash reporting servers support.
Successfully rebased and updated refs/heads/ci.
```

**Comment by eamodio** [comment]
@sralloza Does anything go wrong or is this just about the warning?

@deepak1556 Do you have any idea why VS Code would output this warning? It's being run as the GIT_EDITOR.

**Comment by sralloza** [comment]
Just the warning. It appears again later if i join commits in the rebase, but it works fine.

**Comment by deepak1556** [comment]
Refs https://github.com/microsoft/vscode/issues/115888
