### ISSUE TITLE
Support `Open on Github` as a setting value for `gitlens.statusBar.command`

### ISSUE THREAD

**Issue by joaomoreno** [eamodio/vscode-gitlens#1378]
This would be awesome!

**Comment by eamodio** [comment]
Can you please verify this fix in the insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by joaomoreno** [comment]
YES! Works perfectly. Thanks for this @eamodio.

cc @isidorn
