### ISSUE TITLE
Add support for gitea as a remote

### ISSUE THREAD

**Issue by septatrix** [eamodio/vscode-gitlens#1379]
Gitea is a popular, lightweight alternative to GitHub or GitLab and becoming increasingly popular. It would be nice to add native support for it as a remote. Currently one has to set up a custom remote and specify all the urls to fully use it.

**Comment by eamodio** [comment]
Sounds like a good idea. Would you mind opening a PR to add it or get it started? I'd be happy to help point in the right direction, etc.

**Comment by septatrix** [comment]
If you could point me to where I should get starter/what needs to be implemented I would be happy to help

**Comment by danBamikiya** [comment]
I'd be happy to help also!

**Comment by eamodio** [comment]
You can use `github` as an example to copy from: https://github.com/eamodio/vscode-gitlens/blob/e657def760a118197a9e65a11c8899ddf08e01c2/src/git/remotes/github.ts

And it needs to be added in here:
https://github.com/eamodio/vscode-gitlens/blob/cf5a394f8ec8dbf39c6b4c96022438d08ed12571/src/git/remotes/factory.ts

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by septatrix** [comment]
Yes everything seems to work as expected (apart from the problems with tags I already described in the PR).

**Comment by AlencarGabriel** [comment]
Hey guys,

in this issue were the avatars treated?

I was studying a Gitea implementation to support its avatars, and I ended up finding this issue.

**Comment by eamodio** [comment]
@AlencarGabriel No, this support for Gitea doesn't include "rich" support which covers avatars.

**Comment by AlencarGabriel** [comment]
It's ok.

To implement this it's necessary to adjust in `src/avatars.ts` and to treat separately as the implementation of GitHub?

**Comment by eamodio** [comment]
Ideally it would be a full "rich" provider implementation similar to GitHub, and the PR for GitLab (that I will be merging in soon)

**Comment by AlencarGabriel** [comment]
Understood. 

I'll evaluate how avatars work in Gitea, and after the next version comes out, I try to implement the "rich" provider.
