### ISSUE TITLE
Branch names are not properly escaped in git commands

### ISSUE THREAD

**Issue by chausner** [eamodio/vscode-gitlens#1391]
- GitLens Version: 11.2.1
- Git Version: 2.30.0
- VSCode Version: 1.53.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Create a branch with parenthesis in the name, e.g. my-branch(test)
2. Use GitLens to delete the branch

The following message appears in the terminal:
```
$ git branch --delete my-branch(test)
bash: syntax error near unexpected token `('
```

I haven't tested with any other actions but I assume this is a general issue with how git commands are constructed, not specific to the deletion of branches.

**Comment by danBamikiya** [comment]
I reproduced your steps for creating a branch with a parentheses and its not possible(using GitLens and git cli). Eg: when I created the branch `my-branch(test)` the branch both GitLens and git cli produced were `my-branch`

**Comment by chausner** [comment]
I was using the VS code command to create a new branch.

I also just tested on Windows and git 2.28.0.windows.1 CLI:
```
> git checkout -b "my-branch(test)"
Switched to a new branch 'my-branch(test)'
> git status
On branch my-branch(test)

No commits yet

nothing to commit (create/copy files and use "git add" to track)
```

See also https://stackoverflow.com/a/3651867. It does not disallow parentheses.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
