### ISSUE TITLE
More branch status

### ISSUE THREAD

**Issue by hg-zt** [eamodio/vscode-gitlens#1392]
## Motivation

- We have colorful dots for branches to show whether it's updated, but a little bit ambiguous: "no dot" maybe  `unpublished` and `up-to-date`. Apart from unsynchronized branches, I'd like to be aware of unpublished, merged or useless temporary branches in the GitLens branches view. (related: https://github.com/eamodio/vscode-gitlens/issues/1025)
- Colorful dots are not very intuitive for me. (green for ahead, yellow for diverged)
- There is no `merged` status (`git branch --merged`). It's my weekly routine to use `git show-merged-branches` and `git delete-merged-branches` from https://github.com/tj/git-extras to cleanup my git repo. It would be great if I could do these staff in GitLens.

## Proposal

It would be better if we could show these status before or after branch names. I'm using text labels for description. Maybe using icons would be more compact. Most icons below could be found in font awesome (https://fontawesome.com/cheatsheet)

1. (fixed) relationship to the upstream branch
     - has upstream branch
       - `ahead` (upload cloud icon or upload icon)
       - `behind` (download cloud icon or download icon)
       - `up-to-date` (synchronized icon)
       - `diverged` for both behind and ahead (error icon or exclamation)
    - no upstream branch: `local-only` (desktop icon)
2. (optional) relationship to current branch
   - `current` (check mark icon)
   - `merged` (git merge icon)
   - (none)
3. (optional) worktree status
   - `worktree` if the branch is linked with a worktree (git branch icon?)
   - (none)

So it may looks like (quite similar to `git branch -vv` without commit messages):

- [up-to-date] [current] main
- [local-only] [merged] some-finished-feature (this branch has been merged and deleted on remote)
- [local-only] some-local-wip-feature
- [ahead] some-published-feature-with-new-changes
- ...

**Comment by eamodio** [comment]
In the latest insiders edition, I've added some "decoration" support to the branches view that will show some of the status you are looking for.

![image](https://user-images.githubusercontent.com/641685/109453198-7460ae00-7a1f-11eb-914b-b86bc15c27db.png)

- ⮝ — ahead, the row will also be green
- ⮟ — behind, the row will also be red
- ⮟⮝ — diverged, the row will also be yellow
- ⮙+ — unpublished, the row will also be green

Additionally, I've replaced the ✓ checkmark before the branch name, with a ✓ checkmark at the end for the current branch (this will be in addition to the other decorations)

![image](https://user-images.githubusercontent.com/641685/109453746-d0780200-7a20-11eb-91d8-2c9ecfa2fa7e.png)

There is currently no icon/color for local-only branches (e.g. a branch with no upstream in a repo with no remote) or up-to-date branches.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
