### ISSUE TITLE
Gitlens icon not showing in the activity bar

### ISSUE THREAD

**Issue by akmalick** [eamodio/vscode-gitlens#1397]
The first time I installed Gitlens, everything was just fine and the GitLens icon showed up in the Activity bar of VSCode. Few days back I right-clicked on activity bar and accidentally unchecked the GitLens and ever since I have not beeen able to get it back. I looked up over the internet but no luck. tried few settings like  

- GitLens Version:11.2.1
- Git Version: 2.30.1.windows.1

- VSCode Version: 1.53.2
- OS Version: Windows 10

**Steps to Reproduce:**

1.Install Gitlens plugin
2.right-click on the VSCode activty bar and uncheck Gitlens
3.Now Gitlens should be gone forever.

**Log from Gitlens(Git) channel :**

> [2021-02-25 15:35:16:334] [c:\GitWorkspace\TOOL\Migration\InTransaction] git rev-parse --show-toplevel • 90 ms 
> [2021-02-25 15:35:16:410] [c:/GitWorkspace/TOOL/Migration/InTransaction] git remote -v • 57 ms 
> [2021-02-25 15:35:16:558] [c:\Users\asif\AppData\Roaming\Code\User] git rev-parse --show-toplevel • FAILED 45 ms 
> 
> Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel
> fatal: not a git repository (or any of the parent directories): .git
> 
> [2021-02-25 15:35:16:600] [] git ls-files -- c:\Users\asif\AppData\Roaming\Code\User\settings.json • 41 ms 

**Log from Gitlens channel:**

> [2021-02-25 15:35:16:150] GitLens (v11.2.1): syncedVersion=11.2.1, localVersion=11.2.1, previousVersion=11.2.1, gitlens:views:welcome:visible=undefined, gitlens:views:updates:visible=false
> [2021-02-25 15:35:16:151] [1] GitService.initialize
> [2021-02-25 15:35:16:151] [2] GitService.getBuiltInGitApi
> [2021-02-25 15:35:16:156] [2] GitService.getBuiltInGitApi completed • 5 ms
> [2021-02-25 15:35:16:229] Git found: 2.30.1.windows.1 @ C:\Program Files\Git\cmd\git.exe • 72 ms
> [2021-02-25 15:35:16:229] [1] GitService.initialize completed • 78 ms
> [2021-02-25 15:35:16:243] Starting repository search in 1 folders
> [2021-02-25 15:35:16:243] [3] GitService.repositorySearch(c:\GitWorkspace\TOOL\Migration\InTransaction) searching (depth=1)...
> [2021-02-25 15:35:16:243] [4] GitService.getRepoPathCore — e=c:\GitWorkspace\TOOL\Migration\InTransaction, t=true
> [2021-02-25 15:35:16:247] [5] LineAnnotationController.resume
> [2021-02-25 15:35:16:247] [6] GitLineTracker.start
> [2021-02-25 15:35:16:247] [6] GitLineTracker.start completed • 0 ms
> [2021-02-25 15:35:16:247] [5] LineAnnotationController.resume completed • 0 ms
> [2021-02-25 15:35:16:247] [7] LineAnnotationController.refresh
> [2021-02-25 15:35:16:247] [8] GitLineTracker.start
> [2021-02-25 15:35:16:247] [8] GitLineTracker.start completed • 0 ms
> [2021-02-25 15:35:16:247] [9] GitLineTracker.start
> [2021-02-25 15:35:16:247] [9] GitLineTracker.start completed • 0 ms
> [2021-02-25 15:35:16:256] GitLens (v11.2.1) activated • 106 ms
> [2021-02-25 15:35:16:256] [7] LineAnnotationController.refresh completed • 8 ms
> [2021-02-25 15:35:16:334] [c:\GitWorkspace\TOOL\Migration\InTransaction] git rev-parse --show-toplevel • 90 ms 
> [2021-02-25 15:35:16:334] [4] GitService.getRepoPathCore completed • 91 ms
> [2021-02-25 15:35:16:334] [3] GitService.repositorySearch(c:\GitWorkspace\TOOL\Migration\InTransaction) found root repository in 'c:/GitWorkspace/TOOL/Migration/InTransaction'
> [2021-02-25 15:35:16:335] [a] GitService.repositorySearchCore — e=c:\GitWorkspace\TOOL\Migration\InTransaction, t=1
> [2021-02-25 15:35:16:336] [b] GitService.repositorySearchCore — e=c:\GitWorkspace\TOOL\Migration\InTransaction\.github, t=0
> [2021-02-25 15:35:16:342] [b] GitService.repositorySearchCore completed • 5 ms
> [2021-02-25 15:35:16:342] [c] GitService.repositorySearchCore — e=c:\GitWorkspace\TOOL\Migration\InTransaction\.gradle, t=0
> [2021-02-25 15:35:16:342] [c] GitService.repositorySearchCore completed • 0 ms
> [2021-02-25 15:35:16:343] [d] GitService.repositorySearchCore — e=c:\GitWorkspace\TOOL\Migration\InTransaction\build, t=0
> [2021-02-25 15:35:16:343] [d] GitService.repositorySearchCore completed • 0 ms
> [2021-02-25 15:35:16:343] [e] GitService.repositorySearchCore — e=c:\GitWorkspace\TOOL\Migration\InTransaction\gradle, t=0
> [2021-02-25 15:35:16:343] [e] GitService.repositorySearchCore completed • 0 ms
> [2021-02-25 15:35:16:343] [f] GitService.repositorySearchCore — e=c:\GitWorkspace\TOOL\Migration\InTransaction\src, t=0
> [2021-02-25 15:35:16:344] [f] GitService.repositorySearchCore completed • 1 ms
> [2021-02-25 15:35:16:344] [10] GitService.repositorySearchCore — e=c:\GitWorkspace\TOOL\Migration\InTransaction\WebContent, t=0
> [2021-02-25 15:35:16:345] [10] GitService.repositorySearchCore completed • 0 ms
> [2021-02-25 15:35:16:345] [a] GitService.repositorySearchCore completed • 9 ms
> [2021-02-25 15:35:16:345] [3] GitService.repositorySearch(c:\GitWorkspace\TOOL\Migration\InTransaction) returned 1 repositories (c:/GitWorkspace/TOOL/Migration/InTransaction) • 101 ms
> [2021-02-25 15:35:16:345] [11] GitService.openBuiltInGitRepository — e=c:/GitWorkspace/TOOL/Migration/InTransaction
> [2021-02-25 15:35:16:345] [12] GitService.getBuiltInGitApi
> [2021-02-25 15:35:16:345] [12] GitService.getBuiltInGitApi completed • 0 ms
> [2021-02-25 15:35:16:394] [11] GitService.openBuiltInGitRepository completed • 48 ms
> [2021-02-25 15:35:16:410] [c:/GitWorkspace/TOOL/Migration/InTransaction] git remote -v • 57 ms 
> [2021-02-25 15:35:16:411] [13] GitRemoteParser.parse completed • 0 ms
> [2021-02-25 15:35:16:411] [14] GitService.getRichRemoteProvider — {"includeDisconnected":false}
> [2021-02-25 15:35:16:411] [14] GitService.getRichRemoteProvider completed • 0 ms
> [2021-02-25 15:35:16:411] [15] GitService.getRichRemoteProvider — {"includeDisconnected":true}
> [2021-02-25 15:35:16:411] [15] GitService.getRichRemoteProvider completed • 0 ms
> [2021-02-25 15:35:16:511] [16] GitUri.fromUri — e=Uri(file:///c:/Users/asif/AppData/Roaming/Code/User/settings.json)
> [2021-02-25 15:35:16:511] [17] GitService.getRepoPath — e=Uri(file:///c:/Users/asif/AppData/Roaming/Code/User/settings.json)
> [2021-02-25 15:35:16:511] [18] GitService.getRepository — e=Uri(file:///c:/Users/asif/AppData/Roaming/Code/User/settings.json), t={"skipCacheUpdate":true}
> [2021-02-25 15:35:16:512] [19] GitService.findRepositoryForPath — e=count=1, t=c:\Users\asif\AppData\Roaming\Code\User\settings.json, i=false
> [2021-02-25 15:35:16:512] [19] GitService.findRepositoryForPath completed • 0 ms
> [2021-02-25 15:35:16:512] [18] GitService.getRepository returned undefined • 0 ms
> [2021-02-25 15:35:16:512] [1a] GitService.getRepoPathCore — e=c:\Users\asif\AppData\Roaming\Code\User\settings.json, t=false
> [2021-02-25 15:35:16:558] [c:\Users\asif\AppData\Roaming\Code\User] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel • not a git repository (or any of the parent directories): .git • 45 ms 
> [2021-02-25 15:35:16:558] [1a] GitService.getRepoPathCore completed • 45 ms
> [2021-02-25 15:35:16:558] [17] GitService.getRepoPath returned undefined • 46 ms
> [2021-02-25 15:35:16:558] [16] GitUri.fromUri returned GitUri(file:///c:/Users/asif/AppData/Roaming/Code/User/settings.json) • 47 ms
> [2021-02-25 15:35:16:558] [1b] GitService.getRepository — e=GitUri(file:///c:/Users/asif/AppData/Roaming/Code/User/settings.json)
> [2021-02-25 15:35:16:558] [1c] GitService.findRepositoryForPath — e=count=1, t=c:\Users\asif\AppData\Roaming\Code\User\settings.json, i=false
> [2021-02-25 15:35:16:558] [1c] GitService.findRepositoryForPath completed • 0 ms
> [2021-02-25 15:35:16:558] [1b] GitService.getRepository returned undefined • 0 ms
> [2021-02-25 15:35:16:600] [] git ls-files -- c:\Users\asif\AppData\Roaming\Code\User\settings.json • 41 ms 
> [2021-02-25 15:35:16:600] [1d] GitService.isTracked returned false • 41 ms — e=GitUri(file:///c:/Users/asif/AppData/Roaming/Code/User/settings.json)
> [2021-02-25 15:35:30:336] [1e] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:35:30:336] [1e] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:35:34:339] [1f] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:35:34:340] [1f] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:35:34:819] [20] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:35:34:819] [20] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:35:49:553] [21] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:35:49:553] [21] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:36:09:852] [22] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:36:09:852] [22] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:41:42:893] [23] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:41:42:893] [23] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:41:43:410] [24] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:41:43:410] [24] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:43:11:329] [25] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:43:11:329] [25] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:43:19:194] [26] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:43:19:194] [26] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:44:17:572] [27] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:44:17:572] [27] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:44:22:422] [28] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:44:22:422] [28] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:44:22:849] [29] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:44:22:849] [29] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:44:42:002] [2a] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:44:42:002] [2a] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:44:52:387] [2b] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:44:52:387] [2b] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:44:52:657] [2c] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:44:52:657] [2c] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:44:53:504] [2d] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:44:53:504] [2d] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:44:54:519] [2e] GitService.onWindowStateChanged — e={"focused":false}
> [2021-02-25 15:44:54:519] [2e] GitService.onWindowStateChanged completed • 0 ms
> [2021-02-25 15:47:15:337] [2f] GitService.onWindowStateChanged — e={"focused":true}
> [2021-02-25 15:47:15:337] [2f] GitService.onWindowStateChanged completed • 0 ms

I tried playing around with various gitlens options in the settings,json file, but to no avail.
No trace of it whatsoever, as if my VSCode ide never really knew about Gitlens.
Please do let me know if you need any other info.

**Comment by eamodio** [comment]
You should be able to right-click on the activity bar and re-check GitLens.

**Comment by akmalick** [comment]
![GitLens](https://user-images.githubusercontent.com/5765159/109431273-a5df7680-7a2b-11eb-91ba-4a7c2cee059d.png)

As you can see, I do not get any options for selecting GitLens.

**Comment by eamodio** [comment]
My guess is that GitLens is now in the "Source Control" layout -- so its views are on the _Source Control_ activity. You should be able to switch it back to the "GitLens" layout via the `GitLens: Set Views Layout` command from the command palette.

**Comment by akmalick** [comment]
Looks like, that worked. Thank you so much. The icon though looks changed a bit from what I can recall. Is that a matter of concern.

![image](https://user-images.githubusercontent.com/5765159/109431742-096aa380-7a2e-11eb-9d25-d1c27dc58911.png)

**Comment by eamodio** [comment]
Yeah, unfortunately there was a change in VS Code that stops the correct icon from showing up, I'm hoping there will be a VS Code "fix" for that soon.
