### ISSUE TITLE
GitLens diff window not viewable

### ISSUE THREAD

**Issue by frankmit11** [eamodio/vscode-gitlens#1400]
- GitLens Version: 2.23.0.windows.1
- VSCode Version: 1.53.2 622cb03f7e070a9670c94bae1a45d78d7181fbd4 x64 
-  OS Details

Description | Information
------------ | -------------
| Edition  | Windows 10 Enterprise |
| Version | 20H2 |
| Installed on | 8/‎31/‎2020 
| OS build | 19042.804 
| Experience | Windows Feature Experience Pack 120.2212.551.0

Steps to Reproduce:

https://user-images.githubusercontent.com/5862477/109225409-3ea39700-778b-11eb-811f-e4995de452e2.mp4

**Comment by eamodio** [comment]
@frankmit11 That seems like a VS Code bug, are you still seeing that behavior?

**Comment by frankmit11** [comment]
@eamodio Problem appears to be resolved now, not entirely sure why....if I encounter this again I will open an issue with VS Code.

**Comment by eamodio** [comment]
Sounds good thanks!
