### ISSUE TITLE
the "g" key does not work at vs code

### ISSUE THREAD

**Issue by sajadsholi** [eamodio/vscode-gitlens#1403]
- GitLens Version:v11.2.1
- Git Version: 2.23

- VSCode Version:1.53.2
- OS Version:
- laptop: asus x550c

Steps to Reproduce:

1.after install git lens the "g" key does not work at vs code anymore and after I uninstall the git lens the key works fine

I recorded a video for this problem : 
http://www.mediafire.com/file/gtvlhov18auu9hg/Desktop-1614517212231+(convert-video-online.com).mp4/file

**Comment by eamodio** [comment]
I don't see how GitLens could cause this -- GitLens doesn't ship with any key binding for just `g`. Do you have any customizations in your `keybindings.json` that could be causing it?

You can also turn off all GitLens key bindings by setting `"gitlens.keymap": "none"` to see if that makes any difference.
