### ISSUE TITLE
Line annotation breaks font ligatures

### ISSUE THREAD

**Issue by batjko** [eamodio/vscode-gitlens#141]
- GitLens Version: 5.0.0
- VSCode Version: 1.16.1
- OS Version: Linux Ubuntu 64bit

Steps to Reproduce:

1.Ensure you have a ligature font enabled in vscode.
2.Click on a line with a ligature symbol and observe the gitlens annotation appear.

Result:
![ligature_issue](https://user-images.githubusercontent.com/7287076/30472072-00e58ae6-99f3-11e7-9da7-14af536c35ca.gif)

Now, I cannot be sure how long this has been the case, I only noticed this issue consciously today.

**Comment by eamodio** [comment]
Sadly this is a vscode issue. Opened https://github.com/Microsoft/vscode/issues/34473
