### ISSUE TITLE
File annotations button flickering

### ISSUE THREAD

**Issue by ATrogolo** [eamodio/vscode-gitlens#1410]
Issue Type: <b>Bug</b>

Hi,
I'm experimenting a bug in the last month with the button "File annotations" in the upper [toolbar](https://postimg.cc/CRtj4tH0)
When I click the button it will open the menu, and, after a couple of milliseconds, it closes itself. 
[Here a video sample](https://www.loom.com/share/90134de0bbb44dc79925b7aa8c438594)

Could you check this and help me to figure it out?

Thanks,
Andrea

Extension version: 11.3.0
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.39GB free)|
|Process Argv|--crash-reporter-id ea1d18af-7e7a-48b2-b8ea-241bce2ef94b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by eamodio** [comment]
I've seen that happen once or twice myself, but can never reproduce it (and haven't seen it in a while). If you can still reproduce, can you open an issue with VS Code (as VS Code controls that behavior). Thanks!

**Comment by ATrogolo** [comment]
Ok, I opened an issue here: https://github.com/microsoft/vscode/issues/118413
