### ISSUE TITLE
The text "You, seconds ago | 1 author (You)" bounces up and down when typing

### ISSUE THREAD

**Issue by kerrickstaley** [eamodio/vscode-gitlens#1414]
- GitLens Version: 6.0.2
- Git Version: `git version 2.24.3 (Apple Git-128)`

- VSCode Version:
    ```
    1.54.0
    42e27fe5cdc58539dad9867970326a297eb8cacf
    x64
    ```
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Add a new chunk of code to a tracked file.
2. Wait for the text "You, seconds ago | 1 author (You)" to appear above the chunk.
3. Begin typing again.

Result:
The text "You, seconds ago | 1 author (You)" bounces up and down with every keystroke. This is very distracting and makes the extension unusable. See video:

https://user-images.githubusercontent.com/184773/110387051-f3ed0f00-8015-11eb-9195-de4a398f36e4.mov 

Search keywords: bounce bounces move moves slide slides jitter

**Comment by eamodio** [comment]
Hrm, I've never seen that, but I've heard that reported before, but it, unfortunately, is a bug in VS Code. Could you please re-file this issue there? Thanks!

Also I would recommend upgrading to a much later GitLens version if you are really on v6.02 😄
