### ISSUE TITLE
Gitlens references merge commit in blame

### ISSUE THREAD

**Issue by lramos15** [eamodio/vscode-gitlens#1415]
- GitLens Version: 11.3.0
- Git Version: git version 2.24.3 (Apple Git-128)

- VSCode Version: 1.55.0-insider 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
- OS Version: macOS Big Sur 11.2.2

Steps to Reproduce:

1. Have a repo with a PR that has merged the default branch into it
2. Git blame will say commits reference that PR instead of the actual commit on the default branch.

Example picture:
<img width="596" alt="Screen Shot 2021-03-08 at 4 48 45 PM" src="https://user-images.githubusercontent.com/4544166/110388659-67e8e080-8031-11eb-90db-8b14aa3113da.png">

References: https://github.com/microsoft/vscode/pull/115790
Actual commit: https://github.com/microsoft/vscode/commit/69c0ce82f8b166fbaf06b2d19900ad6b51cc0c91

**Comment by eamodio** [comment]
The issue here is the "choice" of which remote gets used to find the matching PR. Now GitLens will first always choose the default remote (if set), otherwise it will prioritize the upstream remote of the current branch, and then a remote named "upstream", and finally "origin".

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by lramos15** [comment]
Seems like it's working now on insiders
