### ISSUE TITLE
Feature request: colored file names in the tree view for the new/changed files

### ISSUE THREAD

**Issue by vvs** [eamodio/vscode-gitlens#142]
As you may be aware, VS Code doesn't provide this functionality for some reason, even though this is one of the most requested features (well, it is *THE* most requested feature at the moment). See a very funny issue discussion here: Microsoft/vscode#178

Maybe Gitlens is to the rescue? 🙏

**Comment by eamodio** [comment]
@vvs Unfortunately vscode doesn't provide any extension api support to make this possible -- currently I don't even have color control over the items in the GitLens custom view.

Until that changes there is nothing GitLens (or any extension) could do. :(
