### ISSUE TITLE
Create tag with message fails

### ISSUE THREAD

**Issue by nplatis** [eamodio/vscode-gitlens#1423]
- GitLens Version: v11.3.0
- Git Version: 2.30.2

- VSCode Version: 1.54.2
- OS Version: Arch Linux x64

Steps to Reproduce:

1. Try to create a new tag
2. Follow all the steps and add a message
3. The command fails, with error message (at the command line): "fatal: too many params".

This seems like a small oversight: the output shown at the command line is something like `git tag "message" tag_name main`, whereas the correct command should be `git tag -m "message" tag_name main`.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by nplatis** [comment]
I found it works correctly with insiders version 2021.4.705.
Thanks!

**Comment by diablodale** [comment]
Hi, the fix in v11.4.1 and the PR now causes failures tagging on my computer. The tag command now has two `-m` parameters.

### Setup

Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
GitLens v11.4.1

### Repro

1. in commits pane, click on a commit
2. right click and choose create tag
3. enter tagname
4. enter comment
5. press enter to confirm create tag

### Result

```
Microsoft Windows [Version 10.0.19042.928]
(c) Microsoft Corporation. All rights reserved.
C:\mydir>cd "c:/mydir"
C:\mydir>git tag -m -m "update alpha" v1.3.20210428 763276327623762376327632763276
fatal: too many arguments
```

**Comment by diablodale** [comment]
Hi @eamodio. Should I open a new bug or do you want to re-open this bug as the fix was incomplete?

**Comment by eamodio** [comment]
See #1512
