### ISSUE TITLE
Missing GITlens commands, explore view with Insiders 9-13-17 x64

### ISSUE THREAD

**Issue by cleidigh** [eamodio/vscode-gitlens#143]
GitLens 5
Insiders 9-13 x64
Windows 7

@eamodio 
Cannot see many commands such as stash,compare or toggle explorers view.
Also did not see extension output channel.  Is this an issue with x64?
or is there some configuration I'm missing? Commands were usable before.
could not find anything in the documentation to imply problems with above.

**Comment by eamodio** [comment]
@cleidigh Hrm, I'm on Windows 10 with the latest insiders x64 and don't see any issues. Do you see any errors in the devtools console? Or can you try setting  `"gitlens.outputLevel": "verbose"` and see if you see anything in the output channel?

**Comment by cleidigh** [comment]
@eamodio 
I actually already tried to get debug output with verbose.
there is not a GITlens output channel to look at either
just looked at dev tools didn't think of that .. 
there is an error there
![image](https://user-images.githubusercontent.com/25272315/30505116-c74d8588-9a40-11e7-8881-4bccc638bd9e.png)

**Comment by eamodio** [comment]
@cleidigh is that with the marketplace version of GitLens? I'm really confused as to how that could be missing. Can you try uninstalling and re-installing GitLens to see if it helps?

**Comment by cleidigh** [comment]
@eamodio 
yes it's version five from marketplace
just tried to uninstall could not do it prompts me for okay but does nothing
I will try to brute force

**Comment by cleidigh** [comment]
@eamodio 
deleted extension in user data
reinstalled that seem to do it.
I had extensions on auto update something must've happened during the update

**Comment by cleidigh** [comment]
very happy to have my FULL stash commands !

**Comment by eamodio** [comment]
Looks like this is resolved -- closing the issue
