### ISSUE TITLE
Unhandled Timeout Promise

### ISSUE THREAD

**Issue by Jason3S** [eamodio/vscode-gitlens#1432]
- GitLens Version: v11.3.0
- Git Version: 2.26.0

VS Code:
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

GitLens has an unhandled rejected promise due to a timeout.
This is only an issue while debugging another VS Code extension.

![image](https://user-images.githubusercontent.com/3740137/111491574-42985880-873c-11eb-99ef-979aead9e70b.png)

Steps to Reproduce:

1. Clone a large repository (like VS Code https://github.com/microsoft/vscode-extension-samples.git).
1. cd to one of the examples: `lsp-multi-server-sample`
1. build and launch (open another workspace, like `vscode-gitlens`).
1. make changes to a file. (generally the error starts happen once a file is changed.). 

Callstack:

![image](https://user-images.githubusercontent.com/3740137/111494058-6fe60600-873e-11eb-86c6-711493d7d852.png)

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in the GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by Jason3S** [comment]
Thank you. I'll take a look.

**Comment by Jason3S** [comment]
@eamodio,

Thank you for looking into this issue. I have installed the insiders edition and uninstalled the "standard" edition.

The error is still happening. It happens quite frequently while debugging an extension that is in a git repository.

```
Exception has occurred: Error: Timed out after 250 ms
  at Timeout.<anonymous> (/Users/jason/.vscode/extensions/eamodio.gitlens-insiders-2021.6.2201/dist/webpack:/gitlens-insiders/src/system/decorators/timeout.ts:51:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

This is the line that seems to be throwing the error: [vscode-gitlens/timeout.ts#L51](https://github.com/eamodio/vscode-gitlens/blob/2b8a300703103b12ab90b17e1ad0a2d6c9ece1e6/src/system/decorators/timeout.ts#L51)

![image](https://user-images.githubusercontent.com/3740137/123509942-da310f80-d678-11eb-9e0b-f1c1ad6bd688.png)

**Comment by Jason3S** [comment]
@eamodio,

Any update on this?

The important thing seem to be that the file being edited (in the running debug session) is in a git repository.

**Comment by Jason3S** [comment]
Thank you.
