### ISSUE TITLE
Add 'Open All Files' button for a given commit.

### ISSUE THREAD

**Issue by jaredasutton** [eamodio/vscode-gitlens#1436]
At times, the user may want to open all files for a given commit.
![Screen Shot 2021-03-19 at 1 21 30 PM](https://user-images.githubusercontent.com/15662114/111819751-1a813480-88b7-11eb-96cd-d46f7a73de5e.png)

**Comment by eamodio** [comment]
While there isn't a quick button for it, you can get to it via the commits context menu (e.g. right-click)

![image](https://user-images.githubusercontent.com/641685/112793635-9c016100-9033-11eb-80e7-cfe627364fbd.png)
