### ISSUE TITLE
Messages in hovers wrong encoding using non UTF-8

### ISSUE THREAD

**Issue by hkcomori** [eamodio/vscode-gitlens#1438]
Messages in hovers wrong encoding using non UTF-8

I suggest extension setting according to this:

- "gitlens.hovers.CommitsEncoding": for commit messages in hovers
- "gitlens.hovers.filesEncoding": for changes diff in hovers

Another idea, instead of "gitlens.hovers.filesEncoding", it would be better if it is automatically set according to "files.encoding".

The minimum scope for these settings should be files.associations.

My projects has Shift-JIS encoded files and UTF-8 encoded commit massages.
Then, GitLens Hovers Changes Diff wrong file encoding.

My Environments:

- VSCode Version 1.54.3
- GitLens Version 11.3.0
- Windows 10 Pro x64 Version 1909

Steps to Reproduce:

1. Setup user settings according to this:
```json
{
    "files.encoding": "shiftjis"
}
```

2. Initialize a git repository
3. Create a file which is encoded by Shift-JIS
4. Commit the file with commit message which is encoded by UTF-8
5. Open the file by VSCode
6. Mouse hover annotations
7. I saw commit message with right encoding and diffs with wrong encoding

**Comment by eamodio** [comment]
@hkcomori Are only the hovers wrong? Do the commits show up properly in the Commits view?

**Comment by hkcomori** [comment]
The Commits view has right encoding.
The hover has the diff of code (written in Shift-JIS), so it was displayed with the wrong encoding.

In my project, commit messages are UTF-8.
But if the commit message is not UTF-8, it may be encoded incorrectly.
My guess is that this will be the same for hover, commit view, and annotations.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by hkcomori** [comment]
I have verified that the problem has been fixed in the insiders edition.
My environment is following:

- Windows 10 Pro x64 Version 1909
- VSCode Version 1.55.0
- GitLens (Insiders) v2021.4.605

Thanks for the fix!

**Comment by eamodio** [comment]
Awesome -- thank you!
