### ISSUE TITLE
Copying a remote file URL for a file on Azure DevOps does not work

### ISSUE THREAD

**Issue by MeltingMosaic** [eamodio/vscode-gitlens#1439]
- GitLens Version: 11.3.0
- Git Version: 2.28.0.vfs.0.0
- VSCode Version: 1.54.3
- OS Version: Windows 10

Steps to Reproduce:

1. Clone a repo from Azure DevOps
2. Choose a file and highlight some text
3. Do right-click -> Copy As -> Copy Remote File Url
4. Paste the result in a browser tab
5. Observe that it does not take you to the file you requested, but instead to the commit view

Expected:
The file to be opened with the selected text highlighted

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by MeltingMosaic** [comment]
I tested it out on the insiders build and it works!
