### ISSUE TITLE
Allow to disable custom explorer view on startup

### ISSUE THREAD

**Issue by spywhere** [eamodio/vscode-gitlens#144]
- GitLens Version: 5.1.0
- VSCode Version: 1.16.1 (1.16.1)
- OS Version: macOS Sierra 10.12.6 (16G29)

Every time a new project is opened, GitLens will create a custom explorer view. VSCode allow users to hide custom explorer views out of the box. However, doing this hiding stuffs on multiple projects is quite tedious. By allowing GitLens users to disable custom explorer view at all help reduce these kind of task a lot.

I don't see if VSCode already provide an option to disable any custom explorer view by default. So that's why I open this issue.

**Comment by eamodio** [comment]
@spywhere are you looking to just turn off the custom view completely?

**Comment by spywhere** [comment]
Yup, exactly.

**Comment by eamodio** [comment]
So let's say I add a new setting `gitlens.gitExplorer.enabled` that you could set to turn off the custom view completely -- is that acceptable? You wouldn't be able to have the view show up unless you change that setting.

**Comment by spywhere** [comment]
Yes, that's exactly what I need.

**Comment by eamodio** [comment]
@spywhere the latest [GitLens v5 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v5.1.1-beta) adds a new `gitlens.gitExplorer.enabled` setting.

Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know if you experience any issues -- thanks!

**Comment by spywhere** [comment]
@eamodio Thanks. That's work like a charm!

**Comment by spywhere** [comment]
Mark as a reference for VSCode's default behaviour: https://github.com/Microsoft/vscode/issues/34557
