### ISSUE TITLE
Unable to install extension 'eamodio.gitlens' as it is not compatible with the current VS Code engine version '1.51.0'

### ISSUE THREAD

**Issue by ryan25r9** [eamodio/vscode-gitlens#1441]
"Unable to install extension 'eamodio.gitlens' as it is not compatible with the current VS Code engine version '1.51.0'"

- GitLens Version: I've tried all versions, same error
- Git Version: 2.20.1.windows.1

- VSCode Version: Azure Data Studio 1.51.0
- OS Version: Windows 10 20H2 19042.867

Steps to Reproduce:

1. download vsix file
2. Try to load extension into Azure Data Studio

**Comment by eamodio** [comment]
Unfortunately Azure Data Studio is quite a few releases behind VS Code, and GitLens uses apis not available in older versions. Once ADS catches up then GitLens will work. Sorry.
