### ISSUE TITLE
Interactive Rebase Editor not opened but plain text file when called from terminal

### ISSUE THREAD

**Issue by universam1** [eamodio/vscode-gitlens#1442]
Calling "Rebase current branch onto Commit" as "interactive" opens the "Interactive Rebase Editor" just fine. The command executed under the hood in the terminal is `git -c sequence.editor="code --wait --reuse-window" rebase --interactive e2db9b3b250adc217665d30640c16f2fdfe774c8`
However, pasting the same command in the terminal again does not open that editor, it just opens VSCode as a plain text file!

The same problem applies when running `git rebase -i` from terminal, just a plain text file is opened in VSCode, no Interactive Editor.

- GitLens Version: 11.3.0
- Git Version: Run `git --version` 2.25.1

- VSCode Version: Run `code --version` 1.54.3
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. set up git to use VScode as editor
```
[core]
	editor = code --wait
```
2. run `git rebase -i ...` 
3. vscode opens git-rebase-todo as plain text file

Errors seen:
```
[2021-03-24 09:02:22:953] [/home/..../.git/rebase-merge] git rev-parse --show-toplevel • FAILED 8 ms 

Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel
fatal: this operation must be run in a work tree
```

**Comment by eamodio** [comment]
Is this under WSL or are you on Ubuntu natively?

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by universam1** [comment]
> Is this under WSL or are you on Ubuntu natively?

native Ubuntu
