### ISSUE TITLE
File history view "Open Changes with Working File" does not work for the very first commit

### ISSUE THREAD

**Issue by drquake** [eamodio/vscode-gitlens#1444]
- GitLens Version: v11.3.0
- Git Version: 2.7.4
- VSCode Version: Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. In FILE HISTORY view, scroll to the very first commit at bottom and click "Open Changes with Working File" button. Nothing shows up.
2. "Open Changes with Working File" works for all commits in the FILE HISTORY list except the very first one at bottom.
The issue happens since gitlens version 11.
3. I believe it worked correctly in 10 or earlier versions.

GitLens log:
[2021-03-25 02:17:29:140] [20e] ViewCommands.openChangesWithWorking — t=FileRevisionAsCommitNode:&lt;commit&gt;:&lt;filename&gt;, undefined
[2021-03-25 02:17:29:141] [20e] ViewCommands.openChangesWithWorking completed • 0 ms

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by drquake** [comment]
Sorry for replying late.

Yes insider edition fixed the issue. Great job.

Regards
