### ISSUE TITLE
Improve documentation for hiding default added editor actions

### ISSUE THREAD

**Issue by shaman-apprentice** [eamodio/vscode-gitlens#1445]
UI space / icons to show in the editor action toolbar are opinionated (see https://github.com/microsoft/vscode/issues/46403 or https://github.com/eamodio/vscode-gitlens/issues/1211). Therefore, as a user, I want to know how to hide them. 

**Actual behavior:** As stated [here](https://github.com/eamodio/vscode-gitlens/issues/669#issuecomment-467531508) the feature is currently not really documented.

**Possible solution:** Add the following content at the bottom of "Revision Navigation #"-section in [README.md](https://github.com/eamodio/vscode-gitlens#revision-navigation-). 

> The default added icons to the editor action toolbar can be hidden as described [here](https://github.com/eamodio/vscode-gitlens/issues/669#issuecomment-467531508).

P.S.: It seems I wasn't the only one missing this section - https://github.com/eamodio/vscode-gitlens/discussions/1433)

**Comment by shaman-apprentice** [comment]
As a side note: What do you think about adding an issue type "Documentation? "Bug report", "Feature request" nor "Question" felt really right to me for this issue.

**Comment by eamodio** [comment]
@shaman-apprentice I've added a new section about the menu & toolbar customizations to the README -- Let me know what you think.

**Comment by shaman-apprentice** [comment]
Cool. I like it way more, than my minimal addition :+1:  Thx!
