### ISSUE TITLE
Hashes (#) are percent encoded in custom remote urls

### ISSUE THREAD

**Issue by tbaud0n** [eamodio/vscode-gitlens#1448]
- GitLens Version: 11.3.0
- Git Version: 2.17.1
- VSCode Version: 1.54.3
- OS Version: Ubuntu 18.04

Configured remotes urls containings hashtag or percent symbols are entirely escaped when clicking on "Open file on remote". 

Steps to Reproduce:

1.Set a custom URL in `gitlens.remotes.urls` config containing a hashtag or percent (ex: `"fileInCommit": "http://privateRepo.com/projects/repos/${repoPath}/commits/${id}#${file}",`)
2. Click on a "Open file on remote" link using this custom URL.
3. The browser open the required URL but the hashtag is escaped (ex: `http://privateRepo.com/projects/repos/my-repor/commits/e62a0533fed7141beb9edfeed8dfccdd914ebae3%2523src/service/documents/downloader.go`)

**Comment by rdnlsmith** [comment]
This might be the same as #796.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by tbaud0n** [comment]
Thank you @eamodio, it works perfectly!
