### ISSUE TITLE
Configured remotes not showing up in quickpick menu when opening commit on remote

### ISSUE THREAD

**Issue by IvanRadakovic** [eamodio/vscode-gitlens#1449]
I set the output level to debug, but it doesn't output anything.

- GitLens Version: 2021.3.1104
- Git Version: 2.28.0
- VSCode Version: 1.54.3
- OS Version: macOS 11.2.3

Steps to Reproduce:
1. set gitlens.integrations.enabled to true
2. Based on https://github.com/eamodio/vscode-gitlens#remote-provider-integration-settings- add this to settings
"gitlens.remotes": [{
        "domain": "code.company.com",
        "type": "Custom",
        "name": "company",
        "protocol": "https",
        "urls": {
            "repository": "https://code.company.com/packages/${repo}",
            "branches": "https://code.company.com/packages/${repo}/repo-info",
            "branch": "https://code.company.com/packages/${repo}/trees/heads/${branch}",
            "commit": "https://code.company.com/packages/${repo}/commits/${id}",
            "file": "https://code.company.com/packages/${repo}?path=${file}${line}",
            "fileInBranch": "https://code.company.com/packages/${repo}/blobs/${branch}/--/${file}${line}",
            "fileInCommit": "https://code.company.com/packages/${repo}/blobs/${id}/--/${file}${line}",
            "fileLine": "#L${line}",
            "fileRange": "#L${start}-L${end}"
        }
    }],
3. Save
4. Restart VS Code
5. Go to COMMITS tab in source controll. 
6. Click 'Open Commit on Remote' next to a commit

Expected: opens commit on the configured remote.
Actual: 'No auto-detected or configured remote providers found' shows up in quickpick menu as if nothing was ever configured

**Comment by sarthak-k** [comment]
Yup, experiencing this.

**Comment by eamodio** [comment]
Can either of you post what the output of `git remote -vv` returns? Because the `domain` of the custom remote definition has to match the domain of your Git remote.

**Comment by sarthak-k** [comment]
Certainly, it's different. But the purpose with `Custom` remote should enable us to add any domain, I believe we should treat this as a bug.

**Comment by IvanRadakovic** [comment]
So the domain and `git remote -vv` are different, but I was under the impression that this would still allow us to open a webpage in the browser using this template: `https://code.company.com/packages/${repo}/commits/${id}` with the `repo` and `id` fillied in from that corresponding commit.

**Comment by eamodio** [comment]
The `gitlens.remotes` property allows you to configure custom remote "matchers", so GitLens uses those configured custom remotes in addition to its built-in remote support for GitHub, Bitbucket, etc, to match against your repository remotes. If a match is found, then the `urls` configuration is used to open resources. So the `domain` property or the newly added `regex` property must be specified to perform that match.

**Comment by IvanRadakovic** [comment]
Ah I see. That makes sense. I ran into another issue. So `git remote -vv` shows this
```
backup  ssh://git.company.com:2222/pkg/RepoName/backup/username (fetch)
backup  ssh://git.company.com:2222/pkg/RepoName/backup/username (push)
origin  ssh://git.company.com:2222/pkg/RepoName (fetch)
origin  ssh://git.company.com:2222/pkg/RepoName (push)
share   ssh://git.company.com:2222/pkg/RepoName/share/username (fetch)
```
I have changed the `domain` to be `git.company.com`. However now `${repo}` in the URL resolves to `pkg/RepoName`(`https://code.company.com/packages/pkg/RepoName`) instead of just `RepoName` (`https://code.company.com/packages/RepoName`).

**Comment by eamodio** [comment]
So for that you'll need to use the `regex` property instead of `domain` and the first capture group is the domain part and the 2nd capture group is the repo

**Comment by zainfathoni** [comment]
> So for that you'll need to use the `regex` property instead of `domain` and the first capture group is the domain part and the 2nd capture group is the repo

@eamodio Could you please provide an example? I couldn't find it in the `README.md` document. Thanks!

**Comment by IvanRadakovic** [comment]
For this domain
`origin  ssh://git.company.com:2222/pkg/RepoName (fetch)`

I tried
```
"regex": "ssh:\\/\\/(git.company.com):2222\\/pkg\\/(\\w+)"
"regex": "(ssh:\\/\\/git.company.com:2222)\\/pkg\\/(\\w+)"
"regex": "ssh:\/\/(git.company.com):2222\/pkg\/(\\w+)"
"regex": "(ssh:\/\/git.company.com:2222)\/pkg\/(\\w+)"
```
and none of them work. Could you please add documentation in the `README.md` on how use the `regex` property with some examples.

**Comment by objectiveryan** [comment]
I have the original problem (`No auto-detected or configured remote providers found`). I have several equivalent remotes defined (for configuration reasons), and my employer has a custom protocol (`sso`), could either of those cause the problem?

```
$ git remote -vv
origin  sso://our-domain/repo-name (fetch)
origin  sso://our-domain/repo-name (push)
origin-3.2.0-hotfixes   sso://our-domain/repo-name (fetch)
origin-3.2.0-hotfixes   sso://our-domain/repo-name (push)
origin-v3.0.0   sso://our-domain/repo-name (fetch)
origin-v3.0.0   sso://our-domain/repo-name (push)
...
```

settings.json:
```
    "gitlens.integrations.enabled": true,
    "gitlens.remotes": [{
        "domain": "our-domain",
        "type": "Custom",
        "name": "Company Name",
        "protocol": "sso",
        "urls": {
            "repository": "...",
            "branches": "...",
            "branch": "...",
            "commit": "...",
            "file": "...",
            "fileInBranch": "...",
            "fileInCommit": "...",
            "fileLine": "...",
            "fileRange": "..."
        }
    }]
```

**Comment by objectiveryan** [comment]
Is there some more information I can provide? I don't want this issue to be closed – it still affects me.

**Comment by priteshacharya** [comment]
This also affects me, It used to work before but doesn't anymore, what information do you need?

**Comment by objectiveryan** [comment]
FYI I tried removing my other remotes, so there's only one:
```
$ git remote -vv
origin  sso://our-domain/repo-name (fetch)
origin  sso://our-domain/repo-name (push)
$
```
I've tried setting `gitlens.integrations.enabled` and `gitlens.remotes` in my user settings and/or workspace settings (first one, then both, then only the other). I quit and restart VSCode. I still get "No auto-detected or configured remote providers found" :-(

Also, I typically ssh into a remote server to work (through VSCode's Remote - SSH extension), but I tried working out of a local folder and had the same problem.

**Comment by lodotek** [comment]
Bump. Having the same issue here trying to use Bitbucket with GitLens. :-(

**Comment by eamodio** [comment]
Sorry for the delay and confusion around this issue. I think I've gotten to the bottom of it, and I added 2 new examples in the [README](https://github.com/eamodio/vscode-gitlens/tree/main#remote-provider-integration-settings-) that use the `regex` property.

Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by IvanRadakovic** [comment]
Hey thank you so much for the fix!

It works for me. However, I got an `Invalid escape character in string`  error when using what you had in the README example.

`"ssh:\/\/(my\.company\.com):1234\/git\/(.+)"`

This is because `\.` is not a valid escape character in JSON. This caused me to dig deeper into what is actually required.
To make it work, you could remove replace `\.` with just `.` like so

`"ssh:\/\/(my.company.com):1234\/git\/(.+)"`

which works, but it could match other incorrect strings as well.
A better fix would be to properly escape the `\` by replacing `\.` with `\\.` like so

`"ssh:\/\/(my\\.company\\.com):1234\/git\/(.+)"`

I also found out that in JSON, you can, but are not required to escape `/`. `\/` is just as valid as `/`. Allowing `\/` helps when embedding JSON in a `<script>` tag, which doesn't allow `</` inside strings. So this means that the example in the README could be simplified to only escape the `.` with two `\` and leaving everything else alone.
`"ssh://(my\\.company\\.com):1234/git/(.+)"`

**Comment by eamodio** [comment]
Thanks, I've fixed the example.

**Comment by blindside85** [comment]
Hi @eamodio , I'm having issues in a similar vein to the above users, and I think the `regex` option might be the key, but I can't seem to find any docs explaining how it works, only some examples silently using it.

A few questions I think might be handy to explain about the `regex` option:
1. What exactly does it do / allow in the remotes configuration?
2. What are the capture groups for? For example: `(my\\.company\\.com)` and `(.+)`
3. Is the option specific to ssh-related URLs, or would http/https URLs also work?

If there are already docs explaining all this, if someone could link to those I'd appreciate it, I wasn't able to find them 😞
