### ISSUE TITLE
Issues when pulling

### ISSUE THREAD

**Issue by juancarloslopezmck** [eamodio/vscode-gitlens#1452]
Issue Type: <b>Bug</b>

I have to restart VS almost every time when I have to pull/commit a change and this was not happening before.

Extension version: 11.3.0
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.33GB free)|
|Process Argv|--crash-reporter-id f3c5e7d5-3ae3-4b97-9543-17642ad3302e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by eamodio** [comment]
Sorry, but I'll need more information before I can help you. How are you pulling (maybe show a recording)? Why do you have to restart?
