### ISSUE TITLE
Extension not working in Azure Data Studio

### ISSUE THREAD

**Issue by ryan25r9** [eamodio/vscode-gitlens#1453]
- GitLens Version: I tried all versions
- Git Version: Run `git --version`

- VSCode Version: 1.51.0
- Azure Data Studio: 1.27.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Try to install vsix file in Azure Data Studio, either by dragging the file into the Extensions sidebar tab or clicking "Install from VSIX".
2. Returns this error: "Unable to install extension 'eamodio.gitlens' as it is not compatible with the current VS Code engine version '1.51.0'."

**Comment by eamodio** [comment]
Unfortunately Azure Data Studio isn't yet compatible with the version of the VS Code apis that GitLens needs.
