### ISSUE TITLE
"Copy Remote File Url" not showing line ranges

### ISSUE THREAD

**Issue by shermam** [eamodio/vscode-gitlens#1458]
Issue Type: <b>Bug</b>

- Selecte some line or lines of code in a source file tracked by git
- Press `cmd + shift + c` or select the command `GitLens: Copy Remote File Url`

### Expected

Remote Url in the clipboard contains line numbers at the end.

### Actual

Remote Url does not contain line numbers at the end.

### Notes:

I was able to track this change [here](https://github.com/eamodio/vscode-gitlens/pull/1344/files#diff-43b15f79a2abbfd67a7765a7a4c2554fecdd81a88b8caafa46cd3d1841f525b0R92-R93) on the file `src/commands/openFileOnRemote.ts` lines 92 and 93 that were introduced on PR #1344 merged a couple of weeks ago that seems to have introduced the problem.

I was able to dig through the minified version of the extension in my `~/.vscode/extensions/eamodio.gitlens-11.4.0` directory, and revert those two lines and I can confirm that it solved the problem locally for me.

I did not take the time to investigate what the original intent of that extra condition to be added was. So I don't feel comfortable writing a PR just yet. But I would love to see this functionality back since I use it everyday.

This is an awesome extension! Thanks for the awesome work!

Extension version: 11.4.0
VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 955b19b8-7ffb-4a08-aa1f-1020d89685a2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by eamodio** [comment]
Thank you for the debugging ❤️.  Sorry for the inconvenience, I will get that fixed up very soon!

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by shermam** [comment]
> Can you please verify this fix in tomorrow's insiders edition?
> 
> You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

Yes @eamodio . Wow that was really fast! Thanks for the quick response. I will definitely verify this tomorrow and I will let you know.

**Comment by shermam** [comment]
I uninstalled the stable version and installed the insiders edition v2021.4.1405. And I confirm that the line ranges are back! 🎉
Thanks very much for the quick response.
