### ISSUE TITLE
Blame gutter annotation issue when commit contains emoji

### ISSUE THREAD

**Issue by eMerzh** [eamodio/vscode-gitlens#146]
Hi, 
Thanks for your work on this extension! really great ...
it seems that i encounter a small bug (i first thought it was normal :p )
with the "File annotation" feature with commit that contains emojis
it's probably a char count issue or smth like that 

- GitLens Version: 5.1.0
- VSCode Version: 1.16.1
- OS Version: OSX

Steps to Reproduce:
Have commit with and without emojis  like here 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/177003/30532067-78aed0e4-9c52-11e7-91e7-c964440f7f34.png">

**Comment by fgallardograzio** [comment]
I can also reproduce this same issue with a seemingly plain old text-only commit message. Here's a screenshot:

![screenshot-gitlens-vscode](https://user-images.githubusercontent.com/10978027/30623571-ba584c2c-9d8e-11e7-9d15-f6d92a7a0652.png)

[This is the commit](https://github.com/Microsoft/TypeScript-Node-Starter/commit/76c4593f2b3ab55050f114bd41b4a19b87649989) that is causing the issue. The file in the screenshot is `src/controllers/user.ts`. [This is the blamed file on GitHub](https://github.com/Microsoft/TypeScript-Node-Starter/blame/ed149eb0c787b1195a95b44105822c64bb6eb636/src/controllers/user.ts).

Awesome extension, btw!

-----

* GitLens Version: 5.1.0
* VSCode Version: 1.16.1
* OS Version: Linux Mint 18

**Comment by eamodio** [comment]
@eMerzh @fgallardograzio the latest [GitLens v5 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v5.2.0-beta) should fix this as best I can -- the heatmap edge should no longer break, but the right-aligned text could be a little jagged although much better than before.

Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know if you experience any issues -- thanks!

**Comment by fgallardograzio** [comment]
There's an issue with consecutive whitespace characters (spaces, tabs, etc) in the gutter annotation.

This happens whether the spaces are in the gutter annotation format, e.g:
"gitlens.annotations.file.gutter.format": "${author|10}       ${message|30?} ${ago|14-}"

or if they're from the commit message itself, e.g:

> git commit -m "Message with &nbsp;&nbsp; spaces &nbsp;&nbsp; !"

(I've added `&nbsp;`s here so that github's markdown would not get in the way, but in the actual commit message they were just regular spaces).

This is what it looks like using the format string from the first example:

![image](https://user-images.githubusercontent.com/10978027/30629009-ef52447a-9daf-11e7-9c14-9b673b48616c.png)

**Comment by eamodio** [comment]
@fgallardograzio is that with the latest beta?

**Comment by fgallardograzio** [comment]
@eamodio Just installed v5.2.0-beta. Heatmap is perfectly straight! Right aligned text in line 5 (which was broken before) is pushed a few pixels to the left as you predicted.

However this behaviour is accentuated in my "commit message with spaces" example.
In the screenshot below you can see the commit command in the console, and the result in the blame annotation.

![image](https://user-images.githubusercontent.com/10978027/30629465-5ce393a2-9db2-11e7-96a4-9925d9ef3d9b.png)

Additional consecutive spaces in the format string (`gitlens.annotations.file.gutter.format`) are collapsed. No matter how many spaces there are, they're rendered like one, and nothing is misaligned.

**Comment by eamodio** [comment]
Great -- thank you! I'll dig into the space collapsing issue.

**Comment by eMerzh** [comment]
Looks perfect now :)

Thanks for the update
