### ISSUE TITLE
Commit message body line length wrapping in panel

### ISSUE THREAD

**Issue by bbennetts** [eamodio/vscode-gitlens#1460]
The multi line commit message field in the source control panel is great - really useful, and really handy it warns when the title/body exceeds the line length.  It would be nice however if for the commit body it could start a new line when the line length is hit it would save much hitting of the enter key.

**Comment by eamodio** [comment]
That feature is not provided by GitLens, that is provided by VS Code itself. Please open an issue with the VS Code repository. Thanks!
