### ISSUE TITLE
Feature request: Compare Ancestry with Working Tree - should use origin/master

### ISSUE THREAD

**Issue by Mellbourn** [eamodio/vscode-gitlens#1462]
- GitLens Version: 11.4.0
- Git Version: 2.31.1

- VSCode Version: 1.55.1
- OS Version: macOS Big Sur 11.2.3

Steps to Reproduce:

1. Switch to a branch other than master
2. Right-click master and choose `Compare Ancestry with Working Tree`
3. Shows a comparison, BUT this is the _same_ comparison as `Compare with HEAD`

I expected the diff to be more on the lines of the result from `git diff origin/master...`

The reason seems to be that `master` was not refreshed to match `origin/master`.
I think that the it would make more sense to compare with `origin/master` by default, or have a separate command that does that.

**Comment by eamodio** [comment]
To get the behavior you want, you could select `origin/master` in the _Remotes_ view. Given that, I'm not sure this behavior change makes sense.

**Comment by Mellbourn** [comment]
Ah, excellent! I did not think of that alternative. That works the way I desire.
