### ISSUE TITLE
Action before Commit Message submitted caused lost of an entire commit source files.

### ISSUE THREAD

**Issue by chogland** [eamodio/vscode-gitlens#1464]
While using the GitLens within Visual Studio Code, the code changes were being committed. Using the GUI, I entered a message in the window that popped up for the commit message. During that dialog I selected an uwanted SVG and clicked discard. Doing this discarded my entire commit with no way to retrieve it.

**Comment by eamodio** [comment]
GitLens doesn't provide commit features -- they are provided by VS Code itself. So please open an issue there, especially if you can reproduce that issue.
