### ISSUE TITLE
Cannot open file on remote

### ISSUE THREAD

**Issue by YanzhongSu** [eamodio/vscode-gitlens#1468]
- GitLens Version: v11.4.1
- Git Version: 2.26.0

- VSCode Version: 1.55.2
- OS Version: Linux
I used to be able to right click a file and click `Open File On Remote`. It would take me to the file on the remote repo. But the newer version now askes me to set remote providers.
![image](https://user-images.githubusercontent.com/22637390/115029563-03d1fb80-9ebe-11eb-8d73-a4f4395653d5.png)
I have the following in my settings.json file. It does not help.
```
"gitlens.remotes": [{
    "name": "My Company",
    "protocol": "https",
    "domain": "bitbucket.mycompany.com",
    "type": "Bitbucket",
    "urls": {
      "repository": "https://bitbucket.mycompany.com/projects/${repoBase}/repos/${repoPath}",
      "branches": "https://bitbucket.mycompany.com/projects/${repoBase}/repos/${repoPath}/branches",
      "branch": "https://bitbucket.mycompany.com/projects/${repoBase}/repos/${repoPath}/commits/${branch}",
      "commit": "https://bitbucket.mycompany.com/projects/${repoBase}/repos/${repoPath}/commit/${id}",
      "file": "https://bitbucket.mycompany.com/projects/${repoBase}/repos/${repoPath}?path=${file}${line}",
      "fileInBranch": "https://bitbucket.mycompany.com/projects/${repoBase}/repos/${repoPath}/blob/${branch}/${file}${line}",
      "fileInCommit": "https://bitbucket.mycompany.com/projects/${repoBase}/repos/${repoPath}/blob/${id}/${file}${line}",
      "fileLine": "#L${line}",
      "fileRange": "#L${start}-L${end}"
      }
    }]
```
My question is why previous version did not ask me to config remote provider but the newer version does? What did I do wrong with above config? I use bitbucket. The domain name is `bitbucket.mycompany.com`. All the repos is there.

**Comment by eamodio** [comment]
What is the remote url in your `.git/config` file? Maybe there is an issue with GitLens matching that.

**Comment by YanzhongSu** [comment]
> What is the remote url in your `.git/config` file? Maybe there is an issue with GitLens matching that.

This is what I have in `.git/config` file. I do not recall I ever changed this file. I think the issue might lie in the newer version of GitLens given that the previous version worked for me.
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = ssh://git@bitbucket:4500/trial/test_project.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

**Comment by sirianni** [comment]
I'm having the same problem.  With the recent update I no longer see an `Open File on Remote` option
![image](https://user-images.githubusercontent.com/381302/115274638-e647a080-a10e-11eb-9a42-1401cd01257a.png)

**Comment by YanzhongSu** [comment]
> > What is the remote url in your `.git/config` file? Maybe there is an issue with GitLens matching that.
> 
> This is what I have in `.git/config` file. I do not recall I ever changed this file. I think the issue might lie in the newer version of GitLens given that the previous version worked for me.
> 
> ```
> [core]
>         repositoryformatversion = 0
>         filemode = true
>         bare = false
>         logallrefupdates = true
> [remote "origin"]
>         url = ssh://git@bitbucket:4500/trial/test_project.git
>         fetch = +refs/heads/*:refs/remotes/origin/*
> [branch "master"]
>         remote = origin
>         merge = refs/heads/master
> ```

@eamodio Based on above, do you have any idea as to what has changed? I have never edited my `.git/config` file

**Comment by sirianni** [comment]
It started working for me again.  I'm not sure of the root cause but I think it had something to do with my working directory being on an orphaned branch perhaps?

**Comment by YanzhongSu** [comment]
> It started working for me again. I'm not sure of the root cause but I think it had something to do with my working directory being on an orphaned branch perhaps?

@sirianni Can you share what you have inside `.git/config`? Wonder what the issue is in my case.
