### ISSUE TITLE
Add additional domains to gitlens.remotes

### ISSUE THREAD

**Issue by wesbaker** [eamodio/vscode-gitlens#148]
- GitLens Version: 5.1.0
- VSCode Version: 1.1.6.0
- OS Version: macOS 10.12.6

Right now, [from what I can tell](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens#user-content-custom-remotes-settings), you can only setup custom domains for GitHub, GitLab, and BitBucket. Is there any chance we could use an arbitrary URL for commits?

**Comment by eamodio** [comment]
@wesbaker Can you provide an example or use case?

**Comment by wesbaker** [comment]
Sure, my company uses a self-hosted Git repository called GitBlit which is a Gerrit plugin. URLs end up looking like this `company.com/plugins/gitblit/commit/?r=repository.git&h={hash}`. I'd like to be able to click on commit SHAs from VSCode and be able to go to that link.

**Comment by eamodio** [comment]
Ah, gotcha. I'll look into adding support for a `Custom` provider.

**Comment by wesbaker** [comment]
This is perfect, thanks for your work on it!

**Comment by eamodio** [comment]
@wesbaker awesome -- let me know if you run into any challenges/issues
