### ISSUE TITLE
cd /d

### ISSUE THREAD

**Issue by irvnriir** [eamodio/vscode-gitlens#1480]
`Sidebar \ Repositories \ Branches \ RMB \ Create Branch \ ..` [=1] results into 
```
cd "<<path>>"
git branch <<..>>
```
cmd script . This needs to be:
```
cd /d "<<path>>"
git branch <<..>>
```

May be other places where `cd` is needed and is the wrong one .

How does everyone keep missing this in different projects .

Also, the [1] and such Delete Branch, Switch To Branch and i guess other actions doesn't call the list Refresh, so its needed to do manually . (`gitlens.views.repositories.autoRefresh` is On)

**Comment by eamodio** [comment]
Will be resolved when https://github.com/eamodio/vscode-gitlens/issues/1450 is fixed.
