### ISSUE TITLE
Display lines added and subtracted by each contributor

### ISSUE THREAD

**Issue by KShivendu** [eamodio/vscode-gitlens#1489]
Hi there
Github shows lines added or subtracted as well as some graphs representing contributor activity. But unfortunately, this feature isn't available for private organization repositories. And I think Gitlens can fill this gap. 

There are commands like `git log --author="<Author_Name>" --pretty=tformat: --numstat` which can easily calculate lines added and subtracted by each contributor. We may just add this information in the tooltip when hovered over a contributor. What's your opinion? Please comment. 

Cheers!

**Comment by eamodio** [comment]
I've added a _Show Statistics_ / _Hide Statistics_ toggle on the `...` menu of the _Contributors_ view, which controls a new `gitlens.views.contributors.showStatistics` setting. FYI, depending on the repository size, this can take a while.

Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
