### ISSUE TITLE
Word wrapping issue when viewing blame annotations

### ISSUE THREAD

**Issue by fgallardograzio** [eamodio/vscode-gitlens#149]
Word wrapping breaks the blame layout. Please see the attached screenshot.

I think the appropriate behaviour would be to wrap the lines on the right hand side of the "blame panel", after the heatmap.

If this is technically problematic to do, then I'd rather have word wrapping automatically disabled when blaming a file.

![image](https://user-images.githubusercontent.com/10978027/30624170-2bba6712-9d92-11e7-80d5-ea463ccaf642.png)

Thanks!

----

- GitLens Version: 5.1.0
- VSCode Version: 1.16.1
- OS Version: Linux Mint 18

**Comment by eamodio** [comment]
@fgallardograzio While I would **love** to fix this, unfortunately the only way I can provide the blame annotations (via the vscode api) doesn't allow for something like this. Hopefully vscode will ultimately provide a true *gutter* api and the crazy hacks that GitLens has to do could be a thing of the past :)

**Comment by fgallardograzio** [comment]
@eamodio what about having the extension disable word wrapping automatically when blaming a file?

**Comment by eamodio** [comment]
Good idea, but I've gone down that path with toggling on/off visible whitespace (used to be required to the annotations to render properly) and it was fraught with issues and caused a noticeable delay in triggering the annotations. Sorry.
