### ISSUE TITLE
"Restore" command should be named "Checkout"

### ISSUE THREAD

**Issue by RikkiGibson** [eamodio/vscode-gitlens#1493]
- GitLens Version: 11.4.1
- Git Version: 2.30.0.windows.2
- VSCode Version: 
```
1.56.0
cfa2e218100323074ac1948c885448fdf4de2a7f
x64
```
- OS Version: Windows 10 19042.928

The "commits" tree view has a "Restore" command that basically does a `git checkout` of that version of the file into the index. I think it would be a lot more intuitive for git users if this were called "Checkout", as it seems to be the same as the `git checkout ref -- file` command we use on the CLI.

![restore-command](https://user-images.githubusercontent.com/5833655/117379663-c9d89180-ae8c-11eb-9c2e-d70f7b3e50d5.png)

**Comment by eamodio** [comment]
I changed it to be _Restore (Checkout)_ as that should make it clearer -- and aligns with the more recent `git restore` command (as checkout has been split into `restore` and `switch`)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
