### ISSUE TITLE
usage issue about "SOURCE CONTROL REPOSITORIES"

### ISSUE THREAD

**Issue by chandq** [eamodio/vscode-gitlens#1501]
Hi, i have found a problem when use gitLens，it is that i can not see all changed  files in which repository after i closed under "SOURCE CONTROL REPOSITORIES" panel . Although i tried to solved the problem which trouble me with long time, but it failed.
Hope to answer and help to solved the problem, thanks.

**Comment by eamodio** [comment]
Can you please add more detail as to the issue you are experiencing and/or the steps to reproduce it?
