### ISSUE TITLE
Error from Git Lens: cannot use extension any more

### ISSUE THREAD

**Issue by thistlillo** [eamodio/vscode-gitlens#1503]
- GitLens Version: v11.4.1
- Git Version: 2.31.1.windows.1

- VSCode Version: 1.56.1  e713fe9b05fc24facbec8f34fb1017133858842b  x64
- OS Version: Windows 10 Pro 20H2 19042.985

Steps to Reproduce:

1. Install git lens
2. Try to commit some staged changes
3. This error shows up:
```
Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false tag -l --format=%3cn%3e%(refname)%3c*r%3e%(*objectname)%3cr%3e%(objectname)%3cd%3e%(creatordate:iso8601)%3cad%3e%(authordate:iso8601)%3cs%3e%(subject) fatal: bad boolean config value 'null' for 'tag.forcesignannotated'
```

It happened all of a sudden: frankly, I cannot figure out what actions of mine caused the error, but now even if I uninstall/reinstall git lens, quitting/reloading/etc Visual Studio Code, I get his error. It used to work till yesterday.

I looked for the option `tag.forcesignannotated` in settings.json, but could not find anything. My experience with visual studio code is very little, sorry.

I have no problems in running git from the command prompt or using the built-in git commands: they work.

**Comment by eamodio** [comment]
Hrm, that error is talking about your git config -- do you have anything like the following in your git config? (`~/.gitconfig` or in the `.git/config` file in your repo)

```
[tag]
forceSignAnnotated = true
```

Git seems to think you have an invalid value for that setting.
