### ISSUE TITLE
"Open folder history" doesn't work for workspace project folders

### ISSUE THREAD

**Issue by giltayar** [eamodio/vscode-gitlens#1505]
- GitLens Version: 11.4.1
- Git Version:  2.29.2

- VSCode Version: 1.56.2
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Open a workspace file (`*.code-workspace`)
2. Right click on a project folder (top level folder)
3. "Open folder history" doesn't appear there, and it should as this is also a regular folder

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by giltayar** [comment]
@eamodio it works! Thank you SO much.
