### ISSUE TITLE
Avoid ⎇ + Shift + 7 on German keyboard

### ISSUE THREAD

**Issue by BendingBender** [eamodio/vscode-gitlens#151]
- GitLens Version: 5.1.0
- VSCode Version: 1.16.1
- OS Version: OSX 10.12.6

Steps to Reproduce:

1. use shortcut Alt+Shift+7 on German keyboard to enter the backslash char (\\)

When this shortcut is overridden, it's not possible to enter the backslash char on German keyboard (which is used quite frequently in some programming languages).

**Comment by christophberger** [comment]
Apple did a terrible job with the German keyboard layout. I have no idea what they smoked back then when they decided to go completely non-standard with the placement of the curly braces, brackets, the pipe symbol, the backslash, the tilde, and the at sign. Even worse, none of these characters except the at sign are even printed onto the keys. 

I just stumbled over this Alt-Shift-7 issue today when recording a screencast after having installed gitlens yesterday (a great tool btw).

As a temporary workaround, I disabled the shortcut by copying the keybinding over to the user's keybindings file and placing a "-" before the command (which is what the VSCode doc [recommends](https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule) for disabling a shortcut):

```
{ 
		"key": "shift+alt+7",
		"command": "-gitlens.showCommitSearch",
		"when": "gitlens:enabled" 
	},
```

**Comment by chabou** [comment]
This is the same with a french keyboard. To enter a backslash, you need to hit `alt+shift+:` because / is placed on `shift+:`.
But `showCommitSearch` (that have `alt+/`) is triggered.

**Comment by chabou** [comment]
![capture d ecran 2017-10-10 a 08 49 57](https://user-images.githubusercontent.com/4137761/31372884-14e6d06e-ad98-11e7-96ba-f1524c4e6654.png)
As you can see, `showCommitSearch` is exactly what I need to hit to print a backslash.

**Comment by eamodio** [comment]
Let's move this conversation over to https://github.com/eamodio/vscode-gitlens/issues/104 since these are ultimately the same thing
