### ISSUE TITLE
Git tag command can add an extra `-m`

### ISSUE THREAD

**Issue by ahmad-ali14** [eamodio/vscode-gitlens#1512]
- GitLens Version: v11.4.1
- Git Version:  git version 2.29.2.windows.2
- VSCode Version: 1.56.2
                              054a9295330880ed74ceaedda236253b4f39a335
                              x64
- OS Version: windows 10

Steps to Reproduce:

1. try to create a new tag from the UI

  ![](https://i.imgur.com/wVKrI8r.png)

2. will add extra `-m` to the executed command

  ![](https://i.imgur.com/ua6PIAL.png)

**Comment by diablodale** [comment]
yes, it is a bug. I reported it 3 weeks ago but maintainers didn't respond to report and reminder.
https://github.com/eamodio/vscode-gitlens/issues/1423#issuecomment-828814308

**Comment by eamodio** [comment]
@diablodale I've been really busy lately and haven't been able to devote much time to GitLens unfortunately.

Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by diablodale** [comment]
Hi. Your insider gitlens v2021.5.2405 worked well for me.

```
git tag -m "test tag" v1.1.1 f28385db90888947e9d625a35ec95637adf6e64e
```

compared to the current release v11.4.1 that fatal fails
```
git tag -m -m "test tag" v1.1.1 f28385db90888947e9d625a35ec95637adf6e64e
fatal: too many arguments
```
