### ISSUE TITLE
strange GitLens icon & doesn't work in 'workspace'

### ISSUE THREAD

**Issue by j0k4rX** [eamodio/vscode-gitlens#1516]
Strange GitLens icon
it doesn't appear on 'workspace'

- GitLens Version: 11.4.1
- Git Version: 2.25.1
- VSCode Version: 1.56.0
- OS Version: Linux Mint 20.1

![Screenshot from 2021-05-20 10-54-17](https://user-images.githubusercontent.com/71499522/118922307-9d784700-b95b-11eb-9a9b-ef05c986fec8.png)

**Comment by eamodio** [comment]
Yeah, unfortunately there was a change in VS Code that stops the correct icon from showing up, I'm hoping there will be a VS Code "fix" for that soon.

As for the "it doesn't appear on 'workspace'", what do you mean? Can you provide more details and steps? Thanks!
