### ISSUE TITLE
GitLens does not start for interractive rebase when VSCode started from command prompt

### ISSUE THREAD

**Issue by n1l** [eamodio/vscode-gitlens#1526]
Hi, please help, probably something changed in vs code so that git lens does not start when vscode runs by git from command prompt.
ex:

git rebase -i master, vs code is started

![image](https://user-images.githubusercontent.com/1175469/119839261-b610d000-bf0c-11eb-81b8-03d1eae5acda.png)

git rebase -i master, vs code is not started

![image](https://user-images.githubusercontent.com/1175469/119838929-777b1580-bf0c-11eb-8b0d-8d69cfca6963.png)

I tried to start debug, but nothing was in console.

my config file

```
[alias]
    st = status
    lol = log --stat --graph --decorate
    fap = fetch --all --prune
    please = push --force-with-lease
    co = checkout
    ci = commit
[difftool "code"]
    cmd = code  $LOCAL $REMOTE --diff -rw
[mergetool "code"]
    cmd = code $MERGED -rw
    keepBackup = false
[merge]
    tool = code
[diff]
    tool = code
[core]
    editor = code -rw
[commit]
    verbose = 2
[mergetool]
    keepBackup = false
```

settings.json

```
{
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false
    },
    "gitlens.keymap": "alternate",
    "editor.codeLens": false,
    "editor.renderWhitespace": "all",
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.detectIndentation": false,
    "debug.allowBreakpointsEverywhere": true,
    "workbench.colorTheme": "Plastic - deprioritised punctuation",
    "window.zoomLevel": 1,
    "terminal.integrated.tabs.enabled": true
}
```

- GitLens Version: v11.4.1
- Git Version: 2.30.0.windows.2
- VSCode Version: 
  Version: 1.56.2 (user setup)
  Commit: 054a9295330880ed74ceaedda236253b4f39a335
  Date: 2021-05-12T17:13:13.157Z
  Electron: 12.0.4
  Chrome: 89.0.4389.114
  Node.js: 14.16.0
  V8: 8.9.255.24-electron.0
  OS: Windows_NT x64 10.0.19043

**Comment by travisgroth** [comment]
I also started seeing this issue recently.  I'm not seeing any difference with vscode already running vs not.  Any git rebase command from the command line now gives me the old editor view instead of the gitlens view.

GitLens version: v11.4.1
git version: 2.30.1
VSCode Version: ```1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64```

**Comment by eamodio** [comment]
Can you try to see if the issue is still reproducible in GitLens 11.5.1?

**Comment by n1l** [comment]
@eamodio  not for me for now, but there was a message from VSCode with a general security question "Do you trust this window".

I think that this is a root cause.

https://code.visualstudio.com/docs/editor/workspace-trust

**Comment by travisgroth** [comment]
@eamodio I can't reproduce anymore on 11.5.1.  I think this is fixed.  Thanks!
