### ISSUE TITLE
[feature request] Open ~Previous~ Changes with Working File

### ISSUE THREAD

**Issue by AubreyF** [eamodio/vscode-gitlens#1529]
Gitlens currently offers an exceptionally useful "Open Changes with Working File" option when viewing files associated with historical commits. This option stands well on its own, but would be even more useful if complimented by a similar option to diff the pre-commit version of a particular file with the local working copy.

This new option would be functionally different from diffing file changes associated with a particular commit, as diffing with the local working copy should present an editable file instance on the right side of the diff view.

IntelliJ calls this feature "Compare Before with Local", and I find myself using it relatively often.

<img src="https://user-images.githubusercontent.com/2789037/120050252-9e4f4f80-bfd1-11eb-9dec-ca7532eab6db.png" width="300" />     <img src="https://user-images.githubusercontent.com/2789037/120050199-6942fd00-bfd1-11eb-9e8a-53fb3783a817.png" width="400" />

**Comment by eamodio** [comment]
Good idea!

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
