### ISSUE TITLE
Wrong initial keyboard focus in interactive rebase

### ISSUE THREAD

**Issue by The-Compiler** [eamodio/vscode-gitlens#1538]
- GitLens Version: 11.4.1
- Git Version: 2.32.0
- VSCode Version: 1.56.2
- OS Version: Archlinux

Steps to Reproduce:

1. Open an interactive rebase, e.g. via the command palette, "GitLens: Git Rebase...", selecting a branch/commit and interactive rebase.
2. Press `e` in an attempt to mark the first commit as "edit"
3. Notice how the keybindings don't work because the keyboard focus is in some weird place - you'll either need to click the first commit before using the shortcuts; or press the tab key twice.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by The-Compiler** [comment]
Thanks for the quick fix! :heart: I built from sources and can confirm it's working now.

A semi-related question: Given that the bindings for that view seem to be hardcoded, would you consider adding j/k and Shift-J/Shift-K as alternative bindings for Up/Down and Shift-Up/Shift-Down, for people like me who used vim too much and can't go back? :smile: Happy to open a PR if so.
