### ISSUE TITLE
Interactive rebase not in focus

### ISSUE THREAD

**Issue by Neylion** [eamodio/vscode-gitlens#1541]
Issue Type: <b>Bug</b>

1. Initiate rebase (e.g. `git rebase -i HEAD~3`)
2. Wait for the git-rebase-todo to load in (see that it seems to be highlighting the first commit in the list)
3. Attempt to interact with the commit list via the keyboard (arrow key navigation or deciding commit action)

**Expected result:**
Being able to interact with the list via the keyboard

**Actual result:**
Even tho the first commit row visually appears to be focused, vscodes focus is somewhere else. To be able to actually focus the commit list, I either need to manually click it, or run the "View: Focus Active Editor Group" command and then tab once. 

This was working as expected up until this week. I am at a loss of what the cause could be. I have tried initiating the rebase from both the internal terminal and from a separate iterm instance but both cases fail to focus the commit list.

I hope this can be fixed, it was such a smooth experience when it was working properly 🤞 

Extension version: 11.4.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|64.00GB (45.07GB free)|
|Process Argv|/Users/fredriklindberg/git/admin/livecommerce-firebase/dashboard --crash-reporter-id 64750031-25a7-4284-84eb-b3d61289da69|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333


vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

[Gitlens (git).txt](https://github.com/eamodio/vscode-gitlens/files/6641835/Gitlens.git.txt)
[Gitlens.txt](https://github.com/eamodio/vscode-gitlens/files/6641836/Gitlens.txt)

**Comment by The-Compiler** [comment]
Duplicate of #1538 I assume (though I don't remember it ever working properly for me, FWIW)

**Comment by Neylion** [comment]
Oh alright, sweet! I'll close this then. Cheers 😃
