### ISSUE TITLE
Add alternate `j`/`k` & `shift+j`/`shift+k` bindings for rebase editor 

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#1542]
Consider adding j/k and Shift-J/Shift-K as alternative bindings for Up/Down and Alt-Up/Alt-Down, for people like me who used vim too much and can't go back? :smile: Happy to open a PR if so.

_Originally posted by @The-Compiler in https://github.com/eamodio/vscode-gitlens/issues/1538#issuecomment-860032935_

**Comment by eamodio** [comment]
@the-compiler Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by Neylion** [comment]
As a fellow vim user I can confirm that this works! ...but that the order is wrong. `j` should go down, `k` should go up 😅

**Comment by The-Compiler** [comment]
Agreed with @Neylion! Apologies for the confusion, " j/k [...] as alternative bindings for Up/Down" was the wrong way around. I blame muscle memory :slightly_smiling_face:!

**Comment by eamodio** [comment]
Doh -- I thought I had it backward and meant to re-check it before release and forgot! Thanks. 11.5.1 coming with the fix.
