### ISSUE TITLE
Adopt new `createStatusBarItem` API for `id` and `name` properties

### ISSUE THREAD

**Issue by bpasero** [eamodio/vscode-gitlens#1543]
👋  Hi there, Ben here, from the VS Code team.

We just released VSCode 1.57 that landed a new stable API for status bar items to provide `id` and `name` properties: https://code.visualstudio.com/updates/v1_57#_status-bar-item-id-and-name-properties

I noticed that your extension is a consumer of the `createStatusBarItem` API. 

Here is an example how using the new API will improve the user experience around managing status bar items:

Without `id` / `name` right clicking on the status bar item from your extension will show a generic label that is just the name of the extension:

![statusbar](https://user-images.githubusercontent.com/900690/121848861-efa65100-ccea-11eb-889f-1fd8b178d525.png)

As you can see from the example above, the GH Pull Request extension did not yet adopt this new API and as such, the menu only shows a generic entry (as opposed to the other entries that are more specific).

Another motivation to adopt this new API is that it will enable a user to selectively hide/show status bar entries from your extension in case you register more than one status bar item.

An adoption of the new API involves:
* configuring `"engines": { "vscode": "^1.57.0" }` in `package.json`
* where `createStatusBarItem` is called, add a unique `id: string` property as first parameter
* in the returned `StatusBarItem` set `name` to something that describes the intent of the status bar entry (if you provide multiple status bar entries, make sure the name is different for each entry)

Thanks for the support and the great work! ❤️

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
