### ISSUE TITLE
Missing branch comparison controls in versions 11.5.0 and 11.5.1

### ISSUE THREAD

**Issue by mohoyer** [eamodio/vscode-gitlens#1545]
- GitLens Version: 11.5.0 and 11.5.1
- Git Version: 2.30.1 (Apple Git-130)
- VSCode Version: 1.57.0
b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
x64
- OS Version: macOS 11.4

Steps to Reproduce:

1. Navigate to Branches tab in the Source Control tab while GitLens is running.

2. Compare a branch with another branch.

3. Hover over the newly created comparison tree. In version 11.4.1 or earlier, buttons for "Refresh", "Edit" and "Clear" will appear. In versions 11.5.0 and 11.5.1, these buttons are not present.

I cannot find any indication in the change log that the interface changed, so I assume this is a bug.

**Comment by raulrpearson** [comment]
I've found the same issue. In my case, when I downgrade from 11.5.1 to 11.5.0, the problem persists. It resolves when I downgrade to 11.4.1.

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by raulrpearson** [comment]
@eamodio, I installed insiders edition just now (2021.6.2201) and that feature seems to work correctly again. Thanks! 🙌

**Comment by mohoyer** [comment]
The 2021.6.2201 fix works for me as well, thanks!
