### ISSUE TITLE
[Feature Request] Remote repository URL for specific line(s) of code

### ISSUE THREAD

**Issue by aitikgupta** [eamodio/vscode-gitlens#1547]
GitHub recently provided a feature in their web application, wherein we could drag and select lines of code and copy the exact URL.
(previously we could only copy the URL from the search bar, however, now we can get the URL that always points to that piece of code, even if there are a lot of changes being made to that file)

This is done simply by using the commit hash. For example:
`https://github.com/eamodio/vscode-gitlens/blob/54b2c06c1b8e4f573ed4495f42029c9df146efb0/LICENSE#L1` => https://github.com/eamodio/vscode-gitlens/blob/54b2c06c1b8e4f573ed4495f42029c9df146efb0/LICENSE#L1

(there’s also https://github.com/eamodio/vscode-gitlens/blob/main/LICENSE#L1)

When we’re debugging code on the web client, it’s all fine, but if we’re in a VSCode environment, currently there’s (I think) no way we can select a piece of code and get the remote repository URL.
(it sounds pretty straightforward (which I'm sure it's not): local git connection + getting the remote URL + using the current commit hash)

This isn’t a useless request either, since, on GitHub web client these URLs render as code snippets (which is the end goal).
^see rendered snippet for example

Being a useful utility as it is, I don’t think this is discussed anywhere (I might be searching wrong keywords), and I’m quite surprised this isn’t already baked in by default.

If this sounds like a feasible request, I could try and pitch in! :D

**Comment by eamodio** [comment]
@aitikgupta GitLens already supports this via the _Copy Remote Commit Url_. Just select the code you want and either run the command from the command palette or right-click or configure a keybinding for the command (for example, I use `Ctrl+Shift+C`).

![image](https://user-images.githubusercontent.com/641685/122156914-f2fb2300-ce37-11eb-835d-a07dafbc4d19.png)

**Comment by aitikgupta** [comment]
Hey @eamodio, thanks for reaching out.
However, what you're pointing out isn't quite what I want/suggest. Sure, we can get the remote '_commit_' URL using the method you suggested, but we still can't get those exact lines as a remote URL.

I'm not sure how I can explain it better, the end goal is that rendered snippet (in my original comment) from VSCode.

Remote '_commit_' URL just points to the actual commit, whereas the suggestion is to add something which points to the actual blob (and the specific line(s)).

**Comment by eamodio** [comment]
Ugh, sorry I got mixed up -- Use _Copy Remote File Url_ -- basically everything I said applies, I just said the wrong command

**Comment by aitikgupta** [comment]
> Ugh, sorry I got mixed up -- Use Copy Remote File Url -- basically everything I said applies, I just said the wrong command

I should've figured it out, my bad. Thanks again! :D
