### ISSUE TITLE
git version 2.7 requirement vs available centos builds of git

### ISSUE THREAD

**Issue by StarLightPL** [eamodio/vscode-gitlens#1554]
Can we make git version requirement optional somehow? The latest available git-sclo-build for Centos seems to be 2.5.5, and 2.9 is broken since forever. Do you really _need_ to require version 2.7+?
I'm stuck with Centos, and can't do anything about it short of compiling git from sources which I would rather avoid. It's bad enough I have to separately install git >2.0 to be able to use GitLens, now it requires 2.7.2.

**Comment by eamodio** [comment]
The Git version notification is a warning not a block, but there are features of Git in version 1.9 or later that are really required, and I think the only thing that requires 2.7.2 is dealing with tags, because prior to that version Git didn't support the `--format` option.

**Comment by StarLightPL** [comment]
OK sorry my bad. I was under the impression that this is a requirement blocking it from functioning, it turned out that I simply needed to enable it. I'm using the git version 2.5.5 for now and it seems to be working okay so far.
