### ISSUE TITLE
Branches tree shows folder icon when branch name has forward-slash

### ISSUE THREAD

**Issue by easyTree** [eamodio/vscode-gitlens#1555]
![VSCode_branch_slash_bug](https://user-images.githubusercontent.com/686525/123298594-93280a80-d510-11eb-829f-1c8ac19c26b7.png)
Issue Type: <b>Bug</b>

* Create a branch with a forward-slash in the name 
* Switch to another branch (using the GitLens toggle in the status bar)
* Go to the Repositories tab in the GitLens panel
* Expand the Branches node
* Voila! there's an additional level in the tree between the Branches node and the node with the branch name
* Switch to the problem branch - observe the extra level in the tree disappear
* Switch away from the problem branch - observe the extra level return

Presumably branch names with multiple slashes of either type will also cause issues.

Extension version: 11.5.1
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by eamodio** [comment]
This is as-designed -- GitLens offers the ability to nest branch/tag names with `/` as folders. You can control it via this command: 

![image](https://user-images.githubusercontent.com/641685/123578243-65a6bf80-d7a3-11eb-8e74-14e22ee53903.png)

Hope that helps.
