### ISSUE TITLE
Login with Github Failed

### ISSUE THREAD

**Issue by necessityOVO** [eamodio/vscode-gitlens#1565]
- GitLens Version:v11.5.1
- Git Version: 2.32.0.windows.1

- VSCode Version: 1.57.1
- OS Version:win10

Steps to Reproduce:

1.Open VS Code as Administrator.
2.Click to login in gitlens from account
![image](https://user-images.githubusercontent.com/60960561/123978386-6719f700-d9f2-11eb-8be1-d6ca9a560377.png)
3.Authorize Visual Studio Code to access GitHub in Chrome
![image](https://user-images.githubusercontent.com/60960561/123978623-97619580-d9f2-11eb-9ec5-acc98cd9ea42.png)

but vscode developer tools log `Sign in failed: FetchError: request to https://vscode-auth.github.com/token?code=a752aece0dd8f5876465&state=e5387cda-f6b0-4738-a9c5-e33d56c71ea1 failed, reason: read ECONNRESET`
![image](https://user-images.githubusercontent.com/60960561/123979456-51f19800-d9f3-11eb-8546-caa5436ea490.png)

and chrome log `Refused to apply style from 'https://vscode-auth.github.com/css/fonts/roboto.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. `
![image](https://user-images.githubusercontent.com/60960561/123979524-6170e100-d9f3-11eb-881a-7cb549b379c0.png)

I expect to login into gitlens in vscode. Thanks for help

**Comment by eamodio** [comment]
Unfortunately that error is coming from VS Code's GitHub auth provider (which GitLens uses) -- Can you please file this issue on the vscode repo? Thanks!
