### ISSUE TITLE
Bug: unable to open 'pr.url' when clicking PR link

### ISSUE THREAD

**Issue by gordonmleigh** [eamodio/vscode-gitlens#1566]
- GitLens Version: 11.5.1
- Git Version: 2.30.1

- VSCode Version: 1.57.1
- OS Version: macOS Big Sur 11.4

Steps to Reproduce:

1. Hover over current line blame, this will show a popup with commit and PR info
2. Click the PR link on the third row of the popup, just above where it says something like `#123 merged 3 months ago`
3. An error message is shown: "Unable to open 'pr.url'"

Note that the other PR links do work.

![image](https://user-images.githubusercontent.com/1730018/123983557-df18fa80-d9bb-11eb-96d1-7f9aba9774ed.png)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's GitLens insiders edition?

You can install the GitLens insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

Please be sure to disable or uninstall the stable version of GitLens first.

**Comment by gordonmleigh** [comment]
Confirmed fixed, thanks for the quick work! :)
