### ISSUE TITLE
Add "View file at this commit"

### ISSUE THREAD

**Issue by jez9999** [eamodio/vscode-gitlens#157]
When I'm view a file's blame annotations, I sometimes want to trace back the history of a particular line.  So I can "compare line revision with previous", but that only tells me the last change on the line.  What would be nicer is if I could view the file at that commit revision, then use the regular functionality on *that revision* of the file.  So I could view blame annotations for that file's revision, then view the file at the commit revision for the last change on the line then, and so on.  That way I could trace back all the changes made for a particular line (as well as the state of the whole file at each change).

**Comment by jez9999** [comment]
There should also be a "View file at parent commit" option actually, as to trace back the history of a line you want to be able to open the file at the commit just before it was changed, and then view blame annotations for that version.

**Comment by eamodio** [comment]
@jez9999 If you use the `Compare Line Revision with Previous` command, the diff presented is the differences in the whole file for that commit. And you can keep walking back from the left-side of the diff further into the history -- and blame annotations are available inside each diff pane.

Are you asking for something else?

**Comment by jez9999** [comment]
How do you "keep walking back from the left-wide of the diff further into the history"?

**Comment by jez9999** [comment]
No response on this.  I think my original issue remains.

**Comment by eamodio** [comment]
@jez9999 Sorry for the lack of response here. You can use the `alt+,` shortcut to open a diff with the previous revision -- see here: https://github.com/eamodio/vscode-gitlens#powerful-comparison-tools

**Comment by eamodio** [comment]
I'm going to assume this answered the question -- please re-open if there is still an issue.
