### ISSUE TITLE
'ext install gitlens' doesn't find any extension

### ISSUE THREAD

**Issue by FelixButzbach** [eamodio/vscode-gitlens#160]
Not sure if this is the right place, but on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) it is written to do:
`ext install gitlens`
to install the extension, but this won't find any extension.

I think it should be 
`ext install git lens`
(space between git and lens)

I am using vscode 1.16.0 on ubuntu 16.04.

**Comment by eamodio** [comment]
Opened https://github.com/Microsoft/vscode/issues/36185
