### ISSUE TITLE
Force to remove colors from output of git command calls

### ISSUE THREAD

**Issue by Naereen** [eamodio/vscode-gitlens#161]
Hi. First, :clap: for your project!

If the `~/.gitconfig` file (or a local git config) sets `[color]  ui=always`, then ugly ANSI colors codes are displayed in gitlens output. For instance:
![ugly ansi color codes gitlens](https://user-images.githubusercontent.com/11994719/31284898-3714f02a-aaba-11e7-9ea0-a001f8a0575c.png)

I see many different configuration option for `gitlens`, and the only one where I could modify the `git` binary or `git` command line used for each call from gitlens is `gitlens.advanced.git`.
I wrote a tiny script that just adds `-c color.ui=false` to `git`, bit specifying this script does not help to remove the bug.
```bash
#!/usr/bin/env /bin/sh
git -c color.ui=false "$@"
```

So my question is: is there any (or could you add) way of adding a command line flag to git commands used by gitlens (in this case, `-c color.ui=false` would be enough), or to override global git config for gitlens?

**Comment by eamodio** [comment]
Thanks -- I will look into adding that in an upcoming release

**Comment by Naereen** [comment]
Great, thanks for your fast reply!
Let me know if you need a beta tester :smile:

**Comment by Naereen** [comment]
It seems fixed, I will try to update the VSCode extension (when it is updated) and let you know if the bug is fixed. Thanks :clap:!

**Comment by Naereen** [comment]
Perfect! 
![fixed ansi color codes gitlens](https://user-images.githubusercontent.com/11994719/31329802-0d01b3b2-acdc-11e7-8f48-29482664d10c.png)
