### ISSUE TITLE
git required version is 2.20 but latest official is 2.14

### ISSUE THREAD

**Issue by 0m4r** [eamodio/vscode-gitlens#162]
- GitLens Version:  
5.4.1

- VSCode Version: 
Version 1.17.0
Commit be377c0faf7574a59f84940f593a6849f12e4de7
Date 2017-10-04T23:33:52.565Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

- OS Version:
Debian Jessie with Xfce (running on a Chromebook)

Steps to Reproduce:

1. start visual studio code
2. install git lens
2. error message appears saying "GitLens requires a newer version of Git (>= 2.2.0) than is currently installed (2.1.4). Please..."

The problem is that the latest official git version is actually 2.14.2 (https://git-scm.com/downloads)

I am using this extension on a macbook and I find it super cool, I wanted to have it too on my backup Chromebook, but it looks like the issue reported here will not let me do so :(

**Comment by eamodio** [comment]
@0m4r I think there is some confusion with similar version numbers -- GitLens requires 2.**2** or later, while it looks like you have 2.**1**.4 installed, while the latest version of Git as you noted is 2.**14**.2. So if you upgrade to a later version of Git you should be just fine

**Comment by 0m4r** [comment]
@eamodio you are correct. I did manage to update to 2.14 and now the gitlens error message is gone. Sorry for the confusion!
