### ISSUE TITLE
.git/index.lock can be held when vscode is in background because of GitLens calls to `git status`

### ISSUE THREAD

**Issue by joelhock** [eamodio/vscode-gitlens#163]
- gitlens|eam|5.5.0
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-05T06:07:51.906Z)
- OS Version: Darwin x64 16.7.0

Steps to Reproduce:

1. switch from vscode to terminal (so that vscode is in the background)
2. touch file (or do something that touches files, like a `git pull --rebase`)
3. see that `getStatusForRepo('/my/path/to/repo')` is called in GitLens output channel
4. if operation in terminal needs .git/index.lock (e.g. a git rebase operation), it may fail, since the GitLens `getStatusForRepo` may be holding the lock.

vscode's grabbing of the .git/index.lock has been the source of a number of issues filed against it, the main one of which is https://github.com/Microsoft/vscode/issues/11918
other extensions are now being identified that do the same thing, such as:
https://github.com/letmaik/vscode-git-tree-compare/issues/24

The behavior of GitLens can be sidestepped with `gitlens.gitExplorer.includeWorkingTree": false`, but I think GitLens should either not call `git status` when vscode is in the background via the mechanism introduced in https://github.com/Microsoft/vscode/commit/475fb0e6cc7a51a37f842e971d7d41dc594f3010, or it should instruct git (well, future versions of git) to not grab the lock during `git status` calls via the mechanism in https://github.com/Microsoft/vscode/issues/35513

**Comment by joelhock** [comment]
and now that I look at things a bit more, I see that GitLens will call `getStatusForRepo` in response to the git cache changing, so `gitlens.gitExplorer.includeWorkingTree": false` is not a complete workaround.  the filesystem watch that it controls made the problem worse, so setting it to false can still help mitigate the issue.

**Comment by eamodio** [comment]
FYI -- I added the `GIT_OPTIONAL_LOCKS=0` to GitLens 5.6, but I am currently blocked from adding the background checks by https://github.com/Microsoft/vscode/issues/36010

**Comment by joelhock** [comment]
thank you!!

**Comment by wmakley** [comment]
Happening to me constantly in Windows with WSL and the latest everything

**Comment by eamodio** [comment]
@wmakley Please open a new issue for this and attach logs and a clear description of what you were doing and the error that happened. Thanks!
