### ISSUE TITLE
Allow to invoke difftool with --dir-diff

### ISSUE THREAD

**Issue by vvs** [eamodio/vscode-gitlens#164]
It is a very handy feature added lately, to be able to invoke the difftool from within the VS Code.

Would it be possible to enhance this functionality to provide a means to invoke difftool with `--dir-diff` parameter? That way I see the actual tree diff with file structure and stuff rather than multiple tabs open (for each edited file) and in unclear order (current behavior).

**Comment by eamodio** [comment]
This is currently supported if you use the `Directory Compare` command -- that launches `difftool` with `--dir-diff`. Let me know if you had something else in mind.

**Comment by vvs** [comment]
@eamodio What I'd like to do is the following: I modified some files locally and would like to review the changes. For that, I'd prefer to invoke `difftool` with `--dir-diff` (at least that's what I do in the console).

Ideally, I'd like to do that via simple shortcut inside VS Code. The `Directory Compare` is not suitable since it asks for some extra info, like against which branch to compare, which i don't want. All I want is to see the local uncommitted changes, kinda like the `Gitlens: Open Changes (with difftool)`, but that difftool should be with `--dir-diff` parameter.

P.S. Many thanks for the great plug-in and quick responses!
