### ISSUE TITLE
Allow file compare across branches to work with renames

### ISSUE THREAD

**Issue by Shaggy13spe** [eamodio/vscode-gitlens#165]
From time to time, we'll have a file that has had a name change from one branch to another. It'd be great to be able to use GitLens to compare the two files to make sure any development done in the old-named file gets carried over and not lost when merged in to the branch with the new-named file. I do this now just using the git command line, but being able to do so in your extension would be awesome.

**Comment by eamodio** [comment]
GitLens should follow renames (assuming git will follow the rename -- if a file changes too much it won't be seen as a rename). Do you have a case where it isn't working?

**Comment by Shaggy13spe** [comment]
Yes. Let me give more information as to how are branching is set up: We follow a modified GitFlow branching model, where we have a "production" **master** branch and "next release" **develop** branch. We develop by grouping user stories, usually by functionalities being developed, into releases, and might have different teams working on different releases in parallel. So each release itself is a **feature** branch pulled from develop, and then each individual user story is worked on by the pair by creating another **feature** branch from one of those "parent" feature branches and then merging back in to those. The "parent" feature branch is then later merged to **develop** after it has been finished and deemed the next release to production (the business likes to be able to move releases around). At any rate, the business had renamed one of the features of the application, and so we had a story in one of the releases to rename files to match that rename. However, that file was still being worked on in one of the other "parent" **feature** branches. I was wanting to compare those files to make sure I don't lose any code from one to the other. Running the git diff on the command line works, but running your git diff "Compare to another branch" just sees it as a completely new file.

In branch A, the file (and folder path) is named intraDayMsr/intraDayMsr.controller.js
![image](https://user-images.githubusercontent.com/630205/31495397-7c11b4f0-af25-11e7-8bd9-a1f1933bd0e2.png)

In branch B, the file (and folder path) is renamed to nextBay/nextBay.controller.js
![image](https://user-images.githubusercontent.com/630205/31495404-8380fd5e-af25-11e7-8118-256ac1193b35.png)

While in branch A, did GitLens: Compare with another branch
![image](https://user-images.githubusercontent.com/630205/31495409-88c00b20-af25-11e7-8805-59d18100555e.png)

Result is that it sees it as a new file (because that file name/path doesn't exist in branch B)
![image](https://user-images.githubusercontent.com/630205/31495415-8c6e3e0e-af25-11e7-800c-51e5a1847187.png)

**Comment by Shaggy13spe** [comment]
Sorry, didn't mean to hit the Close button

**Comment by eamodio** [comment]
@Shaggy13spe what git command do you use to get this to work for you?

**Comment by eamodio** [comment]
@Shaggy13spe FYI I've added support for this in the latest alpha: https://github.com/eamodio/vscode-gitlens/releases/tag/v6.0.0-alpha

**Comment by Shaggy13spe** [comment]
Sorry, I had never responded to your later inquiries, I had issues with my gmail not refreshing on my phone, and I don't check it all that often online. At any rate, thanks for adding this, love your extension!

**Comment by mungojam** [comment]
is this also meant to work in branch compare? it seems that it picks it up in the file history view but not when comparing branches
