### ISSUE TITLE
Request: too many settings, add a GUI tab

### ISSUE THREAD

**Issue by jose-a-sa** [eamodio/vscode-gitlens#167]
Last time I have checked there are 82 different setting in gitblame, which make it complicated for customizing the extension.
A nice option would be a GUI page (tab) with the essential settings (with dropdowns, checkboxes, ...) with some toggle to show more advanced settings.

**Comment by eamodio** [comment]
While I totally agree, the vscode api doesn't afford much in the way of creating UI for something like this. But I'd be eternally grateful to anyone who wants to spearhead this.

**Comment by eamodio** [comment]
FYI, I'm starting to take a look into what options I can provide here.

**Comment by eamodio** [comment]
Here is an early pass at adding a Settings page to GitLens. Please chime in and let me know what you think, what other settings you'd like to see in the UI. FYI, I don't want to add ALL of them, but cover a good subset that people use.

![image](https://user-images.githubusercontent.com/641685/35058028-ae75b738-fb84-11e7-9fa6-5f4b7d2a024e.png)

**Comment by jose-a-sa** [comment]
I thought it would look more like the one from code spell checker but let me just say that the settings page looks f***ing amazing. Good job
