### ISSUE TITLE
GitLens sidebar pane is blank

### ISSUE THREAD

**Issue by mindpivot** [eamodio/vscode-gitlens#168]
<img width="419" alt="screen shot 2017-10-11 at 4 34 46 pm" src="https://user-images.githubusercontent.com/1554893/31521796-da05b7c0-af78-11e7-9d2c-16eadd3d9cc3.png">
- GitLens Version: 5.6.3
- VSCode Version: 1.17.1
- OS Version: MacOS High Sierra 10.13 (17A405)

Steps to Reproduce:

1. I reordered the sidebar panes to put GitLens above Docker
2. Content in GitLens pane disappeared.
3. Tried uninstalling/upgrading to no avail

Attaching verbose logs:
[gitlens_log.txt](https://github.com/eamodio/vscode-gitlens/files/1380851/gitlens_log.txt)

At first I thought it may have been something with the fact that particular project was using submodules but GitLens has stopped working for any projects on my machine.

**Comment by eamodio** [comment]
@mindpivot would you mind trying this version to see if it resolves your issue? 

[gitlens-5.6.4.zip](https://github.com/eamodio/vscode-gitlens/files/1381208/gitlens-5.6.4.zip)

Please rename it back to `gitlens-5.6.4.vsix` and then follow these instructions to install it: https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions

**Comment by mindpivot** [comment]
That fixed it!

Awesome, thank you!

(apologies for the delayed reply)

**Comment by eamodio** [comment]
Excellent! A bit later tonight I'll release that version to the marketplace. Thank you!
