### ISSUE TITLE
Gitlens Panel > Branches > Commit view keeps collapsing

### ISSUE THREAD

**Issue by awendland** [eamodio/vscode-gitlens#169]
I make heavy usage of the branch commit browser in the Gitlens panel to walk through commits for code review. However, I've been running into an issue where the expanded tree state that I had randomly (and frequently) collapses down to just showing the available branches, instead of maintaining the commit I had expanded and the nested files.

- GitLens Version: 5.6.4
- VSCode Version: 1.17.1 as well as older versions
- OS Version: macOS 10.13

Steps to Reproduce:

1. Open a branch > then a commit > then a file in the Gitlens panel
2. Wait several seconds
3. Witness it automatically collapse w/o user interaction

![gitlens-collapse-branches](https://user-images.githubusercontent.com/1152104/31563708-398e5822-b02e-11e7-9a1e-88169d0ae3c5.gif)

**Comment by eamodio** [comment]
@awendland While the state of the GitLens explorer isn't close to where I would like it, in terms of refreshes losing all context, there are a few blocking vscode issues:

https://github.com/Microsoft/vscode/issues/34789 
https://github.com/Microsoft/vscode/issues/30535 
https://github.com/Microsoft/vscode/issues/33371

Although at the same time, I can't reproduce the behavior you are seeing -- I can expand something in the view and it will stay that way until something changes -- like a file in the repo, or the repo state itself (which could be updated by vscode's auto-fetch (via the `git.autofetch` setting).

Have you noticed any rhyme or reason to when it refreshes and loses its context? Can you try setting `"git.autofetch": false` and see if that changes the behavior? Any more details you can provide would be greatly appreciated.

**Comment by awendland** [comment]
@eamodio Thanks for detailing the issues behind this and for looking into it. GitLens has become an integral part of my flow because of how high quality it is, so I must imagine these vscode limitations are frustrating you to no end 😂 

Setting `git.autofetch` hasn't helped the issue at all unfortunately. For the time being the hammer approach that you've mentioned in #180 is what I'll be using, and I'll make sure to up-vote the appropriate vscode issues wherever possible. Thanks again for such a great extension!

**Comment by eamodio** [comment]
No problem and thank you for your kind words!

Hrm, while there are a lot of known issues with refreshes collapsing everything, I'm still unsure why you are experiencing it if nothing changed. Would you mind trying out the latest [GitLens v6 alpha](https://github.com/eamodio/vscode-gitlens/releases/tag/v6.0.0-alpha)? I've refactored a lot to reduce extra events and overhead which *might* have an effect here. It also has more improved logging that might help determine why the view is refreshing.

**Comment by eamodio** [comment]
@awendland GitLens 6 is out now, if you are still experiencing this issue, please re-open this and attach logs -- thanks!

**Comment by awendland** [comment]
@eamodio The problem seems to have been fixed! Thank you! An era of code review bliss has arrived 😄
