### ISSUE TITLE
Blame annotations start flashing

### ISSUE THREAD

**Issue by oli-laban** [eamodio/vscode-gitlens#170]
I'm encountering a weird issue where all blame annotations start flashing rapidly. Disabling and re-enabling the extension fixed the issue for a while but it returned later in the day (restarting VSCode does not fix the issue).

![2017-10-16 20 36 58](https://user-images.githubusercontent.com/16418002/31631843-f230f66a-b2b2-11e7-93c4-e0319868e7b3.gif)

- GitLens Version: 5.6.4
- VSCode Version: 1.17.1
- OS Version: macOS 10.12.6

**Comment by eamodio** [comment]
Is there any rhyme or reason to when this behavior starts? Does it continue if you switch the current line?

Can you also attach the logs when you experience this issue? Please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your `settings.json`. This will enable logging to the GitLens channel in the Output pane.

**Comment by oli-laban** [comment]
> Is there any rhyme or reason to when this behavior starts?

Not that I've noticed yet. 

> Yes it does, throughout all files in the workspace. I didn't check whether it happens in two separate windows, I will next time. 

> Can you also attach the logs when you experience this issue?

Will do.

**Comment by kevinzli** [comment]
I have the same issue now.

**Comment by eamodio** [comment]
@kevinzli can you provide logs?

**Comment by eamodio** [comment]
@oli-laban @kevinzli can you try out the latest [GitLens v6 alpha](https://github.com/eamodio/vscode-gitlens/releases/tag/v6.0.0-alpha1)? I've reworked how the inline annotations are refreshed and hopefully resolved the issue you are seeing.

Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know if you experience any issues -- thanks!

**Comment by kevinzli** [comment]
@eamodio I don't know what is the reason, but it is working well now. I didn't try v6 alpha though.

**Comment by eamodio** [comment]
I'm hoping GitLens 6 (out now) resolves this. Please re-open if not.
