### ISSUE TITLE
how to get rid of inline annotation?

### ISSUE THREAD

**Issue by geddski** [eamodio/vscode-gitlens#171]
I've tried a ton of settings but can't seem to get rid of this inline annotation in my working files:

![image](https://user-images.githubusercontent.com/515722/31639859-5bcc6160-b298-11e7-8938-dbfb145ff29f.png)

How do I disable this?

**Comment by eamodio** [comment]
Hard to tell for sure in that screenshot but it looks like that is the code lens (appears above a line) -- if so you can use `"gitlens.codeLens.enabled": false` to turn it off. If that is actually the end of line annotations then you can use `"gitlens.blame.line.enabled": false` to turn it off.

Hope that helps.

**Comment by geddski** [comment]
ahh `gitlens.codeLens.enabled` was it! Thank you!

**Comment by sfertman** [comment]
Thank you for Gitlens! It is a great extension and I use it all the time. 

I have just one issue that keeps bugging me: blame is very useful and gitlens makes it conveniently appear in the editor with a click of a button; but do the annotations really need to be there all the time and by default? In addition to the code clutter, every time you switch to a file you get that "bump" effect that opens up new lines in the code and then slow fade-in of codelens text... So, usually the first thing I do after installing is googling how to disable this.

**Comment by eamodio** [comment]
Thank you! In GitLens 8 there is a new WYSIWYG settings editor to allow you to very easily configure GitLens exactly to your needs. You can open it from the Command Palette -- *GitLens: Open Settings*

**Comment by sfertman** [comment]
Oh, this is a great feature!

**Comment by eveevans** [comment]
You can also activate gitLens Zen Mode (this disable some visual features like  inline annotation)
I configured a shorcut to toggle this mode on: gitlens.toggleZenMode

**Comment by stephen-costa** [comment]
> ... If that is actually the end of line annotations then you can use `"gitlens.blame.line.enabled": false` to turn it off. 

Ended up being `"gitlens.currentLine.enabled": false` for me, not sure if they changed it since then or not but figured I'd update here for posterity.

**Comment by Domiii** [comment]
In latest version, things seem to have changed a bit. This works though:


```
"gitlens.codeLens.enabled": false,
"gitlens.blame.highlight.enabled": false,
"gitlens.currentLine.enabled": false
```
