### ISSUE TITLE
File Blame Annotations No Longer Working

### ISSUE THREAD

**Issue by imoby** [eamodio/vscode-gitlens#174]
- GitLens Version: 5.7.0
- VSCode Version: 1.17.2
- OS Version: High Sierra

Steps to Reproduce:

1. Open a file that has git history
2. Initiate File Blame Annotations through button or through keyboard shortcut
3. File blame annotations does not open. 

Issue started happening from the new version

**Comment by DarthPestilane** [comment]
Same problem.

**Comment by eamodio** [comment]
Doh! Thank you for the report -- 5.7.1 is out now with a fix. That's what I get for trying to push a release when I'm not feeling well ;)

**Comment by imoby** [comment]
@eamodio thanks for the quick fix! Hope you get well soon
