### ISSUE TITLE
[Unreleased] next to latest release in the changelog after updating

### ISSUE THREAD

**Issue by TomasHubelbauer** [eamodio/vscode-gitlens#175]
Recently (last 4 releases or so), I've been seeing a `[Unreleased]` label next to the latest release in the VS Code change log for the extension after updating (I always check it after updating to see what changed). Is this expected behavior? Did removal of that just get forgotten before the past few releases?

**Comment by eamodio** [comment]
I've been following the http://keepachangelog.com/ format -- and I use the `## [Unreleased]` section as I'm developing to keep track of the changes prior to the release and once a release is ready a version and date title get inserted below it. See here http://keepachangelog.com/en/1.0.0/#effort

**Comment by TomasHubelbauer** [comment]
I understand but my point is I see the heading still _after_ it's been released. Perhaps before releasing the heading should be removed, release cut, and then added back in so you can start working on new release notes. Check the Changelog tab for the extension in VS Code to see what I mean.

**Comment by eamodio** [comment]
Yup, I know what you mean -- didn't think it would case any confusion seeing an empty `[Unreleased]` section. I'll think about deleting it before a release. Thanks.

**Comment by TomasHubelbauer** [comment]
For some reason I didn't realize it was actually two headers one following the other, but I took it to be a prefix of the current version, hence my misunderstanding. Realizing this, you may be right, I might have been the only one confused. :-) I'll leave it up to you then, just wanted to mention it.

**Comment by eamodio** [comment]
No worries -- appreciate the report. Reducing confusion is always a good thing :)

**Comment by TomasHubelbauer** [comment]
I've given this one more thought @eamodio and I think I made a mistake and this should actually be included. Maybe with a little more context, like an extra sentence saying *These changes are expected to land in version x.y.z at foo/bar* (can always be changed) or something. What do you think?

**Comment by eamodio** [comment]
The `[Unreleased]` section isn't for what is upcoming really -- it is to keep track (during development) what has already been checked in, but not released yet. So there is no version or date to be expected.
