### ISSUE TITLE
Line annotations some times mess with white space.

### ISSUE THREAD

**Issue by mcarpenterjr** [eamodio/vscode-gitlens#176]
- GitLens Version: 5.7.1
- VSCode Version: 1.18.0 - insider
- OS Version: Linux Mint 18.2

Steps to Reproduce:

1. Write some code in a pre-existing repository
2. Create a new line and press tab, get more whitespace than expected.

Sometimes when writing code if the annotation passes the soft break the workspace scrolls way off to the side also.

If lens is disabled or removed the problem goes away.

Otherwise great extension.

**Comment by eamodio** [comment]
Can you provide more details -- what type of file? what language? Also can you maybe include a screen capture of it?

I can't reproduce the behavior, but I'm not sure I'm doing it properly.

**Comment by mcarpenterjr** [comment]
I've noticed this in JS, HTML, and PHP

It happens what seems like randomly, I will try and get a gif for you.

**Comment by eamodio** [comment]
@mcarpenterjr could the issue you are seeing be this one: https://github.com/Microsoft/vscode/issues/36873?

**Comment by mcarpenterjr** [comment]
Nope, it's the line annotations from gitlens, I have a better understanding of what's occuring now. It does happen at what seems like random so it's hard to capture the behavior through Peek to create a gif.

This occurs in CSS JS HTML and PHP files.

While coding the line annotation (the light gray entry that has the user's name time of last commit and the commit title) will appear, this forces the cursor to the end of the annotation, the annotation will then disappear just as quickly as it appeared but leave behind excessive white space. What I would assume is padding around the annotation.
In cases where the line is long and is approaching the softwrap bar, the annotation will actually ignore the softwrap and cause the workspace to scroll horizontally. What it seems like is occurring is the cursor is getting pushed into the great beyond past the softwrap and forces the view to scroll.

Also, I managed to get a partial instance of this occurring...
![wooo](https://user-images.githubusercontent.com/11430497/32790855-8a66ef94-c92d-11e7-9ee1-27e00b72af2a.gif)

**Comment by eamodio** [comment]
OK, I have posted on https://github.com/Microsoft/vscode/issues/34441, which I think this is related to.

Although from your gif -- do you have your auto-save set to some extremely small timeout? Because GitLens should be not showing those annotations while you are editing (i.e. unsaved)

**Comment by mcarpenterjr** [comment]
Autosave is on, I have not changed the timeout, so maybe that needs a BUMP.

**Comment by mcarpenterjr** [comment]
The default for autosave is 1000... ms? that's low.

**Comment by eamodio** [comment]
Hrm, every second is pretty low. I'm guessing part of the problem is that I debounce the events and if its getting hit with a bunch of save/dirty/save/dirty events I am likely skipping some. I'll have to think a bit on how best to protect against that.

Thanks for the extra info!

**Comment by mcarpenterjr** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8add83ef-c2a7-48d2-9054-35462c5d1245-1226cfca-7889-4f73-83fe-a8b2afa987d4-v1.png?transparent=1&palette=1&width=246)
