### ISSUE TITLE
Slight but noticeable keyboard lag with Gitlens

### ISSUE THREAD

**Issue by carlca** [eamodio/vscode-gitlens#178]
- GitLens Version: 5.7.1
- VSCode Version: 1.18.0 Insider
- OS Version: macOS 10.13.0 High Sierra

Other extensions loaded:

PeterJausovec.vscode-docker
RomanPeshkov.go-test-outline
Wosi.omnipascal
be5invis.vscode-custom-css
christian-kohler.path-intellisense
codezombiech.gitignore
deerawan.vscode-dash
donjayamanne.githistory
donjayamanne.python
eamodio.gitlens
eg2.vscode-npm-script
emmanuelbeziat.vscode-great-icons
foxundermoon.shell-format
hars.CppSnippets
hnw.vscode-auto-open-markdown-preview
Kiteco.kite
lukehoban.Go
magicstack.MagicPython
ms-vscode.azure-account
ms-vscode.cpptools
ms-vscode.csharp
nisimiko.theme-whitehat
rogalmic.bash-debug
rubbersheep.gi

Steps to Reproduce:

1. Open VSCode and attempt to edit a .go file
2. Keyboard lag is slight but enough to be noticeable. I've tried narrowing down the culprit by disabling my extensions in turn and it seems to be Gitlens that is causing the issue.

**Comment by egamma** [comment]
@eamodio we now support to profile the extension host pls see https://github.com/Microsoft/vscode/wiki/Performance-Issues#creating-performance-profiles.

**Comment by eamodio** [comment]
I'll take a look into this. In the meantime, can you help me determine if the issue goes away for you if you systematically disable some GitLens features?

`"gitlens.blame.line.enabled": false`
`"gitlens.codeLens.enabled": false`
`"gitlens.gitExplorer.enabled": false`
`"gitlens.statusBar.enabled": false`

If turning off any (or all) of those help, it will also help me pinpoint the issue.

@egamma Yeah -- good point. The profiler was definitely my friend in helping me greatly improve the performance of the full-file blame annotations :)

**Comment by carlca** [comment]
I'll try that in an hour or so. I have to cook some food and eat first. Thanks to you and Erich for the replies!

**Comment by carlca** [comment]
It's difficult to be certain because the differences in response time are barely perceptible but I thought there was a definite speed up when I changed 
`
"gitlens.codeLens.enabled":
`
to 
`
false
`
I hope that helps!

**Comment by eamodio** [comment]
Thank you! I'll check it out

**Comment by eamodio** [comment]
@carlca can you try out the latest [GitLens v6 alpha](https://github.com/eamodio/vscode-gitlens/releases/tag/v6.0.0-alpha1)? I've refactored and reduce a bunch of overhead so hopefully it will resolve the lag you are seeing.

Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know if you experience any issues -- thanks!

**Comment by carlca** [comment]
Something I forgot to mention (sorry!) is that I have been starting VSCode insiders with the arguments  `--args --disable-gpu` . That was because otherwise, the built-in terminal window was not displaying properly. I've just tried it without those arguments and it does seem to be improved. I don't know at the moment if that can be attributed to the new alpha version, though.

**Comment by eamodio** [comment]
Are you still seeing a difference between with and without GitLens? With the new code, there will be some impact (mostly only on the first character typed into a file without any other edits -- but even so it should be very small) it should be extremely small. From profiling I don't even see any GitLens stuff anywhere near the top of the profile.

If you are still seeing issues -- can you try disabling all other extensions and capture a snapshot of the issue, following the steps here: https://github.com/Microsoft/vscode/wiki/Performance-Issues#creating-performance-profiles?

**Comment by carlca** [comment]
I’ll get back to this tomorrow.

Cheers,
Carl

**Comment by carlca** [comment]
There's a lot of different tasks on that page  https://github.com/Microsoft/vscode/wiki/Performance-Issues#creating-performance-profiles .
Which tasks, in particular, should I concentrate on (don't say all of them!!)

**Comment by eamodio** [comment]
@carlca sorry - just https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-extension-process

**Comment by eamodio** [comment]
I'm hoping GitLens 6 (out now) resolves this. Please re-open if not.
