### ISSUE TITLE
GitLens only displayed for some files

### ISSUE THREAD

**Issue by tlyng** [eamodio/vscode-gitlens#18]
I don't know if this is a bug or some user error triggered by me, anyway the gitlens only show up inline in some files. Is this supposed to be like this, are there configuration settings I miss or is this something else?

Here I don't see any gitlens information inline in editor
![lens-hidden](https://cloud.githubusercontent.com/assets/135056/20565080/5df3bf2e-b190-11e6-8bb6-67000aa40a09.png)

but in this file it's displayed.
![lens-displayed](https://cloud.githubusercontent.com/assets/135056/20565097/6b7b25ce-b190-11e6-8264-292781f39b52.png)

**Comment by eamodio** [comment]
@tlyng does that always happen on that file? If you close and reopen, does it show? Is that file by any chance in .gitignore?

Please try add the following setting `"gitlens.advanced.output.level": "verbose"`, and then try closing and re-opening that file and take a look at the `GitLens` output in the Output panel. Hopefully that will have some hints to figure this out.

**Comment by tlyng** [comment]
## Output for file where GitLens is not shown

### GitLens output
```
getBlameForFile('/.../curator/src/curator/curator/auth/__init__.py', undefined, undefined)
Add blame cache for '/.../curator/src/curator/curator/auth/__init__.py'
git blame --incremental --root -- __init__.py   cwd='/.../curator/src/curator/curator/auth'
getBlameForFile('/.../curator/src/curator/curator/auth/__init__.py', undefined, undefined)
```

### git blame output
```
a1347ec7fdbcdef6f02be94f40e255ea198e5a46 2 2 40
author Lyng, Torkel
author-mail <torkel.lyng@*.com>
author-time 1479731079
author-tz +0100
committer Lyng, Torkel
committer-mail <torkel.lyng@*.com>
committer-time 1479731079
committer-tz +0100
summary Initial JWT Authentication support
previous 32949d4e1381a7c8b7dad35d54670ac974dc6cfb src/curator/curator/auth/__init__.py
filename src/curator/curator/auth/__init__.py
32949d4e1381a7c8b7dad35d54670ac974dc6cfb 1 1 1
author Lyng, Torkel
author-mail <torkel.lyng@*.com>
author-time 1479461042
author-tz +0100
committer Lyng, Torkel
committer-mail <torkel.lyng@*.com>
committer-time 1479461042
committer-tz +0100
summary Tweaks and bugfixes
filename src/curator/curator/auth/__init__.py
```

## Output for file where GitLens is enabled

### GitLens output
```
getBlameForFile('/.../curator/src/curator/curator/auth/tests/__init__.py', undefined, undefined)
Add blame cache for '/.../curator/src/curator/curator/auth/tests/__init__.py'
git blame --incremental --root -- __init__.py   cwd='/.../curator/src/curator/curator/auth/tests'
getBlameForFile('/.../curator/src/curator/curator/auth/tests/__init__.py', undefined, undefined)
getBlameForRangeSync('/.../curator/src/curator/curator/auth/tests/__init__.py', [0, 1], undefined, undefined)
```

### git blame output
```
a1347ec7fdbcdef6f02be94f40e255ea198e5a46 1 1 1
author Lyng, Torkel
author-mail <torkel.lyng@*.com>
author-time 1479731079
author-tz +0100
committer Lyng, Torkel
committer-mail <torkel.lyng@*.com>
committer-time 1479731079
committer-tz +0100
summary Initial JWT Authentication support
filename src/curator/curator/auth/tests/__init__.py
```

**Comment by eamodio** [comment]
@tlyng Hrm. It looks like from the git side of things everything is good. I don't have enough logging to see into the CodeLens part currently. Is this repo public?

**Comment by tlyng** [comment]
No, but I can try on a public repo to check if the same thing occur.

**Comment by tlyng** [comment]
Tried it on `https://github.com/tlyng/testpyramidtemplate`, same issue. It looks like it works on most files, here are a list of files which it won't show up:

- `src/testpyramidtemplate/views.py`
- `src/testpyramidtemplate/models.py`
- `src/testpyramidtemplate/__init__.py`

Here are some files which it do show up:

- `setup.py`
- `setup.cfg`
- `Makefile`
- `src/testpyramidtemplate/tests.py`

Other than that I am running on Ubuntu Linux, latest vscode and latest gitlens.

**Comment by tlyng** [comment]
Did more investigation. If I clone the directory and open it in vscode (without creating a virtual environment and setting up the package for development) I get the gitlense view on most files (except `src/testpyramidtemplate/__init__.py`). If I on the other hand actually do setup the repository for development using:

```
$ git clone https://github.com/tlyng/testpyramidtemplate.git
$ cd testpyramidtemplate
$ virtualenv --python=python3.5 .
$ pip install -e .\[test\]
$ code .
```

Then I only get GitLense on a couple of files.

**Comment by tlyng** [comment]
I suspect there are some other python specific plugins that are causing the issue, tried it on golang repositories and everything worked as intended.

**Comment by tlyng** [comment]
Discovered something that solved my issue in python. If I set `gitlens.codelens.location` to `all` or `document+containers` then the lens won't show up on many files. If I set it to just `document` it works on all files.

**Comment by eamodio** [comment]
@tlyng Thanks so much for the investigation! Later tonight I will try your example repo and see if I can track down the issue.

**Comment by eamodio** [comment]
@tlyng OK after lots of pulling my hair out, my best guess is that there is a bug in the python vscode extension. GitLens uses the built-in `vscode.executeDocumentSymbolProvider` command to get document symbols from whatever provider provides them for the current language. For some unknown reason, the python provider seems to return 0 symbols in some cases. The case were I saw it 100% of the time, was when I was testing with both GitLens and TypeLens (we both use `vscode.executeDocumentSymbolProvider`). And whichever one executed `vscode.executeDocumentSymbolProvider` first was the one that got all the symbols, the later one always got 0 symbols.

So my guess is that you have another extension which also calls `vscode.executeDocumentSymbolProvider` or that the python extension sometimes doesn't respond properly in all cases. I would recommend opening an issue with the python vscode extension.

**Comment by eamodio** [comment]
Opened https://github.com/DonJayamanne/pythonVSCode/issues/553 to track this
