### ISSUE TITLE
Option to disable automatic collapsing/expanding of gitexplorer nodes when there is a refresh

### ISSUE THREAD

**Issue by JavierPDev** [eamodio/vscode-gitlens#180]
Feature Request:

Can we get an option for `gitlens.gitExplorer` that would disable the automatic collapsing/expanding of the different nodes when there is a refresh? For Instance, I often have just the Stash node expanded, but then when there's a refresh the Stash node collapses and the Branches node expands. 

I find gitlens to be one of the best git extensions/GUIs I've used and the way it integrates with VSCode is great. This is the only issue I've had so far.

Thanks for the great work.

**Comment by eamodio** [comment]
Hehe -- I wish (believe me it is NOT a feature). Unfortunately the current vscode apis are so limited with custom views there is very little I can do at this point that would make it better. I've covered just some of the limitations (with open issues) here: https://github.com/eamodio/vscode-gitlens/issues/169#issuecomment-336903596

In an attempt to make this a tiny bit less of an issue, I added a couple things in [5.7.0](https://github.com/eamodio/vscode-gitlens/blob/master/CHANGELOG.md#570---2017-10-19). 

You can use a hammer and set `"gitlens.gitExplorer.autoRefresh": false` to turn off the auto-refresh completely -- and therefore you will need to use the refresh button/command to manually refresh the view. Or I also added 2 new commands (menu items in the `...` menu of the GitLens view), that allow you to quickly toggle on/off auto-refresh for the view for that specific workspace.

So at least until vscode expands the feature-set of the custom view api, there isn't a whole lot I can do to make it better -- and BELIEVE me I want too, it drives me **nuts** too

**Comment by eamodio** [comment]
@JavierPDev in vscode 1.19, they have made changes to the custom view support to persist the state better. I have also made some changes to GitLens (since vscode fixed some other underlying issues in 1.19 too) that should help as well.

Please let me know if you think this issue can be closed.

**Comment by JavierPDev** [comment]
It's working great now, thanks. I think this issue can be closed.
