### ISSUE TITLE
Add the option to show heatmap when the blame sidebar is collapsed

### ISSUE THREAD

**Issue by dkniffin** [eamodio/vscode-gitlens#182]
- GitLens Version: 5.5.0
- VSCode Version: 1.16.1
- OS Version: Mac OSX 10.12.3

I really like the heatmap functionality provided by this extension, but I'd like to see it without all the extra info that shows up when the blame sidebar is open

**Comment by eamodio** [comment]
So you'd want to see the heatmap visible all the time? Or just on a toggle -- like the normal blame, but without the extra info?

**Comment by eamodio** [comment]
@dkniffin ☝️

**Comment by dkniffin** [comment]
I think a toggle would be good. I'd probably leave it on all the time, but I could see others not wanting it.

**Comment by eamodio** [comment]
@dkniffin So you'd want to be able to toggle the heatmap by itself, but still have access to toggle the blame annotations too right? I ask because today you could configure the blame annotations to not have a message and just the heatmap (but of course then you can't turn on the messages without editing the config).

**Comment by dkniffin** [comment]
Ideally, yeah, that's how I'd like it. Removing the messages is a good workaround though.

**Comment by eamodio** [comment]
Added in 7.2

**Comment by cateyes99** [comment]
@eamodio  I've installed `7.2`, but I don't see `gitlens.toggleFileHeatmap` to toggle the heatmap annotations on and off. Below are all the settings i can see related to heatmap:
![image](https://user-images.githubusercontent.com/19678455/34503555-dc41171e-f07d-11e7-827d-2d614cdef36e.png)

**Comment by eamodio** [comment]
@cateyes99 `gitlens.toggleFileHeatmap` is a command that can be executed via the command palette --
 `Toggle File Heatmap Annotations`, or by adding a custom keyboard shortcut like:
```json
    {
        "key": "alt+m",
        "command": "gitlens.toggleFileHeatmap",
        "when": "editorTextFocus && gitlens:activeIsBlameable"
    },
```

Hope that helps.

**Comment by cateyes99** [comment]
@eamodio thanks it helps.
