### ISSUE TITLE
Save on resolution of merge conflict

### ISSUE THREAD

**Issue by WesleyYue** [eamodio/vscode-gitlens#188]
I'd like to put in a feature request to save the conflicted file automatically when I resolve it using the git lens interface (GUI?). I've accidentally committed files thinking they were resolved only to realized I never saved after pressing one of the "Accept Change" buttons.

**Comment by eamodio** [comment]
@WesleyYue Merge conflict support is provided by vscode directly -- GitLens doesn't have any features for dealing with merge conflicts. Please report this issue on the vscode repository: https://github.com/Microsoft/vscode/issues. Thanks!

**Comment by WesleyYue** [comment]
Oh, sorry about that! Will do.
