### ISSUE TITLE
Allow branch deletion through the GUI in explorer

### ISSUE THREAD

**Issue by panghal0** [eamodio/vscode-gitlens#189]
A Feature Request.
Right now the context menu on right click on a branch name in repository view only shows 
1. `Refresh` for local branches
2. `Refresh` and `Open Branch in Remote` for remote branches

Can we add another option(s)
1. `Delete Local Branch` for local branches
2. `Delete Local Branch` and `Delete Remote Branch` for remote branches

I don't know how useful it will be to others but I personally hate to type out the commands every time in terminal(not a big terminal user I am). 

...Also thanks everyone for the great tool.

**Comment by eamodio** [comment]
GitLens 6 is out now with new commands that are run in the terminal -- let me know what you think.

**Comment by panghal0** [comment]
That's Awesome
