### ISSUE TITLE
editor shaking when first line was blank

### ISSUE THREAD

**Issue by yuchuanxi** [eamodio/vscode-gitlens#19]
when the text begin from first line, It's OK:
![normal](https://cloud.githubusercontent.com/assets/5205912/20638723/f7118190-b3e9-11e6-8a27-67149df13836.gif)

But, when the fist line is blank, the editor will SHAKING!!!
![bug](https://cloud.githubusercontent.com/assets/5205912/20638724/f916f98e-b3e9-11e6-9e90-77ef9a59b8a7.gif)

**Comment by eamodio** [comment]
This is a bug in vscode, I've opened the following issue: https://github.com/Microsoft/vscode/issues/16097

**Comment by eamodio** [comment]
Since this will be fixed in VSCode 1.8 I'm closing this.
