### ISSUE TITLE
Annotations appear (rarely) before the end of a line

### ISSUE THREAD

**Issue by YMIndustries** [eamodio/vscode-gitlens#190]
- GitLens Version: 5.7.1
- VSCode Version: 1.17.2
- OS Version: Windows 10 Home, 1703, 15063.674

Steps to Reproduce:

Not sure of a reliable way to reproduce this sorry, I've only just noticed it happening on one of my files.

Here's a screenshot of the issue: ![Screenshot](https://i.imgur.com/tpEOzsS.png)

The Git Lens annotation appears to be one character before the end of the line, with the comma in my code appearing after the annotation.

**Comment by eamodio** [comment]
Unfortunately this is a quick of the way vscode line decorations (which GitLens uses for the annotations) are currently implemented. Here is the related vscode issue: https://github.com/Microsoft/vscode/issues/34441
