### ISSUE TITLE
Support for VS Code Workspaces

### ISSUE THREAD

**Issue by joeshub** [eamodio/vscode-gitlens#193]
- GitLens Version: 5.7.1
- VSCode Version: 1.18.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Create a workspace in VS Code containing 2 different git repos
2. Edit files in both repos
3. Notice Git Lens only shows the first repo in your workspace

**Comment by eamodio** [comment]
GitLens 6 is out now, with multi-root workspace support

**Comment by mohammedi-haroune** [comment]
Hello, this is very old but it can't seem to work, I have Gitlens: 10.2.2 and I created my workspace using: File > Add folder to workspace. Any thoughts ?
