### ISSUE TITLE
Get rid of all things that pop up in my files

### ISSUE THREAD

**Issue by rightaway** [eamodio/vscode-gitlens#194]
There should be one setting to disable all things that this extension pops up in files, like a non-intrusive setting for people who just want this extension's functionality when they specifically request it. I don't want to see things appear at the end of the line or at the top of the file and each class (the `You, 5 minutes ago` thing).

How can I disable these individually for now? The ones at the top of the file and each line won't go away and I've tried various settings.

**Comment by eamodio** [comment]
Closing this -- with the 6.1 release the documentation changes are live on the marketplace
