### ISSUE TITLE
Preview search matches

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#197]
6.0.0 introduced the excellent search / grep feature (#127), it would be useful if I could preview the search matches. For example, when I search for `=footer`, I get this:

![image](https://user-images.githubusercontent.com/101152/32647301-cba59fcc-c5f0-11e7-8dcf-345ea0648b62.png)

If these are larger commits with dozen of changed files, it's not easy to find out where exactly the string `"footer"` occurred. I'm not sure how to best do it, maybe inside explorer sidebar somehow.

_Originally suggested here: https://github.com/eamodio/vscode-gitlens/issues/127#issuecomment-339574186_

**Comment by eamodio** [comment]
In [7.3 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.3.0-beta), I've fixed an issue where `Show in Results` wouldn't only show you the files where the match was found (assuming you were matching in files). Hopefully this resolves this issue -- please let me know.

FYI, I've also added `~` and `=` commit search operators to the placeholder hint text in the commit search box.
