### ISSUE TITLE
Files in submodules or nested repositories no longer work properly

### ISSUE THREAD

**Issue by tiansin** [eamodio/vscode-gitlens#198]
- GitLens Version:6.0.0
- VSCode Version:1.18
- OS Version:win10

Steps to Reproduce:

1.Select the submodule file in the file list and right-click on the Compare menu,not work!
![qq 20171110211451](https://user-images.githubusercontent.com/4232281/32660036-3761368e-c65c-11e7-8ac8-0c58e22c56f7.png)

![1](https://user-images.githubusercontent.com/4232281/32659852-6b5d5522-c65b-11e7-94a3-0f2085570773.png)

The editor menu in the submodule file is no longer visible.
gitlens-5.7.1 is support!

**Comment by eamodio** [comment]
@tiansin do you have a public repo with an example where I can try this out?

**Comment by tiansin** [comment]
@eamodio 
![1](https://user-images.githubusercontent.com/4232281/32670419-af370e00-c67e-11e7-9a1f-e209ff8118be.png)
![2](https://user-images.githubusercontent.com/4232281/32670425-b4ba40ea-c67e-11e7-9592-ee04764cab0b.png)
[test.zip](https://github.com/eamodio/vscode-gitlens/files/1462137/test.zip)

**Comment by eamodio** [comment]
@tiansin great, thank you. A fix for this will be in the next release -- sorry for the inconvenience. The refactoring for the multi-root workspace support affected a lot of things and this one slipped through the cracks unfortunately :(
