### ISSUE TITLE
Staged change's vscode diff side-by-side view shows the wrong history

### ISSUE THREAD

**Issue by JasonKleban** [eamodio/vscode-gitlens#202]
The annotations on the staged change's vscode-diff-side-by-side show the wrong history. For example, on a branch that only diverged just a few days ago, the staged change of the merge back to master shows "Joel, 7 months ago * ..." from a seemingly random old commit, rather than the real diverging commit of 17 hours ago.  copied from #187

**Comment by eamodio** [comment]
@JasonKleban Could you try out the new [GitLens beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v6.3.0-beta). I believe it will resolve this issue, but I'd like to be sure before I release it. Thanks!
