### ISSUE TITLE
Show tags

### ISSUE THREAD

**Issue by acorderob** [eamodio/vscode-gitlens#204]
[feature request]

- GitLens Version: 6.1.0
- VSCode Version: 1.18.0
- OS Version: W7 32bit

It would be really nice if a commit selection list would show the commit tags. We set environment tags (production, preproduction, etc.) and when trying to compare with those commits we need to find out first which id they are.

Thanks.

**Comment by eamodio** [comment]
Do you mean having a *Tags* node in the GitLens repository explorer view?

**Comment by acorderob** [comment]
No. I mean in the Command Palette, after selecting a command that asks for a commit (for example "compare file with revision").
