### ISSUE TITLE
Gitlens doesn't work over UNC

### ISSUE THREAD

**Issue by jez9999** [eamodio/vscode-gitlens#208]
I have a project I host on a remote server and access over a UNC share.  When I open its project folder in VS Code, Gitlens doesn't work.  If I click refresh in the Gitlens pane, the following error comes up:

> [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character

I'm guessing this is to do with UNC paths beginning with `\\`?  It would be nice if Gitlens supported this.

**Comment by eamodio** [comment]
@jez9999 While I don't have a need for this (nor an easy way to set this up), I'd like to be able to support this (assuming it isn't a massive amount of work). Can you please provide some logs and any other information you have about where this breaks?

**Comment by eamodio** [comment]
@jez9999 any update on this?

**Comment by jez9999** [comment]
How do I get logs?

**Comment by jez9999** [comment]
The error I mentioned above occurs when the GitLens pane is in History View, and you click refresh.  Also in Repository View when I try to expand the "2 files changed" tab I get the same error.  There may be other times when it happens too.

**Comment by eamodio** [comment]
This should be fixed in 7.2
