### ISSUE TITLE
Editor ruler is not re-positioned when GitLens adds left-hand panel to code tab

### ISSUE THREAD

**Issue by Merryweather** [eamodio/vscode-gitlens#210]
- GitLens Version: 6.1.2
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 6.1.7601
- Other VSCode Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|6.1.2
tslint|eg2|1.0.23
prettier-vscode|esb|0.26.0
auto-close-tag|for|0.5.3
auto-complete-tag|for|0.0.2
auto-rename-tag|for|0.0.15
python|ms-|0.8.0
PowerShell|ms-|1.5.1
angular2-inline|nat|0.0.17

---

Steps to Reproduce:

_Note:_ I am not sure if the issue lies with vscode or gitlens.

1. Ensure the GitLens extension is installed and active.
2. Open a source file that has some Git history.
3. In VSCode 'User Settings', set `"editor.rulers": [140]`
Observe the ruler appears in the source tab and it is positioned correctly.
4. Select the 'Toggle File Blame Annotations' command, provided by the GitLens extension.
(There's a button on the toolbar at the top right of the screen)
This will insert a panel to the left of the code.  Content of the panel is, I believe, irrelevant.
Observe that the code has been shifted to the right to accommodate the extension's panel, but the editor ruler has not moved.  The editor ruler is now in the wrong position in relation to the code.

Expected behavior:
I was anticipating that the ruler would be shifted to the right, in the same way as the code.

Observed actual behavior:
The ruler remained in the same position after the extension had added a panel to the left of the code resulting in the ruler being positioned incorrectly in relation to the code.

**Comment by Merryweather** [comment]
Feels like this should be in the same ballpark as https://github.com/eamodio/vscode-gitlens/issues/91.

**Comment by eamodio** [comment]
Yeah, it is somewhat similar to that issue. I opened https://github.com/Microsoft/vscode/issues/39165. If/when that issue is resolved there will unlikely be any changes required by GitLens, therefore I'm closing this issue. Thanks!
