### ISSUE TITLE
Move GitLens to "Source Control" activity

### ISSUE THREAD

**Issue by ADTC** [eamodio/vscode-gitlens#213]
Right now, GitLens is in the Explorer panel (Ctrl-Shift-E). I would like it to be in the Source Control panel (Ctrl-Shift-G). It makes more sense to be there, and I want the Explorer panel to just be focused on exploring (I even disabled the Open Editors view).

I don't know if VSCode API allows this. I hope so... (Edit: I think it should be possible: https://code.visualstudio.com/docs/extensionAPI/api-scm )

**Comment by eamodio** [comment]
Sadly this isn't yet possible, see https://github.com/Microsoft/vscode/issues/28662. Although once it is possible you bet there will be an option at least to put it there -- because that's exactly where *I* want it too :)

**Comment by ADTC** [comment]
OK. I think maybe there's a chance _someday_ extensions could have their own activity (adding a new icon in the Activity Bar).

**Comment by eamodio** [comment]
Yeah, hopefully so -- and when it's available you can be sure I'll add support :)

**Comment by jens1o** [comment]
I'd also like to see this happen :)

**Comment by tonypee** [comment]
It might also be useful to be able to dock to the bottom panel (not side), as i often find that when i want to browse commits, or file changes, i need to widen the side panel greatly, then to view the diff, the rhs is squished. 
I use a veritcal monitor setup which definitely doesnt help this - but just a thought

**Comment by eamodio** [comment]
@tonypee unfortunately GitLens is positioned in the only location allowed by the vscode api currently. When what is allowed changes, I will definitely be open to exploring alternatives.

**Comment by BerryVM-wend** [comment]
@tonypee Join the club and watch this related issue on the VSCode repo:
https://github.com/Microsoft/vscode/issues/43645

**Comment by eamodio** [comment]
My plan is to move GitLens into the SCM activity. I originally thought that I could make it a user choice (SCM vs GitLens' own activity), but currently that really isn't possible with the provided apis/structures.

Hopefully moving to the SCM view is an acceptable compromise.
