### ISSUE TITLE
Better recognition of local GitLab installations

### ISSUE THREAD

**Issue by ffes** [eamodio/vscode-gitlens#214]
- GitLens Version: 6.2.0
- VSCode Version: 1.18.1
- OS Version: Windows 10

We run a GitLab CE server in our LAN and right now to open the remote I need to add this line to my settings (obviously example.com is replaced with the proper internal name ;-)

```json
"gitlens.remotes": [{ "domain": "gitlab.example.com", "type": "GitLab" }]
```

But as you can see, the URL contains the part `gitlab`. It would be great if GitLens would automatically recognize the `gitlab` part in the URL and open the remote accordingly, so without the need to add the line to the settings.

And yes, when somebody chooses to use `git.example.com` they still would need to configure that manually.

**Comment by eamodio** [comment]
Let me think about this some more. It feels too fragile to me right now. Another option would be if GitLens detects remotes that aren't currently "built-in" that it could prompt you to setup the remote with GitLens. What do you think about something like that?

**Comment by ffes** [comment]
That would help indeed, but I still think that when somebody put `gitlab` in the domain name of a remote it can be safely recognized.
