### ISSUE TITLE
VSCode hang with GitLens enable when changing files externally

### ISSUE THREAD

**Issue by maroy1986** [eamodio/vscode-gitlens#215]
Since VSCode has released x64 version of VSCode, Git Lens make my VSCode hang. Disabling Git Lens make that behavior go away. I have a gulp task that copy files around (mostly in the node_modules folder) when I make code changes while running in watch mode, and this makes VSCode hang when Git Lens is enabled. This is weird because my node_modules folder isn't tracked in my Git, so I don't understand why it makes GitLens go crazy.

I can try to provide you with more debug info if you need them.

- GitLens Version: 6.2.0 (and previous)
- VSCode Version: 1.18.1 x64
- OS Version: Windows 10 1709

Steps to Reproduce:

1. You need to have a task, or maybe do it manually, that copy a bunch of files outside VSCode.
2. About 50% of the time, VSCode will freeze and end up showing a dialog saying it hang and give you the choice to either wait or reload VSCode.
3. Disabling GitLens make things go back to normal.

**Comment by eamodio** [comment]
@maroy1986 Could you possibly turn on logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

**Comment by eamodio** [comment]
@maroy1986 also can you post your `files.exclude` and `search.exclude` settings?

**Comment by maroy1986** [comment]
I have turned on the outputLevel, I'll try to reproduce the issue this afternoon. Problem is, it is not predictable and I got no way to reproduce it all the time, so I'll see this afternoon, I'll sure get it at some point.

My `files.exclude` and `search.exclude` use the default value that ship with VSCode, I didn't change those.
![image](https://user-images.githubusercontent.com/2490360/33283063-ac9e323e-d378-11e7-8a96-d132ff8bc940.png)

I'll keep you posted!

**Comment by eamodio** [comment]
Awesome thank you!

**Comment by meCoding** [comment]
PowerShell is not starting anymore on my machine. It keeps saying "Starting PowerShell". If I disable Gitlens, I can run the PowerShell. Once I enable Gitlens again, PowerShell won't start. This behavior started today when I updated Gitlens to newest version (6.2.0). I also noticed the same on the other machine where I have VS Code and Gitlens.

**Comment by eamodio** [comment]
@meCoding can you please enter a new issue? Since it is pretty unrelated to this one. Also please provide all the issue template details, as well as what version of the Powershell extension, and also please attach logging to show the issue. I'm using the latest Powershell extension and I haven't been able to reproduce what you are seeing. Thanks!

**Comment by maroy1986** [comment]
The issue just happen but I haven't been able to get the logging output, UI was freeze and the message saying that VSCode isn't responding anymore keep popping. The only thing I can do is a screenshot and I doubt the info will be very helpful on the console. There must be more that happens after the editor hang.
![image](https://user-images.githubusercontent.com/2490360/33323125-7d37ea20-d419-11e7-8a22-5fb977b69839.png)
Did you know, by any chances, if those logs are stored somewhere on the disk or if there only there?

**Comment by eamodio** [comment]
@maroy1986 Can you detail a bit more into what files are you moving around? I've tried a bunch of cases and I can't get anything to trigger the behavior you are reporting. 😞

**Comment by eamodio** [comment]
@maroy1986 I just saw this issue posted to the vscode repo: https://github.com/Microsoft/vscode/issues/39266. Do you have any of the files open in the editor when you are changing them externally? Do you think this *could* be related? If you have no editors open and perform the same task, do you see any freeze?

**Comment by maroy1986** [comment]
@eamodio Maybe that's it! But the issue goes away when I remove or disable GitLens... Maybe that's a few things put together that cause the issue I'm having.

It does it a few times again this morning and hasn't been able to really catch something in the output... Random issues like these are the worst... 

For the what file I'm moving question, I basically have some gulp tasks, and I'm in a monorepo. So I have a project A that is used as a dependency in project B. So to avoid having to do `npm install` all the time to get the files updated, I create a gulp task that runs after the build completed to update the dependency in project B from project A. My `dist` folder I'm copying has 615 files for 1.21mb in size. But the full copy only happens when building the entire project, when I make a change to a TS file, only the changed files get copied, so maybe 2-3 files at the time. So that's not that much and those files are pretty small.

**Comment by maroy1986** [comment]
@eamodio Ok, I disabled your extension this afternoon to validate again if your extension was really the cause and guess what, I had the hang error anyway. So that's not your extension, after all, This is weird that last time I disabled it I didn't have any problem but hey, blame on the random issue... Thanks anyway for your support, really appreciated!

**Comment by eamodio** [comment]
I guess I'm happy about that ;) I'd recommend opening an issue with vscode, and if you do can you post a link to it here?
