### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by maxibanki** [eamodio/vscode-gitlens#218]
- VSCode Version: Code - Insiders 1.19.0-insider (3c470706ded48fc75c05f86bc4f9c7b0f4d6c708, 2017-11-27T05:14:17.223Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.0.5
jshint|dba|0.10.15
vscode-eslint|dba|1.4.3
githistory|don|0.2.3
xml|Dot|1.9.2
gitlens|eam|6.2.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
vscode-abap|lar|0.1.0
Go|luk|0.6.69
postscript|max|1.0.0
code-beautifier|mic|1.7.2
debugger-for-chrome|msj|3.5.0
vscode-docker|Pet|0.0.22
vscode-icons|rob|7.18.1
vscode-table-formatter|shu|1.2.1
addDocComments|ste|0.0.8
html-preview-vscode|tht|0.1.1
vscode-import-cost|wix|2.5.1

(1 theme extensions excluded)

---

Steps to Reproduce:

1. I don't know sorry. The error appeared just in the dev tools console.

```
[eamodio.gitlens] Cannot read property 'replace' of undefined: TypeError: Cannot read property 'replace' of undefined
	at PathIterator.reset (C:\Users\mxs\.vscode-insiders\extensions\eamodio.gitlens-6.2.0\out\src\system\searchTree.js:36:26)
	at TernarySearchTree.get (C:\Users\mxs\.vscode-insiders\extensions\eamodio.gitlens-6.2.0\out\src\system\searchTree.js:152:33)
	at GitService.<anonymous> (C:\Users\mxs\.vscode-insiders\extensions\eamodio.gitlens-6.2.0\out\src\gitService.js:955:49)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\mxs\.vscode-insiders\extensions\eamodio.gitlens-6.2.0\out\src\gitService.js:4:58)
	at <anonymous>
e.onUnexpectedError @ shell.ts:459
(anonymous) @ shell.ts:419
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:42
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

```

I think the exception will be thrown will with this stacktrace in typescript:

https://github.com/eamodio/vscode-gitlens/blob/fc25a594e1664cef5b4623b7b12b2280ee12c0f4/src/system/searchTree.ts#L60-L65

https://github.com/eamodio/vscode-gitlens/blob/fc25a594e1664cef5b4623b7b12b2280ee12c0f4/src/system/searchTree.ts#L199-L219

https://github.com/eamodio/vscode-gitlens/blob/fc25a594e1664cef5b4623b7b12b2280ee12c0f4/src/gitService.ts#L243-L253

**Comment by eamodio** [comment]
Thanks for the report! I'm pretty sure 6.3 (coming soon) will resolve this.
