### ISSUE TITLE
Cannot read property 'sha' of undefined

### ISSUE THREAD

**Issue by nonameolsson** [eamodio/vscode-gitlens#22]
The extension throws some errors i the console. This is how it looks when I open Visual Studio Code with the extension activated. I have had some problems with VS Code recently. Error messages showing up and prompting to reload window. That is how I discovered this. I do not yet know if this extension has something to do with that error message.

<img width="550" alt="screen shot 2017-01-07 at 09 24 52 1" src="https://cloud.githubusercontent.com/assets/1493018/21740458/2dfd9026-d4bb-11e6-94b4-0d460cf8d490.png">

**Comment by eamodio** [comment]
@nonameolsson can you enabled `gitlens.advanced.output.level` = `verbose` and `gitlens.advanced.debug` = `true`, and then send me the output from the GitLens output pane when the error occurs?

**Comment by nonameolsson** [comment]
@eamodio Thanks, will do!

**Comment by Tyriar** [comment]
I'm seeing this as well. It happens when `settings.json` is focused. This is a pretty common use case to open files that do not below to any git repository so it should be handled gracefully :smiley: 

```
[Extension Host] [GitLens] getBlameForFile('/home/daniel/.config/Code - Insiders/User/settings.json', undefined, undefined)
```

```
CodeLens config changed; resetting CodeLens provider
getBlameForFile('/home/daniel/.config/Code - Insiders/User/settings.json', undefined, undefined)
Add blame cache for '/home/daniel/.config/code - insiders/user/settings.json'
git blame --root --incremental -- settings.json   cwd='/home/daniel/.config/Code - Insiders/User' 
  Error: fatal: Not a git repository (or any of the parent directories): .git  Failed with exit code: 128
Replace blame cache with empty promise for '/home/daniel/.config/code - insiders/user/settings.json'
Clear cache entry for '/home/daniel/.config/code - insiders/user/settings.json', reason=DocumentSaved
CodeLens config changed; resetting CodeLens provider
getBlameForFile('/home/daniel/.config/Code - Insiders/User/settings.json', undefined, undefined)
Add blame cache for '/home/daniel/.config/code - insiders/user/settings.json'
git blame --root --incremental -- settings.json   cwd='/home/daniel/.config/Code - Insiders/User' 
  Error: fatal: Not a git repository (or any of the parent directories): .git  Failed with exit code: 128
Replace blame cache with empty promise for '/home/daniel/.config/code - insiders/user/settings.json'
getBlameForFile('/home/daniel/dev/sourcelair/xterm.js/package.json', undefined, undefined)
Add blame cache for '/home/daniel/dev/sourcelair/xterm.js/package.json'
git blame --root --incremental -- package.json   cwd='/home/daniel/dev/sourcelair/xterm.js'
getBlameForFile('/home/daniel/.config/Code - Insiders/User/settings.json', undefined, undefined)
getBlameForFile('/home/daniel/.config/Code - Insiders/User/settings.json', undefined, undefined)
getBlameForFile('/home/daniel/.config/Code - Insiders/User/settings.json', undefined, undefined)
```

**Comment by eamodio** [comment]
@Tyriar You are seeing the same `Cannot read property 'sha' of undefined`? With the same stack trace? I can't reproduce this issue - I can go through the same steps and produce practically the same output log you posted, but I never see that error (things are handled gracefully).

Is it always reproducible?

**Comment by Tyriar** [comment]
It seemed always reproducible. Note I was on the insiders build.

**Comment by eamodio** [comment]
Hrm -- I'm running today's insiders too. Can you try this build [gitlens-1.4.2.zip](https://github.com/eamodio/vscode-gitlens/files/709266/gitlens-1.4.2.zip) -- I've added some more logging to trap when this happens. 

(Just need to rename it back to *.vsix -- github wouldn't let me upload it otherwise)

**Comment by Tyriar** [comment]
No reproducing now, it's probably worth adding some more defensive checks though.

**Comment by eamodio** [comment]
@nonameolsson are you still experiencing this issue?

**Comment by eamodio** [comment]
I think I have finally resolved this in the latest version.

**Comment by crnjakovic** [comment]
Same here.
