### ISSUE TITLE
Add "active" repository (root) node in the GitLens Repository view

### ISSUE THREAD

**Issue by cilerler** [eamodio/vscode-gitlens#224]
It is very difficult to follow up visual tree if you have 20+ **Folder** under your **Workspace** and if each of those **has its own repository**.

Provide us an option to hide non-selected folders.  

It would be a very helpful feature...

**Comment by eamodio** [comment]
Can you provide more details on the problem (just too many repositories?) and what you'd like to see changed?

**Comment by cilerler** [comment]
When I click on `FortressOfSolitude` project in _Folders_ section, I would like to see only that one in _GitLens_ section

![image](https://user-images.githubusercontent.com/385958/33907637-d686f432-df53-11e7-93ab-38cf8df02024.png)

**Comment by eamodio** [comment]
Unfortunately there isn't any way I can provide that functionality (vscode doesn't expose any ability for me to know what folder is selected in the explorer). I *could* provide an option similar to the active editor tracking I do (if you switch to the History view) -- where it would would show the repository of the active editor. Or maybe add an option to have an "Active Repository" node always at the start, and that would track the active file, but the rest of the tree would remain the same. Thoughts?

**Comment by cilerler** [comment]
🤔 that is really sad to hear.

**Active Repository** makes sense and it will solve my problem 100%

Thank you for fast response...  🤗

**Comment by eamodio** [comment]
@cilerler Check out the latest [GitLens 7 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.0.0-beta) and let me know what you think about the new `Active Repository` feature

**Comment by cilerler** [comment]
I may be not get it but it seems to me there is no difference, can you point it out via screenshot/screen cast please?

**Comment by eamodio** [comment]
No the first node in the GitLens tree (assuming there is more than 1 repository) will be the `Active Repository` -- which will change as you change which editor is active.

![image](https://user-images.githubusercontent.com/641685/34068357-747de2da-e207-11e7-99fa-475e8a86b5e1.png)

Does that make more sense?

**Comment by cilerler** [comment]
It is still not showing me "Active Repository" and I reinstalled it from the file after uninstall.

Based on your screen shot, even the way you implemented is good enough, allowing to filter repository would give more clearance.  It could be optional but will help to eliminate being too crowd.

Thanks for your fast act by the way...

**Comment by eamodio** [comment]
Hrm, I don't know why it wouldn't be showing. Can you try the updated [GitLens 7 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.0.0-beta)? If it still isn't showing can you send a screenshot?

**Comment by cilerler** [comment]
![image](https://user-images.githubusercontent.com/385958/34075580-fc837cb2-e298-11e7-9fdb-96f5c8af8995.png)

**Comment by eamodio** [comment]
That screenshot looks like v6.4 not the v7 beta. Are you sure you installed v7? What version does it say in the extensions pane?

**Comment by cilerler** [comment]
![image](https://user-images.githubusercontent.com/385958/34075766-bd0e8c74-e29e-11e7-87d2-844adc2148eb.png)

**Comment by eamodio** [comment]
Are you now running vscode 1.19? If not that is probably the issue. Since I now require 1.19

**Comment by cilerler** [comment]
That was the issue.  And upgrade solved the problem.  Working like a charm.  Thanks... 🤗

**Comment by eamodio** [comment]
Phew. Glad it is sorted now :)
