### ISSUE TITLE
Annotations show in Debug Console

### ISSUE THREAD

**Issue by roblourens** [eamodio/vscode-gitlens#226]
I always see annotations from the current line in the Debug Console. Is that expected? I find it distracting.

![image](https://user-images.githubusercontent.com/323878/33868056-98bc1392-deb5-11e7-9066-46ab5e7c23b2.png)

**Comment by eamodio** [comment]
This is definitely not expected or by design. I have seen this a couple of times, but never seem to be able to reproduce it. Do you have any steps?

**Comment by eamodio** [comment]
I believe this will be fixed in GitLens 7, please re-open if it reoccurs.
