### ISSUE TITLE
Gutter blame spills over heatmap

### ISSUE THREAD

**Issue by nicksnyder** [eamodio/vscode-gitlens#228]
- GitLens Version: 6.4.0
- VSCode Version: Version 1.18.1
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

```
"gitlens.blame.file.lineHighlight.locations": [
        "gutter",
        "overviewRuler"
    ],
    "gitlens.annotations.file.gutter.compact": false,
    "gitlens.annotations.file.gutter.format": "[${author|20?}] ${message|20?} ${ago|14-}",
```

![screen recording 2017-12-12 at 02 03 pm](https://user-images.githubusercontent.com/754768/33910899-389c5ea0-df45-11e7-9623-770a473819e9.gif)

**Comment by eamodio** [comment]
Check out the latest [GitLens 7 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.0.0-beta) -- it should resolve this issue
