### ISSUE TITLE
gitlens.keymap problem

### ISSUE THREAD

**Issue by tiansin** [eamodio/vscode-gitlens#229]
- GitLens Version:6.40
- VSCode Version:1.81
- OS Version:win10

Steps to Reproduce:

1. I set it up "gitlens.keymap": "none" or "gitlens.keymap": "standard"
2. The shortcut menu of the editor menu does not change.
![1](https://user-images.githubusercontent.com/4232281/33921773-13f8cce8-e001-11e7-94cc-d275ed810d15.png)
![2](https://user-images.githubusercontent.com/4232281/33921775-170c70c4-e001-11e7-9fef-51ad9b77faa1.png)

**Comment by eamodio** [comment]
This is just an issue with what shows in the menus, not what shortcut keys actually work right? If so, this looks to be a vscode 🐛

**Comment by tiansin** [comment]
The menu is displayed incorrectly, 
I configured "gitlens.keymap": "standard",
But the shortcut still shows [Ctrl+Alt+G+*]

**Comment by eamodio** [comment]
I've opened https://github.com/Microsoft/vscode/issues/40389

**Comment by eamodio** [comment]
I'm going to close this as there isn't much I can do. I need Microsoft/vscode#40389 to fixed in some way.
