### ISSUE TITLE
File History not working on Windows 7

### ISSUE THREAD

**Issue by AriesMOo** [eamodio/vscode-gitlens#23]
On Windows 7, it always show me this warning "**_Unable to show file history. File is probably not under source control_**" and does not work... The file (and the project itself) is on git and github too.
However, the blame feature works well. 

On OS X Sierra all works well (file history + blame), but in Windows 7, I can't make it work properly. 

Thanks for this awesome extension !

**Comment by eamodio** [comment]
@AriesMOo sorry for that. Which version of Git are you running? Can you make sure it is the latest?

If after verifying you are running the latest git version and are still having the same issue, can you set gitlens.advanced.output.level = verbose and gitlens.advanced.debug = true, and then send me the output from the GitLens output pane when the problem occurs?

**Comment by AriesMOo** [comment]
@eamodio It is working now ;)
I had the last Git version, but also had an old portable version in the PATH variable (and a cmder bin variable with another old git version)... I sorted the path variables, just to run the properly version of Git, and all worked fine, so the bug was mine... sorry :S

Thanks for your support !!
