### ISSUE TITLE
Add Gravatar thumbnails to git commit listings or history views

### ISSUE THREAD

**Issue by bgever** [eamodio/vscode-gitlens#230]
It would be great if every listing with commits shows a [Gravatar](https://en.gravatar.com/) thumbnail of the author before the git commit message. This allows in a fairly small amount of screen space to see who authored the commit. Or when someone has made a bunch of commits in sequence. Currently this author information is a bit hidden - after the commit message - which may go out of view in a narrow sidebar.

Coming from Visual Studio, where their git UI has this simple feature, I find that it is really useful and would be a nice addition to gitlens.

**Comment by eamodio** [comment]
@bgever Awesome suggestion! Check out the latest [GitLens 7 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.0.0-beta) and let me know what you think 😉

**Comment by bgever** [comment]
@eamodio It works perfectly! Fantastic how quickly you've implemented this and your codebase looks really neat as well. Kudos to you! 👍 Also, the retro style of the Gravatars is a nice fit with VS Code. 😄 

![image](https://user-images.githubusercontent.com/1618765/34024399-d11c2886-e184-11e7-96c2-335c6da7ab34.png)

From the code I can see that the cached images are stored in memory, and would be reloaded when VS Code restarts. It may be a nice future improvement to cache these to disk, to reduce network traffic, and allow through a VS Code command to refresh the cache. The cache refresh option is also in VS and I've used it before. What do you think?

**Comment by eamodio** [comment]
Thanks -- yeah, the retro looks decent, but the main reason I chose it is because it is "stable" given an email address. So you can actually tell the difference between the commit authors even if there is no gravatar.

Personally I don't think it is worth any local disk caching -- I'm just caching the urls in memory (so I don't have to keep recomputing the e-mail md5. But electron (i.e. chrome) should deal with caching the actual images themselves.

**Comment by bgever** [comment]
Ah I see, leveraging the browser cache, clever. 😄 

I do think the other Gravatars are also sticky, SourceTree uses the more common lighter colored triangular ones.

Thanks again for the quick implementation of this feature!
