### ISSUE TITLE
Apply Changes not appearing in context menu for files in a stash

### ISSUE THREAD

**Issue by jchlu** [eamodio/vscode-gitlens#232]
- GitLens Version: 6.4.0
- VSCode Version: 1.18.1
- OS Version: macOS High Sierra 10.13.1

Steps to Reproduce:

1. Stash changes to multiple files
2. Activate GitLens: Show Stashed Changes
3. Pick latest stash
4. Select file from Changed Files list
5. There is no `Apply Changes` listed in the available actions as per README

![Missing Apply Changes Screenshot](http://d.jch.lu/GtxAT0/7Xh1Xapx+)

**Comment by eamodio** [comment]
The reference in the README is talking about the `GitLens` view, which does offer this option, but the quick pick menu should also support it as well. So I will add that feature in an upcoming release. Thanks!
