### ISSUE TITLE
Compare directory between two tags (or branches)

### ISSUE THREAD

**Issue by rksys** [eamodio/vscode-gitlens#234]
the feature **Compare directories with between two branches** is really cool !  But it seems not very convenient to compare directory between two tags:

Currently, I am reading a [project called requests](https://github.com/requests/requests/) and often need to see the changes between two tags (like `compare 0.4.0..0.5.0`.).   If I want to see all the changes between these two tags, I need checkout to 0.5.0 at first, then **manually browse to find the commit hash** in gitlens pane, after that fire an `Open All Changes With Working Tree` command. the process of eyeballing to the hash of tag 0.4.0 is sort of painful as there are many commits from 0.5.0 to 0.4.0.

So, I am wondering if gitlens have a more convenient way to do that, or whether can add a feature to do it more directly: specify any previous `tag`, then we can open all the changes with current working tree.

The is use-and-feel is like: 

```txt
https://github.com/requests/requests/compare/aa331946...2d98ca74
                                              ^0.4.0      ^0.5.0
```

**Comment by eamodio** [comment]
@rksys GitLens 7 adds this ability -- you can now select a tag in the `GitLens` view, right-click and select `Select for Compare`, and then select another tag, right-click and select `Compare with Selected` and it will open the new `GitLens Results` view with a comparison of those 2. It works for tag, branches, commits, etc
