### ISSUE TITLE
Feature: Refresh GitLens window after git pull

### ISSUE THREAD

**Issue by eladcandroid** [eamodio/vscode-gitlens#235]

**Comment by eamodio** [comment]
This should happen automatically unless you've turned off the auto-refresh of the GitLens view. Can you provide more details?

**Comment by eladcandroid** [comment]
I restarted vs code with only GitLens as the single extension. 
I did "git pull" with a local dev branch. 
I see "dev is up-to-date with origin/dev" , but the origin branch still shows a red icon. 
Image attached.

"gitlens.gitExplorer.autoRefresh" is true.
VSCode: 1.19.1

![git_pull](https://user-images.githubusercontent.com/13297000/34325361-0194f168-e898-11e7-8312-c3834ddebced.png)

**Comment by eamodio** [comment]
Unfortunately I still can't reproduce this. Does it happen 100% of the time? Can you attach logs for when you run the `git pull`? I'm assuming you are doing a `git pull` from the command line right?

Enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please reproduce the issue and attach the relevant log lines from the GitLens channel.

**Comment by eamodio** [comment]
@eladcandroid are you still experiencing this issue?

**Comment by eladcandroid** [comment]
@eamodio Yes.. checked 5 minutes ago..

**Comment by eamodio** [comment]
@eladcandroid As I mentioned I **can't** reproduce this issue. I would recommend uninstalling and re-installing GitLens to see if that helps. If not, please provide logs (as [requested](https://github.com/eamodio/vscode-gitlens/issues/235#issuecomment-354308581)) otherwise there isn't anything I can do to fix this.

**Comment by eladcandroid** [comment]
@eamodio OK, now I have this issue with git push to.
Here's my scenario:
1. Merge some commit from X branch into primary local branch - for example "dev"
2. use "Push to..." from commands to push this merged commit into the primary remote branch - for example "origin/dev".
3. The status is still "dev is not up-top-date with origin/dev" (attached) and you need to refresh manually to make this message disappear.

![image](https://user-images.githubusercontent.com/13297000/34814938-2b9c44b0-f6b8-11e7-82a7-b22bd6f92416.png)


Tested with the latest VSCode (1.19.2)

**Comment by eamodio** [comment]
@eladcandroid Can you try the latest [beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.3.0-beta) and see if there is any difference?

**Comment by eamodio** [comment]
Closing since I haven't heard back. Please re-open if the issue still persists.
