### ISSUE TITLE
Request: Close diff and open working file...

### ISSUE THREAD

**Issue by joerohde** [eamodio/vscode-gitlens#236]
- GitLens Version: 7.00
- VSCode Version: 1.19.1
- OS Version: Win 10, OSX 10.13.2

When a diff is open, it would be ideal to have a command that can close it and replace with the working file.  If this exists, I'm missing it.   'Git.openfile' only works if the diff window contains the working file. Once you start rummaging around in diff this command become a no-op.

Even if I just had 'gitlens.openWorkingFile' I would be happy since I could write an extension to grab the current document url, run the command and close the previous diff doc.

Alternatively, if there is any way for an extension to grab the working file info/url from a gitlens diff that would also work, but once the diff has 2 temp file urls, I don't see a reasonable way to derive what working file they are sourced from (if any).

Thanks - love the extension.

**Comment by eamodio** [comment]
@joerohde Excellent suggestion! I find myself wanting the same all the time! :)

**Comment by joerohde** [comment]
Thanks - I have tremendous respect for your work.  Several times I've dropped down to writing an extension because there was something I wanted to do from the 'diff window' or with the SCM model thinking 'surely there is going to be something hanging off the document' or 'surely I can get info/metadata about the 2 sides of the diff pane'.  While these things may be possible, I have usually run screaming into the night.  As near as I can see the vscode team seems to have a strong desire to eventually expose a general SCM api, but it's hit the stage of 'always going to prioritized under current work, but we aren't going to expose what we have since it's not general enough'.

**Comment by eamodio** [comment]
Appreciate the kind words. Yeah, there are definitely challenges with the current api (mainly just need more exposed), but the vscode team is thoughtful and methodical when it comes to the apis they want to support. We'll get there eventually ;)

**Comment by joerohde** [comment]
Working great - Thanks!
