### ISSUE TITLE
Show a single commit in the GitLens Results view

### ISSUE THREAD

**Issue by ppggff** [eamodio/vscode-gitlens#237]
- GitLens Version: [7.1.0] - 2017-12-22
- VSCode Version: 1.19.1
- OS Version: macos 10.12.6

I know it's possible to show commit detail in quick pick menu.
Then how to open this one target commit in result view?
(not all history of current file, just this commit)

I hope it can be done by a quick link in quick pick menu as "show commit in result ",
or a link in hover annotation.

Thanks

**Comment by eamodio** [comment]
Unfortunately there isn't a way to do this currently, but I will look into adding it in an upcoming release.

**Comment by eamodio** [comment]
Added in 7.2
