### ISSUE TITLE
Show merge commits in file history

### ISSUE THREAD

**Issue by MarekLew** [eamodio/vscode-gitlens#238]
I don`t find merged commit in history view. 

- GitLens Version: 7.1.0
- VSCode Version: Code 1.19.1 (0759f77bb8d86658bc935a10a64f6182c5a1eeba, 2017-12-19T09:41:01.414Z)
- OS Version: Linux x64 4.10.0-42-generic

Steps to Reproduce:

1. Create repository
2. Add file, commit
2. create branch1
3. edit file, commit
4. go to master
5. create branch2
5. edit file,commit
6. merget branch1 to branch2
7. click `show in history view` in pane

At this moment I change in file git.{js|ts} in function `log_file` lines

```
- if (options.skipMerges || !options.ref || options.maxCount! > 2) {
+ if (options.skipMerges || options.maxCount! < 2) {
```

and it`s work fine for me.

but I don`t understand this logic when added  `params.push(`--no-merges`);` to `git` parameters.

**Comment by eamodio** [comment]
If you take this same repo and look at the history on GitHub does it show the merge commit?

**Comment by MarekLew** [comment]
Why GitHub? It`s local git repo. What do you want to say? 
I do not see all commit (merge commit) in current branch (or in other branch to).

**Comment by MarekLew** [comment]
```
marek@marek-XXX:~/xxxx$ git branch
  branch1
* branch2
  master
marek@marek-XXX:~/xxxx$ git log
commit 423bcd7a6ea3b97f8455c5ac49e98886caf2111a
Merge: f479a3b 3a61bea
Author: Marek Lewandowski <marek@testmail.com>
Date:   Mon Jan 1 17:31:42 2018 +0100

    change 3

commit f479a3b8e307c5dadeeee72fafcb31eaf58cc074
Author: Marek Lewandowski <marek@testmail.com>
Date:   Mon Jan 1 17:27:43 2018 +0100

    change 2

commit 3a61bea9fdee71ed856d8dc4b2ac4eb5d69d524a
Author: Marek Lewandowski <marek@testmail.com>
Date:   Mon Jan 1 17:26:32 2018 +0100

    change 1

commit f25cc2773b4414aa13a277c549366a156b67d062
Author: Marek Lewandowski <marek@testmail.com>
Date:   Mon Jan 1 17:25:14 2018 +0100

    change 0
marek@marek-XXX:~/xxxx$
```
when I use orginal extension:
![zrzut ekranu z 2018-01-01 18-24-17](https://user-images.githubusercontent.com/6560667/34469726-73f40ae4-ef25-11e7-851b-619f8bdb1e20.png)
![zrzut ekranu z 2018-01-01 18-24-11](https://user-images.githubusercontent.com/6560667/34469727-76b4e8c0-ef25-11e7-8a7b-0b7e86d82d01.png)
![zrzut ekranu z 2018-01-01 18-24-03](https://user-images.githubusercontent.com/6560667/34469730-7c371160-ef25-11e7-9da4-42046b049a00.png)

after correct code in extension I see:
![zrzut ekranu z 2018-01-01 18-20-47](https://user-images.githubusercontent.com/6560667/34469687-0386727e-ef25-11e7-8b25-66ac0e7cab35.png)
![zrzut ekranu z 2018-01-01 18-21-02](https://user-images.githubusercontent.com/6560667/34469689-04783046-ef25-11e7-85b7-9a8da6ef102d.png)
![zrzut ekranu z 2018-01-01 18-21-40](https://user-images.githubusercontent.com/6560667/34469692-087b196a-ef25-11e7-9068-7638b35ae8be.png)

show change in commits:
![zrzut ekranu z 2018-01-01 18-37-57](https://user-images.githubusercontent.com/6560667/34469810-908148e2-ef26-11e7-99b3-e6aba76c8c9a.png)
![zrzut ekranu z 2018-01-01 18-38-01](https://user-images.githubusercontent.com/6560667/34469811-90b09d2c-ef26-11e7-8c30-9a7249e4fd89.png)
![zrzut ekranu z 2018-01-01 18-38-04](https://user-images.githubusercontent.com/6560667/34469812-90d96bc6-ef26-11e7-8703-351b6037c3ee.png)
![zrzut ekranu z 2018-01-01 18-38-08](https://user-images.githubusercontent.com/6560667/34469813-9100e264-ef26-11e7-93c1-bae77e317e8c.png)

And file adnotation:

![zrzut ekranu z 2018-01-01 19-15-10](https://user-images.githubusercontent.com/6560667/34469969-65115eca-ef28-11e7-8444-7352929ca2b9.png)

**Comment by eamodio** [comment]
This is by design. For file histories I show a simplified version (which leaves out merge commits). Most of the Git tools I've used do the same as well as GitHub (see https://help.github.com/articles/differences-between-commit-views/).

Are you seeing a difference between the file history that GitLens shows vs another tool?

**Comment by MarekLew** [comment]
No it's not this ( https://help.github.com/articles/differences-between-commit-views/). Ignoring commits in another branch it`s not problem. 

Github don't show  merge commit in selecting History? I did not see that. Wher is that?

In the above example gitlens don't show `change 3` (merge commit)(it`s in branch2) for single file in EXLORER view wher branch2 is active.

![zrzut ekranu z 2018-01-01 18-24-03](https://user-images.githubusercontent.com/6560667/34469730-7c371160-ef25-11e7-9da4-42046b049a00.png)

I would rather see it:

![zrzut ekranu z 2018-01-01 18-20-47](https://user-images.githubusercontent.com/6560667/34469687-0386727e-ef25-11e7-8b25-66ac0e7cab35.png)

**Comment by MarekLew** [comment]
PS. `options.ref` in generated `git.js` for `show in history view ` procedure is `undefined`.

**Comment by eamodio** [comment]
Thanks -- I've dug into this a bit more, and see that GitHub does indeed show **some** merge commits in the file history, but GitKraken doesn't. In the next release, I will stop excluding merges and will instead have git simplify them (via --simplify-merges) and I believe this will be the behavior you desire.

Thanks for being persistent on this ;)

**Comment by eamodio** [comment]
@MarekLew If you'd like to try this out its in the latest [7.3 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.3.0-beta)
