### ISSUE TITLE
`gitlens.advanced.quickPick.closeOnFocusOut` setting should be reversed

### ISSUE THREAD

**Issue by mikolino** [eamodio/vscode-gitlens#239]
The option is documented as follows:

    gitlens.advanced.quickPick.closeOnFocusOut 	Specifies whether or not to close the QuickPick menu when focus is lost

This, to me, implies that if it is `true ` then the quickpick should close when it loses focus. But internally this option changes meaning to QuickPick*Ignore*FocusOut:

````
export function getQuickPickIgnoreFocusOut() {
    return configuration.get<boolean>(configuration.name('advanced')('quickPick')('closeOnFocusOut').value);
}
````

I think the option should be inverted internally to make more sense and fit the documentation.

**Comment by eamodio** [comment]
Nice catch -- fixed in 7.2
