### ISSUE TITLE
Debug breakpoints not visible in blame view (author history view) - Current commit area

### ISSUE THREAD

**Issue by ashishkushwaha** [eamodio/vscode-gitlens#24]
Thanks for making this awesome extension. I just noticed that in the blame view (author/commit history view), its not possible to see the breakpoints on the lines highlighted by the current commit.

The breakpoints are set and removed and work fine. Just that they are not visible because i think the commit line block visually overwrites the red break point circle.

Refer to the example image below - There are breakpoints on both line 82 and 83. But its only visible on 83.

![image](https://cloud.githubusercontent.com/assets/17152512/22345250/3d2263c6-e3b4-11e6-90d9-28261cd16580.png)

Its a small issue but really helps during the code review. I can easily see the changes made as a part of that commit and debug them as part of the code review.

**Comment by eamodio** [comment]
@ashishkushwaha could you provide some more information on why this is valuable? With the way vscode deals with the gutter is very simplistic -- so the only way I could not "conflict" with the breakpoints (or really any other gutter item) is to turn off any gutter changes at all. And that isn't really something I'm interested in doing.

**Comment by ashishkushwaha** [comment]
Thanks for looking at this. Its not that critical. The only reason i was looking for it was part of a code review I was doing. It was a pretty big JS file and as part of the code review, I wanted to run through the code and specifically set breakpoints only in the changes which were part of this commit. The author view helped in highlighted the current commit lines. But when i set up the break points, I couldn't see them at all.

Since this extension in any case highlights the entire line of that commit block, i think the gutter line can be removed/skipped maybe? Or can be moved to the right (in scroll area). But like i said, its not that big of a deal.

**Comment by eamodio** [comment]
@ashishkushwaha thanks for the info -- you've convinced me. I think I'll add a new setting for choosing the decoration for the selected blame lines -- something like, highlight, gutter, both

**Comment by ashishkushwaha** [comment]
Yup. That sounds like the best of both worlds solution. Appreciate it.
