### ISSUE TITLE
Broken "gitlens.blame.line.enabled" setting 

### ISSUE THREAD

**Issue by mafflin** [eamodio/vscode-gitlens#242]
"gitlens.blame.line.enabled" setting not working anymore

- GitLens Version: 7.5.1
- VSCode Version: 1.19.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Add setting "gitlens.blame.line.enabled": false,
2. Nothing happens. Option is not working.

**Comment by douglarek** [comment]
yeah, it is true, I got this too.

**Comment by WoodyWoodsta** [comment]
@douglarek That fix works for a while and then it seems to revert. Not sure what might be triggering the revert.

**Comment by douglarek** [comment]
@WoodyWoodsta yeah, you are right; so puzzled

**Comment by alex-bashkatov-ezlo** [comment]
seems reverted in 1 min for me too

**Comment by eamodio** [comment]
So sorry -- will be putting out a release as soon as I get this fixed (should be soon --- just woke up)

**Comment by eamodio** [comment]
Thank you all for your patience -- 7.5.2 has been pushed to the marketplace and should resolve this issue. Please let me know if not. Again sorry for the inconvenience!

**Comment by eamodio** [comment]
https://github.com/Microsoft/vscode/issues/15756 can't happen soon enough. Please upvote ;)

**Comment by alex-bashkatov-ezlo** [comment]
works like a charm from my side! Thanks for quick fix!

**Comment by NeoGenet1c** [comment]
If the configuration is being set for the first time ever, the problem persists (with `false` value).

Switching the value to 'true', reloading VSC and switching back to 'false' seems to make it work.
