### ISSUE TITLE
Consider using fewer default keybindings

### ISSUE THREAD

**Issue by sztomi** [eamodio/vscode-gitlens#244]
As a user of a non-English keyboard layout, I'm running into gitlens replacing key combinations that I otherwise use to enter essential characters, such as `;`, `*`, `{` etc. To get a sense, I'm pasting my keybindings.json here, of which a considerable chunk is just unbinding keys that gitlens keeps adding with each new version:

```
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "alt+cmd+w",
        "command": "gitlens.diffLineWithWorking",
        "when": "editorTextFocus && gitlens:isTracked"
    },
    {
        // don't steal ;
        "key": "alt+[Comma]",
        "command": "-gitlens.diffWithPrevious"
    },
    {
        "key": "alt+cmd+-",
        "command": "gitlens.showLastQuickPick",
        "when": "gitlens:enabled"
    },
    {
        // don't steal *
        "key": "alt+-",
        "command": "-gitlens.showLastQuickPick",
    },
    {
        "key": "f1",
        "command": "-workbench.action.showCommands"
    },
    {
        "key": "shift+cmd+t",
        "command": "workbench.action.terminal.focus"
    },
    {
        // don't steal &
        "key": "alt+c",
        "command": "-gitlens.showQuickCommitFileDetails",
    },
    {
        // don't steal {
        "key": "alt+b",
        "command": "-gitlens.toggleFileBlame"
    }
]
```

When such important keys are replaced it's very frustrating it takes a while to figure out why they don't work (especially when in the given context they don't show gitlens).

I think this can easily be a pain for various non-English layout users (I'm assuming here that the default keybinding are choosen such that they don't collide with English key combinations to enter those characters). In general, I think it would be wise for gitlens to simply not bind keys on its own and let users do it proactively, since it's not feasible to ship keybindings that are "good" and don't collide with any layouts. The command palette in vscode is great to discover and find commands.

**Comment by eamodio** [comment]
You can control the keybindings using the `gitlens.keymap` ([documentation](https://github.com/eamodio/vscode-gitlens#quick-access-settings)). You can easily unset all the keybindings by setting `"gitlens.keymap": "none"`, or you can change them from the default of using `alt` to using chorded keys by using `"gitlens.keymap": "chorded"`

Hope that helps.

**Comment by sztomi** [comment]
Thanks, that definitely helps. But I'm still arguing for a better (less invasive) default setting because you can't possibly *not* break each different keyboard layout.

**Comment by eamodio** [comment]
IMO this is a damned if you do vs. damned if you don't situation. The alternate keymaps are the best compromise I could think of.

**Comment by eamodio** [comment]
Closing this, as I don't feel there is really something actionable here.
