### ISSUE TITLE
gitlens.annotations.file.gutter.gravatars has no effect

### ISSUE THREAD

**Issue by pzelnip** [eamodio/vscode-gitlens#246]
- GitLens Version: 7.5.3
- VSCode Version: 1.19.2
- OS Version: OSX Sierra

Steps to Reproduce:

1. Set ```"gitlens.annotations.file.gutter.gravatars": true,``` in settings
2. Open up the file gutter, and no gravatars (I do see them in the hover tooltip though)

<img width="984" alt="screencapture" src="https://user-images.githubusercontent.com/414933/34965038-0de30bec-fa06-11e7-92b7-c82d25ff9064.png">

**Comment by eamodio** [comment]
I can't seem to reproduce this. Do you have any other extensions that add anything to the gutter? Can you post all your GitLens settings?

Here is a screenshot of what you should be seeing
![image](https://user-images.githubusercontent.com/641685/34975405-92d8980e-fa5f-11e7-83bc-358fe0d094e7.png)

**Comment by pzelnip** [comment]
Looks like that was it, I had another git-related extension installed that I had from before I found Gitlens.  Uninstalled that, and now is working as expected.

Thanks!  Awesome change BTW.
