### ISSUE TITLE
File annotations button or ESC key does not turn off file annotations

### ISSUE THREAD

**Issue by imoby** [eamodio/vscode-gitlens#247]
Issue Description: Click on the file annotations button after toggling the file lens view does not toggle it off again. Neither does hitting the escape key

https://d.pr/i/79WgnB/xc8EmkUbhY

- GitLens Version: Latest
- VSCode Version: Latest
- OS Version: MacOs

Steps to Reproduce:

1. Open file that has git history
2. Click on the file annotations git icon button on the top right of vscode
3. See that the file annotations are shown
4. Click on the button again or hit ESC key
5. Observe that the file annotations does not turn off

**Comment by eamodio** [comment]
Unfortunately I can't reproduce this. Does this happen all the time? Can you post your GitLens settings? Also can you please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

**Comment by imoby** [comment]
@eamodio Ok so here's what I've found even after reinstalling.

Below is my current git lens configuration:
`
    "gitlens.blame.line.enabled": false,
    "gitlens.codeLens.enabled": false,
    "gitlens.statusBar.enabled": false,
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressUpdateNotice": true,
        "suppressWelcomeNotice": false
    },    
    "gitlens.annotations.file.gutter.gravatars": false,
    "gitlens.resultsExplorer.gravatars": false,
    "gitlens.gitExplorer.gravatars": false
`

1. If I turn OFF 'any' one of these related to the gravatars, the button file annotation button doesnt work when I try to turn off the file annotations after turning it on, meaning I click on the button, it shows up, then clicking on it again doesnt hide it.
`
    "gitlens.annotations.file.gutter.gravatars": false,
    "gitlens.resultsExplorer.gravatars": false,
    "gitlens.gitExplorer.gravatars": false
`

2. However, even the overall issue with the escape button not turning off the file annotations is still a bigger issue that I cant get to work even by putting the gravatars configurations back on.

Here is the output in vscode:
`
Keyboard.beginScope 0
getBlameForFile[Not Cached(blame)]('/Users/muhamed.brifkani/project/mb-blog', '/Users/muhamed.brifkani/project/mb-blog/gatsby-config.js', 'undefined')
isTracked('/Users/muhamed.brifkani/project/mb-blog/gatsby-config.js', '/Users/muhamed.brifkani/project/mb-blog', 'undefined')
Add blame cache for '/users/muhamed.brifkani/project/mb-blog/gatsby-config.js:blame'
Running(/Users/muhamed.brifkani/project/mb-blog): git -c core.quotepath=false -c color.ui=false blame --root --incremental -- gatsby-config.js
Completed(/Users/muhamed.brifkani/project/mb-blog): git -c core.quotepath=false -c color.ui=false blame --root --incremental -- gatsby-config.js in 21 ms
Add listener registrations for annotations
3 ms to compute gutter blame annotations
User: Clear annotations for vs.editor.ICodeEditor:1,$model2
Remove all listener registrations for annotations
getBlameForFile[Cached(blame)]('/Users/muhamed.brifkani/project/mb-blog', '/Users/muhamed.brifkani/project/mb-blog/gatsby-config.js', 'undefined')
Add listener registrations for annotations
0 ms to compute gutter blame annotations
User: Clear annotations for vs.editor.ICodeEditor:1,$model2
Remove all listener registrations for annotations
getBlameForFile[Cached(blame)]('/Users/muhamed.brifkani/project/mb-blog', '/Users/muhamed.brifkani/project/mb-blog/gatsby-config.js', 'undefined')
Add listener registrations for annotations
1 ms to compute gutter blame annotations
User: Clear annotations for vs.editor.ICodeEditor:1,$model2
Remove all listener registrations for annotations
`

**Comment by eamodio** [comment]
I've been able to reproduce this now. Will get it fixed up as quickly as I can.

**Comment by eamodio** [comment]
This is fixed in 7.5.5 which should hit the marketplace very shortly. Thank you for your help in getting to the bottom of this!
