### ISSUE TITLE
Gitlens disappears from the status bar

### ISSUE THREAD

**Issue by jsnjack** [eamodio/vscode-gitlens#249]
- GitLens Version: 7.5.3
- VSCode Version:1.19.2
- OS Version:Fedora 27

Steps to Reproduce:

I want gitlens to show commit information only in the status bar. However, after latest updated, it disappeared. My settings are:
```
    "gitlens.blame.line.enabled": false,
    "gitlens.codeLens.recentChange.enabled": false,
    "gitlens.codeLens.authors.enabled": false,
    "gitlens.statusBar.command": "gitlens.showQuickCommitDetails",
    "gitlens.gitExplorer.enabled": false,
    "gitlens.statusBar.enabled": true,
```

If I set "gitlens.blame.line.enabled": true, it appears again. "gitlens.blame.line.enabled" settings should not affect gitlens.statusBar.enabled setting

**Comment by eamodio** [comment]
This will be fixed in 7.5.4 which should hit the marketplace very shortly. Sorry for the inconvenience!

**Comment by jsnjack** [comment]
Thank you for fixing it so quickly!

**Comment by jscheel** [comment]
This issue seems to be cropping up again.

**Comment by cyberbeast** [comment]
The issue still persists

**Comment by ironest** [comment]
The issue still persists

**Comment by eamodio** [comment]
@ironest In GitLens 11, all views have been moved to the Source Control side bar by default. You can move them back to the GitLens side bar via the _Set Views Layout_ (gitlens.setViewsLayout) command or individually via drag and drop
