### ISSUE TITLE
Blame information isn't updated after git operations (commit, reset, etc)

### ISSUE THREAD

**Issue by Glober777** [eamodio/vscode-gitlens#25]
Hi!

I've noticed that the 'Not Committed Yet' message keeps showing even after the change was committed.

GitLens Extension: 2.0.0
VSCode: 1.9.0

Thanks!

**Comment by eamodio** [comment]
@Glober777 Thanks for the report. Sadly code doesn't currently provide a way for me to detect that a file has been committed (at least not that I could find). I am investigating adding a timeout to my cache, so even though it will stick for a while it will resolve eventually. If you find this behavior bothersome you could also disable the GitLens cache by setting `gitlens.advanced.caching.enabled` to `false` (though performance could suffer).

**Comment by Glober777** [comment]
Hey @eamodio! I'm not familiar with the VSCode API, and what hooks are available there, but I was wondering if you could rely on "git diff" output (executed periodically or based on an event that VSCode may be raising every time commits happen). The simplest case would be if the output of git diff is blank, than consider everything as committed. Parsing its output, would help to figure out whether some new code is still staged or not.

**Comment by eamodio** [comment]
Opened https://github.com/Microsoft/vscode/issues/20845
