### ISSUE TITLE
Failures while updating the extension

### ISSUE THREAD

**Issue by sandy081** [eamodio/vscode-gitlens#250]
Hi,

As part of reducing extension failure rates, I am analysing the trend of extension failures reported to our telemetry database when users install/update extensions in VS Code. We use error codes and send them to our telemetry database to understand when an extension is failing while it is being installed. Once understanding the reasons behind the failures, we are fixing in VS Code if there are any thereby making extension installation better.

As part of this, I have seen that gitlens extension is failing majorly during updating, when we try to delete the extension folder with the same `name+version` as the extension being updated.

I would like to know if you are aware any failures or such related failures. It would be great if you can share that information so that we can improve it from our side.

**Comment by eamodio** [comment]
@sandy081 I am not aware of this at all. What kind of failures? It is an in-use file type of issue? How can I help fix them?

**Comment by sandy081** [comment]
@eamodio Here is the data related to gitlens extension update failures in last 7 days in insiders

![image](https://user-images.githubusercontent.com/10746682/35089708-0e377b58-fc38-11e7-92f5-a39b4d4b6436.png)

I categorise extension failures as follows:

- `GalleryFails`: When requests to market place fails
- `IncompatibleFails`: When user installs extension which is incompatible with his/her VS Code version
- `DownloadFails`: When downloading the vsix fails
- `DeletingFails`: Before extracting the vsix into a folder under extensions folder, I try to delete the folder if it exists. 
- `ExtractingFails`: When extracting the downloaded vsix into extensions folder
- `ValidateFails`: When reading the manifest from the disk and validating it
- `LocalFails`: When Reading the extracted extension or updating the metadata of extension back into disk.
- `UnknownFails`: Other unknown reasons

From the above pic, `gitlens` was updated around 10K times and update was failed only 454 times. Basically 4.5% failure rate is good. But, what worries me is the number of times (50% of failures) it failed while deleting the folder in the disk. 

To explain more about this failure, after downloading the new version vsix (say `eamodio.gitlens-1.2.1`) from the market place, I try to delete the folder `eamodio.gitlens-1.2.1` from the extension folder if it exists. Delete failures are those if deleting this folder fails. Theoretically, this is not supposed to happen because the newly updated version folder should not exist in the disk, otherwise the update will be never triggered.

So, would like to know if you have seen any such failures or if users reported such. Also any information about why this could happen with gitlens extension would be helpful.

Thanks

**Comment by eamodio** [comment]
@sandy081 I haven't heard of any issues -- I'm guessing the folder already existing is from people who are running beta versions? Also I do a TON of installing and uninstalling locally when testing -- am I excluded from that count?

**Comment by sandy081** [comment]
@eamodio I do not think you are excluded from the count and the telemetry data will not have user details except machineId. I cannot relate users to machine ids unless users share theirs.

**Comment by sandy081** [comment]
>I'm guessing the folder already existing is from people who are running beta versions

Hmm could be. But since we support beta versions from VS Code side, when user updates from beta version to new version (in market place), new version gets extracted into a folder that does not exist in the disk right?

**Comment by eamodio** [comment]
Ah yeah. In that case, is there a single machineid that is a large outlier compared to the rest?

**Comment by sandy081** [comment]
Unfortunately no. There is not single machine but several machines causing majority of such failures

**Comment by eamodio** [comment]
Hrm, nevermind vscode takes the whole version number in it. So unless I release an update with the same exact version number (which I don't do publicly, but do in my private testing with myself and at least 1 other user) it shouldn't exist. Do  you have any more insights into the actual versions (folders) that fail?

**Comment by eamodio** [comment]
I would know of 3-4 (2-3 of mine, 2 windows, 1 mac) and 1 of my friend's (a private beta tester), but outside of those I wouldn't expect any strange behavior. Are these all from insiders builds or both? I test with mainly insiders on all my machines but then switch to stable testing before a release. And my friend uses stable.

**Comment by sandy081** [comment]
Thanks a lot @eamodio for helping here by providing insights and information. 

After investigating more, I figured out that root cause is extension auto updates that triggers updating the same extension from all open windows. This can lead to failures while deleting the directory. Will provide the fix in VS Code for this.

Closing this.
