### ISSUE TITLE
could not view pull files and their changes

### ISSUE THREAD

**Issue by uc-saj** [eamodio/vscode-gitlens#251]
Can u integrate a feature where the user can see the pull request files and their incoming changes, as Eclipse IDE does.

**Comment by pzelnip** [comment]
I'd be interested in hearing more about this works in Eclipse, are you referring to this? https://eclipsesource.com/blogs/2012/08/28/tips-and-tricks-using-eclipse-with-github/

One extension you might find useful for VS Code is: https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-github as it's what I use for integrating VS Code with PRs on Github.

**Comment by eamodio** [comment]
I think GitHub specific features are best handled by another extensions. I want to keep GitLens agnostic to the Git provider used (and trying to create PR support for many different providers is just far too much work imo). If there are specific non-GitHub only features you'd like to see in GitLens, then by all means please list them.

FYI there is also https://marketplace.visualstudio.com/items?itemName=ms-vscode.github-issues-prs, but its PR support is sitting in a PR ;)

**Comment by eamodio** [comment]
Closing as more info is needed if there are specific features required.
