### ISSUE TITLE
Line status not color highlighted for files in git submodules

### ISSUE THREAD

**Issue by reneroth** [eamodio/vscode-gitlens#254]
- GitLens Version: 7.5.5
- VSCode Version: 1.19.2
- OS Version: MacOS 10.13.2

Steps to Reproduce:

1. Open a git repository with a git submodule
2. Edit a file in the submodule
3. Notice missing colored line indicator

File in base repo:
<img width="717" alt="screen shot 2018-01-19 at 13 29 27" src="https://user-images.githubusercontent.com/11065422/35151179-a5359932-fd1d-11e7-80c0-f876d297222a.png">

File in submodule of the same repo:
<img width="673" alt="screen shot 2018-01-19 at 13 29 11" src="https://user-images.githubusercontent.com/11065422/35151184-ac6b633a-fd1d-11e7-8b6d-d4c6663b95fb.png">

Thank you for this great extension!

**Comment by eamodio** [comment]
Hi! I'm not sure that colored indicator is provided by GitLens -- I think it might be an indicator provided by the built in vscode git extension. If you disable GitLens do you see the same behavior?

**Comment by eamodio** [comment]
It looks like you already opened an issue for this https://github.com/Microsoft/vscode/issues/41865

Can this be closed then?

**Comment by reneroth** [comment]
My bad, I thought this functionality was provided by GitLens! 🙈 sorry for the mixup

**Comment by eamodio** [comment]
No worries! Thanks!
