### ISSUE TITLE
Some branches fail to show history

### ISSUE THREAD

**Issue by Borkes** [eamodio/vscode-gitlens#257]
- GitLens Version:  v7.5.6
- VSCode Version: 1.19.2 (1.19.2)
- OS Version: macOs 10.13.2 (17C88)
![image](https://user-images.githubusercontent.com/20042707/35265135-39805796-005a-11e8-87f1-0157b58f6120.png)
I can see git log in these branches with sourceTree.

I don't know how to  reproduce, it occurs suddenly after my colleague merge hotfix/xx (sourceTree offer) branch and submit，but his git log is alright. And after update GitLens to v7.5.6,  the result is same as me, so I believe the bug belongs to v7.5.6

**Comment by eamodio** [comment]
Is this possibly a public repository? I can't reproduce the issue (so far), can you provide more details? Can you turn on logging and attach the logs after reproducing the issue? You can enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

**Comment by Borkes** [comment]
open master branch logs:

checkout:
```
RepositoryNode.onRepoChanged(repository); triggering node refresh
GitExplorer[view=repository].refreshNode
isTracked('/Users/borkes/workSpace/poker/app.js', '/Users/borkes/workSpace/poker', 'undefined')
Running(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false ls-files /Users/borkes/workSpace/poker/app.js
Completed(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false ls-files /Users/borkes/workSpace/poker/app.js in 12 ms
getBranch('/Users/borkes/workSpace/poker')
Running(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u}
Completed(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u} in 8 ms
getStatusForRepo('/Users/borkes/workSpace/poker')
Running(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false status --porcelain=v2 --branch -u
Completed(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false status --porcelain=v2 --branch -u in 18 ms
getBranches('/Users/borkes/workSpace/poker')
Running(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false branch -vv -a
Completed(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false branch -vv -a in 26 ms
```

open branch show logs
```
getLog('/Users/borkes/workSpace/poker', 'master', undefined, false)
Running(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false log --name-status --full-history -M --format=%x3c%x2ff%x3e%n%x3cr%x3e %H%n%x3ca%x3e %an%n%x3ce%x3e %ae%n%x3cd%x3e %at%n%x3cp%x3e %P%n%x3cs%x3e%n%B%x3c%x2fs%x3e%n%x3cf%x3e -m -n200 master
Completed(/Users/borkes/workSpace/poker): git -c core.quotepath=false -c color.ui=false log --name-status --full-history -M --format=%x3c%x2ff%x3e%n%x3cr%x3e %H%n%x3ca%x3e %an%n%x3ce%x3e %ae%n%x3cd%x3e %at%n%x3cp%x3e %P%n%x3cs%x3e%n%B%x3c%x2fs%x3e%n%x3cf%x3e -m -n200 master in 386 ms
```
you can download a [sourceTree](https://www.sourcetreeapp.com/),  create a hotfix branch in Repository, merge the hotfix branch and delete it after commit. 
And I think it's just one way to reproduce,  there is a public [repository](https://github.com/heyongchenghithub/mqtt_im) (please ignore the content), I can't open master branch using GitLen as well.

**Comment by eamodio** [comment]
Thank you so much for the repository that reproduces it. I should be able to get this fixed up soon!
