### ISSUE TITLE
Add tree-like layout to branches

### ISSUE THREAD

**Issue by Yukaii** [eamodio/vscode-gitlens#258]
- GitLens Version: 7.5.6
- VSCode Version: 1.19.2
- OS Version:

It' common to recognize branch name before `/` as folder name. In SourceTree:

![screen shot 2018-01-25 at 8 49 02 am](https://user-images.githubusercontent.com/4230968/35365475-c6a1daae-01af-11e8-833b-cc23cad6654d.png)

GitLen:

![screen shot 2018-01-25 at 8 48 14 am](https://user-images.githubusercontent.com/4230968/35365483-d0549d52-01af-11e8-82a0-f2b83e8e0d5d.png)

BTW, GitLen is absolute a great work!

**Comment by eamodio** [comment]
Awesome suggestion! Thanks!

**Comment by Yukaii** [comment]
I can't wait to see this feature, so I just made it 😂 

![screen shot 2018-01-25 at 7 03 52 pm](https://user-images.githubusercontent.com/4230968/35385247-a38d9dde-0202-11e8-8ace-3f4abf96853e.png)

It's a prototype now, and I would submit a PR when it's ok 😸
