### ISSUE TITLE
Active line annotation doesn't disappear properly after delete

### ISSUE THREAD

**Issue by innerlee** [eamodio/vscode-gitlens#26]
originally, like this, cursor placed at end of line 13.

![screenshot_2017-02-07_20-32-06](https://cloud.githubusercontent.com/assets/9464825/22691296/c1659490-ed74-11e6-935b-a3dac94ab69f.png)

press ``del`` key. the next line will move up. however, the display is not correct.

![screenshot_2017-02-07_20-32-38](https://cloud.githubusercontent.com/assets/9464825/22691297/c16aac5a-ed74-11e6-9329-8905504dd447.png)

display will become correct once you move cursor elsewhere.

![screenshot_2017-02-07_20-33-02](https://cloud.githubusercontent.com/assets/9464825/22691298/c16bc8d8-ed74-11e6-9a51-0c1cd7bd8698.png)

**Comment by eamodio** [comment]
@innerlee Thanks for the report -- I will look into it. It shouldn't even still be displaying once you start editing (since I found it distracting when you are typing).

**Comment by eamodio** [comment]
Fixed in v2.0.1
