### ISSUE TITLE
Unable to open compare. The file is probably not under source control

### ISSUE THREAD

**Issue by tiansin** [eamodio/vscode-gitlens#261]
- GitLens Version:7.57
- VSCode Version:1.9.3
- OS Version:win10

Steps to Reproduce:

1.
![2](https://user-images.githubusercontent.com/4232281/35428034-cecd4b8e-02a7-11e8-91f5-99bfc03df640.jpg)

2.
![1](https://user-images.githubusercontent.com/4232281/35428036-d2569e68-02a7-11e8-8b22-cda8045ed481.jpg)

After updating the problem, this file is in the sub-module.
Only this document relies on failure.
Other documents normal.

**Comment by eamodio** [comment]
What are you trying to do when you get that message?

Also the message in the title says *Unable to open compare*, but your screenshot is *Unable to file history* -- do both have issues?

**Comment by tiansin** [comment]
An existing file in version control notifying me that I was not in version control and could not be compared
![gif](https://user-images.githubusercontent.com/4232281/35429545-7ac977b2-02af-11e8-9049-e65a59ac0c10.gif)

**Comment by eamodio** [comment]
And this was working in 7.5.6?

**Comment by tiansin** [comment]
I downgraded the test, 7.56 version of the perfect work
![7 56](https://user-images.githubusercontent.com/4232281/35430323-bc8fa07e-02b2-11e8-8999-3ecf7839f81a.gif)

**Comment by eamodio** [comment]
Thank you for checking in the previous version. Can I ask one more favor? Please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

Thanks!

**Comment by tiansin** [comment]
[gitlens.log](https://github.com/eamodio/vscode-gitlens/files/1667210/gitlens.log)
Hope it helps.

**Comment by eamodio** [comment]
@tiansin did you intentionally close this? Did the issue go away?

**Comment by eamodio** [comment]
@tiansin sorry for this issue -- it should be resolved in 7.5.8

**Comment by tiansin** [comment]
Sorry, I have more information about my computer in my uploaded log file.
Thank you for your attention to this issue, I tested 7.58 has been the perfect solution to this defect
