### ISSUE TITLE
Visibility in side bar

### ISSUE THREAD

**Issue by petersykim** [eamodio/vscode-gitlens#264]
Hi, I temporarily hid gitlens side bar in explorer and see no option to make it visible again.  What am I missing here?

**Comment by eamodio** [comment]
You can turn it back on by right-clicking next `Explorer` at the top of the side bar -- it will open a menu you can you re-enable GitLens. Unfortunately once you hide something from the side bar, an extension can't do anything about it.

See https://github.com/Microsoft/vscode/issues/31485

**Comment by petersykim** [comment]
How did I miss that!  Thanks!

**Comment by aroraayush** [comment]
I wasn't able to get GitLens in the  top of the side bar. 
What worked for me was pressing Cmd+Shift+P on my mac and choosing 
Gitlens: Show File History Explorer.

Hope this helps to other people who couldn't get their issue resolved by above mentioned comments

**Comment by thisentirecitymustbepurged** [comment]
To anyone who had it disappear recently on code-insiders sidebar, just downgrade it to a version that works, I went with 10.2.2. 
![image](https://user-images.githubusercontent.com/20511483/99971239-d1035b80-2d94-11eb-9467-e1d8d5852ba1.png)

**Comment by eamodio** [comment]
This was an intention default change in GitLens 11. You can change back to having all the views be on the GitLens side bar by using the _Set Views Layout_ command.

1. Open Command Palette (CMD + SHFT + P)
1. Search GitLens: Set Views Layout
1. Select GitLens Layout

You can also just drag and drop views individually to place them anywhere you'd like.

**Comment by WebMax6** [comment]
And for window it's just (CTRL + SHFT + P)

**Comment by noamgot** [comment]
Just encountered this issue after Gitlens disappeared from the sidebar. Well, it's not a bug - it's a feature!
There a message that pops up after the update and explains this.
All the goodies are now in the source control menu (look at the bottom of the image):
![image](https://user-images.githubusercontent.com/22060133/103274592-b4c59080-49ca-11eb-83d2-e3c262258db3.png)
If you still want to change this - use eamodio's solution above.

**Comment by harshilparmar** [comment]
> 
> 
> This was an intentional default change in GitLens 11. You can change back to having all the views be on the GitLens side bar by using the _Set Views Layout_ command.
> 
>     1. Open Command Palette (CMD + SHFT + P)
> 
>     2. Search GitLens: Set Views Layout
> 
>     3. Select GitLens Layout
> 
> 
> You can also just drag and drop views individually to place them anywhere you'd like.

Thank you so much 😁😁
