### ISSUE TITLE
Wrong time in Popup

### ISSUE THREAD

**Issue by robertzauner** [eamodio/vscode-gitlens#266]
the popup shows the wrong time. It is always of the form x.01am / pm

![gitlensii](https://user-images.githubusercontent.com/6860326/35557291-f649d3da-05a4-11e8-87c1-d9702b6ae1cb.JPG)
![gitlens](https://user-images.githubusercontent.com/6860326/35557279-f13c8afe-05a4-11e8-819e-6afc8c5606ea.JPG)
![Uploading gitlensII.JPG…]()

- GitLens Version: [7.5.7] - 2018-01-25
- VSCode Version: 1.19.3
- OS Version: Win10

**Comment by eamodio** [comment]
Great catch! I can't believe how long that has been broken for -- in the date format it was using `MM` rather than `mm` for the minute, so it was always putting in the month! ;)

**Comment by robertzauner** [comment]
No one delivering such a great tool is an idiot ;-)
