### ISSUE TITLE
Add support for custom remotes with split project/repo url structure

### ISSUE THREAD

**Issue by atlanteh** [eamodio/vscode-gitlens#267]
Hi guys, Awesome extension!!
Hi have a question\feature request..

Our organization has a git server that works as follows:
The clone URL:
```ssh://git@DOMAIN/someProject/someRepo.git```

However to browse the files we need to access:

```https://DOMAIN/projects/someProject/repos/someRepo```

Is there a way to support this kind of behavior?

**Comment by eamodio** [comment]
This should be supported today. You can use the [`gitlens.remotes` setting](https://github.com/eamodio/vscode-gitlens#custom-remotes-settings)

Hope that helps.

**Comment by atlanteh** [comment]
I already looked at it, but you guys identify the someProject/someRepo as the repo name and we can't add stuff in the middle, can we?

**Comment by eamodio** [comment]
Ah, unfortunately that isn't possible today. I will add that to the next release.

**Comment by eamodio** [comment]
In 7.5.10 there are 2 new tokens that can be used in the [`gitlens.remotes` setting](https://github.com/eamodio/vscode-gitlens#custom-remotes-settings)
