### ISSUE TITLE
[Feature Request] Review mode: highlight additions/deletion of a remote branch

### ISSUE THREAD

**Issue by batisteo** [eamodio/vscode-gitlens#268]
I’d like to see an easy way to see the diff of a (remote) branch compared to develop/master.

It would be just like the Pull Request view in Github/Bitbucket/Gitlab but within VScode.
Highlight would be similar to the (staged) changes is stock VScode.

**Comment by eamodio** [comment]
This is supported currently. Using the *GitLens* view you can right-click on any branch (remote branch, commit, tag, etc) and compare it to any other. So in your case you can select the remote branch you want to compare and select `Select for Compare` and then select the branch you want to compare it to and right-click and select `Compare with Selected`.

There are also other quick compare commands:
 - Use `Compare with Remote` to compare the selected branch with its remote 
 - Use `Compare with Index (HEAD)` to compare the branch to the HEAD of the current branch
 - Use `Compare with Working Tree` to compare the branch to the working tree

All of the above commands will open the *GitLens Results* view to allow you to drill down into the details of the comparison.

Hope that helps.

**Comment by eamodio** [comment]
@batisteo Does this meet your needs? Can this issue be closed?

**Comment by batisteo** [comment]
Sorry, yes, I tried, thank you!
It works, but it would need a better UX for this workflow.
But that’s another issue, and I’m too lazy to think about it atm 🙂
