### ISSUE TITLE
GitLens is not starting (or so it seems)

### ISSUE THREAD

**Issue by joaomath** [eamodio/vscode-gitlens#269]
- GitLens Version: 7.5.9
- VSCode Version: 1.19.2
- OS Version: Linux Mint  18 Cinnamon 64-bit

Steps to Reproduce:

1. Open VS Code while GitLens is enabled.

I don't know if this is specific for the project i'm working on, but in this project, and **only** in it, the extension doesn't work. I've already searched for answers, but found nothing. Also tried uninstalling and installing again the extension, etc., and nothing. The issue is simple, once i open VS Code on the said project (which is an angularjs one), the extension doesn't load.

The output shows only this:
```
Git found: 2.7.4 @ /usr/bin/git in 28 ms
Running(/home/joaomatheus/www/mf): git rev-parse --show-toplevel
GitLens(v7.5.9) activated in 84 ms
Completed(/home/joaomatheus/mf): git rev-parse --show-toplevel in 170 ms
```
In the projects that GitLens is working, the output is much bigger, seems like the extension "dies" while loading. Also, the Git button on top of the screen doesn't appear.

Sorry for the post not following the steps to reproduce, but there are really no steps at all, it simply doesn't work.

Thanks for the job on the extension, it is really good, and looking forward to a solution.

**Comment by eamodio** [comment]
If you open up the developer tools (can use the *Toggle Developer Tools* command in the palette) is there any errors in the console? Is the repository with the issues public? Is there anything that you can think of that is special about this repository? Is there a submodule? Anything else?

**Comment by eamodio** [comment]
Can you try this version? Just rename it back to `gitlens-7.5.10-beta.vsix`. I added some more logging and a bit of timing protection. Please  let me know if this helps and if not please attach new logs. Thanks!

[gitlens-7.5.10-beta.zip](https://github.com/eamodio/vscode-gitlens/files/1678775/gitlens-7.5.10-beta.zip)

**Comment by joaomath** [comment]
Thank you @eamodio 

I'll give it a try and collect some more info about the problem.

**Comment by joaomath** [comment]
@eamodio i did as you asked and in the console i got an EACCES:

```
 ERR EACCES: permission denied, scandir '/home/joaomatheus/www/mf/build': Error: EACCES: permission denied, scandir '/home/joaomatheus/www/mf/build'
```
This folder is created with permissions for other users only, by default. So i chmod'ed it, and then reloaded VSCode window, and then the extension worked. So the problem was in the permission. Is there any workaround?

**Comment by eamodio** [comment]
Since GitLens will spawn git as the same user that ran vscode all the permissions will be enforced by the system for that user. There isn't anything GitLens can do.

Glad it is resolved though!

**Comment by joaomath** [comment]
Understood. Thank you very much for the assistance, sir!
