### ISSUE TITLE
Annotations broken in insider build

### ISSUE THREAD

**Issue by killercup** [eamodio/vscode-gitlens#27]
Just installed 2.0.1 of this extension in the latest insider build (from this morning) and every one of the three annotations styles is broken in some way. (Also not the escaped bytes like `\0`.)

Is this a regression in vscode or some other extension that messes this up? It worked perfectly last week with a pre-2.0 version (and an earlier insider build). Sorry to not have more information on this.

![compact](https://cloud.githubusercontent.com/assets/20063/22729681/16e07b8c-ede4-11e6-806d-0b2472e8e4e6.png)

![expanded](https://cloud.githubusercontent.com/assets/20063/22729684/1703d41a-ede4-11e6-81f8-912deb46619c.png)

![trailing](https://cloud.githubusercontent.com/assets/20063/22729682/17008e68-ede4-11e6-987b-c0d9abff996d.png)

**Comment by pdanpdan** [comment]
Hello. Same issue here.
GitLens 2.0.1 / VSCode 1.10.0-insider

**Comment by eamodio** [comment]
This is an issue in vscode -- I opened an issue here. https://github.com/Microsoft/vscode/issues/20137 Feel free to upvote it ;)

**Comment by eamodio** [comment]
I've identified that commit that broke it in vscode -- hopefully a fix will come shortly. In the meantime I just pushed v2.0.2 that adds control over some of the blame annotation characters.

You can add the following for now to get around this issue until the vscode issue is fixed.

```
    "gitlens.blame.annotation.characters.ellipse": "...",
    "gitlens.blame.annotation.characters.indent": "|",
    "gitlens.blame.annotation.characters.padding": ".",
    "gitlens.blame.annotation.characters.separator": "*",
```
