### ISSUE TITLE
Add link to repo in README

### ISSUE THREAD

**Issue by ffes** [eamodio/vscode-gitlens#270]
A fairly simple request: Please add a link in the README to this GitHub repo.

It may sound a bit strange, but remember that the README is also shown inside VS Code when you (pre)view the extension. So having a direct link in VS Code to this repo is useful.

**Comment by eamodio** [comment]
When GitLens 8 comes out (hopefully in the near-ish future) there will be a link in the README, but just so you know, vscode adds the repository link in the header section:

![image](https://user-images.githubusercontent.com/641685/35662129-775fff68-06e4-11e8-90b2-edaf6a23db6e.png)

**Comment by ffes** [comment]
> but just so you know, vscode adds the repository link in the header section

That is a new feature that must have been added recently and I missed. Sorry for the noise.

**Comment by eamodio** [comment]
No worries at all! 😄

**Comment by ffes** [comment]
Quick related question: I assume it gets the info from `package.json`?

**Comment by eamodio** [comment]
Correct
