### ISSUE TITLE
[Request] Better block and container detection (for Golang)

### ISSUE THREAD

**Issue by kwiesmueller** [eamodio/vscode-gitlens#271]
Hey,
I am currently trying out gitlens.
While browsing through the settings I found a lot of stuff and to be honest, the defaults are quite spammy (too much stuff shown/enabled).

Now, I am getting a lot of gitlens chatter in my go files:
https://i.imgur.com/qjnX2Us.png
This is with 
```
"gitlens.codeLens.locations": [
        "document",
        "containers"
    ]
```
When changing to blocks, those don't get correctly as well.
I am not sure if this is a golang syntax issue, but I guess so.
Any suggestions?

**Comment by eamodio** [comment]
It is likely something that would need to change in the golang language service -- but let's check something first. Can you turn on `"gitlens.codeLens.debug": true` (or `"gitlens.debug": true` if you are using the 8.0 beta) and send me the same screenshot? That will show what the language service is returning as the symbols.

**Comment by kwiesmueller** [comment]
I just enabled debug on my mac and enabled all location options. Could not reproduce the problem in any file.
I think I made the report on my Windows machine and will try there this evening, but it then might be related to this.

**Comment by eamodio** [comment]
I'm going to close this, please re-open if this is still an issue. Thanks!
