### ISSUE TITLE
Status bar blame message flicker

### ISSUE THREAD

**Issue by mikolino** [eamodio/vscode-gitlens#272]
When changing lines in a document (with the mouse or the arrow keys) the status bar blame message flickers while it's loading the new one.

This is somewhat distracting, wouldn't it be possible to leave the status bar message as is until the new text is ready to replace it ?

Thank you

- GitLens Version: 8.0.0
- VSCode Version: 1.19.3
- OS Version: Windows 8.1

Steps to Reproduce:

1. Enable statusbar blame display
2. Move the cursor around

**Comment by eamodio** [comment]
Although I like the behavior of clearing the outdated information while you are changing lines (it is more accurate), I can certainly see the desire to not want the flicker. So in the next release, there will be a new setting `"gitlens.statusBar.reduceFlicker": true|false` which will trade immediate accuracy for less flickering.

**Comment by mikolino** [comment]
Thank you for reacting so fast to user feedback, it is very much appreciated!
