### ISSUE TITLE
[Request] Revert selected change

### ISSUE THREAD

**Issue by sergeome** [eamodio/vscode-gitlens#273]
Hello.

First of all, thank you a lot for your work and this great extension.

I would like to ask a question. Personally me and other colleagues from my work really missing a feature "revert selected change". 
Is this possible to add it?

Here's an example of what I mean:
![alt-text](https://media.giphy.com/media/xUOwG1PWf2PEruXPgI/giphy.gif)

I'm really sorry if it does exist, but I spent some time with it + read the docs and couldn't find that functionality. Thank you!

**Comment by eamodio** [comment]
Unfortunately the vscode api doesn't support the ability to do anything like that currently -- I would love that feature myself.

While the UI for these feature doesn't exist vscode does have commands to stage/unstage/revert selected lines

![image](https://user-images.githubusercontent.com/641685/35944339-0bd5a446-0c2a-11e8-901c-f229b17c7315.png)

Hope that helps

**Comment by datocrats-org** [comment]
I used the response to advise me in how to move between changes that I want to revert more quickly. 
 I submitted a related feature request to vscode am not sure if it qualifies as a bug or not but seems to be related to that API limitation you mention https://github.com/microsoft/vscode/issues/75098
