### ISSUE TITLE
TextEditor is closed/disposed occurs when this extension is enabled

### ISSUE THREAD

**Issue by sean-mcmanus** [eamodio/vscode-gitlens#274]
Version 8.0.0 on Linux with Visual Studio Code Insiders (not the non-Insiders).

See https://github.com/Microsoft/vscode/issues/42827 .

I get this error when switching between 2 text documents when I have GitLens enabled.

I initially thought it was a bug with our cpptools extension.

It looks like GitLens is doing some operation on a text editor that is no longer available. I think a setDecorations.

**Comment by eamodio** [comment]
Thanks for the report! This will be fixed in the next release.
