### ISSUE TITLE
Expand results in GitLens Results view

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#275]
An improvement for Compare working copy to merge-base #240 would be to have a quick way to expand the results. For example, if there are 20 files changes in various directories between my `feature-branch` and a `master`, right now I need to expand the results one by one.

**Comment by eamodio** [comment]
Going to hold off on implementing this until https://github.com/Microsoft/vscode/issues/30288 get flushed out. I don't want to hack implement something, if the api support is coming.

**Comment by eamodio** [comment]
Depends on https://github.com/Microsoft/vscode/issues/55879
