### ISSUE TITLE
Lookup for branches without upstreams fails

### ISSUE THREAD

**Issue by diablodale** [eamodio/vscode-gitlens#276]
## Setup

Windows 10 build 17074
VS Code x64 v1.20.0
Git for Windows x64 v2.16.1.windows.1
GitLens 8.0.0 appropriately installed with VS Code

## Repro

1. Run VS Code
2. Make a local git repository with no upstream/remotes
3. Add and commit several files.
4. Edit and commit changes for several files to create histories for files.
5. Edit one of the files with a history
6. Save the file.
7. Click the Source Control icon in the left nav
8. Click the file you edited in 5. to show the diff
9. Right click on a line that is different
10. Choose Show File History

## Result

In the dropdown at the top that appears, there is an error on the second line:
`Show Branch History - shows 🌿 Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u} history`

![image](https://user-images.githubusercontent.com/679350/35985653-6b905d90-0cf7-11e8-89ad-b953ac9b94cd.png)

## Expected

No error.

## Notes

This might be related to https://github.com/eamodio/vscode-gitlens/issues/257

Here is the output from the debugging channel which appears related
```
getStatusForRepo('c:/Users/Dale/Documents/ops/home')
Running(c:/Users/Dale/Documents/ops/home): git status --porcelain=v2 --branch -u
getBranches('c:/Users/Dale/Documents/ops/home')
Running(c:/Users/Dale/Documents/ops/home): git branch -vv -a
Error(c:/Users/Dale/Documents/ops/home): C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u})
    (128) Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u}
fatal: no upstream configured for branch 'master'

fatal: no upstream configured for branch 'master'

Completed(c:/Users/Dale/Documents/ops/home): git rev-parse --abbrev-ref --symbolic-full-name @ @{u} in 88 ms
getBlameForLine('c:/Users/Dale/Documents/ops/home', 'c:\Users\Dale\Documents\ops\home\pinentry.sh', 'undefined', 139)
getBlameForFile[Cached(blame)]('c:/Users/Dale/Documents/ops/home', 'c:\Users\Dale\Documents\ops\home\pinentry.sh', 'undefined')
Completed(c:/Users/Dale/Documents/ops/home): git blame --root --incremental -- pinentry.sh in 122 ms

```

**Comment by eamodio** [comment]
Awesome bug report! Thank you. This will be fixed in the next release.

**Comment by theSoenke** [comment]
I'm still seeing this error in Gitlens 8.1. I just took a look at your commit and noticed that your are checking for the errors in English. In my case the Git errors are in German. Do you think there is a workaround to support other languages?

**Comment by eamodio** [comment]
If you add `LC_ALL=C` before a git command does the output use English?

**Comment by theSoenke** [comment]
Yes, that works. Sounds like this could be a good solution by running git always with `LC_ALL=C`

**Comment by eamodio** [comment]
Awesome, I'll release a patch soon with that set in the env that I run git commands in. Thank you for the report and the help testing!

**Comment by diablodale** [comment]
@theSoenke , what is your environment? Are you in a Windows environment as I described in my original post?

I ask because LC_ALL is a very *nix approach to set a locale. In Win32 it is done in a different way.
As a test to see if LC_ALL will override locale on Windows, I

1. used my environment as in original post
2.  `set LC_ALL=de_DE.UTF-8`
3. changed directory to a non-git directory
4. ran `git rev-parse --`

**_Result_**
My output was in english. I did not get the expected German output.

This suggests to me that in Win32, the `LC_ALL` env variable can not be used to set locale. That approach only works in *nix-like environments.

**Comment by eamodio** [comment]
Damn, I'll have to dig more into how I can force English on windows too.

**Comment by diablodale** [comment]
I may be wrong. I *love* learning. The official issue tracker for Git for Windows https://github.com/git-for-windows/git/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+LC_ALL+ points to frequent use of `LANG` and `LC_ALL` env variables. However in https://github.com/git-for-windows/git/issues/724 is written that the git for windows installer doesn't install localization files. That may be why I can not force mine to German with the variables.

Since the standard install of Git for Windows doesn't have anything but "C" English, and you set the LC_ALL variable, this is likely a non-issue.

Sorry for any unneeded investigation.

**Comment by eamodio** [comment]
@diablodale No worries at all, and thank you SO much for the investigation. Honestly I should have tried to force a language on Windows before shipping it 😉 

Given the above I'm going to close this until someone comes across this fix not working.

Thanks again!
