### ISSUE TITLE
Broken "gitlens.currentLine.enabled" setting

### ISSUE THREAD

**Issue by johnbillion** [eamodio/vscode-gitlens#277]
Previously: #242

It appears that this problem has reappeared with version 8 of GitLens. The setting is now named `gitlens.currentLine.enabled` and appears to have no effect. The status bar blame information shows up regardless of this setting. The "Toggle Line Blame Annotations" command hides this temporarily, until a reload occurs.

**Comment by eamodio** [comment]
Hi -- the status bar information is controlled by `gitlens.statusBar.enabled`. If you open the *GitLens Settings* editor via *GitLens: Open Settings* from the command palette. There is a WYSIWYG editor which should make it easy to configure just the settings you want.

Hope that helps.

**Comment by johnbillion** [comment]
Thanks! My mistake.
