### ISSUE TITLE
"Compare selected ancestor with working tree" needs "select for compare"

### ISSUE THREAD

**Issue by Mellbourn** [eamodio/vscode-gitlens#279]
- GitLens Version: 8.0.0
- VSCode Version: 1.20.0
- OS Version: MacOS 10.13.3

I'm not sure I understand how "Compare selected ancestor with working tree"  is supposed to work.

The only way I can get it to show up is by first doing "select to compare".
And only if I choose my current branch does the result of "Compare selected ancestor..." make sense to me.
Shouldn't "Compare selected ancestor..." work without first doing "select for compare", implicitly choosing the current branch for the merge-base calculation?

**Comment by borekb** [comment]
Agree with this feedback. The functionality is great, basically removing the need for [git-tree-compare](https://marketplace.visualstudio.com/items?itemName=letmaik.git-tree-compare), but the discoverability and usability is not that great, IMO, in GitLens 8.0.

For reference, the issue where the feature was introduced, is: Compare working copy to merge-base #240

**Comment by borekb** [comment]
Regarding 266b43b, "Compare Ancestry with Working Tree" still feels a bit weird to me. For example, it's not obvious to me what "ancestry" means, exactly, and also, I'd like to compare my _branch_ with the base, not the uncommitted changes in my working directory.

Simplest label from my point of view would be "Compare current branch with `master`" – that says exactly what I want to do. The base branch would need to be selectable I believe, which is discussed in #293.

**Comment by eamodio** [comment]
@borekb I feel like these are 2 separate operations -- *Compare Ancestry with Working Tree* is to compare the common ancestry of the selected branch and the current branch's working tree. While what you are suggesting exists as *Compare with Index (HEAD)* if you select the `master` branch.

Does that make sense?

**Comment by borekb** [comment]
No, what I'm after is a GitHub PR style diff, i.e., HEAD (most recent branch commit) vs. common ancestor with my "base branch" (usually master).

It's all a bit confusing, the use cases and terminology should probably be reviewed. Currently, I see these options when I right-click the current branch:

![image](https://user-images.githubusercontent.com/101152/37273592-934dbaac-25da-11e8-964f-535698044fc0.png)

There are many "compares" there but I don't think there is a single one that does GitHub PR-style diff, is there?

I think it's very common to want to know the answer to the questions "what did change in this branch"?

**Comment by eamodio** [comment]
@borekb I opened https://github.com/eamodio/vscode-gitlens/issues/309 to discuss this more, please let me know your thoughts. Thanks!
