### ISSUE TITLE
Feature request: Copy commit hash to clipboard

### ISSUE THREAD

**Issue by rhys-vdw** [eamodio/vscode-gitlens#28]
Hey there, loving the plugin.

I'm really missing some way to copy the commit hash on the blame annotation to the clipboard. A keyboard command is a possibility, but just adding the option the context menu would be sufficient.

**Comment by eamodio** [comment]
@rhys-vdw that is an excellent suggestion! Thanks! Look for that in the next release :)

**Comment by rhys-vdw** [comment]
🙌

**Comment by rhys-vdw** [comment]
Thanks again! Such convenience.
