### ISSUE TITLE
How to disable blame messages?

### ISSUE THREAD

**Issue by jplew** [eamodio/vscode-gitlens#280]
- GitLens Version: v8.0.0
- VSCode Version: 1.19.3
- OS Version: Mac OS X 10.12.6

In the previous version of GitLens, I could completely turn off blame messages with this setting:

`"gitlens.blame.line.enabled": false`

In v8.0.0, however, that is underlined with an `Unknown Configuration Setting` warning. What is the equivalent setting in v8?

I tried `"gitlens.blame.format": ""` but that doesn't work, it still displays a message.

**Comment by jplew** [comment]
Never mind, I found it in the docs. here is the new setting:

`"gitlens.currentLine.enabled": false`

**Comment by eamodio** [comment]
FYI, GitLens 8 has a wysiwyg settings editor which makes it simple to configure things as you'd like
