### ISSUE TITLE
[Nice to Have] Attach gifs to changelogs

### ISSUE THREAD

**Issue by canda** [eamodio/vscode-gitlens#282]
You added some awesome changelogs to the extension, it would be nice to have a gif or screenshots explaining what you are talking about when announcing new features

**Comment by eamodio** [comment]
Good call - I've done it a couple of times in the past, but you are right -- I should do it more often.

**Comment by eamodio** [comment]
I'm going to close this -- as it isn't really actionable immediately, rather I will try to do more of it going forward.
