### ISSUE TITLE
Add delay option for blame hovers

### ISSUE THREAD

**Issue by ffxsam** [eamodio/vscode-gitlens#283]
- GitLens Version: 8.0.0
- VSCode Version: 1.20.0
- OS Version: macOS 10.13.3

It would be nice to have an option to specify a delay in milliseconds before the blame hover pops up. It's always too quick, and gets in the way of my typing.

**Comment by eamodio** [comment]
Unfortunately vscode doesn't provide any facility to control that, so there really isn't any that GitLens can do itself.

While this is probably not what you'll want, there is an option in vscode to turn off all hovers: `"editor.hover": false` (its a hidden setting). Then you can use the `Show Hover` command (`Ctrl+K, Ctrl+I) to open a hover at the current cursor position.
