### ISSUE TITLE
what is the new option to turn off line blame?

### ISSUE THREAD

**Issue by intijk** [eamodio/vscode-gitlens#284]
I found that this option was no longer there
```
    "gitlens.blame.line.enabled": false,
```
Could you tell me the new way to turn off the line blame ?

**Comment by eamodio** [comment]
`"gitlens.currentLine.enabled": false`

FYI GitLens 8 has a whole WYSIWYG settings editor built in. You can open it from the command palette *GitLens: Open Settings* 😄

**Comment by eamodio** [comment]
Also curiously -- was the setting not migrated properly? It should have been.

**Comment by mustafawm** [comment]
Hi @eamodio 
No the setting was not migrated properly. 

The WYSIWYG is awesome.

**Comment by jabacchetta** [comment]
Replacing `gitlens.blame.line.enabled` with `gitlens.currentLine.enabled` worked perfectly.

**Comment by eamodio** [comment]
The setting migration should now work in 8.0.1 -- sorry about that 😢

**Comment by can-artuc** [comment]
> `"gitlens.currentLine.enabled": false`
> 
> FYI GitLens 8 has a whole WYSIWYG settings editor built in. You can open it from the command palette _GitLens: Open Settings_ 😄

Yeap but it is not easy to check 120 settings rather than writing one line.

**Comment by eamodio** [comment]
@can-artuc sure, but if you don't know the name of the setting or if there is even a setting an interactive settings editor definitely helps.

**Comment by can-artuc** [comment]
I agree @eamodio but I can always find the settings name as I found at the moment 😬I checked editor 2 times to find it. May be I am not so good to read settings in editor.

**Comment by eamodio** [comment]
@can-artuc just to make sure I understand that we are talking about the same thing -- here is a screenshot of GitLens' settings editor:

![image](https://user-images.githubusercontent.com/641685/54447352-a3d95b80-471f-11e9-82ad-80f3aba9a21c.png)

You are talking about that one right? If so, I would love to hear any thoughts/feedback how I can make it less overwhelming and more accessible.

**Comment by can-artuc** [comment]
Hmm nope @eamodio , I am talking about this:

![](http://canartuc.com/img/gitlens_settings.png)

**Comment by eamodio** [comment]
@can-artuc Yeah -- that's what I thought -- that is vscode's settings editor -- which is completely unusable for something like GitLens which has a ton of settings. That is why I built my own interactive settings editor -- specifically for GitLens (and long before vscode even had its own ui settings editor).  You can open it from the command palette `GitLens: Open Settings`

**Comment by can-artuc** [comment]
Thank you @eamodio , you are very helpful! I haven't built any vscode extension and don't know the dynamics and structures. But if it is possible to do, may be it is better to put some kind of info or link which points to your interactive settings editor from regular settings window. Thank you very much for your effort for this extension!

**Comment by eamodio** [comment]
@can-artuc Appreciate that -- and glad to help. I wish it was something that was possible. I actually just opened this issue about it: https://github.com/Microsoft/vscode/issues/70589. Please upvote it ;)
