### ISSUE TITLE
CSS errors on welcome page (mask-* properties)

### ISSUE THREAD

**Issue by dipnlik** [eamodio/vscode-gitlens#288]
- GitLens Version: 8.0.0
- VSCode Version: 1.20.0
- OS Version: Ubuntu 17.10

Steps to Reproduce:

1. Ctrl-Shift-P, GitLens: Welcome.
2. Look at these 5 Problems in the status bar.

---

file: 'file:///home/dipnlik/.vscode/extensions/eamodio.gitlens-8.0.0/welcome.html'
severity: 'Warning'
message: 'Unknown property: 'mask-image''
at: '1,3972'
source: 'css'
code: 'unknownProperties'

file: 'file:///home/dipnlik/.vscode/extensions/eamodio.gitlens-8.0.0/welcome.html'
severity: 'Warning'
message: 'Unknown property: 'mask-repeat''
at: '1,4626'
source: 'css'
code: 'unknownProperties'

file: 'file:///home/dipnlik/.vscode/extensions/eamodio.gitlens-8.0.0/welcome.html'
severity: 'Warning'
message: 'Unknown property: 'mask-image''
at: '1,6598'
source: 'css'
code: 'unknownProperties'

file: 'file:///home/dipnlik/.vscode/extensions/eamodio.gitlens-8.0.0/welcome.html'
severity: 'Warning'
message: 'Unknown property: 'mask-size''
at: '1,7026'
source: 'css'
code: 'unknownProperties'

file: 'file:///home/dipnlik/.vscode/extensions/eamodio.gitlens-8.0.0/welcome.html'
severity: 'Warning'
message: 'Unknown property: 'mask-repeat''
at: '1,7074'
source: 'css'
code: 'unknownProperties'

---

I don't know what's the expected behavior of these CSS properties in the page but the page doesn't look "broken" and having problems pop up in the status bar looks bad, so maybe these properties can be safely removed?

**Comment by eamodio** [comment]
I can remove those unprefixed versions for now (they were added as future-proofing) as this is not noise I want to expose users to, but I also opened https://github.com/Microsoft/vscode/issues/43678
