### ISSUE TITLE
GitLens line info causes horizontal scroll in editor

### ISSUE THREAD

**Issue by gwk** [eamodio/vscode-gitlens#290]
Just filed an issue with VSCode and want you to be aware as well: https://github.com/Microsoft/vscode/issues/43940

> With the default settings, Gitlens draws text at the end of the current line showing git blame info.
This causes the line length to exceed that of the window, thereby enabling horizontal scrolling.
Note that horizontal scrolling is not possible, even with wrapping lines, until the first time gitlens takes this action and causes an overflow. The only recourse I see is to reload the editor window, but it's just a temporary fix until gitlens does it again.

Please read the full report there. In summary, I think that causing unwanted horizontal scroll is something that VSCode should prevent extensions from doing. I want to make GitLens aware of this issue, in case you disagree with my assessment or have additional thoughts. I want to see GitLens succeed, and if the community decides that this detail is actually a feature and not a bug I will respect that, but for me personally it is a flaw that causes more trouble than GitLens is worth.

- GitLens Version: v8.0.0
- VSCode Version: Version 1.21.0-insider (1.21.0-insider) 9a4ba7d
- OS Version: 10.13.4 Beta (17E150g)

**Comment by eamodio** [comment]
I'm going to close this, because as far as I can tell there isn't anything GitLens can do to change this behavior (other than turning off the current line annotation).

See https://github.com/Microsoft/vscode/issues/43940#issuecomment-366609954 for more details.

**Comment by fabbballin** [comment]
@eamodio This only appears to be an issue when the **Current Line Blame** line is longer than current width of the active editor tab.

_Some possible solutions here (besides disabling Current Line Blame) would require modifying how "current line blame" is presented_ 

Some idea's:

1. Truncate the blame text so that the entire line char count is less than the tab's width, show full blame on hover.
2. Allow the blame text to be modified (such as removing the or not showing the full file path)
3. Instead of showing the blame at the end of a line, show a git icon, which would reveal blame info on hover.

Thoughts?

**Comment by eamodio** [comment]
@fabbballin Thanks for thinking more about this.

> 1. Truncate the blame text so that the entire line char count is less than the tab's width, show full blame on hover.

Unfortunately I don't know of any way to know the width of the editor/tab. VSCode doesn't provide access to that info, and trying to glean it from line lengths would be prohibitively expensive (especially for large files)

> 2. Allow the blame text to be modified (such as removing the or not showing the full file path)

This is possible today, just not exposed through the interactive settings editor (yet -- thinking about it though). See the [`gitlens.currentLine.format` setting](https://github.com/eamodio/vscode-gitlens#current-line-blame-settings). FYI, similar settings exist for the gutter blame and content in the explorer views.

> 3. Instead of showing the blame at the end of a line, show a git icon, which would reveal blame info on hover.

This is an interesting idea, and I *think* it is possible with the api vscode provides (though I know I can't mix text and images -- has to be one or the other). I'll have to look into it more.

Another option which I really like is to provide the hovers over the line numbers (in the gutter), but unfortunately vscode doesn't currently support it. If you think it would be valuable, please up vote this https://github.com/Microsoft/vscode/issues/28080

**Comment by skbolton** [comment]
You can actually get their personal settings with this api https://code.visualstudio.com/docs/extensionAPI/vscode-api through the `getConfiguration()` method. I would love if we could take a crack at fixing this. I could maybe look and try doing a pr

**Comment by eamodio** [comment]
@skbolton This issue is fixed if you use set the `gitlens.currentLine.scrollable` setting to `false`. Are you looking for more than just that?

**Comment by LinqLover** [comment]
@eamodio If you disable `gitlens.currentLine.scrollable`, hover cards won't work even longer, even if the whole currentLine information is visible. Is this another bug?
