### ISSUE TITLE
Add multi-cursor support to current line annotations

### ISSUE THREAD

**Issue by spikespaz** [eamodio/vscode-gitlens#291]
I would like to request a feature (two actually), and I think here is where to do it based on other people's submitted issues.

Feature: **Option to align inline blame messages to a gutter line (with configurable padding).**
Second feature: Show blame messages on multiline cursors.

**Here is an example of what I envision for both features.**

![image](https://user-images.githubusercontent.com/12502988/36362499-a42643ce-14f2-11e8-9f1c-18c01fd7817f.png)

- GitLens Version: `8.0.0`
- VSCode Version: `1.20.1`
- OS Version: `Microsoft Windows 10 Home Insider Preview 10.0.17074`

**Comment by eamodio** [comment]
Unfortunately there isn't any way for GitLens to align the annotations -- about the only thing I can do, is say how far it is from the end of the line text.

As for supporting multiple cursors -- what is a real use-case for this? To me it kind of feels like it is going to cause more visual noise than valuable information. While, if you want to see the blame of more than 1 line, you can open the full blame (at least that is anchored to the gutter and not intermixed with the actual code).

**Comment by spikespaz** [comment]
Blame messages on multiple lines wouldn't be disruptive at all, if you were selecting multiple lines you would want to be active on those lines and that means having equivalent amounts of information. Specifically my case, I wanted to compare similar changes across two commits within the editor to see if they should be squashed.

Same goes for highlighting blocks, maybe hovering a large section of highlighted code should pop-up all of the blame information for each line (not by default because that is intrusive). Its just more information, and it would be nice to have as an optional feature.

Also, for alignment, what about subtracting the number of columns for both the line text and the message text from the user's preferred ruler (set in the settings) and adding padding to the left of the blame message based on the difference?

I would fork and add it myself but I would have to dig through the repository code to see how it works and I don't have any prior experience with Visual Studio Code extensions. If I have extra time, I'll take a look at what I can do myself, but I have a lot of homework to do.

**Comment by eamodio** [comment]
@spikespaz I've added support for multi-cursor, it will be in the next GitLens release (not sure when that will be yet). For the alignment issue -- there really isn't a way to get that to work. Extensions have very limited control over the positioning of the decorations.
