### ISSUE TITLE
Show commits of current branch

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#293]
Use case: I want to see a list of commits in my current branch, and just those. Both **Show Current Branch History** and the branch view in the sidebar list all commits reachable from HEAD which is technically correct but I'm often interested only in "my commits".

The Git command that produces the desired output is

```
git log $(git merge-base master HEAD)..HEAD
```

(Most commonly, it can be just `git log master..HEAD`.)

In the UI, I think this could be another top-level node in the sidebar, something like **Current branch**.

> BTW, it could also be useful for content comparison as there are some usability issues with it current, see e.g. _"Compare selected ancestor with working tree" needs "select for compare"_ #279.

So the sidebar could look like this:

```
- Current branch
    - Diff
       - ... here is a file tree, introduced in #240 ...
    - Commits
       - [avatar] My second commit
       - [avatar] My first commit
- Branches
- Remotes
- Stashes
- Tags
```

**Comment by eamodio** [comment]
Ah interesting, I think the biggest challenge here, is picking the branch that is the base -- here you are always using `master`, but that isn't always the case.

**Comment by borekb** [comment]
You're right. git-tree-compare deals with that using **Change Base...**:

![image](https://user-images.githubusercontent.com/101152/36568051-eaf69068-1828-11e8-8578-c35bfeecce24.png)

**Comment by jabacchetta** [comment]
I like the "commits behind master" view that Bitbucket gives, and I believe this feature would essentially be the equivalent.

**Comment by eamodio** [comment]
@borekb I've added a new experimental new _Compare <current-branch> with..._ node to each repository. It will let you pick the comparison and it persists based on the workspace/repo/branch. You must set `"gitlens.insiders": true` before it will show up.

[gitlens-9.7.4.vsix.zip](https://github.com/eamodio/vscode-gitlens/files/3185347/gitlens-9.7.4.vsix.zip)

Could you try it out and let me know if this will solve this issue for you? Thanks!

**Comment by borekb** [comment]
Thanks, I like the contents of that node but I'd prefer if this was just directly under the branch. Here's how I see it:

<img width="428" alt="Screenshot 2019-05-16 at 09 06 14" src="https://user-images.githubusercontent.com/101152/57833328-17e4be00-77ba-11e9-9f2d-a0287ba842ef.png">

I understand the challenge with the "base branch" but still think this can be a global setting as per https://github.com/eamodio/vscode-gitlens/issues/293#issuecomment-367846197.

**Comment by eamodio** [comment]
While I see what you are saying, I find the branch history regularly quite valuable. In 9.8 I've add the new comparison node similar to the above. Hopefully that meets your need closely enough.

**Comment by borekb** [comment]
There seems to be many good changes around this in [v9.9](https://github.com/eamodio/vscode-gitlens/blob/master/CHANGELOG.md#990---2019-07-21):

![Screen Recording 2019-07-22 at 15 06 05_05 (1)](https://user-images.githubusercontent.com/101152/61640457-a9cae480-ac9d-11e9-90bf-e123db5a10c1.gif)

The number of commits (12) in case of a two-dot mode is correct, however, the files are not correct: there's not 28 of them but 13 – Git Tree Compare & GitHub Pull Requests extensions show that correctly. Is that a bug or is this feature supposed to work differently?

**Comment by Morikko** [comment]
I just spot the same behavior. It looks like the files changed are always diff with the 2 dot approach.

**Comment by eamodio** [comment]
@borekb @Morikko sorry, that is a bug -- can you pls open a new issue for this?

**Comment by borekb** [comment]
👍 , done that in #797.

**Comment by AndrewDavis** [comment]
I'm totally on board with borekb's request. This is **SO** confusing to me to read. I don't understand what's going on, even though I now know this is happening. I just want my commits to show up like they do when I'm viewing a branch in a repo online. This should be an option to make it the **main** view in Repositories, and probably the default behavior as well.

**Comment by AndrewDavis** [comment]
Also it's showing me commits from a different branch in the other branch I'm currently viewing...? Like what the heck.
