### ISSUE TITLE
This bindind erase default "\" key french keymap

### ISSUE THREAD

**Issue by DavidBabel** [eamodio/vscode-gitlens#294]
It's more an information than a bug, but this binding : 

```
{
  "key": "shift+alt+[Period]",
  "command": "gitlens.showCommitSearch",
  "when": "gitlens:enabled && gitlens:keymap == 'standard'"
}
```

it erase the way of doing a backslash "\\" on MacOs french keyboards.

**Comment by eamodio** [comment]
Please open the GitLens settings (run *GitLens: Open Settings* from the command palette) and jump to *Keyboard Shortcuts* and change to either the `chorded set` or `custom set`.

In the next GitLens release, I am thinking about switching to the `chorded set` by default to avoid these issues.

**Comment by DavidBabel** [comment]
i did this (in keymap), it works too : 

```
  {
    "key": "shift+alt+[Period]",
    "command": "-gitlens.showCommitSearch",
  }
```
