### ISSUE TITLE
Extension host terminated unexpectedly - Message always appearing

### ISSUE THREAD

**Issue by KBPsystem777** [eamodio/vscode-gitlens#298]
Hi there! I am receiving this annoying error once VSCode was opened:

![image](https://user-images.githubusercontent.com/20304211/36736931-c44021e2-1c14-11e8-94cf-71cb9be80b5c.png)

You may see additional details on https://github.com/Microsoft/vscode/issues/44265

- GitLens Version:
![image](https://user-images.githubusercontent.com/20304211/36736682-305599da-1c14-11e8-8186-d5b03d72f450.png)

- VSCode Version:
![image](https://user-images.githubusercontent.com/20304211/36736688-34ff8360-1c14-11e8-811b-7f437865d930.png)

- OS Version:
Windows 10 Enterprise

## Steps to Reproduce:
As seen on https://github.com/Microsoft/vscode/issues/44265

1.  Updated VSCode to `January 2018 (version 1.20)`
2. Installed GitLens

**Comment by eamodio** [comment]
Hrm, first I would suggest uninstalling GitLens, restarting vscode (twice), and then re-installing GitLens, to rule out any installation issues.

If the issue still persists after that, with no extensions enabled other than GitLens, can you enable logging to see if anything shows up? You can enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

**Comment by eamodio** [comment]
@KBPsystem777  Can you retry with the latest GitLens version and see if you are still experiencing this issue?

**Comment by KBPsystem777** [comment]
@eamodio trying now, will get back here for feedback :)

**Comment by KBPsystem777** [comment]
@eamodio issue seems to be resolved. I just updated GitLens to new version, restarted VSCode and the error message didnt showed up again. I waited 2 days but so far, no message is showing up :)

**Comment by eamodio** [comment]
Great! Glad to hear it. I'm going to close this then. Please reopen if it comes back.

**Comment by itsmasud** [comment]
I am getting this error and I am getting this error after having latest update of VS code. I am running react native. The non-react-native people are not getting that error.

**Comment by eamodio** [comment]
@itsmasud can you follow the steps here: https://github.com/eamodio/vscode-gitlens/issues/298#issuecomment-368944503 and post back?
