### ISSUE TITLE
GitLens Explorer - Show, but collapsed/folded

### ISSUE THREAD

**Issue by mpathy** [eamodio/vscode-gitlens#299]
- GitLens Version: current
- VSCode Version: current
- OS Version: 10.10.5

Steps to Reproduce:
1. Open a project / folder or just open VC Code again
2. The Gitlens is opened, and takes up space

I like GitLens, but I dont need it all the time, and I dont have the biggest screen.

So it would be great that in the GitLens Settings, there is an additonal option to say, "Start GitLens in folded state".

Because right now, I always have to do this additional step after opening VC Code.

Its no big deal, but for sure no big coding task either :)

**Comment by eamodio** [comment]
I'm going to close this, please feel free to re-open if you feel this hasn't been resolved (and isn't a vscode issue).
