### ISSUE TITLE
`gitlens.codeLens.scopes` setting cannot be empty

### ISSUE THREAD

**Issue by dbkaplun** [eamodio/vscode-gitlens#300]
- GitLens Version: v8.0.2
- VSCode Version: 1.20.1
- OS Version: OSX 10.13.3 (17D102)

![screen shot 2018-02-28 at 12 57 43 pm](https://user-images.githubusercontent.com/1765130/36803947-10be178c-1c87-11e8-9e63-9d76e0b88881.png)

**Comment by eamodio** [comment]
What are you trying to do that you don't want any scopes?

**Comment by dbkaplun** [comment]
@eamodio I just want this to be visible during editing:
![eamodio-vscode-gitlens-300](https://user-images.githubusercontent.com/1765130/36806177-31285842-1c8d-11e8-901e-c6fa867fdaea.png)

**Comment by eamodio** [comment]
The scopes only affect the code lens, not the current line blame (or anything else). So I'm still not sure what you are looking to do. But I would recommend opening the interactive settings editor, because it will show you visually how each setting works and how it will behave.
