### ISSUE TITLE
GitLens "Open revision" changes the behavior of standard "Go to definition" feature

### ISSUE THREAD

**Issue by zzanzare** [eamodio/vscode-gitlens#301]
- GitLens Version: 8.0.2
- VSCode Version: 1.21.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. create empty git repo, add file like this
```
<?php

function asdf() {

}

asdf();

```
2. commit that change
3. add one line in that file
4. use "Open Revision" feature of GitLense, it will open new tab with the previous revision (Note that file is created in /tmp)
https://imgur.com/a/pQRPY
5. close that new tab, go back to the original file, now Ctrl+click the asdf(); or right-click and "Go to definition"

Expected:
it should jump couple of lines above to the current definition of asdf() as usual

Actual:
it will open that old revision tab again, jumping to the definition of asdf() as it appeared in the old revision. But that is obviously wrong, I want to see the *current* definition when using the "Go to definition" feature.

**Comment by eamodio** [comment]
@zzanzare Can you still reproduce this? I can't with the latest insiders build. I don't have any php language service install, but I tried C#/TypeScript/JavaScript and couldn't get it to happen.

If you still get this to happen, it sounds like a vscode bug or an issue with the php language service.

Let me know, thanks!

**Comment by zzanzare** [comment]
I just tried with the new VSCode version 1.21.0 and GitLens version 8.1.1 and I could still reproduce this issue exactly as before. (yeah, i don't know what happened to the VSCode version number, I must have made a typo when I first opened this issue)

**Comment by eamodio** [comment]
@zzanzare Hrm, GitLens (AFAIK) has no control over this. It feel to me like a bug in the php language service, where it is incorporating file from temp locations and not cleaning them up properly or something. I don't see the behavior with the JavaScript/TypeScript files nor with C# files. So I would recommend open an issue with either vscode or the php language service. Sorry.

**Comment by keck-in-space** [comment]
Same issue here in C project. Only reason I removed gitlens from vscode.
