### ISSUE TITLE
Feature Request: Export modified files  with Folder Structure.

### ISSUE THREAD

**Issue by prakashsvmx** [eamodio/vscode-gitlens#303]
Please provide an option to export modified files  (tracked/untracked) to be exported with folder structure.

**Comment by eamodio** [comment]
Can you provide more details on this, I'm not sure what you are requesting.

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Comment by mwithi** [comment]
Up: in website or PHP webapp development, the ability to export a file to a destination folder along with its complete path structure (useful to extract small patches). Same as Eclipse -> Export -> File System feature

**Comment by DecideNowLib** [comment]
Planing to use VS Code for PHP-development. Waiting for the same feature.
Very useful to deploy changes when many files were changed.

This is [how i do it in Eclipse](https://youtu.be/Ra1OdGFcddM) (workingtree<=> last commit are compared).

[In VS Code I can compare](https://cloud.mail.ru/public/3Lt5/Bubf97rnw) but export with directory structure is not supported.

Thanks!

**Comment by prakashsvmx** [comment]
for example the following command on a mac system creates a backup of modified files only with directory structure.

```
git ls-files --modified --others --exclude-standard  | zip -r ../GitChangesBackup/d_table.zip --names-stdin
```

Benefits:
Easy sharing of modified files
Easy merging of changes.

**Comment by DecideNowLib** [comment]
Thank you. It helped a lot. Now I can start using VS Code.

1. I'm on Windows machine so I had to [add Git bash terminal in VS Code](https://stackoverflow.com/questions/42606837/how-do-i-use-bash-on-windows-from-the-visual-studio-code-integrated-terminal).
2. Git bash does not support `zip` command so I just copy files to new folder (need to create it before coppying with `mkdir` command).
3. I use `git diff` command for different compare options (commit1 - commit2, commit-index etc.) like this

`$ mkdir 'd:/tmp' && git diff --name-only HEAD | xargs -I '{}' cp --parents '{}' 'd:/tmp/'`

It took me some hours to find appropriate commands and oftions for my purpose. Terminal is powerfull but IDE must make life easyer with benifits of WYSIWYG. So I'm looking forward to see simple export tool.
