### ISSUE TITLE
Can not install gitlens

### ISSUE THREAD

**Issue by rafaF** [eamodio/vscode-gitlens#304]
- GitLens Version: 8.1.0
- VSCode Version: 1.13.0
- OS Version: Windows 7 Enterprisa SP1

Steps to Reproduce:

1. Install gitlens from VSIX
2. Nothing happens. The reload tag doesn't dissapear from the gitlens extension in extensions tab of VSCode even reloading / restarting VSCode lot of times
![vscode_gitlens_screenshot](https://user-images.githubusercontent.com/6287112/37145966-b523c510-22c2-11e8-9f92-8c2cfcae033a.png)

**Comment by Identitry** [comment]
Had the same problem but when enabling Developer Tools (Help/Toggle Developer Tools) I could see that you need at least VS Code version 1.20 for GitLens 8.1.0.

`Extension is not compatible with Code 1.17.2. Extension requires: ^1.20.0.`

Updated to VS Code 1.21 and GitLens was enabled on Reload.

**Comment by eamodio** [comment]
Yeah, as @Identitry said GitLens requires vscode version 1.20 or later.
