### ISSUE TITLE
Git right-click file options in explorer

### ISSUE THREAD

**Issue by geogeim** [eamodio/vscode-gitlens#306]
It would be really nice to have the stage, unstage, discard changes commands right in the file explorer. This way I won't have to search for the files I want to commit in the source control tab, especially if I happen to have hundreds of changed files and I just want to commit one or two.

**Comment by eamodio** [comment]
To be honest, on this one, I would start with this request for vscode, since the stage/unstage command are provided by the built-in Git support. If that doesn't go anywhere (or they don't want to add that support), then I will add it into GitLens.

**Comment by eamodio** [comment]
I'm going close this, but feel free to re-open if this request doesn't go anywhere with the vscode team.
