### ISSUE TITLE
Status bar blame & code lens disappeared

### ISSUE THREAD

**Issue by sixclones** [eamodio/vscode-gitlens#307]
Hello !

For 2 days (the last update of gitlens), lots of features disappeared (status bar blame, code lens). Others are still here (gutter blame).

I've tried to disabled all my extensions and enable only GitLens but nothing changed.
I checked the settings, all was good.

- GitLens Version: 8.1.0
- VSCode Version: 1.20
- OS Version: Ubuntu 17.10

Hope this can be fix, it's a great extensions !

Sixclones

**Comment by sixclones** [comment]
Just update VSC and worked again. Thought I was on the latest version.

**Comment by eamodio** [comment]
Glad to hear it got resolved.
