### ISSUE TITLE
Conflicting keymap with swedish keyboard layout

### ISSUE THREAD

**Issue by baelter** [eamodio/vscode-gitlens#308]
- GitLens Version: 8.1.1
- VSCode Version: 1.21.0
- OS Version: 10.13.3 

shift+alt+7 is backslash on swedish keyboards. Please remove the keymap to gitlens.showCommitSearch

Steps to Reproduce:

1. Use swedish keyboard
2. shift+alt+7

**Comment by baelter** [comment]
Found the setting for changing this.

**Comment by eamodio** [comment]
@baelter was this a new install of GitLens or an upgrade from a prior version?

**Comment by baelter** [comment]
Upgrade

**Comment by eamodio** [comment]
Ah, OK, then that is expected -- I didn't want to change the defaults for any existing user (only new ones). Thanks!
