### ISSUE TITLE
Revisit terminology of comparison commands

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#309]
While I wish vscode allowed extensions to dynamically control the label of the menu item, that currently isn't possible. So lets talk about how best to name many of the comparison commands in GitLens.

![image](https://user-images.githubusercontent.com/641685/37288282-3bd396c2-25dd-11e8-8dc8-750fcca8acb6.png)

|Command|Behavior|Example
|------------|---------|---------
|Compare with Remote|Compares the selected branch with its remote|Compares `master` with `origin/master` (e.g. `origin/master...master`)
|Compare with Index (HEAD)|Compares the selected branch (or commit or stash or tag) with the current branch's HEAD|Compares `master` with `HEAD` (e.g. `master...HEAD`)
|Compare with Working Tree|Compares the selected branch (or commit or tag or stash) with the current working tree|Compares `master` with working tree (e.g. `master...`)
|Compare Ancestry with Working Tree|Compares the common ancestor of the current branch and selected branch with the current working tree|Compares the merge-base of `develop` and `master` with working tree (e.g. `(merge-base develop master)...`)
|Select for Compare|Selects the branch (or commit or stash or tag) for later comparison|Select `master` for comparison with another branch
|Compare with Selected|Compares the selected branch (or commit or stash or tag) with the previously selected branch (or commit)|Compares `master` to `demo` (e.g. `master...demo`)

EDIT: The above table has been updated with the current set of commands that will be in GitLens 8.2

**Comment by borekb** [comment]
Hi @eamodio, cool that this is considered so carefully. I'll write more when I have time but my first quick feedback:

**'Compare with Remote'**\
is fine as it is, IMO.

**'Compare with Index (HEAD)'**\
HEAD is not the same as Index so the naming that contains any combination of those is confusing to me. Also, this command doesn't seem to yield too useful results as it combines commits and changes from both branches.

**'Compare with Working Tree'**\
This doesn't seem that useful to me: if I have uncommitted changes, those can be easily seen in the VSCode Git panel or in the first node ("book" icon) of GitLens panel. I would personally remove this command from the context menu.

**'Compare Common Ancestry with Working Tree'**\
My main problem with this is that it was not intuitive to me that I needed to right-click `master` to get the result I wanted. But when I discovered that, this one is the most useful to me of them all.

In the terminology, I find it confusing to use Working Tree as I want to compare two Git states, regardless of my currently edited files.

Ideally, for this last one, I would right-click my current branch and select 'Compare with `master`' but I understand that the label can't be dynamic, so maybe something like 'Compare with base branch'? Another tricky thing is to tell what the base branch is, Git Tree Compare deals with that by providing a way to set a base branch:

![image](https://user-images.githubusercontent.com/101152/37294534-43e189ee-2616-11e8-9e37-01a0511b9aac.png)

**Comment by eamodio** [comment]
@borekb Thank you for your feedback &mdash; really appreciate it. One thing I think that has to be considered, is that many of these commands are executed in the context of a selected branch (or commit, stash, tag) and the current branch (work tree/head/etc).

*Compare with Index (HEAD)* &mdash; my bad on that one, will remove index from it. Updated the table above.

*Compare with Working Tree* &mdash; This command isn't just for comparing the current branch to the working tree, it compares **any** selected branch to the working tree

*Compare Common Ancestry with Working Tree* &mdash; yeah, it all depends on your usage -- this way you can compare the common ancestor of the current branch to any selected branch and then compare that to the working tree.

> In the terminology, I find it confusing to use Working Tree as I want to compare two Git states, regardless of my currently edited files.

If you want to just compare 2 branches, you can use either *Compare with HEAD* (once renamed) to compare the selected branch to the current branch, or use *Select for Compare* to pick branch A and then *Compare with Selected* to pick branch B (and that will work between any 2 shas)

> Ideally, for this last one, I would right-click my current branch and select 'Compare with master' but I understand that the label can't be dynamic, so maybe something like 'Compare with base branch'?

So I understand the natural desire to want to get to this from the current branch, but today you can get the same effect by choosing the `master` branch and selecting *Compare with HEAD*

**Comment by borekb** [comment]
I'm trying it again in practice on my current project:

- Being in a feature branch, right-clicking `master` and choosing _Compare with HEAD_ (once renamed) is a clear winner in usefulness for me. This is a really nice view on "my work", or, generally, work done in a branch.
- I get what you say about the Working Tree and how it could be used with other branches but I realized I simply never needed something like it during the past years of doing branch-based development, and if I absolutely needed to, I could use _Compare with HEAD_ to get close, or create a temporary commit, something like that. In practice, the only thing I care about is the diff to the latest commit which is handled natively by VSCode.
    - Related UX issue: with the "compare with Working Tree commands" from another branch, the Results panel lists commits, files changed in those commits and files changed in the working tree in just two tree nodes. So it's hard to tell which changes are committed and which are just in working tree.
- In a clean working tree state, the long command _Compare Common Ancestry with Working Tree_ does the same as the much simpler _Compare with HEAD_. Again, if you got rid of the working tree comparisons, this could go away as well.

So in the end, I think you could have just this (in this order):

- _Compare with HEAD_
- _Compare with remote_
- _Select for compare_ / _Compare with selected_

Additional UX suggestion: when I ran _Compare with HEAD_ on the current branch, you could display a notification about how to make it useful, something like:

> Did you want to compare your base branch (possibly `master` or `develop`) with the current branch? Right-click that other branch and select _Compare with HEAD_.

I'm not sure about this last one but I'd really try to make the feature more discoverable.

**Comment by borekb** [comment]
Looking at 2ac7164, the eventual change seems pretty small. I still think that the "Working Tree commands" are more confusing than useful to be honest.

**Comment by eamodio** [comment]
I've just released GitLens 8.2 with some changes for this. I disagree on the value of the working tree commands (I use them) and I don't feel that they should cause confusion. Although I definitely agree that when using the working tree ones there isn't a way to see which files were changed by what (like I do under the current branch changes). So I will be looking to add support for that.

Are there any other issues you feel that I'm missing?

**Comment by eamodio** [comment]
@borekb Can you please open a new issue about the `...` vs `..`, I'm not sure how to handle that yet, but I don't want to lose it. Thanks!

**Comment by borekb** [comment]
Done: https://github.com/eamodio/vscode-gitlens/issues/330.

Feel free to update the title, I'm not sure the current one is that good.

**Comment by borekb** [comment]
I'm re-reading the thread and I'm not sure what I was reporting as I see different behavior now (GitLens  8.5.1). I'll report carefully again.

These are my branches, I'm in a feature branch now:

![image](https://user-images.githubusercontent.com/101152/42988427-b5128a04-8bfc-11e8-98bf-c4763eea3f18.png)

Running **Compare with HEAD** from `master`:

![image](https://user-images.githubusercontent.com/101152/42988458-da78ea40-8bfc-11e8-8c8b-ab7ac7d94173.png)

yields these results:

![image](https://user-images.githubusercontent.com/101152/42988501-0a6787b6-8bfd-11e8-892d-1b96a005e004.png)

This is _not_ what I would naturally expect as it mixes commits and changes from both branches. For this, issue #330 was created.

Now, let's try **Compare Ancestry with Working Tree**:

![image](https://user-images.githubusercontent.com/101152/42988532-3b8b53e0-8bfd-11e8-9bd9-6efddefc22c7.png)

This is a "good" result as far as I'm concerned:

![image](https://user-images.githubusercontent.com/101152/42988561-5ba2b20e-8bfd-11e8-9662-f470200c09c4.png)

It is in line with what GitHub shows in a pull request, good:

![image](https://user-images.githubusercontent.com/101152/42988604-8175bf76-8bfd-11e8-8f41-a9612e88e36b.png)

However, if I have some file dirty, it will show up as well in the Results view:

![image](https://user-images.githubusercontent.com/101152/42988823-5f132ad0-8bfe-11e8-992e-9f990ac7c6fd.png)

I don't think this is a useful behavior as there are better ways to visualize what is changed in my working copy. Ideally, there would be a command **Compare Ancestry with HEAD**.

Hope this makes sense :)

**Comment by KolyaKorruptis** [comment]
My use case for "Compare Ancestry with Working Tree" are code reviews, where I review all the changes I did in my feature-branch with a colleague. Including dirty files is rather useful in this case, eg when I make new changes during the review.

I also would like to start this comparison by rightclicking my current branch and having an option named "Compare with Parent Branch".
