### ISSUE TITLE
Disable gitlens if the project does not have `.git` folder

### ISSUE THREAD

**Issue by unional** [eamodio/vscode-gitlens#31]
e.g. Some of the projects I work on is under perforce.

**Comment by eamodio** [comment]
@unional Thanks for you feedback! I currently do disable GitLen in this case, but unfortunately given the current vscode extension api I don't have a great way to remove the commands from the menus and command palette. I will look into it more, and there is an [issue opened](https://github.com/Microsoft/vscode/issues/10401) with vscode to address some of this.
