### ISSUE TITLE
Does not honor the word wrap settings

### ISSUE THREAD

**Issue by atishay** [eamodio/vscode-gitlens#311]
- GitLens Version: 8.1.1
- VSCode Version: 1.20.1
- OS Version: OSX 10.13.3

Steps to Reproduce:

1. Enable word wrap in VSCode Preferences.
2. Check the horizontal scroll bar.

**Comment by eamodio** [comment]
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/290. Unfortunately there isn't much I can do here given the constraints of the vscode api and behavior.
