### ISSUE TITLE
Toggle Line Blame Annotation doesn't work if default setting in currentLine.enabled is changed

### ISSUE THREAD

**Issue by mincer88** [eamodio/vscode-gitlens#314]
- GitLens Version: 8.1.1
- VSCode Version: 1.21.0
- OS Version: Win7 64Bit

Issue:
"gitlens.currentLine.enabled": false
this turns off the current line blame Annotation. 

Toggle line blame Annotation doesn't work anymore. 

Use-Case is, that the line Annotation should be disabled as Default, but turned on via toggle command quickly if needed.

**Comment by idoo** [comment]
looks like it came back
