### ISSUE TITLE
Delayed Loading on File Focus causing scroll position and readability issues

### ISSUE THREAD

**Issue by Tiedye** [eamodio/vscode-gitlens#315]
When switching views from one file to another, it takes a moment for code lenses to load causing a jarring addition of those lines a moment later, which also has the effect of changing the scroll position of the window.

It would be preferable if those lenses were not unloaded when the window is navigated away from so my place is kept in large files and my eyes do have to find what I'm looking at twice each time I open an editor.

Another solution would be to simply reserve the space for those lenses so when they load they do not move the code.

- GitLens Version: 8.1
- VSCode Version: 1.21.0
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Open two or more versioned files in multiple tabs
2. Switch between those tabs

**Comment by eamodio** [comment]
Unfortunately GitLens (or any extension) cannot control that behavior, that is the way code lens works in vscode. They always discard them and refresh them on tab switch. I talk a bit more about it here: https://github.com/eamodio/vscode-gitlens/issues/245#issuecomment-357803035

Although there are some bugs associated with code lens currently that makes the situation much worse: see https://github.com/Microsoft/vscode/issues/41968
