### ISSUE TITLE
Just how to open the so-called "GitLens explorer"?

### ISSUE THREAD

**Issue by marc2377** [eamodio/vscode-gitlens#317]
- GitLens Version: 8.1.1
- VSCode Version: 1.21.1
- OS Version:

Hi.

GitLens has a feature called "GitLens explorer", which is said to support both a tree layout and a list layout. This section explains about the feature: https://github.com/eamodio/vscode-gitlens#gitlens-explorer - however, it does not say how / where to find it.

I can't seem to find it anywhere. Where is it?

`gitlens.gitExplorer.enabled` is `true`.

Thanks.

**Comment by marc2377** [comment]
For now I found a way: In the "View" menu, select "Open View..." and type in "GitLens".

A new section will appear under the "Explorer".

(I was hoping it should be under "Source Control", though.)

Now... Is there a more intuitive way of opening it?

**Comment by eamodio** [comment]
@marc2377 If you hadn't previously turned off the GitLens explorer it should have shown up (albeit collapsed) on the Explorer activity. There *should* be only 3 ways it wouldn't show up:

1. The user turns the view off view the right-clicking on a view and deselecting it (if so, it has to be turned back on via the same mechanism -- extensions can't override this)
1. Setting `"gitlens.gitExplorer.enabled": false`
1. Open a folder that doesn't have a git repository

Were any of the above true?

**Comment by marc2377** [comment]
In fact, I did not know beforehand it would be under "Explorer", and if it was collapsed, I must've missed it.

Perhaps there is also the fact that I was expecting the functionality to be available for _files_ opened directly in the editor (i.e. without opening any _folder_). In which case alternative number 3 would be true.

I'm considering opening a separate feature-request issue about this. The VS Code's native Git integration works this way. Do you know of any reason why it shouldn't be possible with GitLens?

Thank you.

**Comment by eamodio** [comment]
Ah, I see. Feel free to open a new feature request to support single files. It should certainly be possible in GitLens, but will likely require some rework.

**Comment by LAITONEN** [comment]
Have you removed `"gitlens.gitExplorer.enabled": false` option? Can't find it in default VS Code's settings and if I add it to my user settings, VS Code says that the command is unknown.

**Comment by eamodio** [comment]
@LAITONEN The GitLens explorer has been broken up into multiple views -- See https://github.com/eamodio/vscode-gitlens#side-bar-views. Each of them now have their own settings -- it is easiest to use the _GitLens: Open Settings_ command to configure them.

Hope that helps!
