### ISSUE TITLE
00000000 Uncommitted changes distracting

### ISSUE THREAD

**Issue by innerlee** [eamodio/vscode-gitlens#32]
I find the ``Uncommitted changes`` info mostly distracting. These new changes has well indicated besides the line no and also in the scroll bar (maybe also in the coming mini-map). It would be great if we can hide it.

![fff](https://cloud.githubusercontent.com/assets/9464825/23201422/7bd113fe-f914-11e6-89e5-c8f5de3fb77a.png)

**Comment by eamodio** [comment]
@innerlee which part specifically? The hover? The inline annotation? Both? And do you only find it that way for `Uncommitted` or in general?

FYI, there are setting that control almost all of the above, with the exception of differing between `Uncommitted` and `Committed`.

**Comment by innerlee** [comment]
Thanks! I mean
* The hover, and
* ``Uncommitted`` specifically.

**Comment by eamodio** [comment]
@innerlee Ah that makes sense -- the hover is kind of useless when in the `Uncommitted` case. I'll look into removing it.

**Comment by eamodio** [comment]
@innerlee fixed in v2.5.6
