### ISSUE TITLE
Menu shortcuts/mnemonics not working when GitLens is enabled

### ISSUE THREAD

**Issue by stianl** [eamodio/vscode-gitlens#322]
- GitLens Version: 8.1
- VSCode Version: 1.21.0
- OS Version: Ubuntu

Steps to Reproduce:

1. Open VSCode
2. Open any file not from folder
3. Press ALT and click H or S

Pressing ALT highlights the mnemomics in the application menu allowing one to click any of them to open the menu (E.g. ALT-H to open the Help menu and ALT-S for the selection menu). This does not work when GitLens is disabled since the extension seems to hijack some of the combinations.

![screenshot from 2018-03-21 07-50-54](https://user-images.githubusercontent.com/169642/37697409-ff589c4a-2cdc-11e8-9fc6-063061cf93cd.png)

**Comment by eamodio** [comment]
Please open the GitLens settings (run *GitLens: Open Settings* from the command palette) and jump to Keyboard Shortcuts and change it to either the `chorded set` or `custom set`. The 'alternate set` which used to be the default, can both conflict with mnemonics and entering characters in different keyboard layouts.

While the `chorded set` is the new default, I didn't want to change the settings of existing installs.

Hope that helps.
