### ISSUE TITLE
Commit Search shortcut disables the backslash key on german macOS

### ISSUE THREAD

**Issue by eugenk** [eamodio/vscode-gitlens#323]
> ## Commit Search
> Adds a Search Commits command (gitlens.showCommitSearch) with a shortcut of `alt+/` to search for commits by message, author, file(s), commit id, or code changes

https://github.com/eamodio/vscode-gitlens/tree/e81d893bdd7b80ff8d4d67b78785389e439eac61#commit-search

On a german macOS, the keybinding `alt+/` collides with the backslash (`shift+alt+7`). Hence, with the default config, I cannot type a backslash into my code because it opens the Commit Search. I just want to hint at an unlucky default config ;)

**Comment by eamodio** [comment]
Please open the GitLens settings (run *GitLens: Open Settings* from the command palette) and jump to Keyboard Shortcuts and change it to either the `chorded set` or `custom set`. The `alternate set` which used to be the default, can both conflict with mnemonics and entering characters in different keyboard layouts.

While the `chorded set` is the new default, I didn't want to change the settings of existing installs.

Hope that helps.
