### ISSUE TITLE
branch info didn't update after refresh button clicked after changing remote url(git remote set-url xxx) except reinstall

### ISSUE THREAD

**Issue by gemmi** [eamodio/vscode-gitlens#324]
- GitLens Version: 8.1.1
- VSCode Version: 1.20.0
- OS Version: win7 64bit

Steps to Reproduce:

1. change remote url via terminal (`git remote set-url origin xxx`)
2. click "refresh" button , but braches information didn't update
3. reinstall gitlens and branches information are right

**Comment by eamodio** [comment]
I can replicate that it won't refresh the branches after setting the url, because you'd need to do a `git fetch <remote>` first. Then GitLens should update the view appropriately.

**Comment by eamodio** [comment]
@gemmi does that resolve the issue for you?

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
