### ISSUE TITLE
Keybinding for Alt - prevents to type pipe char

### ISSUE THREAD

**Issue by atilkan** [eamodio/vscode-gitlens#326]
Default keybinding for something is this: **alt + -**
It prevents to type pipe character **|**

**Comment by eamodio** [comment]
Please open the GitLens settings (run *GitLens: Open Settings* from the command palette) and jump to *Keyboard Shortcuts* and change it to either the `chorded set` or `custom set`. The `alternate set` which used to be the default, can both conflict with mnemonics and entering characters in different keyboard layouts.

While the `chorded set` is the new default, I didn't want to change the settings of existing installs.

Hope that helps.

**Comment by atilkan** [comment]
Another shortcut prevents to type back tick. This extension great but no need shortcuts.

**Comment by eamodio** [comment]
@atilkan if you set it to `custom set` it won't add any shortcuts &mdash; you'd have to add them yourself.
