### ISSUE TITLE
Text of the Info Bounces when Typing by it

### ISSUE THREAD

**Issue by besteman** [eamodio/vscode-gitlens#329]
- GitLens Version: 8.1.1
- VSCode Version: 1.22
- OS Version: Windows 10

Steps to Reproduce:

1. Start typing
2. Text bounce on the info shown

![alt-text](http://besteman.io/3P1K3z230J21/Screen%20Recording%202018-03-28%20at%2010.28.34%20AM.gif)

**Comment by eamodio** [comment]
Freaky -- haven't seen that one before. :) GitLens doesn't have direct control over that display. This would be a vscode bug -- can you please open an issue in the vscode repo about this?

**Comment by eamodio** [comment]
I'm going to close this because there isn't anything GitLens can do here -- this is purely a vscode bug.
