### ISSUE TITLE
Commit messages can causes markdown formatting in hovers

### ISSUE THREAD

**Issue by aiiak** [eamodio/vscode-gitlens#33]
When message starts with # symbol, it is displayed as title and looks messy.

 ![img_27022017_094903_0](https://cloud.githubusercontent.com/assets/14100012/23354540/b66b5246-fce2-11e6-8e87-d35f4b0db7e6.png)

Do markdown support is really necessary here  or just messages is't properly escaped ? 
p.s. 
If this is a feature, is there some option to disable markdown support  in tooltips?

**Comment by eamodio** [comment]
@aiiak thanks for the report -- this is a bug. I'm not properly escaping the message.

**Comment by batisteo** [comment]
I think it’s happening again. Could you check if there was a regression?
Using 4.0.1

**Comment by eamodio** [comment]
@batisteo the latest [GitLens beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v4.1.0-beta.2) should fix this issue. Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know if you experience any issues -- thanks!

**Comment by jackhorton** [comment]
thanks for the quick response!
