### ISSUE TITLE
Show changes in my branch only (`..` comparison instead of `...`)

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#330]
Commands like _Compare with HEAD_ do a triple-dot comparison, e.g., `master...my-branch`. This lists new stuff in my-branch but also new commits in `master`. (This has been introduced in #240 / 54941e60687afe4fe9e1eeed934c8210520dd30d.)

In practice, I'm much more often interested in changes in `my-branch` only, which is done using a double-dot comparison `master..my-branch`.

**Comment by eamodio** [comment]
@borekb Is this something a global setting would solve for you? If I were to offer a choice -- what would you name it?

**Comment by borekb** [comment]
I'd probably keep the two-dot comparison only – it's something I want in 99% cases. Actually, I can't remember when I last needed the three-dot one.

**Comment by eamodio** [comment]
There is now a `gitlens.advanced.useSymmetricDifferenceNotation` setting which can be set to `false` to use the `..` notation rather than the `...` default.
