### ISSUE TITLE
Code lens shows on every import in Python

### ISSUE THREAD

**Issue by LambiekNL** [eamodio/vscode-gitlens#331]
![image](https://user-images.githubusercontent.com/19410118/38244943-9473b332-373c-11e8-833b-b4d6619ef07b.png)

- GitLens Version: 8.2
- VSCode Version: 1.21.1
- OS Version: Linux Mint 18.3 Sylvia

Steps to Reproduce:

1. Create new Python file
2. Insert following code:
#!/bin/python

import os
import threading

def test():
    pass

test()
3. First commit
4. Add some code
import time
5. Second commit

**Comment by felocru** [comment]
I have the same problem, I see exactly the same message on each line.
Will there be any option to avoid duplicate messages? Only appear once:
"You, a few seconds ago"
![image](https://user-images.githubusercontent.com/11906313/38258689-c17c4c90-3728-11e8-908f-fdba41700d8a.png)

**Comment by felocru** [comment]
I deactivated the option: "Containers scope -- added at the start of modules, classes, interfaces, etc". 
And now it is better appreciated.
![image](https://user-images.githubusercontent.com/11906313/38259582-01d03408-372b-11e8-839a-e3b6db2081bf.png)

**Comment by eamodio** [comment]
@LambiekNL @felocru Can one of you try setting `"gitlens.debug": true` and then send a screen shot of those code lens above the imports? That will give the type of symbol of that type and it can be turned off directly (I can also add it into the default set to ignore as well).

**Comment by LambiekNL** [comment]
@eamodio Sure:

![image](https://user-images.githubusercontent.com/19410118/38291394-dcfc2208-37df-11e8-853d-d4f97759fe5f.png)
