### ISSUE TITLE
Submodules not in the root directory could not be detected

### ISSUE THREAD

**Issue by psychelzh** [eamodio/vscode-gitlens#332]
- GitLens Version: 8.2.0
- VSCode Version: 1.21.1
- OS Version: Windows 10 1709 (16299.309)

See the following screenshots, submodule in the directory `/data/refs` does not show:

![2018-04-04_li](https://user-images.githubusercontent.com/13306020/38290906-ff25d29a-380f-11e8-9afd-1b8ec245d1c9.jpg)

**Comment by eamodio** [comment]
I think this might be an issue with the search depth -- as GitLens only searches directory level deep by default. Although if you open a file from that repo, it should auto-detect it an then add it. Can you try setting `gitlens.advanced.repositorySearchDepth` to something greater than 1 and see if that helps?

**Comment by psychelzh** [comment]
Thanks @eamodio It really works! I close this issue now.
