### ISSUE TITLE
Feature request: merging

### ISSUE THREAD

**Issue by lolmaus** [eamodio/vscode-gitlens#334]
I've been very happy to switch to VS Code, but I still have to revert to IntelliJ IDEA for merging.

IDEA has:
* selection of merge branch and options,
* listing of conflicting files,
* a three-pane merge conflict resolution tool,
* listing of merge results.

I would like to fully rely on VS Code, but I need these features for my everyday work.

![image](https://user-images.githubusercontent.com/200884/38418426-035cd0de-39a5-11e8-9b93-5dc8a0f625b4.png)

![image](https://user-images.githubusercontent.com/200884/38418287-6f57099a-39a4-11e8-8e7a-1e00f45c6e24.png)

![image](https://user-images.githubusercontent.com/200884/38418371-d1c29b12-39a4-11e8-9642-798cd5145b50.png)

![image](https://user-images.githubusercontent.com/200884/38418233-3d6c8f18-39a4-11e8-80bf-7bde46ad1c8f.png)

**Comment by eamodio** [comment]
Unfortunately I feel like this is beyond the scope of my intent and desires for GitLens. I would encourage you to make this request on the vscode repository for the built-in Git extension, since it would be much better suited to this type of feature. Sorry.
