### ISSUE TITLE
Add ability to use -C option for blame

### ISSUE THREAD

**Issue by Mathe172** [eamodio/vscode-gitlens#337]
Would it be possible to add the ability to specify `-C` (or even `-C -C` and `-C -C -C` with custom thresholds, e.g. `-C30`) for the command used to generate the blame annotations? This would allow better tracking of lines that where moved/copied from one file to another.

**Comment by lukas-lang** [comment]
Thanks for the quick implementation of this feature! One note: It seems you've made a mistake in the type specification of the config setting:

![image](https://user-images.githubusercontent.com/33105866/39010150-094dc322-440e-11e8-8c4b-e295aecacfc2.png)

**Comment by eamodio** [comment]
I added a new `gitlens.advanced.blame.customArguments` setting, which takes a string array of arguments that will be passed on to the `git blame` command

For example, `"gitlens.advanced.blame.customArguments": ["-c", "-c"]` to pass `-c -c` to git blame
