### ISSUE TITLE
Problem with GIT Repos inside of a subfolder

### ISSUE THREAD

**Issue by ozanakc** [eamodio/vscode-gitlens#338]
- GitLens Version: 8.2.0
- VSCode Version: 1.22.1
- OS Version: MacOS HighSierra 10.13.3 (17D47)

Steps to Reproduce:

1. Create a GIT repo named **X** and add a subfolder named **test**
2. add **test** folder to gitignore
3. Clone another repository named **Y** inside of test folder
4. Make changes inside of test folder.

Expected:
- Changes should be sent to subfolder's GIT REPO **Y**

Result:
- It says there is no change.

**Comment by ozanakc** [comment]
After a research, i think it's about VSCode itself. Is there any workaround to fix this problem with GIT Lense.

**Comment by eamodio** [comment]
Unfortunately this is all in the vscode Git camp. GitLens can't help out with this issue. Best to file an issue with vscode. Sorry.
