### ISSUE TITLE
Open file should open the selected version of the file

### ISSUE THREAD

**Issue by cateyes99** [eamodio/vscode-gitlens#34]
In "**Show File History**" feature, click a particular commit on the list, it shows "**go back**", "**Compare with Previous Commit**", "**Compare with Working Tree**", and "**Open File**" etc., when clicking "**Open File**", it doesn't open the version of previously selected commit, instead just open the file currently in the folder! That's less interesting. It should open the the version of the selected commit.

**Comment by eamodio** [comment]
@cateyes99 Thanks for the feature request -- funny enough I was just talking about implementing this earlier today! Look for it in the next GitLen release.
