### ISSUE TITLE
code lens can not be toggled off

### ISSUE THREAD

**Issue by vgrafe** [eamodio/vscode-gitlens#340]
Hi!

- GitLens Version: 8.2.1
- VSCode Version:1.22.1
- OS Version:macos 10.12.6

On my laptop, using "toggle git code lens" or changing the setting `gitlens.codeLens.enabled` to `false` does not hide the author info on selected line in the editor.

Maybe it is the wrong setting to do so? I also added `editor.codeLens` and `gitlens.codeLens.authors.enabled` as false to my user settings, without success.

Thanks for helping on this!

**Comment by vgrafe** [comment]
Clarification is needed - I just realized that the code lens appears on top of code blocks. I am talking about the annotation at the right of the currently edited LOC.

<img width="780" alt="screen shot 2018-04-13 at 11 44 41 am" src="https://user-images.githubusercontent.com/3950855/38744555-16ee8a3c-3f10-11e8-9f8a-7e004482c966.png">

**Comment by eamodio** [comment]
It is easiest to use the built-in Settings UI in GitLens (type `GitLens: Open Settings` in the command palette) as it is an interactive editor which will allow you to toggle most of GitLen's features easily. The setting you are looking for is in the *Current Line Blame* section.

But the setting in question is `"gitlens.currentLine.enabled": false`
