### ISSUE TITLE
GitLens crashes while debugging with Chrome Debugger a larger project

### ISSUE THREAD

**Issue by Leninsky** [eamodio/vscode-gitlens#342]
- GitLens Version:  8.2.1
- VSCode Version: 1.22.2
- OS Version:  Windows 10.0.16299 Build 16299

Steps to Reproduce:

1. Open a chrome debugging session with F5
2. Observe that the inline blame messages disappear
3. GitLens sometimes crashes completely when comparing a file with previous revision.

[gitlens.log](https://github.com/eamodio/vscode-gitlens/files/1914953/gitlens.log)

My other extensions : 
![screenshot_4](https://user-images.githubusercontent.com/72609/38805407-6204c1c4-417e-11e8-978a-2d9da9ea76cd.png)

**Comment by eamodio** [comment]
I will fix the errors you are seeing, but the behavior that the inline blame disappears when debugging is intentional as to not conflict with the inline variable decorations and debug hovers.
