### ISSUE TITLE
Can't show blame when VSCode starts on branch without upstream

### ISSUE THREAD

**Issue by benzittlau** [eamodio/vscode-gitlens#343]
- GitLens Version: 8.2.1
- VSCode Version: 1.22.2
- OS Version: OS X 10.13.1

Steps to Reproduce:

1. Open VSCode while on a branch without an upstream
2. Toggle Line Blame Annotations

I'm encountering an issue where if VSCode launches while the project directory is on a branch that doesn't have an upstream, attempts to toggle file blame annotations will fail with the error:

`No upstream configured for branch <branch name>`

![development_rb_ _jobber](https://user-images.githubusercontent.com/366749/38839245-f797e87a-4196-11e8-88be-5ca40986d445.png)

I attempted to enable `"gitlens.outputLevel": "verbose",` to record any output, but no output was visible in the output pane after adding that setting and restarting VSCode.

**Comment by benzittlau** [comment]
Just saw the same issue after:

1. Start VSCode on a branch *with* an upstream
2. Switch to a branch without an upstream
3. Open a new file 
4. Toggle Line Blame Annotations

**Comment by benzittlau** [comment]
@eamodio You just made my day!  Confirmed locally that with version 8.2.3 I am no longer seeing this issue.  Thanks for your active support of this project!

**Comment by eamodio** [comment]
Awesome glad to hear it is actually fixed! 😄

**Comment by ryenus** [comment]
I still have this issue on with 8.3.3 :-(

**Comment by ryenus** [comment]
Here the error I got is.

<pre>
> git rev-parse --symbolic-full-name my_branch@{u}
fatal: upstream branch 'refs/heads/my_branch' not stored as a remote-tracking branch
</pre>

Git version `2.17.1`

**Comment by ryenus** [comment]
FYI, I've created pull request #390.
