### ISSUE TITLE
Merge Conflict Actions Missing

### ISSUE THREAD

**Issue by shane-lawrence** [eamodio/vscode-gitlens#344]
When GitLens is enabled, vscode doesn't show any actions for resolving merge conflicts. There should be buttons for "Accept Current Change", "Accept Incoming Change", "Accept Both Changes", and "Compare Changes".

- GitLens Version: 8.2.1
- VSCode Version: 1.22.2
- OS Version: 10.13.4

Steps to Reproduce:
1. Disable GitLens.
2. Reload vscode.
3. Open a file that has a merge conflict.
4. Observe that merge conflict actions are present.
![image](https://user-images.githubusercontent.com/8320787/38882881-6330ec60-4239-11e8-9854-b6bc2e4dd0f7.png)
5. Enable GitLens.
6. Reload vscode.
7. Open a file that has a merge conflict.
8. Observe that there are no merge conflict actions.
![image](https://user-images.githubusercontent.com/8320787/38882974-a9de544a-4239-11e8-8dde-41cc102f4747.png)

**Comment by eamodio** [comment]
This is a duplicate of #319. You can see my comment here: https://github.com/eamodio/vscode-gitlens/issues/319#issuecomment-374625812

Can you provide more details on that issue? Thanks!

**Comment by t0lkman** [comment]
I have `Accept incoming changes` but it looks like it does `Accept current changes`

Can somebody clarify which are the changes made locally?

**Comment by eamodio** [comment]
@t0lkman that feature is provided by VS Code not GitLens, so you'd need to open an issue on the vscode repo

**Comment by stevenmchoi** [comment]
Solution comment: https://github.com/eamodio/vscode-gitlens/issues/319#issuecomment-429852369

**Comment by stevenmchoi** [comment]
> I have `Accept incoming changes` but it looks like it does `Accept current changes`
> 
> Can somebody clarify which are the changes made locally?

@t0lkman `Accept current changes` means to keep the code on the branch you are currently checked out on locally. `Accept incoming changes` means to replace your code with the new code that you're bringing into your current branch.

**Comment by t0lkman** [comment]
@stevenmchoi thanks for info!  The wording is convoluted... why not just say "Keep current" or "Accept change"

**Comment by stevenmchoi** [comment]
@t0lkman I know, right? I still keep getting confused for the longest time.
