### ISSUE TITLE
Custom date formats don't work in the GitLens view

### ISSUE THREAD

**Issue by hoangnamitc** [eamodio/vscode-gitlens#345]
Hi Guy,
I Want change formatDate in hover detail to D/M/YYYY : h:m:s.
How to do?

![image](https://user-images.githubusercontent.com/7042462/38907456-06c087da-42e6-11e8-9c86-c1b74ce596cb.png)

Thanks !

**Comment by eamodio** [comment]
Use the built-in GitLens interactive settings editor (run `GitLens: Open Settings` from the command palette) and in the *General* section set *Absolute date format*

**Comment by hoangnamitc** [comment]
I do like you say, but not working.

![image](https://user-images.githubusercontent.com/7042462/38910759-2c2b7d4a-42f5-11e8-92ef-945fe463d6ba.png)

**Comment by eamodio** [comment]
Hrm, I tried the same settings that you showed and it works here:
![image](https://user-images.githubusercontent.com/641685/38967306-68cdd59a-4354-11e8-8f0e-ccd45f2d3c0c.png)

What do you see?

**Comment by hoangnamitc** [comment]
hi tks, But not that.
Not that. I mean by this side

![image](https://user-images.githubusercontent.com/7042462/38967439-31e26af2-43b1-11e8-87bc-74a9e2b23c13.png)

**Comment by eamodio** [comment]
Ah, I recently added those new tooltips and failed to make them honor the date format. Thanks, I'll get that fixed!
