### ISSUE TITLE
How to display working tree changes to HEAD on the left side of the editor

### ISSUE THREAD

**Issue by aalexgabi** [eamodio/vscode-gitlens#347]
Some time ago I could see changes between the working tree and HEAD on the left side of the editor with red for deleted lines and green for modified lines. When I would click on the color, I could revert a specific change from working tree.

About a month ago I started getting notifications from Gitlens in bottom right corner saying that I have too many files and that will stop working or something like that. This happened probably because I was in the middle of a huge merge and Gitlens did not like it.

I cannot find a way to reactivate it. I looked in settings but I don't see any option for that. Do yo have any idea hot to re-activate it again?

**Comment by eamodio** [comment]
Those decorations/features are provided by the built-in git extension in vscode, so you'd have to open an issue with the vscode repo. Sorry.
