### ISSUE TITLE
Failed to update on the latest insiders build

### ISSUE THREAD

**Issue by vvs** [eamodio/vscode-gitlens#349]
- GitLens Version: 8.2.3
- VSCode Version: latest insiders build
- OS Version: Windows 10 

See Microsoft/vscode/issues/48373

Basically, any time I am trying to udpate gitlens (since last week or so), I am presented with an error dialog: Failed to update.

**Comment by eamodio** [comment]
As GitLens installation is completely controlled by vscode itself, and the vscode issue has been resolved, I'm going to close this.
