### ISSUE TITLE
Copy Commit Sha to Clipboard not working

### ISSUE THREAD

**Issue by rrerolle** [eamodio/vscode-gitlens#35]
Hello,

I can't seem to make the "Copy Commit Sha to Clipboard" feature work, no matter how hard I try. 

I'm using version 1.9.1 on Ubuntu-Gnome 16.04.

I tried the feature using various ways: the right click contextual menu, the command palette or one of the various quick pick uis.

This has never resulted in anything being copied to the clipboard. Actually my clipboard remains unchanged and still contains what it had before.

Any way to investigate this ?

Thanks.

**Comment by eamodio** [comment]
@rrerolle It seems to be a linux specific issue. I'll dig into and see what I can come up with.

**Comment by eamodio** [comment]
@rrerolle It seems the [node package](https://github.com/xavi-/node-copy-paste) I'm using to copy to the clipboard requires that `xclip` be installed. You can install it via `sudo apt-get install xclip`.

If you install that it should start working.

**Comment by rrerolle** [comment]
That did the trick, it's now working fine, thanks for the info !

**Comment by vadimcn** [comment]
@rrerolle, I suggest you handle the case when xclip is not installed.   It happened to me and for the longest time I thought this was because of a buggy extension.  Finally I came to github to open a bug and only now found this issue :(

**Comment by eamodio** [comment]
@vadimcn GitLens 8 will display the following message if it gets an error trying to use xclip

> Unable to copy commit id, xclip is not installed. You can install it via \`sudo apt-get install xclip\`
