### ISSUE TITLE
Feature requiest: Mercurial integration

### ISSUE THREAD

**Issue by Aliaksei-Martinkevich** [eamodio/vscode-gitlens#350]
Gitlens is amazing extension that helps to work with git a lot. But from time to time I have to work with projects with mercurial. 

There is plugin for Hg support in VS Code, but it cannot be compared with GitLense.

It would be very nice if Gitlense had mercurial compatibility mode or something like this.

**Comment by eamodio** [comment]
While I would love to see GitLens extend beyond just git, there is quite a lot of code that is tightly couple to  git's features, behaviors, etc. There would have to be a LOT of work in creating an abstraction to insulate all the UI features from the underlying scm. But more than that, I, as someone who doesn't use Mercurial at all, would not be able to develop, nor maintain such a feature with the quality I would want.

Sorry.
