### ISSUE TITLE
When comparing files it always jumps to first diff line of the file when changing tabs.

### ISSUE THREAD

**Issue by krasi-georgiev** [eamodio/vscode-gitlens#351]
- GitLens Version: 8.2.4
- VSCode Version:
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:30.761Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Fedora 27

Steps to Reproduce:

1.Select branch to compare
2. Select a file to show the diff.
3. scroll down and put the cursor in the middle or anywhere else in the file.
4. select another open file
5. go back to the tab of the open diff.
the cursor is always at the first line of the diff. 

I expected to keep its scroll position when I go back and forth between files.

**Comment by eamodio** [comment]
This is a bug in vscode itself and it looks like its been fixed (again) in the insiders build, because I can repo this in 1.22.2, but can't in 1.23.
