### ISSUE TITLE
GitLens don't show diffs in the nested git repository

### ISSUE THREAD

**Issue by flkrasnov** [eamodio/vscode-gitlens#356]
- GitLens Version: 8.2.4
- VSCode Version:  1.22.2
- OS Version: Windows 10 x64

GitLens don't highlight diffs in the nested git repository (http://prntscr.com/jaeuvt).

Expected: http://prntscr.com/jaf7es

I still can see changes in `git diff`, gitlens window on the bottom left of VSCode (http://prntscr.com/jaeqqs), but not in the working area (http://prntscr.com/jaerdu).

**Comment by eamodio** [comment]
The features you are pointing to are not provides by GitLens, they are part of the built-in Git extension in vscode. You will need to open an issue on the vscode repository. Sorry.
