### ISSUE TITLE
Blame information is invalid when a file has unsaved changes

### ISSUE THREAD

**Issue by SailorMax** [eamodio/vscode-gitlens#36]
GitLens ignore new line shifts in modified file.

Steps:
1. open document modify history has few people, for example:
line 1 by user A
line 2 by user B
line 3 by user C
2. put cursor in end of line 1 and press Enter
3. check owners of lines 1-4

Expected:
line 1 by user A
line 2 (empty) has no user
line 3 by user B
line 4 by user C

Actual:
line 1 by user A
line 2 (empty) by user B
line 3 by user C
line 4 has no user

**Comment by eamodio** [comment]
@SailorMax Thanks for the report -- there are some definitely issues here and will get them fixed up!

**Comment by SailorMax** [comment]
@eamodio Same problem still exist if file was modified by external editor. VSCode catch modifications, but GitLens - not.

**Comment by eamodio** [comment]
@SailorMax can you open a separate issue for that? Also please provide the steps to reproduce it. Thanks!
