### ISSUE TITLE
Better theming support/docs

### ISSUE THREAD

**Issue by AndreasBackx** [eamodio/vscode-gitlens#360]
I'm currently working on a theme for VS Code called [Rubecula](https://github.com/Rubecula/VS-Code) and have tried to add support for GitLens. However I couldn't fully test all of the colors because I don't know how to reproduce them. I cannot figure out how to make the following color customizations show up:

```javascript
// Specifies the background color of the trailing blame annotation
"gitlens.trailingLineBackgroundColor": "untested",
// Specifies the foreground color of the trailing blame annotation
"gitlens.trailingLineForegroundColor": "untested",
```
_Note that `untested` is converted to the color red._

Could you describe in steps how I could see these colors manifest themselves so I can add support for them? Is it perhaps possible to include some screenshots as well?

Secondly whenever I open the git blame window, GitLens apparently adds a red border (it might be retrieved from the color scheme because it looks like the red I use for errors). Is it possible to change this somewhere or am I missing something?

![Screenshot red border](https://i.imgur.com/4S99FfA.png)

Lastly I was wondering whether it was possible to change the color of this blue line in the Git blame gutter. It seems to be an image that is repeated.

![Screenshot blue line](https://i.imgur.com/j6mug9i.png)

**Comment by eamodio** [comment]
I'd recommend checking out the interactive settings editor that GitLens provides (run `GitLens: Open Settings` from the command palette) as from there you can see all the different features easily.

As for the theme colors, `gitlens.trailingLineForegroundColor` & `gitlens.trailingLineBackgroundColor` apply to the blame annotation for the current line, see the `You, 5 months ago...` 
![image](https://user-images.githubusercontent.com/641685/39609838-e32e357a-4f19-11e8-9c8a-27ac4fdf68ba.png)

The "redish" colors on the side of the blame annotations is a heatmap, and those colors aren't currently configurable -- if you would like for them to be configurable (probably just a start and end color) could you please open a separate issue for that?

The blue line is a gutter indicator of all lines that are part of the same commit as the current line, and the color of that is also not currently configurable. And that one is a bit trickier because that is actually an image (svg).

**Comment by AndreasBackx** [comment]
> I'd recommend checking out the interactive settings editor that GitLens provides (run GitLens: Open Settings from the command palette) as from there you can see all the different features easily.

Neat, I didn't know that.

> As for the theme colors, gitlens.trailingLineForegroundColor & gitlens.trailingLineBackgroundColor apply to the blame annotation for the current line, see the You, 5 months ago...

I should've enabled all of the settings to test it out and I would've seen that. I've got that setting disabled. Thank you!

> The "redish" colors on the side of the blame annotations is a heatmap, and those colors aren't currently configurable -- if you would like for them to be configurable (probably just a start and end color) could you please open a separate issue for that?

Will do.

> The blue line is a gutter indicator of all lines that are part of the same commit as the current line, and the color of that is also not currently configurable. And that one is a bit trickier because that is actually an image (svg).

Any reason as to why this is an SVG instead of a color? Even if it is an SVG, depending on what VS Code allows regarding SVGs we can perhaps change the colors of the SVG. (I haven't looked into it, but it seems like SVGs are restricted somewhat, I assume some security stuff?) Should I add this to the issue regarding the heat map as well or also a separate issue to talk about this?

**Comment by eamodio** [comment]
I would suggest separate issue for both. The reason why it is an SVG is because of the limitations of the vscode api for the gutter only allows for an image path.

**Comment by jsilvermist** [comment]
Regardless of customizability, is there any way to have different colors depending on the change?

For example, green for addition, yellow for change, red for deletion?

**Comment by eamodio** [comment]
@jsilvermist Which colors are you wanting to customize? Can you show a screenshot?

**Comment by jsilvermist** [comment]
@eamodio Honestly, I'm not really sure what I meant at this point, seeing as you already said that "the color of that is also not currently configurable" regarding the gutter colors for indicators.

Feel free to just ignore this for now, though it would be nice to be able to configure them in the future!

**Comment by AndreasBackx** [comment]
@eamodio sorry for the delay on making the issues. I'm in the middle of my finals, but I thought I'd just make them right now cause I had some time.

**Comment by eamodio** [comment]
I'm going to close this in favor of the specific issues.
