### ISSUE TITLE
Add gitlens as activity bar item instead of panel in explorer item

### ISSUE THREAD

**Issue by PixelT** [eamodio/vscode-gitlens#363]
More details about this:
https://code.visualstudio.com/updates/v1_23#_extension-authoring

**Comment by eamodio** [comment]
I thought about going down this route (and maybe I will in the future), but my plan is to move GitLens into the SCM activity. I originally thought that I could make it a user choice, but currently that really isn't possible with the provided apis/structures.

Hopefully moving to the SCM view is an acceptable compromise.

**Comment by MattSturgeon** [comment]
I'm in favour of git lens being either integrated into the Source Control view or its own view using the new [1.23 API](https://code.visualstudio.com/updates/v1_23#_extension-authoring). Either way it doesn't make much sense to me being in the Explore view.

I think it could look rather neat if it was in the SC view, but I have no idea how difficult this is compared with having its own view.
