### ISSUE TITLE
Unknown user in the lens

### ISSUE THREAD

**Issue by Darksoulsong** [eamodio/vscode-gitlens#365]
Where do Gitlens gets the author name information from? I have git user.name set, but the lens only displays "unknown" after the commit.

I'm using Gitlens v8.2.4 on Vscode v1.19.2

![image](https://user-images.githubusercontent.com/2078582/39630448-b6f58f28-4f85-11e8-8964-1dd3950fd2f3.png)

**Comment by eamodio** [comment]
GitLens gets the name from the `author` name of the commit. That should come from `user.name` if set at the time of the commit.

You should be able to see the name that GitLens will show by running `git log --format="%h %an" -n10`
