### ISSUE TITLE
"Running the contributed command:'gitlens.diffWithPrevious' failed." with keybinding not working

### ISSUE THREAD

**Issue by etiennejcharles** [eamodio/vscode-gitlens#366]
- GitLens Version: 8.2.4
- VSCode Version: Version 1.24.0-insider (1.24.0-insider)
- OS Version: 10.13.4

Steps to Reproduce:

1. Disable all extensions, run it with the insiders build with only Gitlens enabled. 
2. In your settings.json only keep the `"gitlens.keymap": "alternate",` setting. 
2. Try to run the keyboard shortcut `alt+,`
3. See the bug

**Comment by eamodio** [comment]
Thanks for the report, it looks like a recent change to the insiders build broke me: https://github.com/Microsoft/vscode/issues/42851

**Comment by eamodio** [comment]
FYI, I've released a beta version of the upcoming 8.3 release here with this fixed: https://github.com/eamodio/vscode-gitlens/releases/tag/v8.3.0-beta
