### ISSUE TITLE
code intellisense becomes super slow with gitlens enabled

### ISSUE THREAD

**Issue by frankyjuang** [eamodio/vscode-gitlens#367]
- GitLens Version: 8.2.4
- VSCode Version: 1.23.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. autocomplete popups immed while typing.
2. enable gitlens
3. took seconds for autocomplete to popup

Gitlens is really great so far, but started to experience this today. Not sure what infos should I provide. Thanks.

**Comment by eamodio** [comment]
@frankyjuang I haven't seen GitLens cause any slowdowns with autocomplete (honestly I couldn't see how as GitLens doesn't hook into autocomplete in any way). Can you provide a video/gif of what you are seeing with GitLens disabled and enabled?

Also please provide the language you are using as well.
