### ISSUE TITLE
Show image diff

### ISSUE THREAD

**Issue by smallma** [eamodio/vscode-gitlens#368]
- GitLens Version: 8.2
- VSCode Version: 1.22.2
- OS Version: MacOS 10.13.1

Gitlens display code difference, but image not. Is it possible to display image diff on git? Thanks.

**Comment by eamodio** [comment]
GitLens relies on the diff abilities of vscode itself, so I would recommend opening an issue with vscode to add image diff support. I would also need to have support for https://github.com/Microsoft/vscode/issues/49914 as well.
