### ISSUE TITLE
Is 'Compare File with Previous Revision' really [Ctrl+Shift+G ,]?

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#369]
Context menu shows me this:

![image](https://user-images.githubusercontent.com/101152/39798785-2dfe8888-5362-11e8-8e1a-6214df944508.png)

However, when I press Ctrl+Shift+G and `,`, it takes me to the Git sidebar and then just writes a comma into the commit message box.

`Alt+,` seems to work for me.

Not sure if related but I use `"gitlens.keymap": "alternate"`, not `chorded`.

- GitLens Version: 8.2
- VSCode Version: 1.23.0
- OS Version: Win10

**Comment by eamodio** [comment]
Sadly this is a vscode issue: https://github.com/Microsoft/vscode/issues/40389
