### ISSUE TITLE
Code lens "recent change" shows on every Python import statement that imports a Class or Function SymbolKind

### ISSUE THREAD

**Issue by phillipdwright** [eamodio/vscode-gitlens#371]
- GitLens Version: 8.2.4
- VSCode Version: 1.23.0
- OS Version: Windows 10 Version 1803

Steps to Reproduce:

1. Include Python import statements of the form `from X import Y`, where Y is a class or function. Eg.,
```py
from unittest import TestCase
from unittest.mock import patch, Mock
from unittest import mock


class SampleTestCase(TestCase):
    def test_something(self):
        mock_patch = Mock(patch)
        self.assertTrue(isinstance(mock_patch, mock.Mock))
```
2. Observe that Code lens "recent change" annotations are listed above every import statement that imports a class or function.

62a7eaf368ef10ae170a3f8d358afaab9dcbd9f3 removed these annotations for imports of the form `import X` or `from X import Y`, where `Y` is a [`SymbolKind.Module`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#SymbolKind), but they remain when `Y` is any other `SymbolKind`. I know there are settings for disabling "recent change" Code lens annotations (`gitlens.codeLens.recentChange.enabled`) and for disabling Code lens annotations altogether for different `SymbolKind`s, but this removes annotations that would be helpful elsewhere in the file.

With added settings
```json
  "gitlens.debug": true,
  "gitlens.codeLens.scopesByLanguage": [
    {
      "language": "python",
      "scopes": [
        "document",
        "containers",
        "blocks"
      ]
    }
  ]
```
the example above shows as follows:
![image](https://user-images.githubusercontent.com/7881277/40076838-f7cb95a8-584d-11e8-8614-43b396c695e7.png)

Adding `"symbolScopes": ["!Module", "!Function", "!Class"]` to my settings would also remove helpful Code lens annotations on the class and function definitions in the file.

Would it be possible to have Python import statements be treated differently for purposes of Code lens and only have annotations show up for `SymbolKind.File` on those lines?

**Comment by phillipdwright** [comment]
Awesome product, by the way! I love it.

**Comment by eamodio** [comment]
Unfortunately right now I don't think there is much I can do to address this. Although once https://github.com/Microsoft/vscode/issues/34968 lands I might be in a better position to be able to address this issue depending on the data provided by the language service and how abstract it can be.

Thanks! 😄

**Comment by ryotat** [comment]
I also had this issue but updating to VS Code (1.24.1) and Gitlens (8.4.0) seem to have fixed the issue. Thanks!

**Comment by eamodio** [comment]
I'm not sure why this changed -- maybe the python language service changed at the same time. @phillipdwright are you seeing this fixed as well?

**Comment by eamodio** [comment]
Err. Nevermind, this was fixed as part of https://github.com/eamodio/vscode-gitlens/issues/331

**Comment by fgs-pwright** [comment]
#331 fixes this for imports of the form `import X` or `from X import Y`, where `Y` is a `SymbolKind.Module`. But the "recent change" annotations remain when `Y` is any other `SymbolKind`.  In particular, I still see this issue for imports of the form `from X import Y`, where `Y` is a `SymbolKind.Class` or a `SymbolKind.Function`.

As a workaround, I have `"gitlens.codeLens.recentChange.enabled": false` in my User Settings, but I know I'm missing out on a helpful feature.

I have updated to VS Code 1.24.1 and GitLens 8.4.0.

**Comment by eamodio** [comment]
The only real option there is to use `gitlens.codeLens.scopesByLanguage` to pick and choose how you want each `SymbolKind` to behave. 

Maybe once Microsoft/vscode#34968 lands and the language services provide more information, I can detect that those symbols are within an import and then suppress them

**Comment by DJMcNab** [comment]
Microsoft/vscode#34968 has landed, but it doesn't seem to give what we would need (unless I'm misunderstanding something).

I came to this issue because of a similar issue with @matklad's [rust-analyzer](https://github.com/matklad/rust-analyzer), where there is recent changes for every simple `mod` statement, which doesn't seem right:

![image](https://user-images.githubusercontent.com/36049421/46261209-1515b100-c4e8-11e8-8365-981b45c6ef5f.png)

**Comment by eamodio** [comment]
Microsoft/vscode#34968 didn't expose any more information to GitLens, but https://github.com/Microsoft/vscode/issues/57984 fixed that (which will be released when the vscode 1.28 ships).

I have also made some changes in the next release of GitLens, to stop adding the authorship codelens unless the symbol is more than 1 line -- which should help with this issue as well.

**Comment by DJMcNab** [comment]
Yeah - that change to stop one line recent changes is a good thing - that looks like it should fix it. Sorry to have bothered you!

**Comment by eamodio** [comment]
No bother at all -- your post prompted me to add the single line change! 😄

**Comment by eamodio** [comment]
I'm going to close this, as I believe this has been addressed now.
