### ISSUE TITLE
Wrong URL to VSTS work item when using hash work item id in commit

### ISSUE THREAD

**Issue by Episodex** [eamodio/vscode-gitlens#372]
I'm using work items ids as hashes in commit to automatically link commits to work items in VSTS. For example commit message: `initial commit #101` will link this commit to work item number 101 in VSTS. GitLens will correctly parse this hash and will make it clickable in the commit details popup. But it goes to wrong url. The url GitLens redirects to is:

`https://example.visualstudio.com/_git/MyProject/_workitems/edit/101` 

which gives 404, as the correct url is:

`https://example.visualstudio.com/MyProject/_workitems/edit/101` (notice `_git` removed).

I couldn't find any way to configure base address for work items in GitLens config. Is there something wrong with my VSTS configuration or is it some kind of a bug in the extension?

**Comment by eamodio** [comment]
@Episodex in your `.git/config` file what does the remote url have the `_git` part in it? And do the other GitLens remote commands work? e.g. Open File in Remote, Open Commit in Remote, etc?

**Comment by Episodex** [comment]
@eamodio Yes, remote url has `_git` in it. The line is:

`url = https://example.visualstudio.com/_git/MyProject`

Open File in Remote works. Open Commit also. It's only Open Work Item that doesn't work because on VSTS work items urls are not under `_git` folder. I don't know if this is true for all VSTS repos or my configuration is unusual.

**Comment by eamodio** [comment]
Honestly I don't have enough (read: much at all) experience with VSTS, but I'll look for `_git` in the url and strip it out. Thanks for the info!

**Comment by Episodex** [comment]
Yes! It's perfect now. Thank you for so fast fix :). I just hope this change doesn't break anything for other people. But it looks like VSTS does it this way, so it should rather fix the issue for everyone.

Thanks again!

**Comment by eamodio** [comment]
No problem! Yeah, hopefully this will work for everyone :)
I'll get this into the next patch release, so probably in the next day or two.
