### ISSUE TITLE
Support Co-Authored-By

### ISSUE THREAD

**Issue by Nevon** [eamodio/vscode-gitlens#373]
Github introduced a convention where the commit message contains a list of co-authors, for use when pairing.

Example:

```
commit 032db38255275dd7372f575e3d06947c878ef4c6
Author: Tommy Brunn <foo@gmail.com>
Date:   Thu May 17 10:21:16 2018 +0200

    Encode int64

    Co-Authored-By: Tulio Ornelas <bar@gmail.com>
```

Both Github and Atom then displays both authors whenever they are showing author information. See http://blog.atom.io/2018/04/18/atom-1-26.html#github-package-improvements-1 for an example of what it looks like in Atom.

**Comment by eamodio** [comment]
While I could provide a command or menu that (in theory) could add the co-author into the Source Control input, I couldn't make it nice and integrated like Atom. For that to happy vscode would need to add this feature into the Git extension itself. I will think about it some more, but I would recommend you request this feature on the vscode repo as well.

**Comment by Nevon** [comment]
Ah, thanks. I wasn't sure if this was provided by vscode's Git extension or you. I'll open an issue there instead.

**Comment by Nevon** [comment]
Opened Microsoft/vscode/issues/50090
