### ISSUE TITLE
noticeable time difference when resolving merge conflicts

### ISSUE THREAD

**Issue by minoseah629** [eamodio/vscode-gitlens#374]
There was a noticeable difference in time after merging a branch and there is a conflict to resolve. 

vs code
https://www.screencast.com/t/d4bxar82g4C

vs code-insider
https://www.screencast.com/t/bvXKV3IO

- GitLens Version: 8.3
- VSCode Version: Version 1.24.0-insider
- OS Version: Windows 10 1803

Steps to Reproduce:
1. do a git merge with 1 conflict
2. open file with conflict

**Comment by eamodio** [comment]
GitLens doesn't provide the merge conflict support, that is built into the Git extension in vscode itself. I would recommend reporting this issue on the vscode repo. Sorry.

**Comment by minoseah629** [comment]
did you even look at the either of the screencasts?

**Comment by minoseah629** [comment]
@eamodio, it appears back to an acceptable time now.
