### ISSUE TITLE
Feature request: Ability to configure gitlens view group

### ISSUE THREAD

**Issue by bigopon** [eamodio/vscode-gitlens#377]
In latest version, Gitlens view is moved to source control view, which I don't believe is desirable all the times. My workflow when contributing to a project can involve / require changes across few branches, and having Gitlens history list view to help me stay aware of what git-related stuff I'm actually doing is very useful.

#213 argument is to have the explorer view clean, I agree to disagree. Once the project grows to certain size, the `Folders` explorer view starts to lose its usefulness, and searching file via file name in VSCode command should be the preferred way (Love to know what is better here), so having Gitlens or not in explorer view will not affect the `Folders` view at all

**Comment by bigopon** [comment]
Very nice, thanks 👍

**Comment by bfsmithATL** [comment]
Thanks so much for doing this!! I was literally just in the process of writing up a new feature request to allow toggle it back to Explorer and @bigopon beat me to it! :-) Gitlens is awesome btw, I use it daily!
