### ISSUE TITLE
Hiding a GitLens explorer from the Source Control view causes vscode to behave badly

### ISSUE THREAD

**Issue by sanket-bhalerao** [eamodio/vscode-gitlens#378]
Issue Type: <b>Bug</b>

tabs are not working properly after enabling git lens
explorer
search
git
debug
plugins

Extension version: 8.3.0
VS Code version: Code - Insiders 1.24.0-insider (912fff91ac4ff1bff9695e8da69abd729f7ae956, 2018-05-18T05:17:26.925Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.96GB (2.76GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sanket-bhalerao** [comment]
when i enable gitLens, clicking on the explorer tab will show a blank explorer window, have to click again in order to see files. in the search tab and the plugins tab the upper half is empty and the search box and installed plugins are shown afterwords. when i disable git lens everything goes back to normal.
i am using the insiders build

**Comment by eamodio** [comment]
Wow I've never heard of any issues like that, nor can I even guess to how it would be possible. My only thought is that there is something corrupted in your install either with GitLens or vscode itself. Can you completely remove GitLens and restart vscode twice and make sure GitLens is removed from your .vscode-insiders folder. Then make sure you don't experience any issues and then reinstall GitLens and see if the problem persists.

**Comment by sanket-bhalerao** [comment]
uninstalled Git lens
restarted VSC twice
installed git lens
reloaded. but issue still there. please find screenshot attached.
![image](https://user-images.githubusercontent.com/9264813/40220121-ad3aec60-5a95-11e8-8ab1-89c9d104a857.png)

**Comment by ruggi** [comment]
Confirming this issue is definitely real (macOS 10.13.4), as reported by @sanket-bhalerao.
Another weird thing: getting `cannot set property 'setVisible' of undefined` whenever opening the source control pane.
<img width="486" alt="screen shot 2018-05-18 at 10 24 39 am" src="https://user-images.githubusercontent.com/1081051/40224303-095caeb2-5a86-11e8-9f60-eb01a0f5450d.png">

**Comment by eamodio** [comment]
@ruggi are you also running the insiders build? If so can you try stable to see if you see the same behavior?

**Comment by ruggi** [comment]
@eamodio nope, I'm using the stable build of VSCode.

GitLens version: 8.3.0
VSCode version: 1.23.1 (1.23.1) d0182c3417d225529c6d5ad24b7572815d0de9ac 2018-05-10T15:58:04.452Z
OS: macOS 10.13.4

**Comment by eamodio** [comment]
@ruggi if you open the devtools, can you see if there is more information about the `setVisible` error? Or any other errors?

**Comment by eamodio** [comment]
@sanket-bhalerao Same as above -- any more information you could provide would be very helpful.

**Comment by clemmyn23** [comment]
@eamodio 
Also happening on Windows

- Windows version: 10.0.17134 Build 17134
- VSCode version: Version 1.23.1 d0182c3417d225529c6d5ad24b7572815d0de9ac
- GitLens version: 8.3.1



![image](https://user-images.githubusercontent.com/6946253/40289918-6cca0aba-5cfe-11e8-8e75-5233362ba5be.png)

**Comment by sanket-bhalerao** [comment]
@eamodio okay, however if I disable GitLens the issue does not re-occur.
Here is something weird I found for replicating the issue

- enable GitLens
- switch to the Source control tab
- switch back to Explorer tab
- at first you will see an empty explorer, click on the explorer icon again to see all your files.
- after this if you click one time on any icon from the left sidebar some weird behavior  is seen on the UI
- the 'setVisible' issue will be visible in the developer tool is visible in the console.

**Comment by eamodio** [comment]
@sanket-bhalerao Can you please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please reproduce the issue and attach the log lines from the GitLens channel.

**Comment by eamodio** [comment]
Also do you have any other extensions installed? Specifically something that adds other views? I can't reproduce the issue here.

**Comment by eamodio** [comment]
Or any other custom settings that might be triggering this behavior?

**Comment by sanket-bhalerao** [comment]
@eamodio could this be causing some issue? (this is in my user settings)
>"gitlens.historyExplorer.enabled": true

**Comment by sanket-bhalerao** [comment]
@eamodio there is a GitLens tab/view added inside the SCM window when gitlens is installed. if you disable it the issue will appear.
![image](https://user-images.githubusercontent.com/9264813/40362381-ffa399d2-5de9-11e8-8fa9-7f5b328377c8.png)
i tried this on stable as well as insiders builds.
regarding other extensions i have deleted/uninstalled all the other extensions except GitLens.
let me know in if you are able to reproduce it.

**Comment by eamodio** [comment]
Until vscode ships a version with the fix, the best work around is either to not hide the GitLens explorer via the vscode provided context menu, and instead use GitLens' setting to disable it. You can open the GitLens settings editor by running `GitLens: Open Settings` from the command palette, and from there jump to the *GitLens Explorer* section and uncheck `Show the GitLens explorer`.

**Comment by sanket-bhalerao** [comment]
@eamodio yup, already enabled them. No more issue 😁

**Comment by sanket-bhalerao** [comment]
issue is resolved for me
