### ISSUE TITLE
Office documents comparation needed

### ISSUE THREAD

**Issue by MaleDong** [eamodio/vscode-gitlens#379]
Issue Type: <b>Feature Request</b>

It seems that in TortoiseGit, we can directly compare office documents such as 'word', 'excel'……ect by opening both of the files in an office application. But we cannot compare office documents in GitLen now in VSC because it says we cannot open binary files, which is either too large to compare....:(

Would you mind adding this feature?

Extension version: 8.3.1
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:38.209Z)
OS version: Windows_NT ia32 6.3.9600

**Comment by eamodio** [comment]
GitLens builds upon the built-in diff support in vscode itself. I would recommend opening an issue with vscode itself to ask for this feature. Once vscode supported diffing office documents, GitLens would natively support it. Although, GitLens also provides commands to compare files in an external diff tool (configured in your git config), and using an external tool such as Beyond Compare could provide the support you are looking for.

Hope that helps.
