### ISSUE TITLE
why is 'show file history' removed from context menu?

### ISSUE THREAD

**Issue by bochen2014** [eamodio/vscode-gitlens#380]
already used to its presence, it's such a useful command, is it possible to bring it back? really miss it
('show file in remote' is in context menu, but I don't see it particular useful. why would you open github for source code while you have vscode which is a much more powerful tool?)

(understand I can `ctrl + shift + G, H`, but, still miss the context menu option)

**Comment by eamodio** [comment]
It is off by default to try to reduce the amount of menu items GitLens' adds out of the box. But if you open the GitLens settings editor (`GitLens: Open Settings` from the command palette) and switch into `Advanced` mode at the top, you can configure the menu items with decent granularity.

![image](https://user-images.githubusercontent.com/641685/40428979-8226b86e-5e6f-11e8-8b93-77202a2ed6b9.png)

Hope that helps.
