### ISSUE TITLE
Add ability to collapse all in explorer views

### ISSUE THREAD

**Issue by rakkarage** [eamodio/vscode-gitlens#383]
- GitLens Version: latest
- VSCode Version: insiders
- OS Version: windows

Steps to Reproduce:

1. expand git lens repository view very deeply
2. collapse all children one at a time

vscode explorer uses ALT to collapse all children but this does not seem to work in git lens

please and thanks

**Comment by eamodio** [comment]
Depends on https://github.com/Microsoft/vscode/issues/55879
