### ISSUE TITLE
Absolute dates not always honored in GitLens Results explorer

### ISSUE THREAD

**Issue by jez9999** [eamodio/vscode-gitlens#384]
In various places (for example, show commit details or blame annotations) GitLens shows vague relative dates for when a commit was made, like "9 months ago".  I wish to get the exact date (and maybe time).  Please add an option to make GitLens show exact dates/times instead.

**Comment by jez9999** [comment]
OK the settings already exist, here's how I got what I wanted (adding to User Settings):

```
	// Specifies how dates will be displayed by default
	"gitlens.defaultDateStyle": "absolute",

	// Specifies how absolute dates will be formatted by default
	// See https://momentjs.com/docs/#/displaying/format/ for valid formats
	"gitlens.defaultDateFormat": "YYYY-MM-DD",
```

**Comment by eamodio** [comment]
Fyi these settings are easily configured via the GitLens settings editor using the `GitLens: Open Settings` command from the command palette

**Comment by jez9999** [comment]
Unfortunately when I change settings on that screen it screws up the format of my user settings file and removes comments.

**Comment by jez9999** [comment]
I'm reopening this, because I've just realized that vague relative dates (eg. "2 months ago") are shown in my Gitlens results panel on the left, for example if I click "Show commit details", then "go back", then "show in results", the commit date shown in the results pane is a relative date.

**Comment by jez9999** [comment]
Reopening.

**Comment by eamodio** [comment]
@jez9999 Can you provide more details on the issue where updating the settings via the GitLens settings editor removes comments / screws up the formatting? I'd like to open an issue with vscode about it, because GitLens it just using the built-in configuration apis to update it settings.

**Comment by jez9999** [comment]
I can't seem to reproduce it right now.  What I'm sure happened was it removed the comments I had next to the setting and put it at the end of the file but right now it works OK.
