### ISSUE TITLE
Question: GitLens for Atom

### ISSUE THREAD

**Issue by shezaan** [eamodio/vscode-gitlens#387]
Is there any chance that gitlens could be ported to Atom? Atom's git integration is far superior to VS Code in my experience.
This would be a great plugin to have on Atom.
Pretty please!

**Comment by eamodio** [comment]
This would not only be a large undertaking, it also isn't something I'm really interested in right now as I am not an Atom user (and I would want to use the product regularly to ensure its high quality).

**Comment by kfshamsi** [comment]
Try 
**atom-inline-blame** in atom packages, install it. 

It won't be able to compete with GitLense but it works fine; it shows inline authors. At least for me that is the only thing I look for.
