### ISSUE TITLE
Make difftool work for any diff

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#389]
VSCode is great for viewing diffs of most files but for example Markdown files with long lines are very hard to make sense of. In such cases, an external diff tool would be very helpful.

GitLens already provides this for uncommitted / staged files since https://github.com/eamodio/vscode-gitlens/pull/154 but I'd also like to have it in other "compare" contexts, like browsing a history of a file, the quick pick menus, etc. What do you think?

**Comment by eamodio** [comment]
Sounds like a great suggestion -- thanks!

**Comment by rattrayalex-stripe** [comment]
We'd also like to be able to view the entire diff in a single editor tab (similar to traditional `git diff` output, but with VSCode's beautiful side-by-side view). Would that be part of this feature, or best as a separate issue'?

**Comment by eamodio** [comment]
@rattrayalex-stripe You can switch vscode into a single editor diff (i.e. inline) today -- it is in the `...` menu in the tab bar or via the `toggle.diff.editorMode` command (but it doesn't seem to be exposed in the command palette).

**Comment by rattrayalex-stripe** [comment]
Oops, sorry for being unclear – I meant viewing the diffs of multiple _files_ in the same editor tab. 

For example, if I execute a codemod or find/replace across 100 files, I would like a single tab through which to scroll to verify my changes. For this purpose, I actually quite like the side-by-side view in VSCode. 

My hunch is that if VSCode can handle arbitrary diff outputs for display, it can do this. 

However, now that I read this issue more carefully, I see that it is roughly the inverse of what I want.

**Comment by eamodio** [comment]
@rattrayalex-stripe no worries thanks for the clarification
