### ISSUE TITLE
Add date format options for status bar blame

### ISSUE THREAD

**Issue by SailorMax** [eamodio/vscode-gitlens#39]
Can you add setting to output dates as is?
Not "15 minutes ago" or "a month ago" (it hard to calculate actual datetime), but "Today"/"Yesterday"/earlier as plain date "02.03.2017" + time

Samples:

- Today at 12:24
- Yesterday at 09:00
- at 01.02.2017 19:34

thank you.

**Comment by eamodio** [comment]
@SailorMax that setting already exists `gitlens.blame.annotation.date` and you can set it to `absolute`. There was an issue in the README that didn't have the updated description -- you can see all the settings here https://github.com/eamodio/vscode-gitlens#extension-settings

**Comment by SailorMax** [comment]
Sorry, but in status bar I still have "3 years ago"...

**Comment by eamodio** [comment]
@SailorMax Ah, gotcha. Will fix that up -- thanks!
