### ISSUE TITLE
GitLens adds some settings in settings.json

### ISSUE THREAD

**Issue by ris58h** [eamodio/vscode-gitlens#391]
- GitLens Version: 8.3.3
- VSCode Version: 1.23.1
- OS Version: Ubuntu 18.04 LTS

I have two settings in my settings.json
`"gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "gitlens.historyExplorer.enabled": true`
After deletion and restart they appear again.

Steps to Reproduce:
1. Remove gitlens.historyExplorer.enabled from settings.json.
2. Restart VSCode.

**Comment by eamodio** [comment]
The `gitlens.advanced.messages` is by design, since you've already seen the keybindings notice and don't want to see it again. While the `gitlens.historyExplorer.enabled` is a bug and will be fixed in the next release
