### ISSUE TITLE
[Feature request] Recent changes for local commits

### ISSUE THREAD

**Issue by valenc3x** [eamodio/vscode-gitlens#396]
I usually do commits for small changes but sometimes that means that I have a bunch of local commits and is easy to lose track of where I've made modifications to a file before pushing my changes, specially for big files.

Right now I know I know which lines are not staged (green for new, blue for edited) and maybe when I commit locally, highlight those lines in a different color (purple?) to represent "committed but unpublished."

**Comment by fishpen0** [comment]
I also find the behavior odd that if I `git add` something that the gutter highlights disappear for that file.  I would like to keep highlights for anything that hasn't been committed.

**Comment by eamodio** [comment]
FYI the gutter highlight support is built into the vscode git extension and is not provided by GitLens. While would also love to have this feature -- it *might* best be implemented in vscode's git extension. Definitely worth opening a feature request for them as well.

**Comment by dwelle** [comment]
This would also be useful for branches or a commits that are not on `master` (in case you're on a detached branch, such as `FETCH_HEAD`. Both use cases are for reviewing PRs while working with the actual code (not diff views).

**Comment by Nowaker** [comment]
All other IDEs do it this way. We really need a new color for stages but uncommitted changes.

**Comment by eamodio** [comment]
A version of this is supported in GitLens 11 -- via the [_Gutter Changes_](https://github.com/eamodio/vscode-gitlens/#gutter-changes-) file annotations

It is limited because of the VS Code apis, but it does provide some of the desired functionality.

Please open new issues/requests for anything missing that you'd like to still see. Thanks!
