### ISSUE TITLE
View entire folder tree of particular commit

### ISSUE THREAD

**Issue by Mellbourn** [eamodio/vscode-gitlens#398]
It is currently possible to view the diff for a branch or commit in a folder view which contains the changed files.

I would like to be able to browse the whole file tree for a commit.
(i.e. show the tree-ish for that commit. Like the tree view in [tig](http://jonas.nitro.dk/tig/manual.html))

The corresponding command line command would be 
`git ls-tree --name-only -r <commit-ish>`

Sometimes it is easier to understand the state of a commit if you can see how all the files were at that point in time.

**Comment by eamodio** [comment]
Thanks for the suggestion. I'm thinking there might be an opportunity to hook into the new `FileSystemProvider` that vscode support -- so you could actually open the workspace for that point in time.
