### ISSUE TITLE
Absolute paths fail on Windows due to backslash

### ISSUE THREAD

**Issue by avih** [eamodio/vscode-gitlens#4]
Currently the code at `src/git.ts` looks as follows, which seem to intend to normalize backslashes to slashes:

```typescript
    static normalizePath(fileName: string, repoPath: string) {
        fileName = fileName.replace(/\\/g, '/');
        return isAbsolute(fileName) ? relative(repoPath, fileName) : fileName;
    }
```

However, on Windows `path.relative` appears to return paths with backslashes - which makes the git commands fail. The node docs seems to support it - https://nodejs.org/api/path.html#path_path_relative_from_to  (note that at the example the absolute path is with backslashes, while in your code it's with slashes, however, it still seems to return backslashes).

I'd suggest to rewrite it like so:
```typescript
    static normalizePath(fileName: string, repoPath: string) {
        if (isAbsolute(fileName))
            fileName = relative(repoPath, fileName);
        return fileName.replace(/\\/g, '/');
    }
```

**Comment by eamodio** [comment]
@avih Thanks! Look for this in 0.0.6

**Comment by avih** [comment]
Thanks, but I think that while 87215850 indeed fixed it, your followup commit on that line (d70a4720) broke it again.

The additional condition `fileName.startsWith(repoPath)` is falsy (apparently `repoPath` is absolute with forward slashes), and so it ends with an absolute path with forward slashes, which git can't find at the repo since it should be relative to the repo.

**Comment by eamodio** [comment]
@avih Doh -- thanks. If change [this line](https://github.com/eamodio/vscode-gitlens/blob/master/src/git.ts#L26) to `return gitCommand(cwd, 'rev-parse', '--show-toplevel').then(data => data.replace(/\r?\n|\r/g, '').replace(/\\/g, '/'));` does that fix it for you?

**Comment by avih** [comment]
Unfortunately, and while it's probably simple, I haven't tried yet to edit the typescript sources (haven't used typescript before), and so my debugging and testing involves editing the generated javascript files, and luckily vscode doesn't recompile the typescript files on every run, so it's sustainable to a degree.

Bottom line, I can't test it yet, but the solution is probably simple: just make sure before and after that both strings have their slashes normalized.

**Comment by avih** [comment]
> ... so it ends with an absolute path with forward slashes, which git can't find at the repo since it should be relative to the repo

This still happens with 0.1.0 at least one some cases, and modifying `normalizePath` to also replace the slashes for `pathRepo` seems to fix it for me locally.

I think the correct thing would be that `normalizePath` doesn't expect anything from its arguments, and instead does whatever it needs with the inputs such that the output is normalized. If this means normalizing both arguments before it does other things, then so be it.

I also think it would be a good idea if you could test on windows too. As it turns out, too many issues seem to slip between the cracks, I'm guessing, because you don't have a system to test it on.

**Comment by eamodio** [comment]
@avih Ugh sorry -- pushed 0.1.1. Yeah, I haven't been testing at all on Windows. I do have access but just haven't had the time to dedicate to getting that spun up and working for testing. :(

**Comment by avih** [comment]
0.1.1 doesn't fix it either. Recall `fileName` has backslashes on entry, `repoPath` has forward slashes. You need to normalize both before you do your thing, and then again at the end (which you do already).

**Comment by avih** [comment]
0.1.2 works as far as I can tell. Thanks :)
