### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by bizoo** [eamodio/vscode-gitlens#40]
There is some issues when encoding of files in Git is not UTF-8.
If I have a file opened in vscode encoded in Windows 1252 (this is my default encoding for my workspace),
when using the Compare with ... command, the files from Git (not the current one in the Working folder) is displayed with the wrong encoding.

To replicate:

1. Create a new file and put this text inside: _référence_
1. Save it with encoding Windows 1252
1. Commit it in a Git repository
1. Modify it and use Compare with Working Tree to show the difference

The current file is OK but the one in Git is wrong (garbage instead of é).
I think the encoding from the current file in vscode must be used to decode the files from Git.

**Comment by eamodio** [comment]
@bizoo Thanks for the report -- I'll take a look into it.

**Comment by eamodio** [comment]
@bizoo does the built-in git diff in vscode work for you? I'm seeing the same behavior with the vscode git diff as with GitLens.

**Comment by eamodio** [comment]
@bizoo I don't think there is currently a way I could fix this. Git itself doesn't know about the file encoding -- and vscode doesn't provide a way (as far as I can tell) to know what encoding the file is opened as.

If you or anyone else has any ideas I'm all ears :)

**Comment by bizoo** [comment]
You're correct, vscode doesn't handle it very well:
- If I put my encoding as default ("files.encoding": "windows1252") in my settings (either workspace or user), built-in git diff in vscode work for me on the same source file that show issues in GitLens.
- If I don't and use the Reopen with encoding to change the encoding, I see the same issues (and even more).

I suppose that it works in vscode because it open the files from git using a different API that respect the file encoding from settings.

So even vscode itself doesn't fully support encoding in git, I'll open an issue for it.
If you can do something in GitLens to work like vscode and respect the encoding setting for all files you open, it would be great.

By the way, thanks for this great plugin.

**Comment by bizoo** [comment]
An issues is already filled:
https://github.com/Microsoft/vscode/issues/21146

And it's incorporated in the March Iteration Plan  :thumbsup:

**Comment by bizoo** [comment]
And you're correct about getting encoding of a file:
https://github.com/Microsoft/vscode/issues/824

**Comment by bizoo** [comment]
Oups, closed by error...

**Comment by eamodio** [comment]
@bizoo Thanks for the updates! I will look into adding support for the `files.encoding` setting.

**Comment by bizoo** [comment]
Following this comment:
https://github.com/Microsoft/vscode/issues/21146#issuecomment-296583138

I tried the new git SCM integration and now the encoding works like before (the encoding of the files.encoding settings is always used), but it doesn't change anything for Git Lens.
Do you think it's possible to have the same behavior in Git Lens ?

**Comment by eamodio** [comment]
@bizoo I will take a look at what was added and see if I can get that in to GitLens

**Comment by eamodio** [comment]
@bizoo Sorry for the long delay, but can you try the new beta here: [v3.5.0-beta.2](https://github.com/eamodio/vscode-gitlens/releases/tag/v3.5.0-beta.2)? You can find installation instructions here: [Installing Beta Releases](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Beta-Releases)

**Comment by bizoo** [comment]
Sorry for the late answer, was on vacation.
Tried reproduce the encoding issues with build 3.5.1 and everything works as expected.
So GitLens as the same behavior as VSCode SCM.
Sad the set/get encoding from file (view) is still not supported in VSCode.

Thanks for your hard works.
