### ISSUE TITLE
How to package and distribute a tag (or branch?)

### ISSUE THREAD

**Issue by nabtron** [eamodio/vscode-gitlens#401]
Hi.

I am trying to know how to package / distribute various versions of the code at my local default repo inside visual studio code to the client? Without pushing it to a remote server.

I hope the question makes sense :(

**Comment by nabtron** [comment]
Also, when i sync the repo with gitlab.com repo, it doesn't push the tags, any update on that please?

**Comment by eamodio** [comment]
I'm not sure I understand your request -- are you talking about creating a git patch? If so, I'd recommend looking at something like this: https://stackoverflow.com/questions/5159185/create-a-git-patch-from-the-changes-in-the-current-working-directory

GitLens doesn't handle the pushing of code/tags/etc. If you are doing it through vscode, then that ability is provided by the built-in Git extension, so I would suggest opening an issue on the vscode repo.

Hope that helps.

**Comment by nabtron** [comment]
Thanks for responding, let me retry to explain:

visual studio code originally doesn't provide any (apparent) way to create tags. However gitlens does. 

So I created a tag in my local repository.

Now when i try to push or sync to my remote repo, all other changes get sync but not the tags. 

Is it due to tagging format on remote server? or visual studio code issue? or anything you can guide me through please?

**Comment by eamodio** [comment]
Please see: https://git-scm.com/book/en/v2/Git-Basics-Tagging#_sharing_tags as you need to explicitly push tags to your remote

**Comment by nabtron** [comment]
Thank you, i am really sorry for your wasting your time for such a simple thing (which i should have read from documentation first). Thanks for your time, patient and kindness.

And thank you for your code and plugin too.

**Comment by eamodio** [comment]
No problem -- glad to help.
