### ISSUE TITLE
Compare File with Previous Revision doesn't work on MacOS

### ISSUE THREAD

**Issue by b-hahn** [eamodio/vscode-gitlens#402]
- GitLens Version: 0.4.1
- VSCode Version: 1.24
- OS Version: macOS Sierra 10.12.6

Steps to Reproduce:

1. Press keyboard combination for command 'Compare File With Previous Revision'

This function works just fine on Ubuntu but for some reason does not work in any repo when using MacOS. When I run the command I get a pop-up stating "Unable to open history compare. The file is probably not under source control." When I search for the command using Cmd-Shift-P it does not appear in the menu either. 
My git config looks ordinary (i.e. nothing that seems to be incorrect, unlike issue #333 ). The developer tools console doesn't show any obvious errors either. 
What could be causing this issue?

Thanks a lot!

**Comment by eamodio** [comment]
Sorry for issue, can you please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your `settings.json`. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

Thanks!

**Comment by b-hahn** [comment]
Thanks for the quick reply - despite setting the out output level to verbose I don't actually see any messages in the Output pane. Is there another setting I have to activate?

**Comment by eamodio** [comment]
Does any other GitLens ability work? I don't understand how there wouldn't be output in the `GitLens` channel in the Output pane

**Comment by b-hahn** [comment]
Sorry, my bad, I was looking at the wrong tab. Here's the output which seems to refer to some git error:

`Keyboard.beginScope 0
Running(/): git rev-parse --show-toplevel
FAILED(/): git rev-parse --show-toplevel FAILED in 9 ms
isTracked('/extension-output-#2', 'undefined', 'undefined')
Running(): git ls-files /extension-output-#2
FAILED(): git ls-files /extension-output-#2 FAILED in 10 ms
getLogForFile[Not Cached(log:follow)]('undefined', 'extension-output-#2', undefined, undefined, undefined, false)
isTracked('extension-output-#2', '.', 'undefined')
Running(.): git ls-files extension-output-#2
Add log cache for '/extension-output-#2:log:follow'
FAILED(.): git ls-files extension-output-#2 FAILED in 9 ms
Skipping log; 'extension-output-#2' is not tracked
ShowMessage(warn, 'Unable to open history compare. The file is probably not under source control.', suppressFileNotUnderSourceControlWarning, [object Object])
KeyboardScope.dispose 1 0`

The command `git rev-parse --show-toplevel` works just fine when I run it in my terminal.

**Comment by eamodio** [comment]
No problem, can you post the logs from the point you click the compare file with previous button?

**Comment by b-hahn** [comment]
Sure:

```
isTracked('src/utils.py', <path to repo>, 'undefined')
Running(<path to repo>/src): git rev-parse --show-toplevel
Completed(/<path to repo>/src): git rev-parse --show-toplevel Completed in 17 ms
Keyboard.beginScope 0
getLogForFile[Not Cached(log:follow)]('<path to repo>, '<path to repo>/src/utils.py', undefined, undefined, undefined, false)
isTracked('src/utils.py', '<path to repo>', 'undefined')
Add log cache for '<path to repo>/src/utils.py:log:follow'
Skipping log; '<path to repo>/src/utils.py' is not tracked
ShowMessage(warn, 'Unable to open history compare. The file is probably not under source control.', suppressFileNotUnderSourceControlWarning, [object Object])
KeyboardScope.dispose 1 0
```

**Comment by eamodio** [comment]
Thanks! So is `<path to repo>/src/utils.py` a file that is part of a git repo?

**Comment by b-hahn** [comment]
Yes exactly.

**Comment by eamodio** [comment]
Does it only affect that file or any file in that repo? Or any file in any repo?

**Comment by eamodio** [comment]
Is there any casing issues with the path of that file? Can you provide a complete log from the output pane? The snippets are missing prior git calls that I need to check. Thanks!

**Comment by b-hahn** [comment]
I think this may indeed be a casing issue - my repos were in a folder with the German letter 'ü'. Is there any way to support this? In the meantime I'll move my code to another folder, thanks for the help!

**Comment by eamodio** [comment]
I'm going to close this, please re-open if you feel there is still an issue here.
