### ISSUE TITLE
Invalid scheme http/https to open resource as editor. Use IOpenerService instead.

### ISSUE THREAD

**Issue by jens1o** [eamodio/vscode-gitlens#403]
- GitLens Version: 8.3.4
- VSCode Version: 
```
Version 1.25.0-insider
Commit 2040792965d90825a47aa1986cff8eb14a34b28e
Date 2018-06-07T05:16:56.305Z
```
- OS Version: Win 10 Home

Steps to Reproduce:

1. Open git repo
2. Execute action `GitLens: Search commits`
3. Press enter again and wait for the search results.
4. Press enter on one commit
5. Click `Open commit in GitHub`
6. 🐛

**Comment by eamodio** [comment]
Not sure what to do at this point, will be tracking: https://github.com/Microsoft/vscode/issues/51358

**Comment by eamodio** [comment]
It looks like they pushed out a new insiders build with this fixed. So I'm going to close this for now.

**Comment by jens1o** [comment]
Alright, thank you @eamodio :)
