### ISSUE TITLE
Inline "[author], [last updated]" messages display before every flow type definition

### ISSUE THREAD

**Issue by t1mmen** [eamodio/vscode-gitlens#406]
- GitLens Version: 8.3.4
- VSCode Version: 1.24.0
- OS Version: macOS 10.13.4

Steps to Reproduce:

* Have a git committed file /w the following contents:
```jsx
// @flow

type Something = { name: string, age: number };
type AnotherThing = { whatever: string };

```
* Notice the `[author], [last updated]` message shows up before _every_ time definition (`gitlens.debug` enabled for screenshot)
<img width="800" alt="screenshot 2018-06-07 16 46 59" src="https://user-images.githubusercontent.com/192263/41131883-927a6bac-6a72-11e8-92d7-ba6ebdeae1b5.png">

Ref: https://twitter.com/eamodio/status/1004802247614783488

❤️ this extension btw, thank you so much for making it!

Edit: Attaching another screenshot in case that'll help:
<img width="919" alt="screenshot 2018-06-07 16 54 40" src="https://user-images.githubusercontent.com/192263/41132042-85324518-6a73-11e8-8513-166ea98c76d2.png">

**Comment by t1mmen** [comment]
@eamodie Yes, this file has a .js extension.

**Comment by eamodio** [comment]
@t1mmen sorry for the delay in getting back to you. Can you try adding the following to the `gitlens.codeLens.scopesByLanguage` setting?

```json
        {
            "language": "javascript",
            "symbolScopes": [
                "!Interface"
            ]
        },
```

That should resolve the issue for you. Hope that helps.

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
