### ISSUE TITLE
Indent guides are rendered for empty lines in the file in file blame panel

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [eamodio/vscode-gitlens#408]
- GitLens Version: 8.3.5
- VSCode Version: 1.24.0
- OS Version: macOS 10.13.4

<img width="426" alt="screenshot 2018-06-08 14 31 31" src="https://user-images.githubusercontent.com/6418145/41156179-7706b2ce-6b29-11e8-9bf5-86a55f9e6c98.png">

**Comment by eamodio** [comment]
It looks like this is a new case of https://github.com/Microsoft/vscode/issues/28628
Can you please open an issue for this on the vscode repo?

**Comment by eamodio** [comment]
I'm going to close this as this is a vscode issue.
