### ISSUE TITLE
Can't install the extension

### ISSUE THREAD

**Issue by carc1n0gen** [eamodio/vscode-gitlens#414]
GitLens Version: No idea because I can't get it installed
- VSCode Version: 1.24.0
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Attempt to install extension
2. Sit and wait

Other extensions install perfectly fine

**Comment by eamodio** [comment]
Unfortunately there is not enough information for me to understand the issue. Can you provide more details? Does the install button just stick at `Installing...`? Or something else?

**Comment by carc1n0gen** [comment]
Yes it gets stuck at installing 
![screen shot 2018-06-14 at 4 45 18 pm](https://user-images.githubusercontent.com/8248986/41437461-862724e6-6ff2-11e8-9519-8cdc66661431.png)

I let it go for a few hours

**Comment by eamodio** [comment]
Hrm, vscode completely owns the installation of extensions and GitLens doesn't do anything beyond that. I would suggest removing GitLens from the extension pane, then close vscode, and then remove any trace of GitLens from the vscode extensions folder on your system. You can find the location here: https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions

Once you remove the GitLens folder, reopen vscode and try to re-install GitLens.

**Comment by carc1n0gen** [comment]
I cannot remove it, since it has never finished installing, it has never shown up in my list of extensions. I've also cleared my extensions folder multiple times. This is very unfortunate to say the least.

**Comment by carc1n0gen** [comment]
WAIT.  Decided to clear my `Application Support/Code` folder, and it has fixed the issue! Shame, as now I've lost all my settings

**Comment by eamodio** [comment]
@carc1n0gen sorry to hear that, but glad its working again. I'm really hoping vscode gets these installation issues worked out -- because you are not the first to hit these types of issues.
