### ISSUE TITLE
Is it possible to not have the code jump on opening files due to GitLens

### ISSUE THREAD

**Issue by nikitavoloboev** [eamodio/vscode-gitlens#418]
- GitLens Version: 8.3
- VSCode Version: 1.24.0
- OS Version: 10.11.6

Steps to Reproduce:

1. Open any new file.
2. Wait ~ 1 second. The text will jump down to make space for the GitLens commit overlay.

I find it extremely annoying how when I open any file the text jumps down a bit to make space for this overlay:

![2018-06-15 at 01 14](https://user-images.githubusercontent.com/6391776/41442821-71225a06-7039-11e8-80d2-b2959f1c47cc.png)

Is it possible to either turn it off completely or make it so that when I open a file, the text is already moved so that the text doesn't shift to make space for that overlay.

Thank you.

**Comment by eamodio** [comment]
You can easily turn off (or customize) the code lens features in GitLens from the GitLens Settings editor (run *GitLens: Open Settings* from the command palette).

Here are the options (make sure you are in *Advanced* mode at the top):
![image](https://user-images.githubusercontent.com/641685/41445207-f5db7abc-7015-11e8-8ea8-11b29eaba680.png)

But other than turning off some of the features (maybe just the *File scope*) the experience is just how vscode renders code lens -- GitLens can't control how they are displayed (i.e. how they pop in)

Hope that helps.

**Comment by eamodio** [comment]
I'm going to close this as this is as expected.

**Comment by nikitavoloboev** [comment]
@eamodio Is it possible for GitLens to make jumping of the file instant as soon as the file opens? This way there is no visible delay until the GitLens overlays show and the text jumps.

**Comment by eamodio** [comment]
Unfortunately not. To keep things performant vscode delays decorations and code lens for a bit after a document is opened

**Comment by Superpencil** [comment]
@eamodio could you move it to the bottom instead to prevent the jumping?

**Comment by eamodio** [comment]
When you say bottom, you mean of the file?

**Comment by slikts** [comment]
This behavior is indeed exceedingly annoying.

**Comment by pqt** [comment]
Easiest solution to this was
```
"gitlens.codeLens.scopes": ["containers", "blocks"]
```
so that it no longer adds anything to the top anymore.

**Comment by friederbluemle** [comment]
@pqt - This does not seem to work anymore :( Any ideas how to do disable it with the latest versions of Code and GitLens? This text jump is sooo annoying.
Also, the screenshot posted by @eamodio - Is that dialog still available today? Or did things change?

**Comment by friederbluemle** [comment]
To answer my own question - Yes the dialog is still available: Command menu: `GitLens: Open Settings`

And sadly, I had to disable "CodeLens" altogether to fully get rid of the "source code jolt" after opening a file.

```
"gitlens.codeLens.enabled": false
```

Hopefully this will be fixed in the future.

**Comment by pqt** [comment]
Yeah @friederbluemle sorry I can't help more, but ultimately I weighed the pros and cons for the plugin and the constant jump had me uninstall it altogether.

Great plugin, but with such a fatal flaw. 🤷🏼‍♂️

**Comment by friederbluemle** [comment]
@pqt - Thanks for your reply. Yeah, if you try the line I posted you can still make use of most of the other features of this great plugin. So far it seems to be working for me. I'll try that for now.

**Comment by eamodio** [comment]
Unfortunately there isn't anything GitLens can do to stop the Git code lens from causing the document to reflow -- that is just how the code lens support works in VS Code. Sadly the best option is the ones provided -- either limit where the Git code lens show up via the `gitlens.codeLens.scopes` or turn them off via `gitlens.codeLens.enabled`. Although also note that you can toggle them on and off on-demand using the _Toggle Git Code Lens_ command.

**Comment by purplejacket** [comment]
I tried `"gitlens.codeLens.scopes": ["containers", "blocks"]` per the comment from **pqt** of 11 months ago, it seems to work.

**Comment by purplejacket** [comment]
@pqt I tried your solution `"gitlens.codeLens.scopes": ["containers", "blocks"]`, it seems to work.
