### ISSUE TITLE
Make blame heatmap color configurable

### ISSUE THREAD

**Issue by AndreasBackx** [eamodio/vscode-gitlens#419]
The heatmap in the git blame adds a red border for the heatmap which currently is not configurable. It would be nice to add make this configurable.

Related: #360.

**Comment by AndreasBackx** [comment]
Thank you for the quick implementation! I hope to add support for it soon in Rubecula.

**Comment by eamodio** [comment]
No problem. Unfortunately I wasn't able to expose the new colors as theme colors. Because vscode doesn't provide a way to get access to the actual color behind a theme color, which is required for the heatmap

**Comment by AndreasBackx** [comment]
Is there an issue of that on the VS Code repo?

**Comment by eamodio** [comment]
There is: https://github.com/Microsoft/vscode/issues/32813

**Comment by AndreasBackx** [comment]
Awesome, thank you. I'll keep an eye on it as well.
