### ISSUE TITLE
Clarification needed in Readme

### ISSUE THREAD

**Issue by AspenForester** [eamodio/vscode-gitlens#424]
- GitLens Version: 8.4
- VSCode Version: 1.24.1
- OS Version: Win10 1709

Steps to Reproduce:

1. Open the current readme.md

Just a seeking clarification in the hopes that the readme will read more clearly.

The first sub-bullet under "Adds completely revamped heat map annotations", reads "The indicator's, now customizable, color will either be hot or cold..." 
Are the indicators customizable or are the colors customizable? 

I could be wrong, but I think that item would read better as "The indicator's color, now customizable, will either be hot or cold..."

I didn't do this a pull request because I think it is a judgment call on your part.

Thanks!

**Comment by eamodio** [comment]
You are correct - it would read better the way you suggest. That's what I get for doing a release too late at night :smile:

**Comment by eamodio** [comment]
Fixed -- it will go out whenever the next release happens.
