### ISSUE TITLE
Add option to always show heatmap

### ISSUE THREAD

**Issue by lajtmaN** [eamodio/vscode-gitlens#426]
It would be awesome if it was possible to configure the heatmap to always be shown.

Furthermore allowing to edit while the heatmap is active.

Thanks for a great plugin! I recommended it to all my colleagues.

**Comment by lajtmaN** [comment]
Didn't knew about that setting - thanks!

I don't know how you implemented the heatmap, but you can assume that each changed line is 0 days old, and use that to color the heatmap - no need to run blame on the entire file just for that :)

**Comment by tristan957** [comment]
Can the heatmap and the git status map not exist at the same time? When I toggle the heat map on, and start to type it goes away.

**Comment by eamodio** [comment]
This has been addressed here: https://github.com/gitkraken/vscode-gitlens/issues/1988#issuecomment-1856564567

Still experimental right now though
