### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by JJBocanegra** [eamodio/vscode-gitlens#429]
The emojis doesn't work anywhere in Gitlens but I saw people with them, for example in the issue https://github.com/eamodio/vscode-gitlens/issues/146

![Proof](https://i.imgur.com/MYrtIUY.png)

- GitLens Version: 8.4.1
- VSCode Version: 1.24.1
- OS Version: Windows 10 Pro

**Comment by eamodio** [comment]
Great suggestion! I'll have to figure out if there is a "standard" way to take something like `:sparkles:` and output the correct unicode character so that vscode will render the emoji
