### ISSUE TITLE
File-level CodeLens isn't using the blame of the whole file as it should

### ISSUE THREAD

**Issue by svipben** [eamodio/vscode-gitlens#43]
Hello,

firstly thanks for such amazing extension for VS Code, secondly I have one problem which a little bit annoys me, because it doesn't produce the real info about commit, I updated `README.md` file more than 10 times and I always see `svipben, a day ago`, but it was yesterday and today, same applies for all files also function `Compare with Previous commit` shows bad info as well as codelens, I mean it shows only first commit, I made ~30 commits and it doesn't updated.

OS: Linux Ubuntu 16.04
VS Code: 1.10
Git: 2.11.0
User Settings: Default
Workspace Settings: Default

Thanks,
svipben

**Comment by eamodio** [comment]
@svipben Sorry for the issues you are experiencing, but I'm not sure I fully understand. Any chance you could provide some more details to what specific things are wrong (maybe a couple of screenshots with the wrong data)?

**Comment by svipben** [comment]
Yes, of course.

![Image](https://i.gyazo.com/e13e1d2d1f7f608c077a5a3c0f34718b.png)

**Comment by eamodio** [comment]
@svipben if you turn of caching -- setting `gitlens.advanced.caching.enabled` = `false` do you still see the same behavior? (Make sure you update to 2.10 first, otherwise it will crash at startup with caching disabled).

**Comment by svipben** [comment]
Updated to 2.10 version, disabled caching with `"gitlens.advanced.caching.enabled": false` in User Settings, but still the same. I already did about 3-5 VS Code restarts and it's still the same...

**Comment by eamodio** [comment]
@svipben hrm. Can you also try to turn on the following settings: `gitlens.advanced.debug` = `true` and `gitlens.advanced.output.level` = `verbose`. That should turn on a bunch of logging (in its own output channel called `GitLens`), as well as put some debug information into the CodeLens themselves.

After you turn can you send me another screenshot?

Also is that repo public? If so I can try pulling it myself to see if I see the same issues.

**Comment by svipben** [comment]
If you're talking about Toggle developer tools, I get in console same error 3 times:

```
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] Activating extension `eamodio.gitlens` failed: Cannot read property 'appendLine' of undefined.
```

My repo: https://github.com/svipben/react-boilerplate

**Comment by svipben** [comment]
After push `README.md` still have `svipben, a day ago`, but `package.json` have `svipben, 4 minutes ago`.

P.S. At top it shows `svipben, 4 minutes ago`, at bottom it shows `svipben, 2 days ago`, here is the picture.
![Image](https://i.gyazo.com/5a950e04308b91943ef16e6bbf4160f1.png)

**Comment by eamodio** [comment]
I actually think this was resolved in GitLens 11.
