### ISSUE TITLE
Feature Request: Show tag comment

### ISSUE THREAD

**Issue by tzachshabtay** [eamodio/vscode-gitlens#431]
If I create a tag with a comment, for example: `git tag -a v1.4 -m "this version has this super cool new feature"` I would like to see this comment in the tag tree (for example: `v1.4 (this version has this super cool new feature`).
Currently only the tag name is shown (`v1.4`).

Thanks for the great extension.

**Comment by eamodio** [comment]
Would having the tag comment show up in the tooltip be enough to satisfy this request?

**Comment by tzachshabtay** [comment]
A tooltip is possible, though personally I would prefer seeing it as part of the title so that I can visibly see all the tag+comment pairs in a nice list.
