### ISSUE TITLE
No sign of Stash Explorer

### ISSUE THREAD

**Issue by agjs** [eamodio/vscode-gitlens#434]
Did you guys remove stash explorer in one of the recent releases? Gitlens History is still part of my VSC explorer but there's no sign of stash menu at all. Also all the configuration options I found for stash explorer no longer work under user settings.

**Comment by agjs** [comment]
bump

**Comment by eamodio** [comment]
The stand-alone Stashes view was removed and its functionality was folded into the *GitLens* explorer (way back in version 5). The *GitLens* explorer contains a stashes node which has all the functionality as the old Stashes view. By default the *GitLens* explorer now lives on the Source Control view (you can open it via the `Show GitLens Explorer` command from the command palette). Its location is also configurable (as most everything in GitLens is) which you can easily configure via GitLen's interactive settings editor (run `GitLens: Open Settings` from the command palette to open it)

Hope that helps.
