### ISSUE TITLE
[Feature request] (gitlens.explorers.commitFormat): Advanced Formatting enable multiline message display

### ISSUE THREAD

**Issue by andreasgrimm** [eamodio/vscode-gitlens#435]
If you want to make use of git's `--autosquash` feature when doing an interactive rebase, the subjects of the subsequent commit messages have to stay the same (except for the `squash! ` or `fixup! ` prefixes of course) https://git-scm.com/docs/git-rebase#git-rebase---autosquash

Thus you have to rely on a commit message's body to reveal information about what an individual commit is all about. Currently if you want to reason about an individual "autosquash-able" commit, you have to mouse hover over it and wait for the tool tip / pop up to appear and show the commit message body.

<img width="422" alt="2018-06-27_vscode - gitlens - commit message format" src="https://user-images.githubusercontent.com/6958703/41988237-c9d933a2-7a3b-11e8-922b-ebdc6074a9eb.png">

What about the possibility to enable multi line display for https://github.com/eamodio/vscode-gitlens/wiki/Advanced-Formatting so that the text of an individual gitlens explorer node would not be restricted to "combined width will always be 54 characters" but could be configured to span multiple lines?

**Comment by eamodio** [comment]
Unfortunately vscode doesn't allow for multi-line entries in the explorer views at this point (though I wish they did). Until that is supported I don't think there is much I can do.
