### ISSUE TITLE
File history or Changed files not shown

### ISSUE THREAD

**Issue by obrejla** [eamodio/vscode-gitlens#44]
VSCode 1.10.1
macOS Sierra

Hi!

I installed the extension, blaming works well, but when I want to see e.g. File History, I get a warn, that "Unable to show file history. File is probably not under source control". Also when I want to look at Changed Files (click on Commit Details -> Show Changed Files) I get warn "Unable to show commit details". 

But as I said...Blame works.

What should I do to let it work? Extension looks awesome, but it would be much better if it work for me :)

Thanks a lot!

**Comment by obrejla** [comment]
I toggled debug mode and in Dev Tools, there is this errror:

```
[GitLens] git log --name-status --full-history -m --date=iso8601-strict --format=%H -%nauthor %an%nauthor-date %ai%ncommitter %cn%ncommitter-date %ci%nsummary %B%nfilename ? --follow -n200 UiUtils.js   cwd='/Users/ondrej/NetBeansProjects/mcs_buf/breeze/client/public_html/modules/base.dt/js' 
  Error: fatal: unknown date format iso8601-strict  Failed with exit code: 128
```

**Comment by obrejla** [comment]
Well, I updated git to 2.10.1 and it started to work.

**Comment by eamodio** [comment]
@obrejla Yeah, that date format I guess is only in later version of git -- I should look into seeing if normal iso8601 would work.

**Comment by obrejla** [comment]
Cool, thanks for the support.
