### ISSUE TITLE
Searching for commits with an empty query yields to no results anymore

### ISSUE THREAD

**Issue by jens1o** [eamodio/vscode-gitlens#440]
- GitLens Version: 8.4.1
- VSCode Version:
```
Version: 1.25.0
Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
Date: 2018-07-05T13:11:58.697Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
``` 
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Execute `GitLens: Search Commits`
2. As soon as the search bar appears, hit enter.
3. Get no results.

Expected behavior:
Get all commits, sorted by last one being first.
Looks like you introduced a breaking change, but I love this feature to get this viewlet. I don't want to use the history bar, because I do not need this feature many times, but when I use it, I'd like it to be like I've been being used to.

**Comment by eamodio** [comment]
I can't seem to reproduce this behavior (it still shows all commits matching `''`). FYI, that output should be the same as `GitLens: Show Current Branch History`

**Comment by jens1o** [comment]
Alright.

Trying `GitLens: Show Current Branch History` I get this message:
![image](https://user-images.githubusercontent.com/11234139/42423252-ab858292-82f7-11e8-8270-f30bfd8186ae.png)
But I do not get any error in the `Developer Tools` (the chromium inspector) nor in the `Git` output. How can I enable more verbose logging?

**Comment by eamodio** [comment]
Is this in a multi-root workspace?

**Comment by jens1o** [comment]
Thank you very much :)
