### ISSUE TITLE
GitLens custom viewlet icon slightly larger than standard

### ISSUE THREAD

**Issue by JacksonKearl** [eamodio/vscode-gitlens#444]
The recently added custom viewlet has an icon that seems to be rendering about 10% larger than the native icons. On my monitor it is about 34px across compared to 30 px for the similarly shaped debugging viewlet icon. It'd be great if you could make the icon uniform in size with the native ones. 

- GitLens Version: 8.5
- VSCode Version:  Code - Insiders 1.26.0-insider (6babef94104b27b252929324aa3c2d69cd38e9f2, 2018-07-16T05:18:37.865Z)
- OS Version: Windows_NT x64 10.0.16299

**Comment by bpasero** [comment]
@eamodio I am still seeing this on Linux:

![image](https://user-images.githubusercontent.com/900690/45425458-b7850600-b699-11e8-8ebc-1a9059f7771f.png)
