### ISSUE TITLE
webstorm support please!

### ISSUE THREAD

**Issue by benmonro** [eamodio/vscode-gitlens#448]
I'm a huge fan of gitlens, one of my fave features of VSCode.  But I also love webstorm.  Any chance you guys can add support for webstorm? :)

**Comment by eamodio** [comment]
Like I mentioned on the request for Atom, this would not only be a large undertaking, it also isn't something I'm really interested in right now as I am not a Webstorm user (and I would want to use the product regularly to ensure its high quality).

**Comment by eamodio** [comment]
I know -- sorry.

**Comment by jxltom** [comment]
Not only for webstorm, as Jetbrain's software have same plugin system, it could work for pycharm, intelliJ, android studio, etc.

**Comment by iamtodor** [comment]
Vote +1 for PyCharm 👍

**Comment by mtianyan** [comment]
Vote +1 for PyCharm  Too👍
