### ISSUE TITLE
Search for string returns merge commits (unlike raw `git log -S`)

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#454]
- GitLens Version: 8.5.2
- VSCode Version: 1.25.1
- OS Version: Windows 10
- Git version: 2.18

I've tried on a couple of repositories and it seems that GitLens returns also merge commits when I search for a string using the `=` syntax. For example, you can try checking out https://github.com/versionpress/versionpress and comparing:

Plain Git: 

```
$ git log -S BulkChangeInfo --oneline | wc -l
11
```

GitLens after searching for `=BulkChangeInfo`:

![image](https://user-images.githubusercontent.com/101152/43025453-2021c7b8-8c72-11e8-8ed5-1421c2590810.png)

The difference is in merge commits:

![image](https://user-images.githubusercontent.com/101152/43025489-4a818110-8c72-11e8-9937-2549b974348a.png)

**Comment by speed-oss** [comment]
@borekb if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
