### ISSUE TITLE
Search panel

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#455]
I think the search could live in some panel, not just in the quick pick UI. The benefits would be:

- Types of searches would have more space to be "documented". In the quick pick field, `=` is too far right and the hint is not visible.
- If the search takes longer (can be 10-20 seconds in some of our repos), panel allows me to do some work in the meantime while quick pick simply goes away.

**Comment by eamodio** [comment]
Great suggestion!
