### ISSUE TITLE
Add repository status to the repository nodes in the Repository explorer

### ISSUE THREAD

**Issue by ryderatman** [eamodio/vscode-gitlens#456]
I really like that gitlens has a repo depth setting, but it does not currently have a visual indicator at the repository level so I can tell which repositories have uncommitted changes.

So basically, show the repo status at the repo node level, rather than in a child of the repo node. Or create a new view that just lists the modified repos as an optional setting. 

Thanks,
Bryan

**Comment by speed-oss** [comment]
@ryderatman if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
