### ISSUE TITLE
Displays the wrong username (You)

### ISSUE THREAD

**Issue by ashley** [eamodio/vscode-gitlens#457]
If a contributor in a Git repository has the same first name as me, GitLens will display "You" as the author. The links and the avatar are for the right user, but when hovering over a LOC, it'll say something like, "You, a x time ago".

 GitLens Version:
- VSCode Version: 8.5.2
- OS Version: MacOS High Sierra 10.13.4

Steps to Reproduce:
1. Go to a repo that includes a contributor with the same first name as you.
2. Go to a line of code which that contributor committed.

**Comment by speed-oss** [comment]
@ashley if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
