### ISSUE TITLE
File blame annotation text overflow with letter spacing setting

### ISSUE THREAD

**Issue by Yukaii** [eamodio/vscode-gitlens#459]
- GitLens Version: 8.5.2
- VSCode Version: 1.25.1
- OS Version: Windows 10

Steps to Reproduce:

1. Toggle file blame
2. Text overflow:
	![image](https://user-images.githubusercontent.com/4230968/43123773-c5cf0e22-8f57-11e8-9886-4465cd23a399.png)

This might be an upstream issue, but I don't know which API is related, so end up open it here 😅 

My font config:

```json
{
  "editor.fontFamily": "Sarasa Mono TC",
  "editor.fontLigatures": true,
  "editor.fontSize": 16,
  "editor.letterSpacing": 1.3
}
```

**Comment by speed-oss** [comment]
@Yukaii if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
