### ISSUE TITLE
ui error when editor.renderWhitespace is boundary

### ISSUE THREAD

**Issue by jedy** [eamodio/vscode-gitlens#46]
![image](https://cloud.githubusercontent.com/assets/1589263/23744613/de6cba5e-04ef-11e7-999d-6486126d5ff4.png)
![image](https://cloud.githubusercontent.com/assets/1589263/23744637/eb0a0d98-04ef-11e7-9ed3-395cdfd6d903.png)

**Comment by eamodio** [comment]
@jedy are you using a non-monospace font? If so this is a [known issue](https://github.com/eamodio/vscode-gitlens#known-issues) and you will need to set `"gitlens.advanced.toggleWhitespace.enabled": true`.

Please let me know if that resolves the issue for you.

**Comment by jedy** [comment]
I use Inconsolata-g, which is a monospace font. Setting `"gitlens.advanced.toggleWhitespace.enabled": true` works. Thank you.

**Comment by eamodio** [comment]
@jedy great -- thanks! With any luck [vscode #11485](https://github.com/Microsoft/vscode/issues/11485) will get resolved soon :)
