### ISSUE TITLE
fatal: Not a git repository - when looking at incoming changes

### ISSUE THREAD

**Issue by bardware** [eamodio/vscode-gitlens#461]
- GitLens Version: 8.5.2

- VSCode Version: 1.25.1
- OS Version: Win 10 64 bit German

Steps to Reproduce:

1. Call `git fetch` in the terminal window
2. switch to gitlense Explorer and open hierarchy `master` => `2 commits behind` open any commit and click a changed file.

VSCode has a view for every plugin. Press `CTRL+ SHIFT + U` and select git in the dropdown to the right.
It reads
```
> git rev-parse --show-toplevel
fatal: Not a git repository (or any of the parent directories): .git
```

I guess the changed file is copied to some temp folder - that indeed is not a git repo - and tries to operate on this.

**Comment by eamodio** [comment]
That log line it just the git command failing -- which is the command GitLens uses to detect whether or not there is a repo associated with the file/folder. It is completely expected behavior.

**Comment by speed-oss** [comment]
@bardware if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)

**Comment by bardware** [comment]
@[speed-oss](/speed-oss) And you are? :eyes:
