### ISSUE TITLE
Source Control shortcut on macOS (⌃⇧G) shouldn't be overridden

### ISSUE THREAD

**Issue by GandalfSaxe** [eamodio/vscode-gitlens#462]
Why this?

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/12127864/43219811-a163cf04-9048-11e8-8d9a-594ad13c39c2.png">

It's evident that GitLens is not using ⌃⇧G for anything, so why make it more cumbersome to go to the Source Control tab by making it ⌃⇧G, G?

Filed as a bug because I can't see any logical explanation for this.

**Comment by GandalfSaxe** [comment]
My guess is it's a bad default due to the keymap on windows that _does_ utilize ctrl+shift+G a whole lot:

![image](https://user-images.githubusercontent.com/12127864/43220163-a921579c-9049-11e8-8b08-32e295f62a01.png)

All these commands are instead used on ⌥⌘G on Mac. Therefore the ⌃⇧GG mapping in OP clearly seems like a bug / should be removed :)

**Comment by speed-oss** [comment]
@GandalfSaxe if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
