### ISSUE TITLE
Checkout arbitrary commit

### ISSUE THREAD

**Issue by GandalfSaxe** [eamodio/vscode-gitlens#463]
Would you consider to make it a feature to checkout any commit on commit id?

For some inconceivable reason, it's not supported by VSCode itself (unless I missed something). The git checkout command in VSCode only works for branch checkouts when I try.

**Comment by eamodio** [comment]
Sounds like a good idea. Thinking it would be another item on the context menu *Checkout Commit (via Terminal)*, along with all the *\* (via terminal)* commands. Does that satisfy your request?

**Comment by GandalfSaxe** [comment]
Must ask, the context menu where?
(I just started using your excellent extension a few hours ago).

I was thinking someting along the lines of:
Basically a global command so you can bring up the command pallette, choose "Checkout commit..." and paste in the id/hash of a commit. Context menus also sound good.

**Comment by GandalfSaxe** [comment]
The VSCode team confirmed that they see the console command as adequate, and I see their point: https://github.com/Microsoft/vscode/issues/55086#issuecomment-407984945

However I do think it makes sense for git extensions to have this feature in places where you contextually are looking back on previous commits.

**Comment by eamodio** [comment]
Yeah, that is the menu. And as for the quickpick lists, I'm going to be syncing the commands from the menus and the commands when you select a commit or file.

**Comment by speed-oss** [comment]
@GandalfSaxe if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
