### ISSUE TITLE
[Feature Request] Popup when X commits behind on open

### ISSUE THREAD

**Issue by qubicaamf** [eamodio/vscode-gitlens#466]
Hi,
Thank you for this amazing extensions, we are using it a lot here in my company.

We work in team usually and due to fast switching from a project to another, sometimes we start to write code without pulling the latest commits.
Actually, we should check the GitLens Explorer, where i can easily see if there are commits behind in local branch:

![image](https://user-images.githubusercontent.com/32999837/43315881-ba4139d0-9197-11e8-8fb5-17753cd1658a.png)

...but, a really nice to have feature would be a [UI Notification](https://code.visualstudio.com/updates/v1_21#_new-notifications-ui) on workplace open and only if the current local branch repo has commits behind the remote one...and a button ("Yes"/"No", or "Pull"...or whatever) to execute the `git pull` command.
A flag to enable this check and the notification should be enough.

What do you think about it?

**Comment by eamodio** [comment]
I think this request would be best served by the built-in vscode git extension. Since it would go along with the status bar indication of the current branch's sync status. So I would recommend opening a feature request on the vscode repo. Thanks!
