### ISSUE TITLE
Unable to click on status bar button in diff mode

### ISSUE THREAD

**Issue by SailorMax** [eamodio/vscode-gitlens#47]
Steps:
1. modify any file;
2. open SCM tab;
3. click on modified file to see diff;
4. put cursor on any line in left part of diff to see author in status bar
5. click on author in status bar

Expected: GitLens menu for selected commit.

Actual: status bar button hide.

**Comment by eamodio** [comment]
@SailorMax Thanks for the report, sadly this is a [vcode issue](https://github.com/Microsoft/vscode/issues/22403)

**Comment by eamodio** [comment]
As this is a vscode issue that I cannot do anything about, I'm going to close this.
