### ISSUE TITLE
How to change the font on the hover panel?

### ISSUE THREAD

**Issue by hyrious** [eamodio/vscode-gitlens#475]
Default is _Courier New_ I guess, which looks blurry on Windows most of the time.
![](https://raw.githubusercontent.com/eamodio/vscode-gitlens/master/images/ss-hovers-current-line.png)
I didn't find any settings about fonts -- maybe I'm missing.
Any way to cure my eyes? XD

**Comment by eamodio** [comment]
AFAIK, there is no way to control the font of the hovers, or many other UI elements in vscode. I would recommend opening an issue with the vscode repo and asking for this ability.
