### ISSUE TITLE
Comparison view should split :up/down/left/right

### ISSUE THREAD

**Issue by thedon-chris** [eamodio/vscode-gitlens#476]
When using GITLENS to compare files across revisions, remotes or branches you should be able to split the view horizontally instead of the current vertical 2 column split. VS code already has the ability to split the view into columns/rows, you should able to do this with GITLENS.

This would be help when comparing files that have longer than usual line lengths.

For example, in the screengrab below I have split the view and GITLENS has not split the comparison view.

![screen shot 2018-08-14 at 5 28 16 pm](https://user-images.githubusercontent.com/30728737/44119524-835b7c06-9fe7-11e8-9076-a367178e71ad.png)

**Comment by eamodio** [comment]
Unfortunately vscode doesn't provide this ability. Diff editors (which is what GitLens uses) can either be inline or split vertically. There is no option for them to be split horizontally currently. I would recommend opening an issue with the vscode repo and asking for Diff editors to be split horizontally if that is what you would like. Sorry.
