### ISSUE TITLE
Can't load any GitLens features or UI

### ISSUE THREAD

**Issue by cameroncooke** [eamodio/vscode-gitlens#477]
So I've just installed GitLens but can't get any of the features or UI to activate. I've tried restarting VSCode and this has had no effect.

My workspace is in a sub-directory of the repo root. My workspace is at `MyProject/FeatureTests/` and the repo root as at `MyProject/`. It appears GitLens can't find the repo because it doesn't search upwards only downwards. Code's own Git features work and can see the repo just fine.

- GitLens Version: v8.5.4
- VSCode Version: 1.26.0
- OS Version: macOS High Sierra 10.13.6

Steps to Reproduce:

1. Open workspace
3. Attempt to activate any GitLens features.
2. View `verbose` logs, see errors.

Logs

```
Git found: 2.15.1 @ /usr/local/Cellar/git in 55 ms
Starting repository search in 1 folders
Searching for repositories (depth=0) in '/Users/joe_bloggs/Source/MyProject/FeatureTests' ...
Running(/Users/joe_bloggs/Source/MyProject/FeatureTests): git rev-parse --show-toplevel
GitLens(v8.5.4) activated in 103 ms
FAILED(/Users/joe_bloggs/Source/MyProject/FeatureTests): git rev-parse --show-toplevel FAILED in 19 ms
Searching for repositories (depth=0) in '/Users/joe_bloggs/Source/MyProject/FeatureTests' took 19 ms
Running(/Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode): git rev-parse --show-toplevel
Awaiting(/Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode): git rev-parse --show-toplevel
FAILED(/Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode): git rev-parse --show-toplevel FAILED in 7 ms
FAILED(/Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode): git rev-parse --show-toplevel FAILED in 1 ms
isTracked('/Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode/settings.json', 'undefined')
Running(): git ls-files /Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode/settings.json
FAILED(): git ls-files /Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode/settings.json FAILED in 5 ms
isTracked('/Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode/settings.json', 'undefined') = false
```

**Comment by eamodio** [comment]
GitLens doesn't need to search upwards in the same way as downward, since git can provide that information directly (using `git rev-parse --show-toplevel`). But for some reason that seems to be failing.

Can you try running `git rev-parse --show-toplevel` from inside the `/Users/joe_bloggs/Source/MyProject/FeatureTests` folder? Also is the casing of that path correct?

**Comment by cameroncooke** [comment]
I’m out at the moment but I did try that and it showed the repo correctly.

**Comment by cameroncooke** [comment]
@eamodio I've ran that comment and got the following:
```
/Users/joe_bloggs/Source/MyProject
```

I notice in the head of the  Gitlens logs:

```
Git found: 2.15.1 @ /usr/local/Cellar/git in 55 ms
Starting repository search in 1 folders
Searching for repositories (depth=0) in '/Users/joe_bloggs/Source/MyProject/FeatureTests' ...
Running(/Users/joe_bloggs/Source/MyProject/FeatureTests): git rev-parse --show-toplevel
GitLens(v8.5.4) activated in 103 ms
```

That it executes that command to find the repo root, and then the next message is `GitLens(v8.5.4) activated in 103 ms` is that says that it's found the repro and activation or does the activation happen regardless? As the following messages after the activation message are recursive searching of the repo.

**Comment by eamodio** [comment]
Hrm, and if you run `git --version` on the command line do you see the same version as in your log?

The activation log message just marks the end of GitLens searching for repositories.

**Comment by eamodio** [comment]
Can set `gitlens.outputLevel` to `debug`, and then post the output from the `GitLens (Git)` channel? It should hopefully provide more details.

**Comment by cameroncooke** [comment]
> Hrm, and if you run git --version on the command line do you see the same version as in your log?

Yes Git version `2.15.1`.

Debug output seems the same when `outputLevel` set to `debug`:
```
Git found: 2.15.1 @ /usr/local/Cellar/git in 47 ms
Starting repository search in 1 folders
Searching for repositories (depth=0) in '/Users/joe_bloggs/Source/MyProject/FeatureTests' ...
Running(/Users/joe_bloggs/Source/MyProject/FeatureTests): git rev-parse --show-toplevel
GitLens(v8.5.4) activated in 90 ms
FAILED(/Users/joe_bloggs/Source/MyProject/FeatureTests): git rev-parse --show-toplevel FAILED in 29 ms
Searching for repositories (depth=0) in '/Users/joe_bloggs/Source/MyProject/FeatureTests' took 30 ms
```

**Comment by cameroncooke** [comment]
It's worth noting the vscode workspace resides in a sub-directory of the repo root `/Users/joe_bloggs/Source/MyProject/FeatureTests/.vscode` while the `.git` directory sits in the repo root at `/Users/joe_bloggs/Source/MyProject`.

**Comment by eamodio** [comment]
With it set to `debug` there should be 2 output channels, `GitLens` and `GitLens (Git)`, can you post the output from `GitLens (Git)`?

**Comment by cameroncooke** [comment]
Thanks for the tip, here is the output:

```
[2018-08-20 08:16:22:691] git rev-parse --show-toplevel FAILED in 24 ms (/Users/joe_bloggs/Source/MyProject/FeatureTests)

Error: spawn EACCES
[2018-08-20 08:16:22:763] git rev-parse --show-toplevel FAILED in 6 ms (/Users/joe_bloggs/Source/MyProject/FeatureTests/features)

Error: spawn EACCES
[2018-08-20 08:16:22:763] git rev-parse --show-toplevel FAILED in 2 ms (/Users/joe_bloggs/Source/MyProject/FeatureTests/features)

Error: spawn EACCES
[2018-08-20 08:16:22:769] git ls-files /Users/joe_bloggs/Source/MyProject/FeatureTests/features/search.feature FAILED in 4 ms ()

Error: spawn EACCES
```

**Comment by cameroncooke** [comment]
Ok I've fixed it by adding the following to my settings:

```
"gitlens.advanced.git": "/usr/local/bin/git"
```

Essentially telling Gitlens to use the same Git executable. I'm not sure why it wouldn't do that by default, to be honest. So might be a bug there but this workaround works for me.

**Comment by cameroncooke** [comment]
Thanks for your help on this.

**Comment by eamodio** [comment]
@cameroncooke I think I know why this isn't working. GitLens does try to get the git path from vscode, but it wasn't apparently waiting correctly if the Git extension hadn't loaded yet (which never seemed to happen in the past, but is now). I've got a fix for that -- can you try out this private build? Remove the `.zip` from the filename and you can install it. If you need instructions see [here](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Prereleases-(vsix))

[gitlens-8.5.5.vsix.zip](https://github.com/eamodio/vscode-gitlens/files/2307374/gitlens-8.5.5.vsix.zip)

**Comment by cameroncooke** [comment]
@eamodio I've removed the `gitlens.advanced.git` option, verified that the release version failed again, then installed the private build.

I can report the private version does indeed fix the issue and everything now works without having to explicitly define the git path. 🎉

**Comment by eamodio** [comment]
Sweet! I'll get a new version out tonight with the fix -- thank you for the help!

**Comment by ItzhakS** [comment]
@eamodio I had a similar issue. Gitlens was  not found, the pre-release worked.

**Comment by yashLadha** [comment]
Error still persists, getting `spawn EACCESS`

**Comment by eamodio** [comment]
@yashLadha Can you open a new issue with more details and logs about what you are experiencing? From `EACCESS` is sounds like a possible permissions issue.

**Comment by speed-oss** [comment]
@cameroncooke if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
