### ISSUE TITLE
Uncommited change behavior on tab or space

### ISSUE THREAD

**Issue by svipben** [eamodio/vscode-gitlens#48]
Hello,

OS: Linux Ubuntu 16.04
VS Code: 1.10.2
GitLens: 2.11.2

When you use space or tab on empty line you get `Uncommited change`, if I remember correctly it was VS Code problem and you created new issue, but seems it wasn't fixed...

![screenshot from 2017-03-12 17 19 51](https://cloud.githubusercontent.com/assets/10441177/23833000/1ebcaf38-0748-11e7-98f5-6a31b4bc45f6.png)

P.S. Enabled debug, seems everything fine, no errors or warning from GitLens.

**Comment by eamodio** [comment]
@svipben vscode "fixed" the issue, but it hasn't been released yet -- I'm not sure it made it into an insiders build yet (but I think so). It will likely be released in vscode v1.11

**Comment by svipben** [comment]
@eamodio oh, sorry then. Thanks!

**Comment by eamodio** [comment]
@svipben no worries at all :)
