### ISSUE TITLE
How to change these strange avatars?

### ISSUE THREAD

**Issue by Maledong** [eamodio/vscode-gitlens#480]
Hello all:

I don't know why we have such strange avatars but some of them are normal as what the user has set?
![avatars](https://user-images.githubusercontent.com/40081831/44319254-4d4bbd80-a46d-11e8-94bc-ef8f691744f4.PNG)

Is there anything to be set to make these "strange" avatars normal? Mine is also strange :(

**Comment by Maledong** [comment]
PS：If we cannot do that, since sometimes the strange avatars are very very similar to each other (e.g: Mine is the topest in the attached image, compared with the 2nd one).

So is it possible to use a random avatar as the default or let the user do something setting in the local (for local identification ONLY)?

http://identicon.net/

**Comment by Maledong** [comment]
PS：Is this a bug? I've noticed that sometimes (Hardly to find) the avatar doesn't match what a user sets?

See this user's avatar:
![default](https://user-images.githubusercontent.com/40081831/44518170-28b94500-a6fc-11e8-80c7-a77d5a933b57.PNG)

The original link is [HERE](https://github.com/nodejs/node/commit/c8a27a761773b9815bd6af07ce6d6e72ae19df30) (Notice the submitted avatar).

/cc：@eamodio

**Comment by eamodio** [comment]
Sorry for the delayed reply. GitLens only uses Gravatar for its avatars (not GitHub). The ones you see are fallback ones when that e-mail address can't be found on Gravatar. You can control the set of fallback avatars by setting `gitlens.defaultGravatarsStyle` (See https://github.com/eamodio/vscode-gitlens#general-settings).

Hope that helps.

**Comment by Maledong** [comment]
Thanks for your quick time !

BTW：I've set the avatar setting. But **is it possible to directly refer the url of someone's avatar from GitHub according to the exposed Api?** And if someone has no avatars, just call Gravana?

Nothing but just a suggestion, and this will make users see clearly who he/she is, something like this：

``` js
response = requests.get("https://api.github.com/users/VikParuchuri/orgs", .....);
orgs = response.json();
print(orgs);

/*
[{'avatar_url': 'https://avatars.githubusercontent.com/u/11148054?v=3', 'description': None, 'repos_url': 'https://api.github.com/orgs/dataquestio/repos', 'url': 'https://api.github.com/orgs/dataquestio', 'login': 'dataquestio', 'events_url': 'https://api.github.com/orgs/dataquestio/events', 'members_url': 'https://api.github.com/orgs/dataquestio/members{/member}', 'id': 11148054, 'public_members_url': 'https://api.github.com/orgs/dataquestio/public_members{/member}'}]
*/
```
For more, you can see：https://developer.github.com/v3/migrations/users/

**Comment by eamodio** [comment]
A request for that feature already exists here: https://github.com/eamodio/vscode-gitlens/issues/281
