### ISSUE TITLE
UI displays "undefined" in results panel when comparing.

### ISSUE THREAD

**Issue by pvormittag** [eamodio/vscode-gitlens#482]
<img width="393" alt="screen shot 2018-08-21 at 7 07 48 am" src="https://user-images.githubusercontent.com/211588/44403358-7a51ac00-a511-11e8-8dc7-a530dfe0dd61.png">

- GitLens Version: 8.5.5

- VSCode Version: 1.26.1
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Select two branches to compare.
2. Open the "Results" panel.

**Comment by speed-oss** [comment]
@pvormittag if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
