### ISSUE TITLE
Gravatar can not be disabled and does not ask for consent (therefor violates GDPR)

### ISSUE THREAD

**Issue by dvdgsng** [eamodio/vscode-gitlens#492]
Currently, usage of Gravatar can not be disabled. Using Gravatar without consent violates GDPR. Please change gitlens to make usage of Gravatar Opt-In. Adding a new setting that defaults to "false" should be enough, e.g. `"gitlens.enableGravatar": "false"`

**Comment by eamodio** [comment]
You can disable all the avatars (Gravatar) by setting the following (or unchecking the avatar options in the GitLens settings UI):

```json
"gitlens.blame.avatars": false,
"gitlens.explorers.avatars": false,
"gitlens.historyExplorer.avatars" false,
"gitlens.hovers.avatars": false
```

So you can opt-out if you'd like.

As for GDPR, while IANAL, it looks like GDPR only applies to companies. See from https://www.eugdpr.org/gdpr-faqs.html:
### Who does the GDPR affect?
> The GDPR not only applies to organisations located within the EU but it will also apply to organisations located outside of the EU if they offer goods or services to, or monitor the behaviour of, EU data subjects. It applies to all companies processing and holding the personal data of data subjects residing in the European Union, regardless of the company’s location.

**Comment by dvdgsng** [comment]
Thank you for the settings, just what I was looking for. Regarding GDPR: IANAL either and I can now Opt-Out easily, so that's alright with me. Thanks. :)

**Comment by guledali** [comment]
@eamodio You should update the codesnippets 
```
  "gitlens.blame.avatars": false,
  "gitlens.views.fileHistory.avatars": false,
  "gitlens.hovers.avatars": false,
  "gitlens.views.lineHistory.avatars": false
```

**Comment by eamodio** [comment]
@guledali Updated the post above: https://github.com/eamodio/vscode-gitlens/issues/492#issuecomment-417407276
