### ISSUE TITLE
Add size indication to commit history

### ISSUE THREAD

**Issue by tnrich** [eamodio/vscode-gitlens#493]
Hey there! 

First off thanks for the awesome tool! It is great :) 

One thing that I think could make it even better is having some sort of indication next to the side of the commit header to show how big a commit is. As it is currently you need to open each commit to see how many files have been changed: 

![image](https://user-images.githubusercontent.com/2730609/44880208-a92df780-ac60-11e8-9b68-a016509becf2.png)

This is indicated using the size of a circle in one of my favorite git tools in atom (git-time-machine): 

![image](https://user-images.githubusercontent.com/2730609/44880287-e8f4df00-ac60-11e8-82f7-f4b9f6951a4c.png)

But I think any sort of indication could work, maybe something like dots: 

![image](https://user-images.githubusercontent.com/2730609/44880964-daa7c280-ac62-11e8-87d7-6afb5fc1dcaa.png)

Or just simply showing the number of files modified. 

Anyways, I know it would help me visually scan for the commit I'm looking for :) 

Thanks!

**Comment by eamodio** [comment]
Excellent suggestion -- thanks!

**Comment by tnrich** [comment]
👍😄 👍😄 👍😄 👍😄 👍😄

**Comment by speed-oss** [comment]
@tnrich if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
