### ISSUE TITLE
Add more basic git functionality

### ISSUE THREAD

**Issue by aster94** [eamodio/vscode-gitlens#494]
Hello,
as far as a i can see it is not possible to do basic git activity (commit, push, pull,etc) with gitlens.
I am asking this because sometimes i need to add a tag/release and with the integrated git it is not possible and i have to do it via CLI.

do you plan to add them?
maybe your aim isn't to replace the integrated scm but i hope that i am not the only one who thinks that having only a tool/panel in vscode to do everything would be useful

**Comment by HazardDev** [comment]
You can add a tag to the code in the command pallet using the default SCM provider. And as far as I know, adding releases is more of a github-only (or website specific) feature. [This extension](https://github.com/KnisterPeter/vscode-github) adds github project flow if you need that.

**Comment by eamodio** [comment]
For the next major release of GitLens, I am planning on providing more UI and built-in support for more common git actions.

**Comment by aster94** [comment]
this sounds great, can't wait for this major release!

**Comment by felipe1982** [comment]
and rebase!

**Comment by aster94** [comment]
any news? why was it closed?

**Comment by eamodio** [comment]
GitLens 9 was released with many new features.
