### ISSUE TITLE
Short hash length doesn't match git's default length

### ISSUE THREAD

**Issue by ducalex** [eamodio/vscode-gitlens#496]
-   GitLens Version: 8.5.6
-   VSCode Version: 1.26.1

The short hash provided by gitlens doesn't match the one displayed by git (and other tools), is it internally forced to be 8 chars instead of using git's own short hash?

See the attached screenshot for an example:
![Example](https://i.imgur.com/Oi6dWTC.png)

**Comment by eamodio** [comment]
Yeah, it probably makes sense to align with the default abbrev hash length

**Comment by speed-oss** [comment]
@ducalex if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
