### ISSUE TITLE
Why are all the avatars the same?

### ISSUE THREAD

**Issue by Maledong** [eamodio/vscode-gitlens#497]
It seems when I upgrade my VS to the 1.27.0 (the latest version now). No matter how I change the avatar settings, everything is always the same:

1：
![1](https://user-images.githubusercontent.com/40081831/45137136-eb63b580-b1d9-11e8-8911-f2db7fa2c3f0.PNG)

2：
![2](https://user-images.githubusercontent.com/40081831/45137156-ff0f1c00-b1d9-11e8-8a53-4e9e0b5d682c.PNG)

Note:
Uninstall the plug-in and re-install. The same.
Uninstall the VS and re-install, the same.

**Comment by Maledong** [comment]
Note: 
1) Uninstall the plug-in and re-install. The same.
2) Uninstall the VS and re-install, the same.

**Comment by Borkes** [comment]
![image](https://user-images.githubusercontent.com/20042707/45298933-92c74c00-b53c-11e8-90ba-818adda2d8c0.png)

vs 1.27.1
 same bug after upgrade vs.

**Comment by szkaym** [comment]
This issue reported by https://github.com/eamodio/vscode-gitlens/issues/499 .

will be fix next update.

**Comment by eamodio** [comment]
Duplicate of #499 -- Sadly won't be fixed until the next vscode update
