### ISSUE TITLE
Correct committers icon show missing.

### ISSUE THREAD

**Issue by szkaym** [eamodio/vscode-gitlens#499]
- GitLens Version: 8.5.6
- VSCode Version:　1.27.0 （user setup）
- OS Version: Windows7

Steps to Reproduce:

1. Open a repository of projects.
2. Show history of Branches in GitLens.
3. All committers icon show Gravatar default.

**Comment by eamodio** [comment]
Dependent on: https://github.com/Microsoft/vscode/issues/58145

**Comment by eamodio** [comment]
Will be fixed in the next vscode update (Sept) or currently in the insiders builds

**Comment by speed-oss** [comment]
@szkaym if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
