### ISSUE TITLE
why is show warning?

### ISSUE THREAD

**Issue by Zeus-Iqd** [eamodio/vscode-gitlens#500]
please help me? 

![image](https://user-images.githubusercontent.com/25756963/45193383-45b75180-b280-11e8-9e09-bca10d9da05e.png)

**Comment by Zeus-Iqd** [comment]
i can't show gitExplorer:scm UI

**Comment by eamodio** [comment]
Can you post your GitLens settings?

**Comment by Zeus-Iqd** [comment]
{
    "typescript.check.npmIsInstalled": false,
    "workbench.colorTheme": "Visual Studio Light",
    "window.zoomLevel": 0,
    "vetur.format.defaultFormatter.js": "vscode-typescript",
    "vetur.format.defaultFormatter.html": "js-beautify-html",
    "vetur.format.defaultFormatterOptions": {
        "js-beautify-html": {
            "wrap_attributes": "force-aligned"
        }
    },
    "editor.wordWrap": "on",
    "editor.tabSize": 2,
    "editor.fontSize": 16,
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmDelete": false,
    "emmet.triggerExpansionOnTab": true,
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "workbench.iconTheme": "vscode-icons"
}
@eamodio this is my user Settings.   But  I delete this setting about gitLens, this will create a setting automatic. I don't delete this setting. can I help me? Thank you very much. latest version. mac Os.

**Comment by eamodio** [comment]
@Zeus-Iqd are you still having this issue? If so it might be an installation issue -- please try uninstalling GitLens, restarting all vscode windows, and re-install GitLens.

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
