### ISSUE TITLE
An easier way to go from a file history entry to the corresponding commit.

### ISSUE THREAD

**Issue by vadimcn** [eamodio/vscode-gitlens#502]
Right now one has to 1) choose "Show Commit Details" in the context menu, then 2) choose "Show Commit Details" again in the drop-down, then 3) choose "Show in Results" in another drop-down.   Which took me a pretty long time to figure out.  

Would it be possible to add context menu item that does this directly?

**Comment by eamodio** [comment]
Yes! I'm am looking at fixing a lot of these "less than ideal" scenarios in the next major release (coming soon hopefully)! Thanks for the suggestion!

**Comment by speed-oss** [comment]
@vadimcn if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
