### ISSUE TITLE
Open Changes (with difftool) opens one difftool window per changed file.

### ISSUE THREAD

**Issue by phindle** [eamodio/vscode-gitlens#503]
- GitLens Version: 8.5.6
- VSCode Version: 1.27.1
- OS Version: Windows 10 Pro (1803)

**Steps to Reproduce**:

1. Have a project open with 2 files (.cs files) modified.
2. Invoke '_GitLens: Open Changes (with difftool)_' from the command palette (or use Alt+M keyboard shortcut)
3. P4Merge (my configured diff tool) opens twice, one for each modified file.

**Expected outcome**:
Using _Open Changes (with difftool)_ should only difftool the currently open editor.

p.s. Thank you Eric - GitLens is brilliant!

**Comment by eamodio** [comment]
Thanks! 😄 Yeah, that command isn't working properly in that case.

**Comment by kaiseiken** [comment]
I was testing this functionality using Meld on Linux and Windows, which supports file comparisons and directory comparisons.  I believe this is the difference between the two difftool commands as previously implemented.

**Comment by eamodio** [comment]
@kaiseiken Thanks for the report -- would you mind opening a new issue for this _Open All Changes (with difftool)_ missing or not working?
