### ISSUE TITLE
Configure to open commit in remote

### ISSUE THREAD

**Issue by akashnimare** [eamodio/vscode-gitlens#504]
Is this possible to configure to open commit in the upstream always -

![image](https://user-images.githubusercontent.com/2263909/45611085-d6a9dc00-ba7b-11e8-8536-c0c56d9ef861.png)
Here I always want to open the commit in the upstream repo which is `zulip/zulip`

**Comment by akashnimare** [comment]
Yeah, this can save a few seconds everytime you want to open an commit (which happens a lot if you're contributing to a project) :)

**Comment by speed-oss** [comment]
@akashnimare  if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
