### ISSUE TITLE
Ability to edit the local file while in a comparison view with a previous version

### ISSUE THREAD

**Issue by mickeypuri** [eamodio/vscode-gitlens#506]
Ability to view the comparison between the local file version in editor and a previous commit. Then to be able to edit the local file inside of the comparison and then save the local file.

**Comment by eamodio** [comment]
You should be able to do this today. You can use the `Compare File with Working Tree` command anytime you are in a revision and it will put the revision on the left and the working file on the right (which will be editable).

Let me know if this doesn't meet your needs.
