### ISSUE TITLE
Restrict commit message size

### ISSUE THREAD

**Issue by LuizCostaa** [eamodio/vscode-gitlens#507]
I use GitLens with another 5 devs, and sometimes, commit messages can be too long, leaving the explorer area polluted.
I tink would be great if us can change the lengh of messages inside of the GitLens Explorer.

Note: If this feature allready exists, please disregard this issue, and please, say the right way to do.

Tks.

**Comment by eamodio** [comment]
Can you post a screenshot of what you are seeing? These messages should already be truncated.

**Comment by LuizCostaa** [comment]
That's i want mean

![image](https://user-images.githubusercontent.com/28596680/45716814-6cbe2f00-bb6e-11e8-8bc5-18625d0fedcb.png)

The messages are too long, to see who did the commit, i need to extend the explorer's window.

I'm trying to use the advanced formatting method, but this don't resolve my problem.

**Comment by LuizCostaa** [comment]
Tks!!

**Comment by speed-oss** [comment]
@LuizCostaa if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
