### ISSUE TITLE
Ensure detected remotes are enabled in the git panel

### ISSUE THREAD

**Issue by Yajo** [eamodio/vscode-gitlens#508]
It's great that Gitlens detects repositories that are, for instance, found inside a git-ignored subfolder. However, if I open that, then click on "Open changes", and then choose any changes and stage them, I get this error:

```
> git hash-object --stdin -w --path odoo/custom/src/server-auth/auth_oauth_multi_token/__init__.py
> git ls-tree -l HEAD -- odoo/custom/src/server-auth/auth_oauth_multi_token/__init__.py
> git update-index --cacheinfo 100644 f7f1903b37ef9e48a9308206401dd8dac2c6b5f0
 odoo/custom/src/server-auth/auth_oauth_multi_token/__init__.py
error: odoo/custom/src/server-auth/auth_oauth_multi_token/__init__.py: cannot add to the index - missing --add option?
fatal: git update-index: --cacheinfo cannot add odoo/custom/src/server-auth/auth_oauth_multi_token/__init__.py
```

:point_up: There, `odoo/custom/src/*` is ignored, and `odoo/custom/src/server-auth` is a git repo (**not** a git submodule).

If I go to the standard git panel, that repo is not detected (as explained in https://github.com/Microsoft/vscode/issues/41565), although in Gitlens panel, it is:

![captura de pantalla de 2018-09-21 09-31-55](https://user-images.githubusercontent.com/973709/45869848-69e75800-bd81-11e8-98ed-b1b3689acc4b.png)
![captura de pantalla de 2018-09-21 09-31-15](https://user-images.githubusercontent.com/973709/45869854-6b188500-bd81-11e8-8d1d-49eaff673e2c.png)

So, after all of this explanation, I'm wondering if Gitlens could contribute the git repos it detects to the main git panel, so all operations work as expected in this kind of development environments.

**Comment by eamodio** [comment]
Unfortunately this isn't something GitLens can provide -- the built-in git extension would need to handle this. Sorry.
