### ISSUE TITLE
Provide some kind of welcome/orientation for first-time users

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#51]
GitLens has a bunch of features many of which are not very discoverable. Figure out ways to welcome/orient users and/or make features more discoverable.

Any ideas are very welcome here.

**Comment by RogerThiede** [comment]
👍 
I ran into this problem after installing GitLens and opening a source code file.
I couldn't figure out how to access the features such as displaying Git Blame, and my editor had no "Toggle Blame Annotations" button in the upper right.  After hunting around, I realized I had to open the git folder in Visual Studio Code before the GitLens features would activate.  This was very different than my normal use case of opening a source code file via "open xxx.c" in Terminal to open Visual Studio Code with the file.

**Comment by eamodio** [comment]
@RogerThiede FYI in the next GitLens version (coming soon) there will no longer be a restriction on having to open a folder for GitLens to work.

**Comment by eamodio** [comment]
@RogerThiede I've just published v3.2.0 which adds support for working without a loaded folder -- hope that helps!

**Comment by RogerThiede** [comment]
Awesome! It now works intuitively for me when opening files.

**Comment by Giusti** [comment]
I just started with visual studio code, and tried gitlens, I am getting the Error that it cant find my git installation so as suggested I wanted to change the gitlens.advanced.git. But nowhere is actually explained where you enter those commands because they didnt work in cmd + shift + p, or in the terminal so I am kinda confused. When I open cmd + shift + p and enter gitlens I get some commands listed but no way to change the gitlens.advanced.git....

**Comment by eamodio** [comment]
@Giusti sorry for the delayed response, I didn't notice the update to this issue (FYI in the future its best to open a new issue unless there is a true duplicate)

the `gitlens.advanced.git` is a setting that goes into you vscode settings file: See here: https://code.visualstudio.com/docs/getstarted/settings

So you would add a line that looks something like `"gitlens.advanced.git": "<put-your-full-path-to-git.exe-here>"`

Hope that helps.

**Comment by eamodio** [comment]
Here is an early peek into a Welcome page for GitLens. Please let me know what you all think, and what other content the welcome page should have (it is way too light on real content right now). Any suggestions, help, etc is greatly appreciated.

![image](https://user-images.githubusercontent.com/641685/35058551-4e355e9e-fb86-11e7-8f51-abc2e5b33aa2.png)
