### ISSUE TITLE
Toggle git lens cause disappear of Code lens in unit test classes

### ISSUE THREAD

**Issue by mehmetilker** [eamodio/vscode-gitlens#511]
GitLens Version:8.5.6

- VSCode Version:1.27.2
- OS Version:Win10

Steps to Reproduce:

1. F1 Toggle Git Code lens
2. Code lens functions disappear in my Python unit test project.
3. F1 Toggle Git Code lens (again)
4. Code lens appear again

![image](https://user-images.githubusercontent.com/279289/45963486-f5841180-c02b-11e8-81b1-088d7db6ecf2.png)

**Comment by eamodio** [comment]
I would recommend opening an issue with the python extension (or vscode itself) as GitLens uses standard vscode api's to toggle on and off its code lens which unless there is a bug with vscode or the python extensions should not cause any issues.

I know there are outstanding issues with the python extension and interactions with GitLens -- see https://github.com/eamodio/vscode-gitlens/issues/439. Although this really isn't a GitLens issue, as GitLens just makes requests to the language services (just like the Outline view, Code Lens, etc from vscode) and the python extension seems to fail to properly handle these requests when they are issued closely together.
