### ISSUE TITLE
Copying of a commit message to clipboard doesn't work

### ISSUE THREAD

**Issue by narad-git** [eamodio/vscode-gitlens#513]
First, thank you for an amazing extension!
Below is a description of the issue I'm experiencing.

Environment:
GitLens version 8.5.6
over VS code version: 1.27.2
over Fedora core 27
over VirtualBox 5.2.18
over Windows 10

To reproduce:
- Open a git controlled project with at least one commit
- Go to GitLens explorer
- Enter current branch
- Open history
- Right click a commit
- Click "Copy commit message to clipboard"
- Try to paste the message anywhere

Expected result:
- Commit message should be pasted

Actual result:
- Whatever was previously in the clipboard is pasted

Notes:
- I tried to paste inside a VS code editor as well as in a separate GNOME terminal window, with same results.

**Comment by eamodio** [comment]
I can't reproduce this issue -- although it is likely to do with a clipboard dependency and your version of Linux. Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings.json. Then reproduce the issue and post the output from the `GitLens` channel in the Output pane?

**Comment by narad-git** [comment]
The problem was that xsel was not installed.
Please note that the error message that popped up after enabling debug provided installation instructions for debian-based distributions (apt install), which could mislead some users.
After installing xsel and restarting vscode, I am able to copy commit descriptions.
Thank you!

**Comment by eamodio** [comment]
@narad-git the error message didn't show up until you set the `outputLevel`? If so that is a bug :)

Also what part is misleading?

**Comment by eamodio** [comment]
Hrm, I looked into it and I can't see how setting `outputLevel` would have any effect on that error message appearing or not. Is it possible that you just missed the message before?

As for the message I will change the text to "Please install it via your package manager, e.g. `sudo apt install xsel`"

The output logging logs in UTC

**Comment by narad-git** [comment]
Yes, it is possible I missed it. Thanks.
