### ISSUE TITLE
CodeLens is showing author line even when disabled

### ISSUE THREAD

**Issue by ypapouin** [eamodio/vscode-gitlens#514]
I think that's a bug since the author line is displayed for python import line with specific pattern
eg: from .models.report import Report

![image](https://user-images.githubusercontent.com/22446243/46063429-14d68800-c16d-11e8-874a-d280d6c50f12.png)

- GitLens Version:
Extension | Author (truncated) | Version
-- | -- | --
gitlens | eam | 8.5.6
copy-word | ale | 2.1.0
pascal | ale | 6.4.0
multiline-find-and-replace | axl | 0.0.1
django-html | bib | 1.2.0
path-intellisense | chr | 1.4.2
bracket-pair-colorizer | Coe | 1.0.60
smoothscroll | cya | 1.0.4
createuniqueid | don | 0.0.3
xml | Dot | 2.3.2
vscode-npm-script | eg2 | 0.3.5
vsc-material-theme | Equ | 2.4.2
battery-indicator | fbo | 1.0.0
shortcuts | giz | 0.0.1
path-autocomplete | ion | 1.12.0
switchit | jbe | 1.0.2
csharpextensions | jch | 1.3.0
vscode-random | jre | 1.3.2
vscode-insertdatestring | jsy | 2.2.3
vscode-icon-theme | jtl | 1.6.3
docomment | k-- | 0.1.2
python | ms- | 2018.8.0
cpptools | ms- | 0.18.1
csharp | ms- | 1.16.1
mono-debug | ms- | 0.15.8
PowerShell | ms- | 1.8.4
trailing-semicolon | nau | 1.0.2
indent-rainbow | ode | 7.2.4
vscode-docker | Pet | 0.3.1
diff | raf | 0.0.1
classynaming | ref | 1.2.0
code-settings-sync | Sha | 3.1.2
shader | sle | 1.1.3
vscode-hexdump | sle | 1.6.0
vscode-multiclip | sle | 0.1.4
unity-debug | Uni | 2.6.1
transpose | v4r | 0.0.5
vscode-todo-highlight | way | 1.0.4
unity-snippets | Ycl | 0.1.2
html-css-class-completion | Zig | 1.17.1

- VSCode Version:
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version:
Win10

**Comment by eamodio** [comment]
How are you disabling the code lens?

**Comment by ypapouin** [comment]
I first tried to set

    "gitlens.codeLens.authors.enabled": false,

But the author line was still displayed.
So I had to set this line instead:

    "gitlens.codeLens.enabled": false,

**Comment by eamodio** [comment]
Ah, yeah, there are 2 code lenses that GitLens adds, a "recent changes" one (the `You, 2 days ago`), and an authors one that only shows if there is more than 1 author for that block. The first is controlled by `gitlens.codeLens.recentChange.enabled` and the latter `gitlens.codeLens.authors.enabled`. And both of them can be turned off completely by using `gitlens.codeLens.enabled`.

You can also use the GitLens interactive settings editor from the command palette run `GitLens: Open Settings`.
