### ISSUE TITLE
Bug: Right click don't work properly in VS Code when gitlens is enabled

### ISSUE THREAD

**Issue by i-shubhamprakash** [eamodio/vscode-gitlens#518]
- GitLens Version:8.5.6

- VSCode Version: 1.27.2
- OS Version: Linux mint 19
 
# Bug description:
1. When I right click on the editor (not on the code), it opens Branch History menu.
2. When I right click on any code, it opens git diff view.
3. when I select text and then right click, it opens function definition view.
4. Sometimes it shows random behavior on right-clicking anywhere in the editor.  For example, it opens the Github repository page in chrome or git diff page in chrome, or even try to run code-runner extension etc.

# Why I think the above problem is occurring due to this extension?

I disabled all the extension and none of the problems occurred. I then enabled every extension one by one each time to check which extension is causing this issue. I found gitlens extension when enable, cause this problem.
I then disabled all the extension and enabled only gitlens to confirm if this is causing the issue and was right.

Please fix this issue.
Your extension is very helpful and I love using it. Nice work.
Thanks.

**Comment by eamodio** [comment]
Unfortunately I can't see how this could possibly happen outside of a corrupted vscode install or bugs within vscode itself. Vscode provides extensions a very limited api to work with, and GitLens cannot control when menus are shown or not -- all I can do is tell vscode (statically in my package.json) that GitLens wants a set of menu items added to a set of named menus and a condition for when.

Are you running any other extensions or things that modify the base vscode install? You might also want to try setting `"window.titleBarStyle": "native"` to see if that has any affect on the issues you are seeing.

**Comment by i-shubhamprakash** [comment]
Currently, I am not running any other extensions or things that modify the base vscode install.
I am not facing the above issue after I uninstalled GitLens extension.
Let me install it again and tell you if the problem returned.

Thanks.

**Comment by i-shubhamprakash** [comment]
As suggested by you, I tried setting "window.titleBarStyle": "native" and found the issue no longer persist.
the editor is functioning normally without any problem.

**Comment by i-shubhamprakash** [comment]
Probably the problem is with VS code custom title bar. But why did the problem occurred only when gitlens was installed? Is it related to this extension also?

**Comment by eamodio** [comment]
Hrm, definitely a vscode bug -- something that GitLens must expose (though I fail to understand how). I would recommend opening an issue with the vscode repo and reference this issue. Hopefully they can get to the bottom of the issue.

**Comment by i-shubhamprakash** [comment]
Alright, I'm opening this issue in the vscode repo referencing this issue.
Thanks for the help.

**Comment by i-shubhamprakash** [comment]
@eamodio The above issue was due to this https://github.com/Microsoft/vscode/issues/57399
It is now fixed in the latest build of VS code i.e.  v1.28
Thanks :)
