### ISSUE TITLE
(False Positive) Extension reported as Trojan by ESET

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [eamodio/vscode-gitlens#520]
Output from ESET Endpoint Security:

```
2018-10-09 2:55:48 PM
Real-time file system protection
C:\Users\<username>\.vscode\extensions\eamodio.gitlens-8.5.6\out\extension.js
a variant of Generik.DHSMSJE trojan
cleaned by deleting
Event occurred during an attempt to access the file by the application: C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\Code.exe
```

- GitLens Version: 8.5.6

- VSCode Version: 1.27.2
- OS Version: Windows 10

Steps to Reproduce:
I had GitLens installed for quite some time now, this appeared while working in vscode.

**Comment by hesperanca** [comment]
Yep same here with exactly the same file. ESET just deleted the file and GitLens stopped working :( 

- VS Code version: 1.28.0
- GitLens version 8.5.6
- OS: windows 10

**Comment by troy-johnson** [comment]
Same thing here. 

GitLens: 8.5.6
VS Code: 1.28.0
OS: macOS Sierra 10.12.6

**Comment by vadviktor** [comment]
Interestingly enough, I have downloaded, extracted the vsix file from the release page, scanned it with Eset manually and found nothing. When installing it as a plugin from the marketplace, it is infected.

Could it be that the marketplace file is hijacked and infected?

**Comment by kevinmarty** [comment]
I had the same problem. Scanning the extension.js file with VirusTotal shows that ESET is the only program flagging it as malicious. False positive?

https://www.virustotal.com/#/file/a81e9e9ee185c98648db5701a72f0cb9ae9fd4fd2a58a5d6a517d6e4345440e7/detection

**Comment by eamodio** [comment]
I'm not sure what to say on this one -- I've scanned the files and everything comes up clean, and Microsoft scans the extensions as they are published to the marketplace. This must be a false positive. I also can't seem to find a way to report it to ESET as a false positive. Anyone know how?

**Comment by eamodio** [comment]
Also from the virustotal scan, it seems that ESET is now reporting it clean. Does anyone still see this issue after ensuring ESET is up to date?

**Comment by eamodio** [comment]
Closing this as it is a false positive
