### ISSUE TITLE
File History doesn't show all commits on file 

### ISSUE THREAD

**Issue by fbehrens** [eamodio/vscode-gitlens#523]
Hi, thanks for the amazing extension. I am using it in the following environment:

- GitLens Version: 8.5.6
- VSCode Version: latest stable
- OS Version: Windows 10

here is my File History Explorer on my `gitlab-ci.yml` file
![image](https://user-images.githubusercontent.com/13704/46798077-2dd85f00-cd51-11e8-933e-6eb7fbf0f5e5.png)

There are changes in the file (coming in from a merge request), which are not shown. Compare this with:
```
git log --graph -5 .gitlab-ci.yml
* bb098e45 - (HEAD -> develop, origin/develop, origin/HEAD) fix gitlab-ci (24 minutes ago) <Frank Behrens>
*   c3caf15d - Merge branch 'mobility' into 'develop' (2 hours ago) <Markus Sauerland>
|\
| *   bd9af011 - Bugfixing and extended logging (2 hours ago) <_Frank Helfrich>
| |\
| * | ab86adfc - Fixed bug with wrong message template in recreate process (5 weeks ago) <_Frank Helfrich>
* | | c3294ed1 - make 0t0x into prod (9 days ago) <Frank Behrens>
| |/
|/|
```

Why are the commits `c3caf15d`, `bd9af011` and `c3294ed1` which introduced chages in the file not shown in the File History Explorer ? Is this a bug or am I missing something ?

**Comment by eamodio** [comment]
Can you try turning off follow renames (from the ... menu on the explorer) and see if that helps?

**Comment by fbehrens** [comment]
Switching off `follow renames` doesn't change the effect. 

For your answer I assume this is a bug.

In the commits no file-renaming was involved. Instead they contain some unresolved merge conflict markers someone accidentally checked in. The VSCODE diff window doesn't render my correcting commit (bb0..) correctly. This may be the reason for this bug, and I am fine to leave it like this.

However, if you want to trace this down, I will provide all required information to fix this.

**Comment by eamodio** [comment]
Is the repo public where you can reproduce this?

**Comment by fbehrens** [comment]
its on private gitlab, I can give you access if you are interested, on your email ?

**Comment by someusersomeuser** [comment]
my case
some files in project after open with Explorer tree no have history
![image](https://user-images.githubusercontent.com/36192774/48766113-c2c16700-ecc4-11e8-9199-eb23f22b43af.png)
after open this same file with buton in diff tool, history display correct
![image](https://user-images.githubusercontent.com/36192774/48766438-8c381c00-ecc5-11e8-96e4-18e572d68ab5.png)
now i have 2 tabs for one file - one with history, another without
this is permanent state - after reopen all, reboot, etc.

 "true" tab in debugger: const cachedLog
PromiseStatus: "resolved", and PromiseValue contains log
![image](https://user-images.githubusercontent.com/36192774/48775445-20ae7880-ecde-11e8-8f6e-9a52bc429ea4.png)


for "bad" tab, PromiseStatus: "resolved", and PromiseValue = undefined

sorry, repo is private.
