### ISSUE TITLE
Codelens Not Showing Author Information for Block Code

### ISSUE THREAD

**Issue by Tonylic** [eamodio/vscode-gitlens#524]
- Extension Name: gitlens
- Extension Version: 8.5.6
- OS Version: MacOS X High Sierra 10.13.6
- VSCode version: 1.28.0

After upgrading to High Sierra, Gitlens stops showing author information for block function code, even if I added `blocks` into `gitlens.codeLens.scopes`. Document and container part look good still.

**Comment by Perdek** [comment]
Same problem
Extension Version: 8.5.6
OS Version: Windows 10 1809
VSCode version: 1.28.1

**Comment by eamodio** [comment]
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by Perdek** [comment]
[gitlens.txt](https://github.com/eamodio/vscode-gitlens/files/2493442/gitlens.txt)

**Comment by eamodio** [comment]
@Perdek Can you try GitLens 9 and see if you are still experiencing the issue? If so what version of the C# extension are you running?

**Comment by Perdek** [comment]
@eamodio With GitLens 9 this problem disappeared. Thanks!

**Comment by Tonylic** [comment]
Working fine now after updating to 9 as well. Thanks!
