### ISSUE TITLE
FAILED in gitlens.outputLevel=verbose; likely due to regex not in quotes

### ISSUE THREAD

**Issue by diablodale** [eamodio/vscode-gitlens#526]
FAILED errors are appearing in the GitLens logs. Perhaps these are harmless, though I've isolated the issues and perhaps it can be fixed.

At some part of the GitLens startup on a repo, it is doing several activities which include getting the user.name and user.email. However, the regex that is given is not within quotes or shell escaped. Therefore, it fails due to special characters like the following three `)(|`. Naturally, there are even more special characters recognized by the cmd, power, sh, and bash shells.

The command attempted is:
```
git -c core.quotepath=false -c color.ui=false config --get-regex user.(name|email)
```

This will fail in many cases:
* CMD will see the `|` pipe and try to route output to an executable named `email)`. The specific error that CMD will give is:
  ```
  'email)' is not recognized as an internal or external command,
  operable program or batch file.
  ```
* BASH will see the `(` and fail with the error:
  ```
  -bash: syntax error near unexpected token `('
  ```
* SH will have error:
  ```
  sh: 1: Syntax error: "(" unexpected
  ```

## Setup
Extension version: 8.5.6
VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

## Steps to Reproduce

1. Run vscode
2. View errors in gitlens logs

## Expected

No errors in GitLens logs

## Actual Result

GitLens
```
Running(n:/opsworkspace/zfs-auto-snapshot): git blame --root --incremental -- Makefile
Completed(n:/opsworkspace/zfs-auto-snapshot): git blame --root --incremental -- Makefile Completed in 1297 ms
Running(n:/opsworkspace/zfs-auto-snapshot): git config --get-regex user.(name|email)
FAILED(n:/opsworkspace/zfs-auto-snapshot): git config --get-regex user.(name|email) FAILED in 259 ms
getBlameForRangeSync('n:/opsworkspace/zfs-auto-snapshot', 'n:\opsworkspace\zfs-auto-snapshot\Makefile', 'undefined', [0, 28])
```

GitLens (git)
```
[2018-10-14 01:19:37:561] git rev-parse --show-toplevel Completed in 460 ms (n:\opsworkspace\zfs-auto-snapshot)
[2018-10-14 01:19:38:121] git remote -v Completed in 527 ms (n:/opsworkspace/zfs-auto-snapshot)
[2018-10-14 01:19:38:542] git ls-files Makefile Completed in 409 ms (n:/opsworkspace/zfs-auto-snapshot)
[2018-10-14 01:19:38:543] git ls-files Makefile Completed in 403 ms (n:/opsworkspace/zfs-auto-snapshot)
[2018-10-14 01:19:38:924] git ls-files n:\opsworkspace\zfs-auto-snapshot\Makefile Completed in 379 ms (n:/opsworkspace/zfs-auto-snapshot)
[2018-10-14 01:19:40:225] git blame --root --incremental -- Makefile Completed in 1297 ms (n:/opsworkspace/zfs-auto-snapshot)
[2018-10-14 01:19:40:485] git config --get-regex user.(name|email) FAILED in 259 ms (n:/opsworkspace/zfs-auto-snapshot)

Error: Command failed: C:\njs\wslgit\wslgit.exe -c core.quotepath=false -c color.ui=false config --get-regex user.(name|email)
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `cd /mnt/n/opsworkspace/zfs-auto-snapshot && git -c core.quotepath=false -c color.ui=false config --get-regex user.(name|email)'
```

## Workaround

None known.
If the commands are sent to a command interpreter (cmd, bash, sh, etc.) then special characters must be escaped or quoted. It is possible to bypass a command interpreter, however, that may be a substantial change to codebase.

Since the escaping method and special characters are different in each command interpreter, the code will likely need to take the most common approach -or- create a conditional escaping mechanism.

Below are three quick ways of escaping/quoting. Of these three, only the third (double quotes) may work in all three shells (cmd, bash, and sh). Maybe....

git config --get-regex user.\(name\|email\)
git config --get-regex 'user.(name|email)'
git config --get-regex "user.(name|email)"

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition? Be sure to disable/uninstall the stable version of GitLens first.

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).
