### ISSUE TITLE
GitLens icon flashes on startup

### ISSUE THREAD

**Issue by nealot** [eamodio/vscode-gitlens#527]
Gitlens version: 8.5.6
Vscode version: 1.29.0-insider

I've noticed that when I open a git folder, gitlens disappears for a moment before reappearing. This is the only activity bar icon that does this, so I'm wondering if it might be a bug. It seems similar to https://github.com/eamodio/vscode-gitlens/issues/447, but that was supposedly fixed? The icon reappears exactly when the SCM badge is displayed.

**Comment by eamodio** [comment]
This will be resolved in the next version of GitLens coming "soon" 😄

**Comment by speed-oss** [comment]
@nealot if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
