### ISSUE TITLE
Remotes not showing, being filtred on domain and file, but not complete path

### ISSUE THREAD

**Issue by GargIT** [eamodio/vscode-gitlens#528]
- GitLens Version: 8.5

- VSCode Version: 1.28.1
- OS Version: Debian 9

Steps to Reproduce:

Have this in the gitconfig

ssh://bahamas2.millnet.site:~dajo/milltime.git
ssh://bahamas2.millnet.site:~dean/milltime.git
ssh://bahamas2.millnet.site:~erma/milltime.git
ssh://bahamas2.millnet.site:~heth/milltime.git
ssh://bahamas2.millnet.site:~maho/milltime.git

And they all being treated as one remote

Full match | 0-46 | `ssh://bahamas2.millnet.site:~dajo/milltime.git`
Group 5. | 6-27 | `bahamas2.millnet.site`
Group 6. | 34-46 | `milltime.git`

**Comment by GargIT** [comment]
my bad, replaced ~ with /home/ and now it works :-)

**Comment by eamodio** [comment]
I would still say this is an issue. I should support `~` in the remote

**Comment by speed-oss** [comment]
@GargIT if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
