### ISSUE TITLE
Show Repository History does not show commits that are upstream

### ISSUE THREAD

**Issue by bfranklyn** [eamodio/vscode-gitlens#53]
This is more of a feature request.
Would it be possible to include a setting to allow the show repository history to also include commits that are upstream?
Currently it only shows commits that have already been pulled down.

**Comment by eamodio** [comment]
@bfranklyn what is the use-case for this? Like how would you want to use it?

I think there are some challenging/tricky issues involved depending on how it would work.

But I have some ideas that while not exactly this could be useful. Like providing "sync" status on the repository status -- maybe even a command there to show only the commits you haven't pulled yet

**Comment by bfranklyn** [comment]
@eamodio sometimes when there are commits up stream, I would like to see some details about those commits like the person who made the commits, commit messages, and probably the files that were changed. I can see how it may be difficult or even impossible but the sync status idea sounds great! And it would indeed solve my use case to some extent.

**Comment by eamodio** [comment]
@bfranklyn I've added support for seeing upstream info in the `GitLens: Show Repository Status` command (also `alt+s`) -- where you can see the set of commits yet to be pulled and/or pushed. 

Please let me know if this satisfies your request.

**Comment by bfranklyn** [comment]
@eamodio Awesome, it is exactly what I was looking for. Thank you very much 👍.
