### ISSUE TITLE
How to remove top-right icons

### ISSUE THREAD

**Issue by lorensr** [eamodio/vscode-gitlens#530]
I read the extensions Details page, but didn't see anything about how to remove these icons at the top-right of the screen?

![image](https://user-images.githubusercontent.com/251288/47115567-f70cb800-d22c-11e8-8003-8c9eb5522ea9.png)

**Comment by lorensr** [comment]
Update: first icon is from Git History, removed by `"gitHistory.showEditorTitleMenuBarIcons": false,`

Second and last are not from this extension, but these two appear to be:

![image](https://user-images.githubusercontent.com/251288/47115831-c37e5d80-d22d-11e8-8413-f0a66da82224.png)

**Comment by eamodio** [comment]
You can customize them using the `gitlens.menus` setting -- or you can also use the GitLens interactive settings editor from the command palette run `GitLens: Open Settings`. See the **Menus & Toolbars** section of the **General** group

Hope that helps!

**Comment by lorensr** [comment]
Thanks, it was the second-to-last item, and required a `Reload Window` to take effect:

![image](https://user-images.githubusercontent.com/251288/47116957-14438580-d231-11e8-98dd-39653a2cb215.png)

**Comment by Vardi** [comment]
In 2020, this is now achieved by deselecting 'Add commands to the editor group toolbar':
![image](https://user-images.githubusercontent.com/9982862/84119217-59cf4a80-aa34-11ea-95c6-b839a0855d03.png)

**Comment by MuhsinFatih** [comment]
Could you make an option so the "editorGroup"->"compare" buttons only show up when viewing a revision?  
I mean these guys:  
![image](https://user-images.githubusercontent.com/8341386/85828088-8afa8b00-b755-11ea-970f-70715a8a275f.png)

As in, I would:
\- run "open changes with previous revision" in command palette
\- then the 3 buttons show up
\- I close the revision window
\- 3 buttons disappear

The buttons are extremely useful, but they take up such a huge space that I sometimes can't see more than one tab in a split window title
