### ISSUE TITLE
How to stage files interactively?

### ISSUE THREAD

**Issue by bendtherules** [eamodio/vscode-gitlens#531]
How do I do the equivalent of `git add -i` inside vscode using gitlens?

I would like to commit parts of a file by choosing the specific lines/hunk in the editor. But couldn't find something like this in gitlens.

If not possible currently, please consider this a feature request.

**Comment by eamodio** [comment]
This is already possible with the built-in vscode git extension via `Stage Selected Range` & `Unstage Selected Range`. Let me know if you were looking for something else.

**Comment by Trass3r** [comment]
I guess he meant a truly interactive version like git add -p which works way faster for me than manually going through the file in the UI because it jumps to the next line on its own and I just need to press 1 key to stage.

**Comment by bendtherules** [comment]
1. I think there is shortcut for goto next change within current file. But yes, you have to still go to each modified file manually and select changed lines manually.

2. Another odd thing is that - it always considers the full line for add/remove to stage, not exactly the selection. So, it's not possible to add only part of the change in a line through UI.

3. Also editing chunk (like diff edit in git add) before staging is not possible.

Makes me think there can be a better ui for git add interactive (maybe a separate extension /command) , which is closer to the original experience.

**Comment by Trass3r** [comment]
It also has a lot of quirks. Jumping to the next change often skips 1, you can't stage a pure deletion change from the UI, you can't stage parts of a hunk as you said.
And most of all the default keyboard shortcuts for all those actions are insanely complicated.

**Comment by bendtherules** [comment]
You can stage a deletion change. In a diff, wherever you see deletion on
the left - you just have to select the a region covering that, on right
side.

I often try to select on left to try to stage it, but this context command
doesn't show up there.

Agree with all the rest.

**Comment by Trass3r** [comment]
Yeah and then you have to remember not to right-click on the red part but on some other.
Also it just happened to me that staging a hunk only staged the deletions but not the additions, very weird.
