### ISSUE TITLE
Some descriptions not using markdown properly in Settings GUI

### ISSUE THREAD

**Issue by beastdestroyer** [eamodio/vscode-gitlens#533]
This issue doesn't have any relevance to the extension functionality itself. Just thought it could do a bit of fixing with the descriptions in VSCode Settings GUI. Below I have listed all the location where markdown code doesn't seem to be working, or where it could be added. This is based on the current state of how it's used in VSCode, I don't mean to say do this do that.

BEWARE: QUITE LONG

1. Advanced › Blame: Custom Arguments
  - `git blame` doesn't show as monospace
2. Advanced: Git
  - `git.path` doesn't show as monospace
3. Advanced › Telemetry: Enabled
  - `telemetry.enableTelemetry` doesn't show as monospace
4. Blame: Date Format
  - `${date}` doesn't show as monospace
  -  https://momentjs.com/docs/#/displaying/format/ should use the blue hyperlink format
5. Blame: Format
  - ${id}, ${author}, ${message}, ${ago}, ${date}, ${date}, ${agoOrDate}, ${authorAgo}, ${authorAgoOrDate} should be monospace
  - `gitlens.blame.dateFormat`, `gitlens.defaultDateStyle` not showing as monospace
  - https://github.com/eamodio/vscode-gitlens/wiki/Advanced-Formatting should use the blue hyperlink format
6. Code Lens › Authors: Command
  - `authors` not showing monospaced
7. Code Lens › Authors: Enabled
  - `authors` not showing monospaced
8. Code Lens: Enabled
  - `Toggle Git Code Lens`, `gitlends.toggleCodeLends` not showing monospaced
9. Code Lens › Recent Change: Command
  - `recent change` not showing monospaced
10. Code Lens › Recent Change: Enabled
  - `recent change` not showing monospaced
11. Code Lens: Symbol Scopes
  - `!`, `SymbolKind` not showing monospaced
12. Current Line: Date Format
  - `${date}` not showing monospaced
  - https://momentjs.com/docs/#/displaying/format/ not showing as blue hyperlink
13. Current Line: Enabled
  - `Toggle Line Blame Annotations`, `gitlens.toggleLineBlame` not showing monospaced
14. Current Line: Format
 - ${id}, ${author}, ${message}, ${ago}, ${date}, ${date}, ${agoOrDate}, ${authorAgo}, ${authorAgoOrDate} should be monospace
  - `gitlens.currentLine.dateFormat`, `gitlens.defaultDateStyle` not showing as monospace
  - https://github.com/eamodio/vscode-gitlens/wiki/Advanced-Formatting should use the blue hyperlink
15. Default Date Format
  - https://momentjs.com/docs/#/displaying/format/ not showing as blue hyperlink
16. Explorers: Avatars
  - `GitLens`, `GitLens Results` not showing monospaced
17. Explorers: Commit File Format
  - ${directory}, ${file}, ${filePath}, ${path} should be monospaced
18. Explorers: Commit Format
    - ${id}, ${author}, ${message}, ${ago}, ${date}, ${date}, ${agoOrDate}, ${authorAgo}, ${authorAgoOrDate} should be monospace
  - `gitlens.defaultDateFormat`, `gitlens.defaultDateStyle` not showing as monospace
  - https://github.com/eamodio/vscode-gitlens/wiki/Advanced-Formatting should use the blue hyperlink
   - Random `\n` appearing in the description and breaking it up
19. Explorers: Stash File Format 
  - ${directory}, ${file}, ${filePath}, ${path} should be monospaced
20. Stash Format
  - ${id}, ${author}, ${message}, ${ago}, ${date}, ${date}, ${agoOrDate}, ${authorAgo}, ${authorAgoOrDate} should be monospace
  - `gitlens.statusBar.dateFormat`, `gitlens.defaultDateStyle` not showing as monospace
  - https://github.com/eamodio/vscode-gitlens/wiki/Advanced-Formatting should use the blue hyperlink
21. Explorers: Status File Format
  - ${directory}, ${file}, ${filePath}, ${path}, ${working} should be monospaced
22. Git Explorer > Branches: Layout
  - `GitLens` not showing as monospace
23. Git Explorer: Enabled
  - `GitLens` not showing as monospace 
24. Git Explorer > Files: Compact
  - `GitLens` not showing as monospace
  - `gitlens.gitExplorer.files.layout`, `tree`, `auto` not showing as monospace
  - Random `#` in `gitlens.gitExplorer.files.layout`
25. Git Explorer > Files: Layout
  - `GitLens` not showing as monospace 
26. Git Explorer > Files: Threshold
  - `GitLens`, `gitlens.gitExplorer.files.layout`, `tree`, `list`, `auto` not showing as monospace
  - Random `#` in `gitlens.gitExplorer.files.layout`
27. Git Explorer: Include Working Tree
  - `Repository Status`, `GitLens` not showing as monospace
28. Git Explorer: Location
  - `GitLens` not showing as monospace
29. Git Explorer: Show Tracking Branch 
  - `GitLens` not showing as monospace
30. Git Explorer: View 
  - `GitLens` not showing as monospace
31. Heatmap: Age Threshold
  -  `gitlens.heatmap.coldColor`, `gitlens.heatmap.hotColor` not showing as monospace
  -  Random `#` in `gitlens.heatmap.coldColor`, `gitlens.heatmap.hotColor`
32. Heatmap: Cold Color
  -  `gitlens.heatmap.ageThreshold` not showing as monospace
  - Random `#`
33. Heatmap: Hot Color
  -  `gitlens.heatmap.ageThreshold` not showing as monospace
  - Random `#`
34. History Explorer: Enabled
  - `GitLens File History` not showing monospaced
35. History Explorer: Location
  - `GitLens File History` not showing monospaced
36. Results Explorer › Files: Compact
  - `GitLens Results`, `gitlens.resultsExplorer.files.layout`, `tree`, `auto` not showing as monospace
  - Random `#` in `gitlens.resultsExplorer.files.layout`
37. Results Explorer > Files: Layout
  - `GitLens Results` not showing monospaced
38. Results Explorer › Files: Threshold
  - `GitLens Results`, `gitlens.resultsExplorer.files.layout`, `tree`, `list` not showing as monospace
  - Random `#` in `gitlens.resultsExplorer.files.layout`
39. Results Explorer: Location
  - `GitLens Results` not showing monospaced
40. Status Bar: Date Format
  - https://momentjs.com/docs/#/displaying/format/  not showing as blue hyperlink
41. Status Bar: Format
 - ${id}, ${author}, ${message}, ${ago}, ${date}, ${date}, ${agoOrDate}, ${authorAgo}, ${authorAgoOrDate} should be monospace
  - `gitlens.statusBar.dateFormat`, `gitlens.defaultDateStyle` not showing as monospace
  - https://github.com/eamodio/vscode-gitlens/wiki/Advanced-Formatting should use the blue hyperlink
42. Strings › Code Lens › Unsaved Changes: Authors Only
  - `authors` not showing as monospace
43. Strings › Code Lens › Unsaved Changes: Recent Change And Authors
  - `recent change`, `authors` not showing as monospace
44. Strings › Code Lens › Unsaved Changes: Recent Change Only
  - `recent change` not showing as monospace

**Comment by speed-oss** [comment]
@beastdestroyer if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
