### ISSUE TITLE
Hover effect

### ISSUE THREAD

**Issue by martinbergpetersen** [eamodio/vscode-gitlens#534]
Gitlens line annotation: Show information on hover.

Could it be possible to have a keyboard command for showing the line information instead of using the mouse to activate hover effect.
As it is right now  you have to hover over the line annotation with the mouse before the information is shown. It could be really nice to stand on a line, and use the keyboard to see the extended information instead of hovering over the line annotation.

**Comment by eamodio** [comment]
Unfortunately there isn't any way for a vscode extension to trigger a hover -- we can only provide them over a range and vscode handles the rest.
