### ISSUE TITLE
Compare HEAD / Compare Working Copy should support commit IDs

### ISSUE THREAD

**Issue by pimlottc-gov** [eamodio/vscode-gitlens#535]
The commands for comparing HEAD or working copy only support branches and tags.  It should also allow you to enter a commit ID.  The dropdown doesn't necessarily need to list them, but you should be type/paste one directly.

Rationale:
Comparing to an arbitrary commit is useful when code reviewing feature branches.  If a branch has not yet been rebased to the current master, then the merge base will be just a commit id without a tag or branch name attached.

**Comment by speed-oss** [comment]
@pimlottc-gov if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
