### ISSUE TITLE
Support "Stage selected ranges" in diff view

### ISSUE THREAD

**Issue by erihanse** [eamodio/vscode-gitlens#536]
Issue Type: <b>Feature</b>

With the built in SCM in vs code, we can stage selected lines by marking the lines we want to apply and invoking the Git: Stage Selected Ranges. Is this supposed to work in gitlens as well, or is there another way to achieve this? 

Extension version: 8.5.6
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
I'm not sure I understand what you are asking for -- as you mentioned the built-in git extension provides this, but I'm not sure what part when using GitLens you are missing. You can only stage changes from the working tree.

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
