### ISSUE TITLE
Author date or Commit date

### ISSUE THREAD

**Issue by ihgsm** [eamodio/vscode-gitlens#537]
Hi,

It looks to me all the dates (absolute and relative) used in gitlens are author date(even it is called commit date in settings) . Is there a way to switch to show the commit date which is the last time the change was commited? Thanks.

**Comment by eamodio** [comment]
Unfortunately GitLens only currently shows the authored date. Would you like to always see the commit date, or just have the commit date accessible in the commit tooltip or something?
