### ISSUE TITLE
Wrong highlight when ignoring FOLDER but NOT SOME files

### ISSUE THREAD

**Issue by jpenna** [eamodio/vscode-gitlens#538]
- GitLens Version: 8.5.6
- VSCode Version: 1.28.2
- OS Version: MacOS 10.13.6

Files are wrongly highlighted when using .gitignore with DON'T ignore:

```.gitignore
# .gitignore
folder/*
!folder/*.track.json
```

<img width="345" alt="screen shot 2018-11-02 at 12 19 35 pm" src="https://user-images.githubusercontent.com/16005946/47893786-d170e700-de99-11e8-8610-5131a401c2b8.png">

Code and Git are tracking correctly.

<img width="339" alt="screen shot 2018-11-02 at 12 20 18 pm" src="https://user-images.githubusercontent.com/16005946/47893787-d170e700-de99-11e8-866b-fab8d85ce650.png">
<img width="340" alt="screen shot 2018-11-02 at 12 20 34 pm" src="https://user-images.githubusercontent.com/16005946/47893789-d2a21400-de99-11e8-8942-400723ed4261.png">

`*.sample.json` should be highlighted and tracked. The others not.

Steps to reproduce:
 1. Just create a folder, ignore it in .gitignore and "unignore" some files.

**Comment by eamodio** [comment]
@jpenna GitLens doesn't provide the features you've shown above -- they are provided by the built-in vscode Git extension. Please file an issue with the vscode repository.
