### ISSUE TITLE
Apply diff

### ISSUE THREAD

**Issue by gennaro-tedesco** [eamodio/vscode-gitlens#539]
functionality: Compare Working Tree with branch...

question: is it possible to directly "apply changes" from file to file in different branches? Say we are looking at the `git diff` between the same file in two different branches and we want to apply it: I assume such functionality is there but I have been unable to find it.

**Comment by eamodio** [comment]
This feature is in GitLens 9 -- hopefully coming out "soon" 😄

**Comment by gennaro-tedesco** [comment]
oh great, thank you for looking into it!

**Comment by speed-oss** [comment]
@gennaro-tedesco if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com) :)
