### ISSUE TITLE
Add option to hide editor title buttons

### ISSUE THREAD

**Issue by forivall** [eamodio/vscode-gitlens#540]
It would be nice to have an option to hide the buttons in the editor title bar -- the ones in the split pane field.

![screen shot 2018-11-02 at 5 46 31 pm](https://user-images.githubusercontent.com/760204/47946301-41e22d00-dec7-11e8-9a5c-6343e033c2ca.png)

it should be as simple as adding an option and then adding the option to the "when" option in the clause in the package.json @ https://github.com/eamodio/vscode-gitlens/blob/4ddb871/package.json#L2701

for example, another plugin has exactly this kind of option: https://github.com/DonJayamanne/gitHistoryVSCode/blob/016e927/package.json#L187

**Comment by eamodio** [comment]
You can customize them using the `gitlens.menus` setting -- or you can also use the GitLens interactive settings editor from the command palette; run *GitLens: Open Settings*. See the **Menus & Toolbars** section of the **General** group

Hope that helps!

**Comment by naguibihab** [comment]
I disabled the menu & toolbars and reloaded but that title bar is still there

**Comment by gennaro-tedesco** [comment]
What option in particular is to be selected? I cannot seem to find the way.

**Comment by evgeniyp** [comment]
```
    "gitlens.menus": {
        "editorGroup": {
            "blame": false,
            "compare": false
        },
```

**Comment by gennaro-tedesco** [comment]
> ```
>     "gitlens.menus": {
>         "editorGroup": {
>             "blame": false,
>             "compare": false
>         },
> ```

awesome, thank you.

**Comment by rodrigograca31** [comment]
Adding this doesnt seem to work..... :sob:

**Comment by rodrigograca31** [comment]
Any alternatives?

**Comment by Rkokie** [comment]
@rodrigograca31 

Have you tried restarting vscode? It worked partially for me, I'm still stuck with the "Open changes" button. Why is it so hard to define which options we can setup somewhere?

**Comment by rodrigograca31** [comment]
@Rkokie Restarting did the trick! Thanks!

Also the JSON object above has a missing closing curly bracket...
And seems this is all you neeed:

```JSON
"gitlens.menus":  false,
```
And yes it seems that "Open Changes" button can't be removed:
https://github.com/eamodio/vscode-gitlens/blob/0b80f3ba7b38083a3727c7751ce6247474db6f13/package.json#L814-L833

**Comment by eamodio** [comment]
@rodrigograca31 @Rkokie The "Open Changes" button is from VS Code itself, not GitLens.

**Comment by eamodio** [comment]
As mentioned above: https://github.com/eamodio/vscode-gitlens/issues/540#issuecomment-435561266

You can use the GitLens settings UI to easy toggle all of these settings:
![image](https://user-images.githubusercontent.com/641685/76505581-1c9cf180-6420-11ea-899d-a79edb49766e.png)

**Comment by Rkokie** [comment]
@eamodio I couldn't find that at first, but now I see it's accessed via Gitlens nav, sorry for the inconvenience!

**Comment by scscgit** [comment]
This is almost impossible to figure out by reading the tips inside this issue. Is there no plan to make the settings (gitlens.menus) more user-friendly, so that they make sense to the user even if they try to search for it by proper keywords? (And I didn't find any "GitLens settings UI".)
