### ISSUE TITLE
Enable configuration of Recent Changes and Gutter Heatmap to be enabled by Reviewing mode

### ISSUE THREAD

**Issue by NeilCross** [eamodio/vscode-gitlens#542]
It doesn't seem that there's a way to enable the recent changes or gutter heatmap features automatically under reviewing mode.  Can we please have a way to toggle them on and off from there?

**Comment by NeilCross** [comment]
Perhaps i'm misunderstanding the reviewing/zen modes here, but I believe the purpose of that feature is to enable/disable features as a mode is activated.  If this correct?
If that's the case, I'd like to be able to enable gutter heatmap when i enter reviewing mode, and disable it in zen mode.

**Comment by speed-oss** [comment]
@NeilCross if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
