### ISSUE TITLE
Add a "Show GitLens Results Explorer" icon to the sidebar

### ISSUE THREAD

**Issue by mikelgmh** [eamodio/vscode-gitlens#543]
I thought it would be a good idea to implement a button in the sidebar so we can open the GitLens Results Explorer in a fast way without having to move it to the explorer view.

If this cannot be implemented, is there any way to open it by a shortcut?

**Comment by eamodio** [comment]
@Jariway Could you try out the [GitLens 9 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v9.0.0-beta) release, the GitLens _Results_ explorer has been split into 2 persistent views, `Search Commits` and `Compare`, let me know if this resolves the issue for you.

**Comment by eamodio** [comment]
GitLens v9 has been released which should address this. Please re-open if not.
