### ISSUE TITLE
Some commit messages have one letter missing

### ISSUE THREAD

**Issue by ljporljp** [eamodio/vscode-gitlens#544]
- GitLens Version:8.5.6

- VSCode Version:1.28.2
- OS Version:win7 6.1

Steps to Reproduce:

1.Checkout the repo: https://github.com/processhacker/processhacker
2.Open vscode with gitlens already installed.
3.Check the earliest log message, you'll see the last letter was missing(not all).e.g.0ba4e1bd7617de8da7ef818bc72ef7f640292a08

**Comment by speed-oss** [comment]
@ljporljp if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
