### ISSUE TITLE
Git commands run in a Python virtualenv fail because of activation

### ISSUE THREAD

**Issue by mattpepin** [eamodio/vscode-gitlens#545]
- GitLens Version: 8.5.6

- VSCode Version: Code OSS 1.27.2
- OS Version: Arch Linux fully up to date

Steps to Reproduce:

1. Create a python virtualenv under source control
2. Create a branch "test"
3. Change something and create a commit
4. Return to master branch and try to merge like this: Open GitLens Explorer, Develop Branches, Right click on the test branch and click on "Merge Branch (Terminal)"

It will fail with an output similar to this:
`cd "/home/matt/venv/src"
[matt@linux]$ git merge test /home/matt/venv/bin/activate
merge: test - not something we can merge`

Once the terminal is open, you can retry the command and it will success because the virtualenv is already activated. It happens for any command run in the terminal (not just merge).

**Comment by eamodio** [comment]
I don't know anything about a python virtualenv, nor if this is still an issue, or if @Flamefork's workaround fixes everything. Given that I'm going to close this issue. Please feel free to open a new issue with more details if the community wants to address this. Thanks!
