### ISSUE TITLE
Changing gitlens.statusBar.enabled has no effect

### ISSUE THREAD

**Issue by andersennl** [eamodio/vscode-gitlens#546]
- GitLens Version: 
8.5.6
- VSCode Version:
1.28.2 (1.28.2)
- OS Version:
MacOS 10.14.1
Steps to Reproduce:
1. Set `"gitlens.mode.statusBar.enabled"` to `false` / disable it via the wizard
2. The "Blame name" in the status bar doesn't disappear.
![bildschirmfoto 2018-11-09 um 09 54 19](https://user-images.githubusercontent.com/2667916/48252597-7b55f380-e405-11e8-896c-8bc26f18b3cd.jpg)

I've changed this via the guide and in the settings itself, but the icon doesn't disappear. All the other settings work fine.

When I activate and deactivate the setting, this is being written to the logs:
```
WebviewEditor.onMessageReceived: type=saveSettings, data={"changes":{"statusBar.enabled":true},"removes":[],"scope":"user","type":"saveSettings"}
Running(/Users/andersennl/Library/Application Support/Code/User): git rev-parse --show-toplevel
FAILED(/Users/andersennl/Library/Application Support/Code/User): git rev-parse --show-toplevel FAILED in 19 ms
isTracked('/Users/andersennl/Library/Application Support/Code/User/settings.json', 'undefined')
isTracked('/Users/andersennl/Library/Application Support/Code/User/settings.json', 'undefined') = false
WebviewEditor.onMessageReceived: type=saveSettings, data={"changes":{"statusBar.enabled":false},"removes":[],"scope":"user","type":"saveSettings"}
Running(/Users/andersennl/Library/Application Support/Code/User): git rev-parse --show-toplevel
FAILED(/Users/andersennl/Library/Application Support/Code/User): git rev-parse --show-toplevel FAILED in 40 ms
isTracked('/Users/andersennl/Library/Application Support/Code/User/settings.json', 'undefined')
isTracked('/Users/andersennl/Library/Application Support/Code/User/settings.json', 'undefined') = false
```

**Comment by eamodio** [comment]
That setting `gitlens.mode.statusBar.enabled` is for the `mode` status bar entry (when you are in a GitLens mode -- zen, review, etc). The setting to control the blame status bar entry is `gitlens.statusBar.enabled`.

You can also use the GitLens interactive settings editor from the command palette run `GitLens: Open Settings` to easily toggle this and most other GitLens settings.

**Comment by andersennl** [comment]
I'm sorry about the "typo" in the post, it's correct in the title. I've set `gitlens.statusBar.enabled` to false, which doesn't hide the git blame indicator in the status bar.
