### ISSUE TITLE
Natural Sorter

### ISSUE THREAD

**Issue by Domvel** [eamodio/vscode-gitlens#547]
A natural sorter would be great. 

```text
// Expected
1.1.0
1.2.0
1.6.0
1.12.0
1.23.0

// Actual
1.1.0
1.12.0
1.2.0
1.23.0
1.6.0
```

![screen](https://user-images.githubusercontent.com/35452565/48574729-3b64a400-e910-11e8-8a22-578728cf07d1.png)

**Comment by eamodio** [comment]
Tags are just strings -- while your strings look like versions, that is just a convention you chose. So I'm not sure how GitLens could sort the list of unknown string any differently.

**Comment by Domvel** [comment]
The windows explorer also sort by natural. File names are also just strings. ... Just a suggestion. :) No problem, if rejected. Because a natrual sorter is a bit more complex as normal sort or no sort. It needs more resources and may produce some bugs at "wrong" implementation. (experience 😄 )
![win](https://user-images.githubusercontent.com/35452565/48612009-0136e900-e988-11e8-8f46-7df978f585f6.png)

**Comment by eamodio** [comment]
@Domvel Sorry, I should have looked more into "natural" sorting before responding -- learned something new! Thanks for the suggestion and it will be coming in the next release!

**Comment by speed-oss** [comment]
@Domvel if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
