### ISSUE TITLE
Switch off inline blame

### ISSUE THREAD

**Issue by michaelaye** [eamodio/vscode-gitlens#549]
The settings do not seem to offer any simple toggle to enable/disable inline blame. I am NOT talking about currentLine but ANY in-editor blame display, e.g. "You, 5 months ago"
I find these extra lines inside my code quite confusing.

**Comment by eamodio** [comment]
Check out the `Code Lens` section of the GitLens interactive settings editor (from the command palette run `GitLens: Open Settings`). From there you can turn on/off those items (vscode calls them Code Lens) as well as most of the other GitLens UI features.

There is also a command `GitLens: Toggle Git Code Lens` to quickly toggle them back on and off -- though it will only affect the current window and will revert to the configured settings on a reload.

Hope that helps.

**Comment by michaelaye** [comment]
i only see toggles for the whole GitLens functionality, not for inline only?

**Comment by eamodio** [comment]
Can you send a screenshot of what you are asking about?

Here are the code lens settings -- the image in the settings will dynamically update as you toggle the settings
![image](https://user-images.githubusercontent.com/641685/48651545-55ae8880-e9c9-11e8-95f3-7b882adee9d1.png)

Here are the current line settings:
![image](https://user-images.githubusercontent.com/641685/48651576-84c4fa00-e9c9-11e8-8480-f1fcdf0b0e98.png)

**Comment by michaelaye** [comment]
Thanks! Wasn't aware of the gitLens own settings dialog, very convenient! And that the name I was looking for was codeLens!
