### ISSUE TITLE
GitLens Requires an unmaintained version of git for OSX

### ISSUE THREAD

**Issue by d3viant0ne** [eamodio/vscode-gitlens#55]
More of a note from one project maintainer to another.

The latest version of gitlens ( which i love btw ) requires a version of Git that isn't available on OSX via the standalone installer which means OSX users will either have to install git from src or use something like homebrew. 

While I personally don't have an issue with either one of those options, a lot of people either aren't going to want to mess with their local git install or simply won't be able to because of a lack of system level knowledge or limited access in IT controlled systems.

Something to consider for the future.

**Comment by obrejla** [comment]
Exactly. Please, remove that check and support just maintained 2.10.1 version ;) Thanks!

**Comment by d3viant0ne** [comment]
From what I can see, that ship has sailed already. Only viable options are to lock to the previous version, disable the plugin, or use something like brew to install a more up to date version of git and then go update your path and deal with xcodes config.

**Comment by mikes-gh** [comment]
OSX and windows user here

I am interested to know what bits of gitlens rely on the changes between 2.10.1 and 2.11.1
A better message might be info  "xyz features of git lens require 2.11.1.  Please upgrade to >= 2.11.1 if you require these features" Dont Show Again|OK

Great extension BTW thanks.

**Comment by guidojo** [comment]
Same as for Fedora! Fedora only comes with git version 2.9.3. This version is stable and I don't see why a higher version should be required tbh. Please downgrade, since I really want to use codelens in my companies big project.

**Comment by josser** [comment]
Same for Ubuntu. 
As you can see http://packages.ubuntu.com/search?suite=all&searchon=names&keywords=git
Even on latest zesty only 2.11.0 is available for install.

**Comment by eamodio** [comment]
Sorry about this -- I didn't realize I had taken a dependency on a later version of Git until I has already released v3. I believe the only case that requires v2.11.0 of Git is my use of the `git status --porcelain=v2`, so I will be looking to put a fallback in place if there is a older version of Git. Once that is in, I will also remove the Git version warning and put it back to the prior version.

I'm terribly sorry about the inconvenience.

**Comment by eamodio** [comment]
I've added a fallback in v3.0.3 to not required git >= 2.11.0, so the requirement should be back to >= 2.2.0 -- again really sorry for this :(

**Comment by d3viant0ne** [comment]
It's all good... `Stuff happens`. Thanks for the quick turn around :)

**Comment by mikes-gh** [comment]
Thanks for quick turnaround
