### ISSUE TITLE
Incorrect linux distribution is detected

### ISSUE THREAD

**Issue by pdkovacs** [eamodio/vscode-gitlens#550]
- GitLens Version: 8.5.6

- VSCode Version: 1.29.1
- OS Version: Fedora 29

Steps to Reproduce:
1. Exercise the _Copy Commit Message to Clipboard_ function without `xsel` installed
2. Observe that the error message gives a hint about installing the missing package which is applicable for a Linux distribution (Ubuntu) different from the one installed (Fedora 29): https://i.imgur.com/uREnUYV.png

One inexpensive (and still acceptable) way to solve the problem would be to make the error message less specific (e.g. by completely omitting the part from the message that gives the command to be used for adding the missing package).

**Comment by eamodio** [comment]
The message has been tweaked in GitLens 9 (coming very soon). Also once vscode's [clipboard api](https://code.visualstudio.com/updates/v1_29#_clipboard-api) lands I will be able to remove the custom solution and avoid this issue completely.
