### ISSUE TITLE
What string should be entered when we wanna open file in remote custom git host?

### ISSUE THREAD

**Issue by ctxhou** [eamodio/vscode-gitlens#551]
Hey!
First thanks for the great package.

I have a question about opening the custom git host website.
I follow the [Custom Remotes Settings](https://github.com/eamodio/vscode-gitlens#custom-remotes-settings) and add a custom remote in the workspace `settings.json`.
When I select a file and want to `Open file to remote`, it shows this dialog:
<img width="737" alt="screen shot 2018-11-19 at 11 49 12" src="https://user-images.githubusercontent.com/3364028/48702803-27f85800-ebf2-11e8-893e-ed5e929fb1b2.png">

Does anyone teach me what should I input? I tried any string I can think of but it didn't work.

Thanks!

**Comment by eamodio** [comment]
@ctxhou Are you still experiencing this issue? If so, can you try with the [GitLens 9 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v9.0.0-beta) release to see if you still have the issue?

**Comment by eamodio** [comment]
@ctxhou GitLens v9 is out hopefully this will resolve any issues. If not please re-open this issue.
