### ISSUE TITLE
"Open Line Changes with..." doesn't work for renamed files

### ISSUE THREAD

**Issue by philraj** [eamodio/vscode-gitlens#552]
Issue Type: <b>Bug</b>

After renaming a file, when you try to e.g. `Compare Commit with Previous` it shows an empty file on the right pane, and the titlebar shows that GitLens thinks the file has been deleted from the perspective of the current commit.
![image](https://user-images.githubusercontent.com/16470658/48737171-59394e00-ec1b-11e8-9cbc-c044bd8dc712.png)
This is despite the fact that the inline git blame is correctly following the rename.

**Steps to reproduce:**
1. Create a blank git repo locally
2. Create a file, add some contents, commit the change
4. Edit the file, commit the change
5. Rename the file, commit the change
6. Try to `Compare Commit with Previous` and notice that the right pane shows an empty file

Extension version: 8.5.6
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 17.7.0

**Comment by eamodio** [comment]
@philraj Can you try again with the [GitLens 9 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v9.0.0-beta) release to see if you still have the issue? It seems to be working for me.

**Comment by philraj** [comment]
Yep, still happening in 9 beta. Here's what happens when I run the two comparison commands (new wording seems less intuitive than "Compare Commit with..." but maybe that's just me):

<br/>

**Open Line Changes with Previous Revision:**

![image](https://user-images.githubusercontent.com/16470658/49059778-8025f000-f1d8-11e8-9e5c-4bdd54d8b44d.png)

<br/>

**Open Line Changes with Working File:**

![image](https://user-images.githubusercontent.com/16470658/49059795-8f0ca280-f1d8-11e8-9eb1-7c5e1048732e.png)

You don't have that issue when you follow those steps?

**Comment by eamodio** [comment]
@philraj what exactly are the steps you are following?

Hrm, I've constantly struggled with the naming of that command. I want to make it clear that it is _line_ specific, rather than file specific -- e.g. just walking back to the previous commit of the file. And rather than calling it _Compare Line Commit with..._, I've aligned with vscode's terminology for diff comparisons -- as they use _Open Changes_

**Comment by philraj** [comment]
Oh, you want to emphasize that the commit you're comparing with is the one from that specific line. I think "Compare Commit with..." was the most ergonomic one so far (I think I saw a few of the previous ones) but you're right, it's tricky to find the right wording that's clear but not too verbose. ("Open Changes Between This Line's Commit And The Revision Before It" doesn't really roll off the tongue)

The steps I'm following are the same I listed in the original bug report, but just to make sure you can follow exactly in my footsteps:
1. Create a new directory and enter it
2. `git init`
3. `touch abc.js`
4. Open it in vscode, add some text, save
5. Commit changes
6. Edit the text
7. Commit changes
8. Rename the file to `cba.js` from vscode
9. Commit changes
10. Now try a comparison of the line you changed as shown above

Your git log should show 3 commits: 2 which change the file contents, and one which is a rename.

**Comment by philraj** [comment]
Thank you!

**Comment by speed-oss** [comment]
@philraj if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
