### ISSUE TITLE
Change tmp directory

### ISSUE THREAD

**Issue by Yanpas** [eamodio/vscode-gitlens#555]
- GitLens Version: 8.5.6

- VSCode Version: 1.29.1
- OS Version: linux

Currently diffs and other actions with history directly create files in /tmp directory.
A better solution would be creating in /tmp/vscode-gitlens
The best one is /tmp/vscode-gitlens/$USER with mod `0750` for the $USER folder

**Comment by eamodio** [comment]
GitLens 9 (coming very soon) avoids using a temp folder completely.
