### ISSUE TITLE
Cause Vetur server crash.

### ISSUE THREAD

**Issue by OhYee** [eamodio/vscode-gitlens#557]
- GitLens Version: v9.0.0-beta

- VSCode Version: 1.29.1
- OS Version: Windows 10

Steps to Reproduce:

1. Install Vetur extension.
2. Commit a `.vue` file(May be need typescript)
3. Click **Open Changes with Previous Revision**
4. Then the Vetur will try to format the previous file, but can not find the file so crashed.
```
Could not find file: '\<xxx@d2fe7bb>\src\components\xxx.vue'
```

**Comment by OhYee** [comment]
I have open a issue on vetur.
https://github.com/vuejs/vetur/issues/987

**Comment by eamodio** [comment]
This will be resolved on the vetur side.
