### ISSUE TITLE
HTML not escaped in GitLens Explorer sidebar

### ISSUE THREAD

**Issue by JohnKahn** [eamodio/vscode-gitlens#559]
Issue Type: <b>Bug</b>

When a commit message has any html (such as \<br />) it won't escape the characters and will instead insert the html into the DOM for vscode. I verified this by looking at the developer tools for vscode.

Steps:
1. Create a commit with html such as "Commit with \<br /> html break"
2. Open GitLens Explorer in sidebar
3. Drop down "History" tree to see that the commit only shows "Commit with " (because the rest is on a new line)

Extension version: 8.5.6
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
Opened https://github.com/Microsoft/vscode/issues/63968
