### ISSUE TITLE
Show tags (like branches) in Explorer commit history

### ISSUE THREAD

**Issue by zedaav** [eamodio/vscode-gitlens#560]
Hi,

Disclaimer :wink: 
Please accept my apologies if the feature is already there or has already been requested, I wasn't able to find something related.

In the *Explorer* view, when browsing the commits history under a given branch, we already have mentions of other branches.

e.g.
```
Explorer
  + Branches
    + master - origin/master
      - (origin/master)> commit 1
      - commit 2
      - (anotherbranch)> commit 3
```

It would be really nice to have tags displayed the same way.
Something like:

```
Explorer
  + Branches
    + master - origin/master
      - (origin/master)> commit 1
      - commit 2
      - (anotherbranch) (v1.1)> commit 3
      - commit 4
      - (v1.0)> commit 5
```

**Comment by speed-oss** [comment]
@zedaav if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
