### ISSUE TITLE
Allow customization of terminal commands

### ISSUE THREAD

**Issue by wpatter6** [eamodio/vscode-gitlens#561]
Hi,

Love the tool, thanks for all your hard work!

I have a small issue that over time is becoming more annoying.  Because of the pull request mechanism we use, the branches we create locally are never merged back into master, that always happens remotely.

This means that when we go to delete local branches using gitlens, we always have to rewrite the command that it puts into the terminal from "-d" to "-D" or add "--force" in order to suppress the warning that the branch has not been fully merged.

Is there any way to change this behavior to use the uppercase D when using git lens to delete a branch?  This is becoming an annoying repetitive task on our team.

Thanks!

**Comment by fseba** [comment]
Hi. Is there any chance that I take part of this issue? I was trying to do a merge enabling --no-ff but i couldn't. 
Can I clone the develop branch, make the changes and create a pull request?

**Comment by eamodio** [comment]
I believe these issues are now fixed in GitLens 11 -- since you can specify many of these flags in the quick pick menus for each of these commands.
