### ISSUE TITLE
Setting the color of blame at top of file.

### ISSUE THREAD

**Issue by roydukkey** [eamodio/vscode-gitlens#562]
> **[3.4.5] - 2017-04-13**
> Adds `gitlens.blame.annotation.activeLineDarkColor` & `gitlens.blame.annotation.activeLineLightColor` settings to control the colors of the active line blame annotation

As per the changelog, I expect these two properties would allow me to change the blame that displays at the top of files. However, I have tried finding these is settings and even attempted setting them from a theme, but haven't be able to get the color of the text to change. I have tried searching the repo for references to `activeLineDarkColor`, `activeLineLightColor`, and `activeLineColor`, but haven't found them.

Here is a screenshot of what I have been able to accomplished with my theme by setting `gitlens.trailingLineForegroundColor`. I haven't been able to change the gray text at the top of the file.

<img width="400" alt="screen shot 2018-11-30 at 3 38 08 pm" src="https://user-images.githubusercontent.com/1509616/49314161-873e4e00-f4b7-11e8-8ead-9fe919ca0b63.png">

**Comment by eamodio** [comment]
Those colors only affect the blame that appears on the active line (the line where your cursor is). There isn't a way to directly control the color of the code lens (the `You, 6 minutes ago | 2 authors (roydukkey and others)`).

You can change the colors for all code lens (not just the ones GitLens provides) by overriding the theme color for `editorCodeLens.foreground`

Hope that helps.

**Comment by roydukkey** [comment]
Thanks. That is the correct solution.
