### ISSUE TITLE
Horizontal scroll on delete row

### ISSUE THREAD

**Issue by bm-stschneider** [eamodio/vscode-gitlens#564]
Issue Type: <b>Bug</b>

When the GitLens view is open in the sidebar, and I delete a line the editor scrolls horizontally.

Extension version: 9.0.1
VS Code version: Code - Insiders 1.30.0-insider (9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096, 2018-12-03T06:12:08.874Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_7317242|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
@bm-stschneider I was able to reproduce this once, but can't seem to any more. I don't think it is related to having the GitLens side bar open. My guess is it is the current line blame annotation messing up (vscode's decorators seem to do that sometimes).

If you try setting `"gitlens.currentLine.scrollable": false,` the current line blame won't affect the horizontal scrolling and my guess would avoid this issue.

**Comment by bm-stschneider** [comment]
Seems to work better that way.

**Comment by eamodio** [comment]
@bm-stschneider with that setting back on -- can you send me a video of the issue? Ideally happening a few times in a row?

**Comment by bm-stschneider** [comment]
I can repeat this over and over, I had to resize the editor a bit to make it work so it might be dependant on the width of the active editor.

![kapture 2018-12-03 at 15 33 35](https://user-images.githubusercontent.com/30625381/49380112-201bd600-f711-11e8-8e94-858c3f6a4e3f.gif)

**Comment by eamodio** [comment]
Unfortunately other than using that setting, I don't think there is anything I can do here. Looks like a vscode issue.
