### ISSUE TITLE
History error with UNC

### ISSUE THREAD

**Issue by ili101** [eamodio/vscode-gitlens#566]
Issue Type: <b>Bug</b>
Similar to https://github.com/eamodio/vscode-gitlens/issues/208
Looks like the bug was reintroduced in 9.0.0 or 9.0.1
The history is shown but errors are being produced while you browse:
`fatal: Invalid path '//ServerIpOrName//ServerIpOrName': No such file or directory`
```
cannot open file://ServerIpOrName//ServerIpOrName/c%24/File.ps1. Detail: A system error occurred (UNKNOWN: unknown error, stat '\\ServerIpOrName\ServerIpOrName\c$\File.ps1')
```

Extension version: 9.0.1
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by speed-oss** [comment]
@ili101  if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
