### ISSUE TITLE
Too many annotations in YAML

### ISSUE THREAD

**Issue by ronag** [eamodio/vscode-gitlens#567]
This is a bit too much annotations in my docker-compose file...

![screenshot 2018-12-04 at 10 31 48](https://user-images.githubusercontent.com/3065230/49432418-eea61780-f7af-11e8-832c-b4e4d72c78f2.png)

- GitLens Version: 9.0
- VSCode Version: 1.29.1
- OS Version: Mojave

**Comment by eamodio** [comment]
That is far less than ideal 😉. I'll look into it and get it fixed up.

**Comment by speed-oss** [comment]
@ronag if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
