### ISSUE TITLE
Open All Changes (with difftool) missing from context menu

### ISSUE THREAD

**Issue by kaiseiken** [eamodio/vscode-gitlens#569]
"Open All Changes (with difftool)" action previously executed a directory comparison with external difftool (in my case, Meld). Feature was removed/broken following an update to v9.0.1, possibly while fixing bug #503 Open Changes (with difftool), which is similar but executed an individual file comparison for all changes.

- GitLens Version: 9.0.1
- VSCode Version: 1.2.9.1
- OS Version: Ubuntu 18.04.1 LTS / Windows 10 Pro 1703/15063.1446

Steps to Reproduce:
1. In Source Control:Git panel, right click Changes heading to access context menu.
2. Observe "Open All Changes (with difftool)" is missing from context menu.
3. Assign a keybinding to "Open All Changes (with difftool)" command.
2. Observe that when command is executed via keyboard shortcut, the "Open Changes (with difftool)" action is incorrectly executed instead.

Possible solutions:
Either remove the "Open All Changes (with difftool)" keybinding shortcut from the list (fully deprecating the feature), or add "Open All Changes (with difftool)" action back to context menu and execute a 
"directory comparison" with external difftool rather than a file comparison (as previously implemented).

**Comment by speed-oss** [comment]
@kaiseiken if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
