### ISSUE TITLE
Warn on directory compare when there is no diff tool configured

### ISSUE THREAD

**Issue by aminpaks** [eamodio/vscode-gitlens#57]
I never could get this to work!
I follow these steps:
- `>GitLens: Directory Compare`
- Pick one remote branch
- Enter

Nothing happens!

Any help?

**Comment by eamodio** [comment]
@aminpaks you'll need to have git configured with a difftool. Do you have that setup?

**Comment by aminpaks** [comment]
No I thought it's part of vscode!
How to do that?

**Comment by eamodio** [comment]
Vscode can't (as far as I know) do directory compares. Would need another difftool like Beyond Compare. 
I will look into either hiding or providing some feedback on those options if it isn't setup

**Comment by aminpaks** [comment]
But if vscode team can provide this ability that would be so good!

Thanks in advance.

**Comment by eamodio** [comment]
@aminpaks FYI https://github.com/Microsoft/vscode/issues/6898

**Comment by Dominik-K** [comment]
Hi @eamodio,

an error message window pops up with *no* text shown, if the `diff.tool` is not set (via `git config --global --unset diff.tool`). Using the current version 1.11.0 (1.11.0).

I just started using your fantastic tool. It's very nice. Thanks for that.

**Comment by eamodio** [comment]
@Dominik-K thanks for the report -- this is fixed in v3.2.1

**Comment by pluma** [comment]
Would it be possible to change this so `diff.guitool` is used instead (and that `git diff` is executed using the `--gui` flag)? I would like to use a GUI tool when running a diff from within VSCode but keep using the default when diffing in the shell.

**Comment by eamodio** [comment]
@pluma Sounds like a good change -- would you mind opening a new issue to track this?
