### ISSUE TITLE
Hide repository separator

### ISSUE THREAD

**Issue by tiansin** [eamodio/vscode-gitlens#571]
![qq20181205-142813](https://user-images.githubusercontent.com/4232281/49494279-0f4a9c00-f89a-11e8-908d-7fdd0e9f7dbf.png)

After upgrading to the latest version, use scm management to find out something like a separator.

**Comment by eamodio** [comment]
That's by design -- just a visual separator of the current branch and context from the rest.

**Comment by tiansin** [comment]
Looks weird.....

**Comment by tiansin** [comment]
@eamodio Is it possible to add a configuration to control its display and hiding, which in my opinion affects my visual enjoyment.

**Comment by speed-oss** [comment]
@tiansin if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
