### ISSUE TITLE
Explorer cant expand some branch folders

### ISSUE THREAD

**Issue by eps1lon** [eamodio/vscode-gitlens#572]
- GitLens Version: 9.0.2
- VSCode Version: 1.29.1 and 1.30-insider
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:
1. 
```sh
$ git clone https://github.com/eps1lon/material-ui.git
$ cd material-ui
$ for i in `git branch -a | grep remote | grep -v HEAD | grep -v master`; do git branch --track ${i#remotes/origin/} $i; done
$ code .
```
2. activity bar > gitlens > explorer
3. expand `feat` or `fix` > Error:
![vscode-gitlens-branch-issue](https://user-images.githubusercontent.com/12292047/49504709-8e2fdc80-f87a-11e8-9f43-726d6fe4c7e0.png)

Attempt at minimal repro but everything worked here.
1.
```sh
mkdir empty-repo && cd empty-repo
echo 'Hello, World!' > readme
git init
git add -A && git commit --m 'Initial commit'
git branch flat/branch1
git branch flat/branch2
git branch some/deep/branch1
git branch some/deep/branch2
```
2. activity bar > gitlens > explorer
3. expand flat > shows branch1 and branch2
3. expan `some` > shows deep

**Comment by speed-oss** [comment]
@eps1lon  if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
