### ISSUE TITLE
Apply Changes not working because of whitespace conflicts

### ISSUE THREAD

**Issue by tiansin** [eamodio/vscode-gitlens#574]
- GitLens Version: 9.02
  
- VSCode Version: 1.2.9
- OS Version: mac 10.13.6

Steps to Reproduce:

This feature is not available for both the repository and submodules

**Comment by eamodio** [comment]
Can you provide more details and steps for what you are seeing?

**Comment by tiansin** [comment]
<img width="445" alt="qq20181212-170031 2x" src="https://user-images.githubusercontent.com/4232281/49858289-7e426a80-fe2f-11e8-9ac0-cc1bc25a5f7c.png">

Always prompt this, choose Yes.

**Comment by eamodio** [comment]
So when you say Yes it doesn't apply the changes to the working tree?

**Comment by tiansin** [comment]
<img width="454" alt="qq20181212-171411 2x" src="https://user-images.githubusercontent.com/4232281/49858997-61a73200-fe31-11e8-8f59-32268aa03168.png">
`
[2018-12-12 09:13:18:971] git — -c, core.quotepath=false, -c, color.ui=false, apply,   cwd='/Users/xxxx/xxxx/xxxx/xxx/src/app/Services'

  
Error: <stdin>:33: trailing whitespace.
     * @param url 
error: patch failed: Public/plat.class.ts:5
error: Public/plat.class.ts: patch does not apply

[2018-12-12 09:13:20:734] git — -c, core.quotepath=false, -c, color.ui=false, apply, -3,   cwd='/Users/xxxx/xxxx/xxxx/xxx/src/app/Services'

  
Error: <stdin>:33: trailing whitespace.
     * @param url 
error: patch failed: Public/plat.class.ts:5
Falling back to three-way merge...
error: patch failed: Public/plat.class.ts:5
error: Public/plat.class.ts: patch does not apply

[2018-12-12 09:13:20:734] Object
Error: <stdin>:33: trailing whitespace.
     * @param url 
error: patch failed: Public/plat.class.ts:5
Falling back to three-way merge...
error: patch failed: Public/plat.class.ts:5
error: Public/plat.class.ts: patch does not apply

`

**Comment by eamodio** [comment]
On the command line what happens if you run:
`git apply --whitespace=warn -3`

**Comment by speed-oss** [comment]
@tiansin if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)

**Comment by tiansin** [comment]
@eamodio  This error appears again here.
