### ISSUE TITLE
Move vscode API extension helpers/base classes to a separate package

### ISSUE THREAD

**Issue by joelday** [eamodio/vscode-gitlens#575]
Would find these very useful for unrelated extensions, especially the infrastructure for managing/registering commands and views, etc.

**Comment by eamodio** [comment]
@joelday can you go into more detail in what you'd like to see?

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
