### ISSUE TITLE
Search by shorten commit ID

### ISSUE THREAD

**Issue by MaximeWeyl** [eamodio/vscode-gitlens#578]
Hello ! Thank you for this addon ! 

It would be great if it was possible to search by shorten (beginning of) commit ID, like I'm used to do with CLI or Git Gui. 

For now it does not work : 
![git_lens](https://user-images.githubusercontent.com/31591159/49576178-c6035680-f944-11e8-9b9f-b56e2aaeceb3.gif)

**Comment by MaximeWeyl** [comment]
I just found out that beginning the search by **#**shortenCommitId does this !

If you think this should work even if **#** is not there, this ticket could remain opened.

**Comment by eamodio** [comment]
This is by-design. There are different prefixes for different types of searching, see the [docs](https://github.com/eamodio/vscode-gitlens/tree/master/#search-commits-view-)

**Comment by MaximeWeyl** [comment]
OK, sorry for the useless issue :)

**Comment by eamodio** [comment]
@MaximeWeyl no worries at all!
