### ISSUE TITLE
GitLens: Toggle Line Blame Annotations

### ISSUE THREAD

**Issue by idoo** [eamodio/vscode-gitlens#582]
- GitLens Version: 9.0.3
  
- VSCode Version: 1.29.1

VSC  doesn't respect `GitLens: Toggle Line Blame Annotations` option
added to settings.json
`"gitlens.currentLine.enabled": false,`

I'm able to toggle it, but after a restart, it came back.

Looks like it happens, because `review mode` is enabled, but it's messy to disable it by option and have it because of some mode?

**Comment by eamodio** [comment]
This is by design. Review mode has the current line blame enabled by default -- the reasoning is that if you are reviewing you "probably" want it on. But it is configurable, by overriding the value when in review mode.

For example:
```
    "gitlens.modes": {
        "review": {
          "name": "Review",
          "currentLine": false
        }
```

**Comment by idoo** [comment]
I guess we should add that to readme, right?

**Comment by eamodio** [comment]
I'm open to suggestions and PRs are very welcomed 😄
