### ISSUE TITLE
Unexpected results when opening diff from file history

### ISSUE THREAD

**Issue by turijs** [eamodio/vscode-gitlens#584]
- GitLens Version: 9.0.3
  
- VSCode Version: 1.29.1
- OS Version: Mac OS 10.13.6

When clicking on a commit in the File History pane to open  a diff:

**Expected:**
A diff showing the changes introduced in that commit

**Actual:**
A diff of the clicked commit with the following commit in the File History (if I'm not mistaken). When history is non-linear, this can cause "extra" changes to show in the diff, which is confusing.

**Comment by turijs** [comment]
I created a minimal repo to demsontrate this as well: https://github.com/turijs/gitlens-issue-584

To reproduce:
1. Open the above repo in vscode with gitlens
2. Open the only file in the repo and go to the GitLens File History pane
3. Click on commit 3, and note that the diff shows changes to "Line 1" and "Line 3", when only "Line 3" was actually changed in that commit.

Is this expected behavior?
Thanks for all the hard work on this extension!

**Comment by speed-oss** [comment]
@turijs if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
