### ISSUE TITLE
Restore deleted line?

### ISSUE THREAD

**Issue by GandalfSaxe** [eamodio/vscode-gitlens#585]
If I accidentally delete a line, is there a way to restore it with GitLens?

Here is an example:

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/12127864/49726832-2ceb7d00-fc6f-11e8-851c-8dcd5e42cd54.png">

I would like to restore line 145, which has been deleted as an uncommitted change. However, I can't select the deleted line with the mouse, I can only select the actual lines in the file that are currently present.

Surely I shouldn't have to revert to select and copy / restore the deleted line right? Is there any solution to this? Otherwise consider this a feature request 🙂

**Comment by eamodio** [comment]
You can just using the built in git extension -- if you aren't in diff view, you will see a little red arrow at the point where you deleted the line. If you hover over it, it will expand to a red rectangle that you can click on and it will open a peek view with the change which you can undo.

Hope that helps.

**Comment by GandalfSaxe** [comment]
Actually it doesn't help me because it's an all-or-nothing feature: I can only discard ALL changes in the block. If I'm only interested in restoring a single line, it's not possible in this pop-up view you speak of to select text here either. Thus I'm forced to go to the web interface of GitHub.com to find the line I'm looking to restore.

**Comment by eamodio** [comment]
If you open the diff view (click the Open Changes button in the editor toolbar) then you should be able to see the contents of the deleted line on the left and copy it to the right.

**Comment by GandalfSaxe** [comment]
The Open Changes view doesn't allow me to select any of the deleted lines either:

![](https://i.imgur.com/DGhptNG.gif)

**Comment by nikopavlica** [comment]
I have the same question. If one could at least copy text of deleted lines, it would be really helpful, but at the moment, its just as @GandalfSaxe said... you can restore the whole chunk or nothing.

Is there any chance to rethink this feature request or add the ability for selecting deleted lines?

**Comment by pmilic021** [comment]
As others have pointed out, it would be of immense help it could be possible to select and copy some content of _red blocks_.

**Comment by eamodio** [comment]
@pmilic021 Unfortunately that isn't something GitLens can fix -- that is an issue with vscode itself. I would recommend opening an issue with the vscode repo -- if there isn't one already (in which case upvote it).

**Comment by pmilic021** [comment]
Alright, never would have guessed

**Comment by meetai** [comment]
Use side-by-side View to copy content.

**Comment by penx** [comment]
> If you open the diff view (click the Open Changes button in the editor toolbar) then you should be able to see the contents of the deleted line on the left and copy it to the right.

@eamodio can Git Lens provide a way to do this without having to copy + paste? Useful if you're doing this for multiple (but not all) lines throughout a file. e.g. select the deleted lines in left view, right click and select 'discard lines'/'discard changes'?

**Comment by penx** [comment]
I've also opened a feature request for vscode that should help with this https://github.com/microsoft/vscode/issues/94365

**Comment by amaisano** [comment]
![image](https://user-images.githubusercontent.com/688435/88883009-2e313b00-d201-11ea-8250-9ff980a7dec5.png)
