### ISSUE TITLE
How to connect GetLens to remote GitHub repository?

### ISSUE THREAD

**Issue by mtp1032** [eamodio/vscode-gitlens#586]
I have just installed VStudio Code V1.29.1 and now want to clone my repo on GitHub to my local system using the editor (Heretofore I've been using GetHub Desktop). There is a youtube video that demonstrates how to accomplish this very clearly using an earlier version of VStudio Code. Sadly, my newer version of VStudio Code doesn't offer the same menu options.  

To date, I have been unable to set the url of my GitHub repo such that GitLens can access it from within VStudio. I've tried setting the path in the "Git:Scan Repositories" settings in settings.json, but that didn't work (i.e., when I clicked on [View]->[SCM] the message displayed was "No source control providers registered." 

I'm pretty sure I'm missing something simple, but the documention seems silent on how to establish the initial connection to a GitHub repo. Any help (or pointers to docs) would be greatly appreciated.

Cheers,

**Comment by mtp1032** [comment]
Well, a friend of mine showed me the way. For others who are reading this, all one has to do is to press <F1>, type in "git clone" followed by the url of you repo.

**Comment by eamodio** [comment]
This is really a question for vscode and not GitLens as the built-in SCM (git) extension handles that view (and cloning).
