### ISSUE TITLE
No search provider registered for scheme: gitlens

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [eamodio/vscode-gitlens#587]
- GitLens Version:
  
- VSCode Version: 1.29.1 (1.29.1)
- OS Version: macOS 10.14.1 (18B75)

Steps to Reproduce:

I'm not sure what did I move, but when I try to make a search on the search module below the file exprorer or when I try to open a file with Cmd+P this message appears:

![screen shot 2018-12-10 at 17 26 26](https://user-images.githubusercontent.com/5341310/49768107-bf584480-fca0-11e8-970b-6943e44c4cfd.png)

I did enable the `"gitlens.outputLevel": "debug"` but I didn't get info there. I also looked on the logs but I didn't find a thing there.

**Comment by forsureitsme** [comment]
Related: https://github.com/Microsoft/vscode/issues/58370

**Comment by eamodio** [comment]
@forsureitsme thanks for linking that!
