### ISSUE TITLE
Output channel doesn't exist with `gitlens.outputLevel` default

### ISSUE THREAD

**Issue by roblourens** [eamodio/vscode-gitlens#588]
- I tried to apply a stash, it failed. 
- A notification told me to find more details in the output channel. 
- I clicked "Open output channel", nothing happened

I had to read the source to find that the output channel isn't created when the "output level" setting is silent, which is the default value. It seems like "errors" would be a more useful default.

**Comment by speed-oss** [comment]
@roblourens if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
