### ISSUE TITLE
Comparing the active file with other branch - feature removed?

### ISSUE THREAD

**Issue by mrsimpson** [eamodio/vscode-gitlens#597]
A feature I recall to have used very often is the comparison of a single file I opened with one in another (potentially remote) branch.

![image](https://user-images.githubusercontent.com/17176678/50146311-c3ddb800-02b3-11e9-8a20-8b00f3380c2d.png)

Now (precisely for some releases) the command `Compare active file with remote branch` is gone.

Current GitLens Version: 9.2.1

Is this a bug, a feature, or a change on the user interaction pattern I did not get?

**Comment by eamodio** [comment]
Sorry for the confusion -- in GitLens 9, I aligned with the VS Code terminology of _Open Changes_, so the "missing" commands use that naming structure:

![image](https://user-images.githubusercontent.com/641685/50181932-dd92f580-02db-11e9-870a-834363377427.png)

**Comment by ldhios** [comment]
@eamodio I looked for it for a long time，The suggestion is to change back to the previous one。 Compart file with other branch or tags is correct。

**Comment by colonelchlorine** [comment]
Just getting here late, but this has been plaguing me for months and thought Gitlens just expected to use the more complex sidebar.

Maybe I'll get used to "Open changes" ... but really what a dev wants to do is _compare_, so that makes the most logical sense to me.

**Comment by bsivanov** [comment]
Not sure if this is possible, but probably you can leave the command with the proper "Open changes" name and just register a "compare" [alias](https://docs.microsoft.com/en-us/visualstudio/ide/reference/visual-studio-command-aliases?view=vs-2019)

**Comment by hanrok** [comment]
Can't find any option to compare current file with the same file on another branch. Do I miss anything?
I have Gitlens 10.2.2
