### ISSUE TITLE
[request] Allow disabling automatic blame, possibly by default

### ISSUE THREAD

**Issue by avih** [eamodio/vscode-gitlens#6]
While using blame is indeed very useful, much of the time it's not needed, and so showing the blame "lines" unconditionally can be distracting (how do you call these lines of [author], [NN time ago] which show up at the source code when editing?).

I'd suggest to add a config to control whether or not the blame lines should display when opening a new file, while possibly setting it to false by default.

This would probably require adding another key binding to toggle the blame lines.

**Comment by eamodio** [comment]
@avih Good idea -- I've been planning on adding a few settings to control behavior -- Like enable/disable the CodeLens, control which CodeLens shows (Recent vs Authors), which command a CodeLens executes (history vs blame), and some settings to control the blame "gutter" info (adding user name and/or date)

Thanks!

**Comment by eamodio** [comment]
@avih v0.1.1 add a lot of configuration settings -- let me know if they cover the main case for you.

**Comment by eamodio** [comment]
@avih v0.3.0 adds a new `ondemand` CodeLens setting as well as much more control. Calling this one fixed.

**Comment by avih** [comment]
Thanks, but for now I uninstalled `gitlens`. I'll wait for it to stabilize a bit before I give it a go again, so I probably won't provide more feedback for now.

For instance, with 0.3.1 it doesn't load at all with an error `Activating extension `eamodio.gitlens` failed:  Cannot find module 'lodash'`.

I do hope you can get it stable and productive since I really like what you've done so far. Good luck :)
