### ISSUE TITLE
Git lens hides Python test lens

### ISSUE THREAD

**Issue by mklemarczyk** [eamodio/vscode-gitlens#60]
I'm using your extension with https://github.com/DonJayamanne/pythonVSCode

I have an issue regarding Python Test lens, your extension removes it from my Visual Studio Code.
I'm unable to use both extensions in the same workspace.

When I disable GitLens extension Python Test lens are working properly.

**Comment by mklemarczyk** [comment]
Screenshots

![screenshot 197](https://cloud.githubusercontent.com/assets/2727261/24827920/53ce1c50-1c53-11e7-8730-cdad4a5192cd.png)
![screenshot 198](https://cloud.githubusercontent.com/assets/2727261/24827922/5af2b8ce-1c53-11e7-8471-d59d4fa0dd88.png)

**Comment by eamodio** [comment]
@mklemarczyk which version of vscode are you running? Is this with a particular file or all python files? Do you have a public repo that reproduces this issue?

**Comment by mklemarczyk** [comment]
@eamodio I running the current version of vscode

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|gitlens|eamodio|3.2.1|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|;

**Comment by eamodio** [comment]
@mklemarczyk thanks for the vscode info. Can you also provide information on the other questions above? I'm unsure how GitLens could conflict with other extensions CodeLens. If you open up the developer tools do you see any errors in the console when this happens?

**Comment by mklemarczyk** [comment]
No errors in console. I can provide you a workspace.
[repo.zip](https://github.com/eamodio/vscode-gitlens/files/914392/repo.zip)

**Comment by eamodio** [comment]
@mklemarczyk thanks -- I'll take a look

**Comment by eamodio** [comment]
This issue is the same as reported here -- https://github.com/DonJayamanne/pythonVSCode/issues/553. I've also added a comment to that effect here -- https://github.com/DonJayamanne/pythonVSCode/issues/865#issuecomment-294079568

**Comment by mklemarczyk** [comment]
👍  Thank you for solving problem

**Comment by GasparCheng** [comment]
Hi all, 
I hit this issue again after updating GitLens to 8.5.6 (8.5.4 works fine)
And VSCode debug console get warning message: 'Git extension API method getGitPath is deprecated'

My environment:
- VSCode 1.27
- GitLens 8.5.6
- Pytest 3.5.1

**Comment by Wattabak** [comment]
Same here, Python test lens buttons don't show up while using GitLens 

![ca8a7e2d579c7a2eccdadf65852228e4](https://user-images.githubusercontent.com/18378763/46604426-e3f83a80-cafe-11e8-9266-049c58795f63.png)
[![Image from Gyazo](https://i.gyazo.com/7a7a6d39cb32226f8314e412e22af93e.png)](https://gyazo.com/7a7a6d39cb32226f8314e412e22af93e)

Environment:

- Win 10
- VSCode 1.27.2
- GitLens 8.5.6
- Pytest 3.8.2

**Comment by eamodio** [comment]
@GasparCheng so with everything the same, if you uninstall GitLens 8.5.6 and install 8.5.4 everything works, and then switching to 8.5.6 breaks things?

**Comment by Wattabak** [comment]
I have been having the same issue as @GasparCheng, python test lens does not work with git lens installed, I tried switching to 8.5.4 version of git lens, didnt work either. I commented two days ago about having this problem but figured it was a problem with vscode rather than git lens and deleted it.

My environment:

- VSCode 1.28
- GitLens 8.5.6
- Pytest 3.5.1
- Python extension 2018.9.0

> @GasparCheng so with everything the same, if you uninstall GitLens 8.5.6 and install 8.5.4 everything works, and then switching to 8.5.6 breaks things?

**Comment by develbro** [comment]
Same issue with latest VS Code and GitLens 8.5.4 and 8.5.6

**Comment by develbro** [comment]
> Same issue with latest VS Code and GitLens 8.5.4 and 8.5.6

Got solution with disables Gitlens › Code Lens › Authors: Enabled and Gitlens › Code Lens › Recent Change: Enabled settings

**Comment by jd-naranjo** [comment]
I am having the same issue, with the latest updates of Visual Studio Code, Pytest and GitLens. The only way for me to get the python unittest lens to work again is to deactivate GitLens as @develbro mentioned.

Recently pytest and vs-code were fixing the python unittest lens, probably their solution didn't take into account working with GitLens.
https://github.com/Microsoft/vscode-python/issues/2347
https://github.com/Microsoft/vscode-python/issues/2663

**Comment by peteboothroyd** [comment]
I am also facing this issue with GitLens 9.2.3, python 3.6.5, pytest 4.0.2 and VSCode 1.30.1

**Comment by milsto** [comment]
There is a newer and opened issue #529 on the same problem. I can confirm that it affects me.
