### ISSUE TITLE
gitlens.historyExplorer.enabled

### ISSUE THREAD

**Issue by HarryAdney** [eamodio/vscode-gitlens#602]
- GitLens Version: 9.2.3
- VSCode Version: 1.31.0-insider
- OS Version: Windows 10 Insider

Steps to Reproduce:

1. Viewed settings.json

Tried uninstalling and reinstalling, but issue remains

**Comment by eamodio** [comment]
I'm really not sure what this issue is about -- can you provide more details? And the setting referenced in the title doesn't exist anymore.

**Comment by HarryAdney** [comment]
Sorry friend,

This issue seems to have disappeared! I've just reinstalled again and this time, the line "gitlens.historyExplorer.enabled" doesn't show in settings.json. Maybe I needed to close vscode and reopen, rather than just reload?

I don't know, either way, it seems to be ok now.
