### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by jjasoncool** [eamodio/vscode-gitlens#603]
- GitLens Version:9.2.3
- VSCode Version:1.30.1
- OS Version:Windows 10

My files is big5 encoding (Not UTF-8), when I using gitlens view history, the encoding will change to UTF-8.
I have to change it by myself, but previous version is auto guess my file encoding.
I have setting vscode setting.json
```json
"files.autoGuessEncoding": true
```

Steps to Reproduce:
- In file history have this issue
![image](https://user-images.githubusercontent.com/24731867/50415410-c4e38c00-0855-11e9-9773-fdeccc057a60.png)

- but it is normal in vscode git viewer
![image](https://user-images.githubusercontent.com/24731867/50415395-aed5cb80-0855-11e9-9e69-5c8767177c55.png)

- it's normal in version 8.5.6
![image](https://user-images.githubusercontent.com/24731867/50415448-f8beb180-0855-11e9-9dea-a4f235f75785.png)

2. I have comment at this issue but no one see it
https://github.com/eamodio/vscode-gitlens/issues/40#issuecomment-447181307

**Comment by eamodio** [comment]
@jjasoncool Can you send me an example file that shows this issue?

**Comment by jjasoncool** [comment]
Hi here is the file which is encording with big5.



Eric Amodio <notifications@github.com> 於 2019年1月8日 週二 下午3:32寫道：

**Comment by jjasoncool** [comment]
Should I provide any information?

**Comment by eamodio** [comment]
@jjasoncool sorry I haven't had a chance to look into it yet

**Comment by jjasoncool** [comment]
after version 9.8.1 this issue has been fixed
