### ISSUE TITLE
Show More Commits not working

### ISSUE THREAD

**Issue by sherlockwang** [eamodio/vscode-gitlens#605]
- GitLens Version: 9.2.3
  
- VSCode Version: 1.30.1
- OS Version: macOS 10.14.2

Steps to Reproduce:

1. Open a repository with a lot of commit
2. Click "Show More Commits"

Nothing happened, no earlier commits loaded.

![image](https://user-images.githubusercontent.com/9678225/50437540-11e26380-0925-11e9-9fdd-820ebc0f224c.png)

**Comment by speed-oss** [comment]
@[sherlockwang](/sherlockwang) if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
