### ISSUE TITLE
How do you view your favorited branches?

### ISSUE THREAD

**Issue by RudyOnRails** [eamodio/vscode-gitlens#616]
This is probably a very easy question to answer but I can't seem to find the answer.

After favoriting a branch, where do you find your favorites? I've looked all over the place which includes googling, Github issues, and searching settings for GitLens...but I cannot find all the favorites I have favorited.

Thanks for any assistance,
Kevin

**Comment by eamodio** [comment]
Favorited branches currently just show up sorted first within the _Branches_ node in the _Repositories_ view. Also if layout branches is set to tree (`"gitlens.views.repositories.branches.layout": "tree"`, the default), then favorited branches won't be grouped with others.

**Comment by RudyOnRails** [comment]
Ok that helps @eamodio.

But what's weird, and threw me off sparking this question, is that my non-favorite branch `160912344` is at the top, and then several favorites after it. If I favorite it, it stays put, and if I un-favorite it, it still stays put.

Any thoughts?

**Comment by mlasson** [comment]
I had the same problem ! See issue #626 and PR #627 for a bug fix.

**Comment by RudyOnRails** [comment]
I see that #627 was merged
