### ISSUE TITLE
Version links in CHANGELOG not functional

### ISSUE THREAD

**Issue by shadowspawn** [eamodio/vscode-gitlens#617]
The version "reference links" in the headings of the CHANGELOG entries are not functional because the separate URLs are missing. Willing to do a Pull Request if you are interested in adding the reference links to the past releases. (I noticed the issue partly because I had same issue with the `Keep a Changelog` format myself.)

# Example Raw

```markdown
## [9.4.1] - 2019-01-08

### Fixed

- Reverts #606 as it causes views to lose their expansion state

[9.4.1]: https://github.com/eamodio/vscode-gitlens/compare/v9.4.0...eamodio:v9.4.1
```

# Rendered

### Fixed

- Reverts #606 as it causes views to lose their expansion state

[9.4.1]: https://github.com/eamodio/vscode-gitlens/compare/v9.4.0...eamodio:v9.4.1

(Thanks for this useful Visual Code extension!)

**Comment by eamodio** [comment]
@JohnRGee sorry for the delay -- this is a great idea -- thank you. I would definitely welcome a PR 😄

**Comment by JohnRGee** [comment]
In progress.

**Comment by shadowspawn** [comment]
Submitted Pull Request for consideration.
