### ISSUE TITLE
When VSCode debugger is up, no more Git blame messages

### ISSUE THREAD

**Issue by felixfong227** [eamodio/vscode-gitlens#619]
- GitLens Version: 9.4.1
  
- VSCode Version: 1.30.2
- OS Version: MacOS 10.13.6

Steps to Reproduce:

1. Developing a React app
2. Open the VSCode debugger
3. Enable the debugger
4. Attach the current debugger process to one of the React's process

Screenshots:

![image](https://user-images.githubusercontent.com/13918481/50896396-d9be4300-1443-11e9-9fee-c95603d0bfda.png)

When the debugger is off, GitLens works jsut fine 👍 🎉 

![image](https://user-images.githubusercontent.com/13918481/50896476-0eca9580-1444-11e9-8bf3-93bdb63256b8.png)
![image](https://user-images.githubusercontent.com/13918481/50896553-49ccc900-1444-11e9-9bdc-dffb57cfe5ec.png)

But when the debugger is enabled, it dosen't show any last commit anymore 😢

**Comment by felixfong227** [comment]
In my personal experiences, I saw the benefit of enabling the GitLens even during a debugging session, since it provides more information about the latest commit that costing the issue at the first place.

And having an option to enable the inline git blame annotations optionally just solve the issue.

**Comment by jpike88** [comment]
During debugging is the most likely point that you'd want to be blaming lines of code in my experience, I think it should show as much as it can.

**Comment by eamodio** [comment]
I will add an option to provide the blame annotations even when debugging.

**Comment by eamodio** [comment]
This was fixed in GitLens 9.6
