### ISSUE TITLE
Git lens proposal - changed lines marked with color next to line number

### ISSUE THREAD

**Issue by mklemarczyk** [eamodio/vscode-gitlens#62]
I have proposal to your extension that will enables user to better work with code.
Can you mark changed lines next to line number?

I mean something like this:
![screenshot 201](https://cloud.githubusercontent.com/assets/2727261/24828083/39570f78-1c56-11e7-9f64-ec84d9d3e3f2.png)

**Comment by eamodio** [comment]
Why is what vscode already provides (adds, changes & deletes) insufficient? I notice that vscode only provides the status for unstaged files (which is probably worth opening a vscode issue about), but other than it seems to provide the behavior you are looking for.

**Comment by mklemarczyk** [comment]
I know that vscode provides some info about file status, as you mentioned it can be a bug in vscode itself.
I usually lose that feature after restart a vscode, than it is had to find where you left your work and what was changed. I need to make diff on each file to find it out.

**Comment by eamodio** [comment]
@mklemarczyk I think it would be worth opening an issue for vscode to fix the cases where it isn't behaving as you'd expect/want. Feel free to link it back to this issue as well.

**Comment by eamodio** [comment]
@mklemarczyk I looked more into this -- and I don't think this would provide any value over what vscode already provides. The only time that I could find where vscode doesn't provide the "diff" is when the file is staged. I believe that is on purpose, but if you feel it should be changed please open an issue with vscode.
