### ISSUE TITLE
Current branch name in left down corner

### ISSUE THREAD

**Issue by fasvald** [eamodio/vscode-gitlens#622]
Hello.
When I try to checkout a branch from a repo using GitLens Side Bar Menu VSCode in the left corner shows me only id/hash of the branch, but not a name.

For example instead of showing `dev` name it shows me `2fgrersd...`.

How can I change it?
Thanks a lot.

**Comment by eamodio** [comment]
Are you checking out a local branch? Are there conflicts when you perform the checkout?

**Comment by Egorvoz** [comment]
@eamodio hello, sir. There are no conflicts at all. It's weird for me when I tried to open branch 'dev' for example but the status line shows me not the name 'dev', but hash :)

Never mind. Maybe it's a feature.
Thanks for your attention btw and nice plugin :)
Good job, sir.

**Comment by Egorvoz** [comment]
@eamodio steps to reproduce :)
I open GitLens as VS Code tab and then open remote branches.
For example, I want to check out `sandbox` branch => click to check out => and then it shows me that I am in `sandbox` branch but the name of it this branch is the hash of the last commit.

**Comment by dfmartin** [comment]
For me this is only with checking out a branch under the Remotes node of the repos tree.  It is actually checking out at that commit - not the branch - so it is showing up as HEAD detached in my console.  This is the only thing so far in GitLens that struck me as not working as it should - or at least as I would have expected it to.

**Comment by eamodio** [comment]
This will get fixed as part of https://github.com/eamodio/vscode-gitlens/issues/709
