### ISSUE TITLE
[Feature Request]  Link to pull request

### ISSUE THREAD

**Issue by kglickman** [eamodio/vscode-gitlens#623]
I frequently have the situation where I don't remember why I changed a line of code. I use the blame feature to find the commit id, build the URL in our internal git repository to see the commit, then use the link on that page to go to the pull request.

It would be amazing if GitLens could provide a link to the commit url, or even better, the pull request.

**Comment by kglickman** [comment]
I frequently have the situation where I don't remember why I changed a line of code.  I use the blame feature to find the commit id, build the URL in our internal git repository to see the commit, then use the link on that page to go to the pull request.

It would be amazing if GitLens could provide a link to the commit url, or even better, the pull request.

**Comment by eamodio** [comment]
@kglickman GitLens currently supports getting the commit url for a commit - see the `GitLens: Open Commit on Remote` command from the command palette. You can also get to this from the right-click menu of a commit on the GitLens views. Hope that helps.

**Comment by kglickman** [comment]
That is perfect!  I didn't have my gitLens.remotes set up correctly so I never knew what those features were supposed to do.

**Comment by kglickman** [comment]
I meant to tell you that this extension is a life saver.  I completely despised git before I found this.

**Comment by eamodio** [comment]
@kglickman Thank you!
