### ISSUE TITLE
Branches comparison not working

### ISSUE THREAD

**Issue by Speedy-VonGofast** [eamodio/vscode-gitlens#624]
Issue Type: <b>Bug</b>

When I try to compare a file from two branches, I get an error that the comparison file doesn't exist.

![image](https://user-images.githubusercontent.com/10726818/51037121-a13b7800-15af-11e9-9a7d-279e285d6214.png)

**Steps to reproduce:**
- Select _Compare <branch, tag or ref>_ on the Gitlens side bar
- Select two different branches
- Select a changed file to view the comparison

Extension version: 9.4.1
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (9.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
@Speedy-VonGofast Please retry this on v9.5 and let me know if it is still an issue

**Comment by eamodio** [comment]
Closing as I believe this is fixed.
