### ISSUE TITLE
Branches in Repositories view shows some commit comment texts as branches

### ISSUE THREAD

**Issue by haojun99** [eamodio/vscode-gitlens#625]
- GitLens Version: 9.4.1
  
- VSCode Version: 1.30.0
- OS Version: Windows 10

Steps to Reproduce:

1. Just open Branches in Repositories view. Some commit comment texts are shown as branches. When it gets worse, Branches won't show anything due to conflicting IDs (two commit comments with same texts).

I ran "git branch -vv --abbrev=40 -a". One suspicious thing I saw is the ^M character in some commit comment, e.g.
  remotes/origin/branchABC                                            7a841f39c052765c5fd04fa5253116d076dd9f3e Merge branch 'abc' into 'master'^M ^M Integrate Jobs UI^M ^M See merge request !9132

Is the text after ^M considered as a new line and thus a branch name?

**Comment by haojun99** [comment]
![untitled](https://user-images.githubusercontent.com/6914381/51080933-e3e17b00-16a9-11e9-98d7-d4a3c437bd7f.png)

**Comment by halicki** [comment]
I can confirm the same issue on:
* gitlens: 9.5.1
* vscode: 1.32.3
* ubuntu 18.04 LTS

And also in the repo on which the problem occurs has multiple commits with `^M` character in their message.

**Comment by eamodio** [comment]
Fixed in 9.7
