### ISSUE TITLE
Branch names with only digits always appear first

### ISSUE THREAD

**Issue by mlasson** [eamodio/vscode-gitlens#626]
Issue Type: <b>Bug</b>

To reproduce, make a branch with a name consisting only of digits (eg. "123") in a repository containing a starred/favorite branch (eg. "master"). Normally, you'll expect to have master appearing first in the list because it is starred but you'll see that the "123" is first:

![image](https://user-images.githubusercontent.com/5814258/51110376-cbcc4180-17f8-11e9-82a9-c47e20828ace.png)

Extension version: 9.4.1
VS Code version: Code - Insiders 1.31.0-insider (e02e44464c02d617b98d0a3265bf5efef7794436, 2018-12-21T06:20:35.852Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by speed-oss** [comment]
@mlasson if this was helpful to you, consider giving a reward to the issue solver using [Speedoss.com](speedoss.com)
