### ISSUE TITLE
Compare Ancestor 

### ISSUE THREAD

**Issue by sa-mm** [eamodio/vscode-gitlens#629]
Is `gitlens.views.compareAncestryWithWorking` working for anyone? I'm unable to see it in my context menu. It doesn't appear in the list of git commands available after pressing command + shift + P. I _can_ assign a keyboard shortcut to it, but invoking the keyboard shortcut does nothing.

Basically, I think I'm after `git diff master...HEAD` or `git diff master...(working copy somehow)`.

**Comment by eamodio** [comment]
@sa-mm That command is only hooked up as a context menu of branches in the GitLens views -- so if you right-click on the `master` branch in the _Repositories_ view, you should see the entry (unless `master` is already the current branch, and if so there is a `Compare with Working Tree` item)

Basically there are a few compare options on a branch, tag, or commit:
- _Compare with HEAD_ which is basically `git diff <selected-branch>...HEAD`
- _Compare with Working Tree_ which is basically `git diff <selected-branch>...`
- (non-current branches only) _Compare Ancestry with Working Tree_ which is basically `git diff (git merge-base --fork-point <selected-branch> <current-branch>)...`

Hope that helps
