### ISSUE TITLE
Switch commit message and author in commit pick list

### ISSUE THREAD

**Issue by mikes-gh** [eamodio/vscode-gitlens#63]
What do people think about having the Commit Message in bold above the Author and time in the pick list.

The same as Github.

![commit message](https://cloud.githubusercontent.com/assets/16208742/24853223/41162898-1dd2-11e7-9188-099ad36c7887.png)

When I'm visually scanning for a commit the message is more important to me.

Or maybe a config parmeter

**Comment by eamodio** [comment]
@mikes-gh Great suggestion! Changed the behavior -- I didn't add a config setting as I definitely agree that the message is much more important.
