### ISSUE TITLE
Is it possible to change these items... too obtrusive?

### ISSUE THREAD

**Issue by mikeerickson** [eamodio/vscode-gitlens#634]
I am curious if it is possible to change the font color for these items (see screenshot)  

![image](https://user-images.githubusercontent.com/183153/51431110-360a2b00-1bd9-11e9-983a-b4701409f92a.png)

**Comment by eamodio** [comment]
Please use the GitLens interactive settings editor from the command palette run `GitLens: Open Settings` and you can disable the Git code lens.
