### ISSUE TITLE
Show more commit not working properly 

### ISSUE THREAD

**Issue by cra0zy** [eamodio/vscode-gitlens#635]
Clicking Show more commits gets automatically collapsed after ~30 seconds.

- GitLens Version: 9.4.1
  
- VSCode Version: 1.30
- OS Version: Linux

Skipping steps as the issue is self explanatory.

**Comment by speed-oss** [comment]
@cra0zy if this was helpful to you, consider adding a reward to this issue using [Speedoss.com](speedoss.com)
