### ISSUE TITLE
WordWrap + heatmap annotations 

### ISSUE THREAD

**Issue by gmonet** [eamodio/vscode-gitlens#639]
- GitLens Version: 9.4.1
- VSCode Version: 1.30.2
- OS Version: Windows 10 17763.253

Steps to Reproduce:

1. enable editor.wordWrap: "on"
2. Enable nable gitLens
3. Enable heatmap with wrapped line

Heatmap annotations are not shown properly with wrapped lines.
Example with my LaTeX document : 
![image](https://user-images.githubusercontent.com/12810242/51823981-50cb5680-22e1-11e9-8dc7-5565463526bd.png)
Thanks for your amazing extension 👍

**Comment by eamodio** [comment]
Unfortunately vscode doesn't provide a way for extensions to provide the decorations required to handle word wrapping. Sorry.
