### ISSUE TITLE
Does not load with Live Share with error Service 'eamodio.gitlens.proxy' is not available.

### ISSUE THREAD

**Issue by kasplat** [eamodio/vscode-gitlens#640]
Issue Type: <b>Bug</b>

When running Gitlens with Live Share, displays error message "Service 'eamodio.gitlens.proxy' is not available." at the bottom right. Does not appear to do anything after this. Whenever I am not using live code, the extension works properly.

Extension version: 9.4.1
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (16.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kasplat** [comment]
Never mind, I just needed to install VS code on the host and it works properly. Would be good if the error was more clear, but not a problem.

**Comment by MaKaNu** [comment]
I have got a similar error but didn't thought about this, until I was wandering why one of my files is not showing gitlense inline blames anymore. I realized it was the file which we tinkered in oure live share session. Everyother file shows gitlense as expected.
