### ISSUE TITLE
Telemetry should be off by default or at least adhere to the general vscode settings

### ISSUE THREAD

**Issue by ferdynice** [eamodio/vscode-gitlens#641]
Telemetry should be disabled by default.

**Comment by ferdynice** [comment]
Didn't read the description well enough. It seems it already adheres to the vscode setting.

**Comment by eamodio** [comment]
@ferdynice Currently there is no telemetry at all - and it's been that way for a long time. Although that is likely to change in the future it will definitely adhere to the vscode setting

**Comment by jkhoogland** [comment]
@eamodio 

Could you explain what exactly is send back by gitlens ?

Looking at [telemetry.js](https://github.com/eamodio/vscode-gitlens/blob/master/src/telemetry.ts) it seems to be commented out ?

**Comment by eamodio** [comment]
Nothing. GitLens collects no data at all.
