### ISSUE TITLE
View size in SCM is not saved

### ISSUE THREAD

**Issue by Bledhard** [eamodio/vscode-gitlens#643]
- GitLens Version: 9.4.1
  
- VSCode Version: 1.30.2
- OS Version: Windows_NT x64 10.0.14393

Steps to Reproduce:

1.  Move 2 GitLens views to the SCM tab.
2. Expand them with the minimum height.
3. Restart VS Code.
4. One of the views moved to the top, making standard 'Changes' view minimal height.

The issue appears only when there are 2 of the views opened (I personally have all 5 views in the SCM tab, but 3 are minimized most of the time). When all views added to the SCM tab
and 4 of them are minimized, it works as expected and the only opened GitLense view saves the height, no matter what size it is.
I believe this issue will also appear if you will move only 2 of the views to the SCM tab and make them minimal height - looks like either a 2nd view is expanding, making other minimal height and taking all the height that has left, or just 1 GitLens view is treated like some kind of 'main' view, thus giving it priority in the placement (just an assumption).

See attached screenshots for the reference:
 ![gitlens_size_issue](https://user-images.githubusercontent.com/22518570/52234367-23c30900-28ca-11e9-9aad-564c1caf36e0.png)

When only 2 views are presented in the SCM tab issue remains:
![screenshot_1](https://user-images.githubusercontent.com/22518570/52235155-fa0ae180-28cb-11e9-9c8f-10d1bb8cb2be.png)

**Comment by eamodio** [comment]
Extensions have no control over the view sizing at all -- although vscode is usually very good at remembering the last position/size of all the views. I would recommend opening an issue on the vscode repository. Sorry.

**Comment by Bledhard** [comment]
@eamodio Thank you for the response.
By the way, the extension is awesome) Good job!

**Comment by eamodio** [comment]
@Bledhard Thank you!
