### ISSUE TITLE
All `npm run <command>` fails on GitLens v9.4.1 source code on macOS Mojave

### ISSUE THREAD

**Issue by billsedison** [eamodio/vscode-gitlens#644]
- GitLens Version: 9.4.1
- VSCode Version: 1.30.2
- OS Version: macOS Mojave 10.14.1
- nodejs version: v10.14.2
- npm version: v6.4.1

Steps to Reproduce:

1. git clone https://github.com/eamodio/vscode-gitlens.git (master branch)
2. cd vscode-gitlens
3. npm i
4. npm run build

You'll see no `dist` folder is generated. If you use VSCode to open it, and run F5, the extension is not runnable.

All `npm run <command>` fails.
The issue is the size of the package.json file. It is around 220KB.
On removing some fields to reduce the file size, `npm run` commands work fine.

**Comment by eamodio** [comment]
@billsedison What is the output from the commands?

**Comment by billsedison** [comment]
@eamodio There is not specific output, `npm run build` only exists silently.

```
$ npm run build

> gitlens@9.4.1 build /Users/honghaowang/Workspace/topcoder/copiloting/Aggregated_Git_Diff_For_VS_Code/9.4.1/vscode-gitlens
> webpack --env.development

$
```

Here is a screencast
![output](https://user-images.githubusercontent.com/5657467/52375525-cdf18b00-2a9a-11e9-88c6-59b9b6301681.gif)

This is only observed on macOS, no such issue on Ubuntu 18.04 and Windows 10.

**Comment by eamodio** [comment]
@billsedison Could this be related: https://stackoverflow.com/questions/53602337/node-and-npm-too-slow-to-start-after-install-of-macos-mojave

If you wait a while does it actually start?

**Comment by eamodio** [comment]
From the output -- it looks like its trying to run the command. I'm at a loss. I would recommend reaching out to npm and ask them or dig into npm's trace logs.

**Comment by billsedison** [comment]
> Could this be related: https://stackoverflow.com/questions/53602337/node-and-npm-too-slow-to-start-after-install-of-macos-mojave
>
> If you wait a while does it actually start?

Nope, it never actually starts even I wait for 1 minute.

> From the output -- it looks like its trying to run the command. I'm at a loss. I would recommend reaching out to npm and ask them or dig into npm's trace logs.

The problem is the `package.json` size (221KB) is too big, this issue wasn't observed on GitLens v8.5.6, where the `package.json` size is 159KB. Looks like the JSON object in `package.json` is too big.

If I reduce the size of package.json, for example, by removing `contributes.configuration`, then `npm run build` works.

Is it possible to move some configurations outside of `package.json`?

**Comment by eamodio** [comment]
Again, I would still recommend reaching out / filling an issue with npm. npm deals with this fine on other OS' (and later versions of macOS I believe) and package-lock.json files are much larger.

As for breaking it up -- I would think it is possible with some sort of build step to put the files back together, but given what would be built would be `package.json` and that's what's used to run commands, etc -- it seems like it would be tricky at the least.

**Comment by billsedison** [comment]
Okay, noted. Thanks.

**Comment by eamodio** [comment]
Sorry I don't have anything better to offer -- I'm at a loss. 😢

**Comment by billsedison** [comment]
No problem at all, thank you. At least I have some tricky workaround to bypass it by reducing the package.json size issue for now, it's been enough for my local development. 😄

**Comment by eamodio** [comment]
👍 Can also just use webpack directly -- the npm scripts themselves aren't really tricky at all.

**Comment by billsedison** [comment]
Yes, exactly!

**Comment by eamodio** [comment]
Going to close this since there isn't much I can do here given the `package.json` structure vscode requires.

**Comment by kburson** [comment]
can you use nps?

https://www.npmjs.com/package/nps

edit package.json:

"scripts": {
   ...,
   "start": "nps"
}

Then create a package.scripts.js file for the build targets?

**Comment by eamodio** [comment]
I've just switched to `yarn` rather than `npm` and hopefully once this PR lands https://github.com/yarnpkg/yarn/pull/7419 this won't be an issue anymore

**Comment by eamodio** [comment]
@billsedison @kburson Could you try and see if the latest [yarn nightly](https://nightly.yarnpkg.com/yarn-1.18.0-20190724.1302-unsigned.msi) resolves the issue for you?

**Comment by eamodio** [comment]
Yarn 1.19 is out which contains a fix for this issue.
