### ISSUE TITLE
monorepo: show only files to be committed under workspace folder(s)

### ISSUE THREAD

**Issue by digeomel** [eamodio/vscode-gitlens#645]
We're working on a monorepo, and each project is in a different folder under the one repository.
I have a different vscode workspace for each project, containing only the folders that are relevant to the project.
When I work on multiple projects (so, I have more than one vscode windows/workspaces) at the same time, Git(Lens) shows me all the files that have changed (to be committed) across all folders (projects).

I would like to see only the files that have changed below the folder(s) of my workspace.

There is a git command for this:

https://stackoverflow.com/questions/4104764/git-show-list-of-files-changed-in-recent-commits-in-a-specific-directory

https://stackoverflow.com/questions/16343659/how-to-show-git-log-history-for-a-sub-directory-of-a-git-repo

**Comment by eamodio** [comment]
@digeomel where are you seeing all the files? Inside the GitLens repositories view or in the Source Control sidebar?

**Comment by digeomel** [comment]
Source Control sidebar. I assume this is not handled by GitLens? Then I should probably remove this request and put it in the vscode github page...

**Comment by eamodio** [comment]
@digeomel yeah, the views on the Source Control side bar are provided by the built-in Git extension for vscode (unless you have configured GitLens to explicitly add its views to that same side bar). So you should open an issue with them.

**Comment by speed-oss** [comment]
@[digeomel](/digeomel) if you think this was helpful, consider adding a reward to this issue using [speedoss.com](speedoss.com) to support the issue solver for their work :)
