### ISSUE TITLE
Quickly show current file on other branch

### ISSUE THREAD

**Issue by cideM** [eamodio/vscode-gitlens#646]
In `vim-fugitive` I can do `:Gedit develop:%`. The `%` expands to the current file path and the command will open that file path but from the specified branch (here `develop`) in my editor. How do I achieve the same in GitLens? I can compare my directory and branch and then navigate through the explorer view but that's a bit clunky. I really just want the current file on the current branch and (next to it, on the side), the same file on a different branch.

**Comment by eamodio** [comment]
From the command palette, you can use the _GitLens: Open Changes with Branch or Tag..._ — compares the active file to the tip of the selected branch. The command is also on the right-click menu of items in the Source Control sidebar.

Or you can use _GitLens: Open Changes with Revision..._ — compares the active file with whatever revision you choose from the quick pick. The command is also on the right-click menu of items in the Explorer & Source Control sidebar. and as the alt (⌥) command of the _Open Changes with Previous Revision_ command in the editor toolbar

![image](https://user-images.githubusercontent.com/641685/52422155-86332980-2ac3-11e9-8c17-cc8673019bbe.png)

Hope that helps!

**Comment by cideM** [comment]
This always opens a diff rather than the file though

**Comment by emmanueltouzery** [comment]
yes `magit` has the same feature in `emacs`. i can pick a file and say "open me that file read-only as it is currently in branch X" and you get to pick which branch. I was hoping this could available through a command in vs code or vscode-gitlens but right now I'm under the impression it's not possible as-is.

**Comment by eamodio** [comment]
Ah, so to just open a readonly version of a specific revision use, _Open Revision..._ — opens a version of the active file with whatever revision you choose from the quick pick.

**Comment by cideM** [comment]
That doesn't let me select a branch though ;) although it's close since I can pick the most recent commit of that branch

**Comment by eamodio** [comment]
Yeah that is the equivalent. But I'll add a new command to open the revision from a branch or tag shortcut like the comparison one.

**Comment by cideM** [comment]
:+1:

**Comment by speed-oss** [comment]
@cideM if you think this was helpful, consider adding a reward to this issue using [speedoss.com](speedoss.com) to support the issue solver for their work :)
