### ISSUE TITLE
Can I move "hunks" between the panes in compare mode

### ISSUE THREAD

**Issue by talmdal** [eamodio/vscode-gitlens#647]
Is there away to transfer lines between panes after opening with "Open Changes with Working File". I usually have some changes stashed or in another branch.  I then want to bring those changes into the current branch. I'm not usually interested in the entire commit so Cherry-picking is not an option.

For example, If I'm comparing files in Intellij, There is a ">>" to transfer the change from the left pane to the right pane.

![image](https://user-images.githubusercontent.com/87743/52420618-43635880-2aa7-11e9-98ec-f095a2ea93b8.png)

Thanks

**Comment by eamodio** [comment]
Unfortunately not, and it is something that vscode itself would need to provide to really have a good experience. See https://github.com/Microsoft/vscode/issues/25887

**Comment by talmdal** [comment]
Thanks, for quick response and link to the other issue... I couldn't find that anywhere

**Comment by speed-oss** [comment]
@talmdal if you think this was helpful, consider adding a reward to this issue using [speedoss.com](speedoss.com) to support the issue solver for their work :)
