### ISSUE TITLE
How can I add additional repositories 

### ISSUE THREAD

**Issue by gbritton1** [eamodio/vscode-gitlens#648]
I have several, unrelated repos for different projects.  Previously I've used Atlassian Source tree, GIT GUI and more recently GitHub desktop for a meta-view of them.  Is there a way to add additional repositories to GitLens?  Did I just miss something easy to do? e.g. in Github desktop I have:

![image](https://user-images.githubusercontent.com/12263288/52425136-5d159780-2ac9-11e9-93d2-f13366144a3d.png)

And it has an "add" button to add more repos.  Can I do this with GitLens?

**Comment by eamodio** [comment]
GitLens only shows the repositories that you have open in vscode, so there isn't a notion of adding a repository — you would just open the folder for the repository (or containing repositories) and they should all show up automatically.

Hope that helps.

**Comment by gbritton1** [comment]
ah yes, that worked!

**Comment by speed-oss** [comment]
@[gbritton1](/gbritton1) if you think this was helpful, consider adding a reward to this issue using [speedoss.com](speedoss.com) to support the issue solver for their work :)
