### ISSUE TITLE
Blame information in the status bar remains after closing all files

### ISSUE THREAD

**Issue by rfgamaral** [eamodio/vscode-gitlens#65]
When you have the blame information displayed in the status bar and close all opened files, that information will still remain in the status bar. IMO, it should be removed when there are no opened files.

**Comment by eamodio** [comment]
@rfgamaral Thanks for the report -- I've reported the issue to vscode and it looks like that has been fixed in the upcoming recovery build. Once that is released, this bug should go away.

**Comment by rfgamaral** [comment]
@eamodio Great :)

Could you just clarify what is a "recovery build"?

**Comment by eamodio** [comment]
@rfgamaral I think what vscode calls a "Recovery Build" is basically a patch release. Basically addressing important issues that crop up right after the normal release.

I would expect to see the next recovery build in a day or two.

**Comment by rfgamaral** [comment]
Cool. Thanks :)

**Comment by eamodio** [comment]
Now that vscode `1.11.2` is released with the fix I'm closing this.
