### ISSUE TITLE
support i18n

### ISSUE THREAD

**Issue by axetroy** [eamodio/vscode-gitlens#652]
GItLens is great for me.

I hope to contribute and add support for i18n.

So ask the author here if you agree

If you agree, I would be happy to submit a PR support Chinese Simplified

**implement is very easy for extension**

**Comment by eamodio** [comment]
@axetroy Yes, I would love the help on this -- see https://github.com/eamodio/vscode-gitlens/issues/577

**Comment by axetroy** [comment]
I do not recommend using the official i18n example

Because it is too complicated, it is not easy for team assistance

There is an easier way to implement it

eg. https://github.com/axetroy/vscode-gpm or https://github.com/shanalikhan/code-settings-sync

**Comment by eamodio** [comment]
Can you explain the differences or the trade-offs with what you are suggesting vs the official vscode-nls library?

**Comment by eamodio** [comment]
Let's also close this issue and continue the conversation on #577

**Comment by speed-oss** [comment]
@[axetroy](/axetroy) if you think this was helpful, consider adding a reward to this issue using [speedoss.com](speedoss.com) to support the issue solver for their work :)
