### ISSUE TITLE
Branches merged with pull request 

### ISSUE THREAD

**Issue by graphicsxp** [eamodio/vscode-gitlens#653]
When we merge a feature branch via pull request, then the line in the visual tool does not go back to the master.
This does not happen when we merge manully a branch to the master.

Is this the expected behaviour ? 

![image](https://user-images.githubusercontent.com/4160415/52556390-aed16100-2dec-11e9-93a6-5bd778a409aa.png)

**Comment by eamodio** [comment]
That screenshot is showing the Git History extension not GitLens.

**Comment by graphicsxp** [comment]
I'm sorry about that. I forgot I've installed this extension and I thought it came from GitLens

**Comment by speed-oss** [comment]
@[graphicsxp](/graphicsxp) if you think this was helpful, consider adding a reward to this issue using [speedoss.com](speedoss.com) to support the issue solver for their work :)
