### ISSUE TITLE
Installs to Azure Data Studio, Doesn't Work

### ISSUE THREAD

**Issue by ScaryDBA** [eamodio/vscode-gitlens#657]
- GitLens Version:
  
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install to Azure Data Studio through .vsix
2. Try using CTL-SHIFT-P GitLens: Open Settings
command 'gitlens.showSettingsPage' not found

**Comment by eamodio** [comment]
GitLens doesn't currently support Azure Data Studio. This is duplicate of #573.

**Comment by speed-oss** [comment]
@ScaryDBA if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com)  :)
