### ISSUE TITLE
ERROR: EPERM: operation not permitted, lstat

### ISSUE THREAD

**Issue by gasharm** [eamodio/vscode-gitlens#658]
- GitLens Version:9.5.1
  
- VSCode Version: 1.13.1
- OS Version:Windows server 2012 R2

Steps to Reproduce:

Almost all the times when I update my local code base and then try to do npm install, I get an error "ERROR: EPERM: operation not permitted, lstat". 

If I run vscode without gitlens extension, I don't get this error.

Is there some way I can avoid this error permanantly or maybe some fix needed with this extension.

**Comment by eamodio** [comment]
@gasharm If you turn off the automatic refresh of the _Repositories_ view does that avoid the issue?

You can disable it (and re-enable it) from here
![image](https://user-images.githubusercontent.com/641685/54061384-9297c880-41ce-11e9-96f1-2673c85c50e6.png)

**Comment by eamodio** [comment]
@gasharm did that avoid the issue?

**Comment by gasharm** [comment]
Thanks @eamodio  for looking into this issue, but seems like the issue is happening even after uninstalling all my extensions. I think this is a VScode issue. Let's close this one.
