### ISSUE TITLE
Remove File & Blame History Explorers (peek style)

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#66]
Given the complexities of maintaining these as well as the non-optimal UI layout, I am thinking about removing these 2 features. Also given the more recent quick pick commands, these are sort of duplicated.

Please voice your feedback here if you feel these are valuable and should not be removed.

**Comment by eamodio** [comment]
I will be removing this feature in a post-5.0 release

**Comment by borekb** [comment]
Hi, I just found out about the Blame History Explorer, not really sure how to use them but is their goal similar to [GitHub's previous blame feature](https://github.com/blog/2304-navigate-file-history-faster-with-improved-blame-view)? Something like that would be super-useful in GitLens as the most recent blame might be something trivial like "code formatting" and an easy way to navigate to previous blames would be fantastic.

**Comment by eamodio** [comment]
@borekb sadly no, they were a VERY early feature that hacked into the peek UI too attempt to make the history visible. It was before I started using quickpicks and before custom views existed. And there is just no reason for them to exist anymore (their cost in the code is also harmful to future features). But you will be happy to know, that I have something in the works that is somewhat similar to that GitHub feature you mentioned :)

**Comment by borekb** [comment]
The new _Blame Previous Revision_ in 5.5.0 is fantastic, thank you!
