### ISSUE TITLE
SVN implementation

### ISSUE THREAD

**Issue by ebat79** [eamodio/vscode-gitlens#661]
Is it possible to integrate the use of this extension also in SUBVERSION repositories?
Now i use "SVN" and "SVN Gutter" extensions but GitLens seems to be more powerful.

**Comment by eamodio** [comment]
Not currently -- GitLens uses git directly to provide its feature set. In theory it could be possible to provide a different implementation of that but it would be a non-trivial amount of work (if it even could be adapted properly).
