### ISSUE TITLE
Make commit id in blame clickable

### ISSUE THREAD

**Issue by dwelle** [eamodio/vscode-gitlens#663]
Make commit id in `File Blame` annotations clickable to open commit on remote.

![image](https://user-images.githubusercontent.com/5153846/53161009-66bef500-35c9-11e9-97bf-bf1bfc4b8d1d.png)

Atom's [blame](https://atom.io/packages/blame) package has buttons:

![image](https://user-images.githubusercontent.com/5153846/53161087-9241df80-35c9-11e9-86d0-95fb1e56f434.png)

**Comment by eamodio** [comment]
While I would love to have that ability -- vscode doesn't allow extensions to provide that. The best I can do is what GitLens does today -- when you hover over one of those lines it will show a popup (called a hover) like:

![image](https://user-images.githubusercontent.com/641685/53197190-ad234c80-35e7-11e9-919b-c2c7ad145cef.png)

And then you can click on the links/buttons in there.

**Comment by dwelle** [comment]
Right.. forgot you could do that via popup since I had them disabled.

**Comment by eamodio** [comment]
Sadly yes. But little by little it gets better and better :smile:
