### ISSUE TITLE
Git lens

### ISSUE THREAD

**Issue by adityagandhi007** [eamodio/vscode-gitlens#665]
Issue Type: <b>Feature Request</b>

how to resolv this "GitLens was unable to find Git. Please make sure Git is installed. Also ensure that Git is either in the PATH, or that 'git.path' is pointed to its installed location."

Extension version: 9.5.1

OS version: Windows_NT x64 10.0.17763

**Comment by eamodio** [comment]
@adityagandhi007 Please ensure that git is in your PATH or set `git.path` in your vscode settings to the path to where git is located on your machine.

Hope that helps.
