### ISSUE TITLE
Decoration rendered before code

### ISSUE THREAD

**Issue by dbaeumer** [eamodio/vscode-gitlens#667]
Steps:

- file under Git
- add a line to that file
- open diff
- set cursor onto the added line in the right hand side editor of the diff
- discard the file changes using the Git viewlet

You get something like this: 

<img width="542" alt="capture" src="https://user-images.githubusercontent.com/1931590/53414590-5e9ef500-39cf-11e9-87e7-29048d5e5d0d.png">

**Comment by bernardo-amaral** [comment]
It's happen to me when I'm codding in file tab. In the VSCode update causes an delay to update the text from gitlens to your position, showing for me a wrong code for just seconds.

**Comment by eamodio** [comment]
@dbaeumer I can't seem to reproduce this with you steps -- though I have definitely seen this happen. Unfortunately I'm pretty sure this is an artifact of the way vscode decorations are implemented. I don't think there is any way for me to get around this.

**Comment by dbaeumer** [comment]
I discussed this with @alexandrudima when we saw this and we were the opinion this is something that can be addressed in the extension. @alexandrudima do you remember the outcome of our discussion :-)

**Comment by alexandrudima** [comment]
@eamodio @dbaeumer 
I think by logical trial & error we concluded that the flaw must be something like the following: 
- we speculate that the end-of-line decoration that does a quick-blame is updated on selection change
- it is possible for the content of the text to change dramatically without a selection change

Therefore, the end-of-line decoration should update both on selection change and on text document change.
