### ISSUE TITLE
Support disabling / hiding editor actions (icons at the right of tab bar)

### ISSUE THREAD

**Issue by ronjouch** [eamodio/vscode-gitlens#669]
I don't like editor actions (the little icons on the right of the tab bar)

![screenshot_gitlens-editor-actions_2019-02-26-11 26 02](https://user-images.githubusercontent.com/522085/53428890-9438e380-39b9-11e9-8845-6609a393dc0f.png)

, because:

1. I don't use them (I invoke the commands via keyboard shortcuts or the command palette)
2. they consume precious space
3. they add UI clutter

So, I'd like to hide them. Ideally, VSCode issue https://github.com/Microsoft/vscode/issues/46403 would be addressed to enable hiding all/some of them, but it's not yet, so on GitLens side I'd love a `gitlens.editorActions.enabled` setting letting me disable them.

Thanks for GitLens 🙂!

**Comment by eamodio** [comment]
This is supported today. While the documentation of it is practically non-existent (using the `gitlens.menus` setting), the GitLens settings editor provides easy access (run _GitLens: Open Settings_ from the command palette).

Here are the settings in `simple` mode:
![image](https://user-images.githubusercontent.com/641685/53432745-17aa0300-39c1-11e9-8311-680c23192688.png)

Use the dropdown pointed at to switch between `simple` and `advanced`.

Hope that helps.

**Comment by ronjouch** [comment]
> This is supported today. While the documentation of it is practically non-existent (using the `gitlens.menus` setting), the GitLens settings editor provides easy access (run _GitLens: Open Settings_ from the command palette).
> 
> Use the dropdown pointed at to switch between `simple` and `advanced`.
> 
> Hope that helps.

@eamodio it does! I had searched the gitlens settings namespace, but  missed `gitlens.menus` So,
```json
    "gitlens.menus": {
        "editorGroup": {
            "blame": false,
            "compare": false
        }
    },
```

Thanks!

**Comment by blowsie** [comment]
![image](https://user-images.githubusercontent.com/308572/66637876-ddb60600-ec0b-11e9-8c9f-6a77c67b65c6.png)

With updated UI

**Comment by sytelus** [comment]
All these should be false *by default*. I'm uninstalling GitLens until VSCode allows better management of editor actions.

**Comment by eamodio** [comment]
@sytelus You can easily set them off yourself.

**Comment by shiraze** [comment]
@sytelus I also found the options horrible, but by enabling them by default allows users to see these features - it's easier to get rid of something you notice than it is to add something you don't know about ;)
Documentation should have something like what @blowsie pointed out as I just couldn't figure out what needed changing!

**Comment by eamodio** [comment]
@shiraze What about the options did you find "horrible"?

Also what do you mean by?
> Documentation should have something like what @blowsie pointed out

That screenshot is from GitLens' settings.

**Comment by shiraze** [comment]
@eamodio I found the default options horrible, but pointed out that having them set like that allowed me to know that it was possible to have gitlens commands in the group toolbar.
Although @blowsie used a screenshot from the docs, the documentation doesn't shed any light how they affect the UI: similar to your first response to the OP - I was no wiser knowing that there was a simple/advanced drop-down.

**Comment by eamodio** [comment]
@shiraze Please feel free to open a PR for adding more documentation -- thanks!

**Comment by trkoch** [comment]
Is there a way to only show compare icons when in a diff?

**Comment by eamodio** [comment]
@trkoch which compare icons? As for the `...` menu that isn't currently an option.
