### ISSUE TITLE
New awesome logo?

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#67]
Any takers? ;)

**Comment by mklemarczyk** [comment]
I have one idea, but I will provide it after Easter.

**Comment by eamodio** [comment]
@mklemarczyk any chance you still have that idea brewing? ;)

**Comment by mklemarczyk** [comment]
@eamodio I do not have permission to make it public. Sorry.
I will try my best, but I can not promise anything.

**Comment by eamodio** [comment]
GitLens 6 has a new logo!

![](https://raw.githubusercontent.com/eamodio/vscode-gitlens/develop/images/gitlens-icon.png)
