### ISSUE TITLE
Configure similarity index for diffs

### ISSUE THREAD

**Issue by creisle** [eamodio/vscode-gitlens#670]
Is it possible to configure the similarity index when comparing to a branch/tag/etc?

If I were doing this from the command line I would be using the -M/--find-renames flag

For example if I wanted to lower the threshold to 20 (from the default 50)

```bash
git diff -M20 <commit>
```

**Comment by eamodio** [comment]
Unfortunately there is no way to do that today -- good feature request 😄

**Comment by eamodio** [comment]
@creisle @x13machine Is a global setting enough for this? Would you likely change this more than once? 

In addition to a global default would you like to change the threshold on a per-comparision basis, say via a command or something and you enter a new threshold and it would be applied to that comparison immediately?

**Comment by creisle** [comment]
A global setting should be good enough for our use case for now. I imagine once we start using it we could see better if it would be useful to have it per comparison?

Thanks for working on this!
