### ISSUE TITLE
DiffDirectoryCommand: Error: No diff tool found

### ISSUE THREAD

**Issue by keelung-yang** [eamodio/vscode-gitlens#671]
Firstly, I know maybe I should run "git config" command to config the third part diff tool. But I don't and Gitlens works--show diff results side by side in vscode, until I run "GitLens: Direcotry Compare All Changes". 

Obviously, GitLens or vscode knows there is a "diff tool" to show diff result without any configuration. But why GitLens's "Direcotry Compare Command" cannot just pick than one? why we must configure it manually?

**Comment by eamodio** [comment]
VSCode doesn't provided a directory compare tool.

**Comment by keelung-yang** [comment]
@eamodio THX! Now I know the reason.

**Comment by BrazhnykYuriy** [comment]
So does there any fix to this? Maybe some plugin?

**Comment by diegolaciar** [comment]
+1 !

**Comment by ezawadzki** [comment]
+1

**Comment by diegolaciar** [comment]
Hi there,

Any update on this?. 
How we can configure a diff tool on VScode for the gitLens functionality ?

**Comment by diegolaciar** [comment]
I found the solution for this.
edit the file:
```
~/.gitconfig
```
add this:
```
[diff]
    tool = vscode
[difftool "vscode"]
    cmd = code --wait --diff $LOCAL $REMOTE
```

if you want, you can also add this to use VSCODE for merge !
```
[merge]
    tool = vscode
[mergetool "vscode"]
    cmd = code --wait $MERGED
```
Soo cool, I love it.
Cheers,

**Comment by skplunkerin** [comment]
If the above fixes the error, but nothing happens when trying to diff... check to see if you can run the command in your terminal

```
code --wait --diff $LOCAL $REMOTE
```

**If not** then diffing isn't happening because you need to get the `code` command installed:

In command palette, search/run:

```
Shell Command: Install 'code' command in PATH
```

Diffing should now work in VSCode, in addition to running the command in your terminal.

**Comment by jankap** [comment]
This does not work for me, vs code opens but it cannot load the workspaces left/right, error is "unable to resolve workspace folder"
![image](https://user-images.githubusercontent.com/12893844/86342722-46d92000-bc58-11ea-8aa6-d07f10008025.png)
![image](https://user-images.githubusercontent.com/12893844/86342801-63755800-bc58-11ea-8783-b1b5f3cba262.png)

Any ideas?

**Comment by normanzb** [comment]
who someone who doesn' want to mess around with your default CLI diff tool, see this ticket:
https://github.com/eamodio/vscode-gitlens/issues/195
