### ISSUE TITLE
Copy deleted change

### ISSUE THREAD

**Issue by rchod** [eamodio/vscode-gitlens#673]
Hi,
Is it possible to add a button to allow the copy of a deleted/added (red/green) change ?
![screenshot from 2019-02-27 15-34-15](https://user-images.githubusercontent.com/623771/53498284-4f3eab00-3aa6-11e9-87b1-2b6c2d2b899a.png)
Otherwise I have to revert the change and then copy the contents and finally remove the change, and that is quite tedious.

**Comment by eamodio** [comment]
Unfortunately this isn't something GitLens can provide (vscode apis don't support it) -- I would recommend opening a feature request with the vscode repo to add support for this.
