### ISSUE TITLE
GitLen's icon looks weird in sidebar.

### ISSUE THREAD

**Issue by jeasonstudio** [eamodio/vscode-gitlens#676]
- GitLens Version: v9.5.1
  
- VSCode Version:  1.32.0-insider (1.32.0-insider)
- OS Version: macOS 10.14.3

It looks bigger than other icons. I don't think this is my illusion.

![image](https://user-images.githubusercontent.com/17971291/53627386-49ca9780-3c43-11e9-9051-2e8e70c6ddea.png)

**Comment by x13machine** [comment]
It's the same size as the debug icon. I checked it in gimp.

**Comment by eamodio** [comment]
Yeah, GitLens follows the vscode guidelines and the image is exactly the same size at the debug one.

**Comment by RayPS** [comment]
It looks weird  because the path is not pixel aligned.
<img width="723" alt="Screen Shot 2019-03-21 at 13 20 15" src="https://user-images.githubusercontent.com/1941540/54734665-16dd4900-4bdc-11e9-898b-286088ffc71e.png">
compare left (half pixels) and right (pixel aligned)

Please reopen.

**Comment by eamodio** [comment]
@RayPS Please feel free to send a PR with an updated image. I'd really need to see the icon in vscode to judge it properly.
