### ISSUE TITLE
GitLens showing commits by me as multiple different contributors

### ISSUE THREAD

**Issue by CodySayer** [eamodio/vscode-gitlens#686]
![Code_pdrsZ1Z7Dj](https://user-images.githubusercontent.com/14969722/54665215-9e736c80-4aa3-11e9-92d4-844af8c5d5f1.png)
Issue Type: <b>Bug</b>

I don't know how to reproduce this, I'm assuming it has something to do with the interaction between GitLens and GitBash for windows since I don't have the issue on MacOS.

On the file blame, end of line blame, and GitLens explorer, my commits are shown under "You", "Cody Sayer", and "CodySayer". 

It doesn't hinder functionality at all, but it looks wonky saying me, myself, and I contributed to this code.

Extension version: 9.5.1
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>

**Comment by eamodio** [comment]
Is it possible that you have committed code to that repo with more than 1 username/email? If you do a `git log` of the file in question, do you see different author names?

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
