### ISSUE TITLE
Disable the in line actions in repository view

### ISSUE THREAD

**Issue by paradoXp** [eamodio/vscode-gitlens#687]
I would like to disable the duplicate actions that appear on hover over each repository in the repositories view.
![image](https://user-images.githubusercontent.com/13684150/54696443-37d16b80-4b02-11e9-8850-ed05c916eb8f.png)

Having the option to select a repository and then take action from the top row of buttons will make the view less cluttered. When the UI is configured this way, it will need to only work against the selected repository. To work against multiple repositories, they would all need to be selected.

Also, I think it would be a good idea to have "collapse all" and "expand all" buttons. (like in the explorer view) 
![image](https://user-images.githubusercontent.com/13684150/54696685-a6aec480-4b02-11e9-922d-dc915b191f09.png)

**Comment by eamodio** [comment]
Unfortunately there isn't a way to multi-select in vscode views (at least not the views that extensions can contribute). If it were possible (or when it is possible), I like the idea of using multi-select to change fetch/pull/push all, but at the same time I'm don't want to lose the utility of the those affecting all the repos. I personally find both the "all" buttons and the individual buttons very useful.

As for the collapse all button, I think that is a good idea -- could you open an issue specifically for that?

**Comment by paradoXp** [comment]
I assumed that the "select multiple" ability was possible because it works from the explorer, but I have no experience developing extensions for vs code, so I don't know what the capabilities actually are.

I would definitely not request that the ability to have the top bar perform actions against all repos be removed. I can see how some people would like that ability. My thought was more to have a config that would change the behavior. By default it would work how it does now, and if the config was set it would work based on the selection.

In any case, I will open a separate request for the collapse all button.

**Comment by paradoXp** [comment]
One more option that may be easier or to implement would be a configuration that would allow the ability to hide the push all and pull all actions only. I find that I end up hitting the push all button quite often even though I only wanted to push a specific repo. Having the ability to hide those "super" buttons would protect imbeciles like me from initiating a push to 30 different repositories :-|

**Comment by eamodio** [comment]
@paradoXp I think the way I'm going to try to resolve this, is to make push/pull/fetch just behave as an entry into the new _Git Commands_ quick pick menu.

So for example, clicking on the _Push Repositories_ icon in the view will show the following:
![image](https://user-images.githubusercontent.com/641685/62679786-81243980-b983-11e9-99dd-c9e06d3b2fe3.png)
And from there, you can proceed, cancel, or even back up and choose which repositories should be pushed

As another example, when you click on a repository's _Pull_ icon it will show:
![image](https://user-images.githubusercontent.com/641685/62679878-d2ccc400-b983-11e9-9fe0-831ed279b125.png)
And you will have the same abilities as above.

What do you think about that?

**Comment by paradoXp** [comment]
Personally, I would rather have the option to hide the "push repositories" button instead of extra clicks, but I think ultimately this will prevent me from accidentally triggering a massive push or pull.

I can imagine some people (who are less error prone than I am) not liking the extra clicks, but maybe making the setting configurable could help with that.

Overall, I think your proposal is a good solution. Thanks for re-visiting this!

**Comment by eamodio** [comment]
Fixed in GitLens 10
