### ISSUE TITLE
Ability to collapse all and expand all in repositories view

### ISSUE THREAD

**Issue by paradoXp** [eamodio/vscode-gitlens#688]
In the repository view, I would like the ability to collapse all repositories so that I can get a quick overview of the repository status and get a more focused view of a specific repository. This would work the same was as the collapse all button in the explorer sidebar.
![image](https://user-images.githubusercontent.com/13684150/54696685-a6aec480-4b02-11e9-922d-dc915b191f09.png)

It could also be useful to have an "expand all" button so that if one were looking for something they could just scroll. An alternate to the "expand all" functionality could be the ability to start typing and the matches expand.

**Comment by derek-shnosh** [comment]
Excellent suggestion; to add, my preference is to have them collapsed by default (in a setting, maybe).

**Comment by eamodio** [comment]
The collapse all button was included in GitLens 9.6.
