### ISSUE TITLE
Disable diff in scrollbar

### ISSUE THREAD

**Issue by krsiakdaniel** [eamodio/vscode-gitlens#689]
Hi,

I tried to hide the diff in scrollbar using these (obviously wrong):

```
  "gitlens.recentChanges.highlight.locations": ["gutter"],
  "gitlens.blame.highlight.locations": ["gutter"],
```

I can view the diff on the left side, in the gutter. On the ride side in scrollbar want to hide it as it is really difficult to see anything else there. For example when I search: https://prnt.sc/n25tgl or select something: http://prntscr.com/n25smp

I would be greatful for help. Could not google it or find in the readme (or misunderstood).
Thanks.

**Comment by eamodio** [comment]
@krsiakdaniel sorry for any confusion, but GitLens doesn't provide the feature (UI) you referenced. It is provided by vscode itself. The setting you are looking is `"scm.diffDecorations"` and it can be set `all`, `overview` (the scrollbar), `gutter`, and `none`.

Hope that helps!

**Comment by dodalovic** [comment]
Hi, @eamodio , I tried setting `scm.diffDecorations` to `none` in the settings to remove highlighted area, but it didn't  work:

![image](https://user-images.githubusercontent.com/6358061/78941935-eef7a680-7ab8-11ea-83ae-f5348d089892.png)

Should I reopen the ticket, or I'm doing something unsupported / wrong? 

/cheers & thanks!

**Comment by eamodio** [comment]
@dodalovic Those decorations aren't from GitLens. But they also aren't Git decorations at all -- those are just the default decorations for added/changed/removed lines when you are in the diff editor. I would suggest you open an issue with VS Code if you want a way to disable that behavior.

**Comment by hotmailbelike** [comment]
I found this in this stackoverflow link: https://stackoverflow.com/questions/43969277/how-can-you-disable-gutter-indicators-in-vs-code

this is the solution, paste this in your settings.json file:
"workbench.colorCustomizations": {
    // Gutter indicators (left)
    "editorGutter.modifiedBackground": "#0000",
    "editorGutter.addedBackground": "#0000",
    "editorGutter.deletedBackground": "#0000",
    // Scrollbar indicators (right)
    "editorOverviewRuler.addedForeground": "#0000",
    "editorOverviewRuler.modifiedForeground": "#0000",
    "editorOverviewRuler.deletedForeground": "#0000"
}
