### ISSUE TITLE
GitLens steals Alt+F

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#69]
GitLens steals the Alt+F keyboard shortcut which should be reserved for File menu. As a workaround, the keybinding [can be removed](https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule).

**Comment by eamodio** [comment]
Ah -- right. I'll look for a new shortcut key for that in the next release. Thanks!

**Comment by eamodio** [comment]
@borekb FYI you can try the new beta here: [v3.5.0-beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v3.5.0-beta)? You can find installation instructions here: [Installing Beta Releases](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Beta-Releases)

This version changes the `alt+f` shortcut to `alt+/`.

**Comment by borekb** [comment]
I can't currently test it but trust that the mapping would work :)

**Comment by eamodio** [comment]
Fixed in 3.5.0
