### ISSUE TITLE
Not able to select a commit sha for branch comparision

### ISSUE THREAD

**Issue by danielo515** [eamodio/vscode-gitlens#690]
Issue Type: <b>Bug</b>

Hello,
Thanks for this great extension, it is awesome.
I am trying to compare one branch HEAD with a particular git commit of the same branch. Ideally I would love to just do `HEAD~1`, but this is not possible. Then I tried to pick the git sha from git log and that is not working either. Is this supposed to be supproted (according to the placeholder it is )

Thansk in advance.

Extension version: 9.5.1
VS Code version: Code 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3, 2019-03-08T00:15:00.418Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.03GB free)|
|Process Argv|-psn_0_11569928|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
@danielo515 Can you provide more details as to where in the UI you are trying this? In the places I can find, I'm able to compare to `HEAD~1` or other computed refs.

**Comment by danielo515** [comment]
Hope this gif clarifies it a bit

![Screen Recording 2019-04-01 at 05 11 PM](https://user-images.githubusercontent.com/2270425/55388205-c2ff2800-552a-11e9-8023-e32ffccf0c28.gif)
