### ISSUE TITLE
Can't open remote on bitbucket

### ISSUE THREAD

**Issue by gbritton1** [eamodio/vscode-gitlens#692]
- GitLens Version: 9.5.1
  
- VSCode Version:  1,32,3
- OS Version: Windows 10

Steps to Reproduce:

1. Connect to a Bitbucket repo, e.g.

```
git remote -v
origin  https://bitbucket.tds.td.com/scm/tbsm/tbsm-vision-db.git (fetch)
origin  https://bitbucket.tds.td.com/scm/tbsm/tbsm-vision-db.git (push)

```
2.
Click on :Open Branch On Remote

3. 404 since the URL is incorrect
(tries to go to https://bitbucket.tds.td.com/projects/scm/repos/tbsm/tbsm-vision-db/commits?until=develop)  

Correct url is: https://bitbucket.tds.td.com/projects/TBSM/repos/tbsm-vision-db/commits

The problem is the "scm/" inserted in the bad url.

**Comment by MitchLillie** [comment]
Also having this issue with Bitbucket Server v5.16.0

`scm` appears in the git URL, however it is not used at all in formulating the url for browsers to visit. Even with the `gitlens.remotes` configuration, it is not possible to construct a dynamic URL that works for each of my repos, and I have to hardcode it per-project.

Example:

```
${repo}: scm/myproject/myrepo
${repoPath}: myproject/myrepo
${repoBase}: scm
```

An example URL I need is:
https://bitbucket.customurl.com/projects/myproject/repos/myrepo/commits/a1b2c3

h1. Solution

Ignore `/scm` when translating the remote names into browser-friendly URLs.

**Comment by grozan** [comment]
PR #767 submitted

**Comment by eddyp** [comment]
When is the next release planned? I'm so tempted to hack a local copy version of the plugin just for this fix...

**Comment by eamodio** [comment]
Most likely tonight or tomorrow night.

**Comment by eddyp** [comment]
> Most likely tonight or tomorrow night.

Excellent!

BTW, thank you for your work! It's appreciated!
