### ISSUE TITLE
Configure remotes for git on TFS

### ISSUE THREAD

**Issue by stavnskov** [eamodio/vscode-gitlens#693]
Our git repo is hosted in Microsoft Team Foundation Server (TFS), see https://docs.microsoft.com/en-us/azure/devops/repos/git/overview?view=azure-devops

gitlens and vscode integration works fine except for remotes links. I try any of these methods to open the file on remote:
* Right click file|Open File on Remote
* gitlens code hover shield|...|Show More Actions|Open file? 
* gitlens sidebar Open File on Remote?
All of them open an empty pick list with gray text 'Open MyFolder/MyOtherFolder/MyFile on...., Nothing happens when I press enter on the empty pick list. I would at least expect it to try to open my browser on some URL.

I try to configure my gitlens.remotes settings:
```
 "gitlens.remotes": [{
        "domain": "tfs-fs.company.com",
        "type": "Custom",
        "name": "CompanyName",
        "protocol": "https",
        "urls": {
            "file": "http://tfs-fs.company.com:8080/tfs/collection/teamproject/_git/${repo}?path=${file}&version=GB${branch}",
            "repository": "https://git.corporate-url.com/${repo}",
            "branches": "https://git.corporate-url.com/${repo}/branches",
            "branch": "https://git.corporate-url.com/${repo}/commits/${branch}",
            "commit": "https://git.corporate-url.com/${repo}/commit/${id}",
            "fileInBranch": "https://git.corporate-url.com/${repo}/blob/${branch}/${file}${line}",
            "fileInCommit": "https://git.corporate-url.com/${repo}/blob/${id}/${file}${line}",
            "fileLine": "#L${line}",
            "fileRange": "#L${start}-L${end}"
            }
        }],
```
Are the values documentated anywhere? 

What types are available? TFS or should I use custom?

**Comment by esmcelroy** [comment]
In the URLs settings, you have to update all of the below values to work with TFS.

>             "repository": "https://**YOUR URL**/${repo}",
>             "branches": "https://**YOUR URL**/${repo}/branches",
>             "branch": "https://**YOUR URL**/${repo}/commits/${branch}",
>             "commit": "https://**YOUR URL**/${repo}/commit/${id}",
>             "fileInBranch": "https://**YOUR URL**/${repo}/blob/${branch}/${file}${line}",
>             "fileInCommit": "https://**YOUR URL**/${repo}/blob/${id}/${file}${line}",

where **YOUR URL** is, in this case `tfs-fs.company.com`

And, for each of these views, like repositories, add in the structure around the keywords, like `repo`, `branch`, `id`, etc. 
In the case of `repository` setting for bitbucket server, this looks like: `https://<git domain>/projects/${repoBase}/repos/${repoPath}/browse

I don't think there's a default setting for TFS, but based on the two examples in the [docs](https://github.com/eamodio/vscode-gitlens/tree/master/#custom-remotes-settings) you should be able to configure this successfully for TFS. You'll just have to do some digging. Recreate each view in a browser for one repo, and use this as your baseline for preparing the patterns

**Comment by stavnskov** [comment]
I have tried to do as you suggest, no luck. I would expect the "file" url to be used when I issue a "Open File on Remote" command. I have tried to fill in a direct working URL without any keys ${...}. That also does not work. There is no browser trying to open at all. Just the empty pick list within vscode.

**Comment by esmcelroy** [comment]
Unless you have all the URLs completed, I suspect the pick list opens up. I ran into similar issues when configuring for Bitbucket Server. Once I had all the URLs managed, it stopped giving a pick list, and copied to clipboard.

**Comment by ianwalkeruk** [comment]
I have found the following allows me to use the Remote URL successfully with an Azure Devops Server (new name for TFS):

`"urls": {
	"repository":   "http://TFSERVER/${repo}",
	"branches":     "http://TFSERVER/${repo}/branches",
	"branch":       "http://TFSERVER/${repo}?version=GB${branch}",
	"commit":       "http://TFSERVER/${repo}/commit/${id}",
	"file":         "http://TFSERVER/${repo}?path=${file}${line}",
	"fileInBranch": "http://TFSERVER/${repo}?path=${file}&version=GB${branch}${line}",
	"fileInCommit": "http://TFSERVER/${repo}/commit/${id}?path=${file}${line}",
	"fileLine":     "&line=${line}",
	"fileRange":    "&line=${start}&lineEnd=${end}"
}
`

Replace `TFSERVER` with your servername and port if necessary, also change HTTP to HTTPS if you have that configured

**Comment by schulzzw** [comment]
Is there somewhere that lists the keywords that are available to use in the patterns?

**Comment by ianwalkeruk** [comment]
> Is there somewhere that lists the keywords that are available to use in the patterns?

They are described in the source here: https://github.com/eamodio/vscode-gitlens/blob/dbab3ca0b0a51500b74baf66269546c176088d31/package.json#L1236

**Comment by alderben-mts-ru** [comment]
@ianwalkeruk [`README.md`](https://github.com/eamodio/vscode-gitlens/blob/master/README.md#custom-remotes-settings) also shows `${repoBase}` in example which is not explained anywhere.

Nevertheless, here is my on-premise Azure DevOps 2019 (formerly TFS) config:

```
    "gitlens.remotes": [{
        "domain": "tfs.mycompany.com",
        "type": "Custom",
        "name": "tfs.mycompany.com",
        "protocol": "https",
        "urls": { // https://github.com/eamodio/vscode-gitlens/blob/master/README.md#custom-remotes-settings
            "repository":   "https://tfs.mycompany.com/${repo}",
            "branches":     "https://tfs.mycompany.com/${repo}/branches",
            "branch":       "https://tfs.mycompany.com/${repo}/commits?itemPath=%2F&itemVersion=GB${branch}",
            "commit":       "https://tfs.mycompany.com/${repo}/commit/${id}",
            "file":         "https://tfs.mycompany.com/${repo}?path=${file}&line=${line}",
            "fileInBranch": "https://tfs.mycompany.com/${repo}?path=${file}&line=${line}&version=GB${branch}",
            "fileInCommit": "https://tfs.mycompany.com/${repo}/commit/${id}?path=%2F${file}&mpath=%2F${file}&mversion=GB${id}", // &gridItemType=2&opath=%2F${originalFile}&oversion=${originalID}&_a=compare
            "fileLine":     "${line}",
            "fileRange":    "${start}&lineEnd=${end}"
        }
    }],
```

However, I have not found any way to use line-references from the UI, thus not tested them. `fileInCommit`, `fileLine` and `fileRange` are just guesses.

**Comment by blindside85** [comment]
This was driving me insane! So, in case it's helpful to someone else, it took a long time to figure out the magical combination of options to get this working for me. The key thing I was missing was getting the `domain` value wrong- I was including the domain *and* the path like this:
```
tfs.company.com/tfs/Company/Department/_git
```
instead of the correct way, which is simply `tfs.company.com`.

Ultimately, here's what I ended up with:
```json
"gitlens.integrations.enabled": true,
"gitlens.remotes": [{
  "type": "Custom",
  "name": "Realpage TFS",
  "protocol": "https",
  "domain": "tfs.company.com",
  "urls": {
    "repository":   "https://tfs.company.com/tfs/Company/Department/_git/${repo}",
    "branches":     "https://tfs.company.com/tfs/Company/Department/_git/${repo}/branches",
    "branch":       "https://tfs.company.com/tfs/Company/Department/_git/${repo}?version=GB${branch}",
    "commit":       "https://tfs.company.com/tfs/Company/Department/_git/${repo}/commit/${id}",
    "file":         "https://tfs.company.com/tfs/Company/Department/_git/${repo}?path=${file}${line}",
    "fileInBranch": "https://tfs.company.com/tfs/Company/Department/_git/${repo}?path=${file}&version=GB${branch}${line}",
    "fileInCommit": "https://tfs.company.com/tfs/Company/Department/_git/${repo}/commit/${id}?path=${file}${line}",
    "fileLine":     "&_a=contents&line=${line}",
    "fileRange":    "&_a=contents&line=${start}&lineEnd=${end}"
  }
}]
```

**Comment by stavnskov** [comment]
I finally managed to configure my remotes. Some notes to observe:
* Remember to include any port in the domain setting and urls
* ${Repo} apparently includes /tfs/collection/teamproject/_git/
* Line number does not seem to work
* Remember to set protocol to either http or https

Example:
```
"gitlens.integrations.enabled": true,
"gitlens.remotes": [ {
        "type": "Custom",
        "name": "Friendly name",
        "protocol": "http",
        "domain": "tfs-fs.mycompany.com:8080",
        "urls": {
            "repository":   "http://tfs-fs.mycompany.com:8080/${repo}",
            "branches":     "http://tfs-fs.mycompany.com:8080/${repo}/branches",
            "branch":       "http://tfs-fs.mycompany.com:8080/${repo}?version=GB${branch}",
            "commit":       "http://tfs-fs.mycompany.com:8080/${repo}/commit/${id}",
            "file":         "http://tfs-fs.mycompany.com:8080/${repo}?path=${file}${line}",
            "fileInBranch": "http://tfs-fs.mycompany.com:8080/${repo}?path=${file}&version=GB${branch}${line}",
            "fileInCommit": "http://tfs-fs.mycompany.com:8080/${repo}/commit/${id}?path=${file}${line}",
            "fileLine":     "&_a=contents&line=${line}",
            "fileRange":    "&_a=contents&line=${start}&lineEnd=${end}"
        }
}]
```
