### ISSUE TITLE
Public Key issue when trying to push/pull for Visual Studio Code on Mac

### ISSUE THREAD

**Issue by mikeflemingcfs** [eamodio/vscode-gitlens#696]
Hi, 
I can't seem to find the right answer here or on the web.

So, if I create a project opening my Repo folder, VSC and GitLens see all the branch details.  However, I cannot use the pull/push features as I get a Permission (publickey) denied error.

I can't figure what setting to update to overcome this issue.

Hoping you can advise.
![Screen Shot 2019-04-04 at 09 45 51](https://user-images.githubusercontent.com/45431594/55542347-c3302c80-56be-11e9-9f2c-3b85649a6633.png)

**Comment by eamodio** [comment]
@mikeflemingcfs Do you see this same issue using the pull/push commands in vscode directly?

**Comment by mikeflemingcfs** [comment]
If you mean I just use VSC terminal?  If I do that I get the passphrase request and then it pushes.

**Comment by eamodio** [comment]
I mean from either the command palette -- `Git: Pull` or from the `...` menu on the Source Control sidebar:
![image](https://user-images.githubusercontent.com/641685/55899964-10ffd580-5b94-11e9-8110-91a06f23b73e.png)

**Comment by mikeflemingcfs** [comment]
Hi Eamodio, yes same issue using the command palette.
Whilst this isn't causing me an issue in Bitbucket, could it be the issue in VSC?
fatal: ambiguous argument 'PE/QA1-Digital-25765_Croatia@{u}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose

**Comment by mikeflemingcfs** [comment]
Source Control, same issue.
![Screen Shot 2019-04-16 at 10 18 20](https://user-images.githubusercontent.com/45431594/56197583-0ed4c580-6031-11e9-9314-931abbc44b3c.png)

**Comment by mikeflemingcfs** [comment]
This was the troubleshooting page that helps me resolve my issue.  In essence, the fact that I was able to successfully push/pull to Bitbucket using sourcetree, obscured the fact that my ssh keys had not been added to git.
https://confluence.atlassian.com/bitbucket/troubleshoot-ssh-issues-271943403.html

**Comment by eamodio** [comment]
@mikeflemingcfs glad you figured it out!

**Comment by aprofromindia** [comment]
need to add your private key to ssh agent

`ssh-add ~/.ssh/<private_key_file>`
