### ISSUE TITLE
Support Git Stash unstaged changes

### ISSUE THREAD

**Issue by julian-poidevin** [eamodio/vscode-gitlens#698]
It would be great to have "Git: Stash unstaged changes" command shortcut in command pannel 
This would avoid typing manually `git stash save -k`.

The "Stash All changes" button in the right pannel has the same function in `STAGED CHANGES` and in `CHANGES` parts. Maybe it could be implemented an other way on the `CHANGES` part to only stash changes not staged.

![image](https://user-images.githubusercontent.com/8756421/55413200-26a84600-5569-11e9-8b2b-0977a7de6c5a.png)

----
Cross issue with https://github.com/Microsoft/vscode/issues/71597

**Comment by julian-poidevin** [comment]
Any updates on my suggestion ? @eamodio ? 😄

**Comment by julian-poidevin** [comment]
Any considerations @eamodio ?

**Comment by eamodio** [comment]
@julian-poidevin Sorry, I somehow missed this before. Good idea -- and I'm also going to be adding stash support to the new _Git Commands_ command as well

**Comment by julian-poidevin** [comment]
@eamodio Thanks for implementing this ! 👍🏻
