### ISSUE TITLE
Not able to compare file with previous commits.

### ISSUE THREAD

**Issue by kggp1995** [eamodio/vscode-gitlens#70]
Here's the message I'm getting when trying to compare the current file with previous commit(Empty file commit previously): **"Unable to open compare. See output channel for more details"**

- GitLens Version: 3.4.8

- VSCode Version: Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:01:14.464Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

What might be possibly going wrong?

**Comment by eamodio** [comment]
@kggp1995 Can you set `"gitlens.outputLevel": "verbose"` in your `settings.json`? This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

**Comment by kggp1995** [comment]
Ok, here's what we have:  
**Error: fatal: Not a git repository (or any parent up to mount point /home/$USER) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).  Failed with exit code: 128**

The file was in a git folder, which in-turn was a sub-folder of the opened non-git folder from the editor.

SO, I opened the specific sub-folder in the editor and now shows the proper message:
...**has no previous commit**
