### ISSUE TITLE
How do you push git repository to GitHub from visual studio?

### ISSUE THREAD

**Issue by nickcorona** [eamodio/vscode-gitlens#700]
There doesn't seem to be any functionality to do that.

**Comment by eamodio** [comment]
@nickcorona are you asking about Visual Studio or VS Code? If the former, then GitLens doesn't apply (it is an extension for VS Code).

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
