### ISSUE TITLE
Any chances to make it work under Visual Studio 2019 Community?

### ISSUE THREAD

**Issue by romanoza** [eamodio/vscode-gitlens#705]
The latest version of VS 2019 Community came with CodeLens enabled. Is there any chance to make this excellent product work under VS 2019 Community?

**Comment by eamodio** [comment]
GitLens is currently only for VS Code. Visual Studio doesn't support the same extension model that VS Code supports so in order to support Visual Studio it would be a new extension written from the ground up.

**Comment by Saibamen** [comment]
Any plans to do it in 2020?
Or maybe you can recommend me a VS plugin for `current line blame`?
