### ISSUE TITLE
Transparent hover

### ISSUE THREAD

**Issue by kylrth** [eamodio/vscode-gitlens#706]
Sometimes I accidentally leave my mouse on the in-line blame annotation, and the hover appears, blocking code I'm trying to read. I haven't found a way to make the hovers transparent. Ideally, it could follow the behavior specified by the following in `settings.json`:

```
"workbench.colorCustomizations": {
    // transparent code suggestions
    "editorSuggestWidget.background": "#21252BAA"
}
```

Let me know if I simply haven't found the setting to change.

**Comment by eamodio** [comment]
`editorHoverWidget.background` should be what you are looking for

You can see them all here:
https://code.visualstudio.com/api/references/theme-color#editor-widget-colors

Hope that helps!
