### ISSUE TITLE
Checkout a remote branch as new local branch

### ISSUE THREAD

**Issue by rehbein-dieter** [eamodio/vscode-gitlens#709]
The context-menu of a remote branch contains a menu item "Checkout". Using that item leads to a detached HEAD.

A second menu item "Checkout as new local branch" would be useful to check it out as a new local branch (if a local branch doesn't already exist).

**Comment by eamodio** [comment]
@rehbein-dieter do you think the detached HEAD version is worth keeping? I'm thinking about just replacing the `Checkout` command on remote branches to be what you describe. Thoughts?

**Comment by rehbein-dieter** [comment]
@eamodio Replacement would be perfectly fine for me (I don't think that I've ever used a detached HEAD). 
Thanks for the quick response.

**Comment by raaaaaymond** [comment]
Thanks @eamodio for addressing this. Yes I would be happy with replacing the detached HEAD version with checkout as local (but tracking the remote obviously) by default. Indeed, this is the default behaviour of the Jetbrains IDEs (from where I'm switching to VSCode). The detached HEAD version is still useful, but we shouldn't have that as default, in my opinion.
