### ISSUE TITLE
Blame information is invalid when a file has changed outside of VSCode

### ISSUE THREAD

**Issue by SailorMax** [eamodio/vscode-gitlens#71]
GitLens ignore new/deleted line shifts in modified by outside file.

Steps:
1. open document which history has few people, for example:
line 1 by user A
line 2 by user B
line 3 by user C
2. open same document in another editor (EditPlus?)
3. EditPlus: put cursor in end of line 1, press Enter and save changes
4. switch to VSCode
5. check owners of lines 1-4

Expected:
line 1 by user A
line 2 (empty) has no user
line 3 by user B
line 4 by user C

Actual:
line 1 by user A
line 2 (empty) by user B
line 3 by user C
line 4 has no user

P.S. GitLens start to see new line only after resave file in VSCode. Looks like it ignore "refresh document" event.

**Comment by SailorMax** [comment]
this is continue of bug #36

**Comment by eamodio** [comment]
Thanks! I'll take a look
