### ISSUE TITLE
Error: Unknown view gitlens.views.fileHistory:gitlens

### ISSUE THREAD

**Issue by scambier** [eamodio/vscode-gitlens#711]
- GitLens Version: 9.6.0
  
- VSCode Version: 1.33.0
- OS Version: Windows 7 64bits

Steps to Reproduce:

1. Execute the "GitLens: Show File History" or "GitLens: Show File History View" command
2. The file history view does not show, and an error message pops in the output: 

```
[2019-04-12 05:56:23:297] e.isVisible
Error: Unknown view gitlens.views.fileHistory:gitlens
```

I tried reinstalling the extension (and even deleting the files in the .vscode/extensions folder), but the problem is still present.

Here's a screenshot of my sidebar:

![image](https://user-images.githubusercontent.com/3216752/56015405-4114b900-5cf9-11e9-837f-2ffd28061acc.png)

**Comment by eamodio** [comment]
This sounds like the same issue as https://github.com/eamodio/vscode-gitlens/issues/710. Unfortunately I can't reproduce either of these. Can you try again with vscode 1.33.1 to see if it makes any difference?

**Comment by scambier** [comment]
I tried with the following VSCode versions (in that order) :
- Downgrade to 1.33.1: not working
- Downgrade to 1.32.3: not working
- Downgrade to 1.31.1 : not working
- **Downgrade to 1.28.2: working**
- Upgrade to 1.29.1: not working


I uninstalled and reinstalled the extension each time I changed VSCode version

**Comment by eamodio** [comment]
@scambier I think I have figured out the issue -- do you have `gitlens.views.fileHistory.enabled` set to `false` in your vscode configuration? If so, that explains the issue, since GitLens doesn't even register the view if it is disabled. I will make a change in the next version to instead prompt you to enable the view in this case.

**Comment by scambier** [comment]
Indeed, that was the issue, even though I don't remember disabling it.

**Comment by musahaidari** [comment]
> @scambier I think I have figured out the issue -- do you have `gitlens.views.fileHistory.enabled` set to `false` in your vscode configuration? If so, that explains the issue, since GitLens doesn't even register the view if it is disabled. I will make a change in the next version to instead prompt you to enable the view in this case.

@eamodio Can you share how did you do it? Sorry if it is a naive questions

**Comment by scambier** [comment]
@musahaidari F1 > "Open User/Workspace Settings"

Click on the "json" icon to have a raw view  
![image](https://user-images.githubusercontent.com/3216752/73763699-14db9480-4772-11ea-9e4d-431b10580a15.png)

Then locate the setting and either change its value or delete the line.
