### ISSUE TITLE
I add written code to solve the issue #670 "Configure similarity index for diffs"

### ISSUE THREAD

**Issue by x13machine** [eamodio/vscode-gitlens#712]
The PR message said to write an issue first. Repo: https://github.com/x13machine/vscode-gitlens

**Comment by eamodio** [comment]
@x13machine Are you going to submit a PR for that? I don't see one currently -- and if you need help with it just let me know.

**Comment by x13machine** [comment]
I'll submit one soon. I made a mistake, I'll fix it before submit.
