### ISSUE TITLE
Toggle comparison style

### ISSUE THREAD

**Issue by jshall** [eamodio/vscode-gitlens#713]
It appears the the comparison tool is based on `git log ref1...ref2`. It would be nice to toggle between `ref1...ref2` and `ref1..ref2`.

**Comment by eamodio** [comment]
@jshall Any thoughts on where/how to toggle that? Like a menu option similar to `Follow Renames`? A config setting? Something else?

**Comment by eamodio** [comment]
Also how would you best explain the difference in the title of a menu choice?

**Comment by eamodio** [comment]
This was addressed in v9.8.0 -- see the `gitlens.advanced.useSymmetricDifferenceNotation` setting
