### ISSUE TITLE
[Feature request] Hotkey: focus into changed file repositories, split changed file section into staged and unstaged 

### ISSUE THREAD

**Issue by phmngocnghia** [eamodio/vscode-gitlens#715]
**Requested Hotkey Lists:**

**- Focus into changed files of repositories:**
Press <key> to open gitlens view. Focus into repositories section then focus into changed file section

**- Split changed files into section: staged and unstaged:**
Make it easy to manage file changed. Also add a hotkey to focus into change and unchanged section.

**- Focus and collapse other**
- Collapse all section repositories, file history, line history .. etc
- Focus into one section will collapse other section
- eg hotkey to focus into repository section and collapse other section... same apply for (file history, line history, compare))

**- Collapse all section:**
- Collapse all section repositories, file history, line history .. etc

**Comment by eamodio** [comment]
This is out of scope for what I would add into GitLens -- especially with GitLens 11 in the same side bar as the built-in Git -- there is little need to duplicate its functionality
