### ISSUE TITLE
Can't see changed files when comparing branches

### ISSUE THREAD

**Issue by joselcvarela** [eamodio/vscode-gitlens#718]
No output from Output pane.

- GitLens Version: 9.6.1
  
- VSCode Version: 1.33.1
- OS Version: Linux Mint 19 Tara

Steps to Reproduce:

1. Compare two branches

This will dispatch a notification with this message:
`Cannot set property repoPath of [object Object] which has only a getter`

I can see the diff in commits but not the files changed.

**Comment by joselcvarela** [comment]
If I install the v9.6.0, this functionality works fine.

**Comment by glogar** [comment]
Same here:

OS Version: win10

**Comment by krpn** [comment]
+1

**Comment by eamodio** [comment]
@joselcvarela @glogar @krpn Sorry for the issue -- I've posted 9.6.2 which fixes this.
