### ISSUE TITLE
Selected line not considered by 'Open Line Changes with Previous Revision'

### ISSUE THREAD

**Issue by max-sixty** [eamodio/vscode-gitlens#719]
As you can see in the gif, "Open Line Changes with Previous Revision" selects a change that's unrelated to the selected line.

Is this unexpected behavior? Possibly it's my expectations...

![line changes small](https://user-images.githubusercontent.com/5635139/56328612-b9420b00-614d-11e9-96a4-79c36114ee0b.gif)

Let me know if logs would be helpful

And thanks for such an awesome package!

- GitLens Version: 9.6.2
- VSCode Version: 1.33.1
- OS Version: MacOS

**Comment by Banana-In-Black** [comment]
It looks like using the working version of selected line instead of last version to compare with previous version.

**Comment by max-sixty** [comment]
Thanks @eamodio !
