### ISSUE TITLE
ISO time and date format

### ISSUE THREAD

**Issue by CornyjK** [eamodio/vscode-gitlens#721]
Is there a way to display date in [original](https://momentjs.com/docs/#/displaying/format/) ISO format? I mean other than just rewriting the format.

**Comment by eamodio** [comment]
No, you'd need to set something like the following:
```
 "gitlens.defaultDateFormat": "YYYY-MM-DDTHH:mm:ss.sssZ",
  "gitlens.defaultDateShortFormat": "YYYY-MM-DD",
  "gitlens.defaultDateStyle": "absolute",
```

Hope that helps.
