### ISSUE TITLE
Top right tool loading/placement enhancement

### ISSUE THREAD

**Issue by zero41120** [eamodio/vscode-gitlens#723]
There are 2 problems I would like to describe for the tool icons on the top right.
## Problem 1
Top right tool icon flickers when enter a diff editor, its load time is not desirable. User can start interact with the vscode default Previous Change/Next Change button and expect them to work without moving their mouse.
![ezgif-1-6122bff52b2a](https://user-images.githubusercontent.com/10471270/56680065-49ff7600-667b-11e9-9136-be6a7213f8b2.gif)

## Problem 2
Almost the same issue as problem 1, however, this one is not about the load time. It is about the placement. As a user, when I click on 'Open Changes with Previous Revision', I expect my next click to do the same action without moving. If a user had not looked at the tool bar and have not noticed the next click is 'Open Changes with Next Revision'. It confuses the user.
![2WCeAtt1VF](https://user-images.githubusercontent.com/10471270/56680669-88496500-667c-11e9-83d6-98705a33a1a1.gif)

### Suggested solution 
 - Prepend icons instead of append, so the default buttons' location does not change. 
 - Instead of dynamically showing buttons that is applicable to the editor, show the entire collection of buttons and disable the unrelated one.

**Comment by hacknug** [comment]
Problem 2 is extremely annoying and should be fixed by disabling unusable buttons like core does (eg. Search sidebar top-right corner icons).
