### ISSUE TITLE
creating a new file right after opening a folder makes vscode ui bug

### ISSUE THREAD

**Issue by mattrn** [eamodio/vscode-gitlens#726]
Issue Type: <b>Bug</b>

1. Install and activate GitLense
2. Open a Project Folder
3. Right after loading, create a new file with the "new file" button in the ui and start typing.
4. After 1 or 2 seconds the little text field for entering the filename will disappear.
5. Afterwards in some cases the "new file" Button wont work anymore

Extension version: 9.6.3
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10 PRO-7850B R7, 12 Compute Cores 4C+8G    (4 x 3693)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|15.92GB (6.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
@mattrn This seems to be a bug in vscode itself. I can reproduce this with 1.33.1, but can't with 1.34 (insiders).
