### ISSUE TITLE
command "gitlens.XXX" not found

### ISSUE THREAD

**Issue by rotwurstesser** [eamodio/vscode-gitlens#727]
Hello, i already deleted the extension in the folder after deinstalling the extension, and even restarted my mac after manually deleting the plugin in the folder. Sadly this didn't fix anything, i still can't call any commands nor do i get blame annotations inside my VSCode. If i can help in any way to fix it please let me now! I really miss my Lens ! Thanks for the great tool 💙

- GitLens Version: 9.6.3
- VSCode Version: 1.33.1
- OS Version: macOS Mojave 10.14.4

**Comment by eamodio** [comment]
@rotwurstesser Can you enabled output logging and post the output?

**Comment by rotwurstesser** [comment]
I apologize If i didn't understand this correctly : i need to set "gitlens.outputLevel": "verbose" in my Settings.json then i should see errors in the "Output" (which is next to the integrated terminal) as soon as i run any gitlens commands ?  I don't get any output ....

**Comment by eamodio** [comment]
Yeah, make sure you reload vscode after setting `gitlens.outputLevel` and you should see the output here:
![image](https://user-images.githubusercontent.com/641685/57007416-76088300-6bb6-11e9-98c0-d38dd6ce77ab.png)

**Comment by rotwurstesser** [comment]
![Screenshot 2019-05-01 at 09 29 34](https://user-images.githubusercontent.com/8830678/57008907-a6badd80-6bf3-11e9-867c-0960524272fd.png)


It doesn't show it =( is there any other settings i might need to do?

**Comment by eamodio** [comment]
@rotwurstesser does this issue still happen with GitLens 9.7 or later?

**Comment by rotwurstesser** [comment]
Yes, 'gitLens.showsettingsPage' (or any commands) not found with version 9.7.3

**Comment by eamodio** [comment]
@rotwurstesser Do you possibly have GitLens disabled or something? I don't understand what could be happening

**Comment by rotwurstesser** [comment]
It is active, a difference i did notice since the upgrade to 9.7.3 though: the folder of gitlens in my extensions now has content...

**Comment by eamodio** [comment]
So is it working now? If not, are there any logs now?

**Comment by rotwurstesser** [comment]
Sadly no... but i found a plugin thats working for my needs atm, not as good as Lens but will do ... =) i will check the updates for gitlens from now on and notify you when it works again, thanks for your time !

**Comment by eamodio** [comment]
The only other thing I can think of is that there is anti-virus that is getting in the way (there were some issues with false positives and av software nuking GitLens files). Can you check inside the `dist` folder inside the GitLens folder and let me know what files are in there?

**Comment by rotwurstesser** [comment]
sure!
This is the content:
- extension.js  
- extension.js.map 
- webviews

**Comment by eamodio** [comment]
@rotwurstesser does the `extension.js` have a valid size ~798 KB?

**Comment by rotwurstesser** [comment]
it has 827kb

**Comment by joelw** [comment]
I had the same problem - what eventually fixed it was deleting all gitlens settings from my settings.json.

**Comment by rotwurstesser** [comment]
@eamodio as @joelw said (thanks! 🙏) this solves it, i cleared everything and did a clean install, glad to use gitlens again =)

**Comment by dsturm** [comment]
Unfortunatly I got the same issue, but a clean install didn't fix it so far. Opening the debugger gives me some "Unexpected token" errors on ~/.vscode/extensions/eamodio.gitlens-9.9.3/dist/extension.js, which addresses the spread operators like in `renderOptions:{before:{...i}}`.

I am using:
- GitLens Version: 9.9.3
- VSCode Version: 1.36.1
- OS Version: macOS Mojave 10.14.6

**Comment by dsturm** [comment]
... even on GitLens Version 10.0.1 the error occurs. I tried the uninstall -> delete folder -> install from marketplace and from .vsix procedure a dozen of times with the same results: The debugger shows an "~/.vscode/extensions/eamodio.gitlens-10.0.1/dist/extension.js: Unexpected token (1:35585)." error. Any hints how to resolve this?

**Comment by holtzilya2008** [comment]
Had the same issue. 
My problem was that i had     "git.enabled": false in my settings.json
My Solution: 
change "git.enabled": true 
reload VScode
if still not work: 
Unistalled gitLens, 
Deleted gitLens folder in .vscode/extensions, 
Clear all gitLens related settings from your settings,json
reload VSCode
install gitLens again

**Comment by dsturm** [comment]
Yeaaas, finally I found the breaking point: For me it was the extension [vscode babel transform
](https://marketplace.visualstudio.com/items?itemName=AndyHsu.vscode-babel-transform). After disabling it, gitLens finally works as expected (and missed long time).

**Comment by ShaoMonkSn** [comment]
> Yeaaas, finally I found the breaking point: For me it was the extension [vscode babel transform ](https://marketplace.visualstudio.com/items?itemName=AndyHsu.vscode-babel-transform). After disabling it, gitLens finally works as expected (and missed long time).

Confirmed. Same thing was somehow blocking GitLens for me.

**Comment by cleancoderKG** [comment]
My problem was [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) v1.26.0, just uninstall and reload VSCode.
