### ISSUE TITLE
GitLens doesn't work with Chinese filenames

### ISSUE THREAD

**Issue by Moerj** [eamodio/vscode-gitlens#73]
When I use GitLens plugin on .vue files. It can not call any command.

like this:

![qq20170516-212137 2x](https://cloud.githubusercontent.com/assets/13795438/26108059/e35c5fe2-3a7d-11e7-8342-7c2a123755b6.jpg)
![qq20170516-211504 2x](https://cloud.githubusercontent.com/assets/13795438/26108069/ea06ca4e-3a7d-11e7-828b-258e42faedae.jpg)

But on .js files is work:
![qq20170516-211816 2x](https://cloud.githubusercontent.com/assets/13795438/26108096/0003b366-3a7e-11e7-9be5-5a0e34e9b40b.jpg)

vetur version 0.6.9

**Comment by eamodio** [comment]
@Moerj Can you do the following:

> If you are encountering an issue that says `See output channel for more details`, please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

And then post back with the relevant logs -- GitLens shouldn't care about file types -- just that its in a git repo so very curious to see what is going on.

Thanks!

**Comment by Moerj** [comment]
> getLogForFile('undefined', 'extension-output-#8', undefined, 1, undefined, false)
> git log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- extension-output-#8   cwd='.' 
>   Error: fatal: Not a git repository (or any of the parent directories): .git  Failed with exit code: 128
> isFileUncommitted('/Users/apple/GitHub/bui-m', 'extension-output-#8')
> git ls-files extension-output-#8   cwd='/Users/apple/GitHub/bui-m'
> getLogForFile('undefined', 'extension-output-#8', undefined, 1, undefined, false)
> git log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- extension-output-#8   cwd='.' 
>   Error: fatal: Not a git repository (or any of the parent directories): .git  Failed with exit code: 128
> getBranch('/Users/apple/GitHub/bui-m')
> git branch   cwd='/Users/apple/GitHub/bui-m'
> getLogForFile('undefined', 'extension-output-#8', undefined, 1, undefined, false)
> git log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- extension-output-#8   cwd='.' 
>   Error: fatal: Not a git repository (or any of the parent directories): .git  Failed with exit code: 128
> Keyboard.beginScope 0
> getLogForRepo('/Users/apple/GitHub/bui-m', master, 200)
> getLogForFile('undefined', '/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue', undefined, 1, undefined, false)
> getLogForFile('undefined', '/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue', undefined, 1, undefined, false)
> git log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- 公告.vue   cwd='/Users/apple/GitHub/bui-m/src/views/课程表'
> isFileUncommitted('/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue', '/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue')
> git Error: 
> spawn ENOTDIR ls-files /Users/apple/GitHub/bui-m/src/views/课程表/公告.vue   cwd='/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue' 
>   Error:  spawn ENOTDIR
> git log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- 公告.vue   cwd='/Users/apple/GitHub/bui-m/src/views/课程表'
> getBlameForFile('/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue', '/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue', undefined)
> git log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? -m -n200 master   cwd='/Users/apple/GitHub/bui-m'
> Keyboard.beginScope 1
> KeyboardScope.dispose 2 0
> KeyboardScope.dispose 1 0
> getLogForFile('undefined', '/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue', undefined, 1, undefined, false)
> git log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- 公告.vue   cwd='/Users/apple/GitHub/bui-m/src/views/课程表'
> getBranch('/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue')
> git Error: 
> spawn ENOTDIR branch   cwd='/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue' 
>   Error:  spawn ENOTDIR
> ShowQuickCurrentBranchHistoryCommand Error: 
> spawn ENOTDIR
> getLogForFile('undefined', '/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue', undefined, 1, undefined, false)
> git log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- 公告.vue   cwd='/Users/apple/GitHub/bui-m/src/views/课程表'
> getBranch('/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue')
> git Error: 
> spawn ENOTDIR branch   cwd='/Users/apple/GitHub/bui-m/src/views/课程表/公告.vue' 
>   Error:  spawn ENOTDIR
> ShowQuickCurrentBranchHistoryCommand Error: 
> spawn ENOTDIR

**Comment by Moerj** [comment]
@eamodio 
I found the bug!😈

If the file name is Chinese. Gitlens can not to open.


![qq20170523-103437](https://cloud.githubusercontent.com/assets/13795438/26336191/e0cca13a-3fa3-11e7-9d50-1dab264e612e.jpg)

**Comment by eamodio** [comment]
@Moerj Thanks for digging into it more! I will try to get to the bottom of why that is happening.

**Comment by Moerj** [comment]
![qq20170523-105008](https://cloud.githubusercontent.com/assets/13795438/26336540/b75488b6-3fa5-11e7-9c36-695b80f00f7f.jpg)
![qq20170523-105044](https://cloud.githubusercontent.com/assets/13795438/26336541/b7b4f8fe-3fa5-11e7-8b3e-7e5b010b1ed5.jpg)

Use the English file name to open GitLens. If changed File is Chinese. Can not open too.

**Comment by eamodio** [comment]
@Moerj Is the filename Chinese in git? And on disk?

**Comment by eamodio** [comment]
@Moerj can you try the new beta here: [v3.5.0-beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v3.5.0-beta)? You can find installation instructions here: [Installing Beta Releases](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Beta-Releases)

**Comment by Moerj** [comment]
@eamodio Very good, it is finally normal. Thanks! 

 ![qq20170523-151618](https://cloud.githubusercontent.com/assets/13795438/26342507/f31b9496-3fca-11e7-8a9c-6f7d998963af.jpg)
