### ISSUE TITLE
Clarify search by changes vs. changed lines

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#730]
Just from the title / tooltip of the actions, it's not clear what's the difference between the two:

<img width="378" alt="Screenshot 2019-04-30 at 15 13 24" src="https://user-images.githubusercontent.com/101152/56963976-8559e300-6b5a-11e9-9a12-a66f8eab2fdb.png">

This is what they do:

https://github.com/eamodio/vscode-gitlens/blob/5020fe18f0972f060a247976530b6e91fb97099d/src/git/gitService.ts#L1415-L1420

The harder part is how to explain the difference 😄 [This StackOverflow answer](https://stackoverflow.com/a/1340245/21728) is quite nice.

In GitLens' UI, it would at least be useful to add this:

- or, by changes (`-G`)
- or, by changed lines (`-S`)

Suggestion for respective tooltips:

- "Show commits whose diffs contain the pattern"
- "Show commits that add or delete the pattern"

**Comment by borekb** [comment]
If there would be way to link to that SO answer or any other similar resource that contains an example, that would be very useful as well. I always have to google it 😄.

**Comment by eamodio** [comment]
@borekb I'm very tempted to just remove the `-S` variant as having 2 is quite confusing and the `-G` version is much more likely what people would expect. Also even the git docs say that `-S` is _Intended for the scripter’s use_: https://git-scm.com/docs/git-log#Documentation/git-log.txt--Sltstringgt

Thoughts?

**Comment by borekb** [comment]
I generally agree, however, I just had a situation where I needed to look for instances of a string that was _removed_ from code, so "changed lines" is what I needed to use.

Still, I think you're right and that for the most part, having two very similar options is not worth it. If you could think of a way to hint at the other option, maybe hide it in the "..." menu as an advanced option or something, that would probably be best but if that feels too cumbersome, I'm fine with keeping just the `-G` option.

**Comment by borekb** [comment]
BTW, looking at my original post, is the current code even correct? `GitRepoSearchBy.Changes` uses `'--pickaxe-regex -S` while `GitRepoSearchBy.ChangedLines` uses `-G`; shouldn't it be the other way around?
