### ISSUE TITLE
ChildProcess.exithandler issue while checking out files from previous commits.

### ISSUE THREAD

**Issue by denizobi** [eamodio/vscode-gitlens#731]
Issue seen while checking out some files from previous commit.

- GitLens Version: 9.6.3
  
- VSCode Version: 1.33.1
- OS Version: CentOS 4.17.3-1.el7.elrepo.x86_64

[2019-05-01 15:10:33:784] ChildProcess.exithandler
Error: Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false apply --whitespace=warn -3
error: patch failed: www/db/testdata.json:41
Falling back to three-way merge...
error: patch failed: www/db/testdata.json:41
error: www/db/testdata.json: patch does not apply

[2019-05-01 15:12:07:574] Warning(/usr/bin/git -c core.quotepath=false -c color.ui=false -c log.showSignature=false show e39fb0f07c965fbad7fe00fca47f7364547e42cf:./www/db/appdata.json --):

**Comment by eamodio** [comment]
@denizobi What issue are you seeing in the UI? That error can certainly be expected when trying to apply changes from a previous commit. Also what command are you using? Apply changes or Checkout?

**Comment by denizobi** [comment]
@eamodio: i see that issue in UI extention on VSCode which i wrote versions above. When i saw that issue i was using UI and selected files to checkout. thanks.

**Comment by eamodio** [comment]
@denizobi does this still happen with GitLens 9.7 or later?

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
