### ISSUE TITLE
Gitlens & Liveshare go to definition bug

### ISSUE THREAD

**Issue by SimonSiefke** [eamodio/vscode-gitlens#733]
- GitLens Version: 9.6.3
- VSCode Version: 1.34.0-insider
- OS Version: Ubuntu 18.10

Steps to Reproduce:

1. Have Live Share and Gitlens installed
2. Create a new file
3. Type `vsl:`
4. `vsl:` turns into a link like go to definition
5. When I click the link the error message `Unable to open '': resource is not available.` is shown

**Screenshots**
![Screenshot from 2019-05-03 20-17-31](https://user-images.githubusercontent.com/23744935/57157585-6caf2e80-6de1-11e9-80ed-3875d0e13d66.png)

**Comment by eamodio** [comment]
While I can reproduce this, I can't see/guess at anything that GitLens could be doing to cause this (GitLens doesn't even register any providers that could create links like this. I would suggest opening an issue with Live Share since they register the `vsls` scheme and have deep hooks into vscode.
