### ISSUE TITLE
Show what exactly was updated after pull/merge

### ISSUE THREAD

**Issue by romanfedyshyn** [eamodio/vscode-gitlens#735]
As a user, I want after successful pull/merge request extension automatically open output on the panel and show list of files which are changed.

**Comment by eamodio** [comment]
@romanfedyshyn I've added a new _Recent incoming changes_ node to repositories in the _Repositories_ view. Please try it out and let me know what you think? I'm not too sure on the naming right now, fyi. Also in order for it to show up, make sure you have `gitlens.insiders` set to `true`

[gitlens-9.7.3.vsix.zip](https://github.com/eamodio/vscode-gitlens/files/3171513/gitlens-9.7.3.vsix.zip)

Just remove the `.zip` extension and install it.

**Comment by eamodio** [comment]
@romanfedyshyn FYI, I just released GitLens 9.7.4 which includes a new experimental _Incoming Activity_ node to each repository in the _Repositories_ view (enabled via `"gitlens.insiders": true`) 

- **Incoming Activity** &mdash; lists the recent incoming activity (merges and pulls) to your local repository
    - Provides the activity command, branch (if available), and date

![image](https://user-images.githubusercontent.com/641685/57755952-277fdc00-76c0-11e9-9091-bf62aabd63a5.png)

Please let me know what you think.
