### ISSUE TITLE
git command error on GitLens 9.7.0 (unknown '-M' option)

### ISSUE THREAD

**Issue by zedaav** [eamodio/vscode-gitlens#736]
- GitLens Version: 9.7.0
  
- VSCode Version: 1.33.1
- OS Version: Ubuntu 18.04.2 LTS
- git version: 2.17.1

I'm just getting this behavior from this morning, once GitLens got updated to 9.7.0
I tried with different workspaces, and I'm still getting the error.
When I install back 9.6.3 version, the behavior disappears.

Steps to Reproduce:

1. Just open a file in VS Code, and try to display any Gitlens view (Repository, File History...)
2. I get a notification with the following error:

> Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false -c color.status=false status --porcelain=v2 -M -- Makefile
> error: unknown switch `M'
> usage: git status [<options>] [--] <pathspec>...
> 
>     -v, --verbose         be verbose
>     -s, --short           show status concisely
>     -b, --branch          show branch information
>     --show-stash          show stash information
>     --ahead-behind        compute full ahead/behind values
>     --porcelain[=<version>]
>                           machine-readable output
>     --long                show status in long format (default)
>     -z, --null            terminate entries with NUL
>     -u, --untracked-files[=<mode>]
>                           show untracked files, optional modes: all, normal, no. (Default: all)
>     --ignored[=<mode>]    show ignored files, optional modes: traditional, matching, no. (Default: traditional)
>     --ignore-submodules[=<when>]
>                           ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
>     --column[=<style>]    list untracked files in columns

Output logs:
[output-gitlens.txt](https://github.com/eamodio/vscode-gitlens/files/3146655/output-gitlens.txt)
[output-gitlens-git.txt](https://github.com/eamodio/vscode-gitlens/files/3146652/output-gitlens-git.txt)

**Comment by light8lee** [comment]
Same error with you when I upgrated GitLens to 9.7.0

**Comment by dalisoft** [comment]
Same error

**Comment by shx996** [comment]
Same error! @eamodio

**Comment by yyonggithub** [comment]
Same error

**Comment by AlexanderVasiliev** [comment]
update git to last version helped

**Comment by eamodio** [comment]
Damn, sorry all. It looks like that parameter is only support in Git 2.18 or later. I'll push out a new release shortly to fix this.

**Comment by bracco23** [comment]
`git version 2.17.1.windows.2` here, seeing the same error.

**Comment by eamodio** [comment]
9.7.1 will be in the marketplace very shortly -- sorry for the issue!

**Comment by dalisoft** [comment]
On macOS helped upgrade `git` with Homebrew and `echo 'export PATH="/usr/local/git/bin:/usr/local/sbin:$PATH"' >> ~/.bash_profile` then restart VSCode.
@eamodio thanks for fast reply and fix

**Comment by BraveHead** [comment]
same error

**Comment by zedaav** [comment]
Just installed 9.7.1
Fix confirmed!
Thanks @eamodio :+1:

**Comment by eamodio** [comment]
@BraveHead the same with 9.7.1?

**Comment by BraveHead** [comment]
now  is ok , update 9.7.1

**Comment by BraveHead** [comment]
> @BraveHead the same with 9.7.1?
Update to 9.7.1 is fine.

**Comment by Cheng-Ya** [comment]
same error
