### ISSUE TITLE
Breadcrumbs don't work on file revisions

### ISSUE THREAD

**Issue by iskandarovBakshi** [eamodio/vscode-gitlens#739]
- GitLens Version: 9.7.1
  
- VSCode Version: 1.33.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. breadcrumb crashes on file compare 
![image](https://user-images.githubusercontent.com/15240881/57273927-8cc54300-70aa-11e9-8bd4-240faad0ceb8.png)

**Comment by eamodio** [comment]
Opened https://github.com/microsoft/vscode/issues/73594

**Comment by eamodio** [comment]
Breadcrumb now mostly work for file revisions although I may work on removing the full path in a later GitLens version

**Comment by eb-jorgemaroto** [comment]
I still having an issue related to breadcrumbs when I have GitLens enabled. I have to disable, reopen the file and the breadcrumbs will be working, but at least for me it's not possible to have both breadcrumbs and gitlens working together :(

**Comment by eamodio** [comment]
@eb-jorgemaroto please open a new issue with more details (fill out the template) about what issues you are experiencing with breakcrumbs?
