### ISSUE TITLE
Opening untracked files from "files changed" section fails

### ISSUE THREAD

**Issue by andares** [eamodio/vscode-gitlens#740]
- GitLens Version: 9.7.1
- VSCode Version: 1.33.1
- OS Version: Windows 10 with WSL (ubuntu 16.04)

### vscode version info

```
Version: 1.33.1 (system setup)
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

I've been using gitlens for a long time, it works very well. At last auto upgrade, when I click a new file (not exists in previous repos) in file changed list, will get a error:

```
DiffWithPreviousCommand — getPreviousDiffUris(d:/src/apps/app, d:\src\apps\app\database\migrations\2019_05_05_195442_create_receipts_table.php, undefined)
Error: File has no history
```

It's in previous version has no problem 😂

**Comment by eamodio** [comment]
@andares I'm not sure I understand the steps to reproduce this issue, can you please provide some detailed steps that I can follow to see this issue? Thanks!

**Comment by andares** [comment]
I try to show it with screenshots 😄 

## step 1

I have a repos

![图片](https://user-images.githubusercontent.com/7556505/57564776-72f66980-73e4-11e9-9a07-c68534b74509.png)

## step 2

create a file

![TIM图片20190511120626](https://user-images.githubusercontent.com/7556505/57564817-45f68680-73e5-11e9-94ba-c503ea9f28a4.png)

## step 3

check file by gitlens view

![图片](https://user-images.githubusercontent.com/7556505/57564822-5dce0a80-73e5-11e9-8b3d-ac6d3eaf0bb6.png)

## step 4 

check output info

![TIM图片20190511120930](https://user-images.githubusercontent.com/7556505/57564868-041a1000-73e6-11e9-9d0f-5261686b4243.png)
