### ISSUE TITLE
Add the ability to sort remote and local branches

### ISSUE THREAD

**Issue by federal977** [eamodio/vscode-gitlens#745]
We have hundreds of remote and local branches. After fetching either remote or local branches new branches appear in the end of the corresponding branch list. To find some new branches in the list becomes a stressful and expensive activity because you need to scroll through the old branches down. Could you please add the ability to sort these lists by the creation date. Thus, they will appear in the beginning of the branch list. Thank you.

**Comment by eamodio** [comment]
Unfortunately git doesn't have a notion of a created date for a branch or remote -- and while technically I could find a pseudo-created date by looking at the first commit of the branch/remote it would be prohibitively expensive performance-wise (as I would need to make an individual git call for each branch).

Although I'm curious as to why the new branches would always show up at the end -- as the branches/remotes are currently sorted alphabetically by their name. Are you seeing something different?

**Comment by federal977** [comment]
Correct, branches/remotes are sorted alphabetically. In my case almost all branch names begin with numbers. Thus, they show up at the end of the list. Probably we can add an option to sort the list in a different order (ascending or descending).Therefore, we could see them at the beginning.
<img width="150" alt="sort_branches" src="https://user-images.githubusercontent.com/10773585/57566870-e8107180-73d9-11e9-8208-7a2408e7d297.png">

**Comment by eamodio** [comment]
@federal977 thanks for the info. Adding an option to change the sort order is certainly doable.

**Comment by haojun99** [comment]
"sort by latest commit" seems most useful to me for local branches.
