### ISSUE TITLE
VS code is opening with default git user ID

### ISSUE THREAD

**Issue by vermaaakansha** [eamodio/vscode-gitlens#746]
Hi Team,

my VS code is opening with default git user ID, which is not the required one. 
i want it to be open with my another git user account. I'm not able to find to any option in VS code to switch the user account. 
can anyone help me to rectify my problem?
![git issue](https://user-images.githubusercontent.com/50359777/57758975-840de600-7716-11e9-9713-1a8026c39405.PNG)

**Comment by eamodio** [comment]
VS Code and GitLens use the Git config files to determine the current user. So I would recommend checking your global `.gitconfig` and/or your local `.git/config` files for your user name. See: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

Hope that helps!
