### ISSUE TITLE
Git pull from ssh URL should prompt for password.

### ISSUE THREAD

**Issue by devvpm** [eamodio/vscode-gitlens#748]
When I do git pull using Gitlens from my ssh URL it shows the below error. 

![image](https://user-images.githubusercontent.com/1164077/57977049-91321a00-7a21-11e9-8c6f-b63585e954b5.png)

However, when I do from the terminal it shows that message from the server and asks for the password, 
![image](https://user-images.githubusercontent.com/1164077/57977096-2b469200-7a23-11e9-9ec2-893f64238c9a.png)

So, while doing git pull using git lens it should prompt like this - 

![image](https://user-images.githubusercontent.com/1164077/57977085-e0c51580-7a22-11e9-98ff-e81a8c6e0328.png)

**Comment by eamodio** [comment]
GitLens uses vscode's built-in _pull_ command to perform its pull operations. Are you experiencing the same issue when using the `Git: Pull` command? If so, please open this issue on the vscode repo -- thanks!

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
