### ISSUE TITLE
Remap alt+shift+7 command does not override the default key-map

### ISSUE THREAD

**Issue by guoliang** [eamodio/vscode-gitlens#75]
- GitLens Version: 3.5.1
- VSCode Version: 1.12.2
- OS Version: OS X El Capitan

Steps to Reproduce:

1. Remapping the key-shortcut
```
{
	"key": "ctrl+shift+7",
	"command": "gitlens.showCommitSearch",
	"when": "gitlens:enabled"
}
```

I want to override the default mapping with the above command since the default one is blocking the default keyboard layout I have for `\`. However adding the above mapping will just include another command instead of overwrite the default one.

**Comment by eamodio** [comment]
@guoliang vscode allows for multiple shortcuts for a single command, but it also allows you to specifically remove a shortcut key -- see https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

Basically I think you just need to add the following to remove that key-binding:
```json
{
	"key": "alt+/",
	"command": "-gitlens.showCommitSearch"
}
```
