### ISSUE TITLE
Show line history data only on double click.

### ISSUE THREAD

**Issue by gurrrung** [eamodio/vscode-gitlens#754]
I am here with a feature request, I would love to see if I can disable the line history data, as it really distracts me sometimes even though it has a dull colour, but I don't want the history to completely go, having feature of viewing line history with something like double click only or some keystroke shortcuts would be great.

**Comment by eamodio** [comment]
@gurrrung Unfortunately vscode doesn't provide any way for extensions to trap mouse or keyboard events directly. Although you can turn off the current line blame by default, and then use the _GitLens: Toggle Line Blame Annotations_ command via the palette and/or set a keyboard shortcut for that command. The command id if you need it is `gitlens.toggleLineBlame`

Hope that helps

**Comment by gurrrung** [comment]
Hey, thank for the reply actually I didn't notice that the line blame is on the status bar too, so I just disabled the current line blame and using the status bar blame line, its great.

**Comment by eamodio** [comment]
FYI, you can also control the content/formatting of the statusbar entry too. So you can get it just like the line blame
