### ISSUE TITLE
How to disable all shortcut keys for gitlens?

### ISSUE THREAD

**Issue by zhangkaiyulw** [eamodio/vscode-gitlens#755]
Hi,

This is a quite briiliant and handy package. 
Sometimes the shortcut keys just break my own. It's very confusing. I'd like to disable all default shortcut keys for gitlens. And for the features that I needed, I assign the one that I used to.

How to achieve that easily? Is there any additional implementation required?

Thanks

**Comment by eamodio** [comment]
You can set `"gitlens.keymap": "none"` and GitLens won't register any key bindings -- you can also access this setting via the `GitLens: Open Settings` command:

![image](https://user-images.githubusercontent.com/641685/58577956-a83ced00-8215-11e9-96be-8eaa8f0b7566.png)

Hope that helps!
