### ISSUE TITLE
Unable to install Extension 'eamodio.gitlens-9.8.0' as it is not compatible with Code '1.28.2'.

### ISSUE THREAD

**Issue by yelichi** [eamodio/vscode-gitlens#757]
Unable to install Extension 'eamodio.gitlens-9.8.0' as it is not compatible with Code '1.28.2'.

**Comment by eamodio** [comment]
That is correct, 9.8 requires VS Code 1.31 or later

**Comment by Crazier-qi** [comment]
it's also not compatible in the verison 1.33.0
