### ISSUE TITLE
Revert changes on a hunk sometimes corrupt entire files

### ISSUE THREAD

**Issue by andyneff** [eamodio/vscode-gitlens#759]
Using the gutter to display than revert the changes of a single hunk

- GitLens Version: 9.8.1, but this has been happening for a long time
- VSCode Version: 1.34, but this has been happening for many versions
- OS Version: Fedora 28-Fedora 30 64-bit
- git Version: 2.21.0

Steps to Reproduce:

1. It is hard to reproduce on demand, but once it happens, Ctrl+Z and repeating will cause it to happen again and again. AFAIK Restarting code will cause the problem to go away until next time
1. I'll be editing code, and decide to revert changes on a single hunk. 
1. I click the gutter to display the code lines I want to revert
1. Click the ↶ revert changes button, and then many line of code through out the entire files are "reverted", not just the hunk selected, and in a very chaoitc way. Often many lines are repeated, some lines are old versions, some new, the entire file is wrecked. This has happened to me over a dozen times, on different projects and a few times I didn't catch it before saving which resulted in some very painful manual fixing.

Other notes:

I'm almost always using sub modules.

**Comment by eamodio** [comment]
@andyneff The gutter indicators/UI is provided by VS Code itself, not GitLens (unfortunately VS Code doesn't even expose that type of UI to extensions, so I couldn't provide them in if I wanted too -- which I do in other cases). Please open this issue on the vscode repo. Thanks.
