### ISSUE TITLE
Blame annotations appears in the wrong location

### ISSUE THREAD

**Issue by jing2si** [eamodio/vscode-gitlens#76]
- GitLens Version: 3.5.1
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

Execute command `GitLens: Toggle Blame Annotations`

My **settings.json** 

```json
{
    "editor.fontFamily": "Microsoft YaHei",
    "editor.renderWhitespace": "all"
}
```

![1](https://cloud.githubusercontent.com/assets/2288824/26519285/3b7d11e6-42f1-11e7-89b8-3446d44b6795.gif)

**Comment by eamodio** [comment]
@jing2si does that only happen with that file or others as well?
