### ISSUE TITLE
Sidebar Line History Box stopped working 9.6.0 -> 9.6.1

### ISSUE THREAD

**Issue by kubenstein** [eamodio/vscode-gitlens#764]
- GitLens Version: 9.6.1 -> current
- VSCode Version: 1.35.0
- OS Version: Mac Mojave 10.14.5

Steps to Reproduce:
1. Clone any repo from github (I cloned [mine](https://github.com/kubenstein/reactoricus.jakubniewczas.pl))
2. With default settings the Line History box is always:
```
No line history could be found.
```

Hi! First of all thank you for such an amazing extension!
I just noticed that Line History box is not working in current version. Its not an annotation line history but the box. I reinstalled to previous versions one by one and I tracked that on `9.6.0` it is working but on `9.6.1` is not working any longer. Please take a look at screenshots and debug dumps. Suspicious is that on `9.6.0` `git show :<FILE>` command is executed but on `9.6.1` not..

Cheers!

### Screenshots:
<img width="707" alt="9 6 0 - works" src="https://user-images.githubusercontent.com/74097/59184583-66af2900-8ba9-11e9-8385-1533c7f4b83e.png">
<img width="711" alt="9 6 1  - doesnt work" src="https://user-images.githubusercontent.com/74097/59184584-66af2900-8ba9-11e9-93a5-cadd20152ca2.png">

### Debug Dumps:

```
9.6.0
Looking for git in: /usr/local/bin/git
Using git 2.22.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /Users/kuba/projects/reactoricus.jakubniewczas.pl
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git check-ignore -v -z --stdin
> git show :src/frontend/lib/deep-copy.js

9.6.1
Looking for git in: /usr/local/bin/git
Using git 2.22.0 from /usr/local/bin/git
> git rev-parse --show-toplevel
> git config --get commit.template
Open repository: /Users/kuba/projects/reactoricus.jakubniewczas.pl
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git show :src/frontend/lib/deep-copy.js
> git check-ignore -v -z --stdin

```

**Comment by eamodio** [comment]
@kubenstein You are only seeing this behavior when you have the last line in the file selected correct? If so, and if the last line in your file is just a newline, then this is expected behavior because git doesn't treat that last line as an actual line at all. It was technically a bug in 9.60 that was causing it to show up.

**Comment by kubenstein** [comment]
@eamodio screenshots are quite unfortunate because of new line indeed, sorry for that. However if I hover over other lines the box is still empty.
Take a look at this screenshot, its from other file, because this file has more commits. We can see that file history as well as inline line history work but not the sidebar box:

<img width="1060" alt="9 6 1" src="https://user-images.githubusercontent.com/74097/59235186-06f96200-8c2b-11e9-83d0-bee262393ae1.png">

**Comment by eamodio** [comment]
Hrm, can you send me full logs? I can't reproduce this:
![image](https://user-images.githubusercontent.com/641685/59239064-4e053a00-8bce-11e9-803d-1086a27f55a2.png)

**Comment by kubenstein** [comment]
Hi, I noticed a new version (9.8.2) was released yesterday and it fixes the issue!
so I think this issue can be closed.

thank you very much!
