### ISSUE TITLE
Repositories/Branches gets stuck and cannot checkout

### ISSUE THREAD

**Issue by gatopeich** [eamodio/vscode-gitlens#765]
Issue Type: <b>Bug</b>

1. Checkout "master", then "branch2" manually
2. Right-click on GitLens Repositories/Branches/master to check it out 
3. Do same with Repositories/Branches/branch2
4. Repeat a few times, until the non-checked-out branch incorrectly displays the tick mark, and no "Checkout" option shows in its pop-up menu.
5. Log "Already on 'master'" when I try to check-out again the one that is already checked-out via pop-up menu.

Extension version: 9.8.2
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 4.15.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3077)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|31.31GB (4.20GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

GitLens log:

> [2019-06-11 08:48:55:273] Warning(/usr/bin/git -c core.quotepath=false -c color.ui=false checkout QA --): Switched to branch 'QA'
> [2019-06-11 08:48:59:472] Warning(/usr/bin/git -c core.quotepath=false -c color.ui=false checkout master --): Switched to branch 'master'
> [2019-06-11 16:15:44:470] Warning(/usr/bin/git -c core.quotepath=false -c color.ui=false checkout master --): Already on 'master'

**Comment by eamodio** [comment]
@gatopeich does this still happen in GitLens 10?

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Comment by gatopeich** [comment]
Sorry for the late update but it was indeed fixed on GitLens 10.
Thanks!
