### ISSUE TITLE
Show commit search shortcut conflicts with backslash on french MacOS keyboards

### ISSUE THREAD

**Issue by maelvalais** [eamodio/vscode-gitlens#77]
Using a french macos keyboard layout, the default shortcut for `gitlens.showCommitSearch` is <kbd>shift</kbd><kbd>option</kbd><kbd>:</kbd>, which is conflicting the the way we type `\` (backslash).

My workaround: I just disable the shortcut.

- GitLens Version: [3.5.1] - 2017-05-25
- VSCode Version: Version 1.12.2 (1.12.2)
- OS Version: MacOS 10.12.4

**Comment by eamodio** [comment]
@maelvalais Hrm, I'm not sure what to do on this one. I quite like the `alt+/` shortcut key and it seems no matter what I pick it conflicts with something :(. At least vscode makes it easy to remove a shortcut key.

**Comment by maelvalais** [comment]
Maybe it could be on vscode's side to warn the user when such conflicts appear, and maybe show him all the conflicting ones in the shortcut view. I'll propose this feature to the vscode's team.

Thanks anyway for your kind and helpful answer!

**Comment by eamodio** [comment]
@maelvalais if you open a vscode issue, would you mind either posting the link back here -- or linking it from the vscode issue?

**Comment by jjabba** [comment]
I'm having the same problem using a Swedish keyboard layout. Backslash in this layout is typed by hitting alt-shift-7 which I guess is the same as git-lens's "search-by-message" shorthand. Looking for a way to change or add an alternative when Swedish keyboard is used.

**Comment by Aenoa** [comment]
issue still existing for FR keyboards, as of version 8.0.0

**Comment by eamodio** [comment]
You can use `"gitlens.keymap": "chorded"` (or `none`) to switch the set of keyboard shortcuts GitLens binds. This setting can also be tweaked using the new settings editor in GitLens 8 -- run `GitLens: Open Settings` from the Command Palette.
