### ISSUE TITLE
Compare branch order not working

### ISSUE THREAD

**Issue by obambrough** [eamodio/vscode-gitlens#773]
Comparing one branch against another uses the three-dot symmetric difference between the two branches (showing all changes between the two branches.) I assume this is a bug because there is a button on the comparison's entry in the compare tree with at tool-tip of 'Swap Comparison'. After pressing it the UI shows the branch order changed but the list of commits is still the same (as its using three-dot difference, not two-dot difference between the branches.)

If this isn't a bug is there a way to see the changes that are in one branch but not in the other (which you'd get with two-dot range difference)? Am I misunderstanding the purpose of the 'Swap Comparison' button?

GitLens (Git) log
`git log --name-status --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -M -m -n200 fix/poll_after_refresh...origin/develop --`

...after pressing the swap order button

git log --name-status --`format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -M -m -n200 origin/develop...fix/poll_after_refresh --`

- GitLens Version: 9.8.2
- VSCode Version: 1.35.1
- OS Version: Mac OS 10.14.5

Steps to Reproduce:

1. Use GitLens to compare any two branches and view the list of commits
2. Press the 'Swap Comparison' button and see the list of commits is identical

**Comment by eamodio** [comment]
The _Swap Comparison_ command just switches the order of the compare, not the type of compare. To switch to use two-dot comparisons set the following setting `"gitlens.advanced.useSymmetricDifferenceNotation": false`

See here: https://github.com/eamodio/vscode-gitlens#advanced-settings-

Hope that helps!

**Comment by obambrough** [comment]
Fantastic, thanks for pointing that setting out (I should've found that!). It would be really handy to have that setting be togglable from the search tree as it is very relevant there, especially since the 'swap comparison' button doesn't really make a difference when its configured to use symmetric difference (which I assume is the default.) Using that setting did work and the 'swap comparison' button does work as expected so closing this issue.

**Comment by eamodio** [comment]
@obambrough in the next release, I'll add buttons to switch between two-dot and three-dot compares (and the setting will just control the default)
