### ISSUE TITLE
Unable to open on remote for a Bitbucket Server

### ISSUE THREAD

**Issue by bracco23** [eamodio/vscode-gitlens#775]
I have a repo on a Bitbucker Server remote that I am unable to use with the "Open in remote" feature.

I have tracked the problem down to the fact that no _https_ is available on our server, we have to access using an unsecured _http_ connection, while, taking a look at https://github.com/eamodio/vscode-gitlens/blob/1d2c2ce5f712c92485cabaea0516b33fa5bb097b/src/git/remotes/bitbucket-server.ts#L15 I see that the protocol is hardcoded as _https_. Since a **protocol** setting is available, it would be nice to use that as protocol, so that it can be configured in each case.

Apart from the protocol, everything else is correct, in the sense that if I manually change the protocol in the resulting URL it works.

**Comment by eamodio** [comment]
This will be fixed as part of https://github.com/eamodio/vscode-gitlens/issues/692 which is fixed but not yet released (will be coming soon)
