### ISSUE TITLE
Configurable fetch command to allow "git fetch --prune origin"

### ISSUE THREAD

**Issue by BillDenton** [eamodio/vscode-gitlens#778]
I would like to be able to configure the fetch command allow pruning of remote (origin) branches that have been removed from the remote repo. So instead of doing
git fetch
it would do
git fetch --prune origin

**Comment by eamodio** [comment]
@BillDenton would just setting Git's config be enough here? See https://stackoverflow.com/a/18718936

**Comment by eamodio** [comment]
@BillDenton In GitLens v9.9, you can now use the new _Git Commands_ command from the palette and pick fetch and prune. Hopefully that provides what you need.
