### ISSUE TITLE
Git Infomation Layout BUG

### ISSUE THREAD

**Issue by cydiacen** [eamodio/vscode-gitlens#779]
At first I thought it was a vscode BUG , but they think it's cause 3rd-part extension。
https://github.com/microsoft/vscode/issues/76650#event-2461930053

- GitLens Version:9.8.2
  
- VSCode Version:1.36.0
- OS Version:macOS Mojave 10.14.5

Steps to Reproduce:

1.![Xnip2019-07-05_10-02-32](https://user-images.githubusercontent.com/11609222/60706165-72d59e80-9f3b-11e9-81be-93f18714c7aa.jpg)

**Comment by eamodio** [comment]
Unfortunately this is a vscode bug, see https://github.com/microsoft/vscode/issues/71745
