### ISSUE TITLE
No option to hide git history per each line of code

### ISSUE THREAD

**Issue by ShashankaNataraj** [eamodio/vscode-gitlens#78]
Absolutely love this extension but didn't find a way to toggle this behaviour off.

- GitLens Version:3.5.1
- VSCode Version:1.12.2 
- OS Version:OSX Sierra

Steps to Reproduce:

1. Click on any line in source code
2. <img width="437" alt="screen shot 2017-05-31 at 8 26 04 am" src="https://cloud.githubusercontent.com/assets/650317/26613966/11b6acea-45db-11e7-9db6-b4dee1ba1863.png">
3. No way of toggling this off, "Toggle git code lens" only toggles off the block level history

**Comment by eamodio** [comment]
@ShashankaNataraj you can turn it off by setting `"gitlens.blame.annotation.activeLine": "off"`. Hope that helps.

**Comment by ShashankaNataraj** [comment]
@eamodio Thanks! That worked! But can it be activated through the omnibox?

**Comment by eamodio** [comment]
@ShashankaNataraj currently no -- you can toggle the whole-file blame on and off, but not just for the current line

**Comment by CoenraadS** [comment]
I would just like to say I experienced this also, I think many users will be confused like we were, please consider adding a toggle for active line.

**Comment by eamodio** [comment]
@ShashankaNataraj @CoenraadS FYI, the latest [GitLens v4.0-alpha](https://github.com/eamodio/vscode-gitlens/releases/tag/v4.0.0-alpha.2) is available and adds a command to toggle the current line annotation on and off. Check it out. Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release

**Comment by ShashankaNataraj** [comment]
@eamodio You must be the most responsive open source dev out there! You are awesome!

**Comment by MrPeker** [comment]
I toggled off this feature adding this line to settings.json `"gitlens.currentLine.enabled": false`

**Comment by Kattman5** [comment]
I am still working on getting Visual Studio and Android Studio to work properly. It looks like new computer time. Please be patient with me. Thanks guys.
