### ISSUE TITLE
Line blame annotations not working when vscode root is home dir and .gnupg dir is inaccessible

### ISSUE THREAD

**Issue by forrcaho** [eamodio/vscode-gitlens#789]
I've reproduced this issue both on my debian linux computer, and using Remote - SSH to connect to an Ubuntu EC2 instance.

If I have a `.gnupg` folder in your home dir, and it's owned by root, and only accessible to root, and I open vscode with your home dir as vscode's root dir (e.g. invoking `code .` from my home dir on the command line), then when I open a file inside a git working dir, I do not see line blame annotations (and  I think Gitlens is completely broken, but did not check for other functionality).

In vscode's output window when "Log (Window)" is selected from the dropdown list, I see this error:
```
[2019-07-13 23:44:56.327] [renderer1] [error] spawn git EACCES: Error: spawn git EACCES
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
[2019-07-13 23:44:56.814] [renderer1] [error] EACCES: permission denied, scandir '/home/forrcaho/.gnupg': Error: EACCES: permission denied, scandir '/home/forrcaho/.gnupg'
```
It does not appear that vscode's native git functionality is affected, although I could be mistaken about that. It requires both the inaccessible ~/.gnupg dir and that the home dir is vscode's root to make this bug occur, if only one is present Gitlens will function normally.

**Comment by eamodio** [comment]
@forrcaho could you please verify if the native git functionality works?

**Comment by forrcaho** [comment]
The red, blue, and green marks in the gutter indicating the changes made since the previous commit still show up as expected, so I guess that confirms the native git functionality works. Sorry for being vague about it before.

**Comment by eamodio** [comment]
Do commands like fetch/pull/etc work?

**Comment by forrcaho** [comment]
Yes. I verified commit, push, and fetch all work.

**Comment by eamodio** [comment]
@forrcaho Can you try the following build to see if it helps? If not please provide logs.

[gitlens-9.9.2-beta2.vsix.zip](https://github.com/eamodio/vscode-gitlens/files/3452558/gitlens-9.9.2-beta2.vsix.zip)

Just remove the .zip extension and install it.

**Comment by forrcaho** [comment]
Confirmed, this vsix fixes the issue for me! Woot!
