### ISSUE TITLE
Application insights package breaks GitLens + eslint

### ISSUE THREAD

**Issue by GollyJer** [eamodio/vscode-gitlens#79]
Hi... I wanted to let you know about an issue I ran into with Gitlens breaking other extensions.
You can read the details and fix [here](https://github.com/esbenp/prettier-vscode/issues/107
).

Thanks!
Jeremy

**Comment by eamodio** [comment]
@GollyJer thanks for the info. Arg -- the damn application-insights package is causing this. I'll see what can be done or I'll just have to nuke it.

**Comment by eamodio** [comment]
@GollyJer can you try the GitLens beta here: [v3.6.0-beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v3.6.0-beta) to see if it resolves the issue for you? You can find installation instructions here: [Installing Beta Releases](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Beta-Releases)

**Comment by eamodio** [comment]
@GollyJer awesome -- thanks!

**Comment by eamodio** [comment]
Fixed in v3.6.0
