### ISSUE TITLE
Invisible git icons when running vscode from WSL with GitLens extension enabled

### ISSUE THREAD

**Issue by Bazalia** [eamodio/vscode-gitlens#790]
Issue Type: <b>Bug</b>

I have GitLens extension installed locally and on WSL, and I also have Remote Development extension pack installed. When I open code normally everything is fine. When I open code from WSL with GitLens disabled everything is fine too. But when I open code from WSL and GitLens is enabled some icons become invisible. They are clickable but invisible. These icons are the GitLens icon on the left and the icons inside the source control window (like stage changes and commit).

Extension version: 9.8.5
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (4.63GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/c/Users/Omar/Desktop/rimads/knowledge_repository --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|7.88GB (4.63GB free)|
|VM|0%|
</details>

**Comment by eamodio** [comment]
@Bazalia I am seeing the same behavior with Remote WSL, but I see it even if I don't have GitLens install in the remote at all. I think this an instance of this issue: https://github.com/microsoft/vscode-remote-release/issues/687

**Comment by offero** [comment]
Same here. Example below:

![image](https://user-images.githubusercontent.com/4681330/63091606-dedcf680-bf2c-11e9-82b7-bcb886deed2d.png)

**Comment by mithunshanbhag** [comment]
This issue looks related to https://github.com/microsoft/vscode-remote-release/issues/687

**Comment by eamodio** [comment]
This should be resolved now that the upstream issue has been fixed.
