### ISSUE TITLE
editor rule doesn't move when the git blame gutter is opened

### ISSUE THREAD

**Issue by joachim-n** [eamodio/vscode-gitlens#793]
- GitLens Version:  9.8.5
- VSCode Version: 1.36.1
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. have the git blame gutter off by default.
2. Open a file
3. Use the command palette to show the git blame gutter

The editor ruler shown at 80 characters doesn't move with the file text.

**Comment by eamodio** [comment]
Unfortunately, this is caused by an issue in vscode itself: https://github.com/microsoft/vscode/issues/39165
