### ISSUE TITLE
Can't get back to settings page easily

### ISSUE THREAD

**Issue by joachim-n** [eamodio/vscode-gitlens#794]
- GitLens Version: 9.8.5
- VSCode Version: 1.36.1
-  OS Version: OS X 10.11.6

Steps to Reproduce:

1. Install git lens
2. Nice settings page is available. This is great!
3. Want to change some settings later
4. Go to user settings. Not so clear.
5. Try to find the settings page I had before. Open 'Git Lens: welcome' from the command palette
6. Open the configure git lens page. 

All the settings are their default values, not the values I configured the first time.

**Comment by eamodio** [comment]
You can use `GitLens: Open Settings` to get directly to that page. Unfortunately the native Settings UI doesn't provide any good way for me to tell users to go to the GitLens Settings UI, nor does it provide a nice experience. I've opened this issue: https://github.com/microsoft/vscode/issues/70589 (please upvote it)

As for the issue about the values being default -- that sounds like a bug, and I can't seem to reproduce it. Is this still happening?

**Comment by joachim-n** [comment]
I've just tried again and it's fine now.

I've upvoted that issue. Thanks for the really quick response!!

**Comment by eamodio** [comment]
In GitLens v10 there will be a note in the Settings UI directing users to _GitLens: Open Settings_ for a richer, interactive experience

**Comment by hacknug** [comment]
@eamodio why not add an icon on the top right corner of the GitLens sidebar like the Debug sidebar does?
