### ISSUE TITLE
Commit quick access icons replaced with open file actions in File History View

### ISSUE THREAD

**Issue by sseremelis** [eamodio/vscode-gitlens#795]
Issue Type: <b>Bug</b>

In File History view, the inline toolbar that is displayed for each commit shows the icons for Open File and Open File on Remote. However I think that the icons for Compare with HEAD, Copy Commit ID to Clipboard and Open Commit on Remote used to be there, because I was used to using them from the File History view.

Is this the expected behaviour? Because I was using these quick actions all the time and it feels really weird that they are not there.

![Screenshot 2019-07-18 at 3 21 12 PM](https://user-images.githubusercontent.com/6206625/61456922-ec27b500-a96f-11e9-938c-3088795f3078.png)

Extension version: 9.8.5
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

**Comment by eamodio** [comment]
@sseremelis Good catch -- this was an unintentional regression
