### ISSUE TITLE
Switch to three-dot comparison doesn't change the files changed list

### ISSUE THREAD

**Issue by haojun99** [eamodio/vscode-gitlens#799]
When doing a comparison between two branches, the option to switch between 3-dot or 2 dot comparison affects the result of commits, but not the result of files changed.
From the log, it looks like it is already running "git diff A B" which is the same as  "git diff A..B"

**Comment by eamodio** [comment]
This was fixed in 9.9.1. Do you still see the issue there?

**Comment by haojun99** [comment]
yes, it works in 9.9.1. Thanks!

**Comment by jankap** [comment]
Has the three-dot notation gone in v10?
