### ISSUE TITLE
Invalid Object Name '00000000'

### ISSUE THREAD

**Issue by con-ssc** [eamodio/vscode-gitlens#8]
It seems that now all files are detected as not yet commited, hence, when I try to get the blame history I end up with the following
![image](https://cloud.githubusercontent.com/assets/8189808/18704862/0157c89e-7fec-11e6-99d3-80b2878df272.png)

**Comment by eamodio** [comment]
@con-ssc Can you provide any more details? I'm not seeing any issues. What OS are you on? Is this repo publicly accessible?

**Comment by con-ssc** [comment]
Sure. It is a private gitlab server.
```
node: v6.6.0
npm: 3.10.8
VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
OS Version: Windows_NT ia32 10.0.10586
```

**Comment by con-ssc** [comment]
gitlab was working the first time I tried it a while ago.

**Comment by eamodio** [comment]
@con-ssc does the blame history still show up and work? I can't seem to get this to happen.

**Comment by con-ssc** [comment]
Now it seems to work, maybe git was locked? before all hashes where 000000 with anonymous

**Comment by eamodio** [comment]
@con-ssc hrm -- not sure. I've pushed v0.5.3 that should hopefully help more, but if it happens again let me know.
