### ISSUE TITLE
Line with link => lens will also be underlined

### ISSUE THREAD

**Issue by jens1o** [eamodio/vscode-gitlens#80]
- GitLens Version: v3.6.0
- VSCode Version: 1.12.2
- OS Version: Win10 Anniversary Update

Steps to Reproduce:

1. Open a file
2. Write down `http://imperavi.com/kube/`
3. Commit it.
4. Put your cursor on the link
5. Get this:
![image](https://cloud.githubusercontent.com/assets/11234139/26819611/f84710b4-4a9f-11e7-8ac6-a4416a1a3efd.png)

**Comment by eamodio** [comment]
@jens1o I think this is very similar to https://github.com/Microsoft/vscode/issues/22018 -- Could you possibly open an issue for vscode? As far as I'm aware there is nothing I can do to stop this behavior -- I've tried forcing `textDecoration` to `none` and still no change..

**Comment by jens1o** [comment]
Okay, thanks, should I leave it open?

**Comment by eamodio** [comment]
@jens1o let's leave it open for now -- if they don't have a work-around for GitLens, then we can close this one.

**Comment by jens1o** [comment]
Yeah, it is not fixed in last insider:

![image](https://user-images.githubusercontent.com/11234139/26837430-b095d2bc-4add-11e7-8638-bbf787ef4c74.png)

**Comment by eamodio** [comment]
☝️ don't get excited -- it doesn't work, but I wanted to leave the `text-decoration` resets in :)

**Comment by jens1o** [comment]
Okay :)
