### ISSUE TITLE
Able to select removed text during diff-view of a line

### ISSUE THREAD

**Issue by spajas** [eamodio/vscode-gitlens#801]
First of all, I want to say I really like GitLens. Actually, it is awesome!

However, I really hope it would be possible to do the following:
1) Modify a piece of text/code in a committed file
2) When GitLens indicates a difference for that line next to the line# in VScode, click on that indication
3) VSCode will show the original text and the modified text using different colors
4) The modified text is selectable and can be copied
5) The original unmodified text however, is not selectable nor it can be copied (as far as I know). 

It would be really great of 5) would be possible. Sometimes I want to re-use/revert part of the removed code and that is not possible now (as far as I know).

**Comment by eamodio** [comment]
Unfortunately the diff view is provided by vscode itself and I can't control if the text can be selected or not. See this issue: https://github.com/microsoft/vscode/issues/8226
