### ISSUE TITLE
Unable to pull a repository

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#807]
Originally opened here: https://github.com/eamodio/vscode-gitlens/issues/649#issue-407826787

![image](https://user-images.githubusercontent.com/12263288/52432563-b6d18e00-2ad8-11e9-89ef-3e1f4fe581a9.png)

@gbritton1 I've move your issue here, since it got taken over by an unrelated issue.

**Comment by eamodio** [comment]
@gbritton1 can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by gbritton1** [comment]
No longer a problem
