### ISSUE TITLE
Broken Sponsors

### ISSUE THREAD

**Issue by builtbyproxy** [eamodio/vscode-gitlens#808]
# I am unable to sponsor you through the github feature

**Sorry** this doesn't fit the format at all. 
Your FUNDING.yml is broken:
![image](https://user-images.githubusercontent.com/16897508/62186285-15513800-b3a9-11e9-8427-be67e158fe8a.png)

**Comment by eamodio** [comment]
Yeah, unfortunately GitHub sponsors still has a waitlist (and so far I haven't gotten in). Please feel free to nominate me though: https://github.co/2IHdeOw 😄

**Comment by builtbyproxy** [comment]
Done!
This is surely one of the most popular VSCode plugins? 
You should put that link in your readme at the top
I can do a PR for it if you dont have the time
