### ISSUE TITLE
Current line annotation feels too sticky

### ISSUE THREAD

**Issue by CoenraadS** [eamodio/vscode-gitlens#81]
- GitLens Version: 4.0.0-alpha.2
- VSCode Version: 1.13.0 insider
- OS Version: Windows 10

Hello, when moving up and down lines in a file, the active line lens stays at its position until a new lens is created. I would like to request that the lens immediately disappears when the active line changes as a small QOL change (I understand that the new lens is still debounced, and I'm not requesting to make the new lens appear faster, just to make it dissapear faster).

I am requesting this just because I rely on then horizontal lines VSCode uses to show my current line position, and having other horizontal elements not on my active line increases the overal noise of the workflow.

**Comment by eamodio** [comment]
Ah, this is a great suggestion -- I will take a look into it. Thanks!

**Comment by eamodio** [comment]
@CoenraadS the latest [GitLens v4.0-beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v4.0.0-beta) is available and should fix this issue -- let me know what you think. Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release

**Comment by CoenraadS** [comment]
Thanks, works great
