### ISSUE TITLE
Regression in 9.9.2: Clicking changed file in Repository Browser opens diff view between WorkingTree <-> WorkingTree, not index

### ISSUE THREAD

**Issue by dsmythe** [eamodio/vscode-gitlens#812]
I just noticed this today, I'm assuming it's from a recent update.

The previous behavior was that when you clicked a modified file in the "N files changed" dropdown under the checked out repository in the Repository browser, it opened a diff view of those unstaged changes ( which I believe is comparing the working tree to the index ). This allowed you to select ranges to stage or view what was being changed as you staged files for commit.

Now, it opens a diff view between the working tree and the working tree, which as you guessed, does not display any changes because it's comparing the same things.

Tried to find configuration settings that would modify the behavior but could not. I asssume it's the result of a recent change in the last week or so as there are similar bugs resolved that presumably hit the same area of code.

Thanks!

- GitLens Version: 9.9.2
- VSCode Version: 1.36.1 (1.36.1)
- OS Version: Mac Mojave 10.14.3

Steps to Reproduce:

1. Open any repository in the Repository browser of GitLens
2. Modify any tracked file
3. Click the file listed under the changed files
4. Observe the diff view open but comparing WorkingTree <-> WorkingTree

![image](https://user-images.githubusercontent.com/9650694/62419230-41321f00-b630-11e9-945c-6cb73d0ee731.png)

**Comment by ajaypanyala** [comment]
I see the same issue after upgrading to Gitlens 9.9.2

- VSCode Version: 1.36.0-insiders and 1.37.0-insiders
- OS Version: Debian 9

**Comment by Jadson666** [comment]
I see the same issue today
when I click '3 files changed', I expect to see what I changed for every line.
but for now, the unstaged files just compare with the unstaged files. therefore it shows nothing different
I guess is because of the newest update

VSCode Version: 1.36.1

**Comment by nztraveler** [comment]
I see the same issue recently.

**Comment by eamodio** [comment]
@dsmythe @ajaypanyala @Jadson666 @nztraveler Sorry for the inconvenience -- this should be resolved in v9.9.3. Thanks for the report!

**Comment by dsmythe** [comment]
Yep, can confirm 9.9.3 resolved the issue now, Thanks @eamodio!
