### ISSUE TITLE
Is it possible to hide tabs like "Over a month ago"

### ISSUE THREAD

**Issue by kanlukasz** [eamodio/vscode-gitlens#816]
Is it possible to hide tabs like "Over a month ago" ?
I talk about:
![obraz](https://user-images.githubusercontent.com/30685349/62629202-04ff0700-b92d-11e9-9051-86a587ba639c.png)
![obraz](https://user-images.githubusercontent.com/30685349/62629208-09c3bb00-b92d-11e9-84c4-cf756720b123.png)
I don't need it. It distracts me

**Comment by eamodio** [comment]
@kanlukasz You can set `"gitlens.views.showRelativeDateMarkers": false,` and those will be turned off
