### ISSUE TITLE
Feedback on vscode's Webview.toWebviewResource API proposal

### ISSUE THREAD

**Issue by mjbvz** [eamodio/vscode-gitlens#819]
## Overview
VS Code 1.37 added a proposed api to help webviews create uris for local resources: https://github.com/microsoft/vscode/blob/192e15b613dd4f4dab9c735b7556e175580c6011/src/vs/vscode.proposed.d.ts#L1166

The main addition is a `toWebviewResource` method property on webviews that translates a local file uri into a webview uri (i.e. one that uses the special `vscode-resource:` scheme). This api is being added primarily to support running VS Code on the web where the existing `vscode-resource:` scheme will not work

## Request
As a popular user of the VS Code webview API, we'd appreciate your feedback on this api proposal. Does it work as advertised? Does the documentation for it make sense? Is it missing any functionality? Feel free to leave your feedback on this issue or on https://github.com/microsoft/vscode/issues/79242

You can try out the proposed api in VS Code 1.38 insiders by following [these instructions](https://code.visualstudio.com/api/advanced-topics/using-proposed-api). Please let me know if you have any questions about testing it out

*PS: There are no plans at the moment to remove the `vscode-resource:` scheme so your extension should continue to work on desktop VS Code even if it does not adopt this new API*

**Comment by eamodio** [comment]
@mjbvz Sorry for the delay -- this looks good to me, and should be vary simple to adopt once it is in stable.
