### ISSUE TITLE
Icons not shown properly

### ISSUE THREAD

**Issue by jens1o** [eamodio/vscode-gitlens#82]
- GitLens Version: 3.6.0
- VSCode Version: 
![image](https://user-images.githubusercontent.com/11234139/26887723-12c07480-4ba9-11e7-8da1-0eede052304e.png)
- OS Version: Windows 10 Anniversary

Steps to Reproduce:

1. Open up the file history with `Alt + H`
2. Select any commit
![image](https://user-images.githubusercontent.com/11234139/26887754-28d5c874-4ba9-11e7-8a10-3bb65985ac0b.png)
3. Type `o`
4. See this:
![image](https://user-images.githubusercontent.com/11234139/26887787-40cd3de0-4ba9-11e7-9129-c682e9424336.png)

**Comment by eamodio** [comment]
@jens1o sadly this is a reported vscode issue: https://github.com/Microsoft/vscode/issues/21243

**Comment by jens1o** [comment]
ah, sorry. Shall I leave it open? I only searched here...

**Comment by eamodio** [comment]
@jens1o Nah, this one is a bug that I can't do anything about (other than getting rid of the icons altogether -- which I'm not going to do). So I will close it. Thanks!
