### ISSUE TITLE
Wrong comparison order in the Compare view when using Compare [HEAD|Working Tree] With comands

### ISSUE THREAD

**Issue by vabc3** [eamodio/vscode-gitlens#821]
Is there an option to keep the old behavior.

For example, I do a change in branch 'my1', and then use the comparion tool to compare with 'origin/my1'.

For old behavior, the diff is origin/my1..my1, which makes more sense. This shows what I'm going to push to remote.

For new behavior, the diff is my1..origin/my1, which is not what I expect

**Comment by eamodio** [comment]
@vabc3 When you say comparison tool -- what do you mean? Creating a new compare from the _Compare_ view? The Branch comparison node in the _Repositories_ view? Selecting a branch and choosing _Select for Compare_ and then selecting another and choosing _Compare with Selected_?

**Comment by vabc3** [comment]
It is F1->
(old version)'GitLens: Compare Working Tree With Branch Or Tag'
(new version)'GitLens: Compare Working Tree With'
