### ISSUE TITLE
Ability to view history of a folder

### ISSUE THREAD

**Issue by benmarch** [eamodio/vscode-gitlens#824]
It is often helpful to be able to view the history of a particular folder. This is especially true for monorepo architectures where a folder could represent a standalone package or module. 

It would be great to be able to right click on a folder in the file explorer and select "View History of Folder". This would be similar behavior to JetBrains products such as IntelliJ and WebStorm.

**Comment by Delapouite** [comment]
Can this issue be closed with the recent addition of `Open Folder History` feature in the latest (11.4.0) release?

**Comment by benmarch** [comment]
Ah sweet! Yeah it looks good to me, thank you!

**Comment by eamodio** [comment]
@Delapouite Thanks for calling that out -- closing this as it is in the 11.4 release.
