### ISSUE TITLE
Deleting stash doesn't remove the stash from the list - have to refresh

### ISSUE THREAD

**Issue by admehta01** [eamodio/vscode-gitlens#826]
- GitLens Version: 9.9.3
- VSCode Version: 1.37.1
- OS: Windows 10

Steps to Reproduce:

1. Stash something
2. In GitLens right click -> Delete Stashed Changes
The list doesn't update. If you try to delete again, it deletes another stash. Potentially disastrous bug.

If you refresh the whole view, then it correctly disappears from the view.

**Comment by eamodio** [comment]
@admehta01 I can't reproduce this behavior. Do you have automatic refresh of the _Repositories_ view turned off?

**Comment by admehta01** [comment]
Here are my settings:

![image](https://user-images.githubusercontent.com/1946614/63663616-f5c6e880-c777-11e9-8100-0c227440efb0.png)

**Comment by eamodio** [comment]
@admehta01 Hrm, can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log lines from the *GitLens* channel. Thanks!

**Comment by admehta01** [comment]
```
[2019-08-26 03:41:21:751] [1a4c] GitService.stashDelete — e=c:/Github/app, t=stash@{0}
[2019-08-26 03:41:24:292] [c:/Github/app] git stash drop stash@{0} • 2541 ms 
[2019-08-26 03:41:24:293] [1a4c] GitService.stashDelete completed • 2541 ms
```

**Comment by eamodio** [comment]
@admehta01 I need the logs that happen after the `stashDelete` call too -- I want to look at how the view responds (or doesn't) to the repository change

**Comment by admehta01** [comment]
Hmm, those are the only lines I see.

**Comment by eamodio** [comment]
If you click on the `...` menu of the _Repositories_ view do you see this:
![image](https://user-images.githubusercontent.com/641685/63665082-a85a7380-c797-11e9-887b-25f257dbd138.png)

Does it say enable or disable?

**Comment by ShinaZin** [comment]
Because of this error, deleting changes from the Stashes list can be very dangerous. May result in erroneous deletion of changes. :disappointed:

**Comment by eamodio** [comment]
@admehta01 @ShinaZin I can't seem to reproduce this for the life of me. Is there any other specific details that you can provide? OS, using VS Code remote? Remote file system? File share? etc?

**Comment by ShinaZin** [comment]
```
VS Code
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601
GitLense v10.0.1
```
Using filesystem: NTFS
Repo `.git/config` file:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
	autocrlf = false
[remote "origin"]
	url = deleted
	fetch = deleted
[branch "master"]
	remote = origin
	merge = refs/heads/master
[gui]
	wmstate = normal
	geometry = 1005x515+358+184 175 196
```

![StashError](https://user-images.githubusercontent.com/18055854/65489107-1f784a00-deb3-11e9-884b-522e30918f76.gif)

**Comment by eamodio** [comment]
Ah! Now I see. Thank you @ShinaZin for the full screenshot! So the basic issue is that the repository it outside of the opened workspace -- so vscode (and in turn) GitLens is unable to get file system change events for it. So I will need to manually cause a refresh when actions are taken.

While its subtle, you can see in the _Repositories_ view there is a `<!>` next to the repository name -- which is the indicator of this (and it mentions it in the tooltip for the repo as well).

@admehta01 is this the same for you? Do you see a `<!>` indicator next to the repositories that you are experiencing this issue with?

**Comment by admehta01** [comment]
Yes, that's in my screenshot as well. What do you mean by "repository it outside of the opened workspace"?
