### ISSUE TITLE
Distracting editor behavior - Unsaved changes (cannot determine authors)

### ISSUE THREAD

**Issue by ChuckIrvine** [eamodio/vscode-gitlens#827]
When ever I type into a vscode editor window, a message briefly appears at the top of the editor saying:

```
Unsaved changes (cannot determine authors)
```

This output causes the editor content to shift up and down and is distracting. How can I disable this behavior?

Thanks.

**Comment by rubaiz** [comment]
I see the same warning everytime I edit a file, it goes away after saving which is specially distracting when autosaving is enabled, as the text moves down and then back up while editing.

My interim fix was to set recentChangeAndAuthors to blank, try adding this your setting.json file:

 "gitlens.strings.codeLens.unsavedChanges.recentChangeAndAuthors": ""

**Comment by CameLion** [comment]
One fix is to disable the Gitlens>Code Lens>Authors

**Comment by haughki** [comment]
I had to disable all of Code Lens. Just unchecking Authors didn't work for me.

**Comment by joe-scotto** [comment]
@haughki This too was distracting for me and I found that disabling both `Authors` and `Recent Change` got rid of it.
![Screen Shot 2020-01-28 at 2 07 26 PM](https://user-images.githubusercontent.com/8194147/73296331-84cca680-41d7-11ea-9396-37057d8630d3.png)

**Comment by Pitasi** [comment]
Not sure if related or a new issue but I found this line "shaking while typing" pretty annoying:

![code](https://user-images.githubusercontent.com/15048443/92702828-efd78180-f351-11ea-87c9-7917662ebad4.gif)

![code2](https://user-images.githubusercontent.com/15048443/92702945-13023100-f352-11ea-9aa0-3e7adf3d5901.gif)

As suggested by joe-scotto I disabled that feature entirely :)

**Comment by eamodio** [comment]
This is "fixed" in GitLens 11 -- as the code lens is replaced with an ellipsis (by default) when it can't currently be displayed.

@Pitasi that looks like a bug in VS Code -- can you report that on the VS Code repo?
