### ISSUE TITLE
Is it possible to only show the commit message in line git blame. No author and time.

### ISSUE THREAD

**Issue by nikitavoloboev** [eamodio/vscode-gitlens#835]
So instead of current `Author . Time ago. Commit msg`. Only have `Commit msg`.

![2019-09-02 at 09 33](https://user-images.githubusercontent.com/6391776/64100997-b9415100-cd64-11e9-933f-5f6d710bd805.png)

Would be super useful for me. Perhaps such setting already exists? And if not can you please add it?

Thank you.

**Comment by eamodio** [comment]
You can do this today, using the GitLens interactive settings editor -- run _GitLens: Open Settings_ from the command palette and scroll/jump to the _Current Line Blame_ section:

![image](https://user-images.githubusercontent.com/641685/64152913-9e6deb80-cdfb-11e9-92a8-8862bd73d8a7.png)
