### ISSUE TITLE
Possibility to adopt single changes or whole file in diff view with a working version

### ISSUE THREAD

**Issue by pahlke** [eamodio/vscode-gitlens#843]
In most IDEs, when having a diff view containing an editable file, there are some arrow buttons which allow to transfer the currently selected change or even the whole file. Would this maybe be a nice feature for GitLens, since VS code is lacking this?

**Comment by eamodio** [comment]
This is something VS Code would need to provide as there isn't any good UI options available to extensions to provide this type of behavior.
