### ISSUE TITLE
File history shows changes from unrelated files

### ISSUE THREAD

**Issue by nfp0** [eamodio/vscode-gitlens#846]
- GitLens Version: 9.9.3
- VSCode Version: 1.38.0
- OS Version: Windows 10 x64 1903

Steps to Reproduce:

1. Check file history of this file on Github:
https://github.com/nfp0/qmk_firmware/commits/solheim68/keyboards/solheim68/keymaps/default/keymap.c

2. Compare with the file and line history shown on the sidebar on GitLens:

![image](https://user-images.githubusercontent.com/11202422/64487588-4b010080-d234-11e9-82e4-07737ec1c751.png)

**Comment by nfp0** [comment]
I've noticed now that if I select the `Don't follow renames` option in File History this doesn't occur anymore. So is it perhaps a bad rename follow?

**Comment by eamodio** [comment]
Yeah, it looks like Git got confused that the other file was renamed. Unfortunately there isn't really anything I can do to fix that.
