### ISSUE TITLE
can't figure out how to turn off blame notes between lines

### ISSUE THREAD

**Issue by joachim-n** [eamodio/vscode-gitlens#848]
- GitLens Version:
  
- VSCode Version: Version: 1.38.0
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. When I open a file with changes, there's a git blame summary that shows between lines.

I can't find a setting that turns this off!

<img width="281" alt="Screenshot 2019-09-09 at 09 03 09" src="https://user-images.githubusercontent.com/105262/64513767-2f9fff00-d2e1-11e9-9261-44fe17b1d3b7.png">

**Comment by joachim-n** [comment]
Oh it's maybe the 'code lens'? I was actually going to file a second issue to say that this setting needs an explanation of what a 'code lens' actually is, as I have no idea.

**Comment by eamodio** [comment]
Yeah, that is the code lens in that image. If you use the _GitLens: Open Settings_ command from the command palette, it should hopefully be a lot clearer as to what is what and how to easily customize them (or turn them off).
