### ISSUE TITLE
Extra backslash in the hovers blame detail's link

### ISSUE THREAD

**Issue by bryceyang** [eamodio/vscode-gitlens#849]
- GitLens Version:  v9.9.3
  
- VSCode Version: Version: 1.39.0-insider,  latest stable version also has the problem.
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. move cursor to the git line blame, then the blame details contain some related issue links pop up;
2. check the end of the links 

further desc:
The correct link in blame detail should be: https://somedomain.com/repo/merge_request_id,
but actually, it is: https://somedomain.com/repo/merge_request_id\. 
The link with an extra backslash can't be accessed by chrome except I remove the `\` manually. 
Check the pic below:

<img width="478" alt="Screen Shot 2019-09-10 at 9 18 41 PM" src="https://user-images.githubusercontent.com/9302617/64617283-c6b7a480-d410-11e9-984a-7aeb95eb98db.png">
.

**Comment by eamodio** [comment]
@bryceyang those links are included in the commit message itself correct?

**Comment by bryceyang** [comment]
> @bryceyang those links are included in the commit message itself correct?

Hi, I checked the commit message.
The links in the origin commit message are surrounded by a pair or angle brackets. 
Like: Tested-by: \<https://somedomain.com/repo/merge_requests/id>

So the brackets could be the reason cause the extra backslash?
