### ISSUE TITLE
What is the setting to allow files to automatically close after diff view

### ISSUE THREAD

**Issue by gitorko** [eamodio/vscode-gitlens#850]
If i select the file the diff shows up in the editor window. However if i select many such diff files then have to manually close all the open diff windows. 
Is there a setting that shows the diff when i select the file and when i unselect the file closes the diff window as well?
Or atleast have the same editor window updated instead of opening a new diff window for change i click on?

**Comment by eamodio** [comment]
When you say "select many diff files" do you mean one after another? How are you opening the diffs?

**Comment by gitorko** [comment]
Git Lens -> Repositories -> Expand the commit -> Select the files in the commit one at a time.
On each selection a diff of the commit opens up. Very soon my editor tabs are filled with such open editor windows. 
Would be nice to have option such that on each selection just a single editor window was updated instead of opening new windows each time.
Similar feature in gitkraken,where you select a commit and click on the files in the commit it just updates one window/view to show the diff. You select the next commit the same view is updated.

**Comment by eamodio** [comment]
GitLens should be opening the diffs in "preview" tabs (what vs code calls them), and when you open another it should replace the first. Do you possibly have `workbench.editor.enablePreview` set to `false` in your settings?

**Comment by gitorko** [comment]
Yes it was set to false after changing to true it works as expected. Thanks.

**Comment by Himel55** [comment]
Is it possible to have enablePreview functionality just for the compare view?
