### ISSUE TITLE
[Feature Request] Limit history lookback when blaming

### ISSUE THREAD

**Issue by woopla** [eamodio/vscode-gitlens#851]
Hello,

There's an option in `git blame` called `--since` that limits the amount of history that blame is going through. We have a very large and messy repo converted from Git, with some files having 25+ years of history, so we pretty much have to use this by default.

I'd like to have a configurable option in GitLens to provide a similar feature. Right now, it takes a lot of time to fetch the blame info, and that aspect of GitLens is pretty much unusable on these files.

Thanks,

Clément

**Comment by eamodio** [comment]
You can do this today -- GitLens has a setting `gitlens.advanced.blame.customArguments`  where you can provide custom arguments to the `git blame` command. Just set it to an array of the arguments you wish to add. Hope that helps!

**Comment by woopla** [comment]
Works fine, thanks @eamodio !
