### ISSUE TITLE
GitLens不具合

### ISSUE THREAD

**Issue by h-shino** [eamodio/vscode-gitlens#852]
Issue Type: <b>Bug</b>

After upgrading VSCode to 1.38.1, GitLens's Explore Repository from Here does not work.

Extension version: 9.9.3
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:35.387Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.00GB (0.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by eamodio** [comment]
This will be fixed in the next release.
