### ISSUE TITLE
"Recent change" information appears in the middle of the file in addition to above the source code.

### ISSUE THREAD

**Issue by KerimG** [eamodio/vscode-gitlens#853]
For some reason in one of my files GitLens shows the last file modification information not only above the source code but also right in the middle of it between line 5 and 6

https://i.imgur.com/XEDfujw.png

- GitLens Version: 9.9.3
  
- VSCode Version: 1,38,1
- OS Version: Windows NT x64 10.0.18362

Steps to Reproduce:

1. I don't know
2. It's only this one file that's affected
3. I was able to reproduce it on a different computer by simply opening the repository and the file

**Comment by KerimG** [comment]
I think the class definition is what causes this issue. But only if the closing curly brace isn't on the same line as the opening one. This is really strange.

![2019-09-18 10_28_07-● index js - learn-react - Visual Studio Code](https://user-images.githubusercontent.com/9061713/65131162-0aa53d80-d9ff-11e9-8f19-c97bdbc16235.png)

**Comment by KerimG** [comment]
Might be related to https://github.com/eamodio/vscode-gitlens/issues/371

**Comment by eamodio** [comment]
@KerimG That is as-designed. GitLens adds git code lens to the top of the file and on code blocks.

You can easily configure where these show up via, _GitLens: Open Settings_ from the command palette:

![image](https://user-images.githubusercontent.com/641685/65222502-37079b00-da8d-11e9-936f-06772196fe78.png)

**Comment by KerimG** [comment]
Oho! I've never noticed it before so I thought that it's a rendering bug. 
Thank you and I'm sorry for the pointless issue post!

**Comment by eamodio** [comment]
No worries at all! Glad to help.
