### ISSUE TITLE
Missing tags in Repositories view

### ISSUE THREAD

**Issue by egvimo** [eamodio/vscode-gitlens#855]
- GitLens Version: 9.9.3
  
- VSCode Version: 1.38.1
- OS Version: Windows 7

Steps to Reproduce:

If I run the `git tag` command I get a list of all tags:
![image](https://user-images.githubusercontent.com/5247100/65328761-5ef31d80-dbb7-11e9-9914-63c728b6c312.png)

But in the Repository view not all tags are listed:
![image](https://user-images.githubusercontent.com/5247100/65328799-73371a80-dbb7-11e9-9505-da4f86a7edcd.png)

The tags `0.3.0` and `0.4.0` are missing.

**Comment by eamodio** [comment]
@egvimo if you run `git show-ref --tags` on the command line do you see the missing tags? If so, can you possibly paste the output of the that command here? Maybe there is something wrong in my parsing.

**Comment by egvimo** [comment]
Yes, the missing tags are also listed with the `show-ref` command:
![image](https://user-images.githubusercontent.com/5247100/65862272-2f3dd580-e36e-11e9-915c-879153a5c475.png)

**Comment by eamodio** [comment]
@egvimo can you try with v10.1 to see if the problem is now resolved?

**Comment by egvimo** [comment]
Now somehow the missing versions are shown in the previous version tags:
![image](https://user-images.githubusercontent.com/5247100/66374258-de9c2d00-e9aa-11e9-8356-0364e371bc08.png)
