### ISSUE TITLE
Bulk deleting branches

### ISSUE THREAD

**Issue by jasonwilliams** [eamodio/vscode-gitlens#856]
It would be nice if i can select multiple branches and delete them in one go.
Sometimes i have a load of branches hanging around, and i have to delete them one by one, it can be a bit laborious.

Same for remote too.

**Comment by eamodio** [comment]
FYI - bulk delete of branches via the _Git Commands_ menu is now in v10.1

**Comment by jasonwilliams** [comment]
@eamodio I didn’t see it mentioned in the release notes
