### ISSUE TITLE
GitHub avatars in blame line hovers are huge

### ISSUE THREAD

**Issue by KamasamaK** [eamodio/vscode-gitlens#858]
- GitLens Version: 10.0.0
- VSCode Version: 1.38.1
- OS Version: Windows 10

Below is an image of the line blame hover I am seeing. I have to scroll down to see the details.
![image](https://user-images.githubusercontent.com/22951521/65364760-bdcd8c80-dbe1-11e9-9a69-596f228ace6e.png)

To verify this was not just mine, I've posted another one below for another user
![image](https://user-images.githubusercontent.com/22951521/65364735-9ecefa80-dbe1-11e9-9d1d-71942abd99c1.png)

The following are the only GitLens settings I have
```json
{
  "gitlens.keymap": "alternate",
  "gitlens.advanced.messages": {
    "suppressCommitHasNoPreviousCommitWarning": false,
    "suppressCommitNotFoundWarning": false,
    "suppressFileNotUnderSourceControlWarning": false,
    "suppressGitVersionWarning": false,
    "suppressLineUncommittedWarning": false,
    "suppressNoRepositoryWarning": false,
    "suppressResultsExplorerNotice": false,
    "suppressShowKeyBindingsNotice": true
  },
  "gitlens.views.fileHistory.enabled": true,
  "gitlens.views.lineHistory.enabled": true,
}
```

**Comment by eamodio** [comment]
@KamasamaK are the e-mail addresses `@users.noreply.github.com` ones?

**Comment by KamasamaK** [comment]
Yes, that is the email domain for the authors of both of the commits presented here.
