### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by sperryOneWeb** [eamodio/vscode-gitlens#859]
- Issue Type: `Bug`
- Extension Name: `gitlens`
- Extension Version: `10.0.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by eamodio** [comment]
@sperryOneWeb Please provide details on the issue you are having.

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
