### ISSUE TITLE
Issues with "renderWhitespace" option

### ISSUE THREAD

**Issue by aengl** [eamodio/vscode-gitlens#86]
Setting `editor.renderWhitespace` to `all` or `boundary` causes the code to overlap the author/commit hash:

<img width="484" alt="screenshot 2017-06-09 19 24 51" src="https://user-images.githubusercontent.com/5022924/26986798-672f902c-4d49-11e7-9d65-66d0d50da7c9.png">

**Comment by aengl** [comment]
After some more testing it seems to be a bit more complicated than that. It's a combination of the font I'm using (Inconsolata) and `renderWhitespace`. Using VSCode 1.13.0 on MacOS.

**Comment by aengl** [comment]
Here's my settings.json for reference:

```
{
    "editor.rulers": [
        80,
        100
    ],
    "editor.lineHeight": 14,
    "editor.fontSize": 14,
    "editor.fontFamily": "Consolas, Inconsolata",
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "all",
    "editor.autoClosingBrackets": false,
    "editor.formatOnPaste": false,
    "editor.formatOnSave": true,
    "editor.wordWrap": "bounded",
    "editor.wordWrapColumn": 100,
    "editor.minimap.enabled": false,
    "window.zoomLevel": 0,
    "window.nativeTabs": true,
    "prettier.singleQuote": true,
    "prettier.printWidth": 80,
    "prettier.trailingComma": "es5",
    "javascript.implicitProjectConfig.checkJs": true,
    "typescript.check.tscVersion": false,
    "typescript.implementationsCodeLens.enabled": true,
    "workbench.iconTheme": "vs-seti",
    "workbench.editor.swipeToNavigate": true,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.exclude": {
        "**/.git": true,
        "**/node_modules": true,
        "ios": true,
        "android": true
    }
}
```

**Comment by zmoazeni** [comment]
Wow I thought I was the only one. Yep also running Inconsolata and renderWhitespace and ran into this issue.

Talk about the timing.

**Comment by zmoazeni** [comment]
Looks like a problem with https://github.com/Microsoft/vscode/issues/11485

**Comment by eamodio** [comment]
Yeah -- to workaround it  please set `"gitlens.advanced.toggleWhitespace.enabled": true` to render the GitLens blame annotations properly. This issue is noted in the README here: https://github.com/eamodio/vscode-gitlens#known-issues

**Comment by eamodio** [comment]
FYI - in v4 (coming shortly) I've re-enabled `"gitlens.advanced.toggleWhitespace.enabled": true` as the default so it will no longer need to be set manually
