### ISSUE TITLE
Unknown date format error

### ISSUE THREAD

**Issue by ihmcjacky** [eamodio/vscode-gitlens#860]
The following error occurs when compare branches and viewing individual commits after upgrading to gitlens v10

Issue Type: Bug (Maybe)
Extension Name: gitlens
Extension Version: 10.0.0
OS Version: Ubuntu 16.04 LTS
VSCode version: 1.38.1
Git Version: v2.7.4

`
Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false for-each-ref --format=%3ch%3e%(HEAD)%3cn%3e%(refname)%3cu%3e%(upstream:short)%3ct%3e%(upstream:track)%3cr%3e%(objectname)%3cd%3e%(committerdate:unix) refs/heads refs/remotes
fatal: unknown date format unix
`

**Comment by eamodio** [comment]
@ihmcjacky what version of Git do you have installed?

**Comment by ihmcjacky** [comment]
> @ihmcjacky what version of Git do you have installed?

Sorry for missing the info, further update the thread

**Comment by eamodio** [comment]
@ihmcjacky It looks like the unix date format was added in Git 2.13.7 -- can you upgrade Git?

**Comment by ihmcjacky** [comment]
> @ihmcjacky It looks like the unix date format was added in Git 2.13.7 -- can you upgrade Git?

@eamodio  After upgrading to git v2.23.0, problem gone, thanks so much!

**Comment by jdblischak** [comment]
The discussion in this Issue was helpful for me as I was debugging a Git-related issue with my own software. Thanks!

> It looks like the unix date format was added in Git 2.13.7 -- can you upgrade Git?

In case anyone else finds this issue, the option `--date=unix` was added in version 2.9.4 ([link to release notes](https://github.com/git/git/blob/53f9a3e157dbbc901a02ac2c73346d375e24978c/Documentation/RelNotes/2.9.4.txt#L19)):

```
$ git clone git@github.com:git/git.git
$ cd git
$ grep 'date=unix' Documentation/RelNotes/*
Documentation/RelNotes/2.10.0.txt:   --date=unix to report the seconds-since-epoch (without timezone)
Documentation/RelNotes/2.9.4.txt:   --date=unix to report the seconds-since-epoch (without timezone)

```
