### ISSUE TITLE
wired font color welcome page in dark theme

### ISSUE THREAD

**Issue by Eskibear** [eamodio/vscode-gitlens#861]
I'm using the default dark theme "Dark+". FYI
![image](https://user-images.githubusercontent.com/2351748/65399567-035fa480-ddf0-11e9-9c56-79149474d82f.png)

**Comment by eamodio** [comment]
@Eskibear It looks like the CSS failed to load for some reason. If you restart vscode does it still happen? If so, I would recommend, uninstalling GitLens, restarting all vscode instances twice, and then re-install GitLens.

**Comment by Eskibear** [comment]
well, a restart works.
