### ISSUE TITLE
Support git filter attribute

### ISSUE THREAD

**Issue by martin-css** [eamodio/vscode-gitlens#866]
We use git-crypt to ensure that some propriety files are kept secure. This generally works well but can cause issues with Git functionality in other tools. We use VS Code for development and it's a pain to not have the integrated diff functionality when reviewing changes of encrypted files.

It would be useful if Gitlens could properly support `.gitattributes` when retrieving data via `git show` so that blob output is passed through a filter if this is defined.

See the [related pull request](https://github.com/microsoft/vscode/pull/81395) for built in Git extension which has more details.

**Comment by eamodio** [comment]
Added in GitLens 11
