### ISSUE TITLE
How to pull development, when on a branch

### ISSUE THREAD

**Issue by NzureAdmin** [eamodio/vscode-gitlens#873]
I work on a branch "Bugfix", of off "Develop".
"Develop" moves on, others commit to it.
My "Bugfix" branch is not behind. So I want to merge newest Develop into it.

I pull and fetch, but get no changes.
The only way to update Develop, is to switch to Develop and Pull it.
Now it's updated
I can now Switch back to "Bugfix" branch and merge develop into it.

What am I doing wrong?

**Comment by eamodio** [comment]
There isn't a way currently in GitLens to do that -- but its a great feature request

**Comment by istarkov** [comment]
The git command for branch like master is 

```
git fetch origin master:master
```

still not supported?

**Comment by eamodio** [comment]
Added in GitLens 11 -- there is a `Pull` command in the _Branches_ view
