### ISSUE TITLE
Editing causes all contextual blames to disappear

### ISSUE THREAD

**Issue by thavidu** [eamodio/vscode-gitlens#875]
Issue Type: <b>Bug</b>

When I edit a file, the git blame annotations (same line, status bar etc) all disappears. If i hit save, everything re-appears.
The only thing that still works once I make any change to a file, is the gutter blame that I have to toggle on with the button in the top right- also for some reason, that auto-hides itself whenever I start changing the code, and I have to manually press it to turn it back on each time too.

If it might lead to any clues, I am developing while using the remote-ssh extension for vscode, and all the code/projects I'm working on lives remotely on a server (incase that makes any difference)

Extension version: 10.1.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:31:32.854Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 4.4.0-143-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|-psn_0_880855|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev2|
|OS|Linux x64 4.4.0-143-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (48 x 2500)|
|Memory (System)|184.85GB (4.25GB free)|
|VM|0%|
</details>

**Comment by sanket-bhalerao** [comment]
facing the same issue #892
