### ISSUE TITLE
How to change the color of the watermark on a line of code?

### ISSUE THREAD

**Issue by dfinke** [eamodio/vscode-gitlens#88]
I'm using a theme white background theme for the editor window and the light gray watermark is hard to read. How can I make it dark gray?

**Comment by eamodio** [comment]
You can change `"gitlens.theme.annotations.line.trailing.light.foregroundColor": "<valid-css-color-here>"`, FYI, you can also find all the other theme controls in the [README](https://github.com/eamodio/vscode-gitlens/blob/master/README.md#theme-settings)
