### ISSUE TITLE
ability to view commit description

### ISSUE THREAD

**Issue by Ardeshir81** [eamodio/vscode-gitlens#880]
Hi!
Today I was trying to read description of a commit. By description I mean what is below the main commit message:
![Screenshot from 2019-10-13 15-11-22](https://user-images.githubusercontent.com/5755214/66715227-7fd11c00-edcd-11e9-8a81-6be8c45d1f3e.png)

And I couldn't find it anywhere. At least not easily accessible.
So I had to go to GitLab to be able to read the commit description

**Comment by eamodio** [comment]
@Ardeshir81 The full commit message is shown in the hovers in the editor (if you hover over the line blame annotation), and if you hover over a commit in the _Repositories_, _File History_, and _Line History_ views.

Where else would you want to see this information?

**Comment by Ardeshir81** [comment]
Wow!
Yeah you're right!
Actually I mostly try to use keyboard only to navigate around in VSCode and when I use mouse, I think I'm navigating too fast that I don't let popups to show up :)
But I've seen that hover so many times, the point is that I never actually took a moment to figure it out.
So I think everything is fine.
Actually I was trying to find commit description in the right click menu. Something like `show commit details` or so. I even tried `copy commit message` and pasting it somewhere, hoping I'd see the description in the clipboard.

Thanks! I think its super fine 👍
