### ISSUE TITLE
Compare Ancestry with Working Tree should have an entrance for origin branches

### ISSUE THREAD

**Issue by vilic** [eamodio/vscode-gitlens#881]
Currently we use shared remote workspaces for easier code review, thus the changes are in the working tree. So our problems are:

1. We have to click "Swap Comparison" every time after click "Compare Ancestry with Working Tree"
2. Sometimes the working tree has newer `origin/master` merged, but the local master branch has not. Thus the result would contain changes from `origin/master`, we have to manually `git branch --force master origin/master` for the comparison to work correctly.

So it would be nice if:

1. There is a direct entrance to compare working tree with ancestry.
2. We can select a remote branch as target.

**Comment by eamodio** [comment]
@vilic Instead of using _Compare Ancestry with Working Tree_ from the local branch, try running it from the remote branch (`origin/master`) under the _Remotes_ node in the _Repositories_ view.

Let me know if that resolves your issue.

**Comment by vilic** [comment]
@eamodio Thanks! I don't know why I didn't find that... But it would be nice to put the remote branches tracked by local branches before the others. Finding `origin/master` in the long remote branches list takes a second or two.
