### ISSUE TITLE
How to make a nice decoration like Git Lense's

### ISSUE THREAD

**Issue by dherault** [eamodio/vscode-gitlens#887]
Hi,

I'm writing a small motivational extension to display a line of text at the end of the cursor like the git blame display does.
How did you do it? 😉 

<img width="750" alt="Screenshot 2019-10-29 at 05 00 17" src="https://user-images.githubusercontent.com/4154003/67736885-85537680-fa09-11e9-97ad-f23ebd1cb96a.png">

**Comment by eamodio** [comment]
GitLens uses the [TextEditor.setDecorations](https://code.visualstudio.com/api/references/vscode-api#TextEditor.setDecorations) API. It is basically adding a after element (with styling) to each line as the cursor moves.

Here is a more simple example about decorations: https://github.com/microsoft/vscode-extension-samples/tree/master/decorator-sample

Hope that helps!
