### ISSUE TITLE
ts files: link decoration in parameters with 'pos' in name

### ISSUE THREAD

**Issue by tao-cumplido** [eamodio/vscode-gitlens#888]
I'm not sure that the issue really lies with GitLens as it only happens with another extension in conjunction, having only one of the extensions enabled doesn't trigger the effect. An issue I opened in the VS Code repo was closed immediately: https://github.com/microsoft/vscode/issues/83410

Since it is a text decoration issue I reopen the issue here as the other extension doesn't seem to use them.

- GitLens Version: 10.1.1
- [PostgreSQL 1.1.11](https://marketplace.visualstudio.com/items?itemName=ckolkman.vscode-postgres)
  
- VSCode Version: 1.39.2 / 1.40.0-insider
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Install/enable GitLens and PostgreSQL extensions
2. Create new file and set language mode to typescript
3. Write a variable with `pos` somewhere in name and explicitly set the type (doesn't matter which), also happens in interfaces
![image](https://user-images.githubusercontent.com/6384563/67660933-3271b480-f960-11e9-8b0b-642da7fad296.png)

**Comment by eamodio** [comment]
This is a bug in vscode and will be fixed in the November iteration.
