### ISSUE TITLE
"Show Line Commit Details" date format

### ISSUE THREAD

**Issue by SailorMax** [eamodio/vscode-gitlens#89]
- GitLens Version: 4.0.1
- VSCode Version: 1.13.0
- OS Version: Windows 10.1703

Steps to Reproduce:
1. right click on any line / "Show Line Commit Details"

Expected: commit details in format "gitlens.annotations.line.trailing.format" (or else?) with date in format "gitlens.annotations.line.trailing.dateFormat"

Actual: commit details in gitlens author specific format.

P.S. Do we really need so many settings for GitLens? ;) For example: why do you support "${message|40?}", but not "{$date|YYYY-MM-DD}"?

**Comment by SailorMax** [comment]
Settings for date format in "Show File History" also can't find.

**Comment by eamodio** [comment]
In the next release there will be a new `gitlens.defaultDateFormat` that can be used as the default format for all absolute dates GitLens uses. The more specific date format settings, will now override the default.

As for the relative dates in the GitLens UI, I won't be providing an option to change them to absolute date. 

> Do we really need so many settings for GitLens?

If you don't need them, don't use them :) I like to err on the side of flexibility with a power tool such as GitLens, and I try my best to pick the best defaults I can.

> For example: why do you support "${message|40?}", but not "{$date|YYYY-MM-DD}"?

It would have made the template parsing more complex, but PRs are welcome :)

**Comment by SailorMax** [comment]
> If you don't need them, don't use them :)

With joy, but I need 10- of them (no codeLens, no blame.line and absolute dates)
and for it I have to scan all your library (69), because I don't know how you named required settings :)

**Comment by eamodio** [comment]
You don't need to go digging for them -- they are all well-documented [here](https://github.com/eamodio/vscode-gitlens#extension-settings)

**Comment by eamodio** [comment]
@SailorMax the latest [GitLens beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v4.1.0-beta.2) adds the new `gitlens.defaultDateFormat`. Please follow [these instructions](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions) to install a pre-release. Let me know if you experience any issues -- thanks!

**Comment by eamodio** [comment]
4.1 is now out

**Comment by SailorMax** [comment]
@eamodio 
Sorry for pause. My work day was done :)

In "Show Line Commit Details" date ignore "gitlens.defaultDateFormat". What can I do with that?

Plus in 4.1.0 "Toggle File Blame" button lost its icon.

**Comment by eamodio** [comment]
No worries.

As I mentioned above:
> As for the relative dates in the GitLens UI, I won't be providing an option to change them to absolute dates.

Doh! Thanks for the report on the icon -- 4.1.1 coming in a few.

**Comment by SailorMax** [comment]
I did not ask about "to change them to absolute dates" :) I ask about date format ;)
Do you want not add settings for format of dates in "Show Line Commit Details" and "Show File History"?

**Comment by eamodio** [comment]
Can you post a screenshot of the dates you are talking about? If you are talking about the dates (x days ago) in the quickpick menus -- then you are correct, I'm not interested in adding the ability to control them.

**Comment by SailorMax** [comment]
Yes, I talk about them. They are not informative, when all records of history are "1 month ago".
Why no interested? Not so easy?

**Comment by SailorMax** [comment]
@eamodio 
in 4.1.0 was button, but without icon
in 4.1.1 no button - no problem? :)

**Comment by eamodio** [comment]
I see (re: the dates).  I'll think more about how I can do that well -- thanks.

As for the button, I don't see it missing -- you still do?

**Comment by SailorMax** [comment]
> As for the button, I don't see it missing -- you still do?

Sorry. Looks like it was problem from my side. VSCode had some error in console. Uninstall GitLens/Reload/Install GitLens/Reload helped. Possible some kind of cache conflict. The button was appeared.

**Comment by eamodio** [comment]
@SailorMax In [7.3 beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v7.3.0-beta), I've added support for controlling the default date style via the `gitlens.defaultDateStyle` setting. Let me know what you think and sorry for the LONG delay in adding this.

**Comment by SailorMax** [comment]
Thanks! Looks like it work.
By why we need "defaultDateStyle" when we have "defaultDateFormat"? If user need, he can just setup "defaultDateFormat" to relative or absolute value. Not? Plus he could setup both formats ("2018-01-03 12:21 [10 minutes ago]" for example)

**Comment by eamodio** [comment]
I didn't want to overload/conflate the current data formatting, with a switch between relative and absolute. Thanks for testing!
