### ISSUE TITLE
Inline Blame in the middle of the line

### ISSUE THREAD

**Issue by petrosschilling** [eamodio/vscode-gitlens#891]
GitLens inline text is pushing the code to the right.

- GitLens Version: 10.1.1
- VSCode Version: 1.40.0-insider
- OS Version: Mojave 10.14.6

Look at the print screen below to see that the selected line text "snbdsbd" has been pushed to the right of the GitLens text.

<img width="431" alt="Screen Shot 2019-10-31 at 2 33 42 pm" src="https://user-images.githubusercontent.com/5184353/67917300-b50ea400-fbec-11e9-9ccd-230065d9e994.png">

**Comment by eamodio** [comment]
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/667
