### ISSUE TITLE
Why does GitLens show commits by me as multiple contributors?

### ISSUE THREAD

**Issue by isaacwashere** [eamodio/vscode-gitlens#898]
### Odd Behavior(s)
- When I go to the GitLens tab in the Activity Bar, under the `Repositories` section (for a repo that is solely my own), I see myself multiple times
- One has a gravatar, my full name and gmail, while the other has a gravatar, my GitHub username and gmail, and a final one will have my GitHub avatar, my full name, and a `+@users.noreply.github.com` email
- Is it possible to merge all those versions for me into 1 (not saying this is what I want, just curious)?
- Is it possible to have only information for one (or pick one) of those versions of me to show up "on hover"?
- I'd appreciate any information that would shed some light on this 👍 

### Tools
- Using Mac running OSX Catalina
- On the standard version of VS Code (Version: 1.39.2)
- I do have the email privacy setup on my GitHub account
- My question is within the context of working in a personal repo where I am/you are the only contributor

### Thoughts 
- The `git log` shows commits on my machine by me (the gmail), and PRs by me (the `+@users.noreply.github`); commits I made on GitHub.com seem to have my username (and gmail), commits I made on my machine have my full name (and gmail), and PR's merged also have my full name (but with the `+@users.noreply.github`email)
- Maybe the `+@users.noreply.github` email is being used for what I do on GitHub.com (like merging PRs) and the `gmail.com` for local commits (?) But the gmail is also being used for commits I made on GitHub.com 😕 

### Notes 
- I didn't file this as an issue because I'm not sure this is one. I think it's more of a misunderstanding on my part 
- This is similar to https://github.com/eamodio/vscode-gitlens/issues/686
- I really just want my GitHub avatar to show up on hover (yep, it's enabled) and for some reason it's not :( But in trying to figure _that_ out, I stumbled on this question (hover shows the gmail account which doesn't have a GH avatar for some reason)

### Relevant image
<img width="687" alt="Screen Shot 2019-11-07 at 12 18 53 PM" src="https://user-images.githubusercontent.com/43455920/68411732-fe18a800-0158-11ea-9964-dbafe4a5abf8.png">

**Comment by eamodio** [comment]
You can use the "mailmap" feature of Git (via a `.mailmap` file) to merge multiple commit identities into 1 (which GitLens will then honor).

Here is a good overview of Git mailmap (while this is from Atlassian it isn't Atlassian/Bitbucket specific): https://blog.developer.atlassian.com/aliasing-authors-in-git/

Hope that helps!

**Comment by isaacwashere** [comment]
Thanks! I appreciate the help! So, if I were to merge my emails/user info into my `+@users.noreply.github.com` I should be able to view my avatar "on hover", right?
