### ISSUE TITLE
Scroll change on input if codeLens is visible on css files

### ISSUE THREAD

**Issue by vizeke** [eamodio/vscode-gitlens#9]
Hi, Just started using the extension and it's awesome. 

But when the codelens are visible on any css files that can be scrolled and your scroll is not on top of the page, if you type something the scroll will go down a little. If the scroll is on top, the page just bounce a little and go back to the original state.

**Comment by eamodio** [comment]
@vizeke thanks for the report. I took a look into it and I think it is a vscode issue. I will open an issue there.

**Comment by eamodio** [comment]
@vizeke are you still experiencing this issue? I haven't noticed it lately -- I'm figuring vscode fixed something.

**Comment by vizeke** [comment]
@eamodio made some tests and everything looks fine. No unwanted scrolls or bounces. If I notice something in the future I'll let you know.

**Comment by eamodio** [comment]
Great. Thank you
