### ISSUE TITLE
remove Context menu / Copy Commit ID

### ISSUE THREAD

**Issue by SailorMax** [eamodio/vscode-gitlens#90]
Context menu of document line has "Copy Commit ID to Clipboard" and "Copy Commit message to Clipboard".
Commit ID/message of what? Of current line? Latest commit? Without Blame Annotations these menus confusing.

May be better remove them from Context menu if you can't change context menu in blame/not blame mode? You have they in "Show Line Commit Details" menu.

**Comment by eamodio** [comment]
It copies the commit of the current line, unless there isn't any editors, then the command (via the command palette) will copy the last commit to the current branch.

You can remove these yourself using `gitlens.advanced.menus` -- can use something like:

```json
"gitlens.advanced.menus":  {
        "editorContext": {
            "copy": false,
        }
}
```

**Comment by SailorMax** [comment]
@eamodio 
Then may be you will rename it to "Copy Line Last Commit ID to Clipboard" and "Copy Document Last Commit ID to Clipboard"?

Previous your menus are more concrete: "Compare Line Commit...", "Compare File with...", "Show File History",..

**Comment by eamodio** [comment]
Unfortunately, I can't have different titles in the menu vs the command palette (without duplicate commands - and I don't feel the need for separate command here). So the commands are just contextual. The reason the others are more specific, is that there is overlap with the line vs file commands.

**Comment by abnerlee** [comment]
@eamodio I tried with
```
"gitlens.advanced.menus":  {
        "editorContext": {
            "copy": false,
        }
}
```

But it is not working, VS Code also indicate it as "Unknown Configuration Setting" if you hover on "gitlens.advanced.menus"

**Comment by eamodio** [comment]
The setting should be `gitlens.menus`

```json
"gitlens.menus":  {
        "editor": {
            "clipboard": false,
        }
}
```

Hope that helps.
