### ISSUE TITLE
Is it possible to make these icons invisible for small screen

### ISSUE THREAD

**Issue by VictorSu000** [eamodio/vscode-gitlens#900]
On some small screens, if too many tabs opened, these icons occupy too much space.  Is it possible to make them disappear?

![image](https://user-images.githubusercontent.com/18596923/68520682-9d15df00-02d4-11ea-855c-659af31e4482.png)

Thank you for your help!

**Comment by eamodio** [comment]
You can change GitLens' menu/toolbar contributions via the GitLens interactive settings editor from the command palette run `GitLens: Open Settings`

![image](https://user-images.githubusercontent.com/641685/68566341-11ab6380-0424-11ea-8ffb-03ada3d66472.png)

Hope that helps!

**Comment by exse2** [comment]
First button of the area marked in red rectangle by op is still visible after disabling "Add commands to the editor group toolbar"

**Comment by eamodio** [comment]
@exse2 The first button is _Open Changes_ and is part of VS Code itself, not GitLens.
