### ISSUE TITLE
Bitbucket Server fails when url = https://DOMAIN/stash/scm/PROJECT/REPO.git

### ISSUE THREAD

**Issue by jaklan** [eamodio/vscode-gitlens#901]
- GitLens Version: 10.1.2
  
- VSCode Version: 1.40.0
- OS Version: MacOs Mojave (10.14.6)

#### Steps to Reproduce:

1. Use Bitbucket Server with such a remote:
`https://DOMAIN/stash/scm/PROJECT/REPO.git`
The most important part is additional `/stash` in the URL.
2. Function [`baseUrl()`](https://github.com/eamodio/vscode-gitlens/blob/861f64180961e2532c92b69de870c7bb6c350464/src/git/remotes/bitbucket-server.ts#L13) in [`bitbucket-server.ts`](https://github.com/eamodio/vscode-gitlens/blob/861f64180961e2532c92b69de870c7bb6c350464/src/git/remotes/bitbucket-server.ts) fails, because `this.path.startsWith('scm/')` is not true and invoked `this.splitPath()` results in `project = "stash"` & `repo = "scm/PROJECT/REPO"`.
3. Such a behaviour also make it impossible to create a proper custom URL, because you also get wrong tokens: `${repoBase} = stash`, `${repo} = stash/scm/PROJECT/REPO` and `${repoPath} = scm/PROJECT/REPO`. Due to that you're not able to reproduce `https://DOMAIN/stash/projects/PROJECT/repos/REPO/browse` in any way.

You can try to create a custom Bitbucket Server config and put `/stash` or `/stash/` in the `domain` field, but it just doesn't work - config is not taken into account when running e.g. `Open Repository on Remote`, so I assume using slashes in the `domain` field is not possible.

#### Potential solution:

Just make it possible to set `DOMAIN/stash` in the `domain` field in a Remote configuration or change `this.path.startsWith('scm/')` line to be also true when any string occurs before `scm` (and change `this.path.replace('scm/', '')` similarly).

**Comment by meandmax** [comment]
Same problem here, would be nice to get this fixed :)

**Comment by robross0606** [comment]
Same problem and then some.  Seems like Bitbucket Server integration thoroughly botches most of the URL constructions.

**Comment by robross0606** [comment]
I recommend allowing configuration of the "base name" or "context path" similar to how Bitbucket itself is set up if you require a URL context.  Even the Atlassian plugin for VSCode supports it this way:
![scrnli_11_20_2020_6-53-20 PM](https://user-images.githubusercontent.com/2965467/99860651-ada49a80-2b61-11eb-8edb-9f442db7a6d7.png)

**Comment by eamodio** [comment]
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.
