### ISSUE TITLE
Make "Branches" List sortable by criteria in VS Code Extension [Feature]

### ISSUE THREAD

**Issue by SirHodlington** [eamodio/vscode-gitlens#905]
Background:
I am using Gitlens on VS Code. We are using feature branches in our Git and over time a quite significant number of branches has been created. 

Problem:
The collapsible "Branches" List shows all the branches in an order that is not clear to me - it's not by creation date and it's not in alphabetical order. There is it sometimes hard to find specific branches in the list.

Suggestion:
Add a sort functionality to the list that allows
1.) sort A-Z
2.) sort by creation date
3.) sort by last push

Thank you for your time and consideration

**Comment by eamodio** [comment]
You can do this today via the `"gitlens.sortBranchesBy"` setting.

You can set it to one of the following values:
- `name:desc` — Sorts branches by name in descending order
- `name:asc` — Sorts branches by name in ascending order
- `date:desc` — Sorts branches by the most recent commit date in descending order
- `date:asc` — Sorts branches by the most recent commit date in ascending order

Hope that helps!
