### ISSUE TITLE
Where do I change ${author}?

### ISSUE THREAD

**Issue by pmahend1** [eamodio/vscode-gitlens#906]
Where do I change `${author}` ? Where does it come from?

**Comment by eamodio** [comment]
Sorry, I'm not sure what you are asking about.

**Comment by pmahend1** [comment]
@eamodio 
![image](https://user-images.githubusercontent.com/21352870/68963851-ef0fa680-07a5-11ea-9d1f-73a32111cc13.png)

**Comment by eamodio** [comment]
You can click on that _Commit Tokens_ link and it will take you to the documentation about those tokens. Also if you use use the GitLens interactive settings editor from the command palette run `GitLens: Open Settings`, you'll get a more guided experience

![image](https://user-images.githubusercontent.com/641685/68964157-ac020300-07a6-11ea-9e66-fcd04c96dc0c.png)

**Comment by pmahend1** [comment]
And where do I set value for the token `author`?

**Comment by eamodio** [comment]
Huh? You don't -- those are replacement tokens which come from the commit.

**Comment by pmahend1** [comment]
Ok. I get it but is there a way I can override this for a repository or all git repositories? 
We have this feature in Visual studio Windows and Mac

**Comment by eamodio** [comment]
I'm sorry I really don't understand what you are trying to do. Those tokens come from the commits themselves -- which could all have different authors. So what do you mean by override?

Are you trying to change how Git displays a particular author?

**Comment by pmahend1** [comment]
Here is the query.

My full name is "ABC XYZ" , if I commit and push from other applications like Visual studio , Visual studio mac , then commit history shows author as ABC XYZ<abcxyz@company.com> 

When I commit and push from VS code its showing "ABC <ancxyz@company.com>

I would like to know if I change  it to ABC XYZ in VS Code or GitLens settings

Is that even possible. 

Is there setting which does below things

```bash
$ git config --global user.name "John Doe"
$ git config --global user.email "john@doe.org"
```

**Comment by eamodio** [comment]
Ah, VS Code Git doesn't offer an override for the author name -- it just uses your git config settings. I would suggest to set your global/local git config to the name you would like to have show up in your commits.

You can use the "mailmap" feature of Git (via a .mailmap file) to merge multiple commit identities into 1 (which GitLens will then honor).

Here is a good overview of Git mailmap (while this is from Atlassian it isn't Atlassian/Bitbucket specific): https://blog.developer.atlassian.com/aliasing-authors-in-git/

Hope that helps!

**Comment by pmahend1** [comment]
I could do it from command line but wanted to check git extension within VS code or GitLens support this. Thanks! May be I will add a request to support this. Would you be able to add it in Gitlens?

**Comment by eamodio** [comment]
Feel free to open an issue on the vscode repo -- GitLens doesn't offer commit capability, so it isn't something that would apply to GitLens.

**Comment by discitechris** [comment]
@eamodio is there a way to show the $(author) token as "John Doe" instead of the rendered suffix "You".

**Comment by eamodio** [comment]
@discitechris No, that currently isn't an option. Could you explain why you would want that?
