### ISSUE TITLE
File Blame Annotations vs editor.renderIndentGuides

### ISSUE THREAD

**Issue by SailorMax** [eamodio/vscode-gitlens#91]
- GitLens Version: 4.1.0
- VSCode Version: 1.13.0
- OS Version: Win 10x64

Steps to Reproduce:

1. turn on "editor.renderIndentGuides"
2. turn on "File Blame Annotations"

Expected: Guide lines shifted with code

Actual: Code shifted but Guide lines not

**Comment by eamodio** [comment]
Fun -- looks like I need to toggle these off as well :(

**Comment by eamodio** [comment]
Opened https://github.com/Microsoft/vscode/issues/28628

**Comment by poke** [comment]
Hey, this problem is still happening for me in VS Code 1.33.1 with GitLens 9.6.3.

I see that the linked VS Code issue was already fixed with 1.15.0 so this should be working, right? But for some reason, it isn’t :/ Does anyone else have that problem?
