### ISSUE TITLE
"Show Commit in Search Commits View" doesn't work

### ISSUE THREAD

**Issue by ethancn** [eamodio/vscode-gitlens#910]
- GitLens Version: 10.2.0
  
- VSCode Version: 1.40.1
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Open File History View, right-click on any commit -> Show Commit in Search Commits View
2. The commit doesn't show up in Search Commits View. Nothing happens.

<img width="389" alt="GitLens_issue_screenshot" src="https://user-images.githubusercontent.com/28993381/69428320-dd14a180-0d6b-11ea-8fa5-af7cf3083b61.png">

**Comment by 3nuc** [comment]
I'm not helping, but to avoid later confusion with the duplicated commits above whether it's fixed - I was able to reproduce this on:
* GitLens 10.2.2
* VS Code Insiders 1.48-insider

**Comment by julee** [comment]
When will this bug be fixed? It's troublesome.

**Comment by eamodio** [comment]
Does this still happen with GitLens 11?

**Comment by 3nuc** [comment]
The renamed equivalent of `Show Commit in Search Commits View` — `Search for Commit in Side Bar` — works great with GitLens 11 now 👍
