### ISSUE TITLE
Add ability to hide ActionBar icons for switching between commits.

### ISSUE THREAD

**Issue by EthanZeigler** [eamodio/vscode-gitlens#912]
The ActionBar buttons for the extension (the top right buttons) take a lot of space that some users, including myself, would rather have to see more tabs at once. An option to hide these buttons and free up this space while having the extension enabled would be fantastic.
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/9123320/69471421-c3c02500-0d6c-11ea-8375-be3afa2c1161.png">

**Comment by eamodio** [comment]
Duplicate of #900
