### ISSUE TITLE
I really want it to support Chinese

### ISSUE THREAD

**Issue by jiejieTop** [eamodio/vscode-gitlens#913]
Gitlens is the best git plugin I have ever used. I really want it to support Chinese. Thank you very much anyway.

**Comment by eamodio** [comment]
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/577

**Comment by jiejieTop** [comment]
@eamodio Oh, I am very sorry that I have not searched, and I am very grateful for your answer.
