### ISSUE TITLE
Linewise history restore

### ISSUE THREAD

**Issue by Safieddine90** [eamodio/vscode-gitlens#916]
I would like to request a feature in which line-wise history restore is available as a button in "Current Line Hovers".

This could be useful in the following scenarios for examples:

1. I did a lot of changes in and pushed in git over several commits.
2. I want to undo some of these changes which are distributed over several different commmits
3. I open gitlens view, and then I go line by line and then put the mouse cursor on the line to get the  "Current Line Hover". 
4. I find in the "Current Line Hover" a history restore button. Each time I click it, it goes commit back in history only for this line.

Thanks a lot and keep up the Superhero work you are doing!

Best Regards
HS

**Comment by eamodio** [comment]
@Safieddine90 If I understand correctly, I believe the _Open Changes_ button here, would do what you are asking for.
![image](https://user-images.githubusercontent.com/641685/100703542-be2eef00-3371-11eb-80ee-20244d98696d.png)

But you can also use the _Open Line Changes with Previous Revision_ command from the command palette to jump back to the line commit.

Let me know if you wanted something else.
