### ISSUE TITLE
Highlighting commit-changes in gitlens mode in different colors

### ISSUE THREAD

**Issue by Safieddine90** [eamodio/vscode-gitlens#919]
I would like to suggest the following feature:

When you go into GitLens mode in VScode, you can see the commits on the left side different . When you click on one of these commits, all the lines on the right which where changed in this commit, is highlighted.

I suggest to use different highlight colors for different commits so that it becomes easier to differentiate between different commits and their corresponding changes in code.

Thanks a lot !
Keep up the Superhero work you're doing!

Best Regards
HSD

**Comment by eamodio** [comment]
@Safieddine90 Why would you like different highlight colors? Right now, GitLens only highlights the commit associated with the line you click on.

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
