### ISSUE TITLE
Click at the end of line, cursor jump back to start on VSCode web 

### ISSUE THREAD

**Issue by yuxuan** [eamodio/vscode-gitlens#920]
- GitLens Version: 10.1.1
  
- VSCode Version: 1.40.1 (WEB)
- OS Version: 

Steps to Reproduce:

1. Open a file with git history info at the end;
![image](https://user-images.githubusercontent.com/2955214/69841371-dcaf6580-1299-11ea-8c35-eb6ed1b2cece.png)

2. Click at the end of the line; 
![image](https://user-images.githubusercontent.com/2955214/69841435-0a94aa00-129a-11ea-837b-4ad37508a581.png)

The cursor will jump to the start of the line

**Comment by eamodio** [comment]
@yuxuan I can't reproduce this -- does this only happen on the web? Can you get it to happen on the desktop too?

**Comment by yuxuan** [comment]
Hi @eamodio. Yes, this is only happened on the web. Desktop doesn't have this issue.

**Comment by jbw716** [comment]
I just started having this issue as well. It seems to only be happening in VSCode-Insiders for me though.

**Comment by JoaoSetas** [comment]
Hi @eamodio. Started happening to me after i switched to VSCode-Insiders

**Comment by JBrLloyd** [comment]
@eamodio I've replicated the issue, attached a video. It's to do with the whitespace between the EOL of the code and the start of Current Line Blame annotation. Replicated bug here: #937

**Comment by Yen** [comment]
https://github.com/microsoft/vscode/issues/88873

**Comment by eamodio** [comment]
Caused by microsoft/vscode#88873
