### ISSUE TITLE
Hide the sidebar button when there isn't a git repository detected

### ISSUE THREAD

**Issue by cxy930123** [eamodio/vscode-gitlens#921]
![图片](https://user-images.githubusercontent.com/7006257/70034834-ce8c7c80-15ec-11ea-831a-5ca9d8e6ad3b.png)

Hello, I find there's a button in sidebar, whether the working directory contains a git repository or not. I hope the button could be hidden when there isn't a git repository detected.

**Comment by kjhx** [comment]
Closed by https://github.com/eamodio/vscode-gitlens/pull/1077#issuecomment-733473664?

**Comment by eamodio** [comment]
Yup, thanks this should be fixed now.
