### ISSUE TITLE
Gitlens unusable when author name is extremely long

### ISSUE THREAD

**Issue by getaceres** [eamodio/vscode-gitlens#923]
Today I came across a corner case that's rendering Visual Studio Code unusable when using GitLens.
In our code we have a commit with an author which is called Victor Menéndez. For whatever reason the é character got messed up when commiting and executing a git blame or git show with the commit shows it as Victor MenÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ.........ndez with the 'Â' character repeated thousands of times. Now this commit has files with hundreds of lines so when opening one of this files Visual Studio Code freezes and the only way to develop on this project is disabling Git Code lens.
I know it's a corner case and I know it's a weird issue on our side but it would be good if instead of freezing on extreme long author names, GitLens would stop parsing it after, let's say 100 characters. Nobody has such a long name anyway.

**Comment by eamodio** [comment]
@getaceres is this in an open source repo I can try myself?

**Comment by eamodio** [comment]
@getaceres I would suggest you use a `.mailmap` file to fix this up.

Here is a good overview of Git mailmap (while this is from Atlassian it isn't Atlassian/Bitbucket specific): https://blog.developer.atlassian.com/aliasing-authors-in-git/

Here is some Git docs on mailmap: https://www.git-scm.com/docs/git-check-mailmap

Hope that helps.
