### ISSUE TITLE
Sort origin to the top of remotes in quick picks by default

### ISSUE THREAD

**Issue by connor4312** [eamodio/vscode-gitlens#924]
Usually I want to, for instance, copy the URL to a commit on the origin, even if I have other remotes from forks

**Comment by eamodio** [comment]
Great idea!

Also note, if you set a particular remote as the default, then all the remote commands will use that rather than showing a quick pick:
![image](https://user-images.githubusercontent.com/641685/71834415-2bac9f80-307d-11ea-8960-cc5d2edc851e.png)
