### ISSUE TITLE
Compare working tree to last commit on local branch

### ISSUE THREAD

**Issue by ericbiewener** [eamodio/vscode-gitlens#927]
I'd like the Compare View to be able to show me the uncommitted changes on my local branch. Currently, I can accomplish this by selecting a comparison like "Working Tree to <branch_name>". However, that comparison is static -- it is a comparison against a specific branch, not my currently active branch. Therefore, as soon as I change branches the comparison will no longer only show uncommitted files on the local branch.

Perhaps there is a different trick available to accomplish this?

**Comment by eamodio** [comment]
@ericbiewener I think there are multiple ways to accomplish this today, but I will also add a feature so you will be select `HEAD` directly from the compare quickpick.

In the meantime, you can use the _GitLens: Compare HEAD with..._ command from the command palette -- and that will open a compare in the _Compare_ view which can be refreshed manually.

But if you want a live view, the _x files changed_ node in the _Repositories_ view shows all the uncommitted changes -- see:
![image](https://user-images.githubusercontent.com/641685/71795380-eacc7080-3013-11ea-83a5-b528b981a3d9.png)

At the same time, I'm curious to why not use the built-in source control view, which also shows exactly this information (unless I'm misunderstanding)?

**Comment by ericbiewener** [comment]
"why not use the built-in source control view" -- Wasn't aware of it! I hadn't bothered to use any git features built into VS Code before installing Git Lens. And the Git Lens Repositories view works well for this as well. Thanks!

Feel free to close this if you want, but I'll leave it open in case it is indeed a feature you want to add.

**Comment by eamodio** [comment]
Fixed in GitLens 11
