### ISSUE TITLE
Clicking on staged change does not bring up compare window

### ISSUE THREAD

**Issue by kchu-tusimple** [eamodio/vscode-gitlens#928]
Clicking on a file that is changed and staged in the repositories view gives the error "unable to open 'xxx': Invalid git URI: missing path."

- GitLens Version: 10.2.0
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:
1. Change any file.
2. Stage the changed file.
3. Click the changed/staged file in the repositories view.

**Comment by eamodio** [comment]
This is caused by a change in vscode -- I need to figure out if the vscode change will stay or I need to fix it in GitLens.

**Comment by corelema** [comment]
Same issue here. Surprisingly if I'm using vscode on windows, it works for the non-staged files, but on wsl (ubuntu), it doesn't work for the staged files either.

**Comment by eamodio** [comment]
Fixed in 10.2.1
