### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by carloscgo** [eamodio/vscode-gitlens#929]
- Issue Type: `Performance`
- Extension Name: `gitlens`
- Extension Version: `10.2.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Carlos Camacho\eamodio.gitlens-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by eamodio** [comment]
No profile was attached. Closing.
