### ISSUE TITLE
VS code built-in icons messed up

### ISSUE THREAD

**Issue by ViggoV** [eamodio/vscode-gitlens#93]
- GitLens Version: 4.1.1
- VSCode Version: 1.13.0
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Update GitLens

This might be a different issue but it occurred after updating GitLens. Basically all built-in icons are replaced with white squares, or blocky representations of themselves. This includes the close buttons on tabs, dropdown arrows in the explorer, icons in the left menu, split pane buttons, stars for extensions and almost every other icon. It does not affect filetype icons. Could it be something is this update?

**Comment by eamodio** [comment]
@ViggoV Hrm, I don't see how that would be possible (for GitLens to cause it). Can you post a screenshot? Does it persist after a restart of vscode? Might also want to try disabling all extensions and see if the issue goes away -- and then re-enabled them 1 by 1.

**Comment by ViggoV** [comment]
You're probably right (disabling GitLens did not help). Yes, the issue persists after restart.
![skaermbillede 2017-06-13 kl 15 46 41](https://user-images.githubusercontent.com/3153568/27085493-b294fdb4-504f-11e7-9b13-a22c23530a6f.png)

**Comment by eamodio** [comment]
I think this is related: https://github.com/Microsoft/vscode/issues/28590

**Comment by ViggoV** [comment]
Weirdly enough it doesn't affect the explorer arrows when expanded. Anyways, thanks for your response. The reason is probably something else :)

**Comment by ViggoV** [comment]
Thanks for the redirect! :D
