### ISSUE TITLE
Enable ctrl+shift+g ctrl+shift+{button} for all keybindings

### ISSUE THREAD

**Issue by arekbal** [eamodio/vscode-gitlens#934]
Using 'ctrl+shift+g {button}' is cumbersome. Mistake of not releasing ctrl, shift before pressing the actual, next button happens. Combinations like 'ctrl+shift+g ctrl+shift+{button}' are much easier - comfortable to use.

I would like these, to be enabled by default for all commands. I would leave the currently used as they are, just to avoid dealing with situation where people that got used to how it works now would have a problem.

**Comment by eamodio** [comment]
While I agree it is easier to keep holding `ctrl+shift` while executing the chord, it doesn't work for some of the shortcuts, because some keys also use `shift` as a differentiator. But you can easily add the extra chords to your keyboard shortcuts in vscode to get this to work for you.

Sorry.
