### ISSUE TITLE
Hovers only work when saving file after switching to another file

### ISSUE THREAD

**Issue by nunojsa** [eamodio/vscode-gitlens#936]
Not sure if this is actually an issue, so I'm opening it as question.

I noticed that the hovers over the lines are not working when I switch to a new file in a different tab. I realized afterwards that they only start to come when I save the file. This does look like a strange behavior. Is this on purpose?

Im running on Ubuntu Mate 18.04 and I could also verify the same behavior in Arch Linux.
vscode: 1.41.1
gitlens: 10.2.0

**Comment by pixmaster** [comment]
I have the same behavior, but with existing files. It can be few cases:
- file is changed but but didn't save
- just opened file
- other cases when conditions weren't memorized

windows 10

**Comment by eamodio** [comment]
@nunojsa @pixmaster Can you provide some step-by-step instructions for how to reproduce this? Thanks!

**Comment by pixmaster** [comment]
Unfortunately, I couldn't find why it's happening. In some files it just don't work. After file save it works again.

**Comment by nunojsa** [comment]
@eamodio for me it happens pretty easily. So if I just do:

1. Open vscode with more than one files opened;
2. Hovers will work in the file you are currently;
3. Switch to another tab/file;
4. Hovers won't work until you save the file.

**Comment by eamodio** [comment]
@nunojsa @terski Can you try this upcoming version of GitLens?

[gitlens-10.3.0-alpha.vsix.zip](https://github.com/eamodio/vscode-gitlens/files/4367668/gitlens-10.3.0-alpha.vsix.zip)

Rename the file to remove the `.zip` and then install it

![image](https://user-images.githubusercontent.com/641685/77290723-242b8880-6cb3-11ea-8ab2-d84a9d32ccfc.png)

**Comment by terski** [comment]
@eamodio I'm running it now. Appears to be fixed. 👍 Thank you! 🙏

**Comment by marcmarina** [comment]
Hey there, I've been having the same problem lately, blame annotations show up very inconsistently. For now adding `"gitlens.hovers.enabled": true,` to the settings file _seems_ to fix it, emphasis on seems. It could just be chance.

**Comment by eamodio** [comment]
Fixed in GitLens 11
