### ISSUE TITLE
Whitespace in front of Current Line Blame Annotation causing cursor to move to start of line

### ISSUE THREAD

**Issue by JBrLloyd** [eamodio/vscode-gitlens#937]
The white space between End Of Line (EOL) of the code to the first character of the 'current line blame annotation' moves the cursor to the start of the line.

If you click x spaces away from the EOL character, your cursor will move x characters away from the start of the line (or possible EOL of the previous line?).

I've also uploaded a video to help visually display the bug, found here:
[https://youtu.be/AL-nzabmg1s](https://youtu.be/AL-nzabmg1s)

- GitLens Version: 10.2.0
- VSCode Version: 1.42.0-insiders
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Use VSCode Insiders Version 1.42.0
2. Install GitLens extension
3. Ensure Current Line Blame Annotation Feature is enabled
4. Get or initialize a git repository
5. Left-click on whitespace between code EOL and the start of git blame annotation
6. Validate that cursor is being moved to start of the line instead of EOL

**Comment by eamodio** [comment]
Caused by: https://github.com/microsoft/vscode/issues/88873
