### ISSUE TITLE
More flexible autolink

### ISSUE THREAD

**Issue by idanpa** [eamodio/vscode-gitlens#946]
It would be nice if the autolink feature could support non-numerical handle such as the ones created be gerrit:
`
Change-Id: I4931e504d995c766a057dbd914a81119aa8802bd
`

I'd be happy to add a PR for this.
What do you think about having `numMatch` property with default option `numeric` and new option `alphanumeric`  to match `[a-zA-Z0-9_]`?
Or maybe just have  `[a-zA-Z0-9_]` for everyone?

**Comment by brightest-dazes** [comment]
I think that is an absolutely perfect idea.
