### ISSUE TITLE
Support ignoring revisions on blame

### ISSUE THREAD

**Issue by pzelnip** [eamodio/vscode-gitlens#947]
In Git 2.23 options were added to blame to allow ignoring revisions in blames: https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt and https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt

This is useful for when (as an example) one does a large bulk change to apply a new formatting scheme to a codebase as those commits aren't particularly useful in a blame.

Any chance support for this could be added to Gitlens?  I'd especially like to see support for blame ignore files, like is described in this blog: https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame  Perhaps adopting the common convention of looking for a file named `.git-blame-ignore-revs` and using it if it exists would be a nice default.

**Comment by joelhock** [comment]
you can specify the ignore file for gitlens to use in blame as described in:
https://github.com/eamodio/vscode-gitlens/issues/413#issuecomment-523640184

or, alternatively, just specify `blame.ignorerevsfile=.git-blame-ignore-revs` in your gitconfig.

**Comment by pzelnip** [comment]
Awesome, thanks!
