### ISSUE TITLE
Add Open Settings command to extension context menu

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#952]
See https://code.visualstudio.com/updates/v1_42#_extensions-view-context-menu

**Comment by zeeshanadnan** [comment]
Hi @eamodio  i want to work on this.

**Comment by eamodio** [comment]
Blocked by not having a way to filter by extension id yet -- opened PR https://github.com/microsoft/vscode/pull/93207 for https://github.com/microsoft/vscode/issues/93206

**Comment by eamodio** [comment]
See https://github.com/eamodio/vscode-gitlens/issues/953#issuecomment-605832202

**Comment by eamodio** [comment]
Added in GitLens 11
