### ISSUE TITLE
Add Welcome command to extension context menu

### ISSUE THREAD

**Issue by eamodio** [eamodio/vscode-gitlens#953]
https://code.visualstudio.com/updates/v1_42#_extensions-view-context-menu

**Comment by zeeshanadnan** [comment]
Hi @eamodio  i want to work on this.

**Comment by zeeshanadnan** [comment]
Hi @eamodio from the reference given the command will be added to the context menu of every extension. Correct me if i am wrong.

**Comment by eamodio** [comment]
@zeeshanadnan Yeah, unfortunately it looks like there isn't a way to filter by extension id yet -- but I opened a PR https://github.com/microsoft/vscode/pull/93207 for https://github.com/microsoft/vscode/issues/93206

**Comment by eamodio** [comment]
@zeeshanadnan the PR for VS Code has been merged, so there is now an `extension` context key that will have the id of the extension -- so you can filter by `extension == eamodio.gitlens`

**Comment by SharakPL** [comment]
@eamodio Can I use extension context inside keybindings.json based on extension's installed/enabled status? Quick example:
```
{
    "key": "ctrl+alt+g",
    "command": "gitlens.supportGitLens",
    "when": "extension == eamodio.gitlens"
}
```
Using `extension` here only breaks the shortcut 😞

**Comment by eamodio** [comment]
@SharakPL No, that context key is only available in the extensions view's context menu

**Comment by eamodio** [comment]
Added in GitLens 11
