### ISSUE TITLE
Copy Commit Message does not work anymore

### ISSUE THREAD

**Issue by phamquocduy** [eamodio/vscode-gitlens#955]
- GitLens Version: 10.2.1
  
- VSCode Version: 1.42
- OS Version: Windows 10 64-bit with latest updates

Steps to Reproduce:

1. Click in GitLens icon in Sidebar
2. Mouse right clicking in any commit, choose Copy Commit Message

**Comment by eamodio** [comment]
@phamquocduy @bcanzanella I can't seem to reproduce this -- are you seeing this with 10.2.1? Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by bcanzanella** [comment]
@eamodio This is working for me now with 10.2.1 in VSC 1.42.1 and 1.43.0-insider

**Comment by phamquocduy** [comment]
@eamodio I confirm this is working for me right now with 10.2.1 and VS Code 1.43 (switched back to GitLens, before that I have it disabled and used Git History because of this bug)
