### ISSUE TITLE
Git 2.25.0 breaks functionality due to lower-cased driver letter

### ISSUE THREAD

**Issue by mseele** [eamodio/vscode-gitlens#957]
- GitLens Version: 10.2.1
  
- VSCode Version: 1.42.0
- OS Version: Windows 10 1909

Gitlens uses lower-cased driver letter which breaks with git 2.25.0 under windows.
please see https://github.com/git-for-windows/git/issues/2478
VSCode was broken, too: https://github.com/microsoft/vscode/issues/89373
This has been fixed in VSCode here: https://github.com/microsoft/vscode/commit/830992d818cbf1a09e744f0ee475c542763bdfff

GitLens needs the same fix...

**Comment by eamodio** [comment]
@mseele What issue are you seeing? GitLens 10.2.1 has a patch for the Git change (notice who filed that git issue 😉)

**Comment by mseele** [comment]
@eamodio ups, i did noch check that, sorry

I get
`[2020-02-13 06:46:11:394] [c:/dev/workspaces/eDMRTaskBasedView/git/eDMRTaskBasedView] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.quotepath=false -c color.ui=false fetch • Could not create directory '/home/mseele/.ssh'. • Host key verification failed. • Could not read from remote repository. •  • Please make sure you have the correct access rights • and the repository exists. • 265 ms`
with git v2.25.0 and i did not get the file & line history.

after downgrading to git v2.24.1.2 everything works fine and i see the file & line history.

**Comment by eamodio** [comment]
@mseele Are you still seeing this with 10.2.1?

**Comment by mseele** [comment]
@eamodio i can confirm it's gone with gitlens 10.2.1 & vscode 1.43.0

**Comment by GriceTurrble** [comment]
I'm using VSCode 1.47.2 and Git 2.21.0.windows.1 (work computer, cannot currently update Git), and finding this is still breaking for me.

Only certain Git commands seem to be doing this: VSCode will use lowercase drive letters for `Open repository`, `git add`, and `git reset`; but it will correctly use uppercase drive letters in `git ls-files`, `git ls-tree`, etc.

Is this a regression?
