### ISSUE TITLE
External diff command always launched when opening files instead of plain git diff

### ISSUE THREAD

**Issue by carlobonamico** [eamodio/vscode-gitlens#96]
- GitLens Version:
- VSCode Version: 1.13
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Configure global git to use an external diff command in .gitconfig
```
[diff]
        external = external-diff-cmd
``` 
2. install vscode-gitlens
3. launch vscode, open git project
4. navigate to various files
5. when opening a file for the first time, the external-diff-cmd is always launched thus interrupting the editing flow

In my specific case I followed these instructions to configure `meld` as the diff viewer https://nathanhoad.net/how-to-meld-for-git-diffs-in-ubuntu-hardy.

```
[diff]
        external = /home/user/scripts/diff.py
```

where `diff.py` contains 
```
#!/usr/bin/python

import sys
import os

os.system('meld "%s" "%s"' % (sys.argv[2], sys.argv[5]))
```
which is needed just to adapt the order in which `git diff` passes cli arguments to the order expected by `meld`

# Proposed fix
Launch `git diff` with an option specifying to use the internal diff algorithm or plain diff
* `git diff --no-ext-diff`
* https://stackoverflow.com/questions/19936187/git-diff-overriding-gitconfig-external-tool

**Comment by eamodio** [comment]
@carlobonamico Thank you so much for this awesome bug report! 4.1.2 is out now with your fix -- thanks again!
