### ISSUE TITLE
Preview commit message on graph

### ISSUE THREAD

**Issue by Kevinwuu** [eamodio/vscode-gitlens#960]
When I was editing my commit message I always cares about whether the length is too long than other message or not.
If I can preview the message on the graph instead of showing "Uncommitted Changes" when I typing in the left side, then it will be great. 👍 

( Or maybe modify commit direct on the graph is an option? )
![image](https://user-images.githubusercontent.com/22792854/74580372-6f7cb800-4fde-11ea-8905-688a39d7e6bf.png)

**Comment by eamodio** [comment]
@Kevinwuu Git Graph is a different extension.
