### ISSUE TITLE
Author names are completely misleading

### ISSUE THREAD

**Issue by sayauYusen** [eamodio/vscode-gitlens#964]
- GitLens Version: 10.2.1 (VS marketplace version)
  
- VSCode Version: 1.36.0
- OS Version: Windows_NT x64 10.0.17763

**Result expected:**
1. _gitLens-text-hint in grey_
      Gitlens should display the correct Author Name and created time next to the code. Example:
      "You, 2 months ago"
2. _gitLens-dialogue-box_
Gitlens should display the correct Author Name and created time in the dialogue box once you hover your mouse over the gitLens-text-hint in grey.

**Actual result:**
1. Gitlens is showing the name of another repository member instead of 'You', even if you are the original inventor of this line of code. Please refer to the picture below:

![gitLen_misleading_authorNames](https://user-images.githubusercontent.com/61306184/75012197-79aa2500-54bc-11ea-8bc5-9f92353051b4.jpg)

**Steps to Reproduce:** (let's say there is a file, say gitLens.vue, created by John Smith)
Step 1. Press ctrl-C to copy the entire file.
Step 2. Delete 98% of the contents in the file (gitLens.vue) and create a new commit, say commit id = 'aa3efe'

Step 3. Paste in the original content to gitLens.vue, save it and commit the change. Let's say the commit id = 'ff553e3'

Now every single line of code in gitLens.vue (commit id =ff553e3) will show 'You' as the author instead of 'John Smith'.

Your repository members can steal your authorship by similar code manipulation.
This bug renders the value of GitLens to ZERO, as GitLens is supposed to be a software to reflect the original copyright of the intellectual property of the true inventor of a line of code/algorithm.

**Comment by eamodio** [comment]
I'm not sure what you are really looking for here -- but this is how Git works. You can always keep going back in history to see who the original author was.
