### ISSUE TITLE
No tree view id registered

### ISSUE THREAD

**Issue by akosyakov** [eamodio/vscode-gitlens#966]
<img width="1904" alt="Screenshot 2020-02-24 at 15 55 23" src="https://user-images.githubusercontent.com/3082655/75162643-28996b80-571e-11ea-965c-07dca62c0c63.png">

Steps to reproduce:
- select explorer view
- select contextual layout
- it is important that file and line history views are collapsed, so if you don't get it first time, then collapse them and switch between layouts

**Comment by eamodio** [comment]
@akosyakov Are you seeing the same issue in Theia? I'm pretty sure this is a vscode bug, not a GitLens issue.

**Comment by akosyakov** [comment]
@eamodio yes, we have similar issue in Theia, but VS Code extension support basically a port from VS Code. probably you are right it has to be fixed in VS Code

**Comment by eamodio** [comment]
Since VS Code (in 1.44) allows the user to move views around, I will be removing the ability to control where the GitLens views are shown -- because it causes issues when the user moves views and tries to use the settings. So once that is removed, this issue will go away.

**Comment by eamodio** [comment]
Fixed in GitLens 11
