### ISSUE TITLE
GitLens show me as multiple different contributors.

### ISSUE THREAD

**Issue by WangShuoran** [eamodio/vscode-gitlens#971]
It question same as #686,But I has any details.
Let me show you.
In my PC,I set git config as `git config --global user.name "WangShuoran"`
But in Github Settings “My profile” --> "name" is "小然同学".(It is not in "account" --> username)
In both of these,I set same Email.
I think it will identify both of them as one contributor.
But it is not. 
Does it work right?
I don't quite understand the principle of git.So, can you help me?
<img width="133" alt="批注 2020-03-04 130222" src="https://user-images.githubusercontent.com/43474491/75846813-667e4a00-5e18-11ea-8bad-92818d55d612.png">
Thank you!

**Comment by WangShuoran** [comment]
I think Gitlens have any parameters let same Email contributor as one contributor.But I not find it.

**Comment by eamodio** [comment]
@WangShuoran See this comment here: https://github.com/eamodio/vscode-gitlens/issues/898#issuecomment-552315495

That should help you combine duplicate identities into one.
