### ISSUE TITLE
Option to exclude whitespace or line ending only changes from annotation

### ISSUE THREAD

**Issue by ssa3512** [eamodio/vscode-gitlens#972]
We had some instances of files where line endings were changed from CRLF to LF throughout the entire file due to mismatched local git configurations. When running a blame/annotation in visual studio, the blame shows the first "real" change to the line where non-whitespace content was changed. Would it be possible to add an option in GitLens to use this behavior instead of the current? Right now in GitLens each of the files in this scenario show inline annotations and blame on every line pointing to the commit where the line endings were changed.

Example:
VS Code: Open changes with previous revision with leading/trailing whitespace changes hidden
![image](https://user-images.githubusercontent.com/1991399/76096844-af5b0d80-5f94-11ea-9841-f96fcb673560.png)

Gitlens: File blame annotations:
![image](https://user-images.githubusercontent.com/1991399/76097003-f2b57c00-5f94-11ea-85da-e40a834afdfa.png)

Visual Studio: Source Control > Blame (Annotate)
![image](https://user-images.githubusercontent.com/1991399/76097188-445e0680-5f95-11ea-85f1-2a9d71087b65.png)

**Comment by eamodio** [comment]
@ssa3512 You can set "gitlens.blame.ignoreWhitespace": true in your settings if you want to ignore whitespace changes from blames.

You can also use:
```json
"gitlens.advanced.blame.customArguments": [
	"--ignore-revs-file",
	".gitignore-revs"
],
```

Where you have a `.gitignore-revs` file (you can call it whatever you want -- it just needs to match the setting) with commit ids to ignore. See: https://git-scm.com/docs/git-blame/en#Documentation/git-blame.txt---ignore-revs-fileltfilegt
