### ISSUE TITLE
File history across branches

### ISSUE THREAD

**Issue by tgreen7** [eamodio/vscode-gitlens#974]
Sometimes I made a change on a different branch in a file that I want to add to other branches. I see you can change the base branch of the file history tab but I am not always sure what branch it was on. If I use the search commits tab and go by filename I can achieve exactly what I want because it does show the commits of the file on every branch. But it would be nicer and faster to just have this same ability right from the file history view.

**Comment by eamodio** [comment]
@tgreen7 I'm not sure I'm understanding what you are looking for. What would it look like?

**Comment by tgreen7** [comment]
@eamodio 
<img width="538" alt="Screen Shot 2020-03-23 at 8 35 41 AM" src="https://user-images.githubusercontent.com/10415101/77333929-5eac1a00-6ce1-11ea-80f7-ea4f826f6000.png">

In the screenshot file history only shows 2 commits but the search commits shows 3 commits (commits to all branches). I was hoping there was a way to make file history show what was in the search commits view.

**Comment by tgreen7** [comment]
@eamodio When will this be on the released version?

**Comment by tgreen7** [comment]
bump

**Comment by eamodio** [comment]
Hopefully within a week (though it highly depends on how this week goes)

**Comment by eamodio** [comment]
Added in GitLens 11
