### ISSUE TITLE
Support per-language overrides for `gitlens.codeLens.scopes` & `gitlens.codeLens.symbolScopes`

### ISSUE THREAD

**Issue by justarandomgeek** [eamodio/vscode-gitlens#977]
My [Factorio Mod Debug](https://marketplace.visualstudio.com/items?itemName=justarandomgeek.factoriomod-debug&ssr=false#overview) extension adds language support for various Factorio files, but GitLens's default config for the changelog is a bit silly, since I classified the groups as Classes. 

I currently set 
```json
{
          "language": "factorio-changelog",
          "scopes": [
            "document",
            "custom"
          ],
          "symbolScopes": [
            "Namespace"
          ]
        }
```
 in my settings.json under `gitlens.codeLens.scopesByLanguage` but this is clunky and I end up suggesting the same to every user too. I tried to apply these settings as a language defaults in my `configurationDefaults` contribution, but it does not appear to allow setting your settings. What is the intended way for me, as a language provider, to offer default gitlens config for my languages?

**Comment by eamodio** [comment]
In the next release you will be able to set per-language overrides for `gitlens.codeLens.scopes` & `gitlens.codeLens.symbolScopes`
