### ISSUE TITLE
Static width of blames in "File Blame" mode

### ISSUE THREAD

**Issue by obrejla** [eamodio/vscode-gitlens#98]
Hi

- GitLens Version: 4.1.2
- VSCode Version: 1.13.1
- OS Version: Mac OS X

I would expect to have some static editable width value of the file gutter blame area. If I set the format of file gutter annotations to `"${id} ${author}"` and some authors have longer/shorter names then another, then the lines in the gutter area are indented differently as well as the code in the file.

![different width of blame lines in gutter](https://user-images.githubusercontent.com/150452/27274413-72cda5cc-54d3-11e7-9103-5e05400c53f5.png)

Thanks!

**Comment by eamodio** [comment]
@obrejla See [Advanced Formatting](https://github.com/eamodio/vscode-gitlens/wiki/Advanced-Formatting) for details on how to control the lengths.

In your example you could use `${id|8} ${author|20}`  -- you can replace `20` with however many characters of the `author` you want displayed.

Hope that helps!

**Comment by obrejla** [comment]
Cool! That did the trick, thanks a lot!
