### ISSUE TITLE
Git blame is completely fraudulent

### ISSUE THREAD

**Issue by sayauYusen** [eamodio/vscode-gitlens#982]
- GitLens Version: 10.2.1
  
- VSCode Version: 1.42.1
- OS Version: Win 10

Steps to Reproduce:
Step 1. Highlight the section of code you want to change its authorship to your name.
Step 2. Control + ] to insert indentation
Step 3. Save the file.

Now you have changed the author of this block of code from someone else to your name.

*** In order to uphold the integrity of git/git blame/git lens, I strongly advice Git Lens should ignore any format-related code changes from Git blame in the next version.

**Comment by eamodio** [comment]
As I mentioned on #964 -- this is how Git works.
