### ISSUE TITLE
Exclude space/tab/indentation from code-change

### ISSUE THREAD

**Issue by sayauYusen** [eamodio/vscode-gitlens#983]
People can change the authorship of code to whoever they like under the current design. This renders the integrity of Git Lens/Git blame to zero.

Step 1. Highlight the section of code you want to change its authorship to your name.
Step 2. Control + ] to insert indentation
Step 3. Save the file.

Now you have changed the author of this block of code from someone else to your name.

*** In order to uphold the integrity of git/git blame/git lens, I strongly advice Git Lens should ignore any format-related code changes from Git blame in the next version.

**Comment by eamodio** [comment]
@sayauYusen You can set `"gitlens.blame.ignoreWhitespace": true` in your settings if you want to ignore whitespace changes from blames.
