### ISSUE TITLE
Automatic linking to remote issues from references in code comments

### ISSUE THREAD

**Issue by alystair** [eamodio/vscode-gitlens#984]
If I have a comment in a piece of code that contains a `#123` type reference (or `issue#123` if you want a super specific regex?), it should automatically link to appropriate remote (github, gitlab, etc) issue.

There is an [existing extension](https://github.com/dt/ghlink) that sort of does it, but it's infrequently maintained, hacky, and only works for GitHub.

**Comment by eamodio** [comment]
This isn't something that I will likely add myself, but if the community wants to provide a PR I'm certainly open to it -- depending on the complexity and scope of the changes required.

**Comment by alystair** [comment]
Might be implemented via this https://github.com/dt/ghlink/issues/13 - will close for now.
