### ISSUE TITLE
add new lottie file json

### ISSUE THREAD

**Issue by boodeveloper** [eamodio/vscode-gitlens#986]
Issue Type: <b>Bug</b>

add new lottie file json when  view CHANGE file in git  git stop working 

token size bug ?

when click icon plus not view file diff can use.

Extension version: 10.2.1
VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.97GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
Sorry, I'm not sure what the issue here is -- can you explain it in more detail what is happening?

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
