### ISSUE TITLE
Turn off highlight color of change

### ISSUE THREAD

**Issue by bhellema** [eamodio/vscode-gitlens#987]
Is there a setting to turn off the highlighting for the commit?  For example the following block of code has been highlighted by gitlens.  I can't seem to figure out the correct setting to disable this.

![image](https://user-images.githubusercontent.com/6395150/77544589-94870500-6e7f-11ea-9399-66ce8ae374b8.png)

**Comment by eamodio** [comment]
Which highlighting? GitLens doesn't highlight anything unless you are in the file blame mode.

**Comment by eamodio** [comment]
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!
