### ISSUE TITLE
Disable click action on recent change

### ISSUE THREAD

**Issue by danvk** [eamodio/vscode-gitlens#989]
I like seeing the recent change / author annotations on blocks:

![image](https://user-images.githubusercontent.com/98301/77928825-e6140300-7276-11ea-9f58-8b2fbd9f3184.png)

However, I keep finding myself accidentally clicking them, which shifts the entire editor to the right. I'd like to keep the annotations, but disable the click action (or make it harder to accidentally trigger). Is there an option for this?

**Comment by eamodio** [comment]
While you can control what happens when you click on it, you can't currently have it do nothing. That is a good idea.

**Comment by abdusabri** [comment]
I've an early stage working prototype 🙂 

This is how it looks when both Authors and Recent Changes commands are disabled
![both-disabled](https://user-images.githubusercontent.com/25670682/80249264-d15a3d80-8671-11ea-93fb-3ae86f93cfa2.gif)

This is how it looks when only the Authors command is enabled
![authors-enabled](https://user-images.githubusercontent.com/25670682/80249325-e59e3a80-8671-11ea-8ed3-7e68447fdb39.gif)

This is how it looks when only the Recent Changes command is enabled
![recent-change-enabled-2](https://user-images.githubusercontent.com/25670682/80249802-ca7ffa80-8672-11ea-95e8-bcf546f9813b.gif)

The approach I'm thinking about would involve adding to config entries as shown below, and would make them both enabled by default
![config](https://user-images.githubusercontent.com/25670682/80248674-b89d5800-8670-11ea-8077-b23b3d978944.png)

Would that be a good approach to implement this feature?

**Comment by eamodio** [comment]
Awesome! Thanks so much for tackling this! Instead of adding a new `enableCommand` flag, I would suggest just adding `false` to the `command`, so it would be `command: CodeLensCommand | false`. That would make the changes required (especially in the GitLens Settings UI) less.

**Comment by abdusabri** [comment]
Thanks @eamodio for the feedback! Will proceed accordingly.

Based on that, the Settings UI should look something like this?
![image](https://user-images.githubusercontent.com/25670682/80279966-285b2380-8701-11ea-97cd-a34e806fd62a.png)

**Comment by eamodio** [comment]
Yeah, I like that UI (I honestly was thinking about just a _When clicked_ `do nothing` type action in the dropdown -- but I like yours much better). The might be a challenge with it being a combine setting with that UI - since unchecking it would set it to `false` which will affect the dropdown. I'm not in front of a machine atm but it might be fine 😄

**Comment by abdusabri** [comment]
Awesome! Thanks for the feedback! 

I got inspiration from the existing `views.repositories.showBranchComparison` setting. Based on my testing, it seems to be working as expected 😄 

Here is a screen capture for a fully functional implementation 🙂 
![full-flow-4](https://user-images.githubusercontent.com/25670682/80288043-7e49be80-8735-11ea-8e26-506923337750.gif)

**Comment by abdusabri** [comment]
Here is how it responds to parent settings being disabled or enabled
![parent-settings](https://user-images.githubusercontent.com/25670682/80288260-2f9d2400-8737-11ea-831f-83ac2074466f.gif)

**Comment by eamodio** [comment]
@abdusabri Looks great! Awesome work!

**Comment by abdusabri** [comment]
I'm very sorry about the wrong references to this issue 😔, was testing some changes on my fork while working on another issue and didn't realize I had used the wrong issue number 🤦‍♂️. Please ignore

**Comment by eamodio** [comment]
Added in GitLens 11
