### ISSUE TITLE
Ctrl+Z spawns a numerous amount of processes

### ISSUE THREAD

**Issue by GeorgeWells** [eamodio/vscode-gitlens#99]
- GitLens Version: 4.1.2
- VSCode Version: 1.13.1
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. Open an existing file
2. Write something then Ctrl+Z

Lots of processes spawn in the task manager relating to conhost.exe and git.exe.

Amount of processes before Ctrl+Z: 104
Amount of processes after Ctrl+Z 10 times (repeatedly Ctrl+Y & Ctrl+Z): 603

It locks out the CPU at 100%. It also seems to be that the larger amount of text there is involved, more processes are created. I can't replicate this issue when I disable this plugin. I have tried both Git versions 2.13.0 and 2.13.1.2.

**Comment by eamodio** [comment]
@GeorgeWells I just published 4.1.4 that *might* fix this issue -- please let me know and re-open this if not.

**Comment by GeorgeWells** [comment]
@eamodio Seems to be working beautifully, thanks! :)
