### ISSUE TITLE
vs code issue: GitLens was unable to find Git. Please make sure Git is installed. Also ensure that Git is either in the PATH, or that 'git.path' is pointed to its installed location.

### ISSUE THREAD

**Issue by nishixpatel** [eamodio/vscode-gitlens#991]
PLEASE HELP!!
GitLens was unable to find Git. Please make sure Git is installed. Also ensure that Git is either in the PATH, or that 'git.path' is pointed to its installed location.

I think there is a path issue but i didn't change anything on my computer!

 I have a windows computer and am using visual studio code. I can give more info if needed. I am also getting two other errors. My terminal won't launch!! I can't use it at all. 

The terminal shell CWD "C:\Users\Nishi\Desktop\cs111" does not exist

also, i get this

The JAVA_HOME environment variable points to a missing or inaccessible folder (C:\Program Files\Java\jdk1.8.0_102)

Also the folder where i keep all my projects and assignments is not opening. there is an exclamation point next to it and it won't display my projects.

**Comment by GreatThinkTank** [comment]
Hey, I had the same problem and I got the solution.
It is well explained.
You can go to the link and read the article
https://towardsdatascience.com/installing-github-in-visual-studio-code-for-windows-10-6abd3325ab1

It will solve your problem. If problem persists let me know.

**Comment by radubartan** [comment]
The link @TheNoobCodr did not work for me. 
I did a search on Medium and found the same article at this link - [https://towardsdatascience.com/installing-github-in-visual-studio-code-for-windows-10-6abd3325ab1](url)
Thanks @TheNoobCodr for providing that resource - it is a good one.

**Comment by Dev-seongjae98** [comment]
> Hey, I had the same problem and I got the solution.
> It is well explained.
> You can go to the link and read the article
> https://towardsdatascience.com/installing-github-in-visual-studio-code-for-windows-10-6abd3325ab1
> 
> It will solve your problem. If problem persists let me know.

Thank you, very much. I solved my problem. :)
