### ISSUE TITLE
File History breaks with same named files in different folders

### ISSUE THREAD

**Issue by mjmatthiesen** [eamodio/vscode-gitlens#993]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Create a named file with similar contents over several folders.
2. Commit to each file a few times. Delete some, whatever.
3. Open GitLens and the File History.
4. See file history that doesn't match the current file.

Here is an example history:
![image](https://user-images.githubusercontent.com/16603906/78406826-b3dd0b00-75c0-11ea-97e8-3741f624ee0c.png)
Click on the first one and end up in a different folder, different file:
![image](https://user-images.githubusercontent.com/16603906/78406865-d1aa7000-75c0-11ea-9ebc-b717785853b2.png)

Now this may be entirely a git issue and not gitlens related.

Extension version: 10.2.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by eamodio** [comment]
@mjmatthiesen Could you possibly setup an example repo to show this behavior?

**Comment by mjmatthiesen** [comment]
https://github.com/mjmatthiesen/vscode-gitlens-history-bug

Here, this one will do. Open acclaim/index.html or likely many of the other files.

View the file history:
![image](https://user-images.githubusercontent.com/16603906/79701435-5a303e00-825a-11ea-906d-acd9dc011e8e.png)

Meanwhile the changes on github:
![image](https://user-images.githubusercontent.com/16603906/79701445-6caa7780-825a-11ea-82ce-9a57d76669e9.png)

And using gitk:
![image](https://user-images.githubusercontent.com/16603906/79701549-41745800-825b-11ea-81f2-d6dc24c9d068.png)

Or git log on the file:
![image](https://user-images.githubusercontent.com/16603906/79701586-85fff380-825b-11ea-8dc2-e3151e3f415f.png)

**Comment by mjmatthiesen** [comment]
?

**Comment by mjmatthiesen** [comment]
Hi,

Any movement on this? It's a pretty easily reproducible issue.

**Comment by mjmatthiesen** [comment]
This appears to be resolved with the newest version
