### ISSUE TITLE
`gitlens.views.repositories.autoReveal` setting not working

### ISSUE THREAD

**Issue by garyking** [eamodio/vscode-gitlens#994]
- GitLens Version: 10.2.1
  
- VSCode Version: 1.43.2
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Set `gitlens.views.repositories.autoReveal` to `false`, in your global VSC settings.
2. In a VSC workspace, that has a Git repo, open a file from another workspace, that also has a Git repo.
3. The second repo will appear in Gitlens -> Repositories view, even though the setting is disabled.

This setting has never worked for me. Is there something I'm doing wrong? I don't want repositories to be automatically added to the Gitlens -> Repositories view.

**Comment by eamodio** [comment]
That setting isn't for controlling that behavior -- it is just for controlling whether or not the selected repo in the _Repositories_ view changes with the currently active editor or not.

Unfortunately, what you are looking for doesn't exist today, but https://github.com/eamodio/vscode-gitlens/issues/995 is the feature request for it.
