### ISSUE TITLE
Rename branch should show existing name highlighted

### ISSUE THREAD

**Issue by jar240** [eamodio/vscode-gitlens#996]
Hi there, when renaming a branch, the UI should show the existing name highlighted instead of an empty input box.

Current:
![image](https://user-images.githubusercontent.com/6794643/78601899-8774f900-7823-11ea-938e-32e529dc7d5d.png)

Desired:
![image](https://user-images.githubusercontent.com/6794643/78602045-c30fc300-7823-11ea-8999-d473ab7070e1.png)

Thanks.

**Comment by eamodio** [comment]
Fixed in GitLens 11
