### ISSUE TITLE
How to toggle off "Explore Repository from Revision"?

### ISSUE THREAD

**Issue by inliquid** [eamodio/vscode-gitlens#997]
After you accidentally click on this folder icon, 
![изображение](https://user-images.githubusercontent.com/6797881/78650559-c197d680-78c7-11ea-954a-b067cf35df13.png)

there seems to be no way to revert it at all. At the same time it causes language server crashes (at least for Go) because it does not support `gitlens` URIs. Your workspace becomes totally broken.

**Comment by eamodio** [comment]
Unfortunately there isn't a way currently to turn this off, but I have removed that command in that toolbar in the next version.

Although I would recommend filing an issue with the Go vscode extension, since it should definitely not crash if it sees a Uri it doesn't recognize.

**Comment by netpoe** [comment]
I'm looking for the same feature. Currently, I needed to close the current workspace in order to revert the file explorer. 

I thought this feature worked as a `git checkout`? 🤔 
I still don't understand the purpose of this feature, though.

**Comment by eamodio** [comment]
Fixed in GitLens 11
