### ISSUE TITLE
VS Code Remote not showing git colors

### ISSUE THREAD

**Issue by AJLiu** [eamodio/vscode-gitlens#999]
- `GitLens` Version: 10.2.1
- `Remote Development` Version: 0.20.0
- `Remote - SSH` Version: 0.51.0
  
- VSCode Version: 1.44.0
- OS Version: Windows_NT x64 10.0.18363
- OS Version (Remote): Linux x64 5.3.0-46-generic

I have a desktop running Ubuntu 18.04 and have been connecting to it from a separate windows machine to develop. When I open a workspace on the linux machine, I get the expected behavior where modified files and new files are colored in the explorer, and the gutter shows lines added, changed, or removed. 

However if I try to open the same workspace remotely, it seems that none of these features are working, and I have verified that things work correctly if I open a local workspace on my windows machine.

Here is a screenshot of VS Code running on my linux machine.
<img src="https://user-images.githubusercontent.com/3196570/79187390-1799dc00-7dea-11ea-8580-8461e1d3ced7.png" width="600px">

Here is what I see when I try to use the ssh remote connection to open the above workspace.
<img src="https://user-images.githubusercontent.com/3196570/79187378-11a3fb00-7dea-11ea-847d-6ea2af2eecaf.png" width="600px">

I don't see any discernible lines in the log output aside from the following in the `Log (Remote Extension)` output.
```
[2020-04-14 00:30:13.827] [exthost] [info] Extension 'eamodio.gitlens' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
[2020-04-14 00:30:13.898] [exthost] [info] Extension 'ms-python.python' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
```

Has anyone dealt with this before? I looked around, but I'm struggling to find information as to whether this is a bug, a limitation with remote development, or if my editor is simply misconfigured...

**Comment by eamodio** [comment]
GitLens doesn't provide the git color decorations -- I would suggest you open this issue on the vscode repo.
